package ev

import "github.com/raitucarp/gomix/icons"

func EvActivity() icons.IsIcon               { return newIcon(fillIcon, "activity") }
func EvAlertCircle() icons.IsIcon            { return newIcon(fillIcon, "alert-circle") }
func EvAlertTriangle() icons.IsIcon          { return newIcon(fillIcon, "alert-triangle") }
func EvArchive() icons.IsIcon                { return newIcon(fillIcon, "archive") }
func EvArrowBack() icons.IsIcon              { return newIcon(fillIcon, "arrow-back") }
func EvArrowCircleDown() icons.IsIcon        { return newIcon(fillIcon, "arrow-circle-down") }
func EvArrowCircleLeft() icons.IsIcon        { return newIcon(fillIcon, "arrow-circle-left") }
func EvArrowCircleRight() icons.IsIcon       { return newIcon(fillIcon, "arrow-circle-right") }
func EvArrowCircleUp() icons.IsIcon          { return newIcon(fillIcon, "arrow-circle-up") }
func EvArrowDown() icons.IsIcon              { return newIcon(fillIcon, "arrow-down") }
func EvArrowDownward() icons.IsIcon          { return newIcon(fillIcon, "arrow-downward") }
func EvArrowForward() icons.IsIcon           { return newIcon(fillIcon, "arrow-forward") }
func EvArrowIosBack() icons.IsIcon           { return newIcon(fillIcon, "arrow-ios-back") }
func EvArrowIosDownward() icons.IsIcon       { return newIcon(fillIcon, "arrow-ios-downward") }
func EvArrowIosForward() icons.IsIcon        { return newIcon(fillIcon, "arrow-ios-forward") }
func EvArrowIosUpward() icons.IsIcon         { return newIcon(fillIcon, "arrow-ios-upward") }
func EvArrowLeft() icons.IsIcon              { return newIcon(fillIcon, "arrow-left") }
func EvArrowRight() icons.IsIcon             { return newIcon(fillIcon, "arrow-right") }
func EvArrowUp() icons.IsIcon                { return newIcon(fillIcon, "arrow-up") }
func EvArrowUpward() icons.IsIcon            { return newIcon(fillIcon, "arrow-upward") }
func EvArrowheadDown() icons.IsIcon          { return newIcon(fillIcon, "arrowhead-down") }
func EvArrowheadLeft() icons.IsIcon          { return newIcon(fillIcon, "arrowhead-left") }
func EvArrowheadRight() icons.IsIcon         { return newIcon(fillIcon, "arrowhead-right") }
func EvArrowheadUp() icons.IsIcon            { return newIcon(fillIcon, "arrowhead-up") }
func EvAt() icons.IsIcon                     { return newIcon(fillIcon, "at") }
func EvAttach2() icons.IsIcon                { return newIcon(fillIcon, "attach-2") }
func EvAttach() icons.IsIcon                 { return newIcon(fillIcon, "attach") }
func EvAward() icons.IsIcon                  { return newIcon(fillIcon, "award") }
func EvBackspace() icons.IsIcon              { return newIcon(fillIcon, "backspace") }
func EvBarChart2() icons.IsIcon              { return newIcon(fillIcon, "bar-chart-2") }
func EvBarChart() icons.IsIcon               { return newIcon(fillIcon, "bar-chart") }
func EvBattery() icons.IsIcon                { return newIcon(fillIcon, "battery") }
func EvBehance() icons.IsIcon                { return newIcon(fillIcon, "behance") }
func EvBellOff() icons.IsIcon                { return newIcon(fillIcon, "bell-off") }
func EvBell() icons.IsIcon                   { return newIcon(fillIcon, "bell") }
func EvBluetooth() icons.IsIcon              { return newIcon(fillIcon, "bluetooth") }
func EvBookOpen() icons.IsIcon               { return newIcon(fillIcon, "book-open") }
func EvBook() icons.IsIcon                   { return newIcon(fillIcon, "book") }
func EvBookmark() icons.IsIcon               { return newIcon(fillIcon, "bookmark") }
func EvBriefcase() icons.IsIcon              { return newIcon(fillIcon, "briefcase") }
func EvBrowser() icons.IsIcon                { return newIcon(fillIcon, "browser") }
func EvBrush() icons.IsIcon                  { return newIcon(fillIcon, "brush") }
func EvBulb() icons.IsIcon                   { return newIcon(fillIcon, "bulb") }
func EvCalendar() icons.IsIcon               { return newIcon(fillIcon, "calendar") }
func EvCamera() icons.IsIcon                 { return newIcon(fillIcon, "camera") }
func EvCar() icons.IsIcon                    { return newIcon(fillIcon, "car") }
func EvCast() icons.IsIcon                   { return newIcon(fillIcon, "cast") }
func EvCharging() icons.IsIcon               { return newIcon(fillIcon, "charging") }
func EvCheckmarkCircle2() icons.IsIcon       { return newIcon(fillIcon, "checkmark-circle-2") }
func EvCheckmarkCircle() icons.IsIcon        { return newIcon(fillIcon, "checkmark-circle") }
func EvCheckmarkSquare2() icons.IsIcon       { return newIcon(fillIcon, "checkmark-square-2") }
func EvCheckmarkSquare() icons.IsIcon        { return newIcon(fillIcon, "checkmark-square") }
func EvCheckmark() icons.IsIcon              { return newIcon(fillIcon, "checkmark") }
func EvChevronDown() icons.IsIcon            { return newIcon(fillIcon, "chevron-down") }
func EvChevronLeft() icons.IsIcon            { return newIcon(fillIcon, "chevron-left") }
func EvChevronRight() icons.IsIcon           { return newIcon(fillIcon, "chevron-right") }
func EvChevronUp() icons.IsIcon              { return newIcon(fillIcon, "chevron-up") }
func EvClipboard() icons.IsIcon              { return newIcon(fillIcon, "clipboard") }
func EvClock() icons.IsIcon                  { return newIcon(fillIcon, "clock") }
func EvCloseCircle() icons.IsIcon            { return newIcon(fillIcon, "close-circle") }
func EvCloseSquare() icons.IsIcon            { return newIcon(fillIcon, "close-square") }
func EvClose() icons.IsIcon                  { return newIcon(fillIcon, "close") }
func EvCloudDownload() icons.IsIcon          { return newIcon(fillIcon, "cloud-download") }
func EvCloudUpload() icons.IsIcon            { return newIcon(fillIcon, "cloud-upload") }
func EvCodeDownload() icons.IsIcon           { return newIcon(fillIcon, "code-download") }
func EvCode() icons.IsIcon                   { return newIcon(fillIcon, "code") }
func EvCollapse() icons.IsIcon               { return newIcon(fillIcon, "collapse") }
func EvColorPalette() icons.IsIcon           { return newIcon(fillIcon, "color-palette") }
func EvColorPicker() icons.IsIcon            { return newIcon(fillIcon, "color-picker") }
func EvCompass() icons.IsIcon                { return newIcon(fillIcon, "compass") }
func EvCopy() icons.IsIcon                   { return newIcon(fillIcon, "copy") }
func EvCornerDownLeft() icons.IsIcon         { return newIcon(fillIcon, "corner-down-left") }
func EvCornerDownRight() icons.IsIcon        { return newIcon(fillIcon, "corner-down-right") }
func EvCornerLeftDown() icons.IsIcon         { return newIcon(fillIcon, "corner-left-down") }
func EvCornerLeftUp() icons.IsIcon           { return newIcon(fillIcon, "corner-left-up") }
func EvCornerRightDown() icons.IsIcon        { return newIcon(fillIcon, "corner-right-down") }
func EvCornerRightUp() icons.IsIcon          { return newIcon(fillIcon, "corner-right-up") }
func EvCornerUpLeft() icons.IsIcon           { return newIcon(fillIcon, "corner-up-left") }
func EvCornerUpRight() icons.IsIcon          { return newIcon(fillIcon, "corner-up-right") }
func EvCreditCard() icons.IsIcon             { return newIcon(fillIcon, "credit-card") }
func EvCrop() icons.IsIcon                   { return newIcon(fillIcon, "crop") }
func EvCube() icons.IsIcon                   { return newIcon(fillIcon, "cube") }
func EvDiagonalArrowLeftDown() icons.IsIcon  { return newIcon(fillIcon, "diagonal-arrow-left-down") }
func EvDiagonalArrowLeftUp() icons.IsIcon    { return newIcon(fillIcon, "diagonal-arrow-left-up") }
func EvDiagonalArrowRightDown() icons.IsIcon { return newIcon(fillIcon, "diagonal-arrow-right-down") }
func EvDiagonalArrowRightUp() icons.IsIcon   { return newIcon(fillIcon, "diagonal-arrow-right-up") }
func EvDoneAll() icons.IsIcon                { return newIcon(fillIcon, "done-all") }
func EvDownload() icons.IsIcon               { return newIcon(fillIcon, "download") }
func EvDropletOff() icons.IsIcon             { return newIcon(fillIcon, "droplet-off") }
func EvDroplet() icons.IsIcon                { return newIcon(fillIcon, "droplet") }
func EvEdit2() icons.IsIcon                  { return newIcon(fillIcon, "edit-2") }
func EvEdit() icons.IsIcon                   { return newIcon(fillIcon, "edit") }
func EvEmail() icons.IsIcon                  { return newIcon(fillIcon, "email") }
func EvExpand() icons.IsIcon                 { return newIcon(fillIcon, "expand") }
func EvExternalLink() icons.IsIcon           { return newIcon(fillIcon, "external-link") }
func EvEyeOff2() icons.IsIcon                { return newIcon(fillIcon, "eye-off-2") }
func EvEyeOff() icons.IsIcon                 { return newIcon(fillIcon, "eye-off") }
func EvEye() icons.IsIcon                    { return newIcon(fillIcon, "eye") }
func EvFacebook() icons.IsIcon               { return newIcon(fillIcon, "facebook") }
func EvFileAdd() icons.IsIcon                { return newIcon(fillIcon, "file-add") }
func EvFileRemove() icons.IsIcon             { return newIcon(fillIcon, "file-remove") }
func EvFileText() icons.IsIcon               { return newIcon(fillIcon, "file-text") }
func EvFile() icons.IsIcon                   { return newIcon(fillIcon, "file") }
func EvFilm() icons.IsIcon                   { return newIcon(fillIcon, "film") }
func EvFlag() icons.IsIcon                   { return newIcon(fillIcon, "flag") }
func EvFlashOff() icons.IsIcon               { return newIcon(fillIcon, "flash-off") }
func EvFlash() icons.IsIcon                  { return newIcon(fillIcon, "flash") }
func EvFlip2() icons.IsIcon                  { return newIcon(fillIcon, "flip-2") }
func EvFlip() icons.IsIcon                   { return newIcon(fillIcon, "flip") }
func EvFolderAdd() icons.IsIcon              { return newIcon(fillIcon, "folder-add") }
func EvFolderRemove() icons.IsIcon           { return newIcon(fillIcon, "folder-remove") }
func EvFolder() icons.IsIcon                 { return newIcon(fillIcon, "folder") }
func EvFunnel() icons.IsIcon                 { return newIcon(fillIcon, "funnel") }
func EvGift() icons.IsIcon                   { return newIcon(fillIcon, "gift") }
func EvGithub() icons.IsIcon                 { return newIcon(fillIcon, "github") }
func EvGlobe2() icons.IsIcon                 { return newIcon(fillIcon, "globe-2") }
func EvGlobe3() icons.IsIcon                 { return newIcon(fillIcon, "globe-3") }
func EvGlobe() icons.IsIcon                  { return newIcon(fillIcon, "globe") }
func EvGoogle() icons.IsIcon                 { return newIcon(fillIcon, "google") }
func EvGrid() icons.IsIcon                   { return newIcon(fillIcon, "grid") }
func EvHardDrive() icons.IsIcon              { return newIcon(fillIcon, "hard-drive") }
func EvHash() icons.IsIcon                   { return newIcon(fillIcon, "hash") }
func EvHeadphones() icons.IsIcon             { return newIcon(fillIcon, "headphones") }
func EvHeart() icons.IsIcon                  { return newIcon(fillIcon, "heart") }
func EvHome() icons.IsIcon                   { return newIcon(fillIcon, "home") }
func EvImage2() icons.IsIcon                 { return newIcon(fillIcon, "image-2") }
func EvImage() icons.IsIcon                  { return newIcon(fillIcon, "image") }
func EvInbox() icons.IsIcon                  { return newIcon(fillIcon, "inbox") }
func EvInfo() icons.IsIcon                   { return newIcon(fillIcon, "info") }
func EvKeypad() icons.IsIcon                 { return newIcon(fillIcon, "keypad") }
func EvLayers() icons.IsIcon                 { return newIcon(fillIcon, "layers") }
func EvLayout() icons.IsIcon                 { return newIcon(fillIcon, "layout") }
func EvLink2() icons.IsIcon                  { return newIcon(fillIcon, "link-2") }
func EvLink() icons.IsIcon                   { return newIcon(fillIcon, "link") }
func EvLinkedin() icons.IsIcon               { return newIcon(fillIcon, "linkedin") }
func EvList() icons.IsIcon                   { return newIcon(fillIcon, "list") }
func EvLock() icons.IsIcon                   { return newIcon(fillIcon, "lock") }
func EvLogIn() icons.IsIcon                  { return newIcon(fillIcon, "log-in") }
func EvLogOut() icons.IsIcon                 { return newIcon(fillIcon, "log-out") }
func EvMap() icons.IsIcon                    { return newIcon(fillIcon, "map") }
func EvMaximize() icons.IsIcon               { return newIcon(fillIcon, "maximize") }
func EvMenu2() icons.IsIcon                  { return newIcon(fillIcon, "menu-2") }
func EvMenuArrow() icons.IsIcon              { return newIcon(fillIcon, "menu-arrow") }
func EvMenu() icons.IsIcon                   { return newIcon(fillIcon, "menu") }
func EvMessageCircle() icons.IsIcon          { return newIcon(fillIcon, "message-circle") }
func EvMessageSquare() icons.IsIcon          { return newIcon(fillIcon, "message-square") }
func EvMicOff() icons.IsIcon                 { return newIcon(fillIcon, "mic-off") }
func EvMic() icons.IsIcon                    { return newIcon(fillIcon, "mic") }
func EvMinimize() icons.IsIcon               { return newIcon(fillIcon, "minimize") }
func EvMinusCircle() icons.IsIcon            { return newIcon(fillIcon, "minus-circle") }
func EvMinusSquare() icons.IsIcon            { return newIcon(fillIcon, "minus-square") }
func EvMinus() icons.IsIcon                  { return newIcon(fillIcon, "minus") }
func EvMonitor() icons.IsIcon                { return newIcon(fillIcon, "monitor") }
func EvMoon() icons.IsIcon                   { return newIcon(fillIcon, "moon") }
func EvMoreHorizontal() icons.IsIcon         { return newIcon(fillIcon, "more-horizontal") }
func EvMoreVertical() icons.IsIcon           { return newIcon(fillIcon, "more-vertical") }
func EvMove() icons.IsIcon                   { return newIcon(fillIcon, "move") }
func EvMusic() icons.IsIcon                  { return newIcon(fillIcon, "music") }
func EvNavigation2() icons.IsIcon            { return newIcon(fillIcon, "navigation-2") }
func EvNavigation() icons.IsIcon             { return newIcon(fillIcon, "navigation") }
func EvNpm() icons.IsIcon                    { return newIcon(fillIcon, "npm") }
func EvOptions2() icons.IsIcon               { return newIcon(fillIcon, "options-2") }
func EvOptions() icons.IsIcon                { return newIcon(fillIcon, "options") }
func EvPantone() icons.IsIcon                { return newIcon(fillIcon, "pantone") }
func EvPaperPlane() icons.IsIcon             { return newIcon(fillIcon, "paper-plane") }
func EvPauseCircle() icons.IsIcon            { return newIcon(fillIcon, "pause-circle") }
func EvPeople() icons.IsIcon                 { return newIcon(fillIcon, "people") }
func EvPercent() icons.IsIcon                { return newIcon(fillIcon, "percent") }
func EvPersonAdd() icons.IsIcon              { return newIcon(fillIcon, "person-add") }
func EvPersonDelete() icons.IsIcon           { return newIcon(fillIcon, "person-delete") }
func EvPersonDone() icons.IsIcon             { return newIcon(fillIcon, "person-done") }
func EvPersonRemove() icons.IsIcon           { return newIcon(fillIcon, "person-remove") }
func EvPerson() icons.IsIcon                 { return newIcon(fillIcon, "person") }
func EvPhoneCall() icons.IsIcon              { return newIcon(fillIcon, "phone-call") }
func EvPhoneMissed() icons.IsIcon            { return newIcon(fillIcon, "phone-missed") }
func EvPhoneOff() icons.IsIcon               { return newIcon(fillIcon, "phone-off") }
func EvPhone() icons.IsIcon                  { return newIcon(fillIcon, "phone") }
func EvPieChart2() icons.IsIcon              { return newIcon(fillIcon, "pie-chart-2") }
func EvPieChart() icons.IsIcon               { return newIcon(fillIcon, "pie-chart") }
func EvPin() icons.IsIcon                    { return newIcon(fillIcon, "pin") }
func EvPlayCircle() icons.IsIcon             { return newIcon(fillIcon, "play-circle") }
func EvPlusCircle() icons.IsIcon             { return newIcon(fillIcon, "plus-circle") }
func EvPlusSquare() icons.IsIcon             { return newIcon(fillIcon, "plus-square") }
func EvPlus() icons.IsIcon                   { return newIcon(fillIcon, "plus") }
func EvPower() icons.IsIcon                  { return newIcon(fillIcon, "power") }
func EvPricetags() icons.IsIcon              { return newIcon(fillIcon, "pricetags") }
func EvPrinter() icons.IsIcon                { return newIcon(fillIcon, "printer") }
func EvQuestionMarkCircle() icons.IsIcon     { return newIcon(fillIcon, "question-mark-circle") }
func EvQuestionMark() icons.IsIcon           { return newIcon(fillIcon, "question-mark") }
func EvRadioButtonOff() icons.IsIcon         { return newIcon(fillIcon, "radio-button-off") }
func EvRadioButtonOn() icons.IsIcon          { return newIcon(fillIcon, "radio-button-on") }
func EvRadio() icons.IsIcon                  { return newIcon(fillIcon, "radio") }
func EvRecording() icons.IsIcon              { return newIcon(fillIcon, "recording") }
func EvRefresh() icons.IsIcon                { return newIcon(fillIcon, "refresh") }
func EvRepeat() icons.IsIcon                 { return newIcon(fillIcon, "repeat") }
func EvRewindLeft() icons.IsIcon             { return newIcon(fillIcon, "rewind-left") }
func EvRewindRight() icons.IsIcon            { return newIcon(fillIcon, "rewind-right") }
func EvSave() icons.IsIcon                   { return newIcon(fillIcon, "save") }
func EvScissors() icons.IsIcon               { return newIcon(fillIcon, "scissors") }
func EvSearch() icons.IsIcon                 { return newIcon(fillIcon, "search") }
func EvSettings2() icons.IsIcon              { return newIcon(fillIcon, "settings-2") }
func EvSettings() icons.IsIcon               { return newIcon(fillIcon, "settings") }
func EvShake() icons.IsIcon                  { return newIcon(fillIcon, "shake") }
func EvShare() icons.IsIcon                  { return newIcon(fillIcon, "share") }
func EvShieldOff() icons.IsIcon              { return newIcon(fillIcon, "shield-off") }
func EvShield() icons.IsIcon                 { return newIcon(fillIcon, "shield") }
func EvShoppingBag() icons.IsIcon            { return newIcon(fillIcon, "shopping-bag") }
func EvShoppingCart() icons.IsIcon           { return newIcon(fillIcon, "shopping-cart") }
func EvShuffle2() icons.IsIcon               { return newIcon(fillIcon, "shuffle-2") }
func EvShuffle() icons.IsIcon                { return newIcon(fillIcon, "shuffle") }
func EvSkipBack() icons.IsIcon               { return newIcon(fillIcon, "skip-back") }
func EvSkipForward() icons.IsIcon            { return newIcon(fillIcon, "skip-forward") }
func EvSlash() icons.IsIcon                  { return newIcon(fillIcon, "slash") }
func EvSmartphone() icons.IsIcon             { return newIcon(fillIcon, "smartphone") }
func EvSmilingFace() icons.IsIcon            { return newIcon(fillIcon, "smiling-face") }
func EvSpeaker() icons.IsIcon                { return newIcon(fillIcon, "speaker") }
func EvSquare() icons.IsIcon                 { return newIcon(fillIcon, "square") }
func EvStar() icons.IsIcon                   { return newIcon(fillIcon, "star") }
func EvStopCircle() icons.IsIcon             { return newIcon(fillIcon, "stop-circle") }
func EvSun() icons.IsIcon                    { return newIcon(fillIcon, "sun") }
func EvSwap() icons.IsIcon                   { return newIcon(fillIcon, "swap") }
func EvSync() icons.IsIcon                   { return newIcon(fillIcon, "sync") }
func EvText() icons.IsIcon                   { return newIcon(fillIcon, "text") }
func EvThermometerMinus() icons.IsIcon       { return newIcon(fillIcon, "thermometer-minus") }
func EvThermometerPlus() icons.IsIcon        { return newIcon(fillIcon, "thermometer-plus") }
func EvThermometer() icons.IsIcon            { return newIcon(fillIcon, "thermometer") }
func EvToggleLeft() icons.IsIcon             { return newIcon(fillIcon, "toggle-left") }
func EvToggleRight() icons.IsIcon            { return newIcon(fillIcon, "toggle-right") }
func EvTrash2() icons.IsIcon                 { return newIcon(fillIcon, "trash-2") }
func EvTrash() icons.IsIcon                  { return newIcon(fillIcon, "trash") }
func EvTrendingDown() icons.IsIcon           { return newIcon(fillIcon, "trending-down") }
func EvTrendingUp() icons.IsIcon             { return newIcon(fillIcon, "trending-up") }
func EvTv() icons.IsIcon                     { return newIcon(fillIcon, "tv") }
func EvTwitter() icons.IsIcon                { return newIcon(fillIcon, "twitter") }
func EvUmbrella() icons.IsIcon               { return newIcon(fillIcon, "umbrella") }
func EvUndo() icons.IsIcon                   { return newIcon(fillIcon, "undo") }
func EvUnlock() icons.IsIcon                 { return newIcon(fillIcon, "unlock") }
func EvUpload() icons.IsIcon                 { return newIcon(fillIcon, "upload") }
func EvVideoOff() icons.IsIcon               { return newIcon(fillIcon, "video-off") }
func EvVideo() icons.IsIcon                  { return newIcon(fillIcon, "video") }
func EvVolumeDown() icons.IsIcon             { return newIcon(fillIcon, "volume-down") }
func EvVolumeMute() icons.IsIcon             { return newIcon(fillIcon, "volume-mute") }
func EvVolumeOff() icons.IsIcon              { return newIcon(fillIcon, "volume-off") }
func EvVolumeUp() icons.IsIcon               { return newIcon(fillIcon, "volume-up") }
func EvWifiOff() icons.IsIcon                { return newIcon(fillIcon, "wifi-off") }
func EvWifi() icons.IsIcon                   { return newIcon(fillIcon, "wifi") }
