package gvi

import "github.com/raitucarp/gomix/icons"

func Gvi18F() icons.IsIcon                { return newIcon("18f") }
func Gvi540Fedapi() icons.IsIcon          { return newIcon("540-fedapi") }
func Gvi540() icons.IsIcon                { return newIcon("540") }
func GviAirplane() icons.IsIcon           { return newIcon("airplane") }
func GviAmbulance() icons.IsIcon          { return newIcon("ambulance") }
func GviAmmo() icons.IsIcon               { return newIcon("ammo") }
func GviAnchor() icons.IsIcon             { return newIcon("anchor") }
func GviAstronautHelmet() icons.IsIcon    { return newIcon("astronaut-helmet") }
func GviBalance() icons.IsIcon            { return newIcon("balance") }
func GviBaldEagle() icons.IsIcon          { return newIcon("bald-eagle") }
func GviBarChart() icons.IsIcon           { return newIcon("bar-chart") }
func GviBarcode() icons.IsIcon            { return newIcon("barcode") }
func GviBiohazard() icons.IsIcon          { return newIcon("biohazard") }
func GviBook() icons.IsIcon               { return newIcon("book") }
func GviBriefcase() icons.IsIcon          { return newIcon("briefcase") }
func GviBuilding() icons.IsIcon           { return newIcon("building") }
func GviBusFront() icons.IsIcon           { return newIcon("bus-front") }
func GviCacO() icons.IsIcon               { return newIcon("cac-o") }
func GviCac() icons.IsIcon                { return newIcon("cac") }
func GviCapitol() icons.IsIcon            { return newIcon("capitol") }
func GviCheckSquareO() icons.IsIcon       { return newIcon("check-square-o") }
func GviCheck() icons.IsIcon              { return newIcon("check") }
func GviClockO() icons.IsIcon             { return newIcon("clock-o") }
func GviCloudO() icons.IsIcon             { return newIcon("cloud-o") }
func GviCloud() icons.IsIcon              { return newIcon("cloud") }
func GviCode() icons.IsIcon               { return newIcon("code") }
func GviCog() icons.IsIcon                { return newIcon("cog") }
func GviCogs() icons.IsIcon               { return newIcon("cogs") }
func GviComment() icons.IsIcon            { return newIcon("comment") }
func GviComments() icons.IsIcon           { return newIcon("comments") }
func GviComputer() icons.IsIcon           { return newIcon("computer") }
func GviConstruction() icons.IsIcon       { return newIcon("construction") }
func GviDatabase() icons.IsIcon           { return newIcon("database") }
func GviDcFlag() icons.IsIcon             { return newIcon("dc-flag") }
func GviDc() icons.IsIcon                 { return newIcon("dc") }
func GviDna() icons.IsIcon                { return newIcon("dna") }
func GviDogtags() icons.IsIcon            { return newIcon("dogtags") }
func GviDonkey() icons.IsIcon             { return newIcon("donkey") }
func GviDrone() icons.IsIcon              { return newIcon("drone") }
func GviElephant() icons.IsIcon           { return newIcon("elephant") }
func GviFactory() icons.IsIcon            { return newIcon("factory") }
func GviFileContractO() icons.IsIcon      { return newIcon("file-contract-o") }
func GviFileExcelO() icons.IsIcon         { return newIcon("file-excel-o") }
func GviFileExcel() icons.IsIcon          { return newIcon("file-excel") }
func GviFileO() icons.IsIcon              { return newIcon("file-o") }
func GviFileTextO() icons.IsIcon          { return newIcon("file-text-o") }
func GviFileText() icons.IsIcon           { return newIcon("file-text") }
func GviFileWordO() icons.IsIcon          { return newIcon("file-word-o") }
func GviFileWord() icons.IsIcon           { return newIcon("file-word") }
func GviFile() icons.IsIcon               { return newIcon("file") }
func GviFingerprint() icons.IsIcon        { return newIcon("fingerprint") }
func GviFolderMisc() icons.IsIcon         { return newIcon("folder-misc") }
func GviFolder() icons.IsIcon             { return newIcon("folder") }
func GviGavel() icons.IsIcon              { return newIcon("gavel") }
func GviGun() icons.IsIcon                { return newIcon("gun") }
func GviHandshake() icons.IsIcon          { return newIcon("handshake") }
func GviHardHat() icons.IsIcon            { return newIcon("hard-hat") }
func GviHeartbeat() icons.IsIcon          { return newIcon("heartbeat") }
func GviHelicopter() icons.IsIcon         { return newIcon("helicopter") }
func GviJeffersonMemorial() icons.IsIcon  { return newIcon("jefferson-memorial") }
func GviJet() icons.IsIcon                { return newIcon("jet") }
func GviKey() icons.IsIcon                { return newIcon("key") }
func GviLeaf() icons.IsIcon               { return newIcon("leaf") }
func GviLibertyBell() icons.IsIcon        { return newIcon("liberty-bell") }
func GviLightbulb() icons.IsIcon          { return newIcon("lightbulb") }
func GviLincolnMemorial() icons.IsIcon    { return newIcon("lincoln-memorial") }
func GviLineChart() icons.IsIcon          { return newIcon("line-chart") }
func GviLock() icons.IsIcon               { return newIcon("lock") }
func GviLogoGovicons() icons.IsIcon       { return newIcon("logo-govicons") }
func GviMedalCircle() icons.IsIcon        { return newIcon("medal-circle") }
func GviMedalStar() icons.IsIcon          { return newIcon("medal-star") }
func GviMedkit() icons.IsIcon             { return newIcon("medkit") }
func GviMetroFront() icons.IsIcon         { return newIcon("metro-front") }
func GviMicroscope() icons.IsIcon         { return newIcon("microscope") }
func GviMissile() icons.IsIcon            { return newIcon("missile") }
func GviMobile() icons.IsIcon             { return newIcon("mobile") }
func GviMoney() icons.IsIcon              { return newIcon("money") }
func GviNuclearPlant() icons.IsIcon       { return newIcon("nuclear-plant") }
func GviPallet() icons.IsIcon             { return newIcon("pallet") }
func GviPentagon() icons.IsIcon           { return newIcon("pentagon") }
func GviPieChart() icons.IsIcon           { return newIcon("pie-chart") }
func GviPoisonBottle() icons.IsIcon       { return newIcon("poison-bottle") }
func GviPoison() icons.IsIcon             { return newIcon("poison") }
func GviPresenter() icons.IsIcon          { return newIcon("presenter") }
func GviRadar() icons.IsIcon              { return newIcon("radar") }
func GviRadioactive() icons.IsIcon        { return newIcon("radioactive") }
func GviRecycle() icons.IsIcon            { return newIcon("recycle") }
func GviReticleCrosshair() icons.IsIcon   { return newIcon("reticle-crosshair") }
func GviReticleDot() icons.IsIcon         { return newIcon("reticle-dot") }
func GviRibbon() icons.IsIcon             { return newIcon("ribbon") }
func GviRoadBarricade() icons.IsIcon      { return newIcon("road-barricade") }
func GviRoadSign() icons.IsIcon           { return newIcon("road-sign") }
func GviRoad() icons.IsIcon               { return newIcon("road") }
func GviRuler() icons.IsIcon              { return newIcon("ruler") }
func GviSatellite() icons.IsIcon          { return newIcon("satellite") }
func GviScript() icons.IsIcon             { return newIcon("script") }
func GviSearch() icons.IsIcon             { return newIcon("search") }
func GviSecurityCamera() icons.IsIcon     { return newIcon("security-camera") }
func GviShieldO() icons.IsIcon            { return newIcon("shield-o") }
func GviShield() icons.IsIcon             { return newIcon("shield") }
func GviShipFront() icons.IsIcon          { return newIcon("ship-front") }
func GviSignal() icons.IsIcon             { return newIcon("signal") }
func GviSpaceShuttle() icons.IsIcon       { return newIcon("space-shuttle") }
func GviStar() icons.IsIcon               { return newIcon("star") }
func GviStatueOfLiberty() icons.IsIcon    { return newIcon("statue-of-liberty") }
func GviStethoscope() icons.IsIcon        { return newIcon("stethoscope") }
func GviSub() icons.IsIcon                { return newIcon("sub") }
func GviTable() icons.IsIcon              { return newIcon("table") }
func GviTables() icons.IsIcon             { return newIcon("tables") }
func GviTablet() icons.IsIcon             { return newIcon("tablet") }
func GviTank() icons.IsIcon               { return newIcon("tank") }
func GviTextile() icons.IsIcon            { return newIcon("textile") }
func GviTimes() icons.IsIcon              { return newIcon("times") }
func GviTools() icons.IsIcon              { return newIcon("tools") }
func GviTrainFront() icons.IsIcon         { return newIcon("train-front") }
func GviTruckFront() icons.IsIcon         { return newIcon("truck-front") }
func GviTruck() icons.IsIcon              { return newIcon("truck") }
func GviUnlock() icons.IsIcon             { return newIcon("unlock") }
func GviUsFlagStraight() icons.IsIcon     { return newIcon("us-flag-straight") }
func GviUsFlagWavy() icons.IsIcon         { return newIcon("us-flag-wavy") }
func GviUsMap() icons.IsIcon              { return newIcon("us-map") }
func GviUsShield() icons.IsIcon           { return newIcon("us-shield") }
func GviUsTopHat() icons.IsIcon           { return newIcon("us-top-hat") }
func GviUsd() icons.IsIcon                { return newIcon("usd") }
func GviUserGraduate() icons.IsIcon       { return newIcon("user-graduate") }
func GviUserMilitary() icons.IsIcon       { return newIcon("user-military") }
func GviUserPolitician() icons.IsIcon     { return newIcon("user-politician") }
func GviUserSuit() icons.IsIcon           { return newIcon("user-suit") }
func GviUser() icons.IsIcon               { return newIcon("user") }
func GviUsers() icons.IsIcon              { return newIcon("users") }
func GviVote() icons.IsIcon               { return newIcon("vote") }
func GviWarning() icons.IsIcon            { return newIcon("warning") }
func GviWashingtonMonument() icons.IsIcon { return newIcon("washington-monument") }
func GviWheelBarrow() icons.IsIcon        { return newIcon("wheel-barrow") }
func GviWhiteHouse() icons.IsIcon         { return newIcon("white-house") }
func GviWorld() icons.IsIcon              { return newIcon("world") }
