package fa5

import "github.com/raitucarp/gomix/icons"

func FaBrand500px() icons.IsIcon          { return createIconSvg("brands/500px") }
func FaBrandAccessibleIcon() icons.IsIcon { return createIconSvg("brands/accessible-icon") }
func FaBrandAccusoft() icons.IsIcon       { return createIconSvg("brands/accusoft") }
func FaBrandAcquisitionsIncorporated() icons.IsIcon {
	return createIconSvg("brands/acquisitions-incorporated")
}
func FaBrandAdn() icons.IsIcon                 { return createIconSvg("brands/adn") }
func FaBrandAdversal() icons.IsIcon            { return createIconSvg("brands/adversal") }
func FaBrandAffiliatetheme() icons.IsIcon      { return createIconSvg("brands/affiliatetheme") }
func FaBrandAirbnb() icons.IsIcon              { return createIconSvg("brands/airbnb") }
func FaBrandAlgolia() icons.IsIcon             { return createIconSvg("brands/algolia") }
func FaBrandAlipay() icons.IsIcon              { return createIconSvg("brands/alipay") }
func FaBrandAmazonPay() icons.IsIcon           { return createIconSvg("brands/amazon-pay") }
func FaBrandAmazon() icons.IsIcon              { return createIconSvg("brands/amazon") }
func FaBrandAmilia() icons.IsIcon              { return createIconSvg("brands/amilia") }
func FaBrandAndroid() icons.IsIcon             { return createIconSvg("brands/android") }
func FaBrandAngellist() icons.IsIcon           { return createIconSvg("brands/angellist") }
func FaBrandAngrycreative() icons.IsIcon       { return createIconSvg("brands/angrycreative") }
func FaBrandAngular() icons.IsIcon             { return createIconSvg("brands/angular") }
func FaBrandAppStoreIos() icons.IsIcon         { return createIconSvg("brands/app-store-ios") }
func FaBrandAppStore() icons.IsIcon            { return createIconSvg("brands/app-store") }
func FaBrandApper() icons.IsIcon               { return createIconSvg("brands/apper") }
func FaBrandApplePay() icons.IsIcon            { return createIconSvg("brands/apple-pay") }
func FaBrandApple() icons.IsIcon               { return createIconSvg("brands/apple") }
func FaBrandArtstation() icons.IsIcon          { return createIconSvg("brands/artstation") }
func FaBrandAsymmetrik() icons.IsIcon          { return createIconSvg("brands/asymmetrik") }
func FaBrandAtlassian() icons.IsIcon           { return createIconSvg("brands/atlassian") }
func FaBrandAudible() icons.IsIcon             { return createIconSvg("brands/audible") }
func FaBrandAutoprefixer() icons.IsIcon        { return createIconSvg("brands/autoprefixer") }
func FaBrandAvianex() icons.IsIcon             { return createIconSvg("brands/avianex") }
func FaBrandAviato() icons.IsIcon              { return createIconSvg("brands/aviato") }
func FaBrandAws() icons.IsIcon                 { return createIconSvg("brands/aws") }
func FaBrandBandcamp() icons.IsIcon            { return createIconSvg("brands/bandcamp") }
func FaBrandBattleNet() icons.IsIcon           { return createIconSvg("brands/battle-net") }
func FaBrandBehanceSquare() icons.IsIcon       { return createIconSvg("brands/behance-square") }
func FaBrandBehance() icons.IsIcon             { return createIconSvg("brands/behance") }
func FaBrandBimobject() icons.IsIcon           { return createIconSvg("brands/bimobject") }
func FaBrandBitbucket() icons.IsIcon           { return createIconSvg("brands/bitbucket") }
func FaBrandBitcoin() icons.IsIcon             { return createIconSvg("brands/bitcoin") }
func FaBrandBity() icons.IsIcon                { return createIconSvg("brands/bity") }
func FaBrandBlackTie() icons.IsIcon            { return createIconSvg("brands/black-tie") }
func FaBrandBlackberry() icons.IsIcon          { return createIconSvg("brands/blackberry") }
func FaBrandBloggerB() icons.IsIcon            { return createIconSvg("brands/blogger-b") }
func FaBrandBlogger() icons.IsIcon             { return createIconSvg("brands/blogger") }
func FaBrandBluetoothB() icons.IsIcon          { return createIconSvg("brands/bluetooth-b") }
func FaBrandBluetooth() icons.IsIcon           { return createIconSvg("brands/bluetooth") }
func FaBrandBootstrap() icons.IsIcon           { return createIconSvg("brands/bootstrap") }
func FaBrandBtc() icons.IsIcon                 { return createIconSvg("brands/btc") }
func FaBrandBuffer() icons.IsIcon              { return createIconSvg("brands/buffer") }
func FaBrandBuromobelexperte() icons.IsIcon    { return createIconSvg("brands/buromobelexperte") }
func FaBrandBuyNLarge() icons.IsIcon           { return createIconSvg("brands/buy-n-large") }
func FaBrandBuysellads() icons.IsIcon          { return createIconSvg("brands/buysellads") }
func FaBrandCanadianMapleLeaf() icons.IsIcon   { return createIconSvg("brands/canadian-maple-leaf") }
func FaBrandCcAmazonPay() icons.IsIcon         { return createIconSvg("brands/cc-amazon-pay") }
func FaBrandCcAmex() icons.IsIcon              { return createIconSvg("brands/cc-amex") }
func FaBrandCcApplePay() icons.IsIcon          { return createIconSvg("brands/cc-apple-pay") }
func FaBrandCcDinersClub() icons.IsIcon        { return createIconSvg("brands/cc-diners-club") }
func FaBrandCcDiscover() icons.IsIcon          { return createIconSvg("brands/cc-discover") }
func FaBrandCcJcb() icons.IsIcon               { return createIconSvg("brands/cc-jcb") }
func FaBrandCcMastercard() icons.IsIcon        { return createIconSvg("brands/cc-mastercard") }
func FaBrandCcPaypal() icons.IsIcon            { return createIconSvg("brands/cc-paypal") }
func FaBrandCcStripe() icons.IsIcon            { return createIconSvg("brands/cc-stripe") }
func FaBrandCcVisa() icons.IsIcon              { return createIconSvg("brands/cc-visa") }
func FaBrandCentercode() icons.IsIcon          { return createIconSvg("brands/centercode") }
func FaBrandCentos() icons.IsIcon              { return createIconSvg("brands/centos") }
func FaBrandChrome() icons.IsIcon              { return createIconSvg("brands/chrome") }
func FaBrandChromecast() icons.IsIcon          { return createIconSvg("brands/chromecast") }
func FaBrandCloudflare() icons.IsIcon          { return createIconSvg("brands/cloudflare") }
func FaBrandCloudscale() icons.IsIcon          { return createIconSvg("brands/cloudscale") }
func FaBrandCloudsmith() icons.IsIcon          { return createIconSvg("brands/cloudsmith") }
func FaBrandCloudversify() icons.IsIcon        { return createIconSvg("brands/cloudversify") }
func FaBrandCodepen() icons.IsIcon             { return createIconSvg("brands/codepen") }
func FaBrandCodiepie() icons.IsIcon            { return createIconSvg("brands/codiepie") }
func FaBrandConfluence() icons.IsIcon          { return createIconSvg("brands/confluence") }
func FaBrandConnectdevelop() icons.IsIcon      { return createIconSvg("brands/connectdevelop") }
func FaBrandContao() icons.IsIcon              { return createIconSvg("brands/contao") }
func FaBrandCottonBureau() icons.IsIcon        { return createIconSvg("brands/cotton-bureau") }
func FaBrandCpanel() icons.IsIcon              { return createIconSvg("brands/cpanel") }
func FaBrandCreativeCommonsBy() icons.IsIcon   { return createIconSvg("brands/creative-commons-by") }
func FaBrandCreativeCommonsNcEu() icons.IsIcon { return createIconSvg("brands/creative-commons-nc-eu") }
func FaBrandCreativeCommonsNcJp() icons.IsIcon { return createIconSvg("brands/creative-commons-nc-jp") }
func FaBrandCreativeCommonsNc() icons.IsIcon   { return createIconSvg("brands/creative-commons-nc") }
func FaBrandCreativeCommonsNd() icons.IsIcon   { return createIconSvg("brands/creative-commons-nd") }
func FaBrandCreativeCommonsPdAlt() icons.IsIcon {
	return createIconSvg("brands/creative-commons-pd-alt")
}
func FaBrandCreativeCommonsPd() icons.IsIcon { return createIconSvg("brands/creative-commons-pd") }
func FaBrandCreativeCommonsRemix() icons.IsIcon {
	return createIconSvg("brands/creative-commons-remix")
}
func FaBrandCreativeCommonsSa() icons.IsIcon { return createIconSvg("brands/creative-commons-sa") }
func FaBrandCreativeCommonsSamplingPlus() icons.IsIcon {
	return createIconSvg("brands/creative-commons-sampling-plus")
}
func FaBrandCreativeCommonsSampling() icons.IsIcon {
	return createIconSvg("brands/creative-commons-sampling")
}
func FaBrandCreativeCommonsShare() icons.IsIcon {
	return createIconSvg("brands/creative-commons-share")
}
func FaBrandCreativeCommonsZero() icons.IsIcon { return createIconSvg("brands/creative-commons-zero") }
func FaBrandCreativeCommons() icons.IsIcon     { return createIconSvg("brands/creative-commons") }
func FaBrandCriticalRole() icons.IsIcon        { return createIconSvg("brands/critical-role") }
func FaBrandCss3Alt() icons.IsIcon             { return createIconSvg("brands/css3-alt") }
func FaBrandCss3() icons.IsIcon                { return createIconSvg("brands/css3") }
func FaBrandCuttlefish() icons.IsIcon          { return createIconSvg("brands/cuttlefish") }
func FaBrandDAndDBeyond() icons.IsIcon         { return createIconSvg("brands/d-and-d-beyond") }
func FaBrandDAndD() icons.IsIcon               { return createIconSvg("brands/d-and-d") }
func FaBrandDailymotion() icons.IsIcon         { return createIconSvg("brands/dailymotion") }
func FaBrandDashcube() icons.IsIcon            { return createIconSvg("brands/dashcube") }
func FaBrandDeezer() icons.IsIcon              { return createIconSvg("brands/deezer") }
func FaBrandDelicious() icons.IsIcon           { return createIconSvg("brands/delicious") }
func FaBrandDeploydog() icons.IsIcon           { return createIconSvg("brands/deploydog") }
func FaBrandDeskpro() icons.IsIcon             { return createIconSvg("brands/deskpro") }
func FaBrandDev() icons.IsIcon                 { return createIconSvg("brands/dev") }
func FaBrandDeviantart() icons.IsIcon          { return createIconSvg("brands/deviantart") }
func FaBrandDhl() icons.IsIcon                 { return createIconSvg("brands/dhl") }
func FaBrandDiaspora() icons.IsIcon            { return createIconSvg("brands/diaspora") }
func FaBrandDigg() icons.IsIcon                { return createIconSvg("brands/digg") }
func FaBrandDigitalOcean() icons.IsIcon        { return createIconSvg("brands/digital-ocean") }
func FaBrandDiscord() icons.IsIcon             { return createIconSvg("brands/discord") }
func FaBrandDiscourse() icons.IsIcon           { return createIconSvg("brands/discourse") }
func FaBrandDochub() icons.IsIcon              { return createIconSvg("brands/dochub") }
func FaBrandDocker() icons.IsIcon              { return createIconSvg("brands/docker") }
func FaBrandDraft2digital() icons.IsIcon       { return createIconSvg("brands/draft2digital") }
func FaBrandDribbbleSquare() icons.IsIcon      { return createIconSvg("brands/dribbble-square") }
func FaBrandDribbble() icons.IsIcon            { return createIconSvg("brands/dribbble") }
func FaBrandDropbox() icons.IsIcon             { return createIconSvg("brands/dropbox") }
func FaBrandDrupal() icons.IsIcon              { return createIconSvg("brands/drupal") }
func FaBrandDyalog() icons.IsIcon              { return createIconSvg("brands/dyalog") }
func FaBrandEarlybirds() icons.IsIcon          { return createIconSvg("brands/earlybirds") }
func FaBrandEbay() icons.IsIcon                { return createIconSvg("brands/ebay") }
func FaBrandEdgeLegacy() icons.IsIcon          { return createIconSvg("brands/edge-legacy") }
func FaBrandEdge() icons.IsIcon                { return createIconSvg("brands/edge") }
func FaBrandElementor() icons.IsIcon           { return createIconSvg("brands/elementor") }
func FaBrandEllo() icons.IsIcon                { return createIconSvg("brands/ello") }
func FaBrandEmber() icons.IsIcon               { return createIconSvg("brands/ember") }
func FaBrandEmpire() icons.IsIcon              { return createIconSvg("brands/empire") }
func FaBrandEnvira() icons.IsIcon              { return createIconSvg("brands/envira") }
func FaBrandErlang() icons.IsIcon              { return createIconSvg("brands/erlang") }
func FaBrandEthereum() icons.IsIcon            { return createIconSvg("brands/ethereum") }
func FaBrandEtsy() icons.IsIcon                { return createIconSvg("brands/etsy") }
func FaBrandEvernote() icons.IsIcon            { return createIconSvg("brands/evernote") }
func FaBrandExpeditedssl() icons.IsIcon        { return createIconSvg("brands/expeditedssl") }
func FaBrandFacebookF() icons.IsIcon           { return createIconSvg("brands/facebook-f") }
func FaBrandFacebookMessenger() icons.IsIcon   { return createIconSvg("brands/facebook-messenger") }
func FaBrandFacebookSquare() icons.IsIcon      { return createIconSvg("brands/facebook-square") }
func FaBrandFacebook() icons.IsIcon            { return createIconSvg("brands/facebook") }
func FaBrandFantasyFlightGames() icons.IsIcon  { return createIconSvg("brands/fantasy-flight-games") }
func FaBrandFedex() icons.IsIcon               { return createIconSvg("brands/fedex") }
func FaBrandFedora() icons.IsIcon              { return createIconSvg("brands/fedora") }
func FaBrandFigma() icons.IsIcon               { return createIconSvg("brands/figma") }
func FaBrandFirefoxBrowser() icons.IsIcon      { return createIconSvg("brands/firefox-browser") }
func FaBrandFirefox() icons.IsIcon             { return createIconSvg("brands/firefox") }
func FaBrandFirstOrderAlt() icons.IsIcon       { return createIconSvg("brands/first-order-alt") }
func FaBrandFirstOrder() icons.IsIcon          { return createIconSvg("brands/first-order") }
func FaBrandFirstdraft() icons.IsIcon          { return createIconSvg("brands/firstdraft") }
func FaBrandFlickr() icons.IsIcon              { return createIconSvg("brands/flickr") }
func FaBrandFlipboard() icons.IsIcon           { return createIconSvg("brands/flipboard") }
func FaBrandFly() icons.IsIcon                 { return createIconSvg("brands/fly") }
func FaBrandFontAwesomeAlt() icons.IsIcon      { return createIconSvg("brands/font-awesome-alt") }
func FaBrandFontAwesomeFlag() icons.IsIcon     { return createIconSvg("brands/font-awesome-flag") }
func FaBrandFontAwesomeLogoFull() icons.IsIcon { return createIconSvg("brands/font-awesome-logo-full") }
func FaBrandFontAwesome() icons.IsIcon         { return createIconSvg("brands/font-awesome") }
func FaBrandFonticonsFi() icons.IsIcon         { return createIconSvg("brands/fonticons-fi") }
func FaBrandFonticons() icons.IsIcon           { return createIconSvg("brands/fonticons") }
func FaBrandFortAwesomeAlt() icons.IsIcon      { return createIconSvg("brands/fort-awesome-alt") }
func FaBrandFortAwesome() icons.IsIcon         { return createIconSvg("brands/fort-awesome") }
func FaBrandForumbee() icons.IsIcon            { return createIconSvg("brands/forumbee") }
func FaBrandFoursquare() icons.IsIcon          { return createIconSvg("brands/foursquare") }
func FaBrandFreeCodeCamp() icons.IsIcon        { return createIconSvg("brands/free-code-camp") }
func FaBrandFreebsd() icons.IsIcon             { return createIconSvg("brands/freebsd") }
func FaBrandFulcrum() icons.IsIcon             { return createIconSvg("brands/fulcrum") }
func FaBrandGalacticRepublic() icons.IsIcon    { return createIconSvg("brands/galactic-republic") }
func FaBrandGalacticSenate() icons.IsIcon      { return createIconSvg("brands/galactic-senate") }
func FaBrandGetPocket() icons.IsIcon           { return createIconSvg("brands/get-pocket") }
func FaBrandGgCircle() icons.IsIcon            { return createIconSvg("brands/gg-circle") }
func FaBrandGg() icons.IsIcon                  { return createIconSvg("brands/gg") }
func FaBrandGitAlt() icons.IsIcon              { return createIconSvg("brands/git-alt") }
func FaBrandGitSquare() icons.IsIcon           { return createIconSvg("brands/git-square") }
func FaBrandGit() icons.IsIcon                 { return createIconSvg("brands/git") }
func FaBrandGithubAlt() icons.IsIcon           { return createIconSvg("brands/github-alt") }
func FaBrandGithubSquare() icons.IsIcon        { return createIconSvg("brands/github-square") }
func FaBrandGithub() icons.IsIcon              { return createIconSvg("brands/github") }
func FaBrandGitkraken() icons.IsIcon           { return createIconSvg("brands/gitkraken") }
func FaBrandGitlab() icons.IsIcon              { return createIconSvg("brands/gitlab") }
func FaBrandGitter() icons.IsIcon              { return createIconSvg("brands/gitter") }
func FaBrandGlideG() icons.IsIcon              { return createIconSvg("brands/glide-g") }
func FaBrandGlide() icons.IsIcon               { return createIconSvg("brands/glide") }
func FaBrandGofore() icons.IsIcon              { return createIconSvg("brands/gofore") }
func FaBrandGoodreadsG() icons.IsIcon          { return createIconSvg("brands/goodreads-g") }
func FaBrandGoodreads() icons.IsIcon           { return createIconSvg("brands/goodreads") }
func FaBrandGoogleDrive() icons.IsIcon         { return createIconSvg("brands/google-drive") }
func FaBrandGooglePay() icons.IsIcon           { return createIconSvg("brands/google-pay") }
func FaBrandGooglePlay() icons.IsIcon          { return createIconSvg("brands/google-play") }
func FaBrandGooglePlusG() icons.IsIcon         { return createIconSvg("brands/google-plus-g") }
func FaBrandGooglePlusSquare() icons.IsIcon    { return createIconSvg("brands/google-plus-square") }
func FaBrandGooglePlus() icons.IsIcon          { return createIconSvg("brands/google-plus") }
func FaBrandGoogleWallet() icons.IsIcon        { return createIconSvg("brands/google-wallet") }
func FaBrandGoogle() icons.IsIcon              { return createIconSvg("brands/google") }
func FaBrandGratipay() icons.IsIcon            { return createIconSvg("brands/gratipay") }
func FaBrandGrav() icons.IsIcon                { return createIconSvg("brands/grav") }
func FaBrandGripfire() icons.IsIcon            { return createIconSvg("brands/gripfire") }
func FaBrandGrunt() icons.IsIcon               { return createIconSvg("brands/grunt") }
func FaBrandGuilded() icons.IsIcon             { return createIconSvg("brands/guilded") }
func FaBrandGulp() icons.IsIcon                { return createIconSvg("brands/gulp") }
func FaBrandHackerNewsSquare() icons.IsIcon    { return createIconSvg("brands/hacker-news-square") }
func FaBrandHackerNews() icons.IsIcon          { return createIconSvg("brands/hacker-news") }
func FaBrandHackerrank() icons.IsIcon          { return createIconSvg("brands/hackerrank") }
func FaBrandHips() icons.IsIcon                { return createIconSvg("brands/hips") }
func FaBrandHireAHelper() icons.IsIcon         { return createIconSvg("brands/hire-a-helper") }
func FaBrandHive() icons.IsIcon                { return createIconSvg("brands/hive") }
func FaBrandHooli() icons.IsIcon               { return createIconSvg("brands/hooli") }
func FaBrandHornbill() icons.IsIcon            { return createIconSvg("brands/hornbill") }
func FaBrandHotjar() icons.IsIcon              { return createIconSvg("brands/hotjar") }
func FaBrandHouzz() icons.IsIcon               { return createIconSvg("brands/houzz") }
func FaBrandHtml5() icons.IsIcon               { return createIconSvg("brands/html5") }
func FaBrandHubspot() icons.IsIcon             { return createIconSvg("brands/hubspot") }
func FaBrandIdeal() icons.IsIcon               { return createIconSvg("brands/ideal") }
func FaBrandImdb() icons.IsIcon                { return createIconSvg("brands/imdb") }
func FaBrandInnosoft() icons.IsIcon            { return createIconSvg("brands/innosoft") }
func FaBrandInstagramSquare() icons.IsIcon     { return createIconSvg("brands/instagram-square") }
func FaBrandInstagram() icons.IsIcon           { return createIconSvg("brands/instagram") }
func FaBrandInstalod() icons.IsIcon            { return createIconSvg("brands/instalod") }
func FaBrandIntercom() icons.IsIcon            { return createIconSvg("brands/intercom") }
func FaBrandInternetExplorer() icons.IsIcon    { return createIconSvg("brands/internet-explorer") }
func FaBrandInvision() icons.IsIcon            { return createIconSvg("brands/invision") }
func FaBrandIoxhost() icons.IsIcon             { return createIconSvg("brands/ioxhost") }
func FaBrandItchIo() icons.IsIcon              { return createIconSvg("brands/itch-io") }
func FaBrandItunesNote() icons.IsIcon          { return createIconSvg("brands/itunes-note") }
func FaBrandItunes() icons.IsIcon              { return createIconSvg("brands/itunes") }
func FaBrandJava() icons.IsIcon                { return createIconSvg("brands/java") }
func FaBrandJediOrder() icons.IsIcon           { return createIconSvg("brands/jedi-order") }
func FaBrandJenkins() icons.IsIcon             { return createIconSvg("brands/jenkins") }
func FaBrandJira() icons.IsIcon                { return createIconSvg("brands/jira") }
func FaBrandJoget() icons.IsIcon               { return createIconSvg("brands/joget") }
func FaBrandJoomla() icons.IsIcon              { return createIconSvg("brands/joomla") }
func FaBrandJsSquare() icons.IsIcon            { return createIconSvg("brands/js-square") }
func FaBrandJs() icons.IsIcon                  { return createIconSvg("brands/js") }
func FaBrandJsfiddle() icons.IsIcon            { return createIconSvg("brands/jsfiddle") }
func FaBrandKaggle() icons.IsIcon              { return createIconSvg("brands/kaggle") }
func FaBrandKeybase() icons.IsIcon             { return createIconSvg("brands/keybase") }
func FaBrandKeycdn() icons.IsIcon              { return createIconSvg("brands/keycdn") }
func FaBrandKickstarterK() icons.IsIcon        { return createIconSvg("brands/kickstarter-k") }
func FaBrandKickstarter() icons.IsIcon         { return createIconSvg("brands/kickstarter") }
func FaBrandKorvue() icons.IsIcon              { return createIconSvg("brands/korvue") }
func FaBrandLaravel() icons.IsIcon             { return createIconSvg("brands/laravel") }
func FaBrandLastfmSquare() icons.IsIcon        { return createIconSvg("brands/lastfm-square") }
func FaBrandLastfm() icons.IsIcon              { return createIconSvg("brands/lastfm") }
func FaBrandLeanpub() icons.IsIcon             { return createIconSvg("brands/leanpub") }
func FaBrandLess() icons.IsIcon                { return createIconSvg("brands/less") }
func FaBrandLine() icons.IsIcon                { return createIconSvg("brands/line") }
func FaBrandLinkedinIn() icons.IsIcon          { return createIconSvg("brands/linkedin-in") }
func FaBrandLinkedin() icons.IsIcon            { return createIconSvg("brands/linkedin") }
func FaBrandLinode() icons.IsIcon              { return createIconSvg("brands/linode") }
func FaBrandLinux() icons.IsIcon               { return createIconSvg("brands/linux") }
func FaBrandLyft() icons.IsIcon                { return createIconSvg("brands/lyft") }
func FaBrandMagento() icons.IsIcon             { return createIconSvg("brands/magento") }
func FaBrandMailchimp() icons.IsIcon           { return createIconSvg("brands/mailchimp") }
func FaBrandMandalorian() icons.IsIcon         { return createIconSvg("brands/mandalorian") }
func FaBrandMarkdown() icons.IsIcon            { return createIconSvg("brands/markdown") }
func FaBrandMastodon() icons.IsIcon            { return createIconSvg("brands/mastodon") }
func FaBrandMaxcdn() icons.IsIcon              { return createIconSvg("brands/maxcdn") }
func FaBrandMdb() icons.IsIcon                 { return createIconSvg("brands/mdb") }
func FaBrandMedapps() icons.IsIcon             { return createIconSvg("brands/medapps") }
func FaBrandMediumM() icons.IsIcon             { return createIconSvg("brands/medium-m") }
func FaBrandMedium() icons.IsIcon              { return createIconSvg("brands/medium") }
func FaBrandMedrt() icons.IsIcon               { return createIconSvg("brands/medrt") }
func FaBrandMeetup() icons.IsIcon              { return createIconSvg("brands/meetup") }
func FaBrandMegaport() icons.IsIcon            { return createIconSvg("brands/megaport") }
func FaBrandMendeley() icons.IsIcon            { return createIconSvg("brands/mendeley") }
func FaBrandMicroblog() icons.IsIcon           { return createIconSvg("brands/microblog") }
func FaBrandMicrosoft() icons.IsIcon           { return createIconSvg("brands/microsoft") }
func FaBrandMix() icons.IsIcon                 { return createIconSvg("brands/mix") }
func FaBrandMixcloud() icons.IsIcon            { return createIconSvg("brands/mixcloud") }
func FaBrandMixer() icons.IsIcon               { return createIconSvg("brands/mixer") }
func FaBrandMizuni() icons.IsIcon              { return createIconSvg("brands/mizuni") }
func FaBrandModx() icons.IsIcon                { return createIconSvg("brands/modx") }
func FaBrandMonero() icons.IsIcon              { return createIconSvg("brands/monero") }
func FaBrandNapster() icons.IsIcon             { return createIconSvg("brands/napster") }
func FaBrandNeos() icons.IsIcon                { return createIconSvg("brands/neos") }
func FaBrandNimblr() icons.IsIcon              { return createIconSvg("brands/nimblr") }
func FaBrandNodeJs() icons.IsIcon              { return createIconSvg("brands/node-js") }
func FaBrandNode() icons.IsIcon                { return createIconSvg("brands/node") }
func FaBrandNpm() icons.IsIcon                 { return createIconSvg("brands/npm") }
func FaBrandNs8() icons.IsIcon                 { return createIconSvg("brands/ns8") }
func FaBrandNutritionix() icons.IsIcon         { return createIconSvg("brands/nutritionix") }
func FaBrandOctopusDeploy() icons.IsIcon       { return createIconSvg("brands/octopus-deploy") }
func FaBrandOdnoklassnikiSquare() icons.IsIcon { return createIconSvg("brands/odnoklassniki-square") }
func FaBrandOdnoklassniki() icons.IsIcon       { return createIconSvg("brands/odnoklassniki") }
func FaBrandOldRepublic() icons.IsIcon         { return createIconSvg("brands/old-republic") }
func FaBrandOpencart() icons.IsIcon            { return createIconSvg("brands/opencart") }
func FaBrandOpenid() icons.IsIcon              { return createIconSvg("brands/openid") }
func FaBrandOpera() icons.IsIcon               { return createIconSvg("brands/opera") }
func FaBrandOptinMonster() icons.IsIcon        { return createIconSvg("brands/optin-monster") }
func FaBrandOrcid() icons.IsIcon               { return createIconSvg("brands/orcid") }
func FaBrandOsi() icons.IsIcon                 { return createIconSvg("brands/osi") }
func FaBrandPage4() icons.IsIcon               { return createIconSvg("brands/page4") }
func FaBrandPagelines() icons.IsIcon           { return createIconSvg("brands/pagelines") }
func FaBrandPalfed() icons.IsIcon              { return createIconSvg("brands/palfed") }
func FaBrandPatreon() icons.IsIcon             { return createIconSvg("brands/patreon") }
func FaBrandPaypal() icons.IsIcon              { return createIconSvg("brands/paypal") }
func FaBrandPennyArcade() icons.IsIcon         { return createIconSvg("brands/penny-arcade") }
func FaBrandPerbyte() icons.IsIcon             { return createIconSvg("brands/perbyte") }
func FaBrandPeriscope() icons.IsIcon           { return createIconSvg("brands/periscope") }
func FaBrandPhabricator() icons.IsIcon         { return createIconSvg("brands/phabricator") }
func FaBrandPhoenixFramework() icons.IsIcon    { return createIconSvg("brands/phoenix-framework") }
func FaBrandPhoenixSquadron() icons.IsIcon     { return createIconSvg("brands/phoenix-squadron") }
func FaBrandPhp() icons.IsIcon                 { return createIconSvg("brands/php") }
func FaBrandPiedPiperAlt() icons.IsIcon        { return createIconSvg("brands/pied-piper-alt") }
func FaBrandPiedPiperHat() icons.IsIcon        { return createIconSvg("brands/pied-piper-hat") }
func FaBrandPiedPiperPp() icons.IsIcon         { return createIconSvg("brands/pied-piper-pp") }
func FaBrandPiedPiperSquare() icons.IsIcon     { return createIconSvg("brands/pied-piper-square") }
func FaBrandPiedPiper() icons.IsIcon           { return createIconSvg("brands/pied-piper") }
func FaBrandPinterestP() icons.IsIcon          { return createIconSvg("brands/pinterest-p") }
func FaBrandPinterestSquare() icons.IsIcon     { return createIconSvg("brands/pinterest-square") }
func FaBrandPinterest() icons.IsIcon           { return createIconSvg("brands/pinterest") }
func FaBrandPlaystation() icons.IsIcon         { return createIconSvg("brands/playstation") }
func FaBrandProductHunt() icons.IsIcon         { return createIconSvg("brands/product-hunt") }
func FaBrandPushed() icons.IsIcon              { return createIconSvg("brands/pushed") }
func FaBrandPython() icons.IsIcon              { return createIconSvg("brands/python") }
func FaBrandQq() icons.IsIcon                  { return createIconSvg("brands/qq") }
func FaBrandQuinscape() icons.IsIcon           { return createIconSvg("brands/quinscape") }
func FaBrandQuora() icons.IsIcon               { return createIconSvg("brands/quora") }
func FaBrandRProject() icons.IsIcon            { return createIconSvg("brands/r-project") }
func FaBrandRaspberryPi() icons.IsIcon         { return createIconSvg("brands/raspberry-pi") }
func FaBrandRavelry() icons.IsIcon             { return createIconSvg("brands/ravelry") }
func FaBrandReact() icons.IsIcon               { return createIconSvg("brands/react") }
func FaBrandReacteurope() icons.IsIcon         { return createIconSvg("brands/reacteurope") }
func FaBrandReadme() icons.IsIcon              { return createIconSvg("brands/readme") }
func FaBrandRebel() icons.IsIcon               { return createIconSvg("brands/rebel") }
func FaBrandRedRiver() icons.IsIcon            { return createIconSvg("brands/red-river") }
func FaBrandRedditAlien() icons.IsIcon         { return createIconSvg("brands/reddit-alien") }
func FaBrandRedditSquare() icons.IsIcon        { return createIconSvg("brands/reddit-square") }
func FaBrandReddit() icons.IsIcon              { return createIconSvg("brands/reddit") }
func FaBrandRedhat() icons.IsIcon              { return createIconSvg("brands/redhat") }
func FaBrandRenren() icons.IsIcon              { return createIconSvg("brands/renren") }
func FaBrandReplyd() icons.IsIcon              { return createIconSvg("brands/replyd") }
func FaBrandResearchgate() icons.IsIcon        { return createIconSvg("brands/researchgate") }
func FaBrandResolving() icons.IsIcon           { return createIconSvg("brands/resolving") }
func FaBrandRev() icons.IsIcon                 { return createIconSvg("brands/rev") }
func FaBrandRocketchat() icons.IsIcon          { return createIconSvg("brands/rocketchat") }
func FaBrandRockrms() icons.IsIcon             { return createIconSvg("brands/rockrms") }
func FaBrandRust() icons.IsIcon                { return createIconSvg("brands/rust") }
func FaBrandSafari() icons.IsIcon              { return createIconSvg("brands/safari") }
func FaBrandSalesforce() icons.IsIcon          { return createIconSvg("brands/salesforce") }
func FaBrandSass() icons.IsIcon                { return createIconSvg("brands/sass") }
func FaBrandSchlix() icons.IsIcon              { return createIconSvg("brands/schlix") }
func FaBrandScribd() icons.IsIcon              { return createIconSvg("brands/scribd") }
func FaBrandSearchengin() icons.IsIcon         { return createIconSvg("brands/searchengin") }
func FaBrandSellcast() icons.IsIcon            { return createIconSvg("brands/sellcast") }
func FaBrandSellsy() icons.IsIcon              { return createIconSvg("brands/sellsy") }
func FaBrandServicestack() icons.IsIcon        { return createIconSvg("brands/servicestack") }
func FaBrandShirtsinbulk() icons.IsIcon        { return createIconSvg("brands/shirtsinbulk") }
func FaBrandShopify() icons.IsIcon             { return createIconSvg("brands/shopify") }
func FaBrandShopware() icons.IsIcon            { return createIconSvg("brands/shopware") }
func FaBrandSimplybuilt() icons.IsIcon         { return createIconSvg("brands/simplybuilt") }
func FaBrandSistrix() icons.IsIcon             { return createIconSvg("brands/sistrix") }
func FaBrandSith() icons.IsIcon                { return createIconSvg("brands/sith") }
func FaBrandSketch() icons.IsIcon              { return createIconSvg("brands/sketch") }
func FaBrandSkyatlas() icons.IsIcon            { return createIconSvg("brands/skyatlas") }
func FaBrandSkype() icons.IsIcon               { return createIconSvg("brands/skype") }
func FaBrandSlackHash() icons.IsIcon           { return createIconSvg("brands/slack-hash") }
func FaBrandSlack() icons.IsIcon               { return createIconSvg("brands/slack") }
func FaBrandSlideshare() icons.IsIcon          { return createIconSvg("brands/slideshare") }
func FaBrandSnapchatGhost() icons.IsIcon       { return createIconSvg("brands/snapchat-ghost") }
func FaBrandSnapchatSquare() icons.IsIcon      { return createIconSvg("brands/snapchat-square") }
func FaBrandSnapchat() icons.IsIcon            { return createIconSvg("brands/snapchat") }
func FaBrandSoundcloud() icons.IsIcon          { return createIconSvg("brands/soundcloud") }
func FaBrandSourcetree() icons.IsIcon          { return createIconSvg("brands/sourcetree") }
func FaBrandSpeakap() icons.IsIcon             { return createIconSvg("brands/speakap") }
func FaBrandSpeakerDeck() icons.IsIcon         { return createIconSvg("brands/speaker-deck") }
func FaBrandSpotify() icons.IsIcon             { return createIconSvg("brands/spotify") }
func FaBrandSquarespace() icons.IsIcon         { return createIconSvg("brands/squarespace") }
func FaBrandStackExchange() icons.IsIcon       { return createIconSvg("brands/stack-exchange") }
func FaBrandStackOverflow() icons.IsIcon       { return createIconSvg("brands/stack-overflow") }
func FaBrandStackpath() icons.IsIcon           { return createIconSvg("brands/stackpath") }
func FaBrandStaylinked() icons.IsIcon          { return createIconSvg("brands/staylinked") }
func FaBrandSteamSquare() icons.IsIcon         { return createIconSvg("brands/steam-square") }
func FaBrandSteamSymbol() icons.IsIcon         { return createIconSvg("brands/steam-symbol") }
func FaBrandSteam() icons.IsIcon               { return createIconSvg("brands/steam") }
func FaBrandStickerMule() icons.IsIcon         { return createIconSvg("brands/sticker-mule") }
func FaBrandStrava() icons.IsIcon              { return createIconSvg("brands/strava") }
func FaBrandStripeS() icons.IsIcon             { return createIconSvg("brands/stripe-s") }
func FaBrandStripe() icons.IsIcon              { return createIconSvg("brands/stripe") }
func FaBrandStudiovinari() icons.IsIcon        { return createIconSvg("brands/studiovinari") }
func FaBrandStumbleuponCircle() icons.IsIcon   { return createIconSvg("brands/stumbleupon-circle") }
func FaBrandStumbleupon() icons.IsIcon         { return createIconSvg("brands/stumbleupon") }
func FaBrandSuperpowers() icons.IsIcon         { return createIconSvg("brands/superpowers") }
func FaBrandSupple() icons.IsIcon              { return createIconSvg("brands/supple") }
func FaBrandSuse() icons.IsIcon                { return createIconSvg("brands/suse") }
func FaBrandSwift() icons.IsIcon               { return createIconSvg("brands/swift") }
func FaBrandSymfony() icons.IsIcon             { return createIconSvg("brands/symfony") }
func FaBrandTeamspeak() icons.IsIcon           { return createIconSvg("brands/teamspeak") }
func FaBrandTelegramPlane() icons.IsIcon       { return createIconSvg("brands/telegram-plane") }
func FaBrandTelegram() icons.IsIcon            { return createIconSvg("brands/telegram") }
func FaBrandTencentWeibo() icons.IsIcon        { return createIconSvg("brands/tencent-weibo") }
func FaBrandTheRedYeti() icons.IsIcon          { return createIconSvg("brands/the-red-yeti") }
func FaBrandThemeco() icons.IsIcon             { return createIconSvg("brands/themeco") }
func FaBrandThemeisle() icons.IsIcon           { return createIconSvg("brands/themeisle") }
func FaBrandThinkPeaks() icons.IsIcon          { return createIconSvg("brands/think-peaks") }
func FaBrandTiktok() icons.IsIcon              { return createIconSvg("brands/tiktok") }
func FaBrandTradeFederation() icons.IsIcon     { return createIconSvg("brands/trade-federation") }
func FaBrandTrello() icons.IsIcon              { return createIconSvg("brands/trello") }
func FaBrandTumblrSquare() icons.IsIcon        { return createIconSvg("brands/tumblr-square") }
func FaBrandTumblr() icons.IsIcon              { return createIconSvg("brands/tumblr") }
func FaBrandTwitch() icons.IsIcon              { return createIconSvg("brands/twitch") }
func FaBrandTwitterSquare() icons.IsIcon       { return createIconSvg("brands/twitter-square") }
func FaBrandTwitter() icons.IsIcon             { return createIconSvg("brands/twitter") }
func FaBrandTypo3() icons.IsIcon               { return createIconSvg("brands/typo3") }
func FaBrandUber() icons.IsIcon                { return createIconSvg("brands/uber") }
func FaBrandUbuntu() icons.IsIcon              { return createIconSvg("brands/ubuntu") }
func FaBrandUikit() icons.IsIcon               { return createIconSvg("brands/uikit") }
func FaBrandUmbraco() icons.IsIcon             { return createIconSvg("brands/umbraco") }
func FaBrandUncharted() icons.IsIcon           { return createIconSvg("brands/uncharted") }
func FaBrandUniregistry() icons.IsIcon         { return createIconSvg("brands/uniregistry") }
func FaBrandUnity() icons.IsIcon               { return createIconSvg("brands/unity") }
func FaBrandUnsplash() icons.IsIcon            { return createIconSvg("brands/unsplash") }
func FaBrandUntappd() icons.IsIcon             { return createIconSvg("brands/untappd") }
func FaBrandUps() icons.IsIcon                 { return createIconSvg("brands/ups") }
func FaBrandUsb() icons.IsIcon                 { return createIconSvg("brands/usb") }
func FaBrandUsps() icons.IsIcon                { return createIconSvg("brands/usps") }
func FaBrandUssunnah() icons.IsIcon            { return createIconSvg("brands/ussunnah") }
func FaBrandVaadin() icons.IsIcon              { return createIconSvg("brands/vaadin") }
func FaBrandViacoin() icons.IsIcon             { return createIconSvg("brands/viacoin") }
func FaBrandViadeoSquare() icons.IsIcon        { return createIconSvg("brands/viadeo-square") }
func FaBrandViadeo() icons.IsIcon              { return createIconSvg("brands/viadeo") }
func FaBrandViber() icons.IsIcon               { return createIconSvg("brands/viber") }
func FaBrandVimeoSquare() icons.IsIcon         { return createIconSvg("brands/vimeo-square") }
func FaBrandVimeoV() icons.IsIcon              { return createIconSvg("brands/vimeo-v") }
func FaBrandVimeo() icons.IsIcon               { return createIconSvg("brands/vimeo") }
func FaBrandVine() icons.IsIcon                { return createIconSvg("brands/vine") }
func FaBrandVk() icons.IsIcon                  { return createIconSvg("brands/vk") }
func FaBrandVnv() icons.IsIcon                 { return createIconSvg("brands/vnv") }
func FaBrandVuejs() icons.IsIcon               { return createIconSvg("brands/vuejs") }
func FaBrandWatchmanMonitoring() icons.IsIcon  { return createIconSvg("brands/watchman-monitoring") }
func FaBrandWaze() icons.IsIcon                { return createIconSvg("brands/waze") }
func FaBrandWeebly() icons.IsIcon              { return createIconSvg("brands/weebly") }
func FaBrandWeibo() icons.IsIcon               { return createIconSvg("brands/weibo") }
func FaBrandWeixin() icons.IsIcon              { return createIconSvg("brands/weixin") }
func FaBrandWhatsappSquare() icons.IsIcon      { return createIconSvg("brands/whatsapp-square") }
func FaBrandWhatsapp() icons.IsIcon            { return createIconSvg("brands/whatsapp") }
func FaBrandWhmcs() icons.IsIcon               { return createIconSvg("brands/whmcs") }
func FaBrandWikipediaW() icons.IsIcon          { return createIconSvg("brands/wikipedia-w") }
func FaBrandWindows() icons.IsIcon             { return createIconSvg("brands/windows") }
func FaBrandWix() icons.IsIcon                 { return createIconSvg("brands/wix") }
func FaBrandWizardsOfTheCoast() icons.IsIcon   { return createIconSvg("brands/wizards-of-the-coast") }
func FaBrandWodu() icons.IsIcon                { return createIconSvg("brands/wodu") }
func FaBrandWolfPackBattalion() icons.IsIcon   { return createIconSvg("brands/wolf-pack-battalion") }
func FaBrandWordpressSimple() icons.IsIcon     { return createIconSvg("brands/wordpress-simple") }
func FaBrandWordpress() icons.IsIcon           { return createIconSvg("brands/wordpress") }
func FaBrandWpbeginner() icons.IsIcon          { return createIconSvg("brands/wpbeginner") }
func FaBrandWpexplorer() icons.IsIcon          { return createIconSvg("brands/wpexplorer") }
func FaBrandWpforms() icons.IsIcon             { return createIconSvg("brands/wpforms") }
func FaBrandWpressr() icons.IsIcon             { return createIconSvg("brands/wpressr") }
func FaBrandXbox() icons.IsIcon                { return createIconSvg("brands/xbox") }
func FaBrandXingSquare() icons.IsIcon          { return createIconSvg("brands/xing-square") }
func FaBrandXing() icons.IsIcon                { return createIconSvg("brands/xing") }
func FaBrandYCombinator() icons.IsIcon         { return createIconSvg("brands/y-combinator") }
func FaBrandYahoo() icons.IsIcon               { return createIconSvg("brands/yahoo") }
func FaBrandYammer() icons.IsIcon              { return createIconSvg("brands/yammer") }
func FaBrandYandexInternational() icons.IsIcon { return createIconSvg("brands/yandex-international") }
func FaBrandYandex() icons.IsIcon              { return createIconSvg("brands/yandex") }
func FaBrandYarn() icons.IsIcon                { return createIconSvg("brands/yarn") }
func FaBrandYelp() icons.IsIcon                { return createIconSvg("brands/yelp") }
func FaBrandYoast() icons.IsIcon               { return createIconSvg("brands/yoast") }
func FaBrandYoutubeSquare() icons.IsIcon       { return createIconSvg("brands/youtube-square") }
func FaBrandYoutube() icons.IsIcon             { return createIconSvg("brands/youtube") }
func FaBrandZhihu() icons.IsIcon               { return createIconSvg("brands/zhihu") }
