package wi

import "github.com/raitucarp/gomix/icons"

func WiAlien() icons.IsIcon                    { return newIcon("wi-alien") }
func WiBarometer() icons.IsIcon                { return newIcon("wi-barometer") }
func WiCelsius() icons.IsIcon                  { return newIcon("wi-celsius") }
func WiCloudDown() icons.IsIcon                { return newIcon("wi-cloud-down") }
func WiCloudRefresh() icons.IsIcon             { return newIcon("wi-cloud-refresh") }
func WiCloudUp() icons.IsIcon                  { return newIcon("wi-cloud-up") }
func WiCloud() icons.IsIcon                    { return newIcon("wi-cloud") }
func WiCloudyGusts() icons.IsIcon              { return newIcon("wi-cloudy-gusts") }
func WiCloudyWindy() icons.IsIcon              { return newIcon("wi-cloudy-windy") }
func WiCloudy() icons.IsIcon                   { return newIcon("wi-cloudy") }
func WiDayCloudyGusts() icons.IsIcon           { return newIcon("wi-day-cloudy-gusts") }
func WiDayCloudyHigh() icons.IsIcon            { return newIcon("wi-day-cloudy-high") }
func WiDayCloudyWindy() icons.IsIcon           { return newIcon("wi-day-cloudy-windy") }
func WiDayCloudy() icons.IsIcon                { return newIcon("wi-day-cloudy") }
func WiDayFog() icons.IsIcon                   { return newIcon("wi-day-fog") }
func WiDayHail() icons.IsIcon                  { return newIcon("wi-day-hail") }
func WiDayHaze() icons.IsIcon                  { return newIcon("wi-day-haze") }
func WiDayLightWind() icons.IsIcon             { return newIcon("wi-day-light-wind") }
func WiDayLightning() icons.IsIcon             { return newIcon("wi-day-lightning") }
func WiDayRainMix() icons.IsIcon               { return newIcon("wi-day-rain-mix") }
func WiDayRainWind() icons.IsIcon              { return newIcon("wi-day-rain-wind") }
func WiDayRain() icons.IsIcon                  { return newIcon("wi-day-rain") }
func WiDayShowers() icons.IsIcon               { return newIcon("wi-day-showers") }
func WiDaySleetStorm() icons.IsIcon            { return newIcon("wi-day-sleet-storm") }
func WiDaySleet() icons.IsIcon                 { return newIcon("wi-day-sleet") }
func WiDaySnowThunderstorm() icons.IsIcon      { return newIcon("wi-day-snow-thunderstorm") }
func WiDaySnowWind() icons.IsIcon              { return newIcon("wi-day-snow-wind") }
func WiDaySnow() icons.IsIcon                  { return newIcon("wi-day-snow") }
func WiDaySprinkle() icons.IsIcon              { return newIcon("wi-day-sprinkle") }
func WiDayStormShowers() icons.IsIcon          { return newIcon("wi-day-storm-showers") }
func WiDaySunnyOvercast() icons.IsIcon         { return newIcon("wi-day-sunny-overcast") }
func WiDaySunny() icons.IsIcon                 { return newIcon("wi-day-sunny") }
func WiDayThunderstorm() icons.IsIcon          { return newIcon("wi-day-thunderstorm") }
func WiDayWindy() icons.IsIcon                 { return newIcon("wi-day-windy") }
func WiDegrees() icons.IsIcon                  { return newIcon("wi-degrees") }
func WiDirectionDownLeft() icons.IsIcon        { return newIcon("wi-direction-down-left") }
func WiDirectionDownRight() icons.IsIcon       { return newIcon("wi-direction-down-right") }
func WiDirectionDown() icons.IsIcon            { return newIcon("wi-direction-down") }
func WiDirectionLeft() icons.IsIcon            { return newIcon("wi-direction-left") }
func WiDirectionRight() icons.IsIcon           { return newIcon("wi-direction-right") }
func WiDirectionUpLeft() icons.IsIcon          { return newIcon("wi-direction-up-left") }
func WiDirectionUpRight() icons.IsIcon         { return newIcon("wi-direction-up-right") }
func WiDirectionUp() icons.IsIcon              { return newIcon("wi-direction-up") }
func WiDust() icons.IsIcon                     { return newIcon("wi-dust") }
func WiEarthquake() icons.IsIcon               { return newIcon("wi-earthquake") }
func WiFahrenheit() icons.IsIcon               { return newIcon("wi-fahrenheit") }
func WiFire() icons.IsIcon                     { return newIcon("wi-fire") }
func WiFlood() icons.IsIcon                    { return newIcon("wi-flood") }
func WiFog() icons.IsIcon                      { return newIcon("wi-fog") }
func WiGaleWarning() icons.IsIcon              { return newIcon("wi-gale-warning") }
func WiHail() icons.IsIcon                     { return newIcon("wi-hail") }
func WiHorizonAlt() icons.IsIcon               { return newIcon("wi-horizon-alt") }
func WiHorizon() icons.IsIcon                  { return newIcon("wi-horizon") }
func WiHot() icons.IsIcon                      { return newIcon("wi-hot") }
func WiHumidity() icons.IsIcon                 { return newIcon("wi-humidity") }
func WiHurricaneWarning() icons.IsIcon         { return newIcon("wi-hurricane-warning") }
func WiHurricane() icons.IsIcon                { return newIcon("wi-hurricane") }
func WiLightning() icons.IsIcon                { return newIcon("wi-lightning") }
func WiLunarEclipse() icons.IsIcon             { return newIcon("wi-lunar-eclipse") }
func WiMeteor() icons.IsIcon                   { return newIcon("wi-meteor") }
func WiMoonAltFirstQuarter() icons.IsIcon      { return newIcon("wi-moon-alt-first-quarter") }
func WiMoonAltFull() icons.IsIcon              { return newIcon("wi-moon-alt-full") }
func WiMoonAltNew() icons.IsIcon               { return newIcon("wi-moon-alt-new") }
func WiMoonAltThirdQuarter() icons.IsIcon      { return newIcon("wi-moon-alt-third-quarter") }
func WiMoonAltWaningCrescent1() icons.IsIcon   { return newIcon("wi-moon-alt-waning-crescent-1") }
func WiMoonAltWaningCrescent2() icons.IsIcon   { return newIcon("wi-moon-alt-waning-crescent-2") }
func WiMoonAltWaningCrescent3() icons.IsIcon   { return newIcon("wi-moon-alt-waning-crescent-3") }
func WiMoonAltWaningCrescent4() icons.IsIcon   { return newIcon("wi-moon-alt-waning-crescent-4") }
func WiMoonAltWaningCrescent5() icons.IsIcon   { return newIcon("wi-moon-alt-waning-crescent-5") }
func WiMoonAltWaningCrescent6() icons.IsIcon   { return newIcon("wi-moon-alt-waning-crescent-6") }
func WiMoonAltWaningGibbous1() icons.IsIcon    { return newIcon("wi-moon-alt-waning-gibbous-1") }
func WiMoonAltWaningGibbous2() icons.IsIcon    { return newIcon("wi-moon-alt-waning-gibbous-2") }
func WiMoonAltWaningGibbous3() icons.IsIcon    { return newIcon("wi-moon-alt-waning-gibbous-3") }
func WiMoonAltWaningGibbous4() icons.IsIcon    { return newIcon("wi-moon-alt-waning-gibbous-4") }
func WiMoonAltWaningGibbous5() icons.IsIcon    { return newIcon("wi-moon-alt-waning-gibbous-5") }
func WiMoonAltWaningGibbous6() icons.IsIcon    { return newIcon("wi-moon-alt-waning-gibbous-6") }
func WiMoonAltWaxingCrescent1() icons.IsIcon   { return newIcon("wi-moon-alt-waxing-crescent-1") }
func WiMoonAltWaxingCrescent2() icons.IsIcon   { return newIcon("wi-moon-alt-waxing-crescent-2") }
func WiMoonAltWaxingCrescent3() icons.IsIcon   { return newIcon("wi-moon-alt-waxing-crescent-3") }
func WiMoonAltWaxingCrescent4() icons.IsIcon   { return newIcon("wi-moon-alt-waxing-crescent-4") }
func WiMoonAltWaxingCrescent5() icons.IsIcon   { return newIcon("wi-moon-alt-waxing-crescent-5") }
func WiMoonAltWaxingCrescent6() icons.IsIcon   { return newIcon("wi-moon-alt-waxing-crescent-6") }
func WiMoonAltWaxingGibbous1() icons.IsIcon    { return newIcon("wi-moon-alt-waxing-gibbous-1") }
func WiMoonAltWaxingGibbous2() icons.IsIcon    { return newIcon("wi-moon-alt-waxing-gibbous-2") }
func WiMoonAltWaxingGibbous3() icons.IsIcon    { return newIcon("wi-moon-alt-waxing-gibbous-3") }
func WiMoonAltWaxingGibbous4() icons.IsIcon    { return newIcon("wi-moon-alt-waxing-gibbous-4") }
func WiMoonAltWaxingGibbous5() icons.IsIcon    { return newIcon("wi-moon-alt-waxing-gibbous-5") }
func WiMoonAltWaxingGibbous6() icons.IsIcon    { return newIcon("wi-moon-alt-waxing-gibbous-6") }
func WiMoonFirstQuarter() icons.IsIcon         { return newIcon("wi-moon-first-quarter") }
func WiMoonFull() icons.IsIcon                 { return newIcon("wi-moon-full") }
func WiMoonNew() icons.IsIcon                  { return newIcon("wi-moon-new") }
func WiMoonThirdQuarter() icons.IsIcon         { return newIcon("wi-moon-third-quarter") }
func WiMoonWaningCrescent1() icons.IsIcon      { return newIcon("wi-moon-waning-crescent-1") }
func WiMoonWaningCrescent2() icons.IsIcon      { return newIcon("wi-moon-waning-crescent-2") }
func WiMoonWaningCrescent3() icons.IsIcon      { return newIcon("wi-moon-waning-crescent-3") }
func WiMoonWaningCrescent4() icons.IsIcon      { return newIcon("wi-moon-waning-crescent-4") }
func WiMoonWaningCrescent5() icons.IsIcon      { return newIcon("wi-moon-waning-crescent-5") }
func WiMoonWaningCrescent6() icons.IsIcon      { return newIcon("wi-moon-waning-crescent-6") }
func WiMoonWaningGibbous1() icons.IsIcon       { return newIcon("wi-moon-waning-gibbous-1") }
func WiMoonWaningGibbous2() icons.IsIcon       { return newIcon("wi-moon-waning-gibbous-2") }
func WiMoonWaningGibbous3() icons.IsIcon       { return newIcon("wi-moon-waning-gibbous-3") }
func WiMoonWaningGibbous4() icons.IsIcon       { return newIcon("wi-moon-waning-gibbous-4") }
func WiMoonWaningGibbous5() icons.IsIcon       { return newIcon("wi-moon-waning-gibbous-5") }
func WiMoonWaningGibbous6() icons.IsIcon       { return newIcon("wi-moon-waning-gibbous-6") }
func WiMoonWaxing6() icons.IsIcon              { return newIcon("wi-moon-waxing-6") }
func WiMoonWaxingCrescent1() icons.IsIcon      { return newIcon("wi-moon-waxing-crescent-1") }
func WiMoonWaxingCrescent2() icons.IsIcon      { return newIcon("wi-moon-waxing-crescent-2") }
func WiMoonWaxingCrescent3() icons.IsIcon      { return newIcon("wi-moon-waxing-crescent-3") }
func WiMoonWaxingCrescent4() icons.IsIcon      { return newIcon("wi-moon-waxing-crescent-4") }
func WiMoonWaxingCrescent5() icons.IsIcon      { return newIcon("wi-moon-waxing-crescent-5") }
func WiMoonWaxingGibbous1() icons.IsIcon       { return newIcon("wi-moon-waxing-gibbous-1") }
func WiMoonWaxingGibbous2() icons.IsIcon       { return newIcon("wi-moon-waxing-gibbous-2") }
func WiMoonWaxingGibbous3() icons.IsIcon       { return newIcon("wi-moon-waxing-gibbous-3") }
func WiMoonWaxingGibbous4() icons.IsIcon       { return newIcon("wi-moon-waxing-gibbous-4") }
func WiMoonWaxingGibbous5() icons.IsIcon       { return newIcon("wi-moon-waxing-gibbous-5") }
func WiMoonWaxingGibbous6() icons.IsIcon       { return newIcon("wi-moon-waxing-gibbous-6") }
func WiMoonrise() icons.IsIcon                 { return newIcon("wi-moonrise") }
func WiMoonset() icons.IsIcon                  { return newIcon("wi-moonset") }
func WiNa() icons.IsIcon                       { return newIcon("wi-na") }
func WiNightAltCloudyGusts() icons.IsIcon      { return newIcon("wi-night-alt-cloudy-gusts") }
func WiNightAltCloudyHigh() icons.IsIcon       { return newIcon("wi-night-alt-cloudy-high") }
func WiNightAltCloudyWindy() icons.IsIcon      { return newIcon("wi-night-alt-cloudy-windy") }
func WiNightAltCloudy() icons.IsIcon           { return newIcon("wi-night-alt-cloudy") }
func WiNightAltHail() icons.IsIcon             { return newIcon("wi-night-alt-hail") }
func WiNightAltLightning() icons.IsIcon        { return newIcon("wi-night-alt-lightning") }
func WiNightAltPartlyCloudy() icons.IsIcon     { return newIcon("wi-night-alt-partly-cloudy") }
func WiNightAltRainMix() icons.IsIcon          { return newIcon("wi-night-alt-rain-mix") }
func WiNightAltRainWind() icons.IsIcon         { return newIcon("wi-night-alt-rain-wind") }
func WiNightAltRain() icons.IsIcon             { return newIcon("wi-night-alt-rain") }
func WiNightAltShowers() icons.IsIcon          { return newIcon("wi-night-alt-showers") }
func WiNightAltSleetStorm() icons.IsIcon       { return newIcon("wi-night-alt-sleet-storm") }
func WiNightAltSleet() icons.IsIcon            { return newIcon("wi-night-alt-sleet") }
func WiNightAltSnowThunderstorm() icons.IsIcon { return newIcon("wi-night-alt-snow-thunderstorm") }
func WiNightAltSnowWind() icons.IsIcon         { return newIcon("wi-night-alt-snow-wind") }
func WiNightAltSnow() icons.IsIcon             { return newIcon("wi-night-alt-snow") }
func WiNightAltSprinkle() icons.IsIcon         { return newIcon("wi-night-alt-sprinkle") }
func WiNightAltStormShowers() icons.IsIcon     { return newIcon("wi-night-alt-storm-showers") }
func WiNightAltThunderstorm() icons.IsIcon     { return newIcon("wi-night-alt-thunderstorm") }
func WiNightClear() icons.IsIcon               { return newIcon("wi-night-clear") }
func WiNightCloudyGusts() icons.IsIcon         { return newIcon("wi-night-cloudy-gusts") }
func WiNightCloudyHigh() icons.IsIcon          { return newIcon("wi-night-cloudy-high") }
func WiNightCloudyWindy() icons.IsIcon         { return newIcon("wi-night-cloudy-windy") }
func WiNightCloudy() icons.IsIcon              { return newIcon("wi-night-cloudy") }
func WiNightFog() icons.IsIcon                 { return newIcon("wi-night-fog") }
func WiNightHail() icons.IsIcon                { return newIcon("wi-night-hail") }
func WiNightLightning() icons.IsIcon           { return newIcon("wi-night-lightning") }
func WiNightPartlyCloudy() icons.IsIcon        { return newIcon("wi-night-partly-cloudy") }
func WiNightRainMix() icons.IsIcon             { return newIcon("wi-night-rain-mix") }
func WiNightRainWind() icons.IsIcon            { return newIcon("wi-night-rain-wind") }
func WiNightRain() icons.IsIcon                { return newIcon("wi-night-rain") }
func WiNightShowers() icons.IsIcon             { return newIcon("wi-night-showers") }
func WiNightSleetStorm() icons.IsIcon          { return newIcon("wi-night-sleet-storm") }
func WiNightSleet() icons.IsIcon               { return newIcon("wi-night-sleet") }
func WiNightSnowThunderstorm() icons.IsIcon    { return newIcon("wi-night-snow-thunderstorm") }
func WiNightSnowWind() icons.IsIcon            { return newIcon("wi-night-snow-wind") }
func WiNightSnow() icons.IsIcon                { return newIcon("wi-night-snow") }
func WiNightSprinkle() icons.IsIcon            { return newIcon("wi-night-sprinkle") }
func WiNightStormShowers() icons.IsIcon        { return newIcon("wi-night-storm-showers") }
func WiNightThunderstorm() icons.IsIcon        { return newIcon("wi-night-thunderstorm") }
func WiRainMix() icons.IsIcon                  { return newIcon("wi-rain-mix") }
func WiRainWind() icons.IsIcon                 { return newIcon("wi-rain-wind") }
func WiRain() icons.IsIcon                     { return newIcon("wi-rain") }
func WiRaindrop() icons.IsIcon                 { return newIcon("wi-raindrop") }
func WiRaindrops() icons.IsIcon                { return newIcon("wi-raindrops") }
func WiRefreshAlt() icons.IsIcon               { return newIcon("wi-refresh-alt") }
func WiRefresh() icons.IsIcon                  { return newIcon("wi-refresh") }
func WiSandstorm() icons.IsIcon                { return newIcon("wi-sandstorm") }
func WiShowers() icons.IsIcon                  { return newIcon("wi-showers") }
func WiSleet() icons.IsIcon                    { return newIcon("wi-sleet") }
func WiSmallCraftAdvisory() icons.IsIcon       { return newIcon("wi-small-craft-advisory") }
func WiSmog() icons.IsIcon                     { return newIcon("wi-smog") }
func WiSmoke() icons.IsIcon                    { return newIcon("wi-smoke") }
func WiSnowWind() icons.IsIcon                 { return newIcon("wi-snow-wind") }
func WiSnow() icons.IsIcon                     { return newIcon("wi-snow") }
func WiSnowflakeCold() icons.IsIcon            { return newIcon("wi-snowflake-cold") }
func WiSolarEclipse() icons.IsIcon             { return newIcon("wi-solar-eclipse") }
func WiSprinkle() icons.IsIcon                 { return newIcon("wi-sprinkle") }
func WiStars() icons.IsIcon                    { return newIcon("wi-stars") }
func WiStormShowers() icons.IsIcon             { return newIcon("wi-storm-showers") }
func WiStormWarning() icons.IsIcon             { return newIcon("wi-storm-warning") }
func WiStrongWind() icons.IsIcon               { return newIcon("wi-strong-wind") }
func WiSunrise() icons.IsIcon                  { return newIcon("wi-sunrise") }
func WiSunset() icons.IsIcon                   { return newIcon("wi-sunset") }
func WiThermometerExterior() icons.IsIcon      { return newIcon("wi-thermometer-exterior") }
func WiThermometerInternal() icons.IsIcon      { return newIcon("wi-thermometer-internal") }
func WiThermometer() icons.IsIcon              { return newIcon("wi-thermometer") }
func WiThunderstorm() icons.IsIcon             { return newIcon("wi-thunderstorm") }
func WiTime1() icons.IsIcon                    { return newIcon("wi-time-1") }
func WiTime10() icons.IsIcon                   { return newIcon("wi-time-10") }
func WiTime11() icons.IsIcon                   { return newIcon("wi-time-11") }
func WiTime12() icons.IsIcon                   { return newIcon("wi-time-12") }
func WiTime2() icons.IsIcon                    { return newIcon("wi-time-2") }
func WiTime3() icons.IsIcon                    { return newIcon("wi-time-3") }
func WiTime4() icons.IsIcon                    { return newIcon("wi-time-4") }
func WiTime5() icons.IsIcon                    { return newIcon("wi-time-5") }
func WiTime6() icons.IsIcon                    { return newIcon("wi-time-6") }
func WiTime7() icons.IsIcon                    { return newIcon("wi-time-7") }
func WiTime8() icons.IsIcon                    { return newIcon("wi-time-8") }
func WiTime9() icons.IsIcon                    { return newIcon("wi-time-9") }
func WiTornado() icons.IsIcon                  { return newIcon("wi-tornado") }
func WiTrain() icons.IsIcon                    { return newIcon("wi-train") }
func WiTsunami() icons.IsIcon                  { return newIcon("wi-tsunami") }
func WiUmbrella() icons.IsIcon                 { return newIcon("wi-umbrella") }
func WiVolcano() icons.IsIcon                  { return newIcon("wi-volcano") }
func WiWindBeaufort0() icons.IsIcon            { return newIcon("wi-wind-beaufort-0") }
func WiWindBeaufort1() icons.IsIcon            { return newIcon("wi-wind-beaufort-1") }
func WiWindBeaufort10() icons.IsIcon           { return newIcon("wi-wind-beaufort-10") }
func WiWindBeaufort11() icons.IsIcon           { return newIcon("wi-wind-beaufort-11") }
func WiWindBeaufort12() icons.IsIcon           { return newIcon("wi-wind-beaufort-12") }
func WiWindBeaufort2() icons.IsIcon            { return newIcon("wi-wind-beaufort-2") }
func WiWindBeaufort3() icons.IsIcon            { return newIcon("wi-wind-beaufort-3") }
func WiWindBeaufort4() icons.IsIcon            { return newIcon("wi-wind-beaufort-4") }
func WiWindBeaufort5() icons.IsIcon            { return newIcon("wi-wind-beaufort-5") }
func WiWindBeaufort6() icons.IsIcon            { return newIcon("wi-wind-beaufort-6") }
func WiWindBeaufort7() icons.IsIcon            { return newIcon("wi-wind-beaufort-7") }
func WiWindBeaufort8() icons.IsIcon            { return newIcon("wi-wind-beaufort-8") }
func WiWindBeaufort9() icons.IsIcon            { return newIcon("wi-wind-beaufort-9") }
func WiWindDeg() icons.IsIcon                  { return newIcon("wi-wind-deg") }
func WiWindy() icons.IsIcon                    { return newIcon("wi-windy") }
