package hi

import "github.com/raitucarp/gomix/icons"

func HiAcademicCap() icons.IsIcon            { return newIcon(solidIcon, "academic-cap") }
func HiAdjustmentsHorizontal() icons.IsIcon  { return newIcon(solidIcon, "adjustments-horizontal") }
func HiAdjustmentsVertical() icons.IsIcon    { return newIcon(solidIcon, "adjustments-vertical") }
func HiArchiveBoxArrowDown() icons.IsIcon    { return newIcon(solidIcon, "archive-box-arrow-down") }
func HiArchiveBoxXMark() icons.IsIcon        { return newIcon(solidIcon, "archive-box-x-mark") }
func HiArchiveBox() icons.IsIcon             { return newIcon(solidIcon, "archive-box") }
func HiArrowDownCircle() icons.IsIcon        { return newIcon(solidIcon, "arrow-down-circle") }
func HiArrowDownLeft() icons.IsIcon          { return newIcon(solidIcon, "arrow-down-left") }
func HiArrowDownOnSquareStack() icons.IsIcon { return newIcon(solidIcon, "arrow-down-on-square-stack") }
func HiArrowDownOnSquare() icons.IsIcon      { return newIcon(solidIcon, "arrow-down-on-square") }
func HiArrowDownRight() icons.IsIcon         { return newIcon(solidIcon, "arrow-down-right") }
func HiArrowDownTray() icons.IsIcon          { return newIcon(solidIcon, "arrow-down-tray") }
func HiArrowDown() icons.IsIcon              { return newIcon(solidIcon, "arrow-down") }
func HiArrowLeftCircle() icons.IsIcon        { return newIcon(solidIcon, "arrow-left-circle") }
func HiArrowLeftEndOnRectangle() icons.IsIcon {
	return newIcon(solidIcon, "arrow-left-end-on-rectangle")
}
func HiArrowLeftOnRectangle() icons.IsIcon { return newIcon(solidIcon, "arrow-left-on-rectangle") }
func HiArrowLeftStartOnRectangle() icons.IsIcon {
	return newIcon(solidIcon, "arrow-left-start-on-rectangle")
}
func HiArrowLeft() icons.IsIcon              { return newIcon(solidIcon, "arrow-left") }
func HiArrowLongDown() icons.IsIcon          { return newIcon(solidIcon, "arrow-long-down") }
func HiArrowLongLeft() icons.IsIcon          { return newIcon(solidIcon, "arrow-long-left") }
func HiArrowLongRight() icons.IsIcon         { return newIcon(solidIcon, "arrow-long-right") }
func HiArrowLongUp() icons.IsIcon            { return newIcon(solidIcon, "arrow-long-up") }
func HiArrowPathRoundedSquare() icons.IsIcon { return newIcon(solidIcon, "arrow-path-rounded-square") }
func HiArrowPath() icons.IsIcon              { return newIcon(solidIcon, "arrow-path") }
func HiArrowRightCircle() icons.IsIcon       { return newIcon(solidIcon, "arrow-right-circle") }
func HiArrowRightEndOnRectangle() icons.IsIcon {
	return newIcon(solidIcon, "arrow-right-end-on-rectangle")
}
func HiArrowRightOnRectangle() icons.IsIcon { return newIcon(solidIcon, "arrow-right-on-rectangle") }
func HiArrowRightStartOnRectangle() icons.IsIcon {
	return newIcon(solidIcon, "arrow-right-start-on-rectangle")
}
func HiArrowRight() icons.IsIcon            { return newIcon(solidIcon, "arrow-right") }
func HiArrowSmallDown() icons.IsIcon        { return newIcon(solidIcon, "arrow-small-down") }
func HiArrowSmallLeft() icons.IsIcon        { return newIcon(solidIcon, "arrow-small-left") }
func HiArrowSmallRight() icons.IsIcon       { return newIcon(solidIcon, "arrow-small-right") }
func HiArrowSmallUp() icons.IsIcon          { return newIcon(solidIcon, "arrow-small-up") }
func HiArrowTopRightOnSquare() icons.IsIcon { return newIcon(solidIcon, "arrow-top-right-on-square") }
func HiArrowTrendingDown() icons.IsIcon     { return newIcon(solidIcon, "arrow-trending-down") }
func HiArrowTrendingUp() icons.IsIcon       { return newIcon(solidIcon, "arrow-trending-up") }
func HiArrowTurnDownLeft() icons.IsIcon     { return newIcon(solidIcon, "arrow-turn-down-left") }
func HiArrowTurnDownRight() icons.IsIcon    { return newIcon(solidIcon, "arrow-turn-down-right") }
func HiArrowTurnLeftDown() icons.IsIcon     { return newIcon(solidIcon, "arrow-turn-left-down") }
func HiArrowTurnLeftUp() icons.IsIcon       { return newIcon(solidIcon, "arrow-turn-left-up") }
func HiArrowTurnRightDown() icons.IsIcon    { return newIcon(solidIcon, "arrow-turn-right-down") }
func HiArrowTurnRightUp() icons.IsIcon      { return newIcon(solidIcon, "arrow-turn-right-up") }
func HiArrowTurnUpLeft() icons.IsIcon       { return newIcon(solidIcon, "arrow-turn-up-left") }
func HiArrowTurnUpRight() icons.IsIcon      { return newIcon(solidIcon, "arrow-turn-up-right") }
func HiArrowUpCircle() icons.IsIcon         { return newIcon(solidIcon, "arrow-up-circle") }
func HiArrowUpLeft() icons.IsIcon           { return newIcon(solidIcon, "arrow-up-left") }
func HiArrowUpOnSquareStack() icons.IsIcon  { return newIcon(solidIcon, "arrow-up-on-square-stack") }
func HiArrowUpOnSquare() icons.IsIcon       { return newIcon(solidIcon, "arrow-up-on-square") }
func HiArrowUpRight() icons.IsIcon          { return newIcon(solidIcon, "arrow-up-right") }
func HiArrowUpTray() icons.IsIcon           { return newIcon(solidIcon, "arrow-up-tray") }
func HiArrowUp() icons.IsIcon               { return newIcon(solidIcon, "arrow-up") }
func HiArrowUturnDown() icons.IsIcon        { return newIcon(solidIcon, "arrow-uturn-down") }
func HiArrowUturnLeft() icons.IsIcon        { return newIcon(solidIcon, "arrow-uturn-left") }
func HiArrowUturnRight() icons.IsIcon       { return newIcon(solidIcon, "arrow-uturn-right") }
func HiArrowUturnUp() icons.IsIcon          { return newIcon(solidIcon, "arrow-uturn-up") }
func HiArrowsPointingIn() icons.IsIcon      { return newIcon(solidIcon, "arrows-pointing-in") }
func HiArrowsPointingOut() icons.IsIcon     { return newIcon(solidIcon, "arrows-pointing-out") }
func HiArrowsRightLeft() icons.IsIcon       { return newIcon(solidIcon, "arrows-right-left") }
func HiArrowsUpDown() icons.IsIcon          { return newIcon(solidIcon, "arrows-up-down") }
func HiAtSymbol() icons.IsIcon              { return newIcon(solidIcon, "at-symbol") }
func HiBackspace() icons.IsIcon             { return newIcon(solidIcon, "backspace") }
func HiBackward() icons.IsIcon              { return newIcon(solidIcon, "backward") }
func HiBanknotes() icons.IsIcon             { return newIcon(solidIcon, "banknotes") }
func HiBars2() icons.IsIcon                 { return newIcon(solidIcon, "bars-2") }
func HiBars3BottomLeft() icons.IsIcon       { return newIcon(solidIcon, "bars-3-bottom-left") }
func HiBars3BottomRight() icons.IsIcon      { return newIcon(solidIcon, "bars-3-bottom-right") }
func HiBars3CenterLeft() icons.IsIcon       { return newIcon(solidIcon, "bars-3-center-left") }
func HiBars3() icons.IsIcon                 { return newIcon(solidIcon, "bars-3") }
func HiBars4() icons.IsIcon                 { return newIcon(solidIcon, "bars-4") }
func HiBarsArrowDown() icons.IsIcon         { return newIcon(solidIcon, "bars-arrow-down") }
func HiBarsArrowUp() icons.IsIcon           { return newIcon(solidIcon, "bars-arrow-up") }
func HiBattery0() icons.IsIcon              { return newIcon(solidIcon, "battery-0") }
func HiBattery100() icons.IsIcon            { return newIcon(solidIcon, "battery-100") }
func HiBattery50() icons.IsIcon             { return newIcon(solidIcon, "battery-50") }
func HiBeaker() icons.IsIcon                { return newIcon(solidIcon, "beaker") }
func HiBellAlert() icons.IsIcon             { return newIcon(solidIcon, "bell-alert") }
func HiBellSlash() icons.IsIcon             { return newIcon(solidIcon, "bell-slash") }
func HiBellSnooze() icons.IsIcon            { return newIcon(solidIcon, "bell-snooze") }
func HiBell() icons.IsIcon                  { return newIcon(solidIcon, "bell") }
func HiBold() icons.IsIcon                  { return newIcon(solidIcon, "bold") }
func HiBoltSlash() icons.IsIcon             { return newIcon(solidIcon, "bolt-slash") }
func HiBolt() icons.IsIcon                  { return newIcon(solidIcon, "bolt") }
func HiBookOpen() icons.IsIcon              { return newIcon(solidIcon, "book-open") }
func HiBookmarkSlash() icons.IsIcon         { return newIcon(solidIcon, "bookmark-slash") }
func HiBookmarkSquare() icons.IsIcon        { return newIcon(solidIcon, "bookmark-square") }
func HiBookmark() icons.IsIcon              { return newIcon(solidIcon, "bookmark") }
func HiBriefcase() icons.IsIcon             { return newIcon(solidIcon, "briefcase") }
func HiBugAnt() icons.IsIcon                { return newIcon(solidIcon, "bug-ant") }
func HiBuildingLibrary() icons.IsIcon       { return newIcon(solidIcon, "building-library") }
func HiBuildingOffice2() icons.IsIcon       { return newIcon(solidIcon, "building-office-2") }
func HiBuildingOffice() icons.IsIcon        { return newIcon(solidIcon, "building-office") }
func HiBuildingStorefront() icons.IsIcon    { return newIcon(solidIcon, "building-storefront") }
func HiCake() icons.IsIcon                  { return newIcon(solidIcon, "cake") }
func HiCalculator() icons.IsIcon            { return newIcon(solidIcon, "calculator") }
func HiCalendarDateRange() icons.IsIcon     { return newIcon(solidIcon, "calendar-date-range") }
func HiCalendarDays() icons.IsIcon          { return newIcon(solidIcon, "calendar-days") }
func HiCalendar() icons.IsIcon              { return newIcon(solidIcon, "calendar") }
func HiCamera() icons.IsIcon                { return newIcon(solidIcon, "camera") }
func HiChartBarSquare() icons.IsIcon        { return newIcon(solidIcon, "chart-bar-square") }
func HiChartBar() icons.IsIcon              { return newIcon(solidIcon, "chart-bar") }
func HiChartPie() icons.IsIcon              { return newIcon(solidIcon, "chart-pie") }
func HiChatBubbleBottomCenterText() icons.IsIcon {
	return newIcon(solidIcon, "chat-bubble-bottom-center-text")
}
func HiChatBubbleBottomCenter() icons.IsIcon { return newIcon(solidIcon, "chat-bubble-bottom-center") }
func HiChatBubbleLeftEllipsis() icons.IsIcon { return newIcon(solidIcon, "chat-bubble-left-ellipsis") }
func HiChatBubbleLeftRight() icons.IsIcon    { return newIcon(solidIcon, "chat-bubble-left-right") }
func HiChatBubbleLeft() icons.IsIcon         { return newIcon(solidIcon, "chat-bubble-left") }
func HiChatBubbleOvalLeftEllipsis() icons.IsIcon {
	return newIcon(solidIcon, "chat-bubble-oval-left-ellipsis")
}
func HiChatBubbleOvalLeft() icons.IsIcon     { return newIcon(solidIcon, "chat-bubble-oval-left") }
func HiCheckBadge() icons.IsIcon             { return newIcon(solidIcon, "check-badge") }
func HiCheckCircle() icons.IsIcon            { return newIcon(solidIcon, "check-circle") }
func HiCheck() icons.IsIcon                  { return newIcon(solidIcon, "check") }
func HiChevronDoubleDown() icons.IsIcon      { return newIcon(solidIcon, "chevron-double-down") }
func HiChevronDoubleLeft() icons.IsIcon      { return newIcon(solidIcon, "chevron-double-left") }
func HiChevronDoubleRight() icons.IsIcon     { return newIcon(solidIcon, "chevron-double-right") }
func HiChevronDoubleUp() icons.IsIcon        { return newIcon(solidIcon, "chevron-double-up") }
func HiChevronDown() icons.IsIcon            { return newIcon(solidIcon, "chevron-down") }
func HiChevronLeft() icons.IsIcon            { return newIcon(solidIcon, "chevron-left") }
func HiChevronRight() icons.IsIcon           { return newIcon(solidIcon, "chevron-right") }
func HiChevronUpDown() icons.IsIcon          { return newIcon(solidIcon, "chevron-up-down") }
func HiChevronUp() icons.IsIcon              { return newIcon(solidIcon, "chevron-up") }
func HiCircleStack() icons.IsIcon            { return newIcon(solidIcon, "circle-stack") }
func HiClipboardDocumentCheck() icons.IsIcon { return newIcon(solidIcon, "clipboard-document-check") }
func HiClipboardDocumentList() icons.IsIcon  { return newIcon(solidIcon, "clipboard-document-list") }
func HiClipboardDocument() icons.IsIcon      { return newIcon(solidIcon, "clipboard-document") }
func HiClipboard() icons.IsIcon              { return newIcon(solidIcon, "clipboard") }
func HiClock() icons.IsIcon                  { return newIcon(solidIcon, "clock") }
func HiCloudArrowDown() icons.IsIcon         { return newIcon(solidIcon, "cloud-arrow-down") }
func HiCloudArrowUp() icons.IsIcon           { return newIcon(solidIcon, "cloud-arrow-up") }
func HiCloud() icons.IsIcon                  { return newIcon(solidIcon, "cloud") }
func HiCodeBracketSquare() icons.IsIcon      { return newIcon(solidIcon, "code-bracket-square") }
func HiCodeBracket() icons.IsIcon            { return newIcon(solidIcon, "code-bracket") }
func HiCog6Tooth() icons.IsIcon              { return newIcon(solidIcon, "cog-6-tooth") }
func HiCog8Tooth() icons.IsIcon              { return newIcon(solidIcon, "cog-8-tooth") }
func HiCog() icons.IsIcon                    { return newIcon(solidIcon, "cog") }
func HiCommandLine() icons.IsIcon            { return newIcon(solidIcon, "command-line") }
func HiComputerDesktop() icons.IsIcon        { return newIcon(solidIcon, "computer-desktop") }
func HiCpuChip() icons.IsIcon                { return newIcon(solidIcon, "cpu-chip") }
func HiCreditCard() icons.IsIcon             { return newIcon(solidIcon, "credit-card") }
func HiCubeTransparent() icons.IsIcon        { return newIcon(solidIcon, "cube-transparent") }
func HiCube() icons.IsIcon                   { return newIcon(solidIcon, "cube") }
func HiCurrencyBangladeshi() icons.IsIcon    { return newIcon(solidIcon, "currency-bangladeshi") }
func HiCurrencyDollar() icons.IsIcon         { return newIcon(solidIcon, "currency-dollar") }
func HiCurrencyEuro() icons.IsIcon           { return newIcon(solidIcon, "currency-euro") }
func HiCurrencyPound() icons.IsIcon          { return newIcon(solidIcon, "currency-pound") }
func HiCurrencyRupee() icons.IsIcon          { return newIcon(solidIcon, "currency-rupee") }
func HiCurrencyYen() icons.IsIcon            { return newIcon(solidIcon, "currency-yen") }
func HiCursorArrowRays() icons.IsIcon        { return newIcon(solidIcon, "cursor-arrow-rays") }
func HiCursorArrowRipple() icons.IsIcon      { return newIcon(solidIcon, "cursor-arrow-ripple") }
func HiDevicePhoneMobile() icons.IsIcon      { return newIcon(solidIcon, "device-phone-mobile") }
func HiDeviceTablet() icons.IsIcon           { return newIcon(solidIcon, "device-tablet") }
func HiDivide() icons.IsIcon                 { return newIcon(solidIcon, "divide") }
func HiDocumentArrowDown() icons.IsIcon      { return newIcon(solidIcon, "document-arrow-down") }
func HiDocumentArrowUp() icons.IsIcon        { return newIcon(solidIcon, "document-arrow-up") }
func HiDocumentChartBar() icons.IsIcon       { return newIcon(solidIcon, "document-chart-bar") }
func HiDocumentCheck() icons.IsIcon          { return newIcon(solidIcon, "document-check") }
func HiDocumentCurrencyBangladeshi() icons.IsIcon {
	return newIcon(solidIcon, "document-currency-bangladeshi")
}
func HiDocumentCurrencyDollar() icons.IsIcon  { return newIcon(solidIcon, "document-currency-dollar") }
func HiDocumentCurrencyEuro() icons.IsIcon    { return newIcon(solidIcon, "document-currency-euro") }
func HiDocumentCurrencyPound() icons.IsIcon   { return newIcon(solidIcon, "document-currency-pound") }
func HiDocumentCurrencyRupee() icons.IsIcon   { return newIcon(solidIcon, "document-currency-rupee") }
func HiDocumentCurrencyYen() icons.IsIcon     { return newIcon(solidIcon, "document-currency-yen") }
func HiDocumentDuplicate() icons.IsIcon       { return newIcon(solidIcon, "document-duplicate") }
func HiDocumentMagnifyingGlass() icons.IsIcon { return newIcon(solidIcon, "document-magnifying-glass") }
func HiDocumentMinus() icons.IsIcon           { return newIcon(solidIcon, "document-minus") }
func HiDocumentPlus() icons.IsIcon            { return newIcon(solidIcon, "document-plus") }
func HiDocumentText() icons.IsIcon            { return newIcon(solidIcon, "document-text") }
func HiDocument() icons.IsIcon                { return newIcon(solidIcon, "document") }
func HiEllipsisHorizontalCircle() icons.IsIcon {
	return newIcon(solidIcon, "ellipsis-horizontal-circle")
}
func HiEllipsisHorizontal() icons.IsIcon    { return newIcon(solidIcon, "ellipsis-horizontal") }
func HiEllipsisVertical() icons.IsIcon      { return newIcon(solidIcon, "ellipsis-vertical") }
func HiEnvelopeOpen() icons.IsIcon          { return newIcon(solidIcon, "envelope-open") }
func HiEnvelope() icons.IsIcon              { return newIcon(solidIcon, "envelope") }
func HiEquals() icons.IsIcon                { return newIcon(solidIcon, "equals") }
func HiExclamationCircle() icons.IsIcon     { return newIcon(solidIcon, "exclamation-circle") }
func HiExclamationTriangle() icons.IsIcon   { return newIcon(solidIcon, "exclamation-triangle") }
func HiEyeDropper() icons.IsIcon            { return newIcon(solidIcon, "eye-dropper") }
func HiEyeSlash() icons.IsIcon              { return newIcon(solidIcon, "eye-slash") }
func HiEye() icons.IsIcon                   { return newIcon(solidIcon, "eye") }
func HiFaceFrown() icons.IsIcon             { return newIcon(solidIcon, "face-frown") }
func HiFaceSmile() icons.IsIcon             { return newIcon(solidIcon, "face-smile") }
func HiFilm() icons.IsIcon                  { return newIcon(solidIcon, "film") }
func HiFingerPrint() icons.IsIcon           { return newIcon(solidIcon, "finger-print") }
func HiFire() icons.IsIcon                  { return newIcon(solidIcon, "fire") }
func HiFlag() icons.IsIcon                  { return newIcon(solidIcon, "flag") }
func HiFolderArrowDown() icons.IsIcon       { return newIcon(solidIcon, "folder-arrow-down") }
func HiFolderMinus() icons.IsIcon           { return newIcon(solidIcon, "folder-minus") }
func HiFolderOpen() icons.IsIcon            { return newIcon(solidIcon, "folder-open") }
func HiFolderPlus() icons.IsIcon            { return newIcon(solidIcon, "folder-plus") }
func HiFolder() icons.IsIcon                { return newIcon(solidIcon, "folder") }
func HiForward() icons.IsIcon               { return newIcon(solidIcon, "forward") }
func HiFunnel() icons.IsIcon                { return newIcon(solidIcon, "funnel") }
func HiGif() icons.IsIcon                   { return newIcon(solidIcon, "gif") }
func HiGiftTop() icons.IsIcon               { return newIcon(solidIcon, "gift-top") }
func HiGift() icons.IsIcon                  { return newIcon(solidIcon, "gift") }
func HiGlobeAlt() icons.IsIcon              { return newIcon(solidIcon, "globe-alt") }
func HiGlobeAmericas() icons.IsIcon         { return newIcon(solidIcon, "globe-americas") }
func HiGlobeAsiaAustralia() icons.IsIcon    { return newIcon(solidIcon, "globe-asia-australia") }
func HiGlobeEuropeAfrica() icons.IsIcon     { return newIcon(solidIcon, "globe-europe-africa") }
func HiH1() icons.IsIcon                    { return newIcon(solidIcon, "h1") }
func HiH2() icons.IsIcon                    { return newIcon(solidIcon, "h2") }
func HiH3() icons.IsIcon                    { return newIcon(solidIcon, "h3") }
func HiHandRaised() icons.IsIcon            { return newIcon(solidIcon, "hand-raised") }
func HiHandThumbDown() icons.IsIcon         { return newIcon(solidIcon, "hand-thumb-down") }
func HiHandThumbUp() icons.IsIcon           { return newIcon(solidIcon, "hand-thumb-up") }
func HiHashtag() icons.IsIcon               { return newIcon(solidIcon, "hashtag") }
func HiHeart() icons.IsIcon                 { return newIcon(solidIcon, "heart") }
func HiHomeModern() icons.IsIcon            { return newIcon(solidIcon, "home-modern") }
func HiHome() icons.IsIcon                  { return newIcon(solidIcon, "home") }
func HiIdentification() icons.IsIcon        { return newIcon(solidIcon, "identification") }
func HiInboxArrowDown() icons.IsIcon        { return newIcon(solidIcon, "inbox-arrow-down") }
func HiInboxStack() icons.IsIcon            { return newIcon(solidIcon, "inbox-stack") }
func HiInbox() icons.IsIcon                 { return newIcon(solidIcon, "inbox") }
func HiInformationCircle() icons.IsIcon     { return newIcon(solidIcon, "information-circle") }
func HiItalic() icons.IsIcon                { return newIcon(solidIcon, "italic") }
func HiKey() icons.IsIcon                   { return newIcon(solidIcon, "key") }
func HiLanguage() icons.IsIcon              { return newIcon(solidIcon, "language") }
func HiLifebuoy() icons.IsIcon              { return newIcon(solidIcon, "lifebuoy") }
func HiLightBulb() icons.IsIcon             { return newIcon(solidIcon, "light-bulb") }
func HiLinkSlash() icons.IsIcon             { return newIcon(solidIcon, "link-slash") }
func HiLink() icons.IsIcon                  { return newIcon(solidIcon, "link") }
func HiListBullet() icons.IsIcon            { return newIcon(solidIcon, "list-bullet") }
func HiLockClosed() icons.IsIcon            { return newIcon(solidIcon, "lock-closed") }
func HiLockOpen() icons.IsIcon              { return newIcon(solidIcon, "lock-open") }
func HiMagnifyingGlassCircle() icons.IsIcon { return newIcon(solidIcon, "magnifying-glass-circle") }
func HiMagnifyingGlassMinus() icons.IsIcon  { return newIcon(solidIcon, "magnifying-glass-minus") }
func HiMagnifyingGlassPlus() icons.IsIcon   { return newIcon(solidIcon, "magnifying-glass-plus") }
func HiMagnifyingGlass() icons.IsIcon       { return newIcon(solidIcon, "magnifying-glass") }
func HiMapPin() icons.IsIcon                { return newIcon(solidIcon, "map-pin") }
func HiMap() icons.IsIcon                   { return newIcon(solidIcon, "map") }
func HiMegaphone() icons.IsIcon             { return newIcon(solidIcon, "megaphone") }
func HiMicrophone() icons.IsIcon            { return newIcon(solidIcon, "microphone") }
func HiMinusCircle() icons.IsIcon           { return newIcon(solidIcon, "minus-circle") }
func HiMinusSmall() icons.IsIcon            { return newIcon(solidIcon, "minus-small") }
func HiMinus() icons.IsIcon                 { return newIcon(solidIcon, "minus") }
func HiMoon() icons.IsIcon                  { return newIcon(solidIcon, "moon") }
func HiMusicalNote() icons.IsIcon           { return newIcon(solidIcon, "musical-note") }
func HiNewspaper() icons.IsIcon             { return newIcon(solidIcon, "newspaper") }
func HiNoSymbol() icons.IsIcon              { return newIcon(solidIcon, "no-symbol") }
func HiNumberedList() icons.IsIcon          { return newIcon(solidIcon, "numbered-list") }
func HiPaintBrush() icons.IsIcon            { return newIcon(solidIcon, "paint-brush") }
func HiPaperAirplane() icons.IsIcon         { return newIcon(solidIcon, "paper-airplane") }
func HiPaperClip() icons.IsIcon             { return newIcon(solidIcon, "paper-clip") }
func HiPauseCircle() icons.IsIcon           { return newIcon(solidIcon, "pause-circle") }
func HiPause() icons.IsIcon                 { return newIcon(solidIcon, "pause") }
func HiPencilSquare() icons.IsIcon          { return newIcon(solidIcon, "pencil-square") }
func HiPencil() icons.IsIcon                { return newIcon(solidIcon, "pencil") }
func HiPercentBadge() icons.IsIcon          { return newIcon(solidIcon, "percent-badge") }
func HiPhoneArrowDownLeft() icons.IsIcon    { return newIcon(solidIcon, "phone-arrow-down-left") }
func HiPhoneArrowUpRight() icons.IsIcon     { return newIcon(solidIcon, "phone-arrow-up-right") }
func HiPhoneXMark() icons.IsIcon            { return newIcon(solidIcon, "phone-x-mark") }
func HiPhone() icons.IsIcon                 { return newIcon(solidIcon, "phone") }
func HiPhoto() icons.IsIcon                 { return newIcon(solidIcon, "photo") }
func HiPlayCircle() icons.IsIcon            { return newIcon(solidIcon, "play-circle") }
func HiPlayPause() icons.IsIcon             { return newIcon(solidIcon, "play-pause") }
func HiPlay() icons.IsIcon                  { return newIcon(solidIcon, "play") }
func HiPlusCircle() icons.IsIcon            { return newIcon(solidIcon, "plus-circle") }
func HiPlusSmall() icons.IsIcon             { return newIcon(solidIcon, "plus-small") }
func HiPlus() icons.IsIcon                  { return newIcon(solidIcon, "plus") }
func HiPower() icons.IsIcon                 { return newIcon(solidIcon, "power") }
func HiPresentationChartBar() icons.IsIcon  { return newIcon(solidIcon, "presentation-chart-bar") }
func HiPresentationChartLine() icons.IsIcon { return newIcon(solidIcon, "presentation-chart-line") }
func HiPrinter() icons.IsIcon               { return newIcon(solidIcon, "printer") }
func HiPuzzlePiece() icons.IsIcon           { return newIcon(solidIcon, "puzzle-piece") }
func HiQrCode() icons.IsIcon                { return newIcon(solidIcon, "qr-code") }
func HiQuestionMarkCircle() icons.IsIcon    { return newIcon(solidIcon, "question-mark-circle") }
func HiQueueList() icons.IsIcon             { return newIcon(solidIcon, "queue-list") }
func HiRadio() icons.IsIcon                 { return newIcon(solidIcon, "radio") }
func HiReceiptPercent() icons.IsIcon        { return newIcon(solidIcon, "receipt-percent") }
func HiReceiptRefund() icons.IsIcon         { return newIcon(solidIcon, "receipt-refund") }
func HiRectangleGroup() icons.IsIcon        { return newIcon(solidIcon, "rectangle-group") }
func HiRectangleStack() icons.IsIcon        { return newIcon(solidIcon, "rectangle-stack") }
func HiRocketLaunch() icons.IsIcon          { return newIcon(solidIcon, "rocket-launch") }
func HiRss() icons.IsIcon                   { return newIcon(solidIcon, "rss") }
func HiScale() icons.IsIcon                 { return newIcon(solidIcon, "scale") }
func HiScissors() icons.IsIcon              { return newIcon(solidIcon, "scissors") }
func HiServerStack() icons.IsIcon           { return newIcon(solidIcon, "server-stack") }
func HiServer() icons.IsIcon                { return newIcon(solidIcon, "server") }
func HiShare() icons.IsIcon                 { return newIcon(solidIcon, "share") }
func HiShieldCheck() icons.IsIcon           { return newIcon(solidIcon, "shield-check") }
func HiShieldExclamation() icons.IsIcon     { return newIcon(solidIcon, "shield-exclamation") }
func HiShoppingBag() icons.IsIcon           { return newIcon(solidIcon, "shopping-bag") }
func HiShoppingCart() icons.IsIcon          { return newIcon(solidIcon, "shopping-cart") }
func HiSignalSlash() icons.IsIcon           { return newIcon(solidIcon, "signal-slash") }
func HiSignal() icons.IsIcon                { return newIcon(solidIcon, "signal") }
func HiSlash() icons.IsIcon                 { return newIcon(solidIcon, "slash") }
func HiSparkles() icons.IsIcon              { return newIcon(solidIcon, "sparkles") }
func HiSpeakerWave() icons.IsIcon           { return newIcon(solidIcon, "speaker-wave") }
func HiSpeakerXMark() icons.IsIcon          { return newIcon(solidIcon, "speaker-x-mark") }
func HiSquare2Stack() icons.IsIcon          { return newIcon(solidIcon, "square-2-stack") }
func HiSquare3Stack3D() icons.IsIcon        { return newIcon(solidIcon, "square-3-stack-3d") }
func HiSquares2X2() icons.IsIcon            { return newIcon(solidIcon, "squares-2x2") }
func HiSquaresPlus() icons.IsIcon           { return newIcon(solidIcon, "squares-plus") }
func HiStar() icons.IsIcon                  { return newIcon(solidIcon, "star") }
func HiStopCircle() icons.IsIcon            { return newIcon(solidIcon, "stop-circle") }
func HiStop() icons.IsIcon                  { return newIcon(solidIcon, "stop") }
func HiStrikethrough() icons.IsIcon         { return newIcon(solidIcon, "strikethrough") }
func HiSun() icons.IsIcon                   { return newIcon(solidIcon, "sun") }
func HiSwatch() icons.IsIcon                { return newIcon(solidIcon, "swatch") }
func HiTableCells() icons.IsIcon            { return newIcon(solidIcon, "table-cells") }
func HiTag() icons.IsIcon                   { return newIcon(solidIcon, "tag") }
func HiTicket() icons.IsIcon                { return newIcon(solidIcon, "ticket") }
func HiTrash() icons.IsIcon                 { return newIcon(solidIcon, "trash") }
func HiTrophy() icons.IsIcon                { return newIcon(solidIcon, "trophy") }
func HiTruck() icons.IsIcon                 { return newIcon(solidIcon, "truck") }
func HiTv() icons.IsIcon                    { return newIcon(solidIcon, "tv") }
func HiUnderline() icons.IsIcon             { return newIcon(solidIcon, "underline") }
func HiUserCircle() icons.IsIcon            { return newIcon(solidIcon, "user-circle") }
func HiUserGroup() icons.IsIcon             { return newIcon(solidIcon, "user-group") }
func HiUserMinus() icons.IsIcon             { return newIcon(solidIcon, "user-minus") }
func HiUserPlus() icons.IsIcon              { return newIcon(solidIcon, "user-plus") }
func HiUser() icons.IsIcon                  { return newIcon(solidIcon, "user") }
func HiUsers() icons.IsIcon                 { return newIcon(solidIcon, "users") }
func HiVariable() icons.IsIcon              { return newIcon(solidIcon, "variable") }
func HiVideoCameraSlash() icons.IsIcon      { return newIcon(solidIcon, "video-camera-slash") }
func HiVideoCamera() icons.IsIcon           { return newIcon(solidIcon, "video-camera") }
func HiViewColumns() icons.IsIcon           { return newIcon(solidIcon, "view-columns") }
func HiViewfinderCircle() icons.IsIcon      { return newIcon(solidIcon, "viewfinder-circle") }
func HiWallet() icons.IsIcon                { return newIcon(solidIcon, "wallet") }
func HiWifi() icons.IsIcon                  { return newIcon(solidIcon, "wifi") }
func HiWindow() icons.IsIcon                { return newIcon(solidIcon, "window") }
func HiWrenchScrewdriver() icons.IsIcon     { return newIcon(solidIcon, "wrench-screwdriver") }
func HiWrench() icons.IsIcon                { return newIcon(solidIcon, "wrench") }
func HiXCircle() icons.IsIcon               { return newIcon(solidIcon, "x-circle") }
func HiXMark() icons.IsIcon                 { return newIcon(solidIcon, "x-mark") }
