package main

import "github.com/raitucarp/gomix/components"

func Render(componentName string) components.IsComponent {
    switch componentName {
	case "accordion_item":
		return RenderAccordionItem()
	case "skeleton":
		return RenderSkeleton()
	case "v_stack":
		return RenderVStack()
	case "tag":
		return RenderTag()
	case "icon":
		return RenderIcon()
	case "spacer":
		return RenderSpacer()
	case "pin_input":
		return RenderPinInput()
	case "tabs":
		return RenderTabs()
	case "modal":
		return RenderModal()
	case "spinner":
		return RenderSpinner()
	case "switch_cmp":
		return RenderSwitchCmp()
	case "toast":
		return RenderToast()
	case "checkbox":
		return RenderCheckbox()
	case "code":
		return RenderCode()
	case "tab":
		return RenderTab()
	case "circular_progress":
		return RenderCircularProgress()
	case "stat":
		return RenderStat()
	case "wrap":
		return RenderWrap()
	case "tooltip":
		return RenderTooltip()
	case "button":
		return RenderButton()
	case "table":
		return RenderTable()
	case "select_native":
		return RenderSelectNative()
	case "alert":
		return RenderAlert()
	case "tab_panels":
		return RenderTabPanels()
	case "visually_hidden":
		return RenderVisuallyHidden()
	case "tab_list":
		return RenderTabList()
	case "icon_button":
		return RenderIconButton()
	case "accordion":
		return RenderAccordion()
	case "disclosure":
		return RenderDisclosure()
	case "text_cmp":
		return RenderTextCmp()
	case "slider":
		return RenderSlider()
	case "menu":
		return RenderMenu()
	case "simple_grid":
		return RenderSimpleGrid()
	case "close_button":
		return RenderCloseButton()
	case "alert_dialog":
		return RenderAlertDialog()
	case "number_input":
		return RenderNumberInput()
	case "radio":
		return RenderRadio()
	case "textarea":
		return RenderTextarea()
	case "grid":
		return RenderGrid()
	case "progress":
		return RenderProgress()
	case "stack":
		return RenderStack()
	case "badge":
		return RenderBadge()
	case "h_stack":
		return RenderHStack()
	case "avatar":
		return RenderAvatar()
	case "heading":
		return RenderHeading()
	case "popover":
		return RenderPopover()
	case "divider":
		return RenderDivider()
	case "center":
		return RenderCenter()
	case "image":
		return RenderImage()
	case "drawer":
		return RenderDrawer()
	case "input":
		return RenderInput()
	case "kbd":
		return RenderKbd()
	case "tab_panel":
		return RenderTabPanel()
    default:
        return nil
    }
}
