package octicons

import "github.com/raitucarp/gomix/icons"

func GoAccessibilityInset() icons.IsIcon        { return newIcon("accessibility-inset") }
func GoAccessibility() icons.IsIcon             { return newIcon("accessibility") }
func GoAgent() icons.IsIcon                     { return newIcon("agent") }
func GoAiModel() icons.IsIcon                   { return newIcon("ai-model") }
func GoAlertFill() icons.IsIcon                 { return newIcon("alert-fill") }
func GoAlert() icons.IsIcon                     { return newIcon("alert") }
func GoApps() icons.IsIcon                      { return newIcon("apps") }
func GoArchive() icons.IsIcon                   { return newIcon("archive") }
func GoArrowBoth() icons.IsIcon                 { return newIcon("arrow-both") }
func GoArrowDownLeft() icons.IsIcon             { return newIcon("arrow-down-left") }
func GoArrowDownRight() icons.IsIcon            { return newIcon("arrow-down-right") }
func GoArrowDown() icons.IsIcon                 { return newIcon("arrow-down") }
func GoArrowLeft() icons.IsIcon                 { return newIcon("arrow-left") }
func GoArrowRight() icons.IsIcon                { return newIcon("arrow-right") }
func GoArrowSwitch() icons.IsIcon               { return newIcon("arrow-switch") }
func GoArrowUpLeft() icons.IsIcon               { return newIcon("arrow-up-left") }
func GoArrowUpRight() icons.IsIcon              { return newIcon("arrow-up-right") }
func GoArrowUp() icons.IsIcon                   { return newIcon("arrow-up") }
func GoBeaker() icons.IsIcon                    { return newIcon("beaker") }
func GoBellFill() icons.IsIcon                  { return newIcon("bell-fill") }
func GoBellSlash() icons.IsIcon                 { return newIcon("bell-slash") }
func GoBell() icons.IsIcon                      { return newIcon("bell") }
func GoBlocked() icons.IsIcon                   { return newIcon("blocked") }
func GoBold() icons.IsIcon                      { return newIcon("bold") }
func GoBook() icons.IsIcon                      { return newIcon("book") }
func GoBookmarkFill() icons.IsIcon              { return newIcon("bookmark-fill") }
func GoBookmarkSlashFill() icons.IsIcon         { return newIcon("bookmark-slash-fill") }
func GoBookmarkSlash() icons.IsIcon             { return newIcon("bookmark-slash") }
func GoBookmark() icons.IsIcon                  { return newIcon("bookmark") }
func GoBriefcase() icons.IsIcon                 { return newIcon("briefcase") }
func GoBroadcast() icons.IsIcon                 { return newIcon("broadcast") }
func GoBrowser() icons.IsIcon                   { return newIcon("browser") }
func GoBug() icons.IsIcon                       { return newIcon("bug") }
func GoCache() icons.IsIcon                     { return newIcon("cache") }
func GoCalendar() icons.IsIcon                  { return newIcon("calendar") }
func GoCheckCircleFill() icons.IsIcon           { return newIcon("check-circle-fill") }
func GoCheckCircle() icons.IsIcon               { return newIcon("check-circle") }
func GoCheck() icons.IsIcon                     { return newIcon("check") }
func GoCheckboxFill() icons.IsIcon              { return newIcon("checkbox-fill") }
func GoCheckbox() icons.IsIcon                  { return newIcon("checkbox") }
func GoChecklist() icons.IsIcon                 { return newIcon("checklist") }
func GoChevronDown() icons.IsIcon               { return newIcon("chevron-down") }
func GoChevronLeft() icons.IsIcon               { return newIcon("chevron-left") }
func GoChevronRight() icons.IsIcon              { return newIcon("chevron-right") }
func GoChevronUp() icons.IsIcon                 { return newIcon("chevron-up") }
func GoCircleSlash() icons.IsIcon               { return newIcon("circle-slash") }
func GoCircle() icons.IsIcon                    { return newIcon("circle") }
func GoClockFill() icons.IsIcon                 { return newIcon("clock-fill") }
func GoClock() icons.IsIcon                     { return newIcon("clock") }
func GoCloudOffline() icons.IsIcon              { return newIcon("cloud-offline") }
func GoCloud() icons.IsIcon                     { return newIcon("cloud") }
func GoCodeOfConduct() icons.IsIcon             { return newIcon("code-of-conduct") }
func GoCodeReview() icons.IsIcon                { return newIcon("code-review") }
func GoCodeSquare() icons.IsIcon                { return newIcon("code-square") }
func GoCode() icons.IsIcon                      { return newIcon("code") }
func GoCodescanCheckmark() icons.IsIcon         { return newIcon("codescan-checkmark") }
func GoCodescan() icons.IsIcon                  { return newIcon("codescan") }
func GoCodespaces() icons.IsIcon                { return newIcon("codespaces") }
func GoColumns() icons.IsIcon                   { return newIcon("columns") }
func GoCommandPalette() icons.IsIcon            { return newIcon("command-palette") }
func GoCommentAi() icons.IsIcon                 { return newIcon("comment-ai") }
func GoCommentDiscussion() icons.IsIcon         { return newIcon("comment-discussion") }
func GoComment() icons.IsIcon                   { return newIcon("comment") }
func GoContainer() icons.IsIcon                 { return newIcon("container") }
func GoCopilot48() icons.IsIcon                 { return newIcon("copilot-48") }
func GoCopilot96() icons.IsIcon                 { return newIcon("copilot-96") }
func GoCopilot() icons.IsIcon                   { return newIcon("copilot") }
func GoCopy() icons.IsIcon                      { return newIcon("copy") }
func GoCpu() icons.IsIcon                       { return newIcon("cpu") }
func GoCreditCard() icons.IsIcon                { return newIcon("credit-card") }
func GoCrossReference() icons.IsIcon            { return newIcon("cross-reference") }
func GoDash() icons.IsIcon                      { return newIcon("dash") }
func GoDatabase() icons.IsIcon                  { return newIcon("database") }
func GoDependabot() icons.IsIcon                { return newIcon("dependabot") }
func GoDesktopDownload() icons.IsIcon           { return newIcon("desktop-download") }
func GoDeviceCameraVideo() icons.IsIcon         { return newIcon("device-camera-video") }
func GoDeviceCamera() icons.IsIcon              { return newIcon("device-camera") }
func GoDeviceDesktop() icons.IsIcon             { return newIcon("device-desktop") }
func GoDeviceMobile() icons.IsIcon              { return newIcon("device-mobile") }
func GoDevices() icons.IsIcon                   { return newIcon("devices") }
func GoDiamond() icons.IsIcon                   { return newIcon("diamond") }
func GoDiffAdded() icons.IsIcon                 { return newIcon("diff-added") }
func GoDiffIgnored() icons.IsIcon               { return newIcon("diff-ignored") }
func GoDiffModified() icons.IsIcon              { return newIcon("diff-modified") }
func GoDiffRemoved() icons.IsIcon               { return newIcon("diff-removed") }
func GoDiffRenamed() icons.IsIcon               { return newIcon("diff-renamed") }
func GoDiff() icons.IsIcon                      { return newIcon("diff") }
func GoDiscussionClosed() icons.IsIcon          { return newIcon("discussion-closed") }
func GoDiscussionDuplicate() icons.IsIcon       { return newIcon("discussion-duplicate") }
func GoDiscussionOutdated() icons.IsIcon        { return newIcon("discussion-outdated") }
func GoDotFill() icons.IsIcon                   { return newIcon("dot-fill") }
func GoDot() icons.IsIcon                       { return newIcon("dot") }
func GoDownload() icons.IsIcon                  { return newIcon("download") }
func GoDuplicate() icons.IsIcon                 { return newIcon("duplicate") }
func GoEllipsis() icons.IsIcon                  { return newIcon("ellipsis") }
func GoEyeClosed() icons.IsIcon                 { return newIcon("eye-closed") }
func GoEye() icons.IsIcon                       { return newIcon("eye") }
func GoFileAdded() icons.IsIcon                 { return newIcon("file-added") }
func GoFileBadge() icons.IsIcon                 { return newIcon("file-badge") }
func GoFileBinary() icons.IsIcon                { return newIcon("file-binary") }
func GoFileCode() icons.IsIcon                  { return newIcon("file-code") }
func GoFileDiff() icons.IsIcon                  { return newIcon("file-diff") }
func GoFileDirectoryFill() icons.IsIcon         { return newIcon("file-directory-fill") }
func GoFileDirectoryOpenFill() icons.IsIcon     { return newIcon("file-directory-open-fill") }
func GoFileDirectorySymlink() icons.IsIcon      { return newIcon("file-directory-symlink") }
func GoFileDirectory() icons.IsIcon             { return newIcon("file-directory") }
func GoFileMedia() icons.IsIcon                 { return newIcon("file-media") }
func GoFileMoved() icons.IsIcon                 { return newIcon("file-moved") }
func GoFileRemoved() icons.IsIcon               { return newIcon("file-removed") }
func GoFileSubmodule() icons.IsIcon             { return newIcon("file-submodule") }
func GoFileSymlinkFile() icons.IsIcon           { return newIcon("file-symlink-file") }
func GoFileZip() icons.IsIcon                   { return newIcon("file-zip") }
func GoFile() icons.IsIcon                      { return newIcon("file") }
func GoFilterRemove() icons.IsIcon              { return newIcon("filter-remove") }
func GoFilter() icons.IsIcon                    { return newIcon("filter") }
func GoFiscalHost() icons.IsIcon                { return newIcon("fiscal-host") }
func GoFlame() icons.IsIcon                     { return newIcon("flame") }
func GoFoldDown() icons.IsIcon                  { return newIcon("fold-down") }
func GoFoldUp() icons.IsIcon                    { return newIcon("fold-up") }
func GoFold() icons.IsIcon                      { return newIcon("fold") }
func GoGear() icons.IsIcon                      { return newIcon("gear") }
func GoGift() icons.IsIcon                      { return newIcon("gift") }
func GoGitBranch() icons.IsIcon                 { return newIcon("git-branch") }
func GoGitCommit() icons.IsIcon                 { return newIcon("git-commit") }
func GoGitCompare() icons.IsIcon                { return newIcon("git-compare") }
func GoGitMergeQueue() icons.IsIcon             { return newIcon("git-merge-queue") }
func GoGitMerge() icons.IsIcon                  { return newIcon("git-merge") }
func GoGitPullRequestClosed() icons.IsIcon      { return newIcon("git-pull-request-closed") }
func GoGitPullRequestDraft() icons.IsIcon       { return newIcon("git-pull-request-draft") }
func GoGitPullRequest() icons.IsIcon            { return newIcon("git-pull-request") }
func GoGlobe() icons.IsIcon                     { return newIcon("globe") }
func GoGoal() icons.IsIcon                      { return newIcon("goal") }
func GoGrabber() icons.IsIcon                   { return newIcon("grabber") }
func GoGraph() icons.IsIcon                     { return newIcon("graph") }
func GoHash() icons.IsIcon                      { return newIcon("hash") }
func GoHeading() icons.IsIcon                   { return newIcon("heading") }
func GoHeartFill() icons.IsIcon                 { return newIcon("heart-fill") }
func GoHeart() icons.IsIcon                     { return newIcon("heart") }
func GoHistory() icons.IsIcon                   { return newIcon("history") }
func GoHomeFill() icons.IsIcon                  { return newIcon("home-fill") }
func GoHome() icons.IsIcon                      { return newIcon("home") }
func GoHorizontalRule() icons.IsIcon            { return newIcon("horizontal-rule") }
func GoHourglass() icons.IsIcon                 { return newIcon("hourglass") }
func GoHubot() icons.IsIcon                     { return newIcon("hubot") }
func GoIdBadge() icons.IsIcon                   { return newIcon("id-badge") }
func GoImage() icons.IsIcon                     { return newIcon("image") }
func GoInbox() icons.IsIcon                     { return newIcon("inbox") }
func GoInfinity() icons.IsIcon                  { return newIcon("infinity") }
func GoInfo() icons.IsIcon                      { return newIcon("info") }
func GoIssueClosed() icons.IsIcon               { return newIcon("issue-closed") }
func GoIssueDraft() icons.IsIcon                { return newIcon("issue-draft") }
func GoIssueOpened() icons.IsIcon               { return newIcon("issue-opened") }
func GoIssueReopened() icons.IsIcon             { return newIcon("issue-reopened") }
func GoIssueTrackedBy() icons.IsIcon            { return newIcon("issue-tracked-by") }
func GoIssueTracks() icons.IsIcon               { return newIcon("issue-tracks") }
func GoItalic() icons.IsIcon                    { return newIcon("italic") }
func GoIterations() icons.IsIcon                { return newIcon("iterations") }
func GoKebabHorizontal() icons.IsIcon           { return newIcon("kebab-horizontal") }
func GoKeyAsterisk() icons.IsIcon               { return newIcon("key-asterisk") }
func GoKey() icons.IsIcon                       { return newIcon("key") }
func GoLaw() icons.IsIcon                       { return newIcon("law") }
func GoLightBulb() icons.IsIcon                 { return newIcon("light-bulb") }
func GoLinkExternal() icons.IsIcon              { return newIcon("link-external") }
func GoLink() icons.IsIcon                      { return newIcon("link") }
func GoListOrdered() icons.IsIcon               { return newIcon("list-ordered") }
func GoListUnordered() icons.IsIcon             { return newIcon("list-unordered") }
func GoLocation() icons.IsIcon                  { return newIcon("location") }
func GoLock() icons.IsIcon                      { return newIcon("lock") }
func GoLog() icons.IsIcon                       { return newIcon("log") }
func GoLogoGist() icons.IsIcon                  { return newIcon("logo-gist") }
func GoLogoGithub() icons.IsIcon                { return newIcon("logo-github") }
func GoLoop() icons.IsIcon                      { return newIcon("loop") }
func GoMail() icons.IsIcon                      { return newIcon("mail") }
func GoMarkGithub() icons.IsIcon                { return newIcon("mark-github") }
func GoMarkdown() icons.IsIcon                  { return newIcon("markdown") }
func GoMaximize() icons.IsIcon                  { return newIcon("maximize") }
func GoMcp() icons.IsIcon                       { return newIcon("mcp") }
func GoMegaphone() icons.IsIcon                 { return newIcon("megaphone") }
func GoMention() icons.IsIcon                   { return newIcon("mention") }
func GoMeter() icons.IsIcon                     { return newIcon("meter") }
func GoMilestone() icons.IsIcon                 { return newIcon("milestone") }
func GoMinimize() icons.IsIcon                  { return newIcon("minimize") }
func GoMirror() icons.IsIcon                    { return newIcon("mirror") }
func GoMoon() icons.IsIcon                      { return newIcon("moon") }
func GoMortarBoard() icons.IsIcon               { return newIcon("mortar-board") }
func GoMoveToBottom() icons.IsIcon              { return newIcon("move-to-bottom") }
func GoMoveToEnd() icons.IsIcon                 { return newIcon("move-to-end") }
func GoMoveToStart() icons.IsIcon               { return newIcon("move-to-start") }
func GoMoveToTop() icons.IsIcon                 { return newIcon("move-to-top") }
func GoMultiSelect() icons.IsIcon               { return newIcon("multi-select") }
func GoMute() icons.IsIcon                      { return newIcon("mute") }
func GoNoEntry() icons.IsIcon                   { return newIcon("no-entry") }
func GoNorthStar() icons.IsIcon                 { return newIcon("north-star") }
func GoNote() icons.IsIcon                      { return newIcon("note") }
func GoNumber() icons.IsIcon                    { return newIcon("number") }
func GoOrganization() icons.IsIcon              { return newIcon("organization") }
func GoPackageDependencies() icons.IsIcon       { return newIcon("package-dependencies") }
func GoPackageDependents() icons.IsIcon         { return newIcon("package-dependents") }
func GoPackage() icons.IsIcon                   { return newIcon("package") }
func GoPaintbrush() icons.IsIcon                { return newIcon("paintbrush") }
func GoPaperAirplane() icons.IsIcon             { return newIcon("paper-airplane") }
func GoPaperclip() icons.IsIcon                 { return newIcon("paperclip") }
func GoPasskeyFill() icons.IsIcon               { return newIcon("passkey-fill") }
func GoPaste() icons.IsIcon                     { return newIcon("paste") }
func GoPause() icons.IsIcon                     { return newIcon("pause") }
func GoPencil() icons.IsIcon                    { return newIcon("pencil") }
func GoPeople() icons.IsIcon                    { return newIcon("people") }
func GoPersonAdd() icons.IsIcon                 { return newIcon("person-add") }
func GoPersonFill() icons.IsIcon                { return newIcon("person-fill") }
func GoPerson() icons.IsIcon                    { return newIcon("person") }
func GoPinSlash() icons.IsIcon                  { return newIcon("pin-slash") }
func GoPin() icons.IsIcon                       { return newIcon("pin") }
func GoPivotColumn() icons.IsIcon               { return newIcon("pivot-column") }
func GoPlay() icons.IsIcon                      { return newIcon("play") }
func GoPlug() icons.IsIcon                      { return newIcon("plug") }
func GoPlusCircle() icons.IsIcon                { return newIcon("plus-circle") }
func GoPlus() icons.IsIcon                      { return newIcon("plus") }
func GoProjectRoadmap() icons.IsIcon            { return newIcon("project-roadmap") }
func GoProjectSymlink() icons.IsIcon            { return newIcon("project-symlink") }
func GoProjectTemplate() icons.IsIcon           { return newIcon("project-template") }
func GoProject() icons.IsIcon                   { return newIcon("project") }
func GoPulse() icons.IsIcon                     { return newIcon("pulse") }
func GoQuestion() icons.IsIcon                  { return newIcon("question") }
func GoQuote() icons.IsIcon                     { return newIcon("quote") }
func GoRead() icons.IsIcon                      { return newIcon("read") }
func GoRedo() icons.IsIcon                      { return newIcon("redo") }
func GoRelFilePath() icons.IsIcon               { return newIcon("rel-file-path") }
func GoReply() icons.IsIcon                     { return newIcon("reply") }
func GoRepoClone() icons.IsIcon                 { return newIcon("repo-clone") }
func GoRepoDelete() icons.IsIcon                { return newIcon("repo-delete") }
func GoRepoForked() icons.IsIcon                { return newIcon("repo-forked") }
func GoRepoLocked() icons.IsIcon                { return newIcon("repo-locked") }
func GoRepoPull() icons.IsIcon                  { return newIcon("repo-pull") }
func GoRepoPush() icons.IsIcon                  { return newIcon("repo-push") }
func GoRepoTemplate() icons.IsIcon              { return newIcon("repo-template") }
func GoRepo() icons.IsIcon                      { return newIcon("repo") }
func GoReport() icons.IsIcon                    { return newIcon("report") }
func GoRocket() icons.IsIcon                    { return newIcon("rocket") }
func GoRows() icons.IsIcon                      { return newIcon("rows") }
func GoRss() icons.IsIcon                       { return newIcon("rss") }
func GoRuby() icons.IsIcon                      { return newIcon("ruby") }
func GoScreenFull() icons.IsIcon                { return newIcon("screen-full") }
func GoScreenNormal() icons.IsIcon              { return newIcon("screen-normal") }
func GoSearch() icons.IsIcon                    { return newIcon("search") }
func GoServer() icons.IsIcon                    { return newIcon("server") }
func GoShareAndroid() icons.IsIcon              { return newIcon("share-android") }
func GoShare() icons.IsIcon                     { return newIcon("share") }
func GoShieldCheck() icons.IsIcon               { return newIcon("shield-check") }
func GoShieldLock() icons.IsIcon                { return newIcon("shield-lock") }
func GoShieldSlash() icons.IsIcon               { return newIcon("shield-slash") }
func GoShieldX() icons.IsIcon                   { return newIcon("shield-x") }
func GoShield() icons.IsIcon                    { return newIcon("shield") }
func GoSidebarCollapse() icons.IsIcon           { return newIcon("sidebar-collapse") }
func GoSidebarExpand() icons.IsIcon             { return newIcon("sidebar-expand") }
func GoSignIn() icons.IsIcon                    { return newIcon("sign-in") }
func GoSignOut() icons.IsIcon                   { return newIcon("sign-out") }
func GoSingleSelect() icons.IsIcon              { return newIcon("single-select") }
func GoSkipFill() icons.IsIcon                  { return newIcon("skip-fill") }
func GoSkip() icons.IsIcon                      { return newIcon("skip") }
func GoSliders() icons.IsIcon                   { return newIcon("sliders") }
func GoSmiley() icons.IsIcon                    { return newIcon("smiley") }
func GoSortAsc() icons.IsIcon                   { return newIcon("sort-asc") }
func GoSortDesc() icons.IsIcon                  { return newIcon("sort-desc") }
func GoSpace() icons.IsIcon                     { return newIcon("space") }
func GoSparkleFill() icons.IsIcon               { return newIcon("sparkle-fill") }
func GoSparkle() icons.IsIcon                   { return newIcon("sparkle") }
func GoSparklesFill() icons.IsIcon              { return newIcon("sparkles-fill") }
func GoSponsorTiers() icons.IsIcon              { return newIcon("sponsor-tiers") }
func GoSquareCircle() icons.IsIcon              { return newIcon("square-circle") }
func GoSquareFill() icons.IsIcon                { return newIcon("square-fill") }
func GoSquare() icons.IsIcon                    { return newIcon("square") }
func GoSquirrel() icons.IsIcon                  { return newIcon("squirrel") }
func GoStack() icons.IsIcon                     { return newIcon("stack") }
func GoStarFill() icons.IsIcon                  { return newIcon("star-fill") }
func GoStar() icons.IsIcon                      { return newIcon("star") }
func GoStop() icons.IsIcon                      { return newIcon("stop") }
func GoStopwatch() icons.IsIcon                 { return newIcon("stopwatch") }
func GoStrikethrough() icons.IsIcon             { return newIcon("strikethrough") }
func GoSun() icons.IsIcon                       { return newIcon("sun") }
func GoSync() icons.IsIcon                      { return newIcon("sync") }
func GoTabExternal() icons.IsIcon               { return newIcon("tab-external") }
func GoTab() icons.IsIcon                       { return newIcon("tab") }
func GoTable() icons.IsIcon                     { return newIcon("table") }
func GoTag() icons.IsIcon                       { return newIcon("tag") }
func GoTasklist() icons.IsIcon                  { return newIcon("tasklist") }
func GoTelescopeFill() icons.IsIcon             { return newIcon("telescope-fill") }
func GoTelescope() icons.IsIcon                 { return newIcon("telescope") }
func GoTerminal() icons.IsIcon                  { return newIcon("terminal") }
func GoThreeBars() icons.IsIcon                 { return newIcon("three-bars") }
func GoThumbsdown() icons.IsIcon                { return newIcon("thumbsdown") }
func GoThumbsup() icons.IsIcon                  { return newIcon("thumbsup") }
func GoTools() icons.IsIcon                     { return newIcon("tools") }
func GoTrackedByClosedCompleted() icons.IsIcon  { return newIcon("tracked-by-closed-completed") }
func GoTrackedByClosedNotPlanned() icons.IsIcon { return newIcon("tracked-by-closed-not-planned") }
func GoTrash() icons.IsIcon                     { return newIcon("trash") }
func GoTriangleDown() icons.IsIcon              { return newIcon("triangle-down") }
func GoTriangleLeft() icons.IsIcon              { return newIcon("triangle-left") }
func GoTriangleRight() icons.IsIcon             { return newIcon("triangle-right") }
func GoTriangleUp() icons.IsIcon                { return newIcon("triangle-up") }
func GoTrophy() icons.IsIcon                    { return newIcon("trophy") }
func GoTypography() icons.IsIcon                { return newIcon("typography") }
func GoUndo() icons.IsIcon                      { return newIcon("undo") }
func GoUnfold() icons.IsIcon                    { return newIcon("unfold") }
func GoUnlink() icons.IsIcon                    { return newIcon("unlink") }
func GoUnlock() icons.IsIcon                    { return newIcon("unlock") }
func GoUnmute() icons.IsIcon                    { return newIcon("unmute") }
func GoUnread() icons.IsIcon                    { return newIcon("unread") }
func GoUnverified() icons.IsIcon                { return newIcon("unverified") }
func GoUpload() icons.IsIcon                    { return newIcon("upload") }
func GoVerified() icons.IsIcon                  { return newIcon("verified") }
func GoVersions() icons.IsIcon                  { return newIcon("versions") }
func GoVideo() icons.IsIcon                     { return newIcon("video") }
func GoVscode() icons.IsIcon                    { return newIcon("vscode") }
func GoWorkflow() icons.IsIcon                  { return newIcon("workflow") }
func GoXCircleFill() icons.IsIcon               { return newIcon("x-circle-fill") }
func GoXCircle() icons.IsIcon                   { return newIcon("x-circle") }
func GoX() icons.IsIcon                         { return newIcon("x") }
func GoZap() icons.IsIcon                       { return newIcon("zap") }
func GoZoomIn() icons.IsIcon                    { return newIcon("zoom-in") }
func GoZoomOut() icons.IsIcon                   { return newIcon("zoom-out") }
