package fa5

import "github.com/raitucarp/gomix/icons"

func FaSolidAd() icons.IsIcon           { return newIcon(solidIcon, "ad") }
func FaSolidAddressBook() icons.IsIcon  { return newIcon(solidIcon, "address-book") }
func FaSolidAddressCard() icons.IsIcon  { return newIcon(solidIcon, "address-card") }
func FaSolidAdjust() icons.IsIcon       { return newIcon(solidIcon, "adjust") }
func FaSolidAirFreshener() icons.IsIcon { return newIcon(solidIcon, "air-freshener") }
func FaSolidAlignCenter() icons.IsIcon  { return newIcon(solidIcon, "align-center") }
func FaSolidAlignJustify() icons.IsIcon { return newIcon(solidIcon, "align-justify") }
func FaSolidAlignLeft() icons.IsIcon    { return newIcon(solidIcon, "align-left") }
func FaSolidAlignRight() icons.IsIcon   { return newIcon(solidIcon, "align-right") }
func FaSolidAllergies() icons.IsIcon    { return newIcon(solidIcon, "allergies") }
func FaSolidAmbulance() icons.IsIcon    { return newIcon(solidIcon, "ambulance") }
func FaSolidAmericanSignLanguageInterpreting() icons.IsIcon {
	return newIcon(solidIcon, "american-sign-language-interpreting")
}
func FaSolidAnchor() icons.IsIcon              { return newIcon(solidIcon, "anchor") }
func FaSolidAngleDoubleDown() icons.IsIcon     { return newIcon(solidIcon, "angle-double-down") }
func FaSolidAngleDoubleLeft() icons.IsIcon     { return newIcon(solidIcon, "angle-double-left") }
func FaSolidAngleDoubleRight() icons.IsIcon    { return newIcon(solidIcon, "angle-double-right") }
func FaSolidAngleDoubleUp() icons.IsIcon       { return newIcon(solidIcon, "angle-double-up") }
func FaSolidAngleDown() icons.IsIcon           { return newIcon(solidIcon, "angle-down") }
func FaSolidAngleLeft() icons.IsIcon           { return newIcon(solidIcon, "angle-left") }
func FaSolidAngleRight() icons.IsIcon          { return newIcon(solidIcon, "angle-right") }
func FaSolidAngleUp() icons.IsIcon             { return newIcon(solidIcon, "angle-up") }
func FaSolidAngry() icons.IsIcon               { return newIcon(solidIcon, "angry") }
func FaSolidAnkh() icons.IsIcon                { return newIcon(solidIcon, "ankh") }
func FaSolidAppleAlt() icons.IsIcon            { return newIcon(solidIcon, "apple-alt") }
func FaSolidArchive() icons.IsIcon             { return newIcon(solidIcon, "archive") }
func FaSolidArchway() icons.IsIcon             { return newIcon(solidIcon, "archway") }
func FaSolidArrowAltCircleDown() icons.IsIcon  { return newIcon(solidIcon, "arrow-alt-circle-down") }
func FaSolidArrowAltCircleLeft() icons.IsIcon  { return newIcon(solidIcon, "arrow-alt-circle-left") }
func FaSolidArrowAltCircleRight() icons.IsIcon { return newIcon(solidIcon, "arrow-alt-circle-right") }
func FaSolidArrowAltCircleUp() icons.IsIcon    { return newIcon(solidIcon, "arrow-alt-circle-up") }
func FaSolidArrowCircleDown() icons.IsIcon     { return newIcon(solidIcon, "arrow-circle-down") }
func FaSolidArrowCircleLeft() icons.IsIcon     { return newIcon(solidIcon, "arrow-circle-left") }
func FaSolidArrowCircleRight() icons.IsIcon    { return newIcon(solidIcon, "arrow-circle-right") }
func FaSolidArrowCircleUp() icons.IsIcon       { return newIcon(solidIcon, "arrow-circle-up") }
func FaSolidArrowDown() icons.IsIcon           { return newIcon(solidIcon, "arrow-down") }
func FaSolidArrowLeft() icons.IsIcon           { return newIcon(solidIcon, "arrow-left") }
func FaSolidArrowRight() icons.IsIcon          { return newIcon(solidIcon, "arrow-right") }
func FaSolidArrowUp() icons.IsIcon             { return newIcon(solidIcon, "arrow-up") }
func FaSolidArrowsAltH() icons.IsIcon          { return newIcon(solidIcon, "arrows-alt-h") }
func FaSolidArrowsAltV() icons.IsIcon          { return newIcon(solidIcon, "arrows-alt-v") }
func FaSolidArrowsAlt() icons.IsIcon           { return newIcon(solidIcon, "arrows-alt") }
func FaSolidAssistiveListeningSystems() icons.IsIcon {
	return newIcon(solidIcon, "assistive-listening-systems")
}
func FaSolidAsterisk() icons.IsIcon             { return newIcon(solidIcon, "asterisk") }
func FaSolidAt() icons.IsIcon                   { return newIcon(solidIcon, "at") }
func FaSolidAtlas() icons.IsIcon                { return newIcon(solidIcon, "atlas") }
func FaSolidAtom() icons.IsIcon                 { return newIcon(solidIcon, "atom") }
func FaSolidAudioDescription() icons.IsIcon     { return newIcon(solidIcon, "audio-description") }
func FaSolidAward() icons.IsIcon                { return newIcon(solidIcon, "award") }
func FaSolidBabyCarriage() icons.IsIcon         { return newIcon(solidIcon, "baby-carriage") }
func FaSolidBaby() icons.IsIcon                 { return newIcon(solidIcon, "baby") }
func FaSolidBackspace() icons.IsIcon            { return newIcon(solidIcon, "backspace") }
func FaSolidBackward() icons.IsIcon             { return newIcon(solidIcon, "backward") }
func FaSolidBacon() icons.IsIcon                { return newIcon(solidIcon, "bacon") }
func FaSolidBacteria() icons.IsIcon             { return newIcon(solidIcon, "bacteria") }
func FaSolidBacterium() icons.IsIcon            { return newIcon(solidIcon, "bacterium") }
func FaSolidBahai() icons.IsIcon                { return newIcon(solidIcon, "bahai") }
func FaSolidBalanceScaleLeft() icons.IsIcon     { return newIcon(solidIcon, "balance-scale-left") }
func FaSolidBalanceScaleRight() icons.IsIcon    { return newIcon(solidIcon, "balance-scale-right") }
func FaSolidBalanceScale() icons.IsIcon         { return newIcon(solidIcon, "balance-scale") }
func FaSolidBan() icons.IsIcon                  { return newIcon(solidIcon, "ban") }
func FaSolidBandAid() icons.IsIcon              { return newIcon(solidIcon, "band-aid") }
func FaSolidBarcode() icons.IsIcon              { return newIcon(solidIcon, "barcode") }
func FaSolidBars() icons.IsIcon                 { return newIcon(solidIcon, "bars") }
func FaSolidBaseballBall() icons.IsIcon         { return newIcon(solidIcon, "baseball-ball") }
func FaSolidBasketballBall() icons.IsIcon       { return newIcon(solidIcon, "basketball-ball") }
func FaSolidBath() icons.IsIcon                 { return newIcon(solidIcon, "bath") }
func FaSolidBatteryEmpty() icons.IsIcon         { return newIcon(solidIcon, "battery-empty") }
func FaSolidBatteryFull() icons.IsIcon          { return newIcon(solidIcon, "battery-full") }
func FaSolidBatteryHalf() icons.IsIcon          { return newIcon(solidIcon, "battery-half") }
func FaSolidBatteryQuarter() icons.IsIcon       { return newIcon(solidIcon, "battery-quarter") }
func FaSolidBatteryThreeQuarters() icons.IsIcon { return newIcon(solidIcon, "battery-three-quarters") }
func FaSolidBed() icons.IsIcon                  { return newIcon(solidIcon, "bed") }
func FaSolidBeer() icons.IsIcon                 { return newIcon(solidIcon, "beer") }
func FaSolidBellSlash() icons.IsIcon            { return newIcon(solidIcon, "bell-slash") }
func FaSolidBell() icons.IsIcon                 { return newIcon(solidIcon, "bell") }
func FaSolidBezierCurve() icons.IsIcon          { return newIcon(solidIcon, "bezier-curve") }
func FaSolidBible() icons.IsIcon                { return newIcon(solidIcon, "bible") }
func FaSolidBicycle() icons.IsIcon              { return newIcon(solidIcon, "bicycle") }
func FaSolidBiking() icons.IsIcon               { return newIcon(solidIcon, "biking") }
func FaSolidBinoculars() icons.IsIcon           { return newIcon(solidIcon, "binoculars") }
func FaSolidBiohazard() icons.IsIcon            { return newIcon(solidIcon, "biohazard") }
func FaSolidBirthdayCake() icons.IsIcon         { return newIcon(solidIcon, "birthday-cake") }
func FaSolidBlenderPhone() icons.IsIcon         { return newIcon(solidIcon, "blender-phone") }
func FaSolidBlender() icons.IsIcon              { return newIcon(solidIcon, "blender") }
func FaSolidBlind() icons.IsIcon                { return newIcon(solidIcon, "blind") }
func FaSolidBlog() icons.IsIcon                 { return newIcon(solidIcon, "blog") }
func FaSolidBold() icons.IsIcon                 { return newIcon(solidIcon, "bold") }
func FaSolidBolt() icons.IsIcon                 { return newIcon(solidIcon, "bolt") }
func FaSolidBomb() icons.IsIcon                 { return newIcon(solidIcon, "bomb") }
func FaSolidBone() icons.IsIcon                 { return newIcon(solidIcon, "bone") }
func FaSolidBong() icons.IsIcon                 { return newIcon(solidIcon, "bong") }
func FaSolidBookDead() icons.IsIcon             { return newIcon(solidIcon, "book-dead") }
func FaSolidBookMedical() icons.IsIcon          { return newIcon(solidIcon, "book-medical") }
func FaSolidBookOpen() icons.IsIcon             { return newIcon(solidIcon, "book-open") }
func FaSolidBookReader() icons.IsIcon           { return newIcon(solidIcon, "book-reader") }
func FaSolidBook() icons.IsIcon                 { return newIcon(solidIcon, "book") }
func FaSolidBookmark() icons.IsIcon             { return newIcon(solidIcon, "bookmark") }
func FaSolidBorderAll() icons.IsIcon            { return newIcon(solidIcon, "border-all") }
func FaSolidBorderNone() icons.IsIcon           { return newIcon(solidIcon, "border-none") }
func FaSolidBorderStyle() icons.IsIcon          { return newIcon(solidIcon, "border-style") }
func FaSolidBowlingBall() icons.IsIcon          { return newIcon(solidIcon, "bowling-ball") }
func FaSolidBoxOpen() icons.IsIcon              { return newIcon(solidIcon, "box-open") }
func FaSolidBoxTissue() icons.IsIcon            { return newIcon(solidIcon, "box-tissue") }
func FaSolidBox() icons.IsIcon                  { return newIcon(solidIcon, "box") }
func FaSolidBoxes() icons.IsIcon                { return newIcon(solidIcon, "boxes") }
func FaSolidBraille() icons.IsIcon              { return newIcon(solidIcon, "braille") }
func FaSolidBrain() icons.IsIcon                { return newIcon(solidIcon, "brain") }
func FaSolidBreadSlice() icons.IsIcon           { return newIcon(solidIcon, "bread-slice") }
func FaSolidBriefcaseMedical() icons.IsIcon     { return newIcon(solidIcon, "briefcase-medical") }
func FaSolidBriefcase() icons.IsIcon            { return newIcon(solidIcon, "briefcase") }
func FaSolidBroadcastTower() icons.IsIcon       { return newIcon(solidIcon, "broadcast-tower") }
func FaSolidBroom() icons.IsIcon                { return newIcon(solidIcon, "broom") }
func FaSolidBrush() icons.IsIcon                { return newIcon(solidIcon, "brush") }
func FaSolidBug() icons.IsIcon                  { return newIcon(solidIcon, "bug") }
func FaSolidBuilding() icons.IsIcon             { return newIcon(solidIcon, "building") }
func FaSolidBullhorn() icons.IsIcon             { return newIcon(solidIcon, "bullhorn") }
func FaSolidBullseye() icons.IsIcon             { return newIcon(solidIcon, "bullseye") }
func FaSolidBurn() icons.IsIcon                 { return newIcon(solidIcon, "burn") }
func FaSolidBusAlt() icons.IsIcon               { return newIcon(solidIcon, "bus-alt") }
func FaSolidBus() icons.IsIcon                  { return newIcon(solidIcon, "bus") }
func FaSolidBusinessTime() icons.IsIcon         { return newIcon(solidIcon, "business-time") }
func FaSolidCalculator() icons.IsIcon           { return newIcon(solidIcon, "calculator") }
func FaSolidCalendarAlt() icons.IsIcon          { return newIcon(solidIcon, "calendar-alt") }
func FaSolidCalendarCheck() icons.IsIcon        { return newIcon(solidIcon, "calendar-check") }
func FaSolidCalendarDay() icons.IsIcon          { return newIcon(solidIcon, "calendar-day") }
func FaSolidCalendarMinus() icons.IsIcon        { return newIcon(solidIcon, "calendar-minus") }
func FaSolidCalendarPlus() icons.IsIcon         { return newIcon(solidIcon, "calendar-plus") }
func FaSolidCalendarTimes() icons.IsIcon        { return newIcon(solidIcon, "calendar-times") }
func FaSolidCalendarWeek() icons.IsIcon         { return newIcon(solidIcon, "calendar-week") }
func FaSolidCalendar() icons.IsIcon             { return newIcon(solidIcon, "calendar") }
func FaSolidCameraRetro() icons.IsIcon          { return newIcon(solidIcon, "camera-retro") }
func FaSolidCamera() icons.IsIcon               { return newIcon(solidIcon, "camera") }
func FaSolidCampground() icons.IsIcon           { return newIcon(solidIcon, "campground") }
func FaSolidCandyCane() icons.IsIcon            { return newIcon(solidIcon, "candy-cane") }
func FaSolidCannabis() icons.IsIcon             { return newIcon(solidIcon, "cannabis") }
func FaSolidCapsules() icons.IsIcon             { return newIcon(solidIcon, "capsules") }
func FaSolidCarAlt() icons.IsIcon               { return newIcon(solidIcon, "car-alt") }
func FaSolidCarBattery() icons.IsIcon           { return newIcon(solidIcon, "car-battery") }
func FaSolidCarCrash() icons.IsIcon             { return newIcon(solidIcon, "car-crash") }
func FaSolidCarSide() icons.IsIcon              { return newIcon(solidIcon, "car-side") }
func FaSolidCar() icons.IsIcon                  { return newIcon(solidIcon, "car") }
func FaSolidCaravan() icons.IsIcon              { return newIcon(solidIcon, "caravan") }
func FaSolidCaretDown() icons.IsIcon            { return newIcon(solidIcon, "caret-down") }
func FaSolidCaretLeft() icons.IsIcon            { return newIcon(solidIcon, "caret-left") }
func FaSolidCaretRight() icons.IsIcon           { return newIcon(solidIcon, "caret-right") }
func FaSolidCaretSquareDown() icons.IsIcon      { return newIcon(solidIcon, "caret-square-down") }
func FaSolidCaretSquareLeft() icons.IsIcon      { return newIcon(solidIcon, "caret-square-left") }
func FaSolidCaretSquareRight() icons.IsIcon     { return newIcon(solidIcon, "caret-square-right") }
func FaSolidCaretSquareUp() icons.IsIcon        { return newIcon(solidIcon, "caret-square-up") }
func FaSolidCaretUp() icons.IsIcon              { return newIcon(solidIcon, "caret-up") }
func FaSolidCarrot() icons.IsIcon               { return newIcon(solidIcon, "carrot") }
func FaSolidCartArrowDown() icons.IsIcon        { return newIcon(solidIcon, "cart-arrow-down") }
func FaSolidCartPlus() icons.IsIcon             { return newIcon(solidIcon, "cart-plus") }
func FaSolidCashRegister() icons.IsIcon         { return newIcon(solidIcon, "cash-register") }
func FaSolidCat() icons.IsIcon                  { return newIcon(solidIcon, "cat") }
func FaSolidCertificate() icons.IsIcon          { return newIcon(solidIcon, "certificate") }
func FaSolidChair() icons.IsIcon                { return newIcon(solidIcon, "chair") }
func FaSolidChalkboardTeacher() icons.IsIcon    { return newIcon(solidIcon, "chalkboard-teacher") }
func FaSolidChalkboard() icons.IsIcon           { return newIcon(solidIcon, "chalkboard") }
func FaSolidChargingStation() icons.IsIcon      { return newIcon(solidIcon, "charging-station") }
func FaSolidChartArea() icons.IsIcon            { return newIcon(solidIcon, "chart-area") }
func FaSolidChartBar() icons.IsIcon             { return newIcon(solidIcon, "chart-bar") }
func FaSolidChartLine() icons.IsIcon            { return newIcon(solidIcon, "chart-line") }
func FaSolidChartPie() icons.IsIcon             { return newIcon(solidIcon, "chart-pie") }
func FaSolidCheckCircle() icons.IsIcon          { return newIcon(solidIcon, "check-circle") }
func FaSolidCheckDouble() icons.IsIcon          { return newIcon(solidIcon, "check-double") }
func FaSolidCheckSquare() icons.IsIcon          { return newIcon(solidIcon, "check-square") }
func FaSolidCheck() icons.IsIcon                { return newIcon(solidIcon, "check") }
func FaSolidCheese() icons.IsIcon               { return newIcon(solidIcon, "cheese") }
func FaSolidChessBishop() icons.IsIcon          { return newIcon(solidIcon, "chess-bishop") }
func FaSolidChessBoard() icons.IsIcon           { return newIcon(solidIcon, "chess-board") }
func FaSolidChessKing() icons.IsIcon            { return newIcon(solidIcon, "chess-king") }
func FaSolidChessKnight() icons.IsIcon          { return newIcon(solidIcon, "chess-knight") }
func FaSolidChessPawn() icons.IsIcon            { return newIcon(solidIcon, "chess-pawn") }
func FaSolidChessQueen() icons.IsIcon           { return newIcon(solidIcon, "chess-queen") }
func FaSolidChessRook() icons.IsIcon            { return newIcon(solidIcon, "chess-rook") }
func FaSolidChess() icons.IsIcon                { return newIcon(solidIcon, "chess") }
func FaSolidChevronCircleDown() icons.IsIcon    { return newIcon(solidIcon, "chevron-circle-down") }
func FaSolidChevronCircleLeft() icons.IsIcon    { return newIcon(solidIcon, "chevron-circle-left") }
func FaSolidChevronCircleRight() icons.IsIcon   { return newIcon(solidIcon, "chevron-circle-right") }
func FaSolidChevronCircleUp() icons.IsIcon      { return newIcon(solidIcon, "chevron-circle-up") }
func FaSolidChevronDown() icons.IsIcon          { return newIcon(solidIcon, "chevron-down") }
func FaSolidChevronLeft() icons.IsIcon          { return newIcon(solidIcon, "chevron-left") }
func FaSolidChevronRight() icons.IsIcon         { return newIcon(solidIcon, "chevron-right") }
func FaSolidChevronUp() icons.IsIcon            { return newIcon(solidIcon, "chevron-up") }
func FaSolidChild() icons.IsIcon                { return newIcon(solidIcon, "child") }
func FaSolidChurch() icons.IsIcon               { return newIcon(solidIcon, "church") }
func FaSolidCircleNotch() icons.IsIcon          { return newIcon(solidIcon, "circle-notch") }
func FaSolidCircle() icons.IsIcon               { return newIcon(solidIcon, "circle") }
func FaSolidCity() icons.IsIcon                 { return newIcon(solidIcon, "city") }
func FaSolidClinicMedical() icons.IsIcon        { return newIcon(solidIcon, "clinic-medical") }
func FaSolidClipboardCheck() icons.IsIcon       { return newIcon(solidIcon, "clipboard-check") }
func FaSolidClipboardList() icons.IsIcon        { return newIcon(solidIcon, "clipboard-list") }
func FaSolidClipboard() icons.IsIcon            { return newIcon(solidIcon, "clipboard") }
func FaSolidClock() icons.IsIcon                { return newIcon(solidIcon, "clock") }
func FaSolidClone() icons.IsIcon                { return newIcon(solidIcon, "clone") }
func FaSolidClosedCaptioning() icons.IsIcon     { return newIcon(solidIcon, "closed-captioning") }
func FaSolidCloudDownloadAlt() icons.IsIcon     { return newIcon(solidIcon, "cloud-download-alt") }
func FaSolidCloudMeatball() icons.IsIcon        { return newIcon(solidIcon, "cloud-meatball") }
func FaSolidCloudMoonRain() icons.IsIcon        { return newIcon(solidIcon, "cloud-moon-rain") }
func FaSolidCloudMoon() icons.IsIcon            { return newIcon(solidIcon, "cloud-moon") }
func FaSolidCloudRain() icons.IsIcon            { return newIcon(solidIcon, "cloud-rain") }
func FaSolidCloudShowersHeavy() icons.IsIcon    { return newIcon(solidIcon, "cloud-showers-heavy") }
func FaSolidCloudSunRain() icons.IsIcon         { return newIcon(solidIcon, "cloud-sun-rain") }
func FaSolidCloudSun() icons.IsIcon             { return newIcon(solidIcon, "cloud-sun") }
func FaSolidCloudUploadAlt() icons.IsIcon       { return newIcon(solidIcon, "cloud-upload-alt") }
func FaSolidCloud() icons.IsIcon                { return newIcon(solidIcon, "cloud") }
func FaSolidCocktail() icons.IsIcon             { return newIcon(solidIcon, "cocktail") }
func FaSolidCodeBranch() icons.IsIcon           { return newIcon(solidIcon, "code-branch") }
func FaSolidCode() icons.IsIcon                 { return newIcon(solidIcon, "code") }
func FaSolidCoffee() icons.IsIcon               { return newIcon(solidIcon, "coffee") }
func FaSolidCog() icons.IsIcon                  { return newIcon(solidIcon, "cog") }
func FaSolidCogs() icons.IsIcon                 { return newIcon(solidIcon, "cogs") }
func FaSolidCoins() icons.IsIcon                { return newIcon(solidIcon, "coins") }
func FaSolidColumns() icons.IsIcon              { return newIcon(solidIcon, "columns") }
func FaSolidCommentAlt() icons.IsIcon           { return newIcon(solidIcon, "comment-alt") }
func FaSolidCommentDollar() icons.IsIcon        { return newIcon(solidIcon, "comment-dollar") }
func FaSolidCommentDots() icons.IsIcon          { return newIcon(solidIcon, "comment-dots") }
func FaSolidCommentMedical() icons.IsIcon       { return newIcon(solidIcon, "comment-medical") }
func FaSolidCommentSlash() icons.IsIcon         { return newIcon(solidIcon, "comment-slash") }
func FaSolidComment() icons.IsIcon              { return newIcon(solidIcon, "comment") }
func FaSolidCommentsDollar() icons.IsIcon       { return newIcon(solidIcon, "comments-dollar") }
func FaSolidComments() icons.IsIcon             { return newIcon(solidIcon, "comments") }
func FaSolidCompactDisc() icons.IsIcon          { return newIcon(solidIcon, "compact-disc") }
func FaSolidCompass() icons.IsIcon              { return newIcon(solidIcon, "compass") }
func FaSolidCompressAlt() icons.IsIcon          { return newIcon(solidIcon, "compress-alt") }
func FaSolidCompressArrowsAlt() icons.IsIcon    { return newIcon(solidIcon, "compress-arrows-alt") }
func FaSolidCompress() icons.IsIcon             { return newIcon(solidIcon, "compress") }
func FaSolidConciergeBell() icons.IsIcon        { return newIcon(solidIcon, "concierge-bell") }
func FaSolidCookieBite() icons.IsIcon           { return newIcon(solidIcon, "cookie-bite") }
func FaSolidCookie() icons.IsIcon               { return newIcon(solidIcon, "cookie") }
func FaSolidCopy() icons.IsIcon                 { return newIcon(solidIcon, "copy") }
func FaSolidCopyright() icons.IsIcon            { return newIcon(solidIcon, "copyright") }
func FaSolidCouch() icons.IsIcon                { return newIcon(solidIcon, "couch") }
func FaSolidCreditCard() icons.IsIcon           { return newIcon(solidIcon, "credit-card") }
func FaSolidCropAlt() icons.IsIcon              { return newIcon(solidIcon, "crop-alt") }
func FaSolidCrop() icons.IsIcon                 { return newIcon(solidIcon, "crop") }
func FaSolidCross() icons.IsIcon                { return newIcon(solidIcon, "cross") }
func FaSolidCrosshairs() icons.IsIcon           { return newIcon(solidIcon, "crosshairs") }
func FaSolidCrow() icons.IsIcon                 { return newIcon(solidIcon, "crow") }
func FaSolidCrown() icons.IsIcon                { return newIcon(solidIcon, "crown") }
func FaSolidCrutch() icons.IsIcon               { return newIcon(solidIcon, "crutch") }
func FaSolidCube() icons.IsIcon                 { return newIcon(solidIcon, "cube") }
func FaSolidCubes() icons.IsIcon                { return newIcon(solidIcon, "cubes") }
func FaSolidCut() icons.IsIcon                  { return newIcon(solidIcon, "cut") }
func FaSolidDatabase() icons.IsIcon             { return newIcon(solidIcon, "database") }
func FaSolidDeaf() icons.IsIcon                 { return newIcon(solidIcon, "deaf") }
func FaSolidDemocrat() icons.IsIcon             { return newIcon(solidIcon, "democrat") }
func FaSolidDesktop() icons.IsIcon              { return newIcon(solidIcon, "desktop") }
func FaSolidDharmachakra() icons.IsIcon         { return newIcon(solidIcon, "dharmachakra") }
func FaSolidDiagnoses() icons.IsIcon            { return newIcon(solidIcon, "diagnoses") }
func FaSolidDiceD20() icons.IsIcon              { return newIcon(solidIcon, "dice-d20") }
func FaSolidDiceD6() icons.IsIcon               { return newIcon(solidIcon, "dice-d6") }
func FaSolidDiceFive() icons.IsIcon             { return newIcon(solidIcon, "dice-five") }
func FaSolidDiceFour() icons.IsIcon             { return newIcon(solidIcon, "dice-four") }
func FaSolidDiceOne() icons.IsIcon              { return newIcon(solidIcon, "dice-one") }
func FaSolidDiceSix() icons.IsIcon              { return newIcon(solidIcon, "dice-six") }
func FaSolidDiceThree() icons.IsIcon            { return newIcon(solidIcon, "dice-three") }
func FaSolidDiceTwo() icons.IsIcon              { return newIcon(solidIcon, "dice-two") }
func FaSolidDice() icons.IsIcon                 { return newIcon(solidIcon, "dice") }
func FaSolidDigitalTachograph() icons.IsIcon    { return newIcon(solidIcon, "digital-tachograph") }
func FaSolidDirections() icons.IsIcon           { return newIcon(solidIcon, "directions") }
func FaSolidDisease() icons.IsIcon              { return newIcon(solidIcon, "disease") }
func FaSolidDivide() icons.IsIcon               { return newIcon(solidIcon, "divide") }
func FaSolidDizzy() icons.IsIcon                { return newIcon(solidIcon, "dizzy") }
func FaSolidDna() icons.IsIcon                  { return newIcon(solidIcon, "dna") }
func FaSolidDog() icons.IsIcon                  { return newIcon(solidIcon, "dog") }
func FaSolidDollarSign() icons.IsIcon           { return newIcon(solidIcon, "dollar-sign") }
func FaSolidDollyFlatbed() icons.IsIcon         { return newIcon(solidIcon, "dolly-flatbed") }
func FaSolidDolly() icons.IsIcon                { return newIcon(solidIcon, "dolly") }
func FaSolidDonate() icons.IsIcon               { return newIcon(solidIcon, "donate") }
func FaSolidDoorClosed() icons.IsIcon           { return newIcon(solidIcon, "door-closed") }
func FaSolidDoorOpen() icons.IsIcon             { return newIcon(solidIcon, "door-open") }
func FaSolidDotCircle() icons.IsIcon            { return newIcon(solidIcon, "dot-circle") }
func FaSolidDove() icons.IsIcon                 { return newIcon(solidIcon, "dove") }
func FaSolidDownload() icons.IsIcon             { return newIcon(solidIcon, "download") }
func FaSolidDraftingCompass() icons.IsIcon      { return newIcon(solidIcon, "drafting-compass") }
func FaSolidDragon() icons.IsIcon               { return newIcon(solidIcon, "dragon") }
func FaSolidDrawPolygon() icons.IsIcon          { return newIcon(solidIcon, "draw-polygon") }
func FaSolidDrumSteelpan() icons.IsIcon         { return newIcon(solidIcon, "drum-steelpan") }
func FaSolidDrum() icons.IsIcon                 { return newIcon(solidIcon, "drum") }
func FaSolidDrumstickBite() icons.IsIcon        { return newIcon(solidIcon, "drumstick-bite") }
func FaSolidDumbbell() icons.IsIcon             { return newIcon(solidIcon, "dumbbell") }
func FaSolidDumpsterFire() icons.IsIcon         { return newIcon(solidIcon, "dumpster-fire") }
func FaSolidDumpster() icons.IsIcon             { return newIcon(solidIcon, "dumpster") }
func FaSolidDungeon() icons.IsIcon              { return newIcon(solidIcon, "dungeon") }
func FaSolidEdit() icons.IsIcon                 { return newIcon(solidIcon, "edit") }
func FaSolidEgg() icons.IsIcon                  { return newIcon(solidIcon, "egg") }
func FaSolidEject() icons.IsIcon                { return newIcon(solidIcon, "eject") }
func FaSolidEllipsisH() icons.IsIcon            { return newIcon(solidIcon, "ellipsis-h") }
func FaSolidEllipsisV() icons.IsIcon            { return newIcon(solidIcon, "ellipsis-v") }
func FaSolidEnvelopeOpenText() icons.IsIcon     { return newIcon(solidIcon, "envelope-open-text") }
func FaSolidEnvelopeOpen() icons.IsIcon         { return newIcon(solidIcon, "envelope-open") }
func FaSolidEnvelopeSquare() icons.IsIcon       { return newIcon(solidIcon, "envelope-square") }
func FaSolidEnvelope() icons.IsIcon             { return newIcon(solidIcon, "envelope") }
func FaSolidEquals() icons.IsIcon               { return newIcon(solidIcon, "equals") }
func FaSolidEraser() icons.IsIcon               { return newIcon(solidIcon, "eraser") }
func FaSolidEthernet() icons.IsIcon             { return newIcon(solidIcon, "ethernet") }
func FaSolidEuroSign() icons.IsIcon             { return newIcon(solidIcon, "euro-sign") }
func FaSolidExchangeAlt() icons.IsIcon          { return newIcon(solidIcon, "exchange-alt") }
func FaSolidExclamationCircle() icons.IsIcon    { return newIcon(solidIcon, "exclamation-circle") }
func FaSolidExclamationTriangle() icons.IsIcon  { return newIcon(solidIcon, "exclamation-triangle") }
func FaSolidExclamation() icons.IsIcon          { return newIcon(solidIcon, "exclamation") }
func FaSolidExpandAlt() icons.IsIcon            { return newIcon(solidIcon, "expand-alt") }
func FaSolidExpandArrowsAlt() icons.IsIcon      { return newIcon(solidIcon, "expand-arrows-alt") }
func FaSolidExpand() icons.IsIcon               { return newIcon(solidIcon, "expand") }
func FaSolidExternalLinkAlt() icons.IsIcon      { return newIcon(solidIcon, "external-link-alt") }
func FaSolidExternalLinkSquareAlt() icons.IsIcon {
	return newIcon(solidIcon, "external-link-square-alt")
}
func FaSolidEyeDropper() icons.IsIcon          { return newIcon(solidIcon, "eye-dropper") }
func FaSolidEyeSlash() icons.IsIcon            { return newIcon(solidIcon, "eye-slash") }
func FaSolidEye() icons.IsIcon                 { return newIcon(solidIcon, "eye") }
func FaSolidFan() icons.IsIcon                 { return newIcon(solidIcon, "fan") }
func FaSolidFastBackward() icons.IsIcon        { return newIcon(solidIcon, "fast-backward") }
func FaSolidFastForward() icons.IsIcon         { return newIcon(solidIcon, "fast-forward") }
func FaSolidFaucet() icons.IsIcon              { return newIcon(solidIcon, "faucet") }
func FaSolidFax() icons.IsIcon                 { return newIcon(solidIcon, "fax") }
func FaSolidFeatherAlt() icons.IsIcon          { return newIcon(solidIcon, "feather-alt") }
func FaSolidFeather() icons.IsIcon             { return newIcon(solidIcon, "feather") }
func FaSolidFemale() icons.IsIcon              { return newIcon(solidIcon, "female") }
func FaSolidFighterJet() icons.IsIcon          { return newIcon(solidIcon, "fighter-jet") }
func FaSolidFileAlt() icons.IsIcon             { return newIcon(solidIcon, "file-alt") }
func FaSolidFileArchive() icons.IsIcon         { return newIcon(solidIcon, "file-archive") }
func FaSolidFileAudio() icons.IsIcon           { return newIcon(solidIcon, "file-audio") }
func FaSolidFileCode() icons.IsIcon            { return newIcon(solidIcon, "file-code") }
func FaSolidFileContract() icons.IsIcon        { return newIcon(solidIcon, "file-contract") }
func FaSolidFileCsv() icons.IsIcon             { return newIcon(solidIcon, "file-csv") }
func FaSolidFileDownload() icons.IsIcon        { return newIcon(solidIcon, "file-download") }
func FaSolidFileExcel() icons.IsIcon           { return newIcon(solidIcon, "file-excel") }
func FaSolidFileExport() icons.IsIcon          { return newIcon(solidIcon, "file-export") }
func FaSolidFileImage() icons.IsIcon           { return newIcon(solidIcon, "file-image") }
func FaSolidFileImport() icons.IsIcon          { return newIcon(solidIcon, "file-import") }
func FaSolidFileInvoiceDollar() icons.IsIcon   { return newIcon(solidIcon, "file-invoice-dollar") }
func FaSolidFileInvoice() icons.IsIcon         { return newIcon(solidIcon, "file-invoice") }
func FaSolidFileMedicalAlt() icons.IsIcon      { return newIcon(solidIcon, "file-medical-alt") }
func FaSolidFileMedical() icons.IsIcon         { return newIcon(solidIcon, "file-medical") }
func FaSolidFilePdf() icons.IsIcon             { return newIcon(solidIcon, "file-pdf") }
func FaSolidFilePowerpoint() icons.IsIcon      { return newIcon(solidIcon, "file-powerpoint") }
func FaSolidFilePrescription() icons.IsIcon    { return newIcon(solidIcon, "file-prescription") }
func FaSolidFileSignature() icons.IsIcon       { return newIcon(solidIcon, "file-signature") }
func FaSolidFileUpload() icons.IsIcon          { return newIcon(solidIcon, "file-upload") }
func FaSolidFileVideo() icons.IsIcon           { return newIcon(solidIcon, "file-video") }
func FaSolidFileWord() icons.IsIcon            { return newIcon(solidIcon, "file-word") }
func FaSolidFile() icons.IsIcon                { return newIcon(solidIcon, "file") }
func FaSolidFillDrip() icons.IsIcon            { return newIcon(solidIcon, "fill-drip") }
func FaSolidFill() icons.IsIcon                { return newIcon(solidIcon, "fill") }
func FaSolidFilm() icons.IsIcon                { return newIcon(solidIcon, "film") }
func FaSolidFilter() icons.IsIcon              { return newIcon(solidIcon, "filter") }
func FaSolidFingerprint() icons.IsIcon         { return newIcon(solidIcon, "fingerprint") }
func FaSolidFireAlt() icons.IsIcon             { return newIcon(solidIcon, "fire-alt") }
func FaSolidFireExtinguisher() icons.IsIcon    { return newIcon(solidIcon, "fire-extinguisher") }
func FaSolidFire() icons.IsIcon                { return newIcon(solidIcon, "fire") }
func FaSolidFirstAid() icons.IsIcon            { return newIcon(solidIcon, "first-aid") }
func FaSolidFish() icons.IsIcon                { return newIcon(solidIcon, "fish") }
func FaSolidFistRaised() icons.IsIcon          { return newIcon(solidIcon, "fist-raised") }
func FaSolidFlagCheckered() icons.IsIcon       { return newIcon(solidIcon, "flag-checkered") }
func FaSolidFlagUsa() icons.IsIcon             { return newIcon(solidIcon, "flag-usa") }
func FaSolidFlag() icons.IsIcon                { return newIcon(solidIcon, "flag") }
func FaSolidFlask() icons.IsIcon               { return newIcon(solidIcon, "flask") }
func FaSolidFlushed() icons.IsIcon             { return newIcon(solidIcon, "flushed") }
func FaSolidFolderMinus() icons.IsIcon         { return newIcon(solidIcon, "folder-minus") }
func FaSolidFolderOpen() icons.IsIcon          { return newIcon(solidIcon, "folder-open") }
func FaSolidFolderPlus() icons.IsIcon          { return newIcon(solidIcon, "folder-plus") }
func FaSolidFolder() icons.IsIcon              { return newIcon(solidIcon, "folder") }
func FaSolidFontAwesomeLogoFull() icons.IsIcon { return newIcon(solidIcon, "font-awesome-logo-full") }
func FaSolidFont() icons.IsIcon                { return newIcon(solidIcon, "font") }
func FaSolidFootballBall() icons.IsIcon        { return newIcon(solidIcon, "football-ball") }
func FaSolidForward() icons.IsIcon             { return newIcon(solidIcon, "forward") }
func FaSolidFrog() icons.IsIcon                { return newIcon(solidIcon, "frog") }
func FaSolidFrownOpen() icons.IsIcon           { return newIcon(solidIcon, "frown-open") }
func FaSolidFrown() icons.IsIcon               { return newIcon(solidIcon, "frown") }
func FaSolidFunnelDollar() icons.IsIcon        { return newIcon(solidIcon, "funnel-dollar") }
func FaSolidFutbol() icons.IsIcon              { return newIcon(solidIcon, "futbol") }
func FaSolidGamepad() icons.IsIcon             { return newIcon(solidIcon, "gamepad") }
func FaSolidGasPump() icons.IsIcon             { return newIcon(solidIcon, "gas-pump") }
func FaSolidGavel() icons.IsIcon               { return newIcon(solidIcon, "gavel") }
func FaSolidGem() icons.IsIcon                 { return newIcon(solidIcon, "gem") }
func FaSolidGenderless() icons.IsIcon          { return newIcon(solidIcon, "genderless") }
func FaSolidGhost() icons.IsIcon               { return newIcon(solidIcon, "ghost") }
func FaSolidGift() icons.IsIcon                { return newIcon(solidIcon, "gift") }
func FaSolidGifts() icons.IsIcon               { return newIcon(solidIcon, "gifts") }
func FaSolidGlassCheers() icons.IsIcon         { return newIcon(solidIcon, "glass-cheers") }
func FaSolidGlassMartiniAlt() icons.IsIcon     { return newIcon(solidIcon, "glass-martini-alt") }
func FaSolidGlassMartini() icons.IsIcon        { return newIcon(solidIcon, "glass-martini") }
func FaSolidGlassWhiskey() icons.IsIcon        { return newIcon(solidIcon, "glass-whiskey") }
func FaSolidGlasses() icons.IsIcon             { return newIcon(solidIcon, "glasses") }
func FaSolidGlobeAfrica() icons.IsIcon         { return newIcon(solidIcon, "globe-africa") }
func FaSolidGlobeAmericas() icons.IsIcon       { return newIcon(solidIcon, "globe-americas") }
func FaSolidGlobeAsia() icons.IsIcon           { return newIcon(solidIcon, "globe-asia") }
func FaSolidGlobeEurope() icons.IsIcon         { return newIcon(solidIcon, "globe-europe") }
func FaSolidGlobe() icons.IsIcon               { return newIcon(solidIcon, "globe") }
func FaSolidGolfBall() icons.IsIcon            { return newIcon(solidIcon, "golf-ball") }
func FaSolidGopuram() icons.IsIcon             { return newIcon(solidIcon, "gopuram") }
func FaSolidGraduationCap() icons.IsIcon       { return newIcon(solidIcon, "graduation-cap") }
func FaSolidGreaterThanEqual() icons.IsIcon    { return newIcon(solidIcon, "greater-than-equal") }
func FaSolidGreaterThan() icons.IsIcon         { return newIcon(solidIcon, "greater-than") }
func FaSolidGrimace() icons.IsIcon             { return newIcon(solidIcon, "grimace") }
func FaSolidGrinAlt() icons.IsIcon             { return newIcon(solidIcon, "grin-alt") }
func FaSolidGrinBeamSweat() icons.IsIcon       { return newIcon(solidIcon, "grin-beam-sweat") }
func FaSolidGrinBeam() icons.IsIcon            { return newIcon(solidIcon, "grin-beam") }
func FaSolidGrinHearts() icons.IsIcon          { return newIcon(solidIcon, "grin-hearts") }
func FaSolidGrinSquintTears() icons.IsIcon     { return newIcon(solidIcon, "grin-squint-tears") }
func FaSolidGrinSquint() icons.IsIcon          { return newIcon(solidIcon, "grin-squint") }
func FaSolidGrinStars() icons.IsIcon           { return newIcon(solidIcon, "grin-stars") }
func FaSolidGrinTears() icons.IsIcon           { return newIcon(solidIcon, "grin-tears") }
func FaSolidGrinTongueSquint() icons.IsIcon    { return newIcon(solidIcon, "grin-tongue-squint") }
func FaSolidGrinTongueWink() icons.IsIcon      { return newIcon(solidIcon, "grin-tongue-wink") }
func FaSolidGrinTongue() icons.IsIcon          { return newIcon(solidIcon, "grin-tongue") }
func FaSolidGrinWink() icons.IsIcon            { return newIcon(solidIcon, "grin-wink") }
func FaSolidGrin() icons.IsIcon                { return newIcon(solidIcon, "grin") }
func FaSolidGripHorizontal() icons.IsIcon      { return newIcon(solidIcon, "grip-horizontal") }
func FaSolidGripLinesVertical() icons.IsIcon   { return newIcon(solidIcon, "grip-lines-vertical") }
func FaSolidGripLines() icons.IsIcon           { return newIcon(solidIcon, "grip-lines") }
func FaSolidGripVertical() icons.IsIcon        { return newIcon(solidIcon, "grip-vertical") }
func FaSolidGuitar() icons.IsIcon              { return newIcon(solidIcon, "guitar") }
func FaSolidHSquare() icons.IsIcon             { return newIcon(solidIcon, "h-square") }
func FaSolidHamburger() icons.IsIcon           { return newIcon(solidIcon, "hamburger") }
func FaSolidHammer() icons.IsIcon              { return newIcon(solidIcon, "hammer") }
func FaSolidHamsa() icons.IsIcon               { return newIcon(solidIcon, "hamsa") }
func FaSolidHandHoldingHeart() icons.IsIcon    { return newIcon(solidIcon, "hand-holding-heart") }
func FaSolidHandHoldingMedical() icons.IsIcon  { return newIcon(solidIcon, "hand-holding-medical") }
func FaSolidHandHoldingUsd() icons.IsIcon      { return newIcon(solidIcon, "hand-holding-usd") }
func FaSolidHandHoldingWater() icons.IsIcon    { return newIcon(solidIcon, "hand-holding-water") }
func FaSolidHandHolding() icons.IsIcon         { return newIcon(solidIcon, "hand-holding") }
func FaSolidHandLizard() icons.IsIcon          { return newIcon(solidIcon, "hand-lizard") }
func FaSolidHandMiddleFinger() icons.IsIcon    { return newIcon(solidIcon, "hand-middle-finger") }
func FaSolidHandPaper() icons.IsIcon           { return newIcon(solidIcon, "hand-paper") }
func FaSolidHandPeace() icons.IsIcon           { return newIcon(solidIcon, "hand-peace") }
func FaSolidHandPointDown() icons.IsIcon       { return newIcon(solidIcon, "hand-point-down") }
func FaSolidHandPointLeft() icons.IsIcon       { return newIcon(solidIcon, "hand-point-left") }
func FaSolidHandPointRight() icons.IsIcon      { return newIcon(solidIcon, "hand-point-right") }
func FaSolidHandPointUp() icons.IsIcon         { return newIcon(solidIcon, "hand-point-up") }
func FaSolidHandPointer() icons.IsIcon         { return newIcon(solidIcon, "hand-pointer") }
func FaSolidHandRock() icons.IsIcon            { return newIcon(solidIcon, "hand-rock") }
func FaSolidHandScissors() icons.IsIcon        { return newIcon(solidIcon, "hand-scissors") }
func FaSolidHandSparkles() icons.IsIcon        { return newIcon(solidIcon, "hand-sparkles") }
func FaSolidHandSpock() icons.IsIcon           { return newIcon(solidIcon, "hand-spock") }
func FaSolidHandsHelping() icons.IsIcon        { return newIcon(solidIcon, "hands-helping") }
func FaSolidHandsWash() icons.IsIcon           { return newIcon(solidIcon, "hands-wash") }
func FaSolidHands() icons.IsIcon               { return newIcon(solidIcon, "hands") }
func FaSolidHandshakeAltSlash() icons.IsIcon   { return newIcon(solidIcon, "handshake-alt-slash") }
func FaSolidHandshakeSlash() icons.IsIcon      { return newIcon(solidIcon, "handshake-slash") }
func FaSolidHandshake() icons.IsIcon           { return newIcon(solidIcon, "handshake") }
func FaSolidHanukiah() icons.IsIcon            { return newIcon(solidIcon, "hanukiah") }
func FaSolidHardHat() icons.IsIcon             { return newIcon(solidIcon, "hard-hat") }
func FaSolidHashtag() icons.IsIcon             { return newIcon(solidIcon, "hashtag") }
func FaSolidHatCowboySide() icons.IsIcon       { return newIcon(solidIcon, "hat-cowboy-side") }
func FaSolidHatCowboy() icons.IsIcon           { return newIcon(solidIcon, "hat-cowboy") }
func FaSolidHatWizard() icons.IsIcon           { return newIcon(solidIcon, "hat-wizard") }
func FaSolidHdd() icons.IsIcon                 { return newIcon(solidIcon, "hdd") }
func FaSolidHeadSideCoughSlash() icons.IsIcon  { return newIcon(solidIcon, "head-side-cough-slash") }
func FaSolidHeadSideCough() icons.IsIcon       { return newIcon(solidIcon, "head-side-cough") }
func FaSolidHeadSideMask() icons.IsIcon        { return newIcon(solidIcon, "head-side-mask") }
func FaSolidHeadSideVirus() icons.IsIcon       { return newIcon(solidIcon, "head-side-virus") }
func FaSolidHeading() icons.IsIcon             { return newIcon(solidIcon, "heading") }
func FaSolidHeadphonesAlt() icons.IsIcon       { return newIcon(solidIcon, "headphones-alt") }
func FaSolidHeadphones() icons.IsIcon          { return newIcon(solidIcon, "headphones") }
func FaSolidHeadset() icons.IsIcon             { return newIcon(solidIcon, "headset") }
func FaSolidHeartBroken() icons.IsIcon         { return newIcon(solidIcon, "heart-broken") }
func FaSolidHeart() icons.IsIcon               { return newIcon(solidIcon, "heart") }
func FaSolidHeartbeat() icons.IsIcon           { return newIcon(solidIcon, "heartbeat") }
func FaSolidHelicopter() icons.IsIcon          { return newIcon(solidIcon, "helicopter") }
func FaSolidHighlighter() icons.IsIcon         { return newIcon(solidIcon, "highlighter") }
func FaSolidHiking() icons.IsIcon              { return newIcon(solidIcon, "hiking") }
func FaSolidHippo() icons.IsIcon               { return newIcon(solidIcon, "hippo") }
func FaSolidHistory() icons.IsIcon             { return newIcon(solidIcon, "history") }
func FaSolidHockeyPuck() icons.IsIcon          { return newIcon(solidIcon, "hockey-puck") }
func FaSolidHollyBerry() icons.IsIcon          { return newIcon(solidIcon, "holly-berry") }
func FaSolidHome() icons.IsIcon                { return newIcon(solidIcon, "home") }
func FaSolidHorseHead() icons.IsIcon           { return newIcon(solidIcon, "horse-head") }
func FaSolidHorse() icons.IsIcon               { return newIcon(solidIcon, "horse") }
func FaSolidHospitalAlt() icons.IsIcon         { return newIcon(solidIcon, "hospital-alt") }
func FaSolidHospitalSymbol() icons.IsIcon      { return newIcon(solidIcon, "hospital-symbol") }
func FaSolidHospitalUser() icons.IsIcon        { return newIcon(solidIcon, "hospital-user") }
func FaSolidHospital() icons.IsIcon            { return newIcon(solidIcon, "hospital") }
func FaSolidHotTub() icons.IsIcon              { return newIcon(solidIcon, "hot-tub") }
func FaSolidHotdog() icons.IsIcon              { return newIcon(solidIcon, "hotdog") }
func FaSolidHotel() icons.IsIcon               { return newIcon(solidIcon, "hotel") }
func FaSolidHourglassEnd() icons.IsIcon        { return newIcon(solidIcon, "hourglass-end") }
func FaSolidHourglassHalf() icons.IsIcon       { return newIcon(solidIcon, "hourglass-half") }
func FaSolidHourglassStart() icons.IsIcon      { return newIcon(solidIcon, "hourglass-start") }
func FaSolidHourglass() icons.IsIcon           { return newIcon(solidIcon, "hourglass") }
func FaSolidHouseDamage() icons.IsIcon         { return newIcon(solidIcon, "house-damage") }
func FaSolidHouseUser() icons.IsIcon           { return newIcon(solidIcon, "house-user") }
func FaSolidHryvnia() icons.IsIcon             { return newIcon(solidIcon, "hryvnia") }
func FaSolidICursor() icons.IsIcon             { return newIcon(solidIcon, "i-cursor") }
func FaSolidIceCream() icons.IsIcon            { return newIcon(solidIcon, "ice-cream") }
func FaSolidIcicles() icons.IsIcon             { return newIcon(solidIcon, "icicles") }
func FaSolidIcons() icons.IsIcon               { return newIcon(solidIcon, "icons") }
func FaSolidIdBadge() icons.IsIcon             { return newIcon(solidIcon, "id-badge") }
func FaSolidIdCardAlt() icons.IsIcon           { return newIcon(solidIcon, "id-card-alt") }
func FaSolidIdCard() icons.IsIcon              { return newIcon(solidIcon, "id-card") }
func FaSolidIgloo() icons.IsIcon               { return newIcon(solidIcon, "igloo") }
func FaSolidImage() icons.IsIcon               { return newIcon(solidIcon, "image") }
func FaSolidImages() icons.IsIcon              { return newIcon(solidIcon, "images") }
func FaSolidInbox() icons.IsIcon               { return newIcon(solidIcon, "inbox") }
func FaSolidIndent() icons.IsIcon              { return newIcon(solidIcon, "indent") }
func FaSolidIndustry() icons.IsIcon            { return newIcon(solidIcon, "industry") }
func FaSolidInfinity() icons.IsIcon            { return newIcon(solidIcon, "infinity") }
func FaSolidInfoCircle() icons.IsIcon          { return newIcon(solidIcon, "info-circle") }
func FaSolidInfo() icons.IsIcon                { return newIcon(solidIcon, "info") }
func FaSolidItalic() icons.IsIcon              { return newIcon(solidIcon, "italic") }
func FaSolidJedi() icons.IsIcon                { return newIcon(solidIcon, "jedi") }
func FaSolidJoint() icons.IsIcon               { return newIcon(solidIcon, "joint") }
func FaSolidJournalWhills() icons.IsIcon       { return newIcon(solidIcon, "journal-whills") }
func FaSolidKaaba() icons.IsIcon               { return newIcon(solidIcon, "kaaba") }
func FaSolidKey() icons.IsIcon                 { return newIcon(solidIcon, "key") }
func FaSolidKeyboard() icons.IsIcon            { return newIcon(solidIcon, "keyboard") }
func FaSolidKhanda() icons.IsIcon              { return newIcon(solidIcon, "khanda") }
func FaSolidKissBeam() icons.IsIcon            { return newIcon(solidIcon, "kiss-beam") }
func FaSolidKissWinkHeart() icons.IsIcon       { return newIcon(solidIcon, "kiss-wink-heart") }
func FaSolidKiss() icons.IsIcon                { return newIcon(solidIcon, "kiss") }
func FaSolidKiwiBird() icons.IsIcon            { return newIcon(solidIcon, "kiwi-bird") }
func FaSolidLandmark() icons.IsIcon            { return newIcon(solidIcon, "landmark") }
func FaSolidLanguage() icons.IsIcon            { return newIcon(solidIcon, "language") }
func FaSolidLaptopCode() icons.IsIcon          { return newIcon(solidIcon, "laptop-code") }
func FaSolidLaptopHouse() icons.IsIcon         { return newIcon(solidIcon, "laptop-house") }
func FaSolidLaptopMedical() icons.IsIcon       { return newIcon(solidIcon, "laptop-medical") }
func FaSolidLaptop() icons.IsIcon              { return newIcon(solidIcon, "laptop") }
func FaSolidLaughBeam() icons.IsIcon           { return newIcon(solidIcon, "laugh-beam") }
func FaSolidLaughSquint() icons.IsIcon         { return newIcon(solidIcon, "laugh-squint") }
func FaSolidLaughWink() icons.IsIcon           { return newIcon(solidIcon, "laugh-wink") }
func FaSolidLaugh() icons.IsIcon               { return newIcon(solidIcon, "laugh") }
func FaSolidLayerGroup() icons.IsIcon          { return newIcon(solidIcon, "layer-group") }
func FaSolidLeaf() icons.IsIcon                { return newIcon(solidIcon, "leaf") }
func FaSolidLemon() icons.IsIcon               { return newIcon(solidIcon, "lemon") }
func FaSolidLessThanEqual() icons.IsIcon       { return newIcon(solidIcon, "less-than-equal") }
func FaSolidLessThan() icons.IsIcon            { return newIcon(solidIcon, "less-than") }
func FaSolidLevelDownAlt() icons.IsIcon        { return newIcon(solidIcon, "level-down-alt") }
func FaSolidLevelUpAlt() icons.IsIcon          { return newIcon(solidIcon, "level-up-alt") }
func FaSolidLifeRing() icons.IsIcon            { return newIcon(solidIcon, "life-ring") }
func FaSolidLightbulb() icons.IsIcon           { return newIcon(solidIcon, "lightbulb") }
func FaSolidLink() icons.IsIcon                { return newIcon(solidIcon, "link") }
func FaSolidLiraSign() icons.IsIcon            { return newIcon(solidIcon, "lira-sign") }
func FaSolidListAlt() icons.IsIcon             { return newIcon(solidIcon, "list-alt") }
func FaSolidListOl() icons.IsIcon              { return newIcon(solidIcon, "list-ol") }
func FaSolidListUl() icons.IsIcon              { return newIcon(solidIcon, "list-ul") }
func FaSolidList() icons.IsIcon                { return newIcon(solidIcon, "list") }
func FaSolidLocationArrow() icons.IsIcon       { return newIcon(solidIcon, "location-arrow") }
func FaSolidLockOpen() icons.IsIcon            { return newIcon(solidIcon, "lock-open") }
func FaSolidLock() icons.IsIcon                { return newIcon(solidIcon, "lock") }
func FaSolidLongArrowAltDown() icons.IsIcon    { return newIcon(solidIcon, "long-arrow-alt-down") }
func FaSolidLongArrowAltLeft() icons.IsIcon    { return newIcon(solidIcon, "long-arrow-alt-left") }
func FaSolidLongArrowAltRight() icons.IsIcon   { return newIcon(solidIcon, "long-arrow-alt-right") }
func FaSolidLongArrowAltUp() icons.IsIcon      { return newIcon(solidIcon, "long-arrow-alt-up") }
func FaSolidLowVision() icons.IsIcon           { return newIcon(solidIcon, "low-vision") }
func FaSolidLuggageCart() icons.IsIcon         { return newIcon(solidIcon, "luggage-cart") }
func FaSolidLungsVirus() icons.IsIcon          { return newIcon(solidIcon, "lungs-virus") }
func FaSolidLungs() icons.IsIcon               { return newIcon(solidIcon, "lungs") }
func FaSolidMagic() icons.IsIcon               { return newIcon(solidIcon, "magic") }
func FaSolidMagnet() icons.IsIcon              { return newIcon(solidIcon, "magnet") }
func FaSolidMailBulk() icons.IsIcon            { return newIcon(solidIcon, "mail-bulk") }
func FaSolidMale() icons.IsIcon                { return newIcon(solidIcon, "male") }
func FaSolidMapMarkedAlt() icons.IsIcon        { return newIcon(solidIcon, "map-marked-alt") }
func FaSolidMapMarked() icons.IsIcon           { return newIcon(solidIcon, "map-marked") }
func FaSolidMapMarkerAlt() icons.IsIcon        { return newIcon(solidIcon, "map-marker-alt") }
func FaSolidMapMarker() icons.IsIcon           { return newIcon(solidIcon, "map-marker") }
func FaSolidMapPin() icons.IsIcon              { return newIcon(solidIcon, "map-pin") }
func FaSolidMapSigns() icons.IsIcon            { return newIcon(solidIcon, "map-signs") }
func FaSolidMap() icons.IsIcon                 { return newIcon(solidIcon, "map") }
func FaSolidMarker() icons.IsIcon              { return newIcon(solidIcon, "marker") }
func FaSolidMarsDouble() icons.IsIcon          { return newIcon(solidIcon, "mars-double") }
func FaSolidMarsStrokeH() icons.IsIcon         { return newIcon(solidIcon, "mars-stroke-h") }
func FaSolidMarsStrokeV() icons.IsIcon         { return newIcon(solidIcon, "mars-stroke-v") }
func FaSolidMarsStroke() icons.IsIcon          { return newIcon(solidIcon, "mars-stroke") }
func FaSolidMars() icons.IsIcon                { return newIcon(solidIcon, "mars") }
func FaSolidMask() icons.IsIcon                { return newIcon(solidIcon, "mask") }
func FaSolidMedal() icons.IsIcon               { return newIcon(solidIcon, "medal") }
func FaSolidMedkit() icons.IsIcon              { return newIcon(solidIcon, "medkit") }
func FaSolidMehBlank() icons.IsIcon            { return newIcon(solidIcon, "meh-blank") }
func FaSolidMehRollingEyes() icons.IsIcon      { return newIcon(solidIcon, "meh-rolling-eyes") }
func FaSolidMeh() icons.IsIcon                 { return newIcon(solidIcon, "meh") }
func FaSolidMemory() icons.IsIcon              { return newIcon(solidIcon, "memory") }
func FaSolidMenorah() icons.IsIcon             { return newIcon(solidIcon, "menorah") }
func FaSolidMercury() icons.IsIcon             { return newIcon(solidIcon, "mercury") }
func FaSolidMeteor() icons.IsIcon              { return newIcon(solidIcon, "meteor") }
func FaSolidMicrochip() icons.IsIcon           { return newIcon(solidIcon, "microchip") }
func FaSolidMicrophoneAltSlash() icons.IsIcon  { return newIcon(solidIcon, "microphone-alt-slash") }
func FaSolidMicrophoneAlt() icons.IsIcon       { return newIcon(solidIcon, "microphone-alt") }
func FaSolidMicrophoneSlash() icons.IsIcon     { return newIcon(solidIcon, "microphone-slash") }
func FaSolidMicrophone() icons.IsIcon          { return newIcon(solidIcon, "microphone") }
func FaSolidMicroscope() icons.IsIcon          { return newIcon(solidIcon, "microscope") }
func FaSolidMinusCircle() icons.IsIcon         { return newIcon(solidIcon, "minus-circle") }
func FaSolidMinusSquare() icons.IsIcon         { return newIcon(solidIcon, "minus-square") }
func FaSolidMinus() icons.IsIcon               { return newIcon(solidIcon, "minus") }
func FaSolidMitten() icons.IsIcon              { return newIcon(solidIcon, "mitten") }
func FaSolidMobileAlt() icons.IsIcon           { return newIcon(solidIcon, "mobile-alt") }
func FaSolidMobile() icons.IsIcon              { return newIcon(solidIcon, "mobile") }
func FaSolidMoneyBillAlt() icons.IsIcon        { return newIcon(solidIcon, "money-bill-alt") }
func FaSolidMoneyBillWaveAlt() icons.IsIcon    { return newIcon(solidIcon, "money-bill-wave-alt") }
func FaSolidMoneyBillWave() icons.IsIcon       { return newIcon(solidIcon, "money-bill-wave") }
func FaSolidMoneyBill() icons.IsIcon           { return newIcon(solidIcon, "money-bill") }
func FaSolidMoneyCheckAlt() icons.IsIcon       { return newIcon(solidIcon, "money-check-alt") }
func FaSolidMoneyCheck() icons.IsIcon          { return newIcon(solidIcon, "money-check") }
func FaSolidMonument() icons.IsIcon            { return newIcon(solidIcon, "monument") }
func FaSolidMoon() icons.IsIcon                { return newIcon(solidIcon, "moon") }
func FaSolidMortarPestle() icons.IsIcon        { return newIcon(solidIcon, "mortar-pestle") }
func FaSolidMosque() icons.IsIcon              { return newIcon(solidIcon, "mosque") }
func FaSolidMotorcycle() icons.IsIcon          { return newIcon(solidIcon, "motorcycle") }
func FaSolidMountain() icons.IsIcon            { return newIcon(solidIcon, "mountain") }
func FaSolidMousePointer() icons.IsIcon        { return newIcon(solidIcon, "mouse-pointer") }
func FaSolidMouse() icons.IsIcon               { return newIcon(solidIcon, "mouse") }
func FaSolidMugHot() icons.IsIcon              { return newIcon(solidIcon, "mug-hot") }
func FaSolidMusic() icons.IsIcon               { return newIcon(solidIcon, "music") }
func FaSolidNetworkWired() icons.IsIcon        { return newIcon(solidIcon, "network-wired") }
func FaSolidNeuter() icons.IsIcon              { return newIcon(solidIcon, "neuter") }
func FaSolidNewspaper() icons.IsIcon           { return newIcon(solidIcon, "newspaper") }
func FaSolidNotEqual() icons.IsIcon            { return newIcon(solidIcon, "not-equal") }
func FaSolidNotesMedical() icons.IsIcon        { return newIcon(solidIcon, "notes-medical") }
func FaSolidObjectGroup() icons.IsIcon         { return newIcon(solidIcon, "object-group") }
func FaSolidObjectUngroup() icons.IsIcon       { return newIcon(solidIcon, "object-ungroup") }
func FaSolidOilCan() icons.IsIcon              { return newIcon(solidIcon, "oil-can") }
func FaSolidOm() icons.IsIcon                  { return newIcon(solidIcon, "om") }
func FaSolidOtter() icons.IsIcon               { return newIcon(solidIcon, "otter") }
func FaSolidOutdent() icons.IsIcon             { return newIcon(solidIcon, "outdent") }
func FaSolidPager() icons.IsIcon               { return newIcon(solidIcon, "pager") }
func FaSolidPaintBrush() icons.IsIcon          { return newIcon(solidIcon, "paint-brush") }
func FaSolidPaintRoller() icons.IsIcon         { return newIcon(solidIcon, "paint-roller") }
func FaSolidPalette() icons.IsIcon             { return newIcon(solidIcon, "palette") }
func FaSolidPallet() icons.IsIcon              { return newIcon(solidIcon, "pallet") }
func FaSolidPaperPlane() icons.IsIcon          { return newIcon(solidIcon, "paper-plane") }
func FaSolidPaperclip() icons.IsIcon           { return newIcon(solidIcon, "paperclip") }
func FaSolidParachuteBox() icons.IsIcon        { return newIcon(solidIcon, "parachute-box") }
func FaSolidParagraph() icons.IsIcon           { return newIcon(solidIcon, "paragraph") }
func FaSolidParking() icons.IsIcon             { return newIcon(solidIcon, "parking") }
func FaSolidPassport() icons.IsIcon            { return newIcon(solidIcon, "passport") }
func FaSolidPastafarianism() icons.IsIcon      { return newIcon(solidIcon, "pastafarianism") }
func FaSolidPaste() icons.IsIcon               { return newIcon(solidIcon, "paste") }
func FaSolidPauseCircle() icons.IsIcon         { return newIcon(solidIcon, "pause-circle") }
func FaSolidPause() icons.IsIcon               { return newIcon(solidIcon, "pause") }
func FaSolidPaw() icons.IsIcon                 { return newIcon(solidIcon, "paw") }
func FaSolidPeace() icons.IsIcon               { return newIcon(solidIcon, "peace") }
func FaSolidPenAlt() icons.IsIcon              { return newIcon(solidIcon, "pen-alt") }
func FaSolidPenFancy() icons.IsIcon            { return newIcon(solidIcon, "pen-fancy") }
func FaSolidPenNib() icons.IsIcon              { return newIcon(solidIcon, "pen-nib") }
func FaSolidPenSquare() icons.IsIcon           { return newIcon(solidIcon, "pen-square") }
func FaSolidPen() icons.IsIcon                 { return newIcon(solidIcon, "pen") }
func FaSolidPencilAlt() icons.IsIcon           { return newIcon(solidIcon, "pencil-alt") }
func FaSolidPencilRuler() icons.IsIcon         { return newIcon(solidIcon, "pencil-ruler") }
func FaSolidPeopleArrows() icons.IsIcon        { return newIcon(solidIcon, "people-arrows") }
func FaSolidPeopleCarry() icons.IsIcon         { return newIcon(solidIcon, "people-carry") }
func FaSolidPepperHot() icons.IsIcon           { return newIcon(solidIcon, "pepper-hot") }
func FaSolidPercent() icons.IsIcon             { return newIcon(solidIcon, "percent") }
func FaSolidPercentage() icons.IsIcon          { return newIcon(solidIcon, "percentage") }
func FaSolidPersonBooth() icons.IsIcon         { return newIcon(solidIcon, "person-booth") }
func FaSolidPhoneAlt() icons.IsIcon            { return newIcon(solidIcon, "phone-alt") }
func FaSolidPhoneSlash() icons.IsIcon          { return newIcon(solidIcon, "phone-slash") }
func FaSolidPhoneSquareAlt() icons.IsIcon      { return newIcon(solidIcon, "phone-square-alt") }
func FaSolidPhoneSquare() icons.IsIcon         { return newIcon(solidIcon, "phone-square") }
func FaSolidPhoneVolume() icons.IsIcon         { return newIcon(solidIcon, "phone-volume") }
func FaSolidPhone() icons.IsIcon               { return newIcon(solidIcon, "phone") }
func FaSolidPhotoVideo() icons.IsIcon          { return newIcon(solidIcon, "photo-video") }
func FaSolidPiggyBank() icons.IsIcon           { return newIcon(solidIcon, "piggy-bank") }
func FaSolidPills() icons.IsIcon               { return newIcon(solidIcon, "pills") }
func FaSolidPizzaSlice() icons.IsIcon          { return newIcon(solidIcon, "pizza-slice") }
func FaSolidPlaceOfWorship() icons.IsIcon      { return newIcon(solidIcon, "place-of-worship") }
func FaSolidPlaneArrival() icons.IsIcon        { return newIcon(solidIcon, "plane-arrival") }
func FaSolidPlaneDeparture() icons.IsIcon      { return newIcon(solidIcon, "plane-departure") }
func FaSolidPlaneSlash() icons.IsIcon          { return newIcon(solidIcon, "plane-slash") }
func FaSolidPlane() icons.IsIcon               { return newIcon(solidIcon, "plane") }
func FaSolidPlayCircle() icons.IsIcon          { return newIcon(solidIcon, "play-circle") }
func FaSolidPlay() icons.IsIcon                { return newIcon(solidIcon, "play") }
func FaSolidPlug() icons.IsIcon                { return newIcon(solidIcon, "plug") }
func FaSolidPlusCircle() icons.IsIcon          { return newIcon(solidIcon, "plus-circle") }
func FaSolidPlusSquare() icons.IsIcon          { return newIcon(solidIcon, "plus-square") }
func FaSolidPlus() icons.IsIcon                { return newIcon(solidIcon, "plus") }
func FaSolidPodcast() icons.IsIcon             { return newIcon(solidIcon, "podcast") }
func FaSolidPollH() icons.IsIcon               { return newIcon(solidIcon, "poll-h") }
func FaSolidPoll() icons.IsIcon                { return newIcon(solidIcon, "poll") }
func FaSolidPooStorm() icons.IsIcon            { return newIcon(solidIcon, "poo-storm") }
func FaSolidPoo() icons.IsIcon                 { return newIcon(solidIcon, "poo") }
func FaSolidPoop() icons.IsIcon                { return newIcon(solidIcon, "poop") }
func FaSolidPortrait() icons.IsIcon            { return newIcon(solidIcon, "portrait") }
func FaSolidPoundSign() icons.IsIcon           { return newIcon(solidIcon, "pound-sign") }
func FaSolidPowerOff() icons.IsIcon            { return newIcon(solidIcon, "power-off") }
func FaSolidPray() icons.IsIcon                { return newIcon(solidIcon, "pray") }
func FaSolidPrayingHands() icons.IsIcon        { return newIcon(solidIcon, "praying-hands") }
func FaSolidPrescriptionBottleAlt() icons.IsIcon {
	return newIcon(solidIcon, "prescription-bottle-alt")
}
func FaSolidPrescriptionBottle() icons.IsIcon { return newIcon(solidIcon, "prescription-bottle") }
func FaSolidPrescription() icons.IsIcon       { return newIcon(solidIcon, "prescription") }
func FaSolidPrint() icons.IsIcon              { return newIcon(solidIcon, "print") }
func FaSolidProcedures() icons.IsIcon         { return newIcon(solidIcon, "procedures") }
func FaSolidProjectDiagram() icons.IsIcon     { return newIcon(solidIcon, "project-diagram") }
func FaSolidPumpMedical() icons.IsIcon        { return newIcon(solidIcon, "pump-medical") }
func FaSolidPumpSoap() icons.IsIcon           { return newIcon(solidIcon, "pump-soap") }
func FaSolidPuzzlePiece() icons.IsIcon        { return newIcon(solidIcon, "puzzle-piece") }
func FaSolidQrcode() icons.IsIcon             { return newIcon(solidIcon, "qrcode") }
func FaSolidQuestionCircle() icons.IsIcon     { return newIcon(solidIcon, "question-circle") }
func FaSolidQuestion() icons.IsIcon           { return newIcon(solidIcon, "question") }
func FaSolidQuidditch() icons.IsIcon          { return newIcon(solidIcon, "quidditch") }
func FaSolidQuoteLeft() icons.IsIcon          { return newIcon(solidIcon, "quote-left") }
func FaSolidQuoteRight() icons.IsIcon         { return newIcon(solidIcon, "quote-right") }
func FaSolidQuran() icons.IsIcon              { return newIcon(solidIcon, "quran") }
func FaSolidRadiationAlt() icons.IsIcon       { return newIcon(solidIcon, "radiation-alt") }
func FaSolidRadiation() icons.IsIcon          { return newIcon(solidIcon, "radiation") }
func FaSolidRainbow() icons.IsIcon            { return newIcon(solidIcon, "rainbow") }
func FaSolidRandom() icons.IsIcon             { return newIcon(solidIcon, "random") }
func FaSolidReceipt() icons.IsIcon            { return newIcon(solidIcon, "receipt") }
func FaSolidRecordVinyl() icons.IsIcon        { return newIcon(solidIcon, "record-vinyl") }
func FaSolidRecycle() icons.IsIcon            { return newIcon(solidIcon, "recycle") }
func FaSolidRedoAlt() icons.IsIcon            { return newIcon(solidIcon, "redo-alt") }
func FaSolidRedo() icons.IsIcon               { return newIcon(solidIcon, "redo") }
func FaSolidRegistered() icons.IsIcon         { return newIcon(solidIcon, "registered") }
func FaSolidRemoveFormat() icons.IsIcon       { return newIcon(solidIcon, "remove-format") }
func FaSolidReplyAll() icons.IsIcon           { return newIcon(solidIcon, "reply-all") }
func FaSolidReply() icons.IsIcon              { return newIcon(solidIcon, "reply") }
func FaSolidRepublican() icons.IsIcon         { return newIcon(solidIcon, "republican") }
func FaSolidRestroom() icons.IsIcon           { return newIcon(solidIcon, "restroom") }
func FaSolidRetweet() icons.IsIcon            { return newIcon(solidIcon, "retweet") }
func FaSolidRibbon() icons.IsIcon             { return newIcon(solidIcon, "ribbon") }
func FaSolidRing() icons.IsIcon               { return newIcon(solidIcon, "ring") }
func FaSolidRoad() icons.IsIcon               { return newIcon(solidIcon, "road") }
func FaSolidRobot() icons.IsIcon              { return newIcon(solidIcon, "robot") }
func FaSolidRocket() icons.IsIcon             { return newIcon(solidIcon, "rocket") }
func FaSolidRoute() icons.IsIcon              { return newIcon(solidIcon, "route") }
func FaSolidRssSquare() icons.IsIcon          { return newIcon(solidIcon, "rss-square") }
func FaSolidRss() icons.IsIcon                { return newIcon(solidIcon, "rss") }
func FaSolidRubleSign() icons.IsIcon          { return newIcon(solidIcon, "ruble-sign") }
func FaSolidRulerCombined() icons.IsIcon      { return newIcon(solidIcon, "ruler-combined") }
func FaSolidRulerHorizontal() icons.IsIcon    { return newIcon(solidIcon, "ruler-horizontal") }
func FaSolidRulerVertical() icons.IsIcon      { return newIcon(solidIcon, "ruler-vertical") }
func FaSolidRuler() icons.IsIcon              { return newIcon(solidIcon, "ruler") }
func FaSolidRunning() icons.IsIcon            { return newIcon(solidIcon, "running") }
func FaSolidRupeeSign() icons.IsIcon          { return newIcon(solidIcon, "rupee-sign") }
func FaSolidSadCry() icons.IsIcon             { return newIcon(solidIcon, "sad-cry") }
func FaSolidSadTear() icons.IsIcon            { return newIcon(solidIcon, "sad-tear") }
func FaSolidSatelliteDish() icons.IsIcon      { return newIcon(solidIcon, "satellite-dish") }
func FaSolidSatellite() icons.IsIcon          { return newIcon(solidIcon, "satellite") }
func FaSolidSave() icons.IsIcon               { return newIcon(solidIcon, "save") }
func FaSolidSchool() icons.IsIcon             { return newIcon(solidIcon, "school") }
func FaSolidScrewdriver() icons.IsIcon        { return newIcon(solidIcon, "screwdriver") }
func FaSolidScroll() icons.IsIcon             { return newIcon(solidIcon, "scroll") }
func FaSolidSdCard() icons.IsIcon             { return newIcon(solidIcon, "sd-card") }
func FaSolidSearchDollar() icons.IsIcon       { return newIcon(solidIcon, "search-dollar") }
func FaSolidSearchLocation() icons.IsIcon     { return newIcon(solidIcon, "search-location") }
func FaSolidSearchMinus() icons.IsIcon        { return newIcon(solidIcon, "search-minus") }
func FaSolidSearchPlus() icons.IsIcon         { return newIcon(solidIcon, "search-plus") }
func FaSolidSearch() icons.IsIcon             { return newIcon(solidIcon, "search") }
func FaSolidSeedling() icons.IsIcon           { return newIcon(solidIcon, "seedling") }
func FaSolidServer() icons.IsIcon             { return newIcon(solidIcon, "server") }
func FaSolidShapes() icons.IsIcon             { return newIcon(solidIcon, "shapes") }
func FaSolidShareAltSquare() icons.IsIcon     { return newIcon(solidIcon, "share-alt-square") }
func FaSolidShareAlt() icons.IsIcon           { return newIcon(solidIcon, "share-alt") }
func FaSolidShareSquare() icons.IsIcon        { return newIcon(solidIcon, "share-square") }
func FaSolidShare() icons.IsIcon              { return newIcon(solidIcon, "share") }
func FaSolidShekelSign() icons.IsIcon         { return newIcon(solidIcon, "shekel-sign") }
func FaSolidShieldAlt() icons.IsIcon          { return newIcon(solidIcon, "shield-alt") }
func FaSolidShieldVirus() icons.IsIcon        { return newIcon(solidIcon, "shield-virus") }
func FaSolidShip() icons.IsIcon               { return newIcon(solidIcon, "ship") }
func FaSolidShippingFast() icons.IsIcon       { return newIcon(solidIcon, "shipping-fast") }
func FaSolidShoePrints() icons.IsIcon         { return newIcon(solidIcon, "shoe-prints") }
func FaSolidShoppingBag() icons.IsIcon        { return newIcon(solidIcon, "shopping-bag") }
func FaSolidShoppingBasket() icons.IsIcon     { return newIcon(solidIcon, "shopping-basket") }
func FaSolidShoppingCart() icons.IsIcon       { return newIcon(solidIcon, "shopping-cart") }
func FaSolidShower() icons.IsIcon             { return newIcon(solidIcon, "shower") }
func FaSolidShuttleVan() icons.IsIcon         { return newIcon(solidIcon, "shuttle-van") }
func FaSolidSignInAlt() icons.IsIcon          { return newIcon(solidIcon, "sign-in-alt") }
func FaSolidSignLanguage() icons.IsIcon       { return newIcon(solidIcon, "sign-language") }
func FaSolidSignOutAlt() icons.IsIcon         { return newIcon(solidIcon, "sign-out-alt") }
func FaSolidSign() icons.IsIcon               { return newIcon(solidIcon, "sign") }
func FaSolidSignal() icons.IsIcon             { return newIcon(solidIcon, "signal") }
func FaSolidSignature() icons.IsIcon          { return newIcon(solidIcon, "signature") }
func FaSolidSimCard() icons.IsIcon            { return newIcon(solidIcon, "sim-card") }
func FaSolidSink() icons.IsIcon               { return newIcon(solidIcon, "sink") }
func FaSolidSitemap() icons.IsIcon            { return newIcon(solidIcon, "sitemap") }
func FaSolidSkating() icons.IsIcon            { return newIcon(solidIcon, "skating") }
func FaSolidSkiingNordic() icons.IsIcon       { return newIcon(solidIcon, "skiing-nordic") }
func FaSolidSkiing() icons.IsIcon             { return newIcon(solidIcon, "skiing") }
func FaSolidSkullCrossbones() icons.IsIcon    { return newIcon(solidIcon, "skull-crossbones") }
func FaSolidSkull() icons.IsIcon              { return newIcon(solidIcon, "skull") }
func FaSolidSlash() icons.IsIcon              { return newIcon(solidIcon, "slash") }
func FaSolidSleigh() icons.IsIcon             { return newIcon(solidIcon, "sleigh") }
func FaSolidSlidersH() icons.IsIcon           { return newIcon(solidIcon, "sliders-h") }
func FaSolidSmileBeam() icons.IsIcon          { return newIcon(solidIcon, "smile-beam") }
func FaSolidSmileWink() icons.IsIcon          { return newIcon(solidIcon, "smile-wink") }
func FaSolidSmile() icons.IsIcon              { return newIcon(solidIcon, "smile") }
func FaSolidSmog() icons.IsIcon               { return newIcon(solidIcon, "smog") }
func FaSolidSmokingBan() icons.IsIcon         { return newIcon(solidIcon, "smoking-ban") }
func FaSolidSmoking() icons.IsIcon            { return newIcon(solidIcon, "smoking") }
func FaSolidSms() icons.IsIcon                { return newIcon(solidIcon, "sms") }
func FaSolidSnowboarding() icons.IsIcon       { return newIcon(solidIcon, "snowboarding") }
func FaSolidSnowflake() icons.IsIcon          { return newIcon(solidIcon, "snowflake") }
func FaSolidSnowman() icons.IsIcon            { return newIcon(solidIcon, "snowman") }
func FaSolidSnowplow() icons.IsIcon           { return newIcon(solidIcon, "snowplow") }
func FaSolidSoap() icons.IsIcon               { return newIcon(solidIcon, "soap") }
func FaSolidSocks() icons.IsIcon              { return newIcon(solidIcon, "socks") }
func FaSolidSolarPanel() icons.IsIcon         { return newIcon(solidIcon, "solar-panel") }
func FaSolidSortAlphaDownAlt() icons.IsIcon   { return newIcon(solidIcon, "sort-alpha-down-alt") }
func FaSolidSortAlphaDown() icons.IsIcon      { return newIcon(solidIcon, "sort-alpha-down") }
func FaSolidSortAlphaUpAlt() icons.IsIcon     { return newIcon(solidIcon, "sort-alpha-up-alt") }
func FaSolidSortAlphaUp() icons.IsIcon        { return newIcon(solidIcon, "sort-alpha-up") }
func FaSolidSortAmountDownAlt() icons.IsIcon  { return newIcon(solidIcon, "sort-amount-down-alt") }
func FaSolidSortAmountDown() icons.IsIcon     { return newIcon(solidIcon, "sort-amount-down") }
func FaSolidSortAmountUpAlt() icons.IsIcon    { return newIcon(solidIcon, "sort-amount-up-alt") }
func FaSolidSortAmountUp() icons.IsIcon       { return newIcon(solidIcon, "sort-amount-up") }
func FaSolidSortDown() icons.IsIcon           { return newIcon(solidIcon, "sort-down") }
func FaSolidSortNumericDownAlt() icons.IsIcon { return newIcon(solidIcon, "sort-numeric-down-alt") }
func FaSolidSortNumericDown() icons.IsIcon    { return newIcon(solidIcon, "sort-numeric-down") }
func FaSolidSortNumericUpAlt() icons.IsIcon   { return newIcon(solidIcon, "sort-numeric-up-alt") }
func FaSolidSortNumericUp() icons.IsIcon      { return newIcon(solidIcon, "sort-numeric-up") }
func FaSolidSortUp() icons.IsIcon             { return newIcon(solidIcon, "sort-up") }
func FaSolidSort() icons.IsIcon               { return newIcon(solidIcon, "sort") }
func FaSolidSpa() icons.IsIcon                { return newIcon(solidIcon, "spa") }
func FaSolidSpaceShuttle() icons.IsIcon       { return newIcon(solidIcon, "space-shuttle") }
func FaSolidSpellCheck() icons.IsIcon         { return newIcon(solidIcon, "spell-check") }
func FaSolidSpider() icons.IsIcon             { return newIcon(solidIcon, "spider") }
func FaSolidSpinner() icons.IsIcon            { return newIcon(solidIcon, "spinner") }
func FaSolidSplotch() icons.IsIcon            { return newIcon(solidIcon, "splotch") }
func FaSolidSprayCan() icons.IsIcon           { return newIcon(solidIcon, "spray-can") }
func FaSolidSquareFull() icons.IsIcon         { return newIcon(solidIcon, "square-full") }
func FaSolidSquareRootAlt() icons.IsIcon      { return newIcon(solidIcon, "square-root-alt") }
func FaSolidSquare() icons.IsIcon             { return newIcon(solidIcon, "square") }
func FaSolidStamp() icons.IsIcon              { return newIcon(solidIcon, "stamp") }
func FaSolidStarAndCrescent() icons.IsIcon    { return newIcon(solidIcon, "star-and-crescent") }
func FaSolidStarHalfAlt() icons.IsIcon        { return newIcon(solidIcon, "star-half-alt") }
func FaSolidStarHalf() icons.IsIcon           { return newIcon(solidIcon, "star-half") }
func FaSolidStarOfDavid() icons.IsIcon        { return newIcon(solidIcon, "star-of-david") }
func FaSolidStarOfLife() icons.IsIcon         { return newIcon(solidIcon, "star-of-life") }
func FaSolidStar() icons.IsIcon               { return newIcon(solidIcon, "star") }
func FaSolidStepBackward() icons.IsIcon       { return newIcon(solidIcon, "step-backward") }
func FaSolidStepForward() icons.IsIcon        { return newIcon(solidIcon, "step-forward") }
func FaSolidStethoscope() icons.IsIcon        { return newIcon(solidIcon, "stethoscope") }
func FaSolidStickyNote() icons.IsIcon         { return newIcon(solidIcon, "sticky-note") }
func FaSolidStopCircle() icons.IsIcon         { return newIcon(solidIcon, "stop-circle") }
func FaSolidStop() icons.IsIcon               { return newIcon(solidIcon, "stop") }
func FaSolidStopwatch20() icons.IsIcon        { return newIcon(solidIcon, "stopwatch-20") }
func FaSolidStopwatch() icons.IsIcon          { return newIcon(solidIcon, "stopwatch") }
func FaSolidStoreAltSlash() icons.IsIcon      { return newIcon(solidIcon, "store-alt-slash") }
func FaSolidStoreAlt() icons.IsIcon           { return newIcon(solidIcon, "store-alt") }
func FaSolidStoreSlash() icons.IsIcon         { return newIcon(solidIcon, "store-slash") }
func FaSolidStore() icons.IsIcon              { return newIcon(solidIcon, "store") }
func FaSolidStream() icons.IsIcon             { return newIcon(solidIcon, "stream") }
func FaSolidStreetView() icons.IsIcon         { return newIcon(solidIcon, "street-view") }
func FaSolidStrikethrough() icons.IsIcon      { return newIcon(solidIcon, "strikethrough") }
func FaSolidStroopwafel() icons.IsIcon        { return newIcon(solidIcon, "stroopwafel") }
func FaSolidSubscript() icons.IsIcon          { return newIcon(solidIcon, "subscript") }
func FaSolidSubway() icons.IsIcon             { return newIcon(solidIcon, "subway") }
func FaSolidSuitcaseRolling() icons.IsIcon    { return newIcon(solidIcon, "suitcase-rolling") }
func FaSolidSuitcase() icons.IsIcon           { return newIcon(solidIcon, "suitcase") }
func FaSolidSun() icons.IsIcon                { return newIcon(solidIcon, "sun") }
func FaSolidSuperscript() icons.IsIcon        { return newIcon(solidIcon, "superscript") }
func FaSolidSurprise() icons.IsIcon           { return newIcon(solidIcon, "surprise") }
func FaSolidSwatchbook() icons.IsIcon         { return newIcon(solidIcon, "swatchbook") }
func FaSolidSwimmer() icons.IsIcon            { return newIcon(solidIcon, "swimmer") }
func FaSolidSwimmingPool() icons.IsIcon       { return newIcon(solidIcon, "swimming-pool") }
func FaSolidSynagogue() icons.IsIcon          { return newIcon(solidIcon, "synagogue") }
func FaSolidSyncAlt() icons.IsIcon            { return newIcon(solidIcon, "sync-alt") }
func FaSolidSync() icons.IsIcon               { return newIcon(solidIcon, "sync") }
func FaSolidSyringe() icons.IsIcon            { return newIcon(solidIcon, "syringe") }
func FaSolidTableTennis() icons.IsIcon        { return newIcon(solidIcon, "table-tennis") }
func FaSolidTable() icons.IsIcon              { return newIcon(solidIcon, "table") }
func FaSolidTabletAlt() icons.IsIcon          { return newIcon(solidIcon, "tablet-alt") }
func FaSolidTablet() icons.IsIcon             { return newIcon(solidIcon, "tablet") }
func FaSolidTablets() icons.IsIcon            { return newIcon(solidIcon, "tablets") }
func FaSolidTachometerAlt() icons.IsIcon      { return newIcon(solidIcon, "tachometer-alt") }
func FaSolidTag() icons.IsIcon                { return newIcon(solidIcon, "tag") }
func FaSolidTags() icons.IsIcon               { return newIcon(solidIcon, "tags") }
func FaSolidTape() icons.IsIcon               { return newIcon(solidIcon, "tape") }
func FaSolidTasks() icons.IsIcon              { return newIcon(solidIcon, "tasks") }
func FaSolidTaxi() icons.IsIcon               { return newIcon(solidIcon, "taxi") }
func FaSolidTeethOpen() icons.IsIcon          { return newIcon(solidIcon, "teeth-open") }
func FaSolidTeeth() icons.IsIcon              { return newIcon(solidIcon, "teeth") }
func FaSolidTemperatureHigh() icons.IsIcon    { return newIcon(solidIcon, "temperature-high") }
func FaSolidTemperatureLow() icons.IsIcon     { return newIcon(solidIcon, "temperature-low") }
func FaSolidTenge() icons.IsIcon              { return newIcon(solidIcon, "tenge") }
func FaSolidTerminal() icons.IsIcon           { return newIcon(solidIcon, "terminal") }
func FaSolidTextHeight() icons.IsIcon         { return newIcon(solidIcon, "text-height") }
func FaSolidTextWidth() icons.IsIcon          { return newIcon(solidIcon, "text-width") }
func FaSolidThLarge() icons.IsIcon            { return newIcon(solidIcon, "th-large") }
func FaSolidThList() icons.IsIcon             { return newIcon(solidIcon, "th-list") }
func FaSolidTh() icons.IsIcon                 { return newIcon(solidIcon, "th") }
func FaSolidTheaterMasks() icons.IsIcon       { return newIcon(solidIcon, "theater-masks") }
func FaSolidThermometerEmpty() icons.IsIcon   { return newIcon(solidIcon, "thermometer-empty") }
func FaSolidThermometerFull() icons.IsIcon    { return newIcon(solidIcon, "thermometer-full") }
func FaSolidThermometerHalf() icons.IsIcon    { return newIcon(solidIcon, "thermometer-half") }
func FaSolidThermometerQuarter() icons.IsIcon { return newIcon(solidIcon, "thermometer-quarter") }
func FaSolidThermometerThreeQuarters() icons.IsIcon {
	return newIcon(solidIcon, "thermometer-three-quarters")
}
func FaSolidThermometer() icons.IsIcon      { return newIcon(solidIcon, "thermometer") }
func FaSolidThumbsDown() icons.IsIcon       { return newIcon(solidIcon, "thumbs-down") }
func FaSolidThumbsUp() icons.IsIcon         { return newIcon(solidIcon, "thumbs-up") }
func FaSolidThumbtack() icons.IsIcon        { return newIcon(solidIcon, "thumbtack") }
func FaSolidTicketAlt() icons.IsIcon        { return newIcon(solidIcon, "ticket-alt") }
func FaSolidTimesCircle() icons.IsIcon      { return newIcon(solidIcon, "times-circle") }
func FaSolidTimes() icons.IsIcon            { return newIcon(solidIcon, "times") }
func FaSolidTintSlash() icons.IsIcon        { return newIcon(solidIcon, "tint-slash") }
func FaSolidTint() icons.IsIcon             { return newIcon(solidIcon, "tint") }
func FaSolidTired() icons.IsIcon            { return newIcon(solidIcon, "tired") }
func FaSolidToggleOff() icons.IsIcon        { return newIcon(solidIcon, "toggle-off") }
func FaSolidToggleOn() icons.IsIcon         { return newIcon(solidIcon, "toggle-on") }
func FaSolidToiletPaperSlash() icons.IsIcon { return newIcon(solidIcon, "toilet-paper-slash") }
func FaSolidToiletPaper() icons.IsIcon      { return newIcon(solidIcon, "toilet-paper") }
func FaSolidToilet() icons.IsIcon           { return newIcon(solidIcon, "toilet") }
func FaSolidToolbox() icons.IsIcon          { return newIcon(solidIcon, "toolbox") }
func FaSolidTools() icons.IsIcon            { return newIcon(solidIcon, "tools") }
func FaSolidTooth() icons.IsIcon            { return newIcon(solidIcon, "tooth") }
func FaSolidTorah() icons.IsIcon            { return newIcon(solidIcon, "torah") }
func FaSolidToriiGate() icons.IsIcon        { return newIcon(solidIcon, "torii-gate") }
func FaSolidTractor() icons.IsIcon          { return newIcon(solidIcon, "tractor") }
func FaSolidTrademark() icons.IsIcon        { return newIcon(solidIcon, "trademark") }
func FaSolidTrafficLight() icons.IsIcon     { return newIcon(solidIcon, "traffic-light") }
func FaSolidTrailer() icons.IsIcon          { return newIcon(solidIcon, "trailer") }
func FaSolidTrain() icons.IsIcon            { return newIcon(solidIcon, "train") }
func FaSolidTram() icons.IsIcon             { return newIcon(solidIcon, "tram") }
func FaSolidTransgenderAlt() icons.IsIcon   { return newIcon(solidIcon, "transgender-alt") }
func FaSolidTransgender() icons.IsIcon      { return newIcon(solidIcon, "transgender") }
func FaSolidTrashAlt() icons.IsIcon         { return newIcon(solidIcon, "trash-alt") }
func FaSolidTrashRestoreAlt() icons.IsIcon  { return newIcon(solidIcon, "trash-restore-alt") }
func FaSolidTrashRestore() icons.IsIcon     { return newIcon(solidIcon, "trash-restore") }
func FaSolidTrash() icons.IsIcon            { return newIcon(solidIcon, "trash") }
func FaSolidTree() icons.IsIcon             { return newIcon(solidIcon, "tree") }
func FaSolidTrophy() icons.IsIcon           { return newIcon(solidIcon, "trophy") }
func FaSolidTruckLoading() icons.IsIcon     { return newIcon(solidIcon, "truck-loading") }
func FaSolidTruckMonster() icons.IsIcon     { return newIcon(solidIcon, "truck-monster") }
func FaSolidTruckMoving() icons.IsIcon      { return newIcon(solidIcon, "truck-moving") }
func FaSolidTruckPickup() icons.IsIcon      { return newIcon(solidIcon, "truck-pickup") }
func FaSolidTruck() icons.IsIcon            { return newIcon(solidIcon, "truck") }
func FaSolidTshirt() icons.IsIcon           { return newIcon(solidIcon, "tshirt") }
func FaSolidTty() icons.IsIcon              { return newIcon(solidIcon, "tty") }
func FaSolidTv() icons.IsIcon               { return newIcon(solidIcon, "tv") }
func FaSolidUmbrellaBeach() icons.IsIcon    { return newIcon(solidIcon, "umbrella-beach") }
func FaSolidUmbrella() icons.IsIcon         { return newIcon(solidIcon, "umbrella") }
func FaSolidUnderline() icons.IsIcon        { return newIcon(solidIcon, "underline") }
func FaSolidUndoAlt() icons.IsIcon          { return newIcon(solidIcon, "undo-alt") }
func FaSolidUndo() icons.IsIcon             { return newIcon(solidIcon, "undo") }
func FaSolidUniversalAccess() icons.IsIcon  { return newIcon(solidIcon, "universal-access") }
func FaSolidUniversity() icons.IsIcon       { return newIcon(solidIcon, "university") }
func FaSolidUnlink() icons.IsIcon           { return newIcon(solidIcon, "unlink") }
func FaSolidUnlockAlt() icons.IsIcon        { return newIcon(solidIcon, "unlock-alt") }
func FaSolidUnlock() icons.IsIcon           { return newIcon(solidIcon, "unlock") }
func FaSolidUpload() icons.IsIcon           { return newIcon(solidIcon, "upload") }
func FaSolidUserAltSlash() icons.IsIcon     { return newIcon(solidIcon, "user-alt-slash") }
func FaSolidUserAlt() icons.IsIcon          { return newIcon(solidIcon, "user-alt") }
func FaSolidUserAstronaut() icons.IsIcon    { return newIcon(solidIcon, "user-astronaut") }
func FaSolidUserCheck() icons.IsIcon        { return newIcon(solidIcon, "user-check") }
func FaSolidUserCircle() icons.IsIcon       { return newIcon(solidIcon, "user-circle") }
func FaSolidUserClock() icons.IsIcon        { return newIcon(solidIcon, "user-clock") }
func FaSolidUserCog() icons.IsIcon          { return newIcon(solidIcon, "user-cog") }
func FaSolidUserEdit() icons.IsIcon         { return newIcon(solidIcon, "user-edit") }
func FaSolidUserFriends() icons.IsIcon      { return newIcon(solidIcon, "user-friends") }
func FaSolidUserGraduate() icons.IsIcon     { return newIcon(solidIcon, "user-graduate") }
func FaSolidUserInjured() icons.IsIcon      { return newIcon(solidIcon, "user-injured") }
func FaSolidUserLock() icons.IsIcon         { return newIcon(solidIcon, "user-lock") }
func FaSolidUserMd() icons.IsIcon           { return newIcon(solidIcon, "user-md") }
func FaSolidUserMinus() icons.IsIcon        { return newIcon(solidIcon, "user-minus") }
func FaSolidUserNinja() icons.IsIcon        { return newIcon(solidIcon, "user-ninja") }
func FaSolidUserNurse() icons.IsIcon        { return newIcon(solidIcon, "user-nurse") }
func FaSolidUserPlus() icons.IsIcon         { return newIcon(solidIcon, "user-plus") }
func FaSolidUserSecret() icons.IsIcon       { return newIcon(solidIcon, "user-secret") }
func FaSolidUserShield() icons.IsIcon       { return newIcon(solidIcon, "user-shield") }
func FaSolidUserSlash() icons.IsIcon        { return newIcon(solidIcon, "user-slash") }
func FaSolidUserTag() icons.IsIcon          { return newIcon(solidIcon, "user-tag") }
func FaSolidUserTie() icons.IsIcon          { return newIcon(solidIcon, "user-tie") }
func FaSolidUserTimes() icons.IsIcon        { return newIcon(solidIcon, "user-times") }
func FaSolidUser() icons.IsIcon             { return newIcon(solidIcon, "user") }
func FaSolidUsersCog() icons.IsIcon         { return newIcon(solidIcon, "users-cog") }
func FaSolidUsersSlash() icons.IsIcon       { return newIcon(solidIcon, "users-slash") }
func FaSolidUsers() icons.IsIcon            { return newIcon(solidIcon, "users") }
func FaSolidUtensilSpoon() icons.IsIcon     { return newIcon(solidIcon, "utensil-spoon") }
func FaSolidUtensils() icons.IsIcon         { return newIcon(solidIcon, "utensils") }
func FaSolidVectorSquare() icons.IsIcon     { return newIcon(solidIcon, "vector-square") }
func FaSolidVenusDouble() icons.IsIcon      { return newIcon(solidIcon, "venus-double") }
func FaSolidVenusMars() icons.IsIcon        { return newIcon(solidIcon, "venus-mars") }
func FaSolidVenus() icons.IsIcon            { return newIcon(solidIcon, "venus") }
func FaSolidVestPatches() icons.IsIcon      { return newIcon(solidIcon, "vest-patches") }
func FaSolidVest() icons.IsIcon             { return newIcon(solidIcon, "vest") }
func FaSolidVial() icons.IsIcon             { return newIcon(solidIcon, "vial") }
func FaSolidVials() icons.IsIcon            { return newIcon(solidIcon, "vials") }
func FaSolidVideoSlash() icons.IsIcon       { return newIcon(solidIcon, "video-slash") }
func FaSolidVideo() icons.IsIcon            { return newIcon(solidIcon, "video") }
func FaSolidVihara() icons.IsIcon           { return newIcon(solidIcon, "vihara") }
func FaSolidVirusSlash() icons.IsIcon       { return newIcon(solidIcon, "virus-slash") }
func FaSolidVirus() icons.IsIcon            { return newIcon(solidIcon, "virus") }
func FaSolidViruses() icons.IsIcon          { return newIcon(solidIcon, "viruses") }
func FaSolidVoicemail() icons.IsIcon        { return newIcon(solidIcon, "voicemail") }
func FaSolidVolleyballBall() icons.IsIcon   { return newIcon(solidIcon, "volleyball-ball") }
func FaSolidVolumeDown() icons.IsIcon       { return newIcon(solidIcon, "volume-down") }
func FaSolidVolumeMute() icons.IsIcon       { return newIcon(solidIcon, "volume-mute") }
func FaSolidVolumeOff() icons.IsIcon        { return newIcon(solidIcon, "volume-off") }
func FaSolidVolumeUp() icons.IsIcon         { return newIcon(solidIcon, "volume-up") }
func FaSolidVoteYea() icons.IsIcon          { return newIcon(solidIcon, "vote-yea") }
func FaSolidVrCardboard() icons.IsIcon      { return newIcon(solidIcon, "vr-cardboard") }
func FaSolidWalking() icons.IsIcon          { return newIcon(solidIcon, "walking") }
func FaSolidWallet() icons.IsIcon           { return newIcon(solidIcon, "wallet") }
func FaSolidWarehouse() icons.IsIcon        { return newIcon(solidIcon, "warehouse") }
func FaSolidWater() icons.IsIcon            { return newIcon(solidIcon, "water") }
func FaSolidWaveSquare() icons.IsIcon       { return newIcon(solidIcon, "wave-square") }
func FaSolidWeightHanging() icons.IsIcon    { return newIcon(solidIcon, "weight-hanging") }
func FaSolidWeight() icons.IsIcon           { return newIcon(solidIcon, "weight") }
func FaSolidWheelchair() icons.IsIcon       { return newIcon(solidIcon, "wheelchair") }
func FaSolidWifi() icons.IsIcon             { return newIcon(solidIcon, "wifi") }
func FaSolidWind() icons.IsIcon             { return newIcon(solidIcon, "wind") }
func FaSolidWindowClose() icons.IsIcon      { return newIcon(solidIcon, "window-close") }
func FaSolidWindowMaximize() icons.IsIcon   { return newIcon(solidIcon, "window-maximize") }
func FaSolidWindowMinimize() icons.IsIcon   { return newIcon(solidIcon, "window-minimize") }
func FaSolidWindowRestore() icons.IsIcon    { return newIcon(solidIcon, "window-restore") }
func FaSolidWineBottle() icons.IsIcon       { return newIcon(solidIcon, "wine-bottle") }
func FaSolidWineGlassAlt() icons.IsIcon     { return newIcon(solidIcon, "wine-glass-alt") }
func FaSolidWineGlass() icons.IsIcon        { return newIcon(solidIcon, "wine-glass") }
func FaSolidWonSign() icons.IsIcon          { return newIcon(solidIcon, "won-sign") }
func FaSolidWrench() icons.IsIcon           { return newIcon(solidIcon, "wrench") }
func FaSolidXRay() icons.IsIcon             { return newIcon(solidIcon, "x-ray") }
func FaSolidYenSign() icons.IsIcon          { return newIcon(solidIcon, "yen-sign") }
func FaSolidYinYang() icons.IsIcon          { return newIcon(solidIcon, "yin-yang") }
