package fi

import "github.com/raitucarp/gomix/icons"

func FiActivity() icons.IsIcon         { return newIcon("activity") }
func FiAirplay() icons.IsIcon          { return newIcon("airplay") }
func FiAlertCircle() icons.IsIcon      { return newIcon("alert-circle") }
func FiAlertOctagon() icons.IsIcon     { return newIcon("alert-octagon") }
func FiAlertTriangle() icons.IsIcon    { return newIcon("alert-triangle") }
func FiAlignCenter() icons.IsIcon      { return newIcon("align-center") }
func FiAlignJustify() icons.IsIcon     { return newIcon("align-justify") }
func FiAlignLeft() icons.IsIcon        { return newIcon("align-left") }
func FiAlignRight() icons.IsIcon       { return newIcon("align-right") }
func FiAnchor() icons.IsIcon           { return newIcon("anchor") }
func FiAperture() icons.IsIcon         { return newIcon("aperture") }
func FiArchive() icons.IsIcon          { return newIcon("archive") }
func FiArrowDownCircle() icons.IsIcon  { return newIcon("arrow-down-circle") }
func FiArrowDownLeft() icons.IsIcon    { return newIcon("arrow-down-left") }
func FiArrowDownRight() icons.IsIcon   { return newIcon("arrow-down-right") }
func FiArrowDown() icons.IsIcon        { return newIcon("arrow-down") }
func FiArrowLeftCircle() icons.IsIcon  { return newIcon("arrow-left-circle") }
func FiArrowLeft() icons.IsIcon        { return newIcon("arrow-left") }
func FiArrowRightCircle() icons.IsIcon { return newIcon("arrow-right-circle") }
func FiArrowRight() icons.IsIcon       { return newIcon("arrow-right") }
func FiArrowUpCircle() icons.IsIcon    { return newIcon("arrow-up-circle") }
func FiArrowUpLeft() icons.IsIcon      { return newIcon("arrow-up-left") }
func FiArrowUpRight() icons.IsIcon     { return newIcon("arrow-up-right") }
func FiArrowUp() icons.IsIcon          { return newIcon("arrow-up") }
func FiAtSign() icons.IsIcon           { return newIcon("at-sign") }
func FiAward() icons.IsIcon            { return newIcon("award") }
func FiBarChart2() icons.IsIcon        { return newIcon("bar-chart-2") }
func FiBarChart() icons.IsIcon         { return newIcon("bar-chart") }
func FiBatteryCharging() icons.IsIcon  { return newIcon("battery-charging") }
func FiBattery() icons.IsIcon          { return newIcon("battery") }
func FiBellOff() icons.IsIcon          { return newIcon("bell-off") }
func FiBell() icons.IsIcon             { return newIcon("bell") }
func FiBluetooth() icons.IsIcon        { return newIcon("bluetooth") }
func FiBold() icons.IsIcon             { return newIcon("bold") }
func FiBookOpen() icons.IsIcon         { return newIcon("book-open") }
func FiBook() icons.IsIcon             { return newIcon("book") }
func FiBookmark() icons.IsIcon         { return newIcon("bookmark") }
func FiBox() icons.IsIcon              { return newIcon("box") }
func FiBriefcase() icons.IsIcon        { return newIcon("briefcase") }
func FiCalendar() icons.IsIcon         { return newIcon("calendar") }
func FiCameraOff() icons.IsIcon        { return newIcon("camera-off") }
func FiCamera() icons.IsIcon           { return newIcon("camera") }
func FiCast() icons.IsIcon             { return newIcon("cast") }
func FiCheckCircle() icons.IsIcon      { return newIcon("check-circle") }
func FiCheckSquare() icons.IsIcon      { return newIcon("check-square") }
func FiCheck() icons.IsIcon            { return newIcon("check") }
func FiChevronDown() icons.IsIcon      { return newIcon("chevron-down") }
func FiChevronLeft() icons.IsIcon      { return newIcon("chevron-left") }
func FiChevronRight() icons.IsIcon     { return newIcon("chevron-right") }
func FiChevronUp() icons.IsIcon        { return newIcon("chevron-up") }
func FiChevronsDown() icons.IsIcon     { return newIcon("chevrons-down") }
func FiChevronsLeft() icons.IsIcon     { return newIcon("chevrons-left") }
func FiChevronsRight() icons.IsIcon    { return newIcon("chevrons-right") }
func FiChevronsUp() icons.IsIcon       { return newIcon("chevrons-up") }
func FiChrome() icons.IsIcon           { return newIcon("chrome") }
func FiCircle() icons.IsIcon           { return newIcon("circle") }
func FiClipboard() icons.IsIcon        { return newIcon("clipboard") }
func FiClock() icons.IsIcon            { return newIcon("clock") }
func FiCloudDrizzle() icons.IsIcon     { return newIcon("cloud-drizzle") }
func FiCloudLightning() icons.IsIcon   { return newIcon("cloud-lightning") }
func FiCloudOff() icons.IsIcon         { return newIcon("cloud-off") }
func FiCloudRain() icons.IsIcon        { return newIcon("cloud-rain") }
func FiCloudSnow() icons.IsIcon        { return newIcon("cloud-snow") }
func FiCloud() icons.IsIcon            { return newIcon("cloud") }
func FiCode() icons.IsIcon             { return newIcon("code") }
func FiCodepen() icons.IsIcon          { return newIcon("codepen") }
func FiCodesandbox() icons.IsIcon      { return newIcon("codesandbox") }
func FiCoffee() icons.IsIcon           { return newIcon("coffee") }
func FiColumns() icons.IsIcon          { return newIcon("columns") }
func FiCommand() icons.IsIcon          { return newIcon("command") }
func FiCompass() icons.IsIcon          { return newIcon("compass") }
func FiCopy() icons.IsIcon             { return newIcon("copy") }
func FiCornerDownLeft() icons.IsIcon   { return newIcon("corner-down-left") }
func FiCornerDownRight() icons.IsIcon  { return newIcon("corner-down-right") }
func FiCornerLeftDown() icons.IsIcon   { return newIcon("corner-left-down") }
func FiCornerLeftUp() icons.IsIcon     { return newIcon("corner-left-up") }
func FiCornerRightDown() icons.IsIcon  { return newIcon("corner-right-down") }
func FiCornerRightUp() icons.IsIcon    { return newIcon("corner-right-up") }
func FiCornerUpLeft() icons.IsIcon     { return newIcon("corner-up-left") }
func FiCornerUpRight() icons.IsIcon    { return newIcon("corner-up-right") }
func FiCpu() icons.IsIcon              { return newIcon("cpu") }
func FiCreditCard() icons.IsIcon       { return newIcon("credit-card") }
func FiCrop() icons.IsIcon             { return newIcon("crop") }
func FiCrosshair() icons.IsIcon        { return newIcon("crosshair") }
func FiDatabase() icons.IsIcon         { return newIcon("database") }
func FiDelete() icons.IsIcon           { return newIcon("delete") }
func FiDisc() icons.IsIcon             { return newIcon("disc") }
func FiDivideCircle() icons.IsIcon     { return newIcon("divide-circle") }
func FiDivideSquare() icons.IsIcon     { return newIcon("divide-square") }
func FiDivide() icons.IsIcon           { return newIcon("divide") }
func FiDollarSign() icons.IsIcon       { return newIcon("dollar-sign") }
func FiDownloadCloud() icons.IsIcon    { return newIcon("download-cloud") }
func FiDownload() icons.IsIcon         { return newIcon("download") }
func FiDribbble() icons.IsIcon         { return newIcon("dribbble") }
func FiDroplet() icons.IsIcon          { return newIcon("droplet") }
func FiEdit2() icons.IsIcon            { return newIcon("edit-2") }
func FiEdit3() icons.IsIcon            { return newIcon("edit-3") }
func FiEdit() icons.IsIcon             { return newIcon("edit") }
func FiExternalLink() icons.IsIcon     { return newIcon("external-link") }
func FiEyeOff() icons.IsIcon           { return newIcon("eye-off") }
func FiEye() icons.IsIcon              { return newIcon("eye") }
func FiFacebook() icons.IsIcon         { return newIcon("facebook") }
func FiFastForward() icons.IsIcon      { return newIcon("fast-forward") }
func FiFeather() icons.IsIcon          { return newIcon("feather") }
func FiFigma() icons.IsIcon            { return newIcon("figma") }
func FiFileMinus() icons.IsIcon        { return newIcon("file-minus") }
func FiFilePlus() icons.IsIcon         { return newIcon("file-plus") }
func FiFileText() icons.IsIcon         { return newIcon("file-text") }
func FiFile() icons.IsIcon             { return newIcon("file") }
func FiFilm() icons.IsIcon             { return newIcon("film") }
func FiFilter() icons.IsIcon           { return newIcon("filter") }
func FiFlag() icons.IsIcon             { return newIcon("flag") }
func FiFolderMinus() icons.IsIcon      { return newIcon("folder-minus") }
func FiFolderPlus() icons.IsIcon       { return newIcon("folder-plus") }
func FiFolder() icons.IsIcon           { return newIcon("folder") }
func FiFramer() icons.IsIcon           { return newIcon("framer") }
func FiFrown() icons.IsIcon            { return newIcon("frown") }
func FiGift() icons.IsIcon             { return newIcon("gift") }
func FiGitBranch() icons.IsIcon        { return newIcon("git-branch") }
func FiGitCommit() icons.IsIcon        { return newIcon("git-commit") }
func FiGitMerge() icons.IsIcon         { return newIcon("git-merge") }
func FiGitPullRequest() icons.IsIcon   { return newIcon("git-pull-request") }
func FiGithub() icons.IsIcon           { return newIcon("github") }
func FiGitlab() icons.IsIcon           { return newIcon("gitlab") }
func FiGlobe() icons.IsIcon            { return newIcon("globe") }
func FiGrid() icons.IsIcon             { return newIcon("grid") }
func FiHardDrive() icons.IsIcon        { return newIcon("hard-drive") }
func FiHash() icons.IsIcon             { return newIcon("hash") }
func FiHeadphones() icons.IsIcon       { return newIcon("headphones") }
func FiHeart() icons.IsIcon            { return newIcon("heart") }
func FiHelpCircle() icons.IsIcon       { return newIcon("help-circle") }
func FiHexagon() icons.IsIcon          { return newIcon("hexagon") }
func FiHome() icons.IsIcon             { return newIcon("home") }
func FiImage() icons.IsIcon            { return newIcon("image") }
func FiInbox() icons.IsIcon            { return newIcon("inbox") }
func FiInfo() icons.IsIcon             { return newIcon("info") }
func FiInstagram() icons.IsIcon        { return newIcon("instagram") }
func FiItalic() icons.IsIcon           { return newIcon("italic") }
func FiKey() icons.IsIcon              { return newIcon("key") }
func FiLayers() icons.IsIcon           { return newIcon("layers") }
func FiLayout() icons.IsIcon           { return newIcon("layout") }
func FiLifeBuoy() icons.IsIcon         { return newIcon("life-buoy") }
func FiLink2() icons.IsIcon            { return newIcon("link-2") }
func FiLink() icons.IsIcon             { return newIcon("link") }
func FiLinkedin() icons.IsIcon         { return newIcon("linkedin") }
func FiList() icons.IsIcon             { return newIcon("list") }
func FiLoader() icons.IsIcon           { return newIcon("loader") }
func FiLock() icons.IsIcon             { return newIcon("lock") }
func FiLogIn() icons.IsIcon            { return newIcon("log-in") }
func FiLogOut() icons.IsIcon           { return newIcon("log-out") }
func FiMail() icons.IsIcon             { return newIcon("mail") }
func FiMapPin() icons.IsIcon           { return newIcon("map-pin") }
func FiMap() icons.IsIcon              { return newIcon("map") }
func FiMaximize2() icons.IsIcon        { return newIcon("maximize-2") }
func FiMaximize() icons.IsIcon         { return newIcon("maximize") }
func FiMeh() icons.IsIcon              { return newIcon("meh") }
func FiMenu() icons.IsIcon             { return newIcon("menu") }
func FiMessageCircle() icons.IsIcon    { return newIcon("message-circle") }
func FiMessageSquare() icons.IsIcon    { return newIcon("message-square") }
func FiMicOff() icons.IsIcon           { return newIcon("mic-off") }
func FiMic() icons.IsIcon              { return newIcon("mic") }
func FiMinimize2() icons.IsIcon        { return newIcon("minimize-2") }
func FiMinimize() icons.IsIcon         { return newIcon("minimize") }
func FiMinusCircle() icons.IsIcon      { return newIcon("minus-circle") }
func FiMinusSquare() icons.IsIcon      { return newIcon("minus-square") }
func FiMinus() icons.IsIcon            { return newIcon("minus") }
func FiMonitor() icons.IsIcon          { return newIcon("monitor") }
func FiMoon() icons.IsIcon             { return newIcon("moon") }
func FiMoreHorizontal() icons.IsIcon   { return newIcon("more-horizontal") }
func FiMoreVertical() icons.IsIcon     { return newIcon("more-vertical") }
func FiMousePointer() icons.IsIcon     { return newIcon("mouse-pointer") }
func FiMove() icons.IsIcon             { return newIcon("move") }
func FiMusic() icons.IsIcon            { return newIcon("music") }
func FiNavigation2() icons.IsIcon      { return newIcon("navigation-2") }
func FiNavigation() icons.IsIcon       { return newIcon("navigation") }
func FiOctagon() icons.IsIcon          { return newIcon("octagon") }
func FiPackage() icons.IsIcon          { return newIcon("package") }
func FiPaperclip() icons.IsIcon        { return newIcon("paperclip") }
func FiPauseCircle() icons.IsIcon      { return newIcon("pause-circle") }
func FiPause() icons.IsIcon            { return newIcon("pause") }
func FiPenTool() icons.IsIcon          { return newIcon("pen-tool") }
func FiPercent() icons.IsIcon          { return newIcon("percent") }
func FiPhoneCall() icons.IsIcon        { return newIcon("phone-call") }
func FiPhoneForwarded() icons.IsIcon   { return newIcon("phone-forwarded") }
func FiPhoneIncoming() icons.IsIcon    { return newIcon("phone-incoming") }
func FiPhoneMissed() icons.IsIcon      { return newIcon("phone-missed") }
func FiPhoneOff() icons.IsIcon         { return newIcon("phone-off") }
func FiPhoneOutgoing() icons.IsIcon    { return newIcon("phone-outgoing") }
func FiPhone() icons.IsIcon            { return newIcon("phone") }
func FiPieChart() icons.IsIcon         { return newIcon("pie-chart") }
func FiPlayCircle() icons.IsIcon       { return newIcon("play-circle") }
func FiPlay() icons.IsIcon             { return newIcon("play") }
func FiPlusCircle() icons.IsIcon       { return newIcon("plus-circle") }
func FiPlusSquare() icons.IsIcon       { return newIcon("plus-square") }
func FiPlus() icons.IsIcon             { return newIcon("plus") }
func FiPocket() icons.IsIcon           { return newIcon("pocket") }
func FiPower() icons.IsIcon            { return newIcon("power") }
func FiPrinter() icons.IsIcon          { return newIcon("printer") }
func FiRadio() icons.IsIcon            { return newIcon("radio") }
func FiRefreshCcw() icons.IsIcon       { return newIcon("refresh-ccw") }
func FiRefreshCw() icons.IsIcon        { return newIcon("refresh-cw") }
func FiRepeat() icons.IsIcon           { return newIcon("repeat") }
func FiRewind() icons.IsIcon           { return newIcon("rewind") }
func FiRotateCcw() icons.IsIcon        { return newIcon("rotate-ccw") }
func FiRotateCw() icons.IsIcon         { return newIcon("rotate-cw") }
func FiRss() icons.IsIcon              { return newIcon("rss") }
func FiSave() icons.IsIcon             { return newIcon("save") }
func FiScissors() icons.IsIcon         { return newIcon("scissors") }
func FiSearch() icons.IsIcon           { return newIcon("search") }
func FiSend() icons.IsIcon             { return newIcon("send") }
func FiServer() icons.IsIcon           { return newIcon("server") }
func FiSettings() icons.IsIcon         { return newIcon("settings") }
func FiShare2() icons.IsIcon           { return newIcon("share-2") }
func FiShare() icons.IsIcon            { return newIcon("share") }
func FiShieldOff() icons.IsIcon        { return newIcon("shield-off") }
func FiShield() icons.IsIcon           { return newIcon("shield") }
func FiShoppingBag() icons.IsIcon      { return newIcon("shopping-bag") }
func FiShoppingCart() icons.IsIcon     { return newIcon("shopping-cart") }
func FiShuffle() icons.IsIcon          { return newIcon("shuffle") }
func FiSidebar() icons.IsIcon          { return newIcon("sidebar") }
func FiSkipBack() icons.IsIcon         { return newIcon("skip-back") }
func FiSkipForward() icons.IsIcon      { return newIcon("skip-forward") }
func FiSlack() icons.IsIcon            { return newIcon("slack") }
func FiSlash() icons.IsIcon            { return newIcon("slash") }
func FiSliders() icons.IsIcon          { return newIcon("sliders") }
func FiSmartphone() icons.IsIcon       { return newIcon("smartphone") }
func FiSmile() icons.IsIcon            { return newIcon("smile") }
func FiSpeaker() icons.IsIcon          { return newIcon("speaker") }
func FiSquare() icons.IsIcon           { return newIcon("square") }
func FiStar() icons.IsIcon             { return newIcon("star") }
func FiStopCircle() icons.IsIcon       { return newIcon("stop-circle") }
func FiSun() icons.IsIcon              { return newIcon("sun") }
func FiSunrise() icons.IsIcon          { return newIcon("sunrise") }
func FiSunset() icons.IsIcon           { return newIcon("sunset") }
func FiTable() icons.IsIcon            { return newIcon("table") }
func FiTablet() icons.IsIcon           { return newIcon("tablet") }
func FiTag() icons.IsIcon              { return newIcon("tag") }
func FiTarget() icons.IsIcon           { return newIcon("target") }
func FiTerminal() icons.IsIcon         { return newIcon("terminal") }
func FiThermometer() icons.IsIcon      { return newIcon("thermometer") }
func FiThumbsDown() icons.IsIcon       { return newIcon("thumbs-down") }
func FiThumbsUp() icons.IsIcon         { return newIcon("thumbs-up") }
func FiToggleLeft() icons.IsIcon       { return newIcon("toggle-left") }
func FiToggleRight() icons.IsIcon      { return newIcon("toggle-right") }
func FiTool() icons.IsIcon             { return newIcon("tool") }
func FiTrash2() icons.IsIcon           { return newIcon("trash-2") }
func FiTrash() icons.IsIcon            { return newIcon("trash") }
func FiTrello() icons.IsIcon           { return newIcon("trello") }
func FiTrendingDown() icons.IsIcon     { return newIcon("trending-down") }
func FiTrendingUp() icons.IsIcon       { return newIcon("trending-up") }
func FiTriangle() icons.IsIcon         { return newIcon("triangle") }
func FiTruck() icons.IsIcon            { return newIcon("truck") }
func FiTv() icons.IsIcon               { return newIcon("tv") }
func FiTwitch() icons.IsIcon           { return newIcon("twitch") }
func FiTwitter() icons.IsIcon          { return newIcon("twitter") }
func FiType() icons.IsIcon             { return newIcon("type") }
func FiUmbrella() icons.IsIcon         { return newIcon("umbrella") }
func FiUnderline() icons.IsIcon        { return newIcon("underline") }
func FiUnlock() icons.IsIcon           { return newIcon("unlock") }
func FiUploadCloud() icons.IsIcon      { return newIcon("upload-cloud") }
func FiUpload() icons.IsIcon           { return newIcon("upload") }
func FiUserCheck() icons.IsIcon        { return newIcon("user-check") }
func FiUserMinus() icons.IsIcon        { return newIcon("user-minus") }
func FiUserPlus() icons.IsIcon         { return newIcon("user-plus") }
func FiUserX() icons.IsIcon            { return newIcon("user-x") }
func FiUser() icons.IsIcon             { return newIcon("user") }
func FiUsers() icons.IsIcon            { return newIcon("users") }
func FiVideoOff() icons.IsIcon         { return newIcon("video-off") }
func FiVideo() icons.IsIcon            { return newIcon("video") }
func FiVoicemail() icons.IsIcon        { return newIcon("voicemail") }
func FiVolume1() icons.IsIcon          { return newIcon("volume-1") }
func FiVolume2() icons.IsIcon          { return newIcon("volume-2") }
func FiVolumeX() icons.IsIcon          { return newIcon("volume-x") }
func FiVolume() icons.IsIcon           { return newIcon("volume") }
func FiWatch() icons.IsIcon            { return newIcon("watch") }
func FiWifiOff() icons.IsIcon          { return newIcon("wifi-off") }
func FiWifi() icons.IsIcon             { return newIcon("wifi") }
func FiWind() icons.IsIcon             { return newIcon("wind") }
func FiXCircle() icons.IsIcon          { return newIcon("x-circle") }
func FiXOctagon() icons.IsIcon         { return newIcon("x-octagon") }
func FiXSquare() icons.IsIcon          { return newIcon("x-square") }
func FiX() icons.IsIcon                { return newIcon("x") }
func FiYoutube() icons.IsIcon          { return newIcon("youtube") }
func FiZapOff() icons.IsIcon           { return newIcon("zap-off") }
func FiZap() icons.IsIcon              { return newIcon("zap") }
func FiZoomIn() icons.IsIcon           { return newIcon("zoom-in") }
func FiZoomOut() icons.IsIcon          { return newIcon("zoom-out") }
