package fa6

import "github.com/raitucarp/gomix/icons"

func FaAddressBook() icons.IsIcon       { return newIcon(regularIcon, "address-book") }
func FaAddressCard() icons.IsIcon       { return newIcon(regularIcon, "address-card") }
func FaBellSlash() icons.IsIcon         { return newIcon(regularIcon, "bell-slash") }
func FaBell() icons.IsIcon              { return newIcon(regularIcon, "bell") }
func FaBookmark() icons.IsIcon          { return newIcon(regularIcon, "bookmark") }
func FaBuilding() icons.IsIcon          { return newIcon(regularIcon, "building") }
func FaCalendarCheck() icons.IsIcon     { return newIcon(regularIcon, "calendar-check") }
func FaCalendarDays() icons.IsIcon      { return newIcon(regularIcon, "calendar-days") }
func FaCalendarMinus() icons.IsIcon     { return newIcon(regularIcon, "calendar-minus") }
func FaCalendarPlus() icons.IsIcon      { return newIcon(regularIcon, "calendar-plus") }
func FaCalendarXmark() icons.IsIcon     { return newIcon(regularIcon, "calendar-xmark") }
func FaCalendar() icons.IsIcon          { return newIcon(regularIcon, "calendar") }
func FaChartBar() icons.IsIcon          { return newIcon(regularIcon, "chart-bar") }
func FaChessBishop() icons.IsIcon       { return newIcon(regularIcon, "chess-bishop") }
func FaChessKing() icons.IsIcon         { return newIcon(regularIcon, "chess-king") }
func FaChessKnight() icons.IsIcon       { return newIcon(regularIcon, "chess-knight") }
func FaChessPawn() icons.IsIcon         { return newIcon(regularIcon, "chess-pawn") }
func FaChessQueen() icons.IsIcon        { return newIcon(regularIcon, "chess-queen") }
func FaChessRook() icons.IsIcon         { return newIcon(regularIcon, "chess-rook") }
func FaCircleCheck() icons.IsIcon       { return newIcon(regularIcon, "circle-check") }
func FaCircleDot() icons.IsIcon         { return newIcon(regularIcon, "circle-dot") }
func FaCircleDown() icons.IsIcon        { return newIcon(regularIcon, "circle-down") }
func FaCircleLeft() icons.IsIcon        { return newIcon(regularIcon, "circle-left") }
func FaCirclePause() icons.IsIcon       { return newIcon(regularIcon, "circle-pause") }
func FaCirclePlay() icons.IsIcon        { return newIcon(regularIcon, "circle-play") }
func FaCircleQuestion() icons.IsIcon    { return newIcon(regularIcon, "circle-question") }
func FaCircleRight() icons.IsIcon       { return newIcon(regularIcon, "circle-right") }
func FaCircleStop() icons.IsIcon        { return newIcon(regularIcon, "circle-stop") }
func FaCircleUp() icons.IsIcon          { return newIcon(regularIcon, "circle-up") }
func FaCircleUser() icons.IsIcon        { return newIcon(regularIcon, "circle-user") }
func FaCircleXmark() icons.IsIcon       { return newIcon(regularIcon, "circle-xmark") }
func FaCircle() icons.IsIcon            { return newIcon(regularIcon, "circle") }
func FaClipboard() icons.IsIcon         { return newIcon(regularIcon, "clipboard") }
func FaClock() icons.IsIcon             { return newIcon(regularIcon, "clock") }
func FaClone() icons.IsIcon             { return newIcon(regularIcon, "clone") }
func FaClosedCaptioning() icons.IsIcon  { return newIcon(regularIcon, "closed-captioning") }
func FaCommentDots() icons.IsIcon       { return newIcon(regularIcon, "comment-dots") }
func FaComment() icons.IsIcon           { return newIcon(regularIcon, "comment") }
func FaComments() icons.IsIcon          { return newIcon(regularIcon, "comments") }
func FaCompass() icons.IsIcon           { return newIcon(regularIcon, "compass") }
func FaCopy() icons.IsIcon              { return newIcon(regularIcon, "copy") }
func FaCopyright() icons.IsIcon         { return newIcon(regularIcon, "copyright") }
func FaCreditCard() icons.IsIcon        { return newIcon(regularIcon, "credit-card") }
func FaEnvelopeOpen() icons.IsIcon      { return newIcon(regularIcon, "envelope-open") }
func FaEnvelope() icons.IsIcon          { return newIcon(regularIcon, "envelope") }
func FaEyeSlash() icons.IsIcon          { return newIcon(regularIcon, "eye-slash") }
func FaEye() icons.IsIcon               { return newIcon(regularIcon, "eye") }
func FaFaceAngry() icons.IsIcon         { return newIcon(regularIcon, "face-angry") }
func FaFaceDizzy() icons.IsIcon         { return newIcon(regularIcon, "face-dizzy") }
func FaFaceFlushed() icons.IsIcon       { return newIcon(regularIcon, "face-flushed") }
func FaFaceFrownOpen() icons.IsIcon     { return newIcon(regularIcon, "face-frown-open") }
func FaFaceFrown() icons.IsIcon         { return newIcon(regularIcon, "face-frown") }
func FaFaceGrimace() icons.IsIcon       { return newIcon(regularIcon, "face-grimace") }
func FaFaceGrinBeamSweat() icons.IsIcon { return newIcon(regularIcon, "face-grin-beam-sweat") }
func FaFaceGrinBeam() icons.IsIcon      { return newIcon(regularIcon, "face-grin-beam") }
func FaFaceGrinHearts() icons.IsIcon    { return newIcon(regularIcon, "face-grin-hearts") }
func FaFaceGrinSquintTears() icons.IsIcon {
	return newIcon(regularIcon, "face-grin-squint-tears")
}
func FaFaceGrinSquint() icons.IsIcon { return newIcon(regularIcon, "face-grin-squint") }
func FaFaceGrinStars() icons.IsIcon  { return newIcon(regularIcon, "face-grin-stars") }
func FaFaceGrinTears() icons.IsIcon  { return newIcon(regularIcon, "face-grin-tears") }
func FaFaceGrinTongueSquint() icons.IsIcon {
	return newIcon(regularIcon, "face-grin-tongue-squint")
}
func FaFaceGrinTongueWink() icons.IsIcon { return newIcon(regularIcon, "face-grin-tongue-wink") }
func FaFaceGrinTongue() icons.IsIcon     { return newIcon(regularIcon, "face-grin-tongue") }
func FaFaceGrinWide() icons.IsIcon       { return newIcon(regularIcon, "face-grin-wide") }
func FaFaceGrinWink() icons.IsIcon       { return newIcon(regularIcon, "face-grin-wink") }
func FaFaceGrin() icons.IsIcon           { return newIcon(regularIcon, "face-grin") }
func FaFaceKissBeam() icons.IsIcon       { return newIcon(regularIcon, "face-kiss-beam") }
func FaFaceKissWinkHeart() icons.IsIcon  { return newIcon(regularIcon, "face-kiss-wink-heart") }
func FaFaceKiss() icons.IsIcon           { return newIcon(regularIcon, "face-kiss") }
func FaFaceLaughBeam() icons.IsIcon      { return newIcon(regularIcon, "face-laugh-beam") }
func FaFaceLaughSquint() icons.IsIcon    { return newIcon(regularIcon, "face-laugh-squint") }
func FaFaceLaughWink() icons.IsIcon      { return newIcon(regularIcon, "face-laugh-wink") }
func FaFaceLaugh() icons.IsIcon          { return newIcon(regularIcon, "face-laugh") }
func FaFaceMehBlank() icons.IsIcon       { return newIcon(regularIcon, "face-meh-blank") }
func FaFaceMeh() icons.IsIcon            { return newIcon(regularIcon, "face-meh") }
func FaFaceRollingEyes() icons.IsIcon    { return newIcon(regularIcon, "face-rolling-eyes") }
func FaFaceSadCry() icons.IsIcon         { return newIcon(regularIcon, "face-sad-cry") }
func FaFaceSadTear() icons.IsIcon        { return newIcon(regularIcon, "face-sad-tear") }
func FaFaceSmileBeam() icons.IsIcon      { return newIcon(regularIcon, "face-smile-beam") }
func FaFaceSmileWink() icons.IsIcon      { return newIcon(regularIcon, "face-smile-wink") }
func FaFaceSmile() icons.IsIcon          { return newIcon(regularIcon, "face-smile") }
func FaFaceSurprise() icons.IsIcon       { return newIcon(regularIcon, "face-surprise") }
func FaFaceTired() icons.IsIcon          { return newIcon(regularIcon, "face-tired") }
func FaFileAudio() icons.IsIcon          { return newIcon(regularIcon, "file-audio") }
func FaFileCode() icons.IsIcon           { return newIcon(regularIcon, "file-code") }
func FaFileExcel() icons.IsIcon          { return newIcon(regularIcon, "file-excel") }
func FaFileImage() icons.IsIcon          { return newIcon(regularIcon, "file-image") }
func FaFileLines() icons.IsIcon          { return newIcon(regularIcon, "file-lines") }
func FaFilePdf() icons.IsIcon            { return newIcon(regularIcon, "file-pdf") }
func FaFilePowerpoint() icons.IsIcon     { return newIcon(regularIcon, "file-powerpoint") }
func FaFileVideo() icons.IsIcon          { return newIcon(regularIcon, "file-video") }
func FaFileWord() icons.IsIcon           { return newIcon(regularIcon, "file-word") }
func FaFileZipper() icons.IsIcon         { return newIcon(regularIcon, "file-zipper") }
func FaFile() icons.IsIcon               { return newIcon(regularIcon, "file") }
func FaFlag() icons.IsIcon               { return newIcon(regularIcon, "flag") }
func FaFloppyDisk() icons.IsIcon         { return newIcon(regularIcon, "floppy-disk") }
func FaFolderClosed() icons.IsIcon       { return newIcon(regularIcon, "folder-closed") }
func FaFolderOpen() icons.IsIcon         { return newIcon(regularIcon, "folder-open") }
func FaFolder() icons.IsIcon             { return newIcon(regularIcon, "folder") }
func FaFontAwesome() icons.IsIcon        { return newIcon(regularIcon, "font-awesome") }
func FaFutbol() icons.IsIcon             { return newIcon(regularIcon, "futbol") }
func FaGem() icons.IsIcon                { return newIcon(regularIcon, "gem") }
func FaHandBackFist() icons.IsIcon       { return newIcon(regularIcon, "hand-back-fist") }
func FaHandLizard() icons.IsIcon         { return newIcon(regularIcon, "hand-lizard") }
func FaHandPeace() icons.IsIcon          { return newIcon(regularIcon, "hand-peace") }
func FaHandPointDown() icons.IsIcon      { return newIcon(regularIcon, "hand-point-down") }
func FaHandPointLeft() icons.IsIcon      { return newIcon(regularIcon, "hand-point-left") }
func FaHandPointRight() icons.IsIcon     { return newIcon(regularIcon, "hand-point-right") }
func FaHandPointUp() icons.IsIcon        { return newIcon(regularIcon, "hand-point-up") }
func FaHandPointer() icons.IsIcon        { return newIcon(regularIcon, "hand-pointer") }
func FaHandScissors() icons.IsIcon       { return newIcon(regularIcon, "hand-scissors") }
func FaHandSpock() icons.IsIcon          { return newIcon(regularIcon, "hand-spock") }
func FaHand() icons.IsIcon               { return newIcon(regularIcon, "hand") }
func FaHandshake() icons.IsIcon          { return newIcon(regularIcon, "handshake") }
func FaHardDrive() icons.IsIcon          { return newIcon(regularIcon, "hard-drive") }
func FaHeart() icons.IsIcon              { return newIcon(regularIcon, "heart") }
func FaHospital() icons.IsIcon           { return newIcon(regularIcon, "hospital") }
func FaHourglassHalf() icons.IsIcon      { return newIcon(regularIcon, "hourglass-half") }
func FaHourglass() icons.IsIcon          { return newIcon(regularIcon, "hourglass") }
func FaIdBadge() icons.IsIcon            { return newIcon(regularIcon, "id-badge") }
func FaIdCard() icons.IsIcon             { return newIcon(regularIcon, "id-card") }
func FaImage() icons.IsIcon              { return newIcon(regularIcon, "image") }
func FaImages() icons.IsIcon             { return newIcon(regularIcon, "images") }
func FaKeyboard() icons.IsIcon           { return newIcon(regularIcon, "keyboard") }
func FaLemon() icons.IsIcon              { return newIcon(regularIcon, "lemon") }
func FaLifeRing() icons.IsIcon           { return newIcon(regularIcon, "life-ring") }
func FaLightbulb() icons.IsIcon          { return newIcon(regularIcon, "lightbulb") }
func FaMap() icons.IsIcon                { return newIcon(regularIcon, "map") }
func FaMessage() icons.IsIcon            { return newIcon(regularIcon, "message") }
func FaMoneyBill1() icons.IsIcon         { return newIcon(regularIcon, "money-bill-1") }
func FaMoon() icons.IsIcon               { return newIcon(regularIcon, "moon") }
func FaNewspaper() icons.IsIcon          { return newIcon(regularIcon, "newspaper") }
func FaNoteSticky() icons.IsIcon         { return newIcon(regularIcon, "note-sticky") }
func FaObjectGroup() icons.IsIcon        { return newIcon(regularIcon, "object-group") }
func FaObjectUngroup() icons.IsIcon      { return newIcon(regularIcon, "object-ungroup") }
func FaPaperPlane() icons.IsIcon         { return newIcon(regularIcon, "paper-plane") }
func FaPaste() icons.IsIcon              { return newIcon(regularIcon, "paste") }
func FaPenToSquare() icons.IsIcon        { return newIcon(regularIcon, "pen-to-square") }
func FaRectangleList() icons.IsIcon      { return newIcon(regularIcon, "rectangle-list") }
func FaRectangleXmark() icons.IsIcon     { return newIcon(regularIcon, "rectangle-xmark") }
func FaRegistered() icons.IsIcon         { return newIcon(regularIcon, "registered") }
func FaShareFromSquare() icons.IsIcon    { return newIcon(regularIcon, "share-from-square") }
func FaSnowflake() icons.IsIcon          { return newIcon(regularIcon, "snowflake") }
func FaSquareCaretDown() icons.IsIcon    { return newIcon(regularIcon, "square-caret-down") }
func FaSquareCaretLeft() icons.IsIcon    { return newIcon(regularIcon, "square-caret-left") }
func FaSquareCaretRight() icons.IsIcon   { return newIcon(regularIcon, "square-caret-right") }
func FaSquareCaretUp() icons.IsIcon      { return newIcon(regularIcon, "square-caret-up") }
func FaSquareCheck() icons.IsIcon        { return newIcon(regularIcon, "square-check") }
func FaSquareFull() icons.IsIcon         { return newIcon(regularIcon, "square-full") }
func FaSquareMinus() icons.IsIcon        { return newIcon(regularIcon, "square-minus") }
func FaSquarePlus() icons.IsIcon         { return newIcon(regularIcon, "square-plus") }
func FaSquare() icons.IsIcon             { return newIcon(regularIcon, "square") }
func FaStarHalfStroke() icons.IsIcon     { return newIcon(regularIcon, "star-half-stroke") }
func FaStarHalf() icons.IsIcon           { return newIcon(regularIcon, "star-half") }
func FaStar() icons.IsIcon               { return newIcon(regularIcon, "star") }
func FaSun() icons.IsIcon                { return newIcon(regularIcon, "sun") }
func FaThumbsDown() icons.IsIcon         { return newIcon(regularIcon, "thumbs-down") }
func FaThumbsUp() icons.IsIcon           { return newIcon(regularIcon, "thumbs-up") }
func FaTrashCan() icons.IsIcon           { return newIcon(regularIcon, "trash-can") }
func FaUser() icons.IsIcon               { return newIcon(regularIcon, "user") }
func FaWindowMaximize() icons.IsIcon     { return newIcon(regularIcon, "window-maximize") }
func FaWindowMinimize() icons.IsIcon     { return newIcon(regularIcon, "window-minimize") }
func FaWindowRestore() icons.IsIcon      { return newIcon(regularIcon, "window-restore") }
