package fa6

import "github.com/raitucarp/gomix/icons"

func FaRegularAddressBook() icons.IsIcon       { return newIcon(regularIcon, "address-book") }
func FaRegularAddressCard() icons.IsIcon       { return newIcon(regularIcon, "address-card") }
func FaRegularBellSlash() icons.IsIcon         { return newIcon(regularIcon, "bell-slash") }
func FaRegularBell() icons.IsIcon              { return newIcon(regularIcon, "bell") }
func FaRegularBookmark() icons.IsIcon          { return newIcon(regularIcon, "bookmark") }
func FaRegularBuilding() icons.IsIcon          { return newIcon(regularIcon, "building") }
func FaRegularCalendarCheck() icons.IsIcon     { return newIcon(regularIcon, "calendar-check") }
func FaRegularCalendarDays() icons.IsIcon      { return newIcon(regularIcon, "calendar-days") }
func FaRegularCalendarMinus() icons.IsIcon     { return newIcon(regularIcon, "calendar-minus") }
func FaRegularCalendarPlus() icons.IsIcon      { return newIcon(regularIcon, "calendar-plus") }
func FaRegularCalendarXmark() icons.IsIcon     { return newIcon(regularIcon, "calendar-xmark") }
func FaRegularCalendar() icons.IsIcon          { return newIcon(regularIcon, "calendar") }
func FaRegularChartBar() icons.IsIcon          { return newIcon(regularIcon, "chart-bar") }
func FaRegularChessBishop() icons.IsIcon       { return newIcon(regularIcon, "chess-bishop") }
func FaRegularChessKing() icons.IsIcon         { return newIcon(regularIcon, "chess-king") }
func FaRegularChessKnight() icons.IsIcon       { return newIcon(regularIcon, "chess-knight") }
func FaRegularChessPawn() icons.IsIcon         { return newIcon(regularIcon, "chess-pawn") }
func FaRegularChessQueen() icons.IsIcon        { return newIcon(regularIcon, "chess-queen") }
func FaRegularChessRook() icons.IsIcon         { return newIcon(regularIcon, "chess-rook") }
func FaRegularCircleCheck() icons.IsIcon       { return newIcon(regularIcon, "circle-check") }
func FaRegularCircleDot() icons.IsIcon         { return newIcon(regularIcon, "circle-dot") }
func FaRegularCircleDown() icons.IsIcon        { return newIcon(regularIcon, "circle-down") }
func FaRegularCircleLeft() icons.IsIcon        { return newIcon(regularIcon, "circle-left") }
func FaRegularCirclePause() icons.IsIcon       { return newIcon(regularIcon, "circle-pause") }
func FaRegularCirclePlay() icons.IsIcon        { return newIcon(regularIcon, "circle-play") }
func FaRegularCircleQuestion() icons.IsIcon    { return newIcon(regularIcon, "circle-question") }
func FaRegularCircleRight() icons.IsIcon       { return newIcon(regularIcon, "circle-right") }
func FaRegularCircleStop() icons.IsIcon        { return newIcon(regularIcon, "circle-stop") }
func FaRegularCircleUp() icons.IsIcon          { return newIcon(regularIcon, "circle-up") }
func FaRegularCircleUser() icons.IsIcon        { return newIcon(regularIcon, "circle-user") }
func FaRegularCircleXmark() icons.IsIcon       { return newIcon(regularIcon, "circle-xmark") }
func FaRegularCircle() icons.IsIcon            { return newIcon(regularIcon, "circle") }
func FaRegularClipboard() icons.IsIcon         { return newIcon(regularIcon, "clipboard") }
func FaRegularClock() icons.IsIcon             { return newIcon(regularIcon, "clock") }
func FaRegularClone() icons.IsIcon             { return newIcon(regularIcon, "clone") }
func FaRegularClosedCaptioning() icons.IsIcon  { return newIcon(regularIcon, "closed-captioning") }
func FaRegularCommentDots() icons.IsIcon       { return newIcon(regularIcon, "comment-dots") }
func FaRegularComment() icons.IsIcon           { return newIcon(regularIcon, "comment") }
func FaRegularComments() icons.IsIcon          { return newIcon(regularIcon, "comments") }
func FaRegularCompass() icons.IsIcon           { return newIcon(regularIcon, "compass") }
func FaRegularCopy() icons.IsIcon              { return newIcon(regularIcon, "copy") }
func FaRegularCopyright() icons.IsIcon         { return newIcon(regularIcon, "copyright") }
func FaRegularCreditCard() icons.IsIcon        { return newIcon(regularIcon, "credit-card") }
func FaRegularEnvelopeOpen() icons.IsIcon      { return newIcon(regularIcon, "envelope-open") }
func FaRegularEnvelope() icons.IsIcon          { return newIcon(regularIcon, "envelope") }
func FaRegularEyeSlash() icons.IsIcon          { return newIcon(regularIcon, "eye-slash") }
func FaRegularEye() icons.IsIcon               { return newIcon(regularIcon, "eye") }
func FaRegularFaceAngry() icons.IsIcon         { return newIcon(regularIcon, "face-angry") }
func FaRegularFaceDizzy() icons.IsIcon         { return newIcon(regularIcon, "face-dizzy") }
func FaRegularFaceFlushed() icons.IsIcon       { return newIcon(regularIcon, "face-flushed") }
func FaRegularFaceFrownOpen() icons.IsIcon     { return newIcon(regularIcon, "face-frown-open") }
func FaRegularFaceFrown() icons.IsIcon         { return newIcon(regularIcon, "face-frown") }
func FaRegularFaceGrimace() icons.IsIcon       { return newIcon(regularIcon, "face-grimace") }
func FaRegularFaceGrinBeamSweat() icons.IsIcon { return newIcon(regularIcon, "face-grin-beam-sweat") }
func FaRegularFaceGrinBeam() icons.IsIcon      { return newIcon(regularIcon, "face-grin-beam") }
func FaRegularFaceGrinHearts() icons.IsIcon    { return newIcon(regularIcon, "face-grin-hearts") }
func FaRegularFaceGrinSquintTears() icons.IsIcon {
	return newIcon(regularIcon, "face-grin-squint-tears")
}
func FaRegularFaceGrinSquint() icons.IsIcon { return newIcon(regularIcon, "face-grin-squint") }
func FaRegularFaceGrinStars() icons.IsIcon  { return newIcon(regularIcon, "face-grin-stars") }
func FaRegularFaceGrinTears() icons.IsIcon  { return newIcon(regularIcon, "face-grin-tears") }
func FaRegularFaceGrinTongueSquint() icons.IsIcon {
	return newIcon(regularIcon, "face-grin-tongue-squint")
}
func FaRegularFaceGrinTongueWink() icons.IsIcon { return newIcon(regularIcon, "face-grin-tongue-wink") }
func FaRegularFaceGrinTongue() icons.IsIcon     { return newIcon(regularIcon, "face-grin-tongue") }
func FaRegularFaceGrinWide() icons.IsIcon       { return newIcon(regularIcon, "face-grin-wide") }
func FaRegularFaceGrinWink() icons.IsIcon       { return newIcon(regularIcon, "face-grin-wink") }
func FaRegularFaceGrin() icons.IsIcon           { return newIcon(regularIcon, "face-grin") }
func FaRegularFaceKissBeam() icons.IsIcon       { return newIcon(regularIcon, "face-kiss-beam") }
func FaRegularFaceKissWinkHeart() icons.IsIcon  { return newIcon(regularIcon, "face-kiss-wink-heart") }
func FaRegularFaceKiss() icons.IsIcon           { return newIcon(regularIcon, "face-kiss") }
func FaRegularFaceLaughBeam() icons.IsIcon      { return newIcon(regularIcon, "face-laugh-beam") }
func FaRegularFaceLaughSquint() icons.IsIcon    { return newIcon(regularIcon, "face-laugh-squint") }
func FaRegularFaceLaughWink() icons.IsIcon      { return newIcon(regularIcon, "face-laugh-wink") }
func FaRegularFaceLaugh() icons.IsIcon          { return newIcon(regularIcon, "face-laugh") }
func FaRegularFaceMehBlank() icons.IsIcon       { return newIcon(regularIcon, "face-meh-blank") }
func FaRegularFaceMeh() icons.IsIcon            { return newIcon(regularIcon, "face-meh") }
func FaRegularFaceRollingEyes() icons.IsIcon    { return newIcon(regularIcon, "face-rolling-eyes") }
func FaRegularFaceSadCry() icons.IsIcon         { return newIcon(regularIcon, "face-sad-cry") }
func FaRegularFaceSadTear() icons.IsIcon        { return newIcon(regularIcon, "face-sad-tear") }
func FaRegularFaceSmileBeam() icons.IsIcon      { return newIcon(regularIcon, "face-smile-beam") }
func FaRegularFaceSmileWink() icons.IsIcon      { return newIcon(regularIcon, "face-smile-wink") }
func FaRegularFaceSmile() icons.IsIcon          { return newIcon(regularIcon, "face-smile") }
func FaRegularFaceSurprise() icons.IsIcon       { return newIcon(regularIcon, "face-surprise") }
func FaRegularFaceTired() icons.IsIcon          { return newIcon(regularIcon, "face-tired") }
func FaRegularFileAudio() icons.IsIcon          { return newIcon(regularIcon, "file-audio") }
func FaRegularFileCode() icons.IsIcon           { return newIcon(regularIcon, "file-code") }
func FaRegularFileExcel() icons.IsIcon          { return newIcon(regularIcon, "file-excel") }
func FaRegularFileImage() icons.IsIcon          { return newIcon(regularIcon, "file-image") }
func FaRegularFileLines() icons.IsIcon          { return newIcon(regularIcon, "file-lines") }
func FaRegularFilePdf() icons.IsIcon            { return newIcon(regularIcon, "file-pdf") }
func FaRegularFilePowerpoint() icons.IsIcon     { return newIcon(regularIcon, "file-powerpoint") }
func FaRegularFileVideo() icons.IsIcon          { return newIcon(regularIcon, "file-video") }
func FaRegularFileWord() icons.IsIcon           { return newIcon(regularIcon, "file-word") }
func FaRegularFileZipper() icons.IsIcon         { return newIcon(regularIcon, "file-zipper") }
func FaRegularFile() icons.IsIcon               { return newIcon(regularIcon, "file") }
func FaRegularFlag() icons.IsIcon               { return newIcon(regularIcon, "flag") }
func FaRegularFloppyDisk() icons.IsIcon         { return newIcon(regularIcon, "floppy-disk") }
func FaRegularFolderClosed() icons.IsIcon       { return newIcon(regularIcon, "folder-closed") }
func FaRegularFolderOpen() icons.IsIcon         { return newIcon(regularIcon, "folder-open") }
func FaRegularFolder() icons.IsIcon             { return newIcon(regularIcon, "folder") }
func FaRegularFontAwesome() icons.IsIcon        { return newIcon(regularIcon, "font-awesome") }
func FaRegularFutbol() icons.IsIcon             { return newIcon(regularIcon, "futbol") }
func FaRegularGem() icons.IsIcon                { return newIcon(regularIcon, "gem") }
func FaRegularHandBackFist() icons.IsIcon       { return newIcon(regularIcon, "hand-back-fist") }
func FaRegularHandLizard() icons.IsIcon         { return newIcon(regularIcon, "hand-lizard") }
func FaRegularHandPeace() icons.IsIcon          { return newIcon(regularIcon, "hand-peace") }
func FaRegularHandPointDown() icons.IsIcon      { return newIcon(regularIcon, "hand-point-down") }
func FaRegularHandPointLeft() icons.IsIcon      { return newIcon(regularIcon, "hand-point-left") }
func FaRegularHandPointRight() icons.IsIcon     { return newIcon(regularIcon, "hand-point-right") }
func FaRegularHandPointUp() icons.IsIcon        { return newIcon(regularIcon, "hand-point-up") }
func FaRegularHandPointer() icons.IsIcon        { return newIcon(regularIcon, "hand-pointer") }
func FaRegularHandScissors() icons.IsIcon       { return newIcon(regularIcon, "hand-scissors") }
func FaRegularHandSpock() icons.IsIcon          { return newIcon(regularIcon, "hand-spock") }
func FaRegularHand() icons.IsIcon               { return newIcon(regularIcon, "hand") }
func FaRegularHandshake() icons.IsIcon          { return newIcon(regularIcon, "handshake") }
func FaRegularHardDrive() icons.IsIcon          { return newIcon(regularIcon, "hard-drive") }
func FaRegularHeart() icons.IsIcon              { return newIcon(regularIcon, "heart") }
func FaRegularHospital() icons.IsIcon           { return newIcon(regularIcon, "hospital") }
func FaRegularHourglassHalf() icons.IsIcon      { return newIcon(regularIcon, "hourglass-half") }
func FaRegularHourglass() icons.IsIcon          { return newIcon(regularIcon, "hourglass") }
func FaRegularIdBadge() icons.IsIcon            { return newIcon(regularIcon, "id-badge") }
func FaRegularIdCard() icons.IsIcon             { return newIcon(regularIcon, "id-card") }
func FaRegularImage() icons.IsIcon              { return newIcon(regularIcon, "image") }
func FaRegularImages() icons.IsIcon             { return newIcon(regularIcon, "images") }
func FaRegularKeyboard() icons.IsIcon           { return newIcon(regularIcon, "keyboard") }
func FaRegularLemon() icons.IsIcon              { return newIcon(regularIcon, "lemon") }
func FaRegularLifeRing() icons.IsIcon           { return newIcon(regularIcon, "life-ring") }
func FaRegularLightbulb() icons.IsIcon          { return newIcon(regularIcon, "lightbulb") }
func FaRegularMap() icons.IsIcon                { return newIcon(regularIcon, "map") }
func FaRegularMessage() icons.IsIcon            { return newIcon(regularIcon, "message") }
func FaRegularMoneyBill1() icons.IsIcon         { return newIcon(regularIcon, "money-bill-1") }
func FaRegularMoon() icons.IsIcon               { return newIcon(regularIcon, "moon") }
func FaRegularNewspaper() icons.IsIcon          { return newIcon(regularIcon, "newspaper") }
func FaRegularNoteSticky() icons.IsIcon         { return newIcon(regularIcon, "note-sticky") }
func FaRegularObjectGroup() icons.IsIcon        { return newIcon(regularIcon, "object-group") }
func FaRegularObjectUngroup() icons.IsIcon      { return newIcon(regularIcon, "object-ungroup") }
func FaRegularPaperPlane() icons.IsIcon         { return newIcon(regularIcon, "paper-plane") }
func FaRegularPaste() icons.IsIcon              { return newIcon(regularIcon, "paste") }
func FaRegularPenToSquare() icons.IsIcon        { return newIcon(regularIcon, "pen-to-square") }
func FaRegularRectangleList() icons.IsIcon      { return newIcon(regularIcon, "rectangle-list") }
func FaRegularRectangleXmark() icons.IsIcon     { return newIcon(regularIcon, "rectangle-xmark") }
func FaRegularRegistered() icons.IsIcon         { return newIcon(regularIcon, "registered") }
func FaRegularShareFromSquare() icons.IsIcon    { return newIcon(regularIcon, "share-from-square") }
func FaRegularSnowflake() icons.IsIcon          { return newIcon(regularIcon, "snowflake") }
func FaRegularSquareCaretDown() icons.IsIcon    { return newIcon(regularIcon, "square-caret-down") }
func FaRegularSquareCaretLeft() icons.IsIcon    { return newIcon(regularIcon, "square-caret-left") }
func FaRegularSquareCaretRight() icons.IsIcon   { return newIcon(regularIcon, "square-caret-right") }
func FaRegularSquareCaretUp() icons.IsIcon      { return newIcon(regularIcon, "square-caret-up") }
func FaRegularSquareCheck() icons.IsIcon        { return newIcon(regularIcon, "square-check") }
func FaRegularSquareFull() icons.IsIcon         { return newIcon(regularIcon, "square-full") }
func FaRegularSquareMinus() icons.IsIcon        { return newIcon(regularIcon, "square-minus") }
func FaRegularSquarePlus() icons.IsIcon         { return newIcon(regularIcon, "square-plus") }
func FaRegularSquare() icons.IsIcon             { return newIcon(regularIcon, "square") }
func FaRegularStarHalfStroke() icons.IsIcon     { return newIcon(regularIcon, "star-half-stroke") }
func FaRegularStarHalf() icons.IsIcon           { return newIcon(regularIcon, "star-half") }
func FaRegularStar() icons.IsIcon               { return newIcon(regularIcon, "star") }
func FaRegularSun() icons.IsIcon                { return newIcon(regularIcon, "sun") }
func FaRegularThumbsDown() icons.IsIcon         { return newIcon(regularIcon, "thumbs-down") }
func FaRegularThumbsUp() icons.IsIcon           { return newIcon(regularIcon, "thumbs-up") }
func FaRegularTrashCan() icons.IsIcon           { return newIcon(regularIcon, "trash-can") }
func FaRegularUser() icons.IsIcon               { return newIcon(regularIcon, "user") }
func FaRegularWindowMaximize() icons.IsIcon     { return newIcon(regularIcon, "window-maximize") }
func FaRegularWindowMinimize() icons.IsIcon     { return newIcon(regularIcon, "window-minimize") }
func FaRegularWindowRestore() icons.IsIcon      { return newIcon(regularIcon, "window-restore") }
