package cg

import "github.com/raitucarp/gomix/icons"

func CgAbstract() icons.IsIcon              { return newIcon("abstract") }
func CgAddR() icons.IsIcon                  { return newIcon("add-r") }
func CgAdd() icons.IsIcon                   { return newIcon("add") }
func CgAdidas() icons.IsIcon                { return newIcon("adidas") }
func CgAirplane() icons.IsIcon              { return newIcon("airplane") }
func CgAlarm() icons.IsIcon                 { return newIcon("alarm") }
func CgAlbum() icons.IsIcon                 { return newIcon("album") }
func CgAlignBottom() icons.IsIcon           { return newIcon("align-bottom") }
func CgAlignCenter() icons.IsIcon           { return newIcon("align-center") }
func CgAlignLeft() icons.IsIcon             { return newIcon("align-left") }
func CgAlignMiddle() icons.IsIcon           { return newIcon("align-middle") }
func CgAlignRight() icons.IsIcon            { return newIcon("align-right") }
func CgAlignTop() icons.IsIcon              { return newIcon("align-top") }
func CgAnchor() icons.IsIcon                { return newIcon("anchor") }
func CgAppleWatch() icons.IsIcon            { return newIcon("apple-watch") }
func CgArrangeBack() icons.IsIcon           { return newIcon("arrange-back") }
func CgArrangeFront() icons.IsIcon          { return newIcon("arrange-front") }
func CgArrowAlignH() icons.IsIcon           { return newIcon("arrow-align-h") }
func CgArrowAlignV() icons.IsIcon           { return newIcon("arrow-align-v") }
func CgArrowBottomLeftO() icons.IsIcon      { return newIcon("arrow-bottom-left-o") }
func CgArrowBottomLeftR() icons.IsIcon      { return newIcon("arrow-bottom-left-r") }
func CgArrowBottomLeft() icons.IsIcon       { return newIcon("arrow-bottom-left") }
func CgArrowBottomRightO() icons.IsIcon     { return newIcon("arrow-bottom-right-o") }
func CgArrowBottomRightR() icons.IsIcon     { return newIcon("arrow-bottom-right-r") }
func CgArrowBottomRight() icons.IsIcon      { return newIcon("arrow-bottom-right") }
func CgArrowDownO() icons.IsIcon            { return newIcon("arrow-down-o") }
func CgArrowDownR() icons.IsIcon            { return newIcon("arrow-down-r") }
func CgArrowDown() icons.IsIcon             { return newIcon("arrow-down") }
func CgArrowLeftO() icons.IsIcon            { return newIcon("arrow-left-o") }
func CgArrowLeftR() icons.IsIcon            { return newIcon("arrow-left-r") }
func CgArrowLeft() icons.IsIcon             { return newIcon("arrow-left") }
func CgArrowLongDownC() icons.IsIcon        { return newIcon("arrow-long-down-c") }
func CgArrowLongDownE() icons.IsIcon        { return newIcon("arrow-long-down-e") }
func CgArrowLongDownL() icons.IsIcon        { return newIcon("arrow-long-down-l") }
func CgArrowLongDownR() icons.IsIcon        { return newIcon("arrow-long-down-r") }
func CgArrowLongDown() icons.IsIcon         { return newIcon("arrow-long-down") }
func CgArrowLongLeftC() icons.IsIcon        { return newIcon("arrow-long-left-c") }
func CgArrowLongLeftE() icons.IsIcon        { return newIcon("arrow-long-left-e") }
func CgArrowLongLeftL() icons.IsIcon        { return newIcon("arrow-long-left-l") }
func CgArrowLongLeftR() icons.IsIcon        { return newIcon("arrow-long-left-r") }
func CgArrowLongLeft() icons.IsIcon         { return newIcon("arrow-long-left") }
func CgArrowLongRightC() icons.IsIcon       { return newIcon("arrow-long-right-c") }
func CgArrowLongRightE() icons.IsIcon       { return newIcon("arrow-long-right-e") }
func CgArrowLongRightL() icons.IsIcon       { return newIcon("arrow-long-right-l") }
func CgArrowLongRightR() icons.IsIcon       { return newIcon("arrow-long-right-r") }
func CgArrowLongRight() icons.IsIcon        { return newIcon("arrow-long-right") }
func CgArrowLongUpC() icons.IsIcon          { return newIcon("arrow-long-up-c") }
func CgArrowLongUpE() icons.IsIcon          { return newIcon("arrow-long-up-e") }
func CgArrowLongUpL() icons.IsIcon          { return newIcon("arrow-long-up-l") }
func CgArrowLongUpR() icons.IsIcon          { return newIcon("arrow-long-up-r") }
func CgArrowLongUp() icons.IsIcon           { return newIcon("arrow-long-up") }
func CgArrowRightO() icons.IsIcon           { return newIcon("arrow-right-o") }
func CgArrowRightR() icons.IsIcon           { return newIcon("arrow-right-r") }
func CgArrowRight() icons.IsIcon            { return newIcon("arrow-right") }
func CgArrowTopLeftO() icons.IsIcon         { return newIcon("arrow-top-left-o") }
func CgArrowTopLeftR() icons.IsIcon         { return newIcon("arrow-top-left-r") }
func CgArrowTopLeft() icons.IsIcon          { return newIcon("arrow-top-left") }
func CgArrowTopRightO() icons.IsIcon        { return newIcon("arrow-top-right-o") }
func CgArrowTopRightR() icons.IsIcon        { return newIcon("arrow-top-right-r") }
func CgArrowTopRight() icons.IsIcon         { return newIcon("arrow-top-right") }
func CgArrowUpO() icons.IsIcon              { return newIcon("arrow-up-o") }
func CgArrowUpR() icons.IsIcon              { return newIcon("arrow-up-r") }
func CgArrowUp() icons.IsIcon               { return newIcon("arrow-up") }
func CgArrowsBreakeH() icons.IsIcon         { return newIcon("arrows-breake-h") }
func CgArrowsBreakeV() icons.IsIcon         { return newIcon("arrows-breake-v") }
func CgArrowsExchangeAltV() icons.IsIcon    { return newIcon("arrows-exchange-alt-v") }
func CgArrowsExchangeAlt() icons.IsIcon     { return newIcon("arrows-exchange-alt") }
func CgArrowsExchangeV() icons.IsIcon       { return newIcon("arrows-exchange-v") }
func CgArrowsExchange() icons.IsIcon        { return newIcon("arrows-exchange") }
func CgArrowsExpandDownLeft() icons.IsIcon  { return newIcon("arrows-expand-down-left") }
func CgArrowsExpandDownRight() icons.IsIcon { return newIcon("arrows-expand-down-right") }
func CgArrowsExpandLeftAlt() icons.IsIcon   { return newIcon("arrows-expand-left-alt") }
func CgArrowsExpandLeft() icons.IsIcon      { return newIcon("arrows-expand-left") }
func CgArrowsExpandRightAlt() icons.IsIcon  { return newIcon("arrows-expand-right-alt") }
func CgArrowsExpandRight() icons.IsIcon     { return newIcon("arrows-expand-right") }
func CgArrowsExpandUpLeft() icons.IsIcon    { return newIcon("arrows-expand-up-left") }
func CgArrowsExpandUpRight() icons.IsIcon   { return newIcon("arrows-expand-up-right") }
func CgArrowsHAlt() icons.IsIcon            { return newIcon("arrows-h-alt") }
func CgArrowsH() icons.IsIcon               { return newIcon("arrows-h") }
func CgArrowsMergeAltH() icons.IsIcon       { return newIcon("arrows-merge-alt-h") }
func CgArrowsMergeAltV() icons.IsIcon       { return newIcon("arrows-merge-alt-v") }
func CgArrowsScrollH() icons.IsIcon         { return newIcon("arrows-scroll-h") }
func CgArrowsScrollV() icons.IsIcon         { return newIcon("arrows-scroll-v") }
func CgArrowsShrinkH() icons.IsIcon         { return newIcon("arrows-shrink-h") }
func CgArrowsShrinkV() icons.IsIcon         { return newIcon("arrows-shrink-v") }
func CgArrowsVAlt() icons.IsIcon            { return newIcon("arrows-v-alt") }
func CgArrowsV() icons.IsIcon               { return newIcon("arrows-v") }
func CgAssign() icons.IsIcon                { return newIcon("assign") }
func CgAsterisk() icons.IsIcon              { return newIcon("asterisk") }
func CgAtlasian() icons.IsIcon              { return newIcon("atlasian") }
func CgAttachment() icons.IsIcon            { return newIcon("attachment") }
func CgAttribution() icons.IsIcon           { return newIcon("attribution") }
func CgAwards() icons.IsIcon                { return newIcon("awards") }
func CgBackspace() icons.IsIcon             { return newIcon("backspace") }
func CgBandAid() icons.IsIcon               { return newIcon("band-aid") }
func CgBatteryEmpty() icons.IsIcon          { return newIcon("battery-empty") }
func CgBatteryFull() icons.IsIcon           { return newIcon("battery-full") }
func CgBattery() icons.IsIcon               { return newIcon("battery") }
func CgBee() icons.IsIcon                   { return newIcon("bee") }
func CgBell() icons.IsIcon                  { return newIcon("bell") }
func CgBitbucket() icons.IsIcon             { return newIcon("bitbucket") }
func CgBlock() icons.IsIcon                 { return newIcon("block") }
func CgBmw() icons.IsIcon                   { return newIcon("bmw") }
func CgBoard() icons.IsIcon                 { return newIcon("board") }
func CgBolt() icons.IsIcon                  { return newIcon("bolt") }
func CgBookmark() icons.IsIcon              { return newIcon("bookmark") }
func CgBorderAll() icons.IsIcon             { return newIcon("border-all") }
func CgBorderBottom() icons.IsIcon          { return newIcon("border-bottom") }
func CgBorderLeft() icons.IsIcon            { return newIcon("border-left") }
func CgBorderRight() icons.IsIcon           { return newIcon("border-right") }
func CgBorderStyleDashed() icons.IsIcon     { return newIcon("border-style-dashed") }
func CgBorderStyleDotted() icons.IsIcon     { return newIcon("border-style-dotted") }
func CgBorderStyleSolid() icons.IsIcon      { return newIcon("border-style-solid") }
func CgBorderTop() icons.IsIcon             { return newIcon("border-top") }
func CgBot() icons.IsIcon                   { return newIcon("bot") }
func CgBowl() icons.IsIcon                  { return newIcon("bowl") }
func CgBox() icons.IsIcon                   { return newIcon("box") }
func CgBoy() icons.IsIcon                   { return newIcon("boy") }
func CgBrackets() icons.IsIcon              { return newIcon("brackets") }
func CgBriefcase() icons.IsIcon             { return newIcon("briefcase") }
func CgBrowse() icons.IsIcon                { return newIcon("browse") }
func CgBrowser() icons.IsIcon               { return newIcon("browser") }
func CgBrush() icons.IsIcon                 { return newIcon("brush") }
func CgBulb() icons.IsIcon                  { return newIcon("bulb") }
func CgCPlusPlus() icons.IsIcon             { return newIcon("c-plus-plus") }
func CgCalculator() icons.IsIcon            { return newIcon("calculator") }
func CgCalendarDates() icons.IsIcon         { return newIcon("calendar-dates") }
func CgCalendarDue() icons.IsIcon           { return newIcon("calendar-due") }
func CgCalendarNext() icons.IsIcon          { return newIcon("calendar-next") }
func CgCalendarToday() icons.IsIcon         { return newIcon("calendar-today") }
func CgCalendarTwo() icons.IsIcon           { return newIcon("calendar-two") }
func CgCalendar() icons.IsIcon              { return newIcon("calendar") }
func CgCalibrate() icons.IsIcon             { return newIcon("calibrate") }
func CgCamera() icons.IsIcon                { return newIcon("camera") }
func CgCap() icons.IsIcon                   { return newIcon("cap") }
func CgCaptions() icons.IsIcon              { return newIcon("captions") }
func CgCardClubs() icons.IsIcon             { return newIcon("card-clubs") }
func CgCardDiamonds() icons.IsIcon          { return newIcon("card-diamonds") }
func CgCardHearts() icons.IsIcon            { return newIcon("card-hearts") }
func CgCardSpades() icons.IsIcon            { return newIcon("card-spades") }
func CgCarousel() icons.IsIcon              { return newIcon("carousel") }
func CgCast() icons.IsIcon                  { return newIcon("cast") }
func CgChanel() icons.IsIcon                { return newIcon("chanel") }
func CgChart() icons.IsIcon                 { return newIcon("chart") }
func CgCheckO() icons.IsIcon                { return newIcon("check-o") }
func CgCheckR() icons.IsIcon                { return newIcon("check-r") }
func CgCheck() icons.IsIcon                 { return newIcon("check") }
func CgChevronDoubleDownO() icons.IsIcon    { return newIcon("chevron-double-down-o") }
func CgChevronDoubleDownR() icons.IsIcon    { return newIcon("chevron-double-down-r") }
func CgChevronDoubleDown() icons.IsIcon     { return newIcon("chevron-double-down") }
func CgChevronDoubleLeftO() icons.IsIcon    { return newIcon("chevron-double-left-o") }
func CgChevronDoubleLeftR() icons.IsIcon    { return newIcon("chevron-double-left-r") }
func CgChevronDoubleLeft() icons.IsIcon     { return newIcon("chevron-double-left") }
func CgChevronDoubleRightO() icons.IsIcon   { return newIcon("chevron-double-right-o") }
func CgChevronDoubleRightR() icons.IsIcon   { return newIcon("chevron-double-right-r") }
func CgChevronDoubleRight() icons.IsIcon    { return newIcon("chevron-double-right") }
func CgChevronDoubleUpO() icons.IsIcon      { return newIcon("chevron-double-up-o") }
func CgChevronDoubleUpR() icons.IsIcon      { return newIcon("chevron-double-up-r") }
func CgChevronDoubleUp() icons.IsIcon       { return newIcon("chevron-double-up") }
func CgChevronDownO() icons.IsIcon          { return newIcon("chevron-down-o") }
func CgChevronDownR() icons.IsIcon          { return newIcon("chevron-down-r") }
func CgChevronDown() icons.IsIcon           { return newIcon("chevron-down") }
func CgChevronLeftO() icons.IsIcon          { return newIcon("chevron-left-o") }
func CgChevronLeftR() icons.IsIcon          { return newIcon("chevron-left-r") }
func CgChevronLeft() icons.IsIcon           { return newIcon("chevron-left") }
func CgChevronRightO() icons.IsIcon         { return newIcon("chevron-right-o") }
func CgChevronRightR() icons.IsIcon         { return newIcon("chevron-right-r") }
func CgChevronRight() icons.IsIcon          { return newIcon("chevron-right") }
func CgChevronUpO() icons.IsIcon            { return newIcon("chevron-up-o") }
func CgChevronUpR() icons.IsIcon            { return newIcon("chevron-up-r") }
func CgChevronUp() icons.IsIcon             { return newIcon("chevron-up") }
func CgCircleci() icons.IsIcon              { return newIcon("circleci") }
func CgClapperBoard() icons.IsIcon          { return newIcon("clapper-board") }
func CgClipboard() icons.IsIcon             { return newIcon("clipboard") }
func CgCloseO() icons.IsIcon                { return newIcon("close-o") }
func CgCloseR() icons.IsIcon                { return newIcon("close-r") }
func CgClose() icons.IsIcon                 { return newIcon("close") }
func CgCloud() icons.IsIcon                 { return newIcon("cloud") }
func CgCodeClimate() icons.IsIcon           { return newIcon("code-climate") }
func CgCodeSlash() icons.IsIcon             { return newIcon("code-slash") }
func CgCode() icons.IsIcon                  { return newIcon("code") }
func CgCoffee() icons.IsIcon                { return newIcon("coffee") }
func CgCollage() icons.IsIcon               { return newIcon("collage") }
func CgColorBucket() icons.IsIcon           { return newIcon("color-bucket") }
func CgColorPicker() icons.IsIcon           { return newIcon("color-picker") }
func CgComedyCentral() icons.IsIcon         { return newIcon("comedy-central") }
func CgComment() icons.IsIcon               { return newIcon("comment") }
func CgCommunity() icons.IsIcon             { return newIcon("community") }
func CgComponents() icons.IsIcon            { return newIcon("components") }
func CgCompressLeft() icons.IsIcon          { return newIcon("compress-left") }
func CgCompressRight() icons.IsIcon         { return newIcon("compress-right") }
func CgCompressV() icons.IsIcon             { return newIcon("compress-v") }
func CgCompress() icons.IsIcon              { return newIcon("compress") }
func CgController() icons.IsIcon            { return newIcon("controller") }
func CgCopy() icons.IsIcon                  { return newIcon("copy") }
func CgCopyright() icons.IsIcon             { return newIcon("copyright") }
func CgCornerDoubleDownLeft() icons.IsIcon  { return newIcon("corner-double-down-left") }
func CgCornerDoubleDownRight() icons.IsIcon { return newIcon("corner-double-down-right") }
func CgCornerDoubleLeftDown() icons.IsIcon  { return newIcon("corner-double-left-down") }
func CgCornerDoubleLeftUp() icons.IsIcon    { return newIcon("corner-double-left-up") }
func CgCornerDoubleRightDown() icons.IsIcon { return newIcon("corner-double-right-down") }
func CgCornerDoubleRightUp() icons.IsIcon   { return newIcon("corner-double-right-up") }
func CgCornerDoubleUpLeft() icons.IsIcon    { return newIcon("corner-double-up-left") }
func CgCornerDoubleUpRight() icons.IsIcon   { return newIcon("corner-double-up-right") }
func CgCornerDownLeft() icons.IsIcon        { return newIcon("corner-down-left") }
func CgCornerDownRight() icons.IsIcon       { return newIcon("corner-down-right") }
func CgCornerLeftDown() icons.IsIcon        { return newIcon("corner-left-down") }
func CgCornerLeftUp() icons.IsIcon          { return newIcon("corner-left-up") }
func CgCornerRightDown() icons.IsIcon       { return newIcon("corner-right-down") }
func CgCornerRightUp() icons.IsIcon         { return newIcon("corner-right-up") }
func CgCornerUpLeft() icons.IsIcon          { return newIcon("corner-up-left") }
func CgCornerUpRight() icons.IsIcon         { return newIcon("corner-up-right") }
func CgCreditCard() icons.IsIcon            { return newIcon("credit-card") }
func CgCrop() icons.IsIcon                  { return newIcon("crop") }
func CgCross() icons.IsIcon                 { return newIcon("cross") }
func CgCrowdfire() icons.IsIcon             { return newIcon("crowdfire") }
func CgCrown() icons.IsIcon                 { return newIcon("crown") }
func CgDanger() icons.IsIcon                { return newIcon("danger") }
func CgDarkMode() icons.IsIcon              { return newIcon("dark-mode") }
func CgData() icons.IsIcon                  { return newIcon("data") }
func CgDatabase() icons.IsIcon              { return newIcon("database") }
func CgDebug() icons.IsIcon                 { return newIcon("debug") }
func CgDesignmodo() icons.IsIcon            { return newIcon("designmodo") }
func CgDesktop() icons.IsIcon               { return newIcon("desktop") }
func CgDetailsLess() icons.IsIcon           { return newIcon("details-less") }
func CgDetailsMore() icons.IsIcon           { return newIcon("details-more") }
func CgDialpad() icons.IsIcon               { return newIcon("dialpad") }
func CgDice1() icons.IsIcon                 { return newIcon("dice-1") }
func CgDice2() icons.IsIcon                 { return newIcon("dice-2") }
func CgDice3() icons.IsIcon                 { return newIcon("dice-3") }
func CgDice4() icons.IsIcon                 { return newIcon("dice-4") }
func CgDice5() icons.IsIcon                 { return newIcon("dice-5") }
func CgDice6() icons.IsIcon                 { return newIcon("dice-6") }
func CgDigitalocean() icons.IsIcon          { return newIcon("digitalocean") }
func CgDisc() icons.IsIcon                  { return newIcon("disc") }
func CgDisplayFlex() icons.IsIcon           { return newIcon("display-flex") }
func CgDisplayFullwidth() icons.IsIcon      { return newIcon("display-fullwidth") }
func CgDisplayGrid() icons.IsIcon           { return newIcon("display-grid") }
func CgDisplaySpacing() icons.IsIcon        { return newIcon("display-spacing") }
func CgDistributeHorizontal() icons.IsIcon  { return newIcon("distribute-horizontal") }
func CgDistributeVertical() icons.IsIcon    { return newIcon("distribute-vertical") }
func CgDockBottom() icons.IsIcon            { return newIcon("dock-bottom") }
func CgDockLeft() icons.IsIcon              { return newIcon("dock-left") }
func CgDockRight() icons.IsIcon             { return newIcon("dock-right") }
func CgDockWindow() icons.IsIcon            { return newIcon("dock-window") }
func CgDolby() icons.IsIcon                 { return newIcon("dolby") }
func CgDollar() icons.IsIcon                { return newIcon("dollar") }
func CgDribbble() icons.IsIcon              { return newIcon("dribbble") }
func CgDrive() icons.IsIcon                 { return newIcon("drive") }
func CgDropInvert() icons.IsIcon            { return newIcon("drop-invert") }
func CgDropOpacity() icons.IsIcon           { return newIcon("drop-opacity") }
func CgDrop() icons.IsIcon                  { return newIcon("drop") }
func CgDuplicate() icons.IsIcon             { return newIcon("duplicate") }
func CgEditBlackPoint() icons.IsIcon        { return newIcon("edit-black-point") }
func CgEditContrast() icons.IsIcon          { return newIcon("edit-contrast") }
func CgEditExposure() icons.IsIcon          { return newIcon("edit-exposure") }
func CgEditFade() icons.IsIcon              { return newIcon("edit-fade") }
func CgEditFlipH() icons.IsIcon             { return newIcon("edit-flip-h") }
func CgEditFlipV() icons.IsIcon             { return newIcon("edit-flip-v") }
func CgEditHighlight() icons.IsIcon         { return newIcon("edit-highlight") }
func CgEditMarkup() icons.IsIcon            { return newIcon("edit-markup") }
func CgEditMask() icons.IsIcon              { return newIcon("edit-mask") }
func CgEditNoise() icons.IsIcon             { return newIcon("edit-noise") }
func CgEditShadows() icons.IsIcon           { return newIcon("edit-shadows") }
func CgEditStraight() icons.IsIcon          { return newIcon("edit-straight") }
func CgEditUnmask() icons.IsIcon            { return newIcon("edit-unmask") }
func CgEject() icons.IsIcon                 { return newIcon("eject") }
func CgEnter() icons.IsIcon                 { return newIcon("enter") }
func CgErase() icons.IsIcon                 { return newIcon("erase") }
func CgEreader() icons.IsIcon               { return newIcon("ereader") }
func CgEricsson() icons.IsIcon              { return newIcon("ericsson") }
func CgEthernet() icons.IsIcon              { return newIcon("ethernet") }
func CgEuro() icons.IsIcon                  { return newIcon("euro") }
func CgEventbrite() icons.IsIcon            { return newIcon("eventbrite") }
func CgExpand() icons.IsIcon                { return newIcon("expand") }
func CgExport() icons.IsIcon                { return newIcon("export") }
func CgExtensionAdd() icons.IsIcon          { return newIcon("extension-add") }
func CgExtensionAlt() icons.IsIcon          { return newIcon("extension-alt") }
func CgExtensionRemove() icons.IsIcon       { return newIcon("extension-remove") }
func CgExtension() icons.IsIcon             { return newIcon("extension") }
func CgExternal() icons.IsIcon              { return newIcon("external") }
func CgEyeAlt() icons.IsIcon                { return newIcon("eye-alt") }
func CgEye() icons.IsIcon                   { return newIcon("eye") }
func CgFacebook() icons.IsIcon              { return newIcon("facebook") }
func CgFeed() icons.IsIcon                  { return newIcon("feed") }
func CgFigma() icons.IsIcon                 { return newIcon("figma") }
func CgFileAdd() icons.IsIcon               { return newIcon("file-add") }
func CgFileDocument() icons.IsIcon          { return newIcon("file-document") }
func CgFileRemove() icons.IsIcon            { return newIcon("file-remove") }
func CgFile() icons.IsIcon                  { return newIcon("file") }
func CgFilm() icons.IsIcon                  { return newIcon("film") }
func CgFilters() icons.IsIcon               { return newIcon("filters") }
func CgFlagAlt() icons.IsIcon               { return newIcon("flag-alt") }
func CgFlag() icons.IsIcon                  { return newIcon("flag") }
func CgFolderAdd() icons.IsIcon             { return newIcon("folder-add") }
func CgFolderRemove() icons.IsIcon          { return newIcon("folder-remove") }
func CgFolder() icons.IsIcon                { return newIcon("folder") }
func CgFontHeight() icons.IsIcon            { return newIcon("font-height") }
func CgFontSpacing() icons.IsIcon           { return newIcon("font-spacing") }
func CgFormatBold() icons.IsIcon            { return newIcon("format-bold") }
func CgFormatCenter() icons.IsIcon          { return newIcon("format-center") }
func CgFormatColor() icons.IsIcon           { return newIcon("format-color") }
func CgFormatHeading() icons.IsIcon         { return newIcon("format-heading") }
func CgFormatIndentDecrease() icons.IsIcon  { return newIcon("format-indent-decrease") }
func CgFormatIndentIncrease() icons.IsIcon  { return newIcon("format-indent-increase") }
func CgFormatItalic() icons.IsIcon          { return newIcon("format-italic") }
func CgFormatJustify() icons.IsIcon         { return newIcon("format-justify") }
func CgFormatLeft() icons.IsIcon            { return newIcon("format-left") }
func CgFormatLineHeight() icons.IsIcon      { return newIcon("format-line-height") }
func CgFormatRight() icons.IsIcon           { return newIcon("format-right") }
func CgFormatSeparator() icons.IsIcon       { return newIcon("format-separator") }
func CgFormatSlash() icons.IsIcon           { return newIcon("format-slash") }
func CgFormatStrike() icons.IsIcon          { return newIcon("format-strike") }
func CgFormatText() icons.IsIcon            { return newIcon("format-text") }
func CgFormatUnderline() icons.IsIcon       { return newIcon("format-underline") }
func CgFormatUppercase() icons.IsIcon       { return newIcon("format-uppercase") }
func CgFramer() icons.IsIcon                { return newIcon("framer") }
func CgGames() icons.IsIcon                 { return newIcon("games") }
func CgGenderFemale() icons.IsIcon          { return newIcon("gender-female") }
func CgGenderMale() icons.IsIcon            { return newIcon("gender-male") }
func CgGhostCharacter() icons.IsIcon        { return newIcon("ghost-character") }
func CgGhost() icons.IsIcon                 { return newIcon("ghost") }
func CgGift() icons.IsIcon                  { return newIcon("gift") }
func CgGirl() icons.IsIcon                  { return newIcon("girl") }
func CgGitBranch() icons.IsIcon             { return newIcon("git-branch") }
func CgGitCommit() icons.IsIcon             { return newIcon("git-commit") }
func CgGitFork() icons.IsIcon               { return newIcon("git-fork") }
func CgGitPull() icons.IsIcon               { return newIcon("git-pull") }
func CgGitter() icons.IsIcon                { return newIcon("gitter") }
func CgGlassAlt() icons.IsIcon              { return newIcon("glass-alt") }
func CgGlass() icons.IsIcon                 { return newIcon("glass") }
func CgGlobeAlt() icons.IsIcon              { return newIcon("globe-alt") }
func CgGlobe() icons.IsIcon                 { return newIcon("globe") }
func CgGoogleTasks() icons.IsIcon           { return newIcon("google-tasks") }
func CgGoogle() icons.IsIcon                { return newIcon("google") }
func CgGym() icons.IsIcon                   { return newIcon("gym") }
func CgHashtag() icons.IsIcon               { return newIcon("hashtag") }
func CgHeadset() icons.IsIcon               { return newIcon("headset") }
func CgHeart() icons.IsIcon                 { return newIcon("heart") }
func CgHello() icons.IsIcon                 { return newIcon("hello") }
func CgHomeAlt() icons.IsIcon               { return newIcon("home-alt") }
func CgHomeScreen() icons.IsIcon            { return newIcon("home-screen") }
func CgHome() icons.IsIcon                  { return newIcon("home") }
func CgIcecream() icons.IsIcon              { return newIcon("icecream") }
func CgIfDesign() icons.IsIcon              { return newIcon("if-design") }
func CgImage() icons.IsIcon                 { return newIcon("image") }
func CgImport() icons.IsIcon                { return newIcon("import") }
func CgInbox() icons.IsIcon                 { return newIcon("inbox") }
func CgIndieHackers() icons.IsIcon          { return newIcon("indie-hackers") }
func CgInfinity() icons.IsIcon              { return newIcon("infinity") }
func CgInfo() icons.IsIcon                  { return newIcon("info") }
func CgInpicture() icons.IsIcon             { return newIcon("inpicture") }
func CgInsertAfterO() icons.IsIcon          { return newIcon("insert-after-o") }
func CgInsertAfterR() icons.IsIcon          { return newIcon("insert-after-r") }
func CgInsertAfter() icons.IsIcon           { return newIcon("insert-after") }
func CgInsertBeforeO() icons.IsIcon         { return newIcon("insert-before-o") }
func CgInsertBeforeR() icons.IsIcon         { return newIcon("insert-before-r") }
func CgInsertBefore() icons.IsIcon          { return newIcon("insert-before") }
func CgInsights() icons.IsIcon              { return newIcon("insights") }
func CgInstagram() icons.IsIcon             { return newIcon("instagram") }
func CgInternal() icons.IsIcon              { return newIcon("internal") }
func CgKey() icons.IsIcon                   { return newIcon("key") }
func CgKeyboard() icons.IsIcon              { return newIcon("keyboard") }
func CgKeyhole() icons.IsIcon               { return newIcon("keyhole") }
func CgLaptop() icons.IsIcon                { return newIcon("laptop") }
func CgLastpass() icons.IsIcon              { return newIcon("lastpass") }
func CgLayoutGridSmall() icons.IsIcon       { return newIcon("layout-grid-small") }
func CgLayoutGrid() icons.IsIcon            { return newIcon("layout-grid") }
func CgLayoutList() icons.IsIcon            { return newIcon("layout-list") }
func CgLayoutPin() icons.IsIcon             { return newIcon("layout-pin") }
func CgLinear() icons.IsIcon                { return newIcon("linear") }
func CgLink() icons.IsIcon                  { return newIcon("link") }
func CgListTree() icons.IsIcon              { return newIcon("list-tree") }
func CgList() icons.IsIcon                  { return newIcon("list") }
func CgLivePhoto() icons.IsIcon             { return newIcon("live-photo") }
func CgLoadbarAlt() icons.IsIcon            { return newIcon("loadbar-alt") }
func CgLoadbarDoc() icons.IsIcon            { return newIcon("loadbar-doc") }
func CgLoadbarSound() icons.IsIcon          { return newIcon("loadbar-sound") }
func CgLoadbar() icons.IsIcon               { return newIcon("loadbar") }
func CgLockUnlock() icons.IsIcon            { return newIcon("lock-unlock") }
func CgLock() icons.IsIcon                  { return newIcon("lock") }
func CgLogIn() icons.IsIcon                 { return newIcon("log-in") }
func CgLogOff() icons.IsIcon                { return newIcon("log-off") }
func CgLogOut() icons.IsIcon                { return newIcon("log-out") }
func CgLoupe() icons.IsIcon                 { return newIcon("loupe") }
func CgMagnet() icons.IsIcon                { return newIcon("magnet") }
func CgMailForward() icons.IsIcon           { return newIcon("mail-forward") }
func CgMailOpen() icons.IsIcon              { return newIcon("mail-open") }
func CgMailReply() icons.IsIcon             { return newIcon("mail-reply") }
func CgMail() icons.IsIcon                  { return newIcon("mail") }
func CgMathDivide() icons.IsIcon            { return newIcon("math-divide") }
func CgMathEqual() icons.IsIcon             { return newIcon("math-equal") }
func CgMathMinus() icons.IsIcon             { return newIcon("math-minus") }
func CgMathPercent() icons.IsIcon           { return newIcon("math-percent") }
func CgMathPlus() icons.IsIcon              { return newIcon("math-plus") }
func CgMaximizeAlt() icons.IsIcon           { return newIcon("maximize-alt") }
func CgMaximize() icons.IsIcon              { return newIcon("maximize") }
func CgMaze() icons.IsIcon                  { return newIcon("maze") }
func CgMediaLive() icons.IsIcon             { return newIcon("media-live") }
func CgMediaPodcast() icons.IsIcon          { return newIcon("media-podcast") }
func CgMenuBoxed() icons.IsIcon             { return newIcon("menu-boxed") }
func CgMenuCake() icons.IsIcon              { return newIcon("menu-cake") }
func CgMenuCheese() icons.IsIcon            { return newIcon("menu-cheese") }
func CgMenuGridO() icons.IsIcon             { return newIcon("menu-grid-o") }
func CgMenuGridR() icons.IsIcon             { return newIcon("menu-grid-r") }
func CgMenuHotdog() icons.IsIcon            { return newIcon("menu-hotdog") }
func CgMenuLeftAlt() icons.IsIcon           { return newIcon("menu-left-alt") }
func CgMenuLeft() icons.IsIcon              { return newIcon("menu-left") }
func CgMenuMotion() icons.IsIcon            { return newIcon("menu-motion") }
func CgMenuOreos() icons.IsIcon             { return newIcon("menu-oreos") }
func CgMenuRightAlt() icons.IsIcon          { return newIcon("menu-right-alt") }
func CgMenuRight() icons.IsIcon             { return newIcon("menu-right") }
func CgMenuRound() icons.IsIcon             { return newIcon("menu-round") }
func CgMenu() icons.IsIcon                  { return newIcon("menu") }
func CgMergeHorizontal() icons.IsIcon       { return newIcon("merge-horizontal") }
func CgMergeVertical() icons.IsIcon         { return newIcon("merge-vertical") }
func CgMic() icons.IsIcon                   { return newIcon("mic") }
func CgMicrobit() icons.IsIcon              { return newIcon("microbit") }
func CgMicrosoft() icons.IsIcon             { return newIcon("microsoft") }
func CgMiniPlayer() icons.IsIcon            { return newIcon("mini-player") }
func CgMinimizeAlt() icons.IsIcon           { return newIcon("minimize-alt") }
func CgMinimize() icons.IsIcon              { return newIcon("minimize") }
func CgModem() icons.IsIcon                 { return newIcon("modem") }
func CgMonday() icons.IsIcon                { return newIcon("monday") }
func CgMoon() icons.IsIcon                  { return newIcon("moon") }
func CgMoreAlt() icons.IsIcon               { return newIcon("more-alt") }
func CgMoreO() icons.IsIcon                 { return newIcon("more-o") }
func CgMoreR() icons.IsIcon                 { return newIcon("more-r") }
func CgMoreVerticalAlt() icons.IsIcon       { return newIcon("more-vertical-alt") }
func CgMoreVerticalO() icons.IsIcon         { return newIcon("more-vertical-o") }
func CgMoreVerticalR() icons.IsIcon         { return newIcon("more-vertical-r") }
func CgMoreVertical() icons.IsIcon          { return newIcon("more-vertical") }
func CgMore() icons.IsIcon                  { return newIcon("more") }
func CgMouse() icons.IsIcon                 { return newIcon("mouse") }
func CgMoveDown() icons.IsIcon              { return newIcon("move-down") }
func CgMoveLeft() icons.IsIcon              { return newIcon("move-left") }
func CgMoveRight() icons.IsIcon             { return newIcon("move-right") }
func CgMoveTask() icons.IsIcon              { return newIcon("move-task") }
func CgMoveUp() icons.IsIcon                { return newIcon("move-up") }
func CgMusicNote() icons.IsIcon             { return newIcon("music-note") }
func CgMusicSpeaker() icons.IsIcon          { return newIcon("music-speaker") }
func CgMusic() icons.IsIcon                 { return newIcon("music") }
func CgNametag() icons.IsIcon               { return newIcon("nametag") }
func CgNotes() icons.IsIcon                 { return newIcon("notes") }
func CgNotifications() icons.IsIcon         { return newIcon("notifications") }
func CgNpm() icons.IsIcon                   { return newIcon("npm") }
func CgOculus() icons.IsIcon                { return newIcon("oculus") }
func CgOpenCollective() icons.IsIcon        { return newIcon("open-collective") }
func CgOptions() icons.IsIcon               { return newIcon("options") }
func CgOrganisation() icons.IsIcon          { return newIcon("organisation") }
func CgOverflow() icons.IsIcon              { return newIcon("overflow") }
func CgPacman() icons.IsIcon                { return newIcon("pacman") }
func CgPassword() icons.IsIcon              { return newIcon("password") }
func CgPathBack() icons.IsIcon              { return newIcon("path-back") }
func CgPathCrop() icons.IsIcon              { return newIcon("path-crop") }
func CgPathDivide() icons.IsIcon            { return newIcon("path-divide") }
func CgPathExclude() icons.IsIcon           { return newIcon("path-exclude") }
func CgPathFront() icons.IsIcon             { return newIcon("path-front") }
func CgPathIntersect() icons.IsIcon         { return newIcon("path-intersect") }
func CgPathOutline() icons.IsIcon           { return newIcon("path-outline") }
func CgPathTrim() icons.IsIcon              { return newIcon("path-trim") }
func CgPathUnite() icons.IsIcon             { return newIcon("path-unite") }
func CgPatreon() icons.IsIcon               { return newIcon("patreon") }
func CgPaypal() icons.IsIcon                { return newIcon("paypal") }
func CgPen() icons.IsIcon                   { return newIcon("pen") }
func CgPentagonBottomLeft() icons.IsIcon    { return newIcon("pentagon-bottom-left") }
func CgPentagonBottomRight() icons.IsIcon   { return newIcon("pentagon-bottom-right") }
func CgPentagonDown() icons.IsIcon          { return newIcon("pentagon-down") }
func CgPentagonLeft() icons.IsIcon          { return newIcon("pentagon-left") }
func CgPentagonRight() icons.IsIcon         { return newIcon("pentagon-right") }
func CgPentagonTopLeft() icons.IsIcon       { return newIcon("pentagon-top-left") }
func CgPentagonTopRight() icons.IsIcon      { return newIcon("pentagon-top-right") }
func CgPentagonUp() icons.IsIcon            { return newIcon("pentagon-up") }
func CgPerformance() icons.IsIcon           { return newIcon("performance") }
func CgPexels() icons.IsIcon                { return newIcon("pexels") }
func CgPhone() icons.IsIcon                 { return newIcon("phone") }
func CgPhotoscan() icons.IsIcon             { return newIcon("photoscan") }
func CgPiano() icons.IsIcon                 { return newIcon("piano") }
func CgPill() icons.IsIcon                  { return newIcon("pill") }
func CgPinAlt() icons.IsIcon                { return newIcon("pin-alt") }
func CgPinBottom() icons.IsIcon             { return newIcon("pin-bottom") }
func CgPinTop() icons.IsIcon                { return newIcon("pin-top") }
func CgPin() icons.IsIcon                   { return newIcon("pin") }
func CgPlayBackwards() icons.IsIcon         { return newIcon("play-backwards") }
func CgPlayButtonO() icons.IsIcon           { return newIcon("play-button-o") }
func CgPlayButtonR() icons.IsIcon           { return newIcon("play-button-r") }
func CgPlayButton() icons.IsIcon            { return newIcon("play-button") }
func CgPlayForwards() icons.IsIcon          { return newIcon("play-forwards") }
func CgPlayListAdd() icons.IsIcon           { return newIcon("play-list-add") }
func CgPlayListCheck() icons.IsIcon         { return newIcon("play-list-check") }
func CgPlayListRemove() icons.IsIcon        { return newIcon("play-list-remove") }
func CgPlayListSearch() icons.IsIcon        { return newIcon("play-list-search") }
func CgPlayList() icons.IsIcon              { return newIcon("play-list") }
func CgPlayPauseO() icons.IsIcon            { return newIcon("play-pause-o") }
func CgPlayPauseR() icons.IsIcon            { return newIcon("play-pause-r") }
func CgPlayPause() icons.IsIcon             { return newIcon("play-pause") }
func CgPlayStopO() icons.IsIcon             { return newIcon("play-stop-o") }
func CgPlayStopR() icons.IsIcon             { return newIcon("play-stop-r") }
func CgPlayStop() icons.IsIcon              { return newIcon("play-stop") }
func CgPlayTrackNextO() icons.IsIcon        { return newIcon("play-track-next-o") }
func CgPlayTrackNextR() icons.IsIcon        { return newIcon("play-track-next-r") }
func CgPlayTrackNext() icons.IsIcon         { return newIcon("play-track-next") }
func CgPlayTrackPrevO() icons.IsIcon        { return newIcon("play-track-prev-o") }
func CgPlayTrackPrevR() icons.IsIcon        { return newIcon("play-track-prev-r") }
func CgPlayTrackPrev() icons.IsIcon         { return newIcon("play-track-prev") }
func CgPlug() icons.IsIcon                  { return newIcon("plug") }
func CgPocket() icons.IsIcon                { return newIcon("pocket") }
func CgPokemon() icons.IsIcon               { return newIcon("pokemon") }
func CgPolaroid() icons.IsIcon              { return newIcon("polaroid") }
func CgPoll() icons.IsIcon                  { return newIcon("poll") }
func CgPresentation() icons.IsIcon          { return newIcon("presentation") }
func CgPrinter() icons.IsIcon               { return newIcon("printer") }
func CgProductHunt() icons.IsIcon           { return newIcon("product-hunt") }
func CgProfile() icons.IsIcon               { return newIcon("profile") }
func CgPullClear() icons.IsIcon             { return newIcon("pull-clear") }
func CgPushChevronDownO() icons.IsIcon      { return newIcon("push-chevron-down-o") }
func CgPushChevronDownR() icons.IsIcon      { return newIcon("push-chevron-down-r") }
func CgPushChevronDown() icons.IsIcon       { return newIcon("push-chevron-down") }
func CgPushChevronLeftO() icons.IsIcon      { return newIcon("push-chevron-left-o") }
func CgPushChevronLeftR() icons.IsIcon      { return newIcon("push-chevron-left-r") }
func CgPushChevronLeft() icons.IsIcon       { return newIcon("push-chevron-left") }
func CgPushChevronRightO() icons.IsIcon     { return newIcon("push-chevron-right-o") }
func CgPushChevronRightR() icons.IsIcon     { return newIcon("push-chevron-right-r") }
func CgPushChevronRight() icons.IsIcon      { return newIcon("push-chevron-right") }
func CgPushChevronUpO() icons.IsIcon        { return newIcon("push-chevron-up-o") }
func CgPushChevronUpR() icons.IsIcon        { return newIcon("push-chevron-up-r") }
func CgPushChevronUp() icons.IsIcon         { return newIcon("push-chevron-up") }
func CgPushDown() icons.IsIcon              { return newIcon("push-down") }
func CgPushLeft() icons.IsIcon              { return newIcon("push-left") }
func CgPushRight() icons.IsIcon             { return newIcon("push-right") }
func CgPushUp() icons.IsIcon                { return newIcon("push-up") }
func CgQr() icons.IsIcon                    { return newIcon("qr") }
func CgQuoteO() icons.IsIcon                { return newIcon("quote-o") }
func CgQuote() icons.IsIcon                 { return newIcon("quote") }
func CgRadioCheck() icons.IsIcon            { return newIcon("radio-check") }
func CgRadioChecked() icons.IsIcon          { return newIcon("radio-checked") }
func CgRatio() icons.IsIcon                 { return newIcon("ratio") }
func CgRead() icons.IsIcon                  { return newIcon("read") }
func CgReadme() icons.IsIcon                { return newIcon("readme") }
func CgRecord() icons.IsIcon                { return newIcon("record") }
func CgRedo() icons.IsIcon                  { return newIcon("redo") }
func CgRemote() icons.IsIcon                { return newIcon("remote") }
func CgRemoveR() icons.IsIcon               { return newIcon("remove-r") }
func CgRemove() icons.IsIcon                { return newIcon("remove") }
func CgRename() icons.IsIcon                { return newIcon("rename") }
func CgReorder() icons.IsIcon               { return newIcon("reorder") }
func CgRepeat() icons.IsIcon                { return newIcon("repeat") }
func CgRing() icons.IsIcon                  { return newIcon("ring") }
func CgRowFirst() icons.IsIcon              { return newIcon("row-first") }
func CgRowLast() icons.IsIcon               { return newIcon("row-last") }
func CgRuler() icons.IsIcon                 { return newIcon("ruler") }
func CgSandClock() icons.IsIcon             { return newIcon("sand-clock") }
func CgScan() icons.IsIcon                  { return newIcon("scan") }
func CgScreenMirror() icons.IsIcon          { return newIcon("screen-mirror") }
func CgScreenShot() icons.IsIcon            { return newIcon("screen-shot") }
func CgScreenWide() icons.IsIcon            { return newIcon("screen-wide") }
func CgScreen() icons.IsIcon                { return newIcon("screen") }
func CgScrollH() icons.IsIcon               { return newIcon("scroll-h") }
func CgScrollV() icons.IsIcon               { return newIcon("scroll-v") }
func CgSearchFound() icons.IsIcon           { return newIcon("search-found") }
func CgSearchLoading() icons.IsIcon         { return newIcon("search-loading") }
func CgSearch() icons.IsIcon                { return newIcon("search") }
func CgSelectO() icons.IsIcon               { return newIcon("select-o") }
func CgSelectR() icons.IsIcon               { return newIcon("select-r") }
func CgSelect() icons.IsIcon                { return newIcon("select") }
func CgServer() icons.IsIcon                { return newIcon("server") }
func CgServerless() icons.IsIcon            { return newIcon("serverless") }
func CgShapeCircle() icons.IsIcon           { return newIcon("shape-circle") }
func CgShapeHalfCircle() icons.IsIcon       { return newIcon("shape-half-circle") }
func CgShapeHexagon() icons.IsIcon          { return newIcon("shape-hexagon") }
func CgShapeRhombus() icons.IsIcon          { return newIcon("shape-rhombus") }
func CgShapeSquare() icons.IsIcon           { return newIcon("shape-square") }
func CgShapeTriangle() icons.IsIcon         { return newIcon("shape-triangle") }
func CgShapeZigzag() icons.IsIcon           { return newIcon("shape-zigzag") }
func CgShare() icons.IsIcon                 { return newIcon("share") }
func CgShield() icons.IsIcon                { return newIcon("shield") }
func CgShoppingBag() icons.IsIcon           { return newIcon("shopping-bag") }
func CgShoppingCart() icons.IsIcon          { return newIcon("shopping-cart") }
func CgShortcut() icons.IsIcon              { return newIcon("shortcut") }
func CgShutterstock() icons.IsIcon          { return newIcon("shutterstock") }
func CgSidebarOpen() icons.IsIcon           { return newIcon("sidebar-open") }
func CgSidebarRight() icons.IsIcon          { return newIcon("sidebar-right") }
func CgSidebar() icons.IsIcon               { return newIcon("sidebar") }
func CgSignal() icons.IsIcon                { return newIcon("signal") }
func CgSize() icons.IsIcon                  { return newIcon("size") }
func CgSketch() icons.IsIcon                { return newIcon("sketch") }
func CgSlack() icons.IsIcon                 { return newIcon("slack") }
func CgSleep() icons.IsIcon                 { return newIcon("sleep") }
func CgSmartHomeBoiler() icons.IsIcon       { return newIcon("smart-home-boiler") }
func CgSmartHomeCooker() icons.IsIcon       { return newIcon("smart-home-cooker") }
func CgSmartHomeHeat() icons.IsIcon         { return newIcon("smart-home-heat") }
func CgSmartHomeLight() icons.IsIcon        { return newIcon("smart-home-light") }
func CgSmartHomeRefrigerator() icons.IsIcon { return newIcon("smart-home-refrigerator") }
func CgSmartHomeWashMachine() icons.IsIcon  { return newIcon("smart-home-wash-machine") }
func CgSmartphoneChip() icons.IsIcon        { return newIcon("smartphone-chip") }
func CgSmartphoneRam() icons.IsIcon         { return newIcon("smartphone-ram") }
func CgSmartphoneShake() icons.IsIcon       { return newIcon("smartphone-shake") }
func CgSmartphone() icons.IsIcon            { return newIcon("smartphone") }
func CgSmileMouthOpen() icons.IsIcon        { return newIcon("smile-mouth-open") }
func CgSmileNeutral() icons.IsIcon          { return newIcon("smile-neutral") }
func CgSmileNoMouth() icons.IsIcon          { return newIcon("smile-no-mouth") }
func CgSmileNone() icons.IsIcon             { return newIcon("smile-none") }
func CgSmileSad() icons.IsIcon              { return newIcon("smile-sad") }
func CgSmileUpside() icons.IsIcon           { return newIcon("smile-upside") }
func CgSmile() icons.IsIcon                 { return newIcon("smile") }
func CgSoftwareDownload() icons.IsIcon      { return newIcon("software-download") }
func CgSoftwareUpload() icons.IsIcon        { return newIcon("software-upload") }
func CgSortAz() icons.IsIcon                { return newIcon("sort-az") }
func CgSortZa() icons.IsIcon                { return newIcon("sort-za") }
func CgSpaceBetweenV() icons.IsIcon         { return newIcon("space-between-v") }
func CgSpaceBetween() icons.IsIcon          { return newIcon("space-between") }
func CgSpectrum() icons.IsIcon              { return newIcon("spectrum") }
func CgSpinnerAlt() icons.IsIcon            { return newIcon("spinner-alt") }
func CgSpinnerTwoAlt() icons.IsIcon         { return newIcon("spinner-two-alt") }
func CgSpinnerTwo() icons.IsIcon            { return newIcon("spinner-two") }
func CgSpinner() icons.IsIcon               { return newIcon("spinner") }
func CgSquare() icons.IsIcon                { return newIcon("square") }
func CgStack() icons.IsIcon                 { return newIcon("stack") }
func CgStark() icons.IsIcon                 { return newIcon("stark") }
func CgStopwatch() icons.IsIcon             { return newIcon("stopwatch") }
func CgStories() icons.IsIcon               { return newIcon("stories") }
func CgStudio() icons.IsIcon                { return newIcon("studio") }
func CgStyle() icons.IsIcon                 { return newIcon("style") }
func CgSun() icons.IsIcon                   { return newIcon("sun") }
func CgSupport() icons.IsIcon               { return newIcon("support") }
func CgSwapVertical() icons.IsIcon          { return newIcon("swap-vertical") }
func CgSwap() icons.IsIcon                  { return newIcon("swap") }
func CgSweden() icons.IsIcon                { return newIcon("sweden") }
func CgSwiss() icons.IsIcon                 { return newIcon("swiss") }
func CgSync() icons.IsIcon                  { return newIcon("sync") }
func CgTab() icons.IsIcon                   { return newIcon("tab") }
func CgTag() icons.IsIcon                   { return newIcon("tag") }
func CgTally() icons.IsIcon                 { return newIcon("tally") }
func CgTapDouble() icons.IsIcon             { return newIcon("tap-double") }
func CgTapSingle() icons.IsIcon             { return newIcon("tap-single") }
func CgTemplate() icons.IsIcon              { return newIcon("template") }
func CgTennis() icons.IsIcon                { return newIcon("tennis") }
func CgTerminal() icons.IsIcon              { return newIcon("terminal") }
func CgTerrain() icons.IsIcon               { return newIcon("terrain") }
func CgThermometer() icons.IsIcon           { return newIcon("thermometer") }
func CgThermostat() icons.IsIcon            { return newIcon("thermostat") }
func CgTikcode() icons.IsIcon               { return newIcon("tikcode") }
func CgTime() icons.IsIcon                  { return newIcon("time") }
func CgTimelapse() icons.IsIcon             { return newIcon("timelapse") }
func CgTimer() icons.IsIcon                 { return newIcon("timer") }
func CgToday() icons.IsIcon                 { return newIcon("today") }
func CgToggleOff() icons.IsIcon             { return newIcon("toggle-off") }
func CgToggleOn() icons.IsIcon              { return newIcon("toggle-on") }
func CgToggleSquareOff() icons.IsIcon       { return newIcon("toggle-square-off") }
func CgToggleSquare() icons.IsIcon          { return newIcon("toggle-square") }
func CgToolbarBottom() icons.IsIcon         { return newIcon("toolbar-bottom") }
func CgToolbarLeft() icons.IsIcon           { return newIcon("toolbar-left") }
func CgToolbarRight() icons.IsIcon          { return newIcon("toolbar-right") }
func CgToolbarTop() icons.IsIcon            { return newIcon("toolbar-top") }
func CgToolbox() icons.IsIcon               { return newIcon("toolbox") }
func CgTouchpad() icons.IsIcon              { return newIcon("touchpad") }
func CgTrack() icons.IsIcon                 { return newIcon("track") }
func CgTranscript() icons.IsIcon            { return newIcon("transcript") }
func CgTrashEmpty() icons.IsIcon            { return newIcon("trash-empty") }
func CgTrash() icons.IsIcon                 { return newIcon("trash") }
func CgTree() icons.IsIcon                  { return newIcon("tree") }
func CgTrees() icons.IsIcon                 { return newIcon("trees") }
func CgTrello() icons.IsIcon                { return newIcon("trello") }
func CgTrendingDown() icons.IsIcon          { return newIcon("trending-down") }
func CgTrending() icons.IsIcon              { return newIcon("trending") }
func CgTrophy() icons.IsIcon                { return newIcon("trophy") }
func CgTv() icons.IsIcon                    { return newIcon("tv") }
func CgTwilio() icons.IsIcon                { return newIcon("twilio") }
func CgTwitter() icons.IsIcon               { return newIcon("twitter") }
func CgUiKit() icons.IsIcon                 { return newIcon("ui-kit") }
func CgUmbrella() icons.IsIcon              { return newIcon("umbrella") }
func CgUnavailable() icons.IsIcon           { return newIcon("unavailable") }
func CgUnblock() icons.IsIcon               { return newIcon("unblock") }
func CgUndo() icons.IsIcon                  { return newIcon("undo") }
func CgUnfold() icons.IsIcon                { return newIcon("unfold") }
func CgUnsplash() icons.IsIcon              { return newIcon("unsplash") }
func CgUsbC() icons.IsIcon                  { return newIcon("usb-c") }
func CgUsb() icons.IsIcon                   { return newIcon("usb") }
func CgUserAdd() icons.IsIcon               { return newIcon("user-add") }
func CgUserList() icons.IsIcon              { return newIcon("user-list") }
func CgUserRemove() icons.IsIcon            { return newIcon("user-remove") }
func CgUser() icons.IsIcon                  { return newIcon("user") }
func CgUserlane() icons.IsIcon              { return newIcon("userlane") }
func CgVercel() icons.IsIcon                { return newIcon("vercel") }
func CgViewCols() icons.IsIcon              { return newIcon("view-cols") }
func CgViewComfortable() icons.IsIcon       { return newIcon("view-comfortable") }
func CgViewDay() icons.IsIcon               { return newIcon("view-day") }
func CgViewGrid() icons.IsIcon              { return newIcon("view-grid") }
func CgViewList() icons.IsIcon              { return newIcon("view-list") }
func CgViewMonth() icons.IsIcon             { return newIcon("view-month") }
func CgViewSplit() icons.IsIcon             { return newIcon("view-split") }
func CgVinyl() icons.IsIcon                 { return newIcon("vinyl") }
func CgVoicemailO() icons.IsIcon            { return newIcon("voicemail-o") }
func CgVoicemailR() icons.IsIcon            { return newIcon("voicemail-r") }
func CgVoicemail() icons.IsIcon             { return newIcon("voicemail") }
func CgVolume() icons.IsIcon                { return newIcon("volume") }
func CgWebcam() icons.IsIcon                { return newIcon("webcam") }
func CgWebsite() icons.IsIcon               { return newIcon("website") }
func CgWindows() icons.IsIcon               { return newIcon("windows") }
func CgWorkAlt() icons.IsIcon               { return newIcon("work-alt") }
func CgYinyang() icons.IsIcon               { return newIcon("yinyang") }
func CgYoutube() icons.IsIcon               { return newIcon("youtube") }
func CgZoomIn() icons.IsIcon                { return newIcon("zoom-in") }
func CgZoomOut() icons.IsIcon               { return newIcon("zoom-out") }
