package di

import "github.com/raitucarp/gomix/icons"

func DiAndroid() icons.IsIcon              { return newIcon("android") }
func DiAngularSimple() icons.IsIcon        { return newIcon("angular_simple") }
func DiAppcelerator() icons.IsIcon         { return newIcon("appcelerator") }
func DiApple() icons.IsIcon                { return newIcon("apple") }
func DiAppstore() icons.IsIcon             { return newIcon("appstore") }
func DiAptana() icons.IsIcon               { return newIcon("aptana") }
func DiAsterisk() icons.IsIcon             { return newIcon("asterisk") }
func DiAtlassian() icons.IsIcon            { return newIcon("atlassian") }
func DiAtom() icons.IsIcon                 { return newIcon("atom") }
func DiAws() icons.IsIcon                  { return newIcon("aws") }
func DiBackbone() icons.IsIcon             { return newIcon("backbone") }
func DiBingSmall() icons.IsIcon            { return newIcon("bing_small") }
func DiBintray() icons.IsIcon              { return newIcon("bintray") }
func DiBitbucket() icons.IsIcon            { return newIcon("bitbucket") }
func DiBlackberry() icons.IsIcon           { return newIcon("blackberry") }
func DiBootstrap() icons.IsIcon            { return newIcon("bootstrap") }
func DiBower() icons.IsIcon                { return newIcon("bower") }
func DiBrackets() icons.IsIcon             { return newIcon("brackets") }
func DiBugsense() icons.IsIcon             { return newIcon("bugsense") }
func DiCelluloid() icons.IsIcon            { return newIcon("celluloid") }
func DiChrome() icons.IsIcon               { return newIcon("chrome") }
func DiCisco() icons.IsIcon                { return newIcon("cisco") }
func DiClojureAlt() icons.IsIcon           { return newIcon("clojure_alt") }
func DiClojure() icons.IsIcon              { return newIcon("clojure") }
func DiCloud9() icons.IsIcon               { return newIcon("cloud9") }
func DiCoda() icons.IsIcon                 { return newIcon("coda") }
func DiCodeBadge() icons.IsIcon            { return newIcon("code_badge") }
func DiCode() icons.IsIcon                 { return newIcon("code") }
func DiCodeigniter() icons.IsIcon          { return newIcon("codeigniter") }
func DiCodepen() icons.IsIcon              { return newIcon("codepen") }
func DiCodrops() icons.IsIcon              { return newIcon("codrops") }
func DiCoffeescript() icons.IsIcon         { return newIcon("coffeescript") }
func DiCompass() icons.IsIcon              { return newIcon("compass") }
func DiComposer() icons.IsIcon             { return newIcon("composer") }
func DiCreativecommonsBadge() icons.IsIcon { return newIcon("creativecommons_badge") }
func DiCreativecommons() icons.IsIcon      { return newIcon("creativecommons") }
func DiCssTricks() icons.IsIcon            { return newIcon("css_tricks") }
func DiCss3Full() icons.IsIcon             { return newIcon("css3_full") }
func DiCss3() icons.IsIcon                 { return newIcon("css3") }
func DiCssdeck() icons.IsIcon              { return newIcon("cssdeck") }
func DiDart() icons.IsIcon                 { return newIcon("dart") }
func DiDatabase() icons.IsIcon             { return newIcon("database") }
func DiDebian() icons.IsIcon               { return newIcon("debian") }
func DiDigitalOcean() icons.IsIcon         { return newIcon("digital-ocean") }
func DiDjango() icons.IsIcon               { return newIcon("django") }
func DiDlang() icons.IsIcon                { return newIcon("dlang") }
func DiDocker() icons.IsIcon               { return newIcon("docker") }
func DiDoctrine() icons.IsIcon             { return newIcon("doctrine") }
func DiDojo() icons.IsIcon                 { return newIcon("dojo") }
func DiDotnet() icons.IsIcon               { return newIcon("dotnet") }
func DiDreamweaver() icons.IsIcon          { return newIcon("dreamweaver") }
func DiDropbox() icons.IsIcon              { return newIcon("dropbox") }
func DiDrupal() icons.IsIcon               { return newIcon("drupal") }
func DiEclipse() icons.IsIcon              { return newIcon("eclipse") }
func DiEmber() icons.IsIcon                { return newIcon("ember") }
func DiEnvato() icons.IsIcon               { return newIcon("envato") }
func DiErlang() icons.IsIcon               { return newIcon("erlang") }
func DiExtjs() icons.IsIcon                { return newIcon("extjs") }
func DiFirebase() icons.IsIcon             { return newIcon("firebase") }
func DiFirefox() icons.IsIcon              { return newIcon("firefox") }
func DiFsharp() icons.IsIcon               { return newIcon("fsharp") }
func DiGhostSmall() icons.IsIcon           { return newIcon("ghost_small") }
func DiGhost() icons.IsIcon                { return newIcon("ghost") }
func DiGitBranch() icons.IsIcon            { return newIcon("git_branch") }
func DiGitCommit() icons.IsIcon            { return newIcon("git_commit") }
func DiGitCompare() icons.IsIcon           { return newIcon("git_compare") }
func DiGitMerge() icons.IsIcon             { return newIcon("git_merge") }
func DiGitPullRequest() icons.IsIcon       { return newIcon("git_pull_request") }
func DiGit() icons.IsIcon                  { return newIcon("git") }
func DiGithubAlt() icons.IsIcon            { return newIcon("github_alt") }
func DiGithubBadge() icons.IsIcon          { return newIcon("github_badge") }
func DiGithubFull() icons.IsIcon           { return newIcon("github_full") }
func DiGithub() icons.IsIcon               { return newIcon("github") }
func DiGnu() icons.IsIcon                  { return newIcon("gnu") }
func DiGo() icons.IsIcon                   { return newIcon("go") }
func DiGoogleAnalytics() icons.IsIcon      { return newIcon("google_analytics") }
func DiGoogleDrive() icons.IsIcon          { return newIcon("google_drive") }
func DiGoogleCloudPlatform() icons.IsIcon  { return newIcon("google-cloud-platform") }
func DiGrails() icons.IsIcon               { return newIcon("grails") }
func DiGroovy() icons.IsIcon               { return newIcon("groovy") }
func DiGrunt() icons.IsIcon                { return newIcon("grunt") }
func DiGulp() icons.IsIcon                 { return newIcon("gulp") }
func DiHackernews() icons.IsIcon           { return newIcon("hackernews") }
func DiHaskell() icons.IsIcon              { return newIcon("haskell") }
func DiHeroku() icons.IsIcon               { return newIcon("heroku") }
func DiHtml53DEffects() icons.IsIcon       { return newIcon("html5_3d_effects") }
func DiHtml5Connectivity() icons.IsIcon    { return newIcon("html5_connectivity") }
func DiHtml5DeviceAccess() icons.IsIcon    { return newIcon("html5_device_access") }
func DiHtml5Multimedia() icons.IsIcon      { return newIcon("html5_multimedia") }
func DiHtml5() icons.IsIcon                { return newIcon("html5") }
func DiIe() icons.IsIcon                   { return newIcon("ie") }
func DiIllustrator() icons.IsIcon          { return newIcon("illustrator") }
func DiIntellij() icons.IsIcon             { return newIcon("intellij") }
func DiIonic() icons.IsIcon                { return newIcon("ionic") }
func DiJava() icons.IsIcon                 { return newIcon("java") }
func DiJavascript1() icons.IsIcon          { return newIcon("javascript_1") }
func DiJavascript() icons.IsIcon           { return newIcon("javascript") }
func DiJekyllSmall() icons.IsIcon          { return newIcon("jekyll_small") }
func DiJenkins() icons.IsIcon              { return newIcon("jenkins") }
func DiJira() icons.IsIcon                 { return newIcon("jira") }
func DiJoomla() icons.IsIcon               { return newIcon("joomla") }
func DiJqueryLogo() icons.IsIcon           { return newIcon("jquery_logo") }
func DiJqueryUiLogo() icons.IsIcon         { return newIcon("jquery_ui_logo") }
func DiJsBadge() icons.IsIcon              { return newIcon("js_badge") }
func DiKomodo() icons.IsIcon               { return newIcon("komodo") }
func DiKrakenjsBadge() icons.IsIcon        { return newIcon("krakenjs_badge") }
func DiKrakenjs() icons.IsIcon             { return newIcon("krakenjs") }
func DiLaravel() icons.IsIcon              { return newIcon("laravel") }
func DiLess() icons.IsIcon                 { return newIcon("less") }
func DiLinux() icons.IsIcon                { return newIcon("linux") }
func DiMagento() icons.IsIcon              { return newIcon("magento") }
func DiMailchimp() icons.IsIcon            { return newIcon("mailchimp") }
func DiMarkdown() icons.IsIcon             { return newIcon("markdown") }
func DiMaterializecss() icons.IsIcon       { return newIcon("materializecss") }
func DiMeteor() icons.IsIcon               { return newIcon("meteor") }
func DiMeteorfull() icons.IsIcon           { return newIcon("meteorfull") }
func DiMitlicence() icons.IsIcon           { return newIcon("mitlicence") }
func DiModernizr() icons.IsIcon            { return newIcon("modernizr") }
func DiMongodb() icons.IsIcon              { return newIcon("mongodb") }
func DiMootoolsBadge() icons.IsIcon        { return newIcon("mootools_badge") }
func DiMootools() icons.IsIcon             { return newIcon("mootools") }
func DiMozilla() icons.IsIcon              { return newIcon("mozilla") }
func DiMsqlServer() icons.IsIcon           { return newIcon("msql_server") }
func DiMysql() icons.IsIcon                { return newIcon("mysql") }
func DiNancy() icons.IsIcon                { return newIcon("nancy") }
func DiNetbeans() icons.IsIcon             { return newIcon("netbeans") }
func DiNetmagazine() icons.IsIcon          { return newIcon("netmagazine") }
func DiNginx() icons.IsIcon                { return newIcon("nginx") }
func DiNodejsSmall() icons.IsIcon          { return newIcon("nodejs_small") }
func DiNodejs() icons.IsIcon               { return newIcon("nodejs") }
func DiNpm() icons.IsIcon                  { return newIcon("npm") }
func DiOnedrive() icons.IsIcon             { return newIcon("onedrive") }
func DiOpenshift() icons.IsIcon            { return newIcon("openshift") }
func DiOpensource() icons.IsIcon           { return newIcon("opensource") }
func DiOpera() icons.IsIcon                { return newIcon("opera") }
func DiPerl() icons.IsIcon                 { return newIcon("perl") }
func DiPhonegap() icons.IsIcon             { return newIcon("phonegap") }
func DiPhotoshop() icons.IsIcon            { return newIcon("photoshop") }
func DiPhp() icons.IsIcon                  { return newIcon("php") }
func DiPostgresql() icons.IsIcon           { return newIcon("postgresql") }
func DiProlog() icons.IsIcon               { return newIcon("prolog") }
func DiPython() icons.IsIcon               { return newIcon("python") }
func DiRackspace() icons.IsIcon            { return newIcon("rackspace") }
func DiRaphael() icons.IsIcon              { return newIcon("raphael") }
func DiRasberryPi() icons.IsIcon           { return newIcon("rasberry_pi") }
func DiReact() icons.IsIcon                { return newIcon("react") }
func DiRedhat() icons.IsIcon               { return newIcon("redhat") }
func DiRedis() icons.IsIcon                { return newIcon("redis") }
func DiRequirejs() icons.IsIcon            { return newIcon("requirejs") }
func DiResponsive() icons.IsIcon           { return newIcon("responsive") }
func DiRor() icons.IsIcon                  { return newIcon("ror") }
func DiRubyRough() icons.IsIcon            { return newIcon("ruby_rough") }
func DiRuby() icons.IsIcon                 { return newIcon("ruby") }
func DiRust() icons.IsIcon                 { return newIcon("rust") }
func DiSafari() icons.IsIcon               { return newIcon("safari") }
func DiSass() icons.IsIcon                 { return newIcon("sass") }
func DiScala() icons.IsIcon                { return newIcon("scala") }
func DiScriptcs() icons.IsIcon             { return newIcon("scriptcs") }
func DiScrum() icons.IsIcon                { return newIcon("scrum") }
func DiSenchatouch() icons.IsIcon          { return newIcon("senchatouch") }
func DiSizzlejs() icons.IsIcon             { return newIcon("sizzlejs") }
func DiSmashingMagazine() icons.IsIcon     { return newIcon("smashing_magazine") }
func DiSnapSvg() icons.IsIcon              { return newIcon("snap_svg") }
func DiSpark() icons.IsIcon                { return newIcon("spark") }
func DiSqllite() icons.IsIcon              { return newIcon("sqllite") }
func DiStackoverflow() icons.IsIcon        { return newIcon("stackoverflow") }
func DiStreamline() icons.IsIcon           { return newIcon("streamline") }
func DiStylus() icons.IsIcon               { return newIcon("stylus") }
func DiSublime() icons.IsIcon              { return newIcon("sublime") }
func DiSwift() icons.IsIcon                { return newIcon("swift") }
func DiSymfonyBadge() icons.IsIcon         { return newIcon("symfony_badge") }
func DiSymfony() icons.IsIcon              { return newIcon("symfony") }
func DiTechcrunch() icons.IsIcon           { return newIcon("techcrunch") }
func DiTerminalBadge() icons.IsIcon        { return newIcon("terminal_badge") }
func DiTerminal() icons.IsIcon             { return newIcon("terminal") }
func DiTravis() icons.IsIcon               { return newIcon("travis") }
func DiTrello() icons.IsIcon               { return newIcon("trello") }
func DiTypo3() icons.IsIcon                { return newIcon("typo3") }
func DiUbuntu() icons.IsIcon               { return newIcon("ubuntu") }
func DiUikit() icons.IsIcon                { return newIcon("uikit") }
func DiUnitySmall() icons.IsIcon           { return newIcon("unity_small") }
func DiVim() icons.IsIcon                  { return newIcon("vim") }
func DiVisualstudio() icons.IsIcon         { return newIcon("visualstudio") }
func DiW3C() icons.IsIcon                  { return newIcon("w3c") }
func DiWebplatform() icons.IsIcon          { return newIcon("webplatform") }
func DiWindows() icons.IsIcon              { return newIcon("windows") }
func DiWordpress() icons.IsIcon            { return newIcon("wordpress") }
func DiYahooSmall() icons.IsIcon           { return newIcon("yahoo_small") }
func DiYahoo() icons.IsIcon                { return newIcon("yahoo") }
func DiYeoman() icons.IsIcon               { return newIcon("yeoman") }
func DiYii() icons.IsIcon                  { return newIcon("yii") }
func DiZend() icons.IsIcon                 { return newIcon("zend") }
