package rx

import "github.com/raitucarp/gomix/icons"

func RxAccessibility() icons.IsIcon            { return newIcon("accessibility") }
func RxActivityLog() icons.IsIcon              { return newIcon("activity-log") }
func RxAlignBaseline() icons.IsIcon            { return newIcon("align-baseline") }
func RxAlignBottom() icons.IsIcon              { return newIcon("align-bottom") }
func RxAlignCenterHorizontally() icons.IsIcon  { return newIcon("align-center-horizontally") }
func RxAlignCenterVertically() icons.IsIcon    { return newIcon("align-center-vertically") }
func RxAlignCenter() icons.IsIcon              { return newIcon("align-center") }
func RxAlignEnd() icons.IsIcon                 { return newIcon("align-end") }
func RxAlignHorizontalCenters() icons.IsIcon   { return newIcon("align-horizontal-centers") }
func RxAlignLeft() icons.IsIcon                { return newIcon("align-left") }
func RxAlignRight() icons.IsIcon               { return newIcon("align-right") }
func RxAlignStart() icons.IsIcon               { return newIcon("align-start") }
func RxAlignStretch() icons.IsIcon             { return newIcon("align-stretch") }
func RxAlignTop() icons.IsIcon                 { return newIcon("align-top") }
func RxAlignVerticalCenters() icons.IsIcon     { return newIcon("align-vertical-centers") }
func RxAllSides() icons.IsIcon                 { return newIcon("all-sides") }
func RxAngle() icons.IsIcon                    { return newIcon("angle") }
func RxArchive() icons.IsIcon                  { return newIcon("archive") }
func RxArrowBottomLeft() icons.IsIcon          { return newIcon("arrow-bottom-left") }
func RxArrowBottomRight() icons.IsIcon         { return newIcon("arrow-bottom-right") }
func RxArrowDown() icons.IsIcon                { return newIcon("arrow-down") }
func RxArrowLeft() icons.IsIcon                { return newIcon("arrow-left") }
func RxArrowRight() icons.IsIcon               { return newIcon("arrow-right") }
func RxArrowTopLeft() icons.IsIcon             { return newIcon("arrow-top-left") }
func RxArrowTopRight() icons.IsIcon            { return newIcon("arrow-top-right") }
func RxArrowUp() icons.IsIcon                  { return newIcon("arrow-up") }
func RxAspectRatio() icons.IsIcon              { return newIcon("aspect-ratio") }
func RxAvatar() icons.IsIcon                   { return newIcon("avatar") }
func RxBackpack() icons.IsIcon                 { return newIcon("backpack") }
func RxBadge() icons.IsIcon                    { return newIcon("badge") }
func RxBarChart() icons.IsIcon                 { return newIcon("bar-chart") }
func RxBell() icons.IsIcon                     { return newIcon("bell") }
func RxBlendingMode() icons.IsIcon             { return newIcon("blending-mode") }
func RxBookmarkFilled() icons.IsIcon           { return newIcon("bookmark-filled") }
func RxBookmark() icons.IsIcon                 { return newIcon("bookmark") }
func RxBorderAll() icons.IsIcon                { return newIcon("border-all") }
func RxBorderBottom() icons.IsIcon             { return newIcon("border-bottom") }
func RxBorderDashed() icons.IsIcon             { return newIcon("border-dashed") }
func RxBorderDotted() icons.IsIcon             { return newIcon("border-dotted") }
func RxBorderLeft() icons.IsIcon               { return newIcon("border-left") }
func RxBorderNone() icons.IsIcon               { return newIcon("border-none") }
func RxBorderRight() icons.IsIcon              { return newIcon("border-right") }
func RxBorderSolid() icons.IsIcon              { return newIcon("border-solid") }
func RxBorderSplit() icons.IsIcon              { return newIcon("border-split") }
func RxBorderStyle() icons.IsIcon              { return newIcon("border-style") }
func RxBorderTop() icons.IsIcon                { return newIcon("border-top") }
func RxBorderWidth() icons.IsIcon              { return newIcon("border-width") }
func RxBoxModel() icons.IsIcon                 { return newIcon("box-model") }
func RxBox() icons.IsIcon                      { return newIcon("box") }
func RxButton() icons.IsIcon                   { return newIcon("button") }
func RxCalendar() icons.IsIcon                 { return newIcon("calendar") }
func RxCamera() icons.IsIcon                   { return newIcon("camera") }
func RxCardStackMinus() icons.IsIcon           { return newIcon("card-stack-minus") }
func RxCardStackPlus() icons.IsIcon            { return newIcon("card-stack-plus") }
func RxCardStack() icons.IsIcon                { return newIcon("card-stack") }
func RxCaretDown() icons.IsIcon                { return newIcon("caret-down") }
func RxCaretLeft() icons.IsIcon                { return newIcon("caret-left") }
func RxCaretRight() icons.IsIcon               { return newIcon("caret-right") }
func RxCaretSort() icons.IsIcon                { return newIcon("caret-sort") }
func RxCaretUp() icons.IsIcon                  { return newIcon("caret-up") }
func RxChatBubble() icons.IsIcon               { return newIcon("chat-bubble") }
func RxCheckCircled() icons.IsIcon             { return newIcon("check-circled") }
func RxCheck() icons.IsIcon                    { return newIcon("check") }
func RxCheckbox() icons.IsIcon                 { return newIcon("checkbox") }
func RxChevronDown() icons.IsIcon              { return newIcon("chevron-down") }
func RxChevronLeft() icons.IsIcon              { return newIcon("chevron-left") }
func RxChevronRight() icons.IsIcon             { return newIcon("chevron-right") }
func RxChevronUp() icons.IsIcon                { return newIcon("chevron-up") }
func RxCircleBackslash() icons.IsIcon          { return newIcon("circle-backslash") }
func RxCircle() icons.IsIcon                   { return newIcon("circle") }
func RxClipboardCopy() icons.IsIcon            { return newIcon("clipboard-copy") }
func RxClipboard() icons.IsIcon                { return newIcon("clipboard") }
func RxClock() icons.IsIcon                    { return newIcon("clock") }
func RxCode() icons.IsIcon                     { return newIcon("code") }
func RxCodesandboxLogo() icons.IsIcon          { return newIcon("codesandbox-logo") }
func RxColorWheel() icons.IsIcon               { return newIcon("color-wheel") }
func RxColumnSpacing() icons.IsIcon            { return newIcon("column-spacing") }
func RxColumns() icons.IsIcon                  { return newIcon("columns") }
func RxCommit() icons.IsIcon                   { return newIcon("commit") }
func RxComponent1() icons.IsIcon               { return newIcon("component-1") }
func RxComponent2() icons.IsIcon               { return newIcon("component-2") }
func RxComponentBoolean() icons.IsIcon         { return newIcon("component-boolean") }
func RxComponentInstance() icons.IsIcon        { return newIcon("component-instance") }
func RxComponentNone() icons.IsIcon            { return newIcon("component-none") }
func RxComponentPlaceholder() icons.IsIcon     { return newIcon("component-placeholder") }
func RxContainer() icons.IsIcon                { return newIcon("container") }
func RxCookie() icons.IsIcon                   { return newIcon("cookie") }
func RxCopy() icons.IsIcon                     { return newIcon("copy") }
func RxCornerBottomLeft() icons.IsIcon         { return newIcon("corner-bottom-left") }
func RxCornerBottomRight() icons.IsIcon        { return newIcon("corner-bottom-right") }
func RxCornerTopLeft() icons.IsIcon            { return newIcon("corner-top-left") }
func RxCornerTopRight() icons.IsIcon           { return newIcon("corner-top-right") }
func RxCorners() icons.IsIcon                  { return newIcon("corners") }
func RxCountdownTimer() icons.IsIcon           { return newIcon("countdown-timer") }
func RxCounterClockwiseClock() icons.IsIcon    { return newIcon("counter-clockwise-clock") }
func RxCrop() icons.IsIcon                     { return newIcon("crop") }
func RxCross1() icons.IsIcon                   { return newIcon("cross-1") }
func RxCross2() icons.IsIcon                   { return newIcon("cross-2") }
func RxCrossCircled() icons.IsIcon             { return newIcon("cross-circled") }
func RxCrosshair1() icons.IsIcon               { return newIcon("crosshair-1") }
func RxCrosshair2() icons.IsIcon               { return newIcon("crosshair-2") }
func RxCrumpledPaper() icons.IsIcon            { return newIcon("crumpled-paper") }
func RxCube() icons.IsIcon                     { return newIcon("cube") }
func RxCursorArrow() icons.IsIcon              { return newIcon("cursor-arrow") }
func RxCursorText() icons.IsIcon               { return newIcon("cursor-text") }
func RxDash() icons.IsIcon                     { return newIcon("dash") }
func RxDashboard() icons.IsIcon                { return newIcon("dashboard") }
func RxDatabase() icons.IsIcon                 { return newIcon("database") }
func RxDesktop() icons.IsIcon                  { return newIcon("desktop") }
func RxDimensions() icons.IsIcon               { return newIcon("dimensions") }
func RxDisc() icons.IsIcon                     { return newIcon("disc") }
func RxDiscordLogo() icons.IsIcon              { return newIcon("discord-logo") }
func RxDividerHorizontal() icons.IsIcon        { return newIcon("divider-horizontal") }
func RxDividerVertical() icons.IsIcon          { return newIcon("divider-vertical") }
func RxDotFilled() icons.IsIcon                { return newIcon("dot-filled") }
func RxDotSolid() icons.IsIcon                 { return newIcon("dot-solid") }
func RxDot() icons.IsIcon                      { return newIcon("dot") }
func RxDotsHorizontal() icons.IsIcon           { return newIcon("dots-horizontal") }
func RxDotsVertical() icons.IsIcon             { return newIcon("dots-vertical") }
func RxDoubleArrowDown() icons.IsIcon          { return newIcon("double-arrow-down") }
func RxDoubleArrowLeft() icons.IsIcon          { return newIcon("double-arrow-left") }
func RxDoubleArrowRight() icons.IsIcon         { return newIcon("double-arrow-right") }
func RxDoubleArrowUp() icons.IsIcon            { return newIcon("double-arrow-up") }
func RxDownload() icons.IsIcon                 { return newIcon("download") }
func RxDragHandleDots1() icons.IsIcon          { return newIcon("drag-handle-dots-1") }
func RxDragHandleDots2() icons.IsIcon          { return newIcon("drag-handle-dots-2") }
func RxDragHandleHorizontal() icons.IsIcon     { return newIcon("drag-handle-horizontal") }
func RxDragHandleVertical() icons.IsIcon       { return newIcon("drag-handle-vertical") }
func RxDrawingPinFilled() icons.IsIcon         { return newIcon("drawing-pin-filled") }
func RxDrawingPinSolid() icons.IsIcon          { return newIcon("drawing-pin-solid") }
func RxDrawingPin() icons.IsIcon               { return newIcon("drawing-pin") }
func RxDropdownMenu() icons.IsIcon             { return newIcon("dropdown-menu") }
func RxEnterFullScreen() icons.IsIcon          { return newIcon("enter-full-screen") }
func RxEnter() icons.IsIcon                    { return newIcon("enter") }
func RxEnvelopeClosed() icons.IsIcon           { return newIcon("envelope-closed") }
func RxEnvelopeOpen() icons.IsIcon             { return newIcon("envelope-open") }
func RxEraser() icons.IsIcon                   { return newIcon("eraser") }
func RxExclamationCircled() icons.IsIcon       { return newIcon("exclamation-circled") }
func RxExclamationMark() icons.IsIcon          { return newIcon("exclamation-mark") }
func RxExclamationTriangle() icons.IsIcon      { return newIcon("exclamation-triangle") }
func RxExitFullScreen() icons.IsIcon           { return newIcon("exit-full-screen") }
func RxExit() icons.IsIcon                     { return newIcon("exit") }
func RxExternalLink() icons.IsIcon             { return newIcon("external-link") }
func RxEyeClosed() icons.IsIcon                { return newIcon("eye-closed") }
func RxEyeNone() icons.IsIcon                  { return newIcon("eye-none") }
func RxEyeOpen() icons.IsIcon                  { return newIcon("eye-open") }
func RxFace() icons.IsIcon                     { return newIcon("face") }
func RxFigmaLogo() icons.IsIcon                { return newIcon("figma-logo") }
func RxFileMinus() icons.IsIcon                { return newIcon("file-minus") }
func RxFilePlus() icons.IsIcon                 { return newIcon("file-plus") }
func RxFileText() icons.IsIcon                 { return newIcon("file-text") }
func RxFile() icons.IsIcon                     { return newIcon("file") }
func RxFilter() icons.IsIcon                   { return newIcon("filter") }
func RxFontBold() icons.IsIcon                 { return newIcon("font-bold") }
func RxFontFamily() icons.IsIcon               { return newIcon("font-family") }
func RxFontItalic() icons.IsIcon               { return newIcon("font-italic") }
func RxFontRoman() icons.IsIcon                { return newIcon("font-roman") }
func RxFontSize() icons.IsIcon                 { return newIcon("font-size") }
func RxFontStyle() icons.IsIcon                { return newIcon("font-style") }
func RxFrame() icons.IsIcon                    { return newIcon("frame") }
func RxFramerLogo() icons.IsIcon               { return newIcon("framer-logo") }
func RxGear() icons.IsIcon                     { return newIcon("gear") }
func RxGithubLogo() icons.IsIcon               { return newIcon("github-logo") }
func RxGlobe2() icons.IsIcon                   { return newIcon("globe-2") }
func RxGlobe() icons.IsIcon                    { return newIcon("globe") }
func RxGrid() icons.IsIcon                     { return newIcon("grid") }
func RxGroup() icons.IsIcon                    { return newIcon("group") }
func RxHalf1() icons.IsIcon                    { return newIcon("half-1") }
func RxHalf2() icons.IsIcon                    { return newIcon("half-2") }
func RxHamburgerMenu() icons.IsIcon            { return newIcon("hamburger-menu") }
func RxHand() icons.IsIcon                     { return newIcon("hand") }
func RxHeading() icons.IsIcon                  { return newIcon("heading") }
func RxHeartFilled() icons.IsIcon              { return newIcon("heart-filled") }
func RxHeart() icons.IsIcon                    { return newIcon("heart") }
func RxHeight() icons.IsIcon                   { return newIcon("height") }
func RxHobbyKnife() icons.IsIcon               { return newIcon("hobby-knife") }
func RxHome() icons.IsIcon                     { return newIcon("home") }
func RxIconjarLogo() icons.IsIcon              { return newIcon("iconjar-logo") }
func RxIdCard() icons.IsIcon                   { return newIcon("id-card") }
func RxImage() icons.IsIcon                    { return newIcon("image") }
func RxInfoCircled() icons.IsIcon              { return newIcon("info-circled") }
func RxInnerShadow() icons.IsIcon              { return newIcon("inner-shadow") }
func RxInput() icons.IsIcon                    { return newIcon("input") }
func RxInstagramLogo() icons.IsIcon            { return newIcon("instagram-logo") }
func RxJustifyCenter() icons.IsIcon            { return newIcon("justify-center") }
func RxJustifyEnd() icons.IsIcon               { return newIcon("justify-end") }
func RxJustifyStart() icons.IsIcon             { return newIcon("justify-start") }
func RxJustifyStretch() icons.IsIcon           { return newIcon("justify-stretch") }
func RxKeyboard() icons.IsIcon                 { return newIcon("keyboard") }
func RxLapTimer() icons.IsIcon                 { return newIcon("lap-timer") }
func RxLaptop() icons.IsIcon                   { return newIcon("laptop") }
func RxLayers() icons.IsIcon                   { return newIcon("layers") }
func RxLayout() icons.IsIcon                   { return newIcon("layout") }
func RxLetterCaseCapitalize() icons.IsIcon     { return newIcon("letter-case-capitalize") }
func RxLetterCaseLowercase() icons.IsIcon      { return newIcon("letter-case-lowercase") }
func RxLetterCaseToggle() icons.IsIcon         { return newIcon("letter-case-toggle") }
func RxLetterCaseUppercase() icons.IsIcon      { return newIcon("letter-case-uppercase") }
func RxLetterSpacing() icons.IsIcon            { return newIcon("letter-spacing") }
func RxLightningBolt() icons.IsIcon            { return newIcon("lightning-bolt") }
func RxLineHeight() icons.IsIcon               { return newIcon("line-height") }
func RxLink1() icons.IsIcon                    { return newIcon("link-1") }
func RxLink2() icons.IsIcon                    { return newIcon("link-2") }
func RxLinkBreak1() icons.IsIcon               { return newIcon("link-break-1") }
func RxLinkBreak2() icons.IsIcon               { return newIcon("link-break-2") }
func RxLinkNone1() icons.IsIcon                { return newIcon("link-none-1") }
func RxLinkNone2() icons.IsIcon                { return newIcon("link-none-2") }
func RxLinkedinLogo() icons.IsIcon             { return newIcon("linkedin-logo") }
func RxListBullet() icons.IsIcon               { return newIcon("list-bullet") }
func RxLockClosed() icons.IsIcon               { return newIcon("lock-closed") }
func RxLockOpen1() icons.IsIcon                { return newIcon("lock-open-1") }
func RxLockOpen2() icons.IsIcon                { return newIcon("lock-open-2") }
func RxLoop() icons.IsIcon                     { return newIcon("loop") }
func RxMagicWand() icons.IsIcon                { return newIcon("magic-wand") }
func RxMagnifyingGlass() icons.IsIcon          { return newIcon("magnifying-glass") }
func RxMargin() icons.IsIcon                   { return newIcon("margin") }
func RxMaskOff() icons.IsIcon                  { return newIcon("mask-off") }
func RxMaskOn() icons.IsIcon                   { return newIcon("mask-on") }
func RxMinimize() icons.IsIcon                 { return newIcon("minimize") }
func RxMinusCircled() icons.IsIcon             { return newIcon("minus-circled") }
func RxMinus() icons.IsIcon                    { return newIcon("minus") }
func RxMix() icons.IsIcon                      { return newIcon("mix") }
func RxMixerHorizontal() icons.IsIcon          { return newIcon("mixer-horizontal") }
func RxMixerVertical() icons.IsIcon            { return newIcon("mixer-vertical") }
func RxMobile() icons.IsIcon                   { return newIcon("mobile") }
func RxModulzLogo() icons.IsIcon               { return newIcon("modulz-logo") }
func RxMoon() icons.IsIcon                     { return newIcon("moon") }
func RxMove() icons.IsIcon                     { return newIcon("move") }
func RxNotionLogo() icons.IsIcon               { return newIcon("notion-logo") }
func RxOpacity() icons.IsIcon                  { return newIcon("opacity") }
func RxOpenInNewWindow() icons.IsIcon          { return newIcon("open-in-new-window") }
func RxOuterShadow() icons.IsIcon              { return newIcon("outer-shadow") }
func RxOverline() icons.IsIcon                 { return newIcon("overline") }
func RxPadding() icons.IsIcon                  { return newIcon("padding") }
func RxPanelBottomMinimized() icons.IsIcon     { return newIcon("panel-bottom-minimized") }
func RxPanelBottom() icons.IsIcon              { return newIcon("panel-bottom") }
func RxPanelLeftMinimized() icons.IsIcon       { return newIcon("panel-left-minimized") }
func RxPanelLeft() icons.IsIcon                { return newIcon("panel-left") }
func RxPanelRightMinimized() icons.IsIcon      { return newIcon("panel-right-minimized") }
func RxPanelRight() icons.IsIcon               { return newIcon("panel-right") }
func RxPaperPlane() icons.IsIcon               { return newIcon("paper-plane") }
func RxPause() icons.IsIcon                    { return newIcon("pause") }
func RxPencil1() icons.IsIcon                  { return newIcon("pencil-1") }
func RxPencil2() icons.IsIcon                  { return newIcon("pencil-2") }
func RxPeople() icons.IsIcon                   { return newIcon("people") }
func RxPerson() icons.IsIcon                   { return newIcon("person") }
func RxPieChart() icons.IsIcon                 { return newIcon("pie-chart") }
func RxPilcrow() icons.IsIcon                  { return newIcon("pilcrow") }
func RxPinBottom() icons.IsIcon                { return newIcon("pin-bottom") }
func RxPinLeft() icons.IsIcon                  { return newIcon("pin-left") }
func RxPinRight() icons.IsIcon                 { return newIcon("pin-right") }
func RxPinTop() icons.IsIcon                   { return newIcon("pin-top") }
func RxPlay() icons.IsIcon                     { return newIcon("play") }
func RxPlusCircled() icons.IsIcon              { return newIcon("plus-circled") }
func RxPlus() icons.IsIcon                     { return newIcon("plus") }
func RxQuestionMarkCircled() icons.IsIcon      { return newIcon("question-mark-circled") }
func RxQuestionMark() icons.IsIcon             { return newIcon("question-mark") }
func RxQuote() icons.IsIcon                    { return newIcon("quote") }
func RxRadiobutton() icons.IsIcon              { return newIcon("radiobutton") }
func RxReader() icons.IsIcon                   { return newIcon("reader") }
func RxReload() icons.IsIcon                   { return newIcon("reload") }
func RxReset() icons.IsIcon                    { return newIcon("reset") }
func RxResume() icons.IsIcon                   { return newIcon("resume") }
func RxRocket() icons.IsIcon                   { return newIcon("rocket") }
func RxRotateCounterClockwise() icons.IsIcon   { return newIcon("rotate-counter-clockwise") }
func RxRowSpacing() icons.IsIcon               { return newIcon("row-spacing") }
func RxRows() icons.IsIcon                     { return newIcon("rows") }
func RxRulerHorizontal() icons.IsIcon          { return newIcon("ruler-horizontal") }
func RxRulerSquare() icons.IsIcon              { return newIcon("ruler-square") }
func RxScissors() icons.IsIcon                 { return newIcon("scissors") }
func RxSection() icons.IsIcon                  { return newIcon("section") }
func RxServer() icons.IsIcon                   { return newIcon("server") }
func RxSewingPinFilled() icons.IsIcon          { return newIcon("sewing-pin-filled") }
func RxSewingPinSolid() icons.IsIcon           { return newIcon("sewing-pin-solid") }
func RxSewingPin() icons.IsIcon                { return newIcon("sewing-pin") }
func RxShadowInner() icons.IsIcon              { return newIcon("shadow-inner") }
func RxShadowNone() icons.IsIcon               { return newIcon("shadow-none") }
func RxShadowOuter() icons.IsIcon              { return newIcon("shadow-outer") }
func RxShadow() icons.IsIcon                   { return newIcon("shadow") }
func RxShare1() icons.IsIcon                   { return newIcon("share-1") }
func RxShare2() icons.IsIcon                   { return newIcon("share-2") }
func RxShuffle() icons.IsIcon                  { return newIcon("shuffle") }
func RxSize() icons.IsIcon                     { return newIcon("size") }
func RxSketchLogo() icons.IsIcon               { return newIcon("sketch-logo") }
func RxSlash() icons.IsIcon                    { return newIcon("slash") }
func RxSlider() icons.IsIcon                   { return newIcon("slider") }
func RxSpaceBetweenHorizontally() icons.IsIcon { return newIcon("space-between-horizontally") }
func RxSpaceBetweenVertically() icons.IsIcon   { return newIcon("space-between-vertically") }
func RxSpaceEvenlyHorizontally() icons.IsIcon  { return newIcon("space-evenly-horizontally") }
func RxSpaceEvenlyVertically() icons.IsIcon    { return newIcon("space-evenly-vertically") }
func RxSpeakerLoud() icons.IsIcon              { return newIcon("speaker-loud") }
func RxSpeakerModerate() icons.IsIcon          { return newIcon("speaker-moderate") }
func RxSpeakerOff() icons.IsIcon               { return newIcon("speaker-off") }
func RxSpeakerQuiet() icons.IsIcon             { return newIcon("speaker-quiet") }
func RxSquare() icons.IsIcon                   { return newIcon("square") }
func RxStack() icons.IsIcon                    { return newIcon("stack") }
func RxStarFilled() icons.IsIcon               { return newIcon("star-filled") }
func RxStar() icons.IsIcon                     { return newIcon("star") }
func RxStitchesLogo() icons.IsIcon             { return newIcon("stitches-logo") }
func RxStop() icons.IsIcon                     { return newIcon("stop") }
func RxStopwatch() icons.IsIcon                { return newIcon("stopwatch") }
func RxStretchHorizontally() icons.IsIcon      { return newIcon("stretch-horizontally") }
func RxStretchVertically() icons.IsIcon        { return newIcon("stretch-vertically") }
func RxStrikethrough() icons.IsIcon            { return newIcon("strikethrough") }
func RxSun() icons.IsIcon                      { return newIcon("sun") }
func RxSwitch() icons.IsIcon                   { return newIcon("switch") }
func RxSymbol() icons.IsIcon                   { return newIcon("symbol") }
func RxTable() icons.IsIcon                    { return newIcon("table") }
func RxTarget() icons.IsIcon                   { return newIcon("target") }
func RxTextAlignBottom() icons.IsIcon          { return newIcon("text-align-bottom") }
func RxTextAlignCenter() icons.IsIcon          { return newIcon("text-align-center") }
func RxTextAlignJustify() icons.IsIcon         { return newIcon("text-align-justify") }
func RxTextAlignLeft() icons.IsIcon            { return newIcon("text-align-left") }
func RxTextAlignMiddle() icons.IsIcon          { return newIcon("text-align-middle") }
func RxTextAlignRight() icons.IsIcon           { return newIcon("text-align-right") }
func RxTextAlignTop() icons.IsIcon             { return newIcon("text-align-top") }
func RxTextNone() icons.IsIcon                 { return newIcon("text-none") }
func RxText() icons.IsIcon                     { return newIcon("text") }
func RxThickArrowDown() icons.IsIcon           { return newIcon("thick-arrow-down") }
func RxThickArrowLeft() icons.IsIcon           { return newIcon("thick-arrow-left") }
func RxThickArrowRight() icons.IsIcon          { return newIcon("thick-arrow-right") }
func RxThickArrowUp() icons.IsIcon             { return newIcon("thick-arrow-up") }
func RxTimer() icons.IsIcon                    { return newIcon("timer") }
func RxTokens() icons.IsIcon                   { return newIcon("tokens") }
func RxTrackNext() icons.IsIcon                { return newIcon("track-next") }
func RxTrackPrevious() icons.IsIcon            { return newIcon("track-previous") }
func RxTransform() icons.IsIcon                { return newIcon("transform") }
func RxTransparencyGrid() icons.IsIcon         { return newIcon("transparency-grid") }
func RxTrash() icons.IsIcon                    { return newIcon("trash") }
func RxTriangleDown() icons.IsIcon             { return newIcon("triangle-down") }
func RxTriangleLeft() icons.IsIcon             { return newIcon("triangle-left") }
func RxTriangleRight() icons.IsIcon            { return newIcon("triangle-right") }
func RxTriangleUp() icons.IsIcon               { return newIcon("triangle-up") }
func RxTwitterLogo() icons.IsIcon              { return newIcon("twitter-logo") }
func RxUnderline() icons.IsIcon                { return newIcon("underline") }
func RxUpdate() icons.IsIcon                   { return newIcon("update") }
func RxUpload() icons.IsIcon                   { return newIcon("upload") }
func RxValueNone() icons.IsIcon                { return newIcon("value-none") }
func RxValue() icons.IsIcon                    { return newIcon("value") }
func RxVercelLogo() icons.IsIcon               { return newIcon("vercel-logo") }
func RxVideo() icons.IsIcon                    { return newIcon("video") }
func RxViewGrid() icons.IsIcon                 { return newIcon("view-grid") }
func RxViewHorizontal() icons.IsIcon           { return newIcon("view-horizontal") }
func RxViewNone() icons.IsIcon                 { return newIcon("view-none") }
func RxViewVertical() icons.IsIcon             { return newIcon("view-vertical") }
func RxWidth() icons.IsIcon                    { return newIcon("width") }
func RxZoomIn() icons.IsIcon                   { return newIcon("zoom-in") }
func RxZoomOut() icons.IsIcon                  { return newIcon("zoom-out") }
