package bi

import "github.com/raitucarp/gomix/icons"

func BiLogo500Px() icons.IsIcon            { return newIcon(logosIcon, "bxl-500px") }
func BiLogo99Designs() icons.IsIcon        { return newIcon(logosIcon, "bxl-99designs") }
func BiLogoAdobe() icons.IsIcon            { return newIcon(logosIcon, "bxl-adobe") }
func BiLogoAirbnb() icons.IsIcon           { return newIcon(logosIcon, "bxl-airbnb") }
func BiLogoAlgolia() icons.IsIcon          { return newIcon(logosIcon, "bxl-algolia") }
func BiLogoAmazon() icons.IsIcon           { return newIcon(logosIcon, "bxl-amazon") }
func BiLogoAndroid() icons.IsIcon          { return newIcon(logosIcon, "bxl-android") }
func BiLogoAngular() icons.IsIcon          { return newIcon(logosIcon, "bxl-angular") }
func BiLogoApple() icons.IsIcon            { return newIcon(logosIcon, "bxl-apple") }
func BiLogoAudible() icons.IsIcon          { return newIcon(logosIcon, "bxl-audible") }
func BiLogoAws() icons.IsIcon              { return newIcon(logosIcon, "bxl-aws") }
func BiLogoBaidu() icons.IsIcon            { return newIcon(logosIcon, "bxl-baidu") }
func BiLogoBehance() icons.IsIcon          { return newIcon(logosIcon, "bxl-behance") }
func BiLogoBing() icons.IsIcon             { return newIcon(logosIcon, "bxl-bing") }
func BiLogoBitcoin() icons.IsIcon          { return newIcon(logosIcon, "bxl-bitcoin") }
func BiLogoBlender() icons.IsIcon          { return newIcon(logosIcon, "bxl-blender") }
func BiLogoBlogger() icons.IsIcon          { return newIcon(logosIcon, "bxl-blogger") }
func BiLogoBootstrap() icons.IsIcon        { return newIcon(logosIcon, "bxl-bootstrap") }
func BiLogoCPlusPlus() icons.IsIcon        { return newIcon(logosIcon, "bxl-c-plus-plus") }
func BiLogoChrome() icons.IsIcon           { return newIcon(logosIcon, "bxl-chrome") }
func BiLogoCodepen() icons.IsIcon          { return newIcon(logosIcon, "bxl-codepen") }
func BiLogoCreativeCommons() icons.IsIcon  { return newIcon(logosIcon, "bxl-creative-commons") }
func BiLogoCss3() icons.IsIcon             { return newIcon(logosIcon, "bxl-css3") }
func BiLogoDailymotion() icons.IsIcon      { return newIcon(logosIcon, "bxl-dailymotion") }
func BiLogoDeezer() icons.IsIcon           { return newIcon(logosIcon, "bxl-deezer") }
func BiLogoDevTo() icons.IsIcon            { return newIcon(logosIcon, "bxl-dev-to") }
func BiLogoDeviantart() icons.IsIcon       { return newIcon(logosIcon, "bxl-deviantart") }
func BiLogoDigg() icons.IsIcon             { return newIcon(logosIcon, "bxl-digg") }
func BiLogoDigitalocean() icons.IsIcon     { return newIcon(logosIcon, "bxl-digitalocean") }
func BiLogoDiscordAlt() icons.IsIcon       { return newIcon(logosIcon, "bxl-discord-alt") }
func BiLogoDiscord() icons.IsIcon          { return newIcon(logosIcon, "bxl-discord") }
func BiLogoDiscourse() icons.IsIcon        { return newIcon(logosIcon, "bxl-discourse") }
func BiLogoDjango() icons.IsIcon           { return newIcon(logosIcon, "bxl-django") }
func BiLogoDocker() icons.IsIcon           { return newIcon(logosIcon, "bxl-docker") }
func BiLogoDribbble() icons.IsIcon         { return newIcon(logosIcon, "bxl-dribbble") }
func BiLogoDropbox() icons.IsIcon          { return newIcon(logosIcon, "bxl-dropbox") }
func BiLogoDrupal() icons.IsIcon           { return newIcon(logosIcon, "bxl-drupal") }
func BiLogoEbay() icons.IsIcon             { return newIcon(logosIcon, "bxl-ebay") }
func BiLogoEdge() icons.IsIcon             { return newIcon(logosIcon, "bxl-edge") }
func BiLogoEtsy() icons.IsIcon             { return newIcon(logosIcon, "bxl-etsy") }
func BiLogoFacebookCircle() icons.IsIcon   { return newIcon(logosIcon, "bxl-facebook-circle") }
func BiLogoFacebookSquare() icons.IsIcon   { return newIcon(logosIcon, "bxl-facebook-square") }
func BiLogoFacebook() icons.IsIcon         { return newIcon(logosIcon, "bxl-facebook") }
func BiLogoFigma() icons.IsIcon            { return newIcon(logosIcon, "bxl-figma") }
func BiLogoFirebase() icons.IsIcon         { return newIcon(logosIcon, "bxl-firebase") }
func BiLogoFirefox() icons.IsIcon          { return newIcon(logosIcon, "bxl-firefox") }
func BiLogoFlask() icons.IsIcon            { return newIcon(logosIcon, "bxl-flask") }
func BiLogoFlickrSquare() icons.IsIcon     { return newIcon(logosIcon, "bxl-flickr-square") }
func BiLogoFlickr() icons.IsIcon           { return newIcon(logosIcon, "bxl-flickr") }
func BiLogoFlutter() icons.IsIcon          { return newIcon(logosIcon, "bxl-flutter") }
func BiLogoFoursquare() icons.IsIcon       { return newIcon(logosIcon, "bxl-foursquare") }
func BiLogoGit() icons.IsIcon              { return newIcon(logosIcon, "bxl-git") }
func BiLogoGithub() icons.IsIcon           { return newIcon(logosIcon, "bxl-github") }
func BiLogoGitlab() icons.IsIcon           { return newIcon(logosIcon, "bxl-gitlab") }
func BiLogoGmail() icons.IsIcon            { return newIcon(logosIcon, "bxl-gmail") }
func BiLogoGoLang() icons.IsIcon           { return newIcon(logosIcon, "bxl-go-lang") }
func BiLogoGoogleCloud() icons.IsIcon      { return newIcon(logosIcon, "bxl-google-cloud") }
func BiLogoGooglePlusCircle() icons.IsIcon { return newIcon(logosIcon, "bxl-google-plus-circle") }
func BiLogoGooglePlus() icons.IsIcon       { return newIcon(logosIcon, "bxl-google-plus") }
func BiLogoGoogle() icons.IsIcon           { return newIcon(logosIcon, "bxl-google") }
func BiLogoGraphql() icons.IsIcon          { return newIcon(logosIcon, "bxl-graphql") }
func BiLogoHeroku() icons.IsIcon           { return newIcon(logosIcon, "bxl-heroku") }
func BiLogoHtml5() icons.IsIcon            { return newIcon(logosIcon, "bxl-html5") }
func BiLogoImdb() icons.IsIcon             { return newIcon(logosIcon, "bxl-imdb") }
func BiLogoInstagramAlt() icons.IsIcon     { return newIcon(logosIcon, "bxl-instagram-alt") }
func BiLogoInstagram() icons.IsIcon        { return newIcon(logosIcon, "bxl-instagram") }
func BiLogoInternetExplorer() icons.IsIcon { return newIcon(logosIcon, "bxl-internet-explorer") }
func BiLogoInvision() icons.IsIcon         { return newIcon(logosIcon, "bxl-invision") }
func BiLogoJava() icons.IsIcon             { return newIcon(logosIcon, "bxl-java") }
func BiLogoJavascript() icons.IsIcon       { return newIcon(logosIcon, "bxl-javascript") }
func BiLogoJoomla() icons.IsIcon           { return newIcon(logosIcon, "bxl-joomla") }
func BiLogoJquery() icons.IsIcon           { return newIcon(logosIcon, "bxl-jquery") }
func BiLogoJsfiddle() icons.IsIcon         { return newIcon(logosIcon, "bxl-jsfiddle") }
func BiLogoKickstarter() icons.IsIcon      { return newIcon(logosIcon, "bxl-kickstarter") }
func BiLogoKubernetes() icons.IsIcon       { return newIcon(logosIcon, "bxl-kubernetes") }
func BiLogoLess() icons.IsIcon             { return newIcon(logosIcon, "bxl-less") }
func BiLogoLinkedinSquare() icons.IsIcon   { return newIcon(logosIcon, "bxl-linkedin-square") }
func BiLogoLinkedin() icons.IsIcon         { return newIcon(logosIcon, "bxl-linkedin") }
func BiLogoMagento() icons.IsIcon          { return newIcon(logosIcon, "bxl-magento") }
func BiLogoMailchimp() icons.IsIcon        { return newIcon(logosIcon, "bxl-mailchimp") }
func BiLogoMarkdown() icons.IsIcon         { return newIcon(logosIcon, "bxl-markdown") }
func BiLogoMastercard() icons.IsIcon       { return newIcon(logosIcon, "bxl-mastercard") }
func BiLogoMastodon() icons.IsIcon         { return newIcon(logosIcon, "bxl-mastodon") }
func BiLogoMediumOld() icons.IsIcon        { return newIcon(logosIcon, "bxl-medium-old") }
func BiLogoMediumSquare() icons.IsIcon     { return newIcon(logosIcon, "bxl-medium-square") }
func BiLogoMedium() icons.IsIcon           { return newIcon(logosIcon, "bxl-medium") }
func BiLogoMessenger() icons.IsIcon        { return newIcon(logosIcon, "bxl-messenger") }
func BiLogoMeta() icons.IsIcon             { return newIcon(logosIcon, "bxl-meta") }
func BiLogoMicrosoftTeams() icons.IsIcon   { return newIcon(logosIcon, "bxl-microsoft-teams") }
func BiLogoMicrosoft() icons.IsIcon        { return newIcon(logosIcon, "bxl-microsoft") }
func BiLogoMongodb() icons.IsIcon          { return newIcon(logosIcon, "bxl-mongodb") }
func BiLogoNetlify() icons.IsIcon          { return newIcon(logosIcon, "bxl-netlify") }
func BiLogoNodejs() icons.IsIcon           { return newIcon(logosIcon, "bxl-nodejs") }
func BiLogoOkRu() icons.IsIcon             { return newIcon(logosIcon, "bxl-ok-ru") }
func BiLogoOpera() icons.IsIcon            { return newIcon(logosIcon, "bxl-opera") }
func BiLogoPatreon() icons.IsIcon          { return newIcon(logosIcon, "bxl-patreon") }
func BiLogoPaypal() icons.IsIcon           { return newIcon(logosIcon, "bxl-paypal") }
func BiLogoPeriscope() icons.IsIcon        { return newIcon(logosIcon, "bxl-periscope") }
func BiLogoPhp() icons.IsIcon              { return newIcon(logosIcon, "bxl-php") }
func BiLogoPinterestAlt() icons.IsIcon     { return newIcon(logosIcon, "bxl-pinterest-alt") }
func BiLogoPinterest() icons.IsIcon        { return newIcon(logosIcon, "bxl-pinterest") }
func BiLogoPlayStore() icons.IsIcon        { return newIcon(logosIcon, "bxl-play-store") }
func BiLogoPocket() icons.IsIcon           { return newIcon(logosIcon, "bxl-pocket") }
func BiLogoPostgresql() icons.IsIcon       { return newIcon(logosIcon, "bxl-postgresql") }
func BiLogoProductHunt() icons.IsIcon      { return newIcon(logosIcon, "bxl-product-hunt") }
func BiLogoPython() icons.IsIcon           { return newIcon(logosIcon, "bxl-python") }
func BiLogoQuora() icons.IsIcon            { return newIcon(logosIcon, "bxl-quora") }
func BiLogoReact() icons.IsIcon            { return newIcon(logosIcon, "bxl-react") }
func BiLogoRedbubble() icons.IsIcon        { return newIcon(logosIcon, "bxl-redbubble") }
func BiLogoReddit() icons.IsIcon           { return newIcon(logosIcon, "bxl-reddit") }
func BiLogoRedux() icons.IsIcon            { return newIcon(logosIcon, "bxl-redux") }
func BiLogoSass() icons.IsIcon             { return newIcon(logosIcon, "bxl-sass") }
func BiLogoShopify() icons.IsIcon          { return newIcon(logosIcon, "bxl-shopify") }
func BiLogoSketch() icons.IsIcon           { return newIcon(logosIcon, "bxl-sketch") }
func BiLogoSkype() icons.IsIcon            { return newIcon(logosIcon, "bxl-skype") }
func BiLogoSlackOld() icons.IsIcon         { return newIcon(logosIcon, "bxl-slack-old") }
func BiLogoSlack() icons.IsIcon            { return newIcon(logosIcon, "bxl-slack") }
func BiLogoSnapchat() icons.IsIcon         { return newIcon(logosIcon, "bxl-snapchat") }
func BiLogoSoundcloud() icons.IsIcon       { return newIcon(logosIcon, "bxl-soundcloud") }
func BiLogoSpotify() icons.IsIcon          { return newIcon(logosIcon, "bxl-spotify") }
func BiLogoSpringBoot() icons.IsIcon       { return newIcon(logosIcon, "bxl-spring-boot") }
func BiLogoSquarespace() icons.IsIcon      { return newIcon(logosIcon, "bxl-squarespace") }
func BiLogoStackOverflow() icons.IsIcon    { return newIcon(logosIcon, "bxl-stack-overflow") }
func BiLogoSteam() icons.IsIcon            { return newIcon(logosIcon, "bxl-steam") }
func BiLogoStripe() icons.IsIcon           { return newIcon(logosIcon, "bxl-stripe") }
func BiLogoTailwindCss() icons.IsIcon      { return newIcon(logosIcon, "bxl-tailwind-css") }
func BiLogoTelegram() icons.IsIcon         { return newIcon(logosIcon, "bxl-telegram") }
func BiLogoTiktok() icons.IsIcon           { return newIcon(logosIcon, "bxl-tiktok") }
func BiLogoTrello() icons.IsIcon           { return newIcon(logosIcon, "bxl-trello") }
func BiLogoTripAdvisor() icons.IsIcon      { return newIcon(logosIcon, "bxl-trip-advisor") }
func BiLogoTumblr() icons.IsIcon           { return newIcon(logosIcon, "bxl-tumblr") }
func BiLogoTux() icons.IsIcon              { return newIcon(logosIcon, "bxl-tux") }
func BiLogoTwitch() icons.IsIcon           { return newIcon(logosIcon, "bxl-twitch") }
func BiLogoTwitter() icons.IsIcon          { return newIcon(logosIcon, "bxl-twitter") }
func BiLogoTypescript() icons.IsIcon       { return newIcon(logosIcon, "bxl-typescript") }
func BiLogoUnity() icons.IsIcon            { return newIcon(logosIcon, "bxl-unity") }
func BiLogoUnsplash() icons.IsIcon         { return newIcon(logosIcon, "bxl-unsplash") }
func BiLogoUpwork() icons.IsIcon           { return newIcon(logosIcon, "bxl-upwork") }
func BiLogoVenmo() icons.IsIcon            { return newIcon(logosIcon, "bxl-venmo") }
func BiLogoVimeo() icons.IsIcon            { return newIcon(logosIcon, "bxl-vimeo") }
func BiLogoVisa() icons.IsIcon             { return newIcon(logosIcon, "bxl-visa") }
func BiLogoVisualStudio() icons.IsIcon     { return newIcon(logosIcon, "bxl-visual-studio") }
func BiLogoVk() icons.IsIcon               { return newIcon(logosIcon, "bxl-vk") }
func BiLogoVuejs() icons.IsIcon            { return newIcon(logosIcon, "bxl-vuejs") }
func BiLogoWhatsappSquare() icons.IsIcon   { return newIcon(logosIcon, "bxl-whatsapp-square") }
func BiLogoWhatsapp() icons.IsIcon         { return newIcon(logosIcon, "bxl-whatsapp") }
func BiLogoWikipedia() icons.IsIcon        { return newIcon(logosIcon, "bxl-wikipedia") }
func BiLogoWindows() icons.IsIcon          { return newIcon(logosIcon, "bxl-windows") }
func BiLogoWix() icons.IsIcon              { return newIcon(logosIcon, "bxl-wix") }
func BiLogoWordpress() icons.IsIcon        { return newIcon(logosIcon, "bxl-wordpress") }
func BiLogoXing() icons.IsIcon             { return newIcon(logosIcon, "bxl-xing") }
func BiLogoYahoo() icons.IsIcon            { return newIcon(logosIcon, "bxl-yahoo") }
func BiLogoYelp() icons.IsIcon             { return newIcon(logosIcon, "bxl-yelp") }
func BiLogoYoutube() icons.IsIcon          { return newIcon(logosIcon, "bxl-youtube") }
func BiLogoZoom() icons.IsIcon             { return newIcon(logosIcon, "bxl-zoom") }
