package bi

import "github.com/raitucarp/gomix/icons"

func BiAbacus() icons.IsIcon              { return newIcon(regularIcon, "bx-abacus") }
func BiAccessibility() icons.IsIcon       { return newIcon(regularIcon, "bx-accessibility") }
func BiAddToQueue() icons.IsIcon          { return newIcon(regularIcon, "bx-add-to-queue") }
func BiAdjust() icons.IsIcon              { return newIcon(regularIcon, "bx-adjust") }
func BiAlarmAdd() icons.IsIcon            { return newIcon(regularIcon, "bx-alarm-add") }
func BiAlarmExclamation() icons.IsIcon    { return newIcon(regularIcon, "bx-alarm-exclamation") }
func BiAlarmOff() icons.IsIcon            { return newIcon(regularIcon, "bx-alarm-off") }
func BiAlarmSnooze() icons.IsIcon         { return newIcon(regularIcon, "bx-alarm-snooze") }
func BiAlarm() icons.IsIcon               { return newIcon(regularIcon, "bx-alarm") }
func BiAlbum() icons.IsIcon               { return newIcon(regularIcon, "bx-album") }
func BiAlignJustify() icons.IsIcon        { return newIcon(regularIcon, "bx-align-justify") }
func BiAlignLeft() icons.IsIcon           { return newIcon(regularIcon, "bx-align-left") }
func BiAlignMiddle() icons.IsIcon         { return newIcon(regularIcon, "bx-align-middle") }
func BiAlignRight() icons.IsIcon          { return newIcon(regularIcon, "bx-align-right") }
func BiAnalyse() icons.IsIcon             { return newIcon(regularIcon, "bx-analyse") }
func BiAnchor() icons.IsIcon              { return newIcon(regularIcon, "bx-anchor") }
func BiAngry() icons.IsIcon               { return newIcon(regularIcon, "bx-angry") }
func BiAperture() icons.IsIcon            { return newIcon(regularIcon, "bx-aperture") }
func BiArch() icons.IsIcon                { return newIcon(regularIcon, "bx-arch") }
func BiArchiveIn() icons.IsIcon           { return newIcon(regularIcon, "bx-archive-in") }
func BiArchiveOut() icons.IsIcon          { return newIcon(regularIcon, "bx-archive-out") }
func BiArchive() icons.IsIcon             { return newIcon(regularIcon, "bx-archive") }
func BiArea() icons.IsIcon                { return newIcon(regularIcon, "bx-area") }
func BiArrowBack() icons.IsIcon           { return newIcon(regularIcon, "bx-arrow-back") }
func BiArrowFromBottom() icons.IsIcon     { return newIcon(regularIcon, "bx-arrow-from-bottom") }
func BiArrowFromLeft() icons.IsIcon       { return newIcon(regularIcon, "bx-arrow-from-left") }
func BiArrowFromRight() icons.IsIcon      { return newIcon(regularIcon, "bx-arrow-from-right") }
func BiArrowFromTop() icons.IsIcon        { return newIcon(regularIcon, "bx-arrow-from-top") }
func BiArrowToBottom() icons.IsIcon       { return newIcon(regularIcon, "bx-arrow-to-bottom") }
func BiArrowToLeft() icons.IsIcon         { return newIcon(regularIcon, "bx-arrow-to-left") }
func BiArrowToRight() icons.IsIcon        { return newIcon(regularIcon, "bx-arrow-to-right") }
func BiArrowToTop() icons.IsIcon          { return newIcon(regularIcon, "bx-arrow-to-top") }
func BiAt() icons.IsIcon                  { return newIcon(regularIcon, "bx-at") }
func BiAtom() icons.IsIcon                { return newIcon(regularIcon, "bx-atom") }
func BiAward() icons.IsIcon               { return newIcon(regularIcon, "bx-award") }
func BiBadgeCheck() icons.IsIcon          { return newIcon(regularIcon, "bx-badge-check") }
func BiBadge() icons.IsIcon               { return newIcon(regularIcon, "bx-badge") }
func BiBaguette() icons.IsIcon            { return newIcon(regularIcon, "bx-baguette") }
func BiBall() icons.IsIcon                { return newIcon(regularIcon, "bx-ball") }
func BiBandAid() icons.IsIcon             { return newIcon(regularIcon, "bx-band-aid") }
func BiBarChartAlt2() icons.IsIcon        { return newIcon(regularIcon, "bx-bar-chart-alt-2") }
func BiBarChartAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-bar-chart-alt") }
func BiBarChartSquare() icons.IsIcon      { return newIcon(regularIcon, "bx-bar-chart-square") }
func BiBarChart() icons.IsIcon            { return newIcon(regularIcon, "bx-bar-chart") }
func BiBarcodeReader() icons.IsIcon       { return newIcon(regularIcon, "bx-barcode-reader") }
func BiBarcode() icons.IsIcon             { return newIcon(regularIcon, "bx-barcode") }
func BiBaseball() icons.IsIcon            { return newIcon(regularIcon, "bx-baseball") }
func BiBasket() icons.IsIcon              { return newIcon(regularIcon, "bx-basket") }
func BiBasketball() icons.IsIcon          { return newIcon(regularIcon, "bx-basketball") }
func BiBath() icons.IsIcon                { return newIcon(regularIcon, "bx-bath") }
func BiBattery() icons.IsIcon             { return newIcon(regularIcon, "bx-battery") }
func BiBed() icons.IsIcon                 { return newIcon(regularIcon, "bx-bed") }
func BiBeenHere() icons.IsIcon            { return newIcon(regularIcon, "bx-been-here") }
func BiBeer() icons.IsIcon                { return newIcon(regularIcon, "bx-beer") }
func BiBellMinus() icons.IsIcon           { return newIcon(regularIcon, "bx-bell-minus") }
func BiBellOff() icons.IsIcon             { return newIcon(regularIcon, "bx-bell-off") }
func BiBellPlus() icons.IsIcon            { return newIcon(regularIcon, "bx-bell-plus") }
func BiBell() icons.IsIcon                { return newIcon(regularIcon, "bx-bell") }
func BiBible() icons.IsIcon               { return newIcon(regularIcon, "bx-bible") }
func BiBitcoin() icons.IsIcon             { return newIcon(regularIcon, "bx-bitcoin") }
func BiBlanket() icons.IsIcon             { return newIcon(regularIcon, "bx-blanket") }
func BiBlock() icons.IsIcon               { return newIcon(regularIcon, "bx-block") }
func BiBluetooth() icons.IsIcon           { return newIcon(regularIcon, "bx-bluetooth") }
func BiBody() icons.IsIcon                { return newIcon(regularIcon, "bx-body") }
func BiBold() icons.IsIcon                { return newIcon(regularIcon, "bx-bold") }
func BiBoltCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-bolt-circle") }
func BiBomb() icons.IsIcon                { return newIcon(regularIcon, "bx-bomb") }
func BiBone() icons.IsIcon                { return newIcon(regularIcon, "bx-bone") }
func BiBong() icons.IsIcon                { return newIcon(regularIcon, "bx-bong") }
func BiBookAdd() icons.IsIcon             { return newIcon(regularIcon, "bx-book-add") }
func BiBookAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-book-alt") }
func BiBookBookmark() icons.IsIcon        { return newIcon(regularIcon, "bx-book-bookmark") }
func BiBookContent() icons.IsIcon         { return newIcon(regularIcon, "bx-book-content") }
func BiBookHeart() icons.IsIcon           { return newIcon(regularIcon, "bx-book-heart") }
func BiBookOpen() icons.IsIcon            { return newIcon(regularIcon, "bx-book-open") }
func BiBookReader() icons.IsIcon          { return newIcon(regularIcon, "bx-book-reader") }
func BiBook() icons.IsIcon                { return newIcon(regularIcon, "bx-book") }
func BiBookmarkAltMinus() icons.IsIcon    { return newIcon(regularIcon, "bx-bookmark-alt-minus") }
func BiBookmarkAltPlus() icons.IsIcon     { return newIcon(regularIcon, "bx-bookmark-alt-plus") }
func BiBookmarkAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-bookmark-alt") }
func BiBookmarkHeart() icons.IsIcon       { return newIcon(regularIcon, "bx-bookmark-heart") }
func BiBookmarkMinus() icons.IsIcon       { return newIcon(regularIcon, "bx-bookmark-minus") }
func BiBookmarkPlus() icons.IsIcon        { return newIcon(regularIcon, "bx-bookmark-plus") }
func BiBookmark() icons.IsIcon            { return newIcon(regularIcon, "bx-bookmark") }
func BiBookmarks() icons.IsIcon           { return newIcon(regularIcon, "bx-bookmarks") }
func BiBorderAll() icons.IsIcon           { return newIcon(regularIcon, "bx-border-all") }
func BiBorderBottom() icons.IsIcon        { return newIcon(regularIcon, "bx-border-bottom") }
func BiBorderInner() icons.IsIcon         { return newIcon(regularIcon, "bx-border-inner") }
func BiBorderLeft() icons.IsIcon          { return newIcon(regularIcon, "bx-border-left") }
func BiBorderNone() icons.IsIcon          { return newIcon(regularIcon, "bx-border-none") }
func BiBorderOuter() icons.IsIcon         { return newIcon(regularIcon, "bx-border-outer") }
func BiBorderRadius() icons.IsIcon        { return newIcon(regularIcon, "bx-border-radius") }
func BiBorderRight() icons.IsIcon         { return newIcon(regularIcon, "bx-border-right") }
func BiBorderTop() icons.IsIcon           { return newIcon(regularIcon, "bx-border-top") }
func BiBot() icons.IsIcon                 { return newIcon(regularIcon, "bx-bot") }
func BiBowlHot() icons.IsIcon             { return newIcon(regularIcon, "bx-bowl-hot") }
func BiBowlRice() icons.IsIcon            { return newIcon(regularIcon, "bx-bowl-rice") }
func BiBowlingBall() icons.IsIcon         { return newIcon(regularIcon, "bx-bowling-ball") }
func BiBox() icons.IsIcon                 { return newIcon(regularIcon, "bx-box") }
func BiBracket() icons.IsIcon             { return newIcon(regularIcon, "bx-bracket") }
func BiBraille() icons.IsIcon             { return newIcon(regularIcon, "bx-braille") }
func BiBrain() icons.IsIcon               { return newIcon(regularIcon, "bx-brain") }
func BiBriefcaseAlt2() icons.IsIcon       { return newIcon(regularIcon, "bx-briefcase-alt-2") }
func BiBriefcaseAlt() icons.IsIcon        { return newIcon(regularIcon, "bx-briefcase-alt") }
func BiBriefcase() icons.IsIcon           { return newIcon(regularIcon, "bx-briefcase") }
func BiBrightnessHalf() icons.IsIcon      { return newIcon(regularIcon, "bx-brightness-half") }
func BiBrightness() icons.IsIcon          { return newIcon(regularIcon, "bx-brightness") }
func BiBroadcast() icons.IsIcon           { return newIcon(regularIcon, "bx-broadcast") }
func BiBrushAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-brush-alt") }
func BiBrush() icons.IsIcon               { return newIcon(regularIcon, "bx-brush") }
func BiBugAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-bug-alt") }
func BiBug() icons.IsIcon                 { return newIcon(regularIcon, "bx-bug") }
func BiBuildingHouse() icons.IsIcon       { return newIcon(regularIcon, "bx-building-house") }
func BiBuilding() icons.IsIcon            { return newIcon(regularIcon, "bx-building") }
func BiBuildings() icons.IsIcon           { return newIcon(regularIcon, "bx-buildings") }
func BiBulb() icons.IsIcon                { return newIcon(regularIcon, "bx-bulb") }
func BiBullseye() icons.IsIcon            { return newIcon(regularIcon, "bx-bullseye") }
func BiBuoy() icons.IsIcon                { return newIcon(regularIcon, "bx-buoy") }
func BiBusSchool() icons.IsIcon           { return newIcon(regularIcon, "bx-bus-school") }
func BiBus() icons.IsIcon                 { return newIcon(regularIcon, "bx-bus") }
func BiCabinet() icons.IsIcon             { return newIcon(regularIcon, "bx-cabinet") }
func BiCableCar() icons.IsIcon            { return newIcon(regularIcon, "bx-cable-car") }
func BiCake() icons.IsIcon                { return newIcon(regularIcon, "bx-cake") }
func BiCalculator() icons.IsIcon          { return newIcon(regularIcon, "bx-calculator") }
func BiCalendarAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-calendar-alt") }
func BiCalendarCheck() icons.IsIcon       { return newIcon(regularIcon, "bx-calendar-check") }
func BiCalendarEdit() icons.IsIcon        { return newIcon(regularIcon, "bx-calendar-edit") }
func BiCalendarEvent() icons.IsIcon       { return newIcon(regularIcon, "bx-calendar-event") }
func BiCalendarExclamation() icons.IsIcon { return newIcon(regularIcon, "bx-calendar-exclamation") }
func BiCalendarHeart() icons.IsIcon       { return newIcon(regularIcon, "bx-calendar-heart") }
func BiCalendarMinus() icons.IsIcon       { return newIcon(regularIcon, "bx-calendar-minus") }
func BiCalendarPlus() icons.IsIcon        { return newIcon(regularIcon, "bx-calendar-plus") }
func BiCalendarStar() icons.IsIcon        { return newIcon(regularIcon, "bx-calendar-star") }
func BiCalendarWeek() icons.IsIcon        { return newIcon(regularIcon, "bx-calendar-week") }
func BiCalendarX() icons.IsIcon           { return newIcon(regularIcon, "bx-calendar-x") }
func BiCalendar() icons.IsIcon            { return newIcon(regularIcon, "bx-calendar") }
func BiCameraHome() icons.IsIcon          { return newIcon(regularIcon, "bx-camera-home") }
func BiCameraMovie() icons.IsIcon         { return newIcon(regularIcon, "bx-camera-movie") }
func BiCameraOff() icons.IsIcon           { return newIcon(regularIcon, "bx-camera-off") }
func BiCamera() icons.IsIcon              { return newIcon(regularIcon, "bx-camera") }
func BiCandles() icons.IsIcon             { return newIcon(regularIcon, "bx-candles") }
func BiCapsule() icons.IsIcon             { return newIcon(regularIcon, "bx-capsule") }
func BiCaptions() icons.IsIcon            { return newIcon(regularIcon, "bx-captions") }
func BiCar() icons.IsIcon                 { return newIcon(regularIcon, "bx-car") }
func BiCard() icons.IsIcon                { return newIcon(regularIcon, "bx-card") }
func BiCaretDownCircle() icons.IsIcon     { return newIcon(regularIcon, "bx-caret-down-circle") }
func BiCaretDownSquare() icons.IsIcon     { return newIcon(regularIcon, "bx-caret-down-square") }
func BiCaretDown() icons.IsIcon           { return newIcon(regularIcon, "bx-caret-down") }
func BiCaretLeftCircle() icons.IsIcon     { return newIcon(regularIcon, "bx-caret-left-circle") }
func BiCaretLeftSquare() icons.IsIcon     { return newIcon(regularIcon, "bx-caret-left-square") }
func BiCaretLeft() icons.IsIcon           { return newIcon(regularIcon, "bx-caret-left") }
func BiCaretRightCircle() icons.IsIcon    { return newIcon(regularIcon, "bx-caret-right-circle") }
func BiCaretRightSquare() icons.IsIcon    { return newIcon(regularIcon, "bx-caret-right-square") }
func BiCaretRight() icons.IsIcon          { return newIcon(regularIcon, "bx-caret-right") }
func BiCaretUpCircle() icons.IsIcon       { return newIcon(regularIcon, "bx-caret-up-circle") }
func BiCaretUpSquare() icons.IsIcon       { return newIcon(regularIcon, "bx-caret-up-square") }
func BiCaretUp() icons.IsIcon             { return newIcon(regularIcon, "bx-caret-up") }
func BiCarousel() icons.IsIcon            { return newIcon(regularIcon, "bx-carousel") }
func BiCartAdd() icons.IsIcon             { return newIcon(regularIcon, "bx-cart-add") }
func BiCartAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-cart-alt") }
func BiCartDownload() icons.IsIcon        { return newIcon(regularIcon, "bx-cart-download") }
func BiCart() icons.IsIcon                { return newIcon(regularIcon, "bx-cart") }
func BiCast() icons.IsIcon                { return newIcon(regularIcon, "bx-cast") }
func BiCategoryAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-category-alt") }
func BiCategory() icons.IsIcon            { return newIcon(regularIcon, "bx-category") }
func BiCctv() icons.IsIcon                { return newIcon(regularIcon, "bx-cctv") }
func BiCertification() icons.IsIcon       { return newIcon(regularIcon, "bx-certification") }
func BiChair() icons.IsIcon               { return newIcon(regularIcon, "bx-chair") }
func BiChalkboard() icons.IsIcon          { return newIcon(regularIcon, "bx-chalkboard") }
func BiChart() icons.IsIcon               { return newIcon(regularIcon, "bx-chart") }
func BiChat() icons.IsIcon                { return newIcon(regularIcon, "bx-chat") }
func BiCheckCircle() icons.IsIcon         { return newIcon(regularIcon, "bx-check-circle") }
func BiCheckDouble() icons.IsIcon         { return newIcon(regularIcon, "bx-check-double") }
func BiCheckShield() icons.IsIcon         { return newIcon(regularIcon, "bx-check-shield") }
func BiCheckSquare() icons.IsIcon         { return newIcon(regularIcon, "bx-check-square") }
func BiCheck() icons.IsIcon               { return newIcon(regularIcon, "bx-check") }
func BiCheckboxChecked() icons.IsIcon     { return newIcon(regularIcon, "bx-checkbox-checked") }
func BiCheckboxMinus() icons.IsIcon       { return newIcon(regularIcon, "bx-checkbox-minus") }
func BiCheckboxSquare() icons.IsIcon      { return newIcon(regularIcon, "bx-checkbox-square") }
func BiCheckbox() icons.IsIcon            { return newIcon(regularIcon, "bx-checkbox") }
func BiCheese() icons.IsIcon              { return newIcon(regularIcon, "bx-cheese") }
func BiChevronDownCircle() icons.IsIcon   { return newIcon(regularIcon, "bx-chevron-down-circle") }
func BiChevronDownSquare() icons.IsIcon   { return newIcon(regularIcon, "bx-chevron-down-square") }
func BiChevronDown() icons.IsIcon         { return newIcon(regularIcon, "bx-chevron-down") }
func BiChevronLeftCircle() icons.IsIcon   { return newIcon(regularIcon, "bx-chevron-left-circle") }
func BiChevronLeftSquare() icons.IsIcon   { return newIcon(regularIcon, "bx-chevron-left-square") }
func BiChevronLeft() icons.IsIcon         { return newIcon(regularIcon, "bx-chevron-left") }
func BiChevronRightCircle() icons.IsIcon  { return newIcon(regularIcon, "bx-chevron-right-circle") }
func BiChevronRightSquare() icons.IsIcon  { return newIcon(regularIcon, "bx-chevron-right-square") }
func BiChevronRight() icons.IsIcon        { return newIcon(regularIcon, "bx-chevron-right") }
func BiChevronUpCircle() icons.IsIcon     { return newIcon(regularIcon, "bx-chevron-up-circle") }
func BiChevronUpSquare() icons.IsIcon     { return newIcon(regularIcon, "bx-chevron-up-square") }
func BiChevronUp() icons.IsIcon           { return newIcon(regularIcon, "bx-chevron-up") }
func BiChevronsDown() icons.IsIcon        { return newIcon(regularIcon, "bx-chevrons-down") }
func BiChevronsLeft() icons.IsIcon        { return newIcon(regularIcon, "bx-chevrons-left") }
func BiChevronsRight() icons.IsIcon       { return newIcon(regularIcon, "bx-chevrons-right") }
func BiChevronsUp() icons.IsIcon          { return newIcon(regularIcon, "bx-chevrons-up") }
func BiChild() icons.IsIcon               { return newIcon(regularIcon, "bx-child") }
func BiChip() icons.IsIcon                { return newIcon(regularIcon, "bx-chip") }
func BiChurch() icons.IsIcon              { return newIcon(regularIcon, "bx-church") }
func BiCircleHalf() icons.IsIcon          { return newIcon(regularIcon, "bx-circle-half") }
func BiCircleQuarter() icons.IsIcon       { return newIcon(regularIcon, "bx-circle-quarter") }
func BiCircleThreeQuarter() icons.IsIcon  { return newIcon(regularIcon, "bx-circle-three-quarter") }
func BiCircle() icons.IsIcon              { return newIcon(regularIcon, "bx-circle") }
func BiClinic() icons.IsIcon              { return newIcon(regularIcon, "bx-clinic") }
func BiClipboard() icons.IsIcon           { return newIcon(regularIcon, "bx-clipboard") }
func BiCloset() icons.IsIcon              { return newIcon(regularIcon, "bx-closet") }
func BiCloudDownload() icons.IsIcon       { return newIcon(regularIcon, "bx-cloud-download") }
func BiCloudDrizzle() icons.IsIcon        { return newIcon(regularIcon, "bx-cloud-drizzle") }
func BiCloudLightRain() icons.IsIcon      { return newIcon(regularIcon, "bx-cloud-light-rain") }
func BiCloudLightning() icons.IsIcon      { return newIcon(regularIcon, "bx-cloud-lightning") }
func BiCloudRain() icons.IsIcon           { return newIcon(regularIcon, "bx-cloud-rain") }
func BiCloudSnow() icons.IsIcon           { return newIcon(regularIcon, "bx-cloud-snow") }
func BiCloudUpload() icons.IsIcon         { return newIcon(regularIcon, "bx-cloud-upload") }
func BiCloud() icons.IsIcon               { return newIcon(regularIcon, "bx-cloud") }
func BiCodeAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-code-alt") }
func BiCodeBlock() icons.IsIcon           { return newIcon(regularIcon, "bx-code-block") }
func BiCodeCurly() icons.IsIcon           { return newIcon(regularIcon, "bx-code-curly") }
func BiCode() icons.IsIcon                { return newIcon(regularIcon, "bx-code") }
func BiCoffeeTogo() icons.IsIcon          { return newIcon(regularIcon, "bx-coffee-togo") }
func BiCoffee() icons.IsIcon              { return newIcon(regularIcon, "bx-coffee") }
func BiCog() icons.IsIcon                 { return newIcon(regularIcon, "bx-cog") }
func BiCoinStack() icons.IsIcon           { return newIcon(regularIcon, "bx-coin-stack") }
func BiCoin() icons.IsIcon                { return newIcon(regularIcon, "bx-coin") }
func BiCollapseAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-collapse-alt") }
func BiCollapseHorizontal() icons.IsIcon  { return newIcon(regularIcon, "bx-collapse-horizontal") }
func BiCollapseVertical() icons.IsIcon    { return newIcon(regularIcon, "bx-collapse-vertical") }
func BiCollapse() icons.IsIcon            { return newIcon(regularIcon, "bx-collapse") }
func BiCollection() icons.IsIcon          { return newIcon(regularIcon, "bx-collection") }
func BiColorFill() icons.IsIcon           { return newIcon(regularIcon, "bx-color-fill") }
func BiColor() icons.IsIcon               { return newIcon(regularIcon, "bx-color") }
func BiColumns() icons.IsIcon             { return newIcon(regularIcon, "bx-columns") }
func BiCommand() icons.IsIcon             { return newIcon(regularIcon, "bx-command") }
func BiCommentAdd() icons.IsIcon          { return newIcon(regularIcon, "bx-comment-add") }
func BiCommentCheck() icons.IsIcon        { return newIcon(regularIcon, "bx-comment-check") }
func BiCommentDetail() icons.IsIcon       { return newIcon(regularIcon, "bx-comment-detail") }
func BiCommentDots() icons.IsIcon         { return newIcon(regularIcon, "bx-comment-dots") }
func BiCommentEdit() icons.IsIcon         { return newIcon(regularIcon, "bx-comment-edit") }
func BiCommentError() icons.IsIcon        { return newIcon(regularIcon, "bx-comment-error") }
func BiCommentMinus() icons.IsIcon        { return newIcon(regularIcon, "bx-comment-minus") }
func BiCommentX() icons.IsIcon            { return newIcon(regularIcon, "bx-comment-x") }
func BiComment() icons.IsIcon             { return newIcon(regularIcon, "bx-comment") }
func BiCompass() icons.IsIcon             { return newIcon(regularIcon, "bx-compass") }
func BiConfused() icons.IsIcon            { return newIcon(regularIcon, "bx-confused") }
func BiConversation() icons.IsIcon        { return newIcon(regularIcon, "bx-conversation") }
func BiCookie() icons.IsIcon              { return newIcon(regularIcon, "bx-cookie") }
func BiCool() icons.IsIcon                { return newIcon(regularIcon, "bx-cool") }
func BiCopyAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-copy-alt") }
func BiCopy() icons.IsIcon                { return newIcon(regularIcon, "bx-copy") }
func BiCopyright() icons.IsIcon           { return newIcon(regularIcon, "bx-copyright") }
func BiCreditCardAlt() icons.IsIcon       { return newIcon(regularIcon, "bx-credit-card-alt") }
func BiCreditCardFront() icons.IsIcon     { return newIcon(regularIcon, "bx-credit-card-front") }
func BiCreditCard() icons.IsIcon          { return newIcon(regularIcon, "bx-credit-card") }
func BiCricketBall() icons.IsIcon         { return newIcon(regularIcon, "bx-cricket-ball") }
func BiCrop() icons.IsIcon                { return newIcon(regularIcon, "bx-crop") }
func BiCross() icons.IsIcon               { return newIcon(regularIcon, "bx-cross") }
func BiCrosshair() icons.IsIcon           { return newIcon(regularIcon, "bx-crosshair") }
func BiCrown() icons.IsIcon               { return newIcon(regularIcon, "bx-crown") }
func BiCubeAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-cube-alt") }
func BiCube() icons.IsIcon                { return newIcon(regularIcon, "bx-cube") }
func BiCuboid() icons.IsIcon              { return newIcon(regularIcon, "bx-cuboid") }
func BiCurrentLocation() icons.IsIcon     { return newIcon(regularIcon, "bx-current-location") }
func BiCustomize() icons.IsIcon           { return newIcon(regularIcon, "bx-customize") }
func BiCut() icons.IsIcon                 { return newIcon(regularIcon, "bx-cut") }
func BiCycling() icons.IsIcon             { return newIcon(regularIcon, "bx-cycling") }
func BiCylinder() icons.IsIcon            { return newIcon(regularIcon, "bx-cylinder") }
func BiData() icons.IsIcon                { return newIcon(regularIcon, "bx-data") }
func BiDesktop() icons.IsIcon             { return newIcon(regularIcon, "bx-desktop") }
func BiDetail() icons.IsIcon              { return newIcon(regularIcon, "bx-detail") }
func BiDevices() icons.IsIcon             { return newIcon(regularIcon, "bx-devices") }
func BiDialpadAlt() icons.IsIcon          { return newIcon(regularIcon, "bx-dialpad-alt") }
func BiDialpad() icons.IsIcon             { return newIcon(regularIcon, "bx-dialpad") }
func BiDiamond() icons.IsIcon             { return newIcon(regularIcon, "bx-diamond") }
func BiDice1() icons.IsIcon               { return newIcon(regularIcon, "bx-dice-1") }
func BiDice2() icons.IsIcon               { return newIcon(regularIcon, "bx-dice-2") }
func BiDice3() icons.IsIcon               { return newIcon(regularIcon, "bx-dice-3") }
func BiDice4() icons.IsIcon               { return newIcon(regularIcon, "bx-dice-4") }
func BiDice5() icons.IsIcon               { return newIcon(regularIcon, "bx-dice-5") }
func BiDice6() icons.IsIcon               { return newIcon(regularIcon, "bx-dice-6") }
func BiDirections() icons.IsIcon          { return newIcon(regularIcon, "bx-directions") }
func BiDisc() icons.IsIcon                { return newIcon(regularIcon, "bx-disc") }
func BiDish() icons.IsIcon                { return newIcon(regularIcon, "bx-dish") }
func BiDislike() icons.IsIcon             { return newIcon(regularIcon, "bx-dislike") }
func BiDizzy() icons.IsIcon               { return newIcon(regularIcon, "bx-dizzy") }
func BiDna() icons.IsIcon                 { return newIcon(regularIcon, "bx-dna") }
func BiDockBottom() icons.IsIcon          { return newIcon(regularIcon, "bx-dock-bottom") }
func BiDockLeft() icons.IsIcon            { return newIcon(regularIcon, "bx-dock-left") }
func BiDockRight() icons.IsIcon           { return newIcon(regularIcon, "bx-dock-right") }
func BiDockTop() icons.IsIcon             { return newIcon(regularIcon, "bx-dock-top") }
func BiDollarCircle() icons.IsIcon        { return newIcon(regularIcon, "bx-dollar-circle") }
func BiDollar() icons.IsIcon              { return newIcon(regularIcon, "bx-dollar") }
func BiDonateBlood() icons.IsIcon         { return newIcon(regularIcon, "bx-donate-blood") }
func BiDonateHeart() icons.IsIcon         { return newIcon(regularIcon, "bx-donate-heart") }
func BiDoorOpen() icons.IsIcon            { return newIcon(regularIcon, "bx-door-open") }
func BiDotsHorizontalRounded() icons.IsIcon {
	return newIcon(regularIcon, "bx-dots-horizontal-rounded")
}
func BiDotsHorizontal() icons.IsIcon       { return newIcon(regularIcon, "bx-dots-horizontal") }
func BiDotsVerticalRounded() icons.IsIcon  { return newIcon(regularIcon, "bx-dots-vertical-rounded") }
func BiDotsVertical() icons.IsIcon         { return newIcon(regularIcon, "bx-dots-vertical") }
func BiDoughnutChart() icons.IsIcon        { return newIcon(regularIcon, "bx-doughnut-chart") }
func BiDownArrowAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-down-arrow-alt") }
func BiDownArrowCircle() icons.IsIcon      { return newIcon(regularIcon, "bx-down-arrow-circle") }
func BiDownArrow() icons.IsIcon            { return newIcon(regularIcon, "bx-down-arrow") }
func BiDownload() icons.IsIcon             { return newIcon(regularIcon, "bx-download") }
func BiDownvote() icons.IsIcon             { return newIcon(regularIcon, "bx-downvote") }
func BiDrink() icons.IsIcon                { return newIcon(regularIcon, "bx-drink") }
func BiDroplet() icons.IsIcon              { return newIcon(regularIcon, "bx-droplet") }
func BiDumbbell() icons.IsIcon             { return newIcon(regularIcon, "bx-dumbbell") }
func BiDuplicate() icons.IsIcon            { return newIcon(regularIcon, "bx-duplicate") }
func BiEditAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-edit-alt") }
func BiEdit() icons.IsIcon                 { return newIcon(regularIcon, "bx-edit") }
func BiEnvelopeOpen() icons.IsIcon         { return newIcon(regularIcon, "bx-envelope-open") }
func BiEnvelope() icons.IsIcon             { return newIcon(regularIcon, "bx-envelope") }
func BiEqualizer() icons.IsIcon            { return newIcon(regularIcon, "bx-equalizer") }
func BiEraser() icons.IsIcon               { return newIcon(regularIcon, "bx-eraser") }
func BiErrorAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-error-alt") }
func BiErrorCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-error-circle") }
func BiError() icons.IsIcon                { return newIcon(regularIcon, "bx-error") }
func BiEuro() icons.IsIcon                 { return newIcon(regularIcon, "bx-euro") }
func BiExclude() icons.IsIcon              { return newIcon(regularIcon, "bx-exclude") }
func BiExitFullscreen() icons.IsIcon       { return newIcon(regularIcon, "bx-exit-fullscreen") }
func BiExit() icons.IsIcon                 { return newIcon(regularIcon, "bx-exit") }
func BiExpandAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-expand-alt") }
func BiExpandHorizontal() icons.IsIcon     { return newIcon(regularIcon, "bx-expand-horizontal") }
func BiExpandVertical() icons.IsIcon       { return newIcon(regularIcon, "bx-expand-vertical") }
func BiExpand() icons.IsIcon               { return newIcon(regularIcon, "bx-expand") }
func BiExport() icons.IsIcon               { return newIcon(regularIcon, "bx-export") }
func BiExtension() icons.IsIcon            { return newIcon(regularIcon, "bx-extension") }
func BiFace() icons.IsIcon                 { return newIcon(regularIcon, "bx-face") }
func BiFastForwardCircle() icons.IsIcon    { return newIcon(regularIcon, "bx-fast-forward-circle") }
func BiFastForward() icons.IsIcon          { return newIcon(regularIcon, "bx-fast-forward") }
func BiFemaleSign() icons.IsIcon           { return newIcon(regularIcon, "bx-female-sign") }
func BiFemale() icons.IsIcon               { return newIcon(regularIcon, "bx-female") }
func BiFileBlank() icons.IsIcon            { return newIcon(regularIcon, "bx-file-blank") }
func BiFileFind() icons.IsIcon             { return newIcon(regularIcon, "bx-file-find") }
func BiFile() icons.IsIcon                 { return newIcon(regularIcon, "bx-file") }
func BiFilm() icons.IsIcon                 { return newIcon(regularIcon, "bx-film") }
func BiFilterAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-filter-alt") }
func BiFilter() icons.IsIcon               { return newIcon(regularIcon, "bx-filter") }
func BiFingerprint() icons.IsIcon          { return newIcon(regularIcon, "bx-fingerprint") }
func BiFirstAid() icons.IsIcon             { return newIcon(regularIcon, "bx-first-aid") }
func BiFirstPage() icons.IsIcon            { return newIcon(regularIcon, "bx-first-page") }
func BiFlag() icons.IsIcon                 { return newIcon(regularIcon, "bx-flag") }
func BiFolderMinus() icons.IsIcon          { return newIcon(regularIcon, "bx-folder-minus") }
func BiFolderOpen() icons.IsIcon           { return newIcon(regularIcon, "bx-folder-open") }
func BiFolderPlus() icons.IsIcon           { return newIcon(regularIcon, "bx-folder-plus") }
func BiFolder() icons.IsIcon               { return newIcon(regularIcon, "bx-folder") }
func BiFontColor() icons.IsIcon            { return newIcon(regularIcon, "bx-font-color") }
func BiFontFamily() icons.IsIcon           { return newIcon(regularIcon, "bx-font-family") }
func BiFontSize() icons.IsIcon             { return newIcon(regularIcon, "bx-font-size") }
func BiFont() icons.IsIcon                 { return newIcon(regularIcon, "bx-font") }
func BiFoodMenu() icons.IsIcon             { return newIcon(regularIcon, "bx-food-menu") }
func BiFoodTag() icons.IsIcon              { return newIcon(regularIcon, "bx-food-tag") }
func BiFootball() icons.IsIcon             { return newIcon(regularIcon, "bx-football") }
func BiFork() icons.IsIcon                 { return newIcon(regularIcon, "bx-fork") }
func BiFridge() icons.IsIcon               { return newIcon(regularIcon, "bx-fridge") }
func BiFullscreen() icons.IsIcon           { return newIcon(regularIcon, "bx-fullscreen") }
func BiGame() icons.IsIcon                 { return newIcon(regularIcon, "bx-game") }
func BiGasPump() icons.IsIcon              { return newIcon(regularIcon, "bx-gas-pump") }
func BiGhost() icons.IsIcon                { return newIcon(regularIcon, "bx-ghost") }
func BiGift() icons.IsIcon                 { return newIcon(regularIcon, "bx-gift") }
func BiGitBranch() icons.IsIcon            { return newIcon(regularIcon, "bx-git-branch") }
func BiGitCommit() icons.IsIcon            { return newIcon(regularIcon, "bx-git-commit") }
func BiGitCompare() icons.IsIcon           { return newIcon(regularIcon, "bx-git-compare") }
func BiGitMerge() icons.IsIcon             { return newIcon(regularIcon, "bx-git-merge") }
func BiGitPullRequest() icons.IsIcon       { return newIcon(regularIcon, "bx-git-pull-request") }
func BiGitRepoForked() icons.IsIcon        { return newIcon(regularIcon, "bx-git-repo-forked") }
func BiGlassesAlt() icons.IsIcon           { return newIcon(regularIcon, "bx-glasses-alt") }
func BiGlasses() icons.IsIcon              { return newIcon(regularIcon, "bx-glasses") }
func BiGlobeAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-globe-alt") }
func BiGlobe() icons.IsIcon                { return newIcon(regularIcon, "bx-globe") }
func BiGridAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-grid-alt") }
func BiGridHorizontal() icons.IsIcon       { return newIcon(regularIcon, "bx-grid-horizontal") }
func BiGridSmall() icons.IsIcon            { return newIcon(regularIcon, "bx-grid-small") }
func BiGridVertical() icons.IsIcon         { return newIcon(regularIcon, "bx-grid-vertical") }
func BiGrid() icons.IsIcon                 { return newIcon(regularIcon, "bx-grid") }
func BiGroup() icons.IsIcon                { return newIcon(regularIcon, "bx-group") }
func BiHandicap() icons.IsIcon             { return newIcon(regularIcon, "bx-handicap") }
func BiHappyAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-happy-alt") }
func BiHappyBeaming() icons.IsIcon         { return newIcon(regularIcon, "bx-happy-beaming") }
func BiHappyHeartEyes() icons.IsIcon       { return newIcon(regularIcon, "bx-happy-heart-eyes") }
func BiHappy() icons.IsIcon                { return newIcon(regularIcon, "bx-happy") }
func BiHardHat() icons.IsIcon              { return newIcon(regularIcon, "bx-hard-hat") }
func BiHash() icons.IsIcon                 { return newIcon(regularIcon, "bx-hash") }
func BiHdd() icons.IsIcon                  { return newIcon(regularIcon, "bx-hdd") }
func BiHeading() icons.IsIcon              { return newIcon(regularIcon, "bx-heading") }
func BiHeadphone() icons.IsIcon            { return newIcon(regularIcon, "bx-headphone") }
func BiHealth() icons.IsIcon               { return newIcon(regularIcon, "bx-health") }
func BiHeartCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-heart-circle") }
func BiHeartSquare() icons.IsIcon          { return newIcon(regularIcon, "bx-heart-square") }
func BiHeart() icons.IsIcon                { return newIcon(regularIcon, "bx-heart") }
func BiHelpCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-help-circle") }
func BiHide() icons.IsIcon                 { return newIcon(regularIcon, "bx-hide") }
func BiHighlight() icons.IsIcon            { return newIcon(regularIcon, "bx-highlight") }
func BiHistory() icons.IsIcon              { return newIcon(regularIcon, "bx-history") }
func BiHive() icons.IsIcon                 { return newIcon(regularIcon, "bx-hive") }
func BiHomeAlt2() icons.IsIcon             { return newIcon(regularIcon, "bx-home-alt-2") }
func BiHomeAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-home-alt") }
func BiHomeCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-home-circle") }
func BiHomeHeart() icons.IsIcon            { return newIcon(regularIcon, "bx-home-heart") }
func BiHomeSmile() icons.IsIcon            { return newIcon(regularIcon, "bx-home-smile") }
func BiHome() icons.IsIcon                 { return newIcon(regularIcon, "bx-home") }
func BiHorizontalCenter() icons.IsIcon     { return newIcon(regularIcon, "bx-horizontal-center") }
func BiHorizontalLeft() icons.IsIcon       { return newIcon(regularIcon, "bx-horizontal-left") }
func BiHorizontalRight() icons.IsIcon      { return newIcon(regularIcon, "bx-horizontal-right") }
func BiHotel() icons.IsIcon                { return newIcon(regularIcon, "bx-hotel") }
func BiHourglass() icons.IsIcon            { return newIcon(regularIcon, "bx-hourglass") }
func BiIdCard() icons.IsIcon               { return newIcon(regularIcon, "bx-id-card") }
func BiImageAdd() icons.IsIcon             { return newIcon(regularIcon, "bx-image-add") }
func BiImageAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-image-alt") }
func BiImage() icons.IsIcon                { return newIcon(regularIcon, "bx-image") }
func BiImages() icons.IsIcon               { return newIcon(regularIcon, "bx-images") }
func BiImport() icons.IsIcon               { return newIcon(regularIcon, "bx-import") }
func BiInfinite() icons.IsIcon             { return newIcon(regularIcon, "bx-infinite") }
func BiInfoCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-info-circle") }
func BiInfoSquare() icons.IsIcon           { return newIcon(regularIcon, "bx-info-square") }
func BiInjection() icons.IsIcon            { return newIcon(regularIcon, "bx-injection") }
func BiIntersect() icons.IsIcon            { return newIcon(regularIcon, "bx-intersect") }
func BiItalic() icons.IsIcon               { return newIcon(regularIcon, "bx-italic") }
func BiJoystickAlt() icons.IsIcon          { return newIcon(regularIcon, "bx-joystick-alt") }
func BiJoystickButton() icons.IsIcon       { return newIcon(regularIcon, "bx-joystick-button") }
func BiJoystick() icons.IsIcon             { return newIcon(regularIcon, "bx-joystick") }
func BiKey() icons.IsIcon                  { return newIcon(regularIcon, "bx-key") }
func BiKnife() icons.IsIcon                { return newIcon(regularIcon, "bx-knife") }
func BiLabel() icons.IsIcon                { return newIcon(regularIcon, "bx-label") }
func BiLandscape() icons.IsIcon            { return newIcon(regularIcon, "bx-landscape") }
func BiLaptop() icons.IsIcon               { return newIcon(regularIcon, "bx-laptop") }
func BiLastPage() icons.IsIcon             { return newIcon(regularIcon, "bx-last-page") }
func BiLaugh() icons.IsIcon                { return newIcon(regularIcon, "bx-laugh") }
func BiLayerMinus() icons.IsIcon           { return newIcon(regularIcon, "bx-layer-minus") }
func BiLayerPlus() icons.IsIcon            { return newIcon(regularIcon, "bx-layer-plus") }
func BiLayer() icons.IsIcon                { return newIcon(regularIcon, "bx-layer") }
func BiLayout() icons.IsIcon               { return newIcon(regularIcon, "bx-layout") }
func BiLeaf() icons.IsIcon                 { return newIcon(regularIcon, "bx-leaf") }
func BiLeftArrowAlt() icons.IsIcon         { return newIcon(regularIcon, "bx-left-arrow-alt") }
func BiLeftArrowCircle() icons.IsIcon      { return newIcon(regularIcon, "bx-left-arrow-circle") }
func BiLeftArrow() icons.IsIcon            { return newIcon(regularIcon, "bx-left-arrow") }
func BiLeftDownArrowCircle() icons.IsIcon  { return newIcon(regularIcon, "bx-left-down-arrow-circle") }
func BiLeftIndent() icons.IsIcon           { return newIcon(regularIcon, "bx-left-indent") }
func BiLeftTopArrowCircle() icons.IsIcon   { return newIcon(regularIcon, "bx-left-top-arrow-circle") }
func BiLemon() icons.IsIcon                { return newIcon(regularIcon, "bx-lemon") }
func BiLibrary() icons.IsIcon              { return newIcon(regularIcon, "bx-library") }
func BiLike() icons.IsIcon                 { return newIcon(regularIcon, "bx-like") }
func BiLineChartDown() icons.IsIcon        { return newIcon(regularIcon, "bx-line-chart-down") }
func BiLineChart() icons.IsIcon            { return newIcon(regularIcon, "bx-line-chart") }
func BiLinkAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-link-alt") }
func BiLinkExternal() icons.IsIcon         { return newIcon(regularIcon, "bx-link-external") }
func BiLink() icons.IsIcon                 { return newIcon(regularIcon, "bx-link") }
func BiLira() icons.IsIcon                 { return newIcon(regularIcon, "bx-lira") }
func BiListCheck() icons.IsIcon            { return newIcon(regularIcon, "bx-list-check") }
func BiListMinus() icons.IsIcon            { return newIcon(regularIcon, "bx-list-minus") }
func BiListOl() icons.IsIcon               { return newIcon(regularIcon, "bx-list-ol") }
func BiListPlus() icons.IsIcon             { return newIcon(regularIcon, "bx-list-plus") }
func BiListUl() icons.IsIcon               { return newIcon(regularIcon, "bx-list-ul") }
func BiLoaderAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-loader-alt") }
func BiLoaderCircle() icons.IsIcon         { return newIcon(regularIcon, "bx-loader-circle") }
func BiLoader() icons.IsIcon               { return newIcon(regularIcon, "bx-loader") }
func BiLocationPlus() icons.IsIcon         { return newIcon(regularIcon, "bx-location-plus") }
func BiLockAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-lock-alt") }
func BiLockOpenAlt() icons.IsIcon          { return newIcon(regularIcon, "bx-lock-open-alt") }
func BiLockOpen() icons.IsIcon             { return newIcon(regularIcon, "bx-lock-open") }
func BiLock() icons.IsIcon                 { return newIcon(regularIcon, "bx-lock") }
func BiLogInCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-log-in-circle") }
func BiLogIn() icons.IsIcon                { return newIcon(regularIcon, "bx-log-in") }
func BiLogOutCircle() icons.IsIcon         { return newIcon(regularIcon, "bx-log-out-circle") }
func BiLogOut() icons.IsIcon               { return newIcon(regularIcon, "bx-log-out") }
func BiLowVision() icons.IsIcon            { return newIcon(regularIcon, "bx-low-vision") }
func BiMagnet() icons.IsIcon               { return newIcon(regularIcon, "bx-magnet") }
func BiMailSend() icons.IsIcon             { return newIcon(regularIcon, "bx-mail-send") }
func BiMaleFemale() icons.IsIcon           { return newIcon(regularIcon, "bx-male-female") }
func BiMaleSign() icons.IsIcon             { return newIcon(regularIcon, "bx-male-sign") }
func BiMale() icons.IsIcon                 { return newIcon(regularIcon, "bx-male") }
func BiMapAlt() icons.IsIcon               { return newIcon(regularIcon, "bx-map-alt") }
func BiMapPin() icons.IsIcon               { return newIcon(regularIcon, "bx-map-pin") }
func BiMap() icons.IsIcon                  { return newIcon(regularIcon, "bx-map") }
func BiMask() icons.IsIcon                 { return newIcon(regularIcon, "bx-mask") }
func BiMath() icons.IsIcon                 { return newIcon(regularIcon, "bx-math") }
func BiMedal() icons.IsIcon                { return newIcon(regularIcon, "bx-medal") }
func BiMehAlt() icons.IsIcon               { return newIcon(regularIcon, "bx-meh-alt") }
func BiMehBlank() icons.IsIcon             { return newIcon(regularIcon, "bx-meh-blank") }
func BiMeh() icons.IsIcon                  { return newIcon(regularIcon, "bx-meh") }
func BiMemoryCard() icons.IsIcon           { return newIcon(regularIcon, "bx-memory-card") }
func BiMenuAltLeft() icons.IsIcon          { return newIcon(regularIcon, "bx-menu-alt-left") }
func BiMenuAltRight() icons.IsIcon         { return newIcon(regularIcon, "bx-menu-alt-right") }
func BiMenu() icons.IsIcon                 { return newIcon(regularIcon, "bx-menu") }
func BiMerge() icons.IsIcon                { return newIcon(regularIcon, "bx-merge") }
func BiMessageAdd() icons.IsIcon           { return newIcon(regularIcon, "bx-message-add") }
func BiMessageAltAdd() icons.IsIcon        { return newIcon(regularIcon, "bx-message-alt-add") }
func BiMessageAltCheck() icons.IsIcon      { return newIcon(regularIcon, "bx-message-alt-check") }
func BiMessageAltDetail() icons.IsIcon     { return newIcon(regularIcon, "bx-message-alt-detail") }
func BiMessageAltDots() icons.IsIcon       { return newIcon(regularIcon, "bx-message-alt-dots") }
func BiMessageAltEdit() icons.IsIcon       { return newIcon(regularIcon, "bx-message-alt-edit") }
func BiMessageAltError() icons.IsIcon      { return newIcon(regularIcon, "bx-message-alt-error") }
func BiMessageAltMinus() icons.IsIcon      { return newIcon(regularIcon, "bx-message-alt-minus") }
func BiMessageAltX() icons.IsIcon          { return newIcon(regularIcon, "bx-message-alt-x") }
func BiMessageAlt() icons.IsIcon           { return newIcon(regularIcon, "bx-message-alt") }
func BiMessageCheck() icons.IsIcon         { return newIcon(regularIcon, "bx-message-check") }
func BiMessageDetail() icons.IsIcon        { return newIcon(regularIcon, "bx-message-detail") }
func BiMessageDots() icons.IsIcon          { return newIcon(regularIcon, "bx-message-dots") }
func BiMessageEdit() icons.IsIcon          { return newIcon(regularIcon, "bx-message-edit") }
func BiMessageError() icons.IsIcon         { return newIcon(regularIcon, "bx-message-error") }
func BiMessageMinus() icons.IsIcon         { return newIcon(regularIcon, "bx-message-minus") }
func BiMessageRoundedAdd() icons.IsIcon    { return newIcon(regularIcon, "bx-message-rounded-add") }
func BiMessageRoundedCheck() icons.IsIcon  { return newIcon(regularIcon, "bx-message-rounded-check") }
func BiMessageRoundedDetail() icons.IsIcon { return newIcon(regularIcon, "bx-message-rounded-detail") }
func BiMessageRoundedDots() icons.IsIcon   { return newIcon(regularIcon, "bx-message-rounded-dots") }
func BiMessageRoundedEdit() icons.IsIcon   { return newIcon(regularIcon, "bx-message-rounded-edit") }
func BiMessageRoundedError() icons.IsIcon  { return newIcon(regularIcon, "bx-message-rounded-error") }
func BiMessageRoundedMinus() icons.IsIcon  { return newIcon(regularIcon, "bx-message-rounded-minus") }
func BiMessageRoundedX() icons.IsIcon      { return newIcon(regularIcon, "bx-message-rounded-x") }
func BiMessageRounded() icons.IsIcon       { return newIcon(regularIcon, "bx-message-rounded") }
func BiMessageSquareAdd() icons.IsIcon     { return newIcon(regularIcon, "bx-message-square-add") }
func BiMessageSquareCheck() icons.IsIcon   { return newIcon(regularIcon, "bx-message-square-check") }
func BiMessageSquareDetail() icons.IsIcon  { return newIcon(regularIcon, "bx-message-square-detail") }
func BiMessageSquareDots() icons.IsIcon    { return newIcon(regularIcon, "bx-message-square-dots") }
func BiMessageSquareEdit() icons.IsIcon    { return newIcon(regularIcon, "bx-message-square-edit") }
func BiMessageSquareError() icons.IsIcon   { return newIcon(regularIcon, "bx-message-square-error") }
func BiMessageSquareMinus() icons.IsIcon   { return newIcon(regularIcon, "bx-message-square-minus") }
func BiMessageSquareX() icons.IsIcon       { return newIcon(regularIcon, "bx-message-square-x") }
func BiMessageSquare() icons.IsIcon        { return newIcon(regularIcon, "bx-message-square") }
func BiMessageX() icons.IsIcon             { return newIcon(regularIcon, "bx-message-x") }
func BiMessage() icons.IsIcon              { return newIcon(regularIcon, "bx-message") }
func BiMeteor() icons.IsIcon               { return newIcon(regularIcon, "bx-meteor") }
func BiMicrochip() icons.IsIcon            { return newIcon(regularIcon, "bx-microchip") }
func BiMicrophoneOff() icons.IsIcon        { return newIcon(regularIcon, "bx-microphone-off") }
func BiMicrophone() icons.IsIcon           { return newIcon(regularIcon, "bx-microphone") }
func BiMinusBack() icons.IsIcon            { return newIcon(regularIcon, "bx-minus-back") }
func BiMinusCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-minus-circle") }
func BiMinusFront() icons.IsIcon           { return newIcon(regularIcon, "bx-minus-front") }
func BiMinus() icons.IsIcon                { return newIcon(regularIcon, "bx-minus") }
func BiMobileAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-mobile-alt") }
func BiMobileLandscape() icons.IsIcon      { return newIcon(regularIcon, "bx-mobile-landscape") }
func BiMobileVibration() icons.IsIcon      { return newIcon(regularIcon, "bx-mobile-vibration") }
func BiMobile() icons.IsIcon               { return newIcon(regularIcon, "bx-mobile") }
func BiMoneyWithdraw() icons.IsIcon        { return newIcon(regularIcon, "bx-money-withdraw") }
func BiMoney() icons.IsIcon                { return newIcon(regularIcon, "bx-money") }
func BiMoon() icons.IsIcon                 { return newIcon(regularIcon, "bx-moon") }
func BiMouseAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-mouse-alt") }
func BiMouse() icons.IsIcon                { return newIcon(regularIcon, "bx-mouse") }
func BiMoveHorizontal() icons.IsIcon       { return newIcon(regularIcon, "bx-move-horizontal") }
func BiMoveVertical() icons.IsIcon         { return newIcon(regularIcon, "bx-move-vertical") }
func BiMove() icons.IsIcon                 { return newIcon(regularIcon, "bx-move") }
func BiMoviePlay() icons.IsIcon            { return newIcon(regularIcon, "bx-movie-play") }
func BiMovie() icons.IsIcon                { return newIcon(regularIcon, "bx-movie") }
func BiMusic() icons.IsIcon                { return newIcon(regularIcon, "bx-music") }
func BiNavigation() icons.IsIcon           { return newIcon(regularIcon, "bx-navigation") }
func BiNetworkChart() icons.IsIcon         { return newIcon(regularIcon, "bx-network-chart") }
func BiNews() icons.IsIcon                 { return newIcon(regularIcon, "bx-news") }
func BiNoEntry() icons.IsIcon              { return newIcon(regularIcon, "bx-no-entry") }
func BiNoSignal() icons.IsIcon             { return newIcon(regularIcon, "bx-no-signal") }
func BiNote() icons.IsIcon                 { return newIcon(regularIcon, "bx-note") }
func BiNotepad() icons.IsIcon              { return newIcon(regularIcon, "bx-notepad") }
func BiNotificationOff() icons.IsIcon      { return newIcon(regularIcon, "bx-notification-off") }
func BiNotification() icons.IsIcon         { return newIcon(regularIcon, "bx-notification") }
func BiObjectsHorizontalCenter() icons.IsIcon {
	return newIcon(regularIcon, "bx-objects-horizontal-center")
}
func BiObjectsHorizontalLeft() icons.IsIcon {
	return newIcon(regularIcon, "bx-objects-horizontal-left")
}
func BiObjectsHorizontalRight() icons.IsIcon {
	return newIcon(regularIcon, "bx-objects-horizontal-right")
}
func BiObjectsVerticalBottom() icons.IsIcon {
	return newIcon(regularIcon, "bx-objects-vertical-bottom")
}
func BiObjectsVerticalCenter() icons.IsIcon {
	return newIcon(regularIcon, "bx-objects-vertical-center")
}
func BiObjectsVerticalTop() icons.IsIcon   { return newIcon(regularIcon, "bx-objects-vertical-top") }
func BiOutline() icons.IsIcon              { return newIcon(regularIcon, "bx-outline") }
func BiPackage() icons.IsIcon              { return newIcon(regularIcon, "bx-package") }
func BiPaintRoll() icons.IsIcon            { return newIcon(regularIcon, "bx-paint-roll") }
func BiPaint() icons.IsIcon                { return newIcon(regularIcon, "bx-paint") }
func BiPalette() icons.IsIcon              { return newIcon(regularIcon, "bx-palette") }
func BiPaperPlane() icons.IsIcon           { return newIcon(regularIcon, "bx-paper-plane") }
func BiPaperclip() icons.IsIcon            { return newIcon(regularIcon, "bx-paperclip") }
func BiParagraph() icons.IsIcon            { return newIcon(regularIcon, "bx-paragraph") }
func BiParty() icons.IsIcon                { return newIcon(regularIcon, "bx-party") }
func BiPaste() icons.IsIcon                { return newIcon(regularIcon, "bx-paste") }
func BiPauseCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-pause-circle") }
func BiPause() icons.IsIcon                { return newIcon(regularIcon, "bx-pause") }
func BiPen() icons.IsIcon                  { return newIcon(regularIcon, "bx-pen") }
func BiPencil() icons.IsIcon               { return newIcon(regularIcon, "bx-pencil") }
func BiPhoneCall() icons.IsIcon            { return newIcon(regularIcon, "bx-phone-call") }
func BiPhoneIncoming() icons.IsIcon        { return newIcon(regularIcon, "bx-phone-incoming") }
func BiPhoneOff() icons.IsIcon             { return newIcon(regularIcon, "bx-phone-off") }
func BiPhoneOutgoing() icons.IsIcon        { return newIcon(regularIcon, "bx-phone-outgoing") }
func BiPhone() icons.IsIcon                { return newIcon(regularIcon, "bx-phone") }
func BiPhotoAlbum() icons.IsIcon           { return newIcon(regularIcon, "bx-photo-album") }
func BiPieChartAlt2() icons.IsIcon         { return newIcon(regularIcon, "bx-pie-chart-alt-2") }
func BiPieChartAlt() icons.IsIcon          { return newIcon(regularIcon, "bx-pie-chart-alt") }
func BiPieChart() icons.IsIcon             { return newIcon(regularIcon, "bx-pie-chart") }
func BiPin() icons.IsIcon                  { return newIcon(regularIcon, "bx-pin") }
func BiPlanet() icons.IsIcon               { return newIcon(regularIcon, "bx-planet") }
func BiPlayCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-play-circle") }
func BiPlay() icons.IsIcon                 { return newIcon(regularIcon, "bx-play") }
func BiPlug() icons.IsIcon                 { return newIcon(regularIcon, "bx-plug") }
func BiPlusCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-plus-circle") }
func BiPlusMedical() icons.IsIcon          { return newIcon(regularIcon, "bx-plus-medical") }
func BiPlus() icons.IsIcon                 { return newIcon(regularIcon, "bx-plus") }
func BiPodcast() icons.IsIcon              { return newIcon(regularIcon, "bx-podcast") }
func BiPointer() icons.IsIcon              { return newIcon(regularIcon, "bx-pointer") }
func BiPoll() icons.IsIcon                 { return newIcon(regularIcon, "bx-poll") }
func BiPolygon() icons.IsIcon              { return newIcon(regularIcon, "bx-polygon") }
func BiPopsicle() icons.IsIcon             { return newIcon(regularIcon, "bx-popsicle") }
func BiPound() icons.IsIcon                { return newIcon(regularIcon, "bx-pound") }
func BiPowerOff() icons.IsIcon             { return newIcon(regularIcon, "bx-power-off") }
func BiPrinter() icons.IsIcon              { return newIcon(regularIcon, "bx-printer") }
func BiPulse() icons.IsIcon                { return newIcon(regularIcon, "bx-pulse") }
func BiPurchaseTagAlt() icons.IsIcon       { return newIcon(regularIcon, "bx-purchase-tag-alt") }
func BiPurchaseTag() icons.IsIcon          { return newIcon(regularIcon, "bx-purchase-tag") }
func BiPyramid() icons.IsIcon              { return newIcon(regularIcon, "bx-pyramid") }
func BiQrScan() icons.IsIcon               { return newIcon(regularIcon, "bx-qr-scan") }
func BiQr() icons.IsIcon                   { return newIcon(regularIcon, "bx-qr") }
func BiQuestionMark() icons.IsIcon         { return newIcon(regularIcon, "bx-question-mark") }
func BiRadar() icons.IsIcon                { return newIcon(regularIcon, "bx-radar") }
func BiRadioCircleMarked() icons.IsIcon    { return newIcon(regularIcon, "bx-radio-circle-marked") }
func BiRadioCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-radio-circle") }
func BiRadio() icons.IsIcon                { return newIcon(regularIcon, "bx-radio") }
func BiReceipt() icons.IsIcon              { return newIcon(regularIcon, "bx-receipt") }
func BiRectangle() icons.IsIcon            { return newIcon(regularIcon, "bx-rectangle") }
func BiRecycle() icons.IsIcon              { return newIcon(regularIcon, "bx-recycle") }
func BiRedo() icons.IsIcon                 { return newIcon(regularIcon, "bx-redo") }
func BiReflectHorizontal() icons.IsIcon    { return newIcon(regularIcon, "bx-reflect-horizontal") }
func BiReflectVertical() icons.IsIcon      { return newIcon(regularIcon, "bx-reflect-vertical") }
func BiRefresh() icons.IsIcon              { return newIcon(regularIcon, "bx-refresh") }
func BiRegistered() icons.IsIcon           { return newIcon(regularIcon, "bx-registered") }
func BiRename() icons.IsIcon               { return newIcon(regularIcon, "bx-rename") }
func BiRepeat() icons.IsIcon               { return newIcon(regularIcon, "bx-repeat") }
func BiReplyAll() icons.IsIcon             { return newIcon(regularIcon, "bx-reply-all") }
func BiReply() icons.IsIcon                { return newIcon(regularIcon, "bx-reply") }
func BiRepost() icons.IsIcon               { return newIcon(regularIcon, "bx-repost") }
func BiReset() icons.IsIcon                { return newIcon(regularIcon, "bx-reset") }
func BiRestaurant() icons.IsIcon           { return newIcon(regularIcon, "bx-restaurant") }
func BiRevision() icons.IsIcon             { return newIcon(regularIcon, "bx-revision") }
func BiRewindCircle() icons.IsIcon         { return newIcon(regularIcon, "bx-rewind-circle") }
func BiRewind() icons.IsIcon               { return newIcon(regularIcon, "bx-rewind") }
func BiRfid() icons.IsIcon                 { return newIcon(regularIcon, "bx-rfid") }
func BiRightArrowAlt() icons.IsIcon        { return newIcon(regularIcon, "bx-right-arrow-alt") }
func BiRightArrowCircle() icons.IsIcon     { return newIcon(regularIcon, "bx-right-arrow-circle") }
func BiRightArrow() icons.IsIcon           { return newIcon(regularIcon, "bx-right-arrow") }
func BiRightDownArrowCircle() icons.IsIcon { return newIcon(regularIcon, "bx-right-down-arrow-circle") }
func BiRightIndent() icons.IsIcon          { return newIcon(regularIcon, "bx-right-indent") }
func BiRightTopArrowCircle() icons.IsIcon  { return newIcon(regularIcon, "bx-right-top-arrow-circle") }
func BiRocket() icons.IsIcon               { return newIcon(regularIcon, "bx-rocket") }
func BiRotateLeft() icons.IsIcon           { return newIcon(regularIcon, "bx-rotate-left") }
func BiRotateRight() icons.IsIcon          { return newIcon(regularIcon, "bx-rotate-right") }
func BiRss() icons.IsIcon                  { return newIcon(regularIcon, "bx-rss") }
func BiRuble() icons.IsIcon                { return newIcon(regularIcon, "bx-ruble") }
func BiRuler() icons.IsIcon                { return newIcon(regularIcon, "bx-ruler") }
func BiRun() icons.IsIcon                  { return newIcon(regularIcon, "bx-run") }
func BiRupee() icons.IsIcon                { return newIcon(regularIcon, "bx-rupee") }
func BiSad() icons.IsIcon                  { return newIcon(regularIcon, "bx-sad") }
func BiSave() icons.IsIcon                 { return newIcon(regularIcon, "bx-save") }
func BiScan() icons.IsIcon                 { return newIcon(regularIcon, "bx-scan") }
func BiScatterChart() icons.IsIcon         { return newIcon(regularIcon, "bx-scatter-chart") }
func BiScreenshot() icons.IsIcon           { return newIcon(regularIcon, "bx-screenshot") }
func BiSearchAlt2() icons.IsIcon           { return newIcon(regularIcon, "bx-search-alt-2") }
func BiSearchAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-search-alt") }
func BiSearch() icons.IsIcon               { return newIcon(regularIcon, "bx-search") }
func BiSelectMultiple() icons.IsIcon       { return newIcon(regularIcon, "bx-select-multiple") }
func BiSelection() icons.IsIcon            { return newIcon(regularIcon, "bx-selection") }
func BiSend() icons.IsIcon                 { return newIcon(regularIcon, "bx-send") }
func BiServer() icons.IsIcon               { return newIcon(regularIcon, "bx-server") }
func BiShapeCircle() icons.IsIcon          { return newIcon(regularIcon, "bx-shape-circle") }
func BiShapePolygon() icons.IsIcon         { return newIcon(regularIcon, "bx-shape-polygon") }
func BiShapeSquare() icons.IsIcon          { return newIcon(regularIcon, "bx-shape-square") }
func BiShapeTriangle() icons.IsIcon        { return newIcon(regularIcon, "bx-shape-triangle") }
func BiShareAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-share-alt") }
func BiShare() icons.IsIcon                { return newIcon(regularIcon, "bx-share") }
func BiShekel() icons.IsIcon               { return newIcon(regularIcon, "bx-shekel") }
func BiShieldAlt2() icons.IsIcon           { return newIcon(regularIcon, "bx-shield-alt-2") }
func BiShieldAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-shield-alt") }
func BiShieldMinus() icons.IsIcon          { return newIcon(regularIcon, "bx-shield-minus") }
func BiShieldPlus() icons.IsIcon           { return newIcon(regularIcon, "bx-shield-plus") }
func BiShieldQuarter() icons.IsIcon        { return newIcon(regularIcon, "bx-shield-quarter") }
func BiShieldX() icons.IsIcon              { return newIcon(regularIcon, "bx-shield-x") }
func BiShield() icons.IsIcon               { return newIcon(regularIcon, "bx-shield") }
func BiShocked() icons.IsIcon              { return newIcon(regularIcon, "bx-shocked") }
func BiShoppingBag() icons.IsIcon          { return newIcon(regularIcon, "bx-shopping-bag") }
func BiShowAlt() icons.IsIcon              { return newIcon(regularIcon, "bx-show-alt") }
func BiShow() icons.IsIcon                 { return newIcon(regularIcon, "bx-show") }
func BiShower() icons.IsIcon               { return newIcon(regularIcon, "bx-shower") }
func BiShuffle() icons.IsIcon              { return newIcon(regularIcon, "bx-shuffle") }
func BiSidebar() icons.IsIcon              { return newIcon(regularIcon, "bx-sidebar") }
func BiSignal1() icons.IsIcon              { return newIcon(regularIcon, "bx-signal-1") }
func BiSignal2() icons.IsIcon              { return newIcon(regularIcon, "bx-signal-2") }
func BiSignal3() icons.IsIcon              { return newIcon(regularIcon, "bx-signal-3") }
func BiSignal4() icons.IsIcon              { return newIcon(regularIcon, "bx-signal-4") }
func BiSignal5() icons.IsIcon              { return newIcon(regularIcon, "bx-signal-5") }
func BiSitemap() icons.IsIcon              { return newIcon(regularIcon, "bx-sitemap") }
func BiSkipNextCircle() icons.IsIcon       { return newIcon(regularIcon, "bx-skip-next-circle") }
func BiSkipNext() icons.IsIcon             { return newIcon(regularIcon, "bx-skip-next") }
func BiSkipPreviousCircle() icons.IsIcon   { return newIcon(regularIcon, "bx-skip-previous-circle") }
func BiSkipPrevious() icons.IsIcon         { return newIcon(regularIcon, "bx-skip-previous") }
func BiSleepy() icons.IsIcon               { return newIcon(regularIcon, "bx-sleepy") }
func BiSliderAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-slider-alt") }
func BiSlider() icons.IsIcon               { return newIcon(regularIcon, "bx-slider") }
func BiSlideshow() icons.IsIcon            { return newIcon(regularIcon, "bx-slideshow") }
func BiSmile() icons.IsIcon                { return newIcon(regularIcon, "bx-smile") }
func BiSortAZ() icons.IsIcon               { return newIcon(regularIcon, "bx-sort-a-z") }
func BiSortAlt2() icons.IsIcon             { return newIcon(regularIcon, "bx-sort-alt-2") }
func BiSortDown() icons.IsIcon             { return newIcon(regularIcon, "bx-sort-down") }
func BiSortUp() icons.IsIcon               { return newIcon(regularIcon, "bx-sort-up") }
func BiSortZA() icons.IsIcon               { return newIcon(regularIcon, "bx-sort-z-a") }
func BiSort() icons.IsIcon                 { return newIcon(regularIcon, "bx-sort") }
func BiSpa() icons.IsIcon                  { return newIcon(regularIcon, "bx-spa") }
func BiSpaceBar() icons.IsIcon             { return newIcon(regularIcon, "bx-space-bar") }
func BiSpeaker() icons.IsIcon              { return newIcon(regularIcon, "bx-speaker") }
func BiSprayCan() icons.IsIcon             { return newIcon(regularIcon, "bx-spray-can") }
func BiSpreadsheet() icons.IsIcon          { return newIcon(regularIcon, "bx-spreadsheet") }
func BiSquareRounded() icons.IsIcon        { return newIcon(regularIcon, "bx-square-rounded") }
func BiSquare() icons.IsIcon               { return newIcon(regularIcon, "bx-square") }
func BiStar() icons.IsIcon                 { return newIcon(regularIcon, "bx-star") }
func BiStation() icons.IsIcon              { return newIcon(regularIcon, "bx-station") }
func BiStats() icons.IsIcon                { return newIcon(regularIcon, "bx-stats") }
func BiSticker() icons.IsIcon              { return newIcon(regularIcon, "bx-sticker") }
func BiStopCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-stop-circle") }
func BiStop() icons.IsIcon                 { return newIcon(regularIcon, "bx-stop") }
func BiStopwatch() icons.IsIcon            { return newIcon(regularIcon, "bx-stopwatch") }
func BiStoreAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-store-alt") }
func BiStore() icons.IsIcon                { return newIcon(regularIcon, "bx-store") }
func BiStreetView() icons.IsIcon           { return newIcon(regularIcon, "bx-street-view") }
func BiStrikethrough() icons.IsIcon        { return newIcon(regularIcon, "bx-strikethrough") }
func BiSubdirectoryLeft() icons.IsIcon     { return newIcon(regularIcon, "bx-subdirectory-left") }
func BiSubdirectoryRight() icons.IsIcon    { return newIcon(regularIcon, "bx-subdirectory-right") }
func BiSun() icons.IsIcon                  { return newIcon(regularIcon, "bx-sun") }
func BiSupport() icons.IsIcon              { return newIcon(regularIcon, "bx-support") }
func BiSushi() icons.IsIcon                { return newIcon(regularIcon, "bx-sushi") }
func BiSwim() icons.IsIcon                 { return newIcon(regularIcon, "bx-swim") }
func BiSync() icons.IsIcon                 { return newIcon(regularIcon, "bx-sync") }
func BiTab() icons.IsIcon                  { return newIcon(regularIcon, "bx-tab") }
func BiTable() icons.IsIcon                { return newIcon(regularIcon, "bx-table") }
func BiTachometer() icons.IsIcon           { return newIcon(regularIcon, "bx-tachometer") }
func BiTagAlt() icons.IsIcon               { return newIcon(regularIcon, "bx-tag-alt") }
func BiTag() icons.IsIcon                  { return newIcon(regularIcon, "bx-tag") }
func BiTargetLock() icons.IsIcon           { return newIcon(regularIcon, "bx-target-lock") }
func BiTaskX() icons.IsIcon                { return newIcon(regularIcon, "bx-task-x") }
func BiTask() icons.IsIcon                 { return newIcon(regularIcon, "bx-task") }
func BiTaxi() icons.IsIcon                 { return newIcon(regularIcon, "bx-taxi") }
func BiTennisBall() icons.IsIcon           { return newIcon(regularIcon, "bx-tennis-ball") }
func BiTerminal() icons.IsIcon             { return newIcon(regularIcon, "bx-terminal") }
func BiTestTube() icons.IsIcon             { return newIcon(regularIcon, "bx-test-tube") }
func BiText() icons.IsIcon                 { return newIcon(regularIcon, "bx-text") }
func BiTimeFive() icons.IsIcon             { return newIcon(regularIcon, "bx-time-five") }
func BiTime() icons.IsIcon                 { return newIcon(regularIcon, "bx-time") }
func BiTimer() icons.IsIcon                { return newIcon(regularIcon, "bx-timer") }
func BiTired() icons.IsIcon                { return newIcon(regularIcon, "bx-tired") }
func BiToggleLeft() icons.IsIcon           { return newIcon(regularIcon, "bx-toggle-left") }
func BiToggleRight() icons.IsIcon          { return newIcon(regularIcon, "bx-toggle-right") }
func BiTone() icons.IsIcon                 { return newIcon(regularIcon, "bx-tone") }
func BiTrafficCone() icons.IsIcon          { return newIcon(regularIcon, "bx-traffic-cone") }
func BiTrain() icons.IsIcon                { return newIcon(regularIcon, "bx-train") }
func BiTransferAlt() icons.IsIcon          { return newIcon(regularIcon, "bx-transfer-alt") }
func BiTransfer() icons.IsIcon             { return newIcon(regularIcon, "bx-transfer") }
func BiTrashAlt() icons.IsIcon             { return newIcon(regularIcon, "bx-trash-alt") }
func BiTrash() icons.IsIcon                { return newIcon(regularIcon, "bx-trash") }
func BiTrendingDown() icons.IsIcon         { return newIcon(regularIcon, "bx-trending-down") }
func BiTrendingUp() icons.IsIcon           { return newIcon(regularIcon, "bx-trending-up") }
func BiTrim() icons.IsIcon                 { return newIcon(regularIcon, "bx-trim") }
func BiTrip() icons.IsIcon                 { return newIcon(regularIcon, "bx-trip") }
func BiTrophy() icons.IsIcon               { return newIcon(regularIcon, "bx-trophy") }
func BiTv() icons.IsIcon                   { return newIcon(regularIcon, "bx-tv") }
func BiUnderline() icons.IsIcon            { return newIcon(regularIcon, "bx-underline") }
func BiUndo() icons.IsIcon                 { return newIcon(regularIcon, "bx-undo") }
func BiUnite() icons.IsIcon                { return newIcon(regularIcon, "bx-unite") }
func BiUniversalAccess() icons.IsIcon      { return newIcon(regularIcon, "bx-universal-access") }
func BiUnlink() icons.IsIcon               { return newIcon(regularIcon, "bx-unlink") }
func BiUpArrowAlt() icons.IsIcon           { return newIcon(regularIcon, "bx-up-arrow-alt") }
func BiUpArrowCircle() icons.IsIcon        { return newIcon(regularIcon, "bx-up-arrow-circle") }
func BiUpArrow() icons.IsIcon              { return newIcon(regularIcon, "bx-up-arrow") }
func BiUpload() icons.IsIcon               { return newIcon(regularIcon, "bx-upload") }
func BiUpsideDown() icons.IsIcon           { return newIcon(regularIcon, "bx-upside-down") }
func BiUpvote() icons.IsIcon               { return newIcon(regularIcon, "bx-upvote") }
func BiUsb() icons.IsIcon                  { return newIcon(regularIcon, "bx-usb") }
func BiUserCheck() icons.IsIcon            { return newIcon(regularIcon, "bx-user-check") }
func BiUserCircle() icons.IsIcon           { return newIcon(regularIcon, "bx-user-circle") }
func BiUserMinus() icons.IsIcon            { return newIcon(regularIcon, "bx-user-minus") }
func BiUserPin() icons.IsIcon              { return newIcon(regularIcon, "bx-user-pin") }
func BiUserPlus() icons.IsIcon             { return newIcon(regularIcon, "bx-user-plus") }
func BiUserVoice() icons.IsIcon            { return newIcon(regularIcon, "bx-user-voice") }
func BiUserX() icons.IsIcon                { return newIcon(regularIcon, "bx-user-x") }
func BiUser() icons.IsIcon                 { return newIcon(regularIcon, "bx-user") }
func BiVector() icons.IsIcon               { return newIcon(regularIcon, "bx-vector") }
func BiVerticalBottom() icons.IsIcon       { return newIcon(regularIcon, "bx-vertical-bottom") }
func BiVerticalCenter() icons.IsIcon       { return newIcon(regularIcon, "bx-vertical-center") }
func BiVerticalTop() icons.IsIcon          { return newIcon(regularIcon, "bx-vertical-top") }
func BiVial() icons.IsIcon                 { return newIcon(regularIcon, "bx-vial") }
func BiVideoOff() icons.IsIcon             { return newIcon(regularIcon, "bx-video-off") }
func BiVideoPlus() icons.IsIcon            { return newIcon(regularIcon, "bx-video-plus") }
func BiVideoRecording() icons.IsIcon       { return newIcon(regularIcon, "bx-video-recording") }
func BiVideo() icons.IsIcon                { return newIcon(regularIcon, "bx-video") }
func BiVoicemail() icons.IsIcon            { return newIcon(regularIcon, "bx-voicemail") }
func BiVolumeFull() icons.IsIcon           { return newIcon(regularIcon, "bx-volume-full") }
func BiVolumeLow() icons.IsIcon            { return newIcon(regularIcon, "bx-volume-low") }
func BiVolumeMute() icons.IsIcon           { return newIcon(regularIcon, "bx-volume-mute") }
func BiVolume() icons.IsIcon               { return newIcon(regularIcon, "bx-volume") }
func BiWalk() icons.IsIcon                 { return newIcon(regularIcon, "bx-walk") }
func BiWalletAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-wallet-alt") }
func BiWallet() icons.IsIcon               { return newIcon(regularIcon, "bx-wallet") }
func BiWater() icons.IsIcon                { return newIcon(regularIcon, "bx-water") }
func BiWebcam() icons.IsIcon               { return newIcon(regularIcon, "bx-webcam") }
func BiWifi0() icons.IsIcon                { return newIcon(regularIcon, "bx-wifi-0") }
func BiWifi1() icons.IsIcon                { return newIcon(regularIcon, "bx-wifi-1") }
func BiWifi2() icons.IsIcon                { return newIcon(regularIcon, "bx-wifi-2") }
func BiWifiOff() icons.IsIcon              { return newIcon(regularIcon, "bx-wifi-off") }
func BiWifi() icons.IsIcon                 { return newIcon(regularIcon, "bx-wifi") }
func BiWind() icons.IsIcon                 { return newIcon(regularIcon, "bx-wind") }
func BiWindowAlt() icons.IsIcon            { return newIcon(regularIcon, "bx-window-alt") }
func BiWindowClose() icons.IsIcon          { return newIcon(regularIcon, "bx-window-close") }
func BiWindowOpen() icons.IsIcon           { return newIcon(regularIcon, "bx-window-open") }
func BiWindow() icons.IsIcon               { return newIcon(regularIcon, "bx-window") }
func BiWindows() icons.IsIcon              { return newIcon(regularIcon, "bx-windows") }
func BiWine() icons.IsIcon                 { return newIcon(regularIcon, "bx-wine") }
func BiWinkSmile() icons.IsIcon            { return newIcon(regularIcon, "bx-wink-smile") }
func BiWinkTongue() icons.IsIcon           { return newIcon(regularIcon, "bx-wink-tongue") }
func BiWon() icons.IsIcon                  { return newIcon(regularIcon, "bx-won") }
func BiWorld() icons.IsIcon                { return newIcon(regularIcon, "bx-world") }
func BiWrench() icons.IsIcon               { return newIcon(regularIcon, "bx-wrench") }
func BiXCircle() icons.IsIcon              { return newIcon(regularIcon, "bx-x-circle") }
func BiX() icons.IsIcon                    { return newIcon(regularIcon, "bx-x") }
func BiYen() icons.IsIcon                  { return newIcon(regularIcon, "bx-yen") }
func BiZoomIn() icons.IsIcon               { return newIcon(regularIcon, "bx-zoom-in") }
func BiZoomOut() icons.IsIcon              { return newIcon(regularIcon, "bx-zoom-out") }
