package bi

import "github.com/raitucarp/gomix/icons"

func BiSolidAddToQueue() icons.IsIcon          { return newIcon(solidIcon, "bxs-add-to-queue") }
func BiSolidAdjustAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-adjust-alt") }
func BiSolidAdjust() icons.IsIcon              { return newIcon(solidIcon, "bxs-adjust") }
func BiSolidAlarmAdd() icons.IsIcon            { return newIcon(solidIcon, "bxs-alarm-add") }
func BiSolidAlarmExclamation() icons.IsIcon    { return newIcon(solidIcon, "bxs-alarm-exclamation") }
func BiSolidAlarmOff() icons.IsIcon            { return newIcon(solidIcon, "bxs-alarm-off") }
func BiSolidAlarmSnooze() icons.IsIcon         { return newIcon(solidIcon, "bxs-alarm-snooze") }
func BiSolidAlarm() icons.IsIcon               { return newIcon(solidIcon, "bxs-alarm") }
func BiSolidAlbum() icons.IsIcon               { return newIcon(solidIcon, "bxs-album") }
func BiSolidAmbulance() icons.IsIcon           { return newIcon(solidIcon, "bxs-ambulance") }
func BiSolidAnalyse() icons.IsIcon             { return newIcon(solidIcon, "bxs-analyse") }
func BiSolidAngry() icons.IsIcon               { return newIcon(solidIcon, "bxs-angry") }
func BiSolidArch() icons.IsIcon                { return newIcon(solidIcon, "bxs-arch") }
func BiSolidArchiveIn() icons.IsIcon           { return newIcon(solidIcon, "bxs-archive-in") }
func BiSolidArchiveOut() icons.IsIcon          { return newIcon(solidIcon, "bxs-archive-out") }
func BiSolidArchive() icons.IsIcon             { return newIcon(solidIcon, "bxs-archive") }
func BiSolidArea() icons.IsIcon                { return newIcon(solidIcon, "bxs-area") }
func BiSolidArrowFromBottom() icons.IsIcon     { return newIcon(solidIcon, "bxs-arrow-from-bottom") }
func BiSolidArrowFromLeft() icons.IsIcon       { return newIcon(solidIcon, "bxs-arrow-from-left") }
func BiSolidArrowFromRight() icons.IsIcon      { return newIcon(solidIcon, "bxs-arrow-from-right") }
func BiSolidArrowFromTop() icons.IsIcon        { return newIcon(solidIcon, "bxs-arrow-from-top") }
func BiSolidArrowToBottom() icons.IsIcon       { return newIcon(solidIcon, "bxs-arrow-to-bottom") }
func BiSolidArrowToLeft() icons.IsIcon         { return newIcon(solidIcon, "bxs-arrow-to-left") }
func BiSolidArrowToRight() icons.IsIcon        { return newIcon(solidIcon, "bxs-arrow-to-right") }
func BiSolidArrowToTop() icons.IsIcon          { return newIcon(solidIcon, "bxs-arrow-to-top") }
func BiSolidAward() icons.IsIcon               { return newIcon(solidIcon, "bxs-award") }
func BiSolidBabyCarriage() icons.IsIcon        { return newIcon(solidIcon, "bxs-baby-carriage") }
func BiSolidBackpack() icons.IsIcon            { return newIcon(solidIcon, "bxs-backpack") }
func BiSolidBadgeCheck() icons.IsIcon          { return newIcon(solidIcon, "bxs-badge-check") }
func BiSolidBadgeDollar() icons.IsIcon         { return newIcon(solidIcon, "bxs-badge-dollar") }
func BiSolidBadge() icons.IsIcon               { return newIcon(solidIcon, "bxs-badge") }
func BiSolidBaguette() icons.IsIcon            { return newIcon(solidIcon, "bxs-baguette") }
func BiSolidBall() icons.IsIcon                { return newIcon(solidIcon, "bxs-ball") }
func BiSolidBalloon() icons.IsIcon             { return newIcon(solidIcon, "bxs-balloon") }
func BiSolidBandAid() icons.IsIcon             { return newIcon(solidIcon, "bxs-band-aid") }
func BiSolidBank() icons.IsIcon                { return newIcon(solidIcon, "bxs-bank") }
func BiSolidBarChartAlt2() icons.IsIcon        { return newIcon(solidIcon, "bxs-bar-chart-alt-2") }
func BiSolidBarChartSquare() icons.IsIcon      { return newIcon(solidIcon, "bxs-bar-chart-square") }
func BiSolidBarcode() icons.IsIcon             { return newIcon(solidIcon, "bxs-barcode") }
func BiSolidBaseball() icons.IsIcon            { return newIcon(solidIcon, "bxs-baseball") }
func BiSolidBasket() icons.IsIcon              { return newIcon(solidIcon, "bxs-basket") }
func BiSolidBasketball() icons.IsIcon          { return newIcon(solidIcon, "bxs-basketball") }
func BiSolidBath() icons.IsIcon                { return newIcon(solidIcon, "bxs-bath") }
func BiSolidBatteryCharging() icons.IsIcon     { return newIcon(solidIcon, "bxs-battery-charging") }
func BiSolidBatteryFull() icons.IsIcon         { return newIcon(solidIcon, "bxs-battery-full") }
func BiSolidBatteryLow() icons.IsIcon          { return newIcon(solidIcon, "bxs-battery-low") }
func BiSolidBattery() icons.IsIcon             { return newIcon(solidIcon, "bxs-battery") }
func BiSolidBed() icons.IsIcon                 { return newIcon(solidIcon, "bxs-bed") }
func BiSolidBeenHere() icons.IsIcon            { return newIcon(solidIcon, "bxs-been-here") }
func BiSolidBeer() icons.IsIcon                { return newIcon(solidIcon, "bxs-beer") }
func BiSolidBellMinus() icons.IsIcon           { return newIcon(solidIcon, "bxs-bell-minus") }
func BiSolidBellOff() icons.IsIcon             { return newIcon(solidIcon, "bxs-bell-off") }
func BiSolidBellPlus() icons.IsIcon            { return newIcon(solidIcon, "bxs-bell-plus") }
func BiSolidBellRing() icons.IsIcon            { return newIcon(solidIcon, "bxs-bell-ring") }
func BiSolidBell() icons.IsIcon                { return newIcon(solidIcon, "bxs-bell") }
func BiSolidBible() icons.IsIcon               { return newIcon(solidIcon, "bxs-bible") }
func BiSolidBinoculars() icons.IsIcon          { return newIcon(solidIcon, "bxs-binoculars") }
func BiSolidBlanket() icons.IsIcon             { return newIcon(solidIcon, "bxs-blanket") }
func BiSolidBoltCircle() icons.IsIcon          { return newIcon(solidIcon, "bxs-bolt-circle") }
func BiSolidBolt() icons.IsIcon                { return newIcon(solidIcon, "bxs-bolt") }
func BiSolidBomb() icons.IsIcon                { return newIcon(solidIcon, "bxs-bomb") }
func BiSolidBone() icons.IsIcon                { return newIcon(solidIcon, "bxs-bone") }
func BiSolidBong() icons.IsIcon                { return newIcon(solidIcon, "bxs-bong") }
func BiSolidBookAdd() icons.IsIcon             { return newIcon(solidIcon, "bxs-book-add") }
func BiSolidBookAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-book-alt") }
func BiSolidBookBookmark() icons.IsIcon        { return newIcon(solidIcon, "bxs-book-bookmark") }
func BiSolidBookContent() icons.IsIcon         { return newIcon(solidIcon, "bxs-book-content") }
func BiSolidBookHeart() icons.IsIcon           { return newIcon(solidIcon, "bxs-book-heart") }
func BiSolidBookOpen() icons.IsIcon            { return newIcon(solidIcon, "bxs-book-open") }
func BiSolidBookReader() icons.IsIcon          { return newIcon(solidIcon, "bxs-book-reader") }
func BiSolidBook() icons.IsIcon                { return newIcon(solidIcon, "bxs-book") }
func BiSolidBookmarkAltMinus() icons.IsIcon    { return newIcon(solidIcon, "bxs-bookmark-alt-minus") }
func BiSolidBookmarkAltPlus() icons.IsIcon     { return newIcon(solidIcon, "bxs-bookmark-alt-plus") }
func BiSolidBookmarkAlt() icons.IsIcon         { return newIcon(solidIcon, "bxs-bookmark-alt") }
func BiSolidBookmarkHeart() icons.IsIcon       { return newIcon(solidIcon, "bxs-bookmark-heart") }
func BiSolidBookmarkMinus() icons.IsIcon       { return newIcon(solidIcon, "bxs-bookmark-minus") }
func BiSolidBookmarkPlus() icons.IsIcon        { return newIcon(solidIcon, "bxs-bookmark-plus") }
func BiSolidBookmarkStar() icons.IsIcon        { return newIcon(solidIcon, "bxs-bookmark-star") }
func BiSolidBookmark() icons.IsIcon            { return newIcon(solidIcon, "bxs-bookmark") }
func BiSolidBookmarks() icons.IsIcon           { return newIcon(solidIcon, "bxs-bookmarks") }
func BiSolidBot() icons.IsIcon                 { return newIcon(solidIcon, "bxs-bot") }
func BiSolidBowlHot() icons.IsIcon             { return newIcon(solidIcon, "bxs-bowl-hot") }
func BiSolidBowlRice() icons.IsIcon            { return newIcon(solidIcon, "bxs-bowl-rice") }
func BiSolidBowlingBall() icons.IsIcon         { return newIcon(solidIcon, "bxs-bowling-ball") }
func BiSolidBox() icons.IsIcon                 { return newIcon(solidIcon, "bxs-box") }
func BiSolidBrain() icons.IsIcon               { return newIcon(solidIcon, "bxs-brain") }
func BiSolidBriefcaseAlt2() icons.IsIcon       { return newIcon(solidIcon, "bxs-briefcase-alt-2") }
func BiSolidBriefcaseAlt() icons.IsIcon        { return newIcon(solidIcon, "bxs-briefcase-alt") }
func BiSolidBriefcase() icons.IsIcon           { return newIcon(solidIcon, "bxs-briefcase") }
func BiSolidBrightnessHalf() icons.IsIcon      { return newIcon(solidIcon, "bxs-brightness-half") }
func BiSolidBrightness() icons.IsIcon          { return newIcon(solidIcon, "bxs-brightness") }
func BiSolidBrushAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-brush-alt") }
func BiSolidBrush() icons.IsIcon               { return newIcon(solidIcon, "bxs-brush") }
func BiSolidBugAlt() icons.IsIcon              { return newIcon(solidIcon, "bxs-bug-alt") }
func BiSolidBug() icons.IsIcon                 { return newIcon(solidIcon, "bxs-bug") }
func BiSolidBuildingHouse() icons.IsIcon       { return newIcon(solidIcon, "bxs-building-house") }
func BiSolidBuilding() icons.IsIcon            { return newIcon(solidIcon, "bxs-building") }
func BiSolidBuildings() icons.IsIcon           { return newIcon(solidIcon, "bxs-buildings") }
func BiSolidBulb() icons.IsIcon                { return newIcon(solidIcon, "bxs-bulb") }
func BiSolidBullseye() icons.IsIcon            { return newIcon(solidIcon, "bxs-bullseye") }
func BiSolidBuoy() icons.IsIcon                { return newIcon(solidIcon, "bxs-buoy") }
func BiSolidBusSchool() icons.IsIcon           { return newIcon(solidIcon, "bxs-bus-school") }
func BiSolidBus() icons.IsIcon                 { return newIcon(solidIcon, "bxs-bus") }
func BiSolidBusiness() icons.IsIcon            { return newIcon(solidIcon, "bxs-business") }
func BiSolidCabinet() icons.IsIcon             { return newIcon(solidIcon, "bxs-cabinet") }
func BiSolidCableCar() icons.IsIcon            { return newIcon(solidIcon, "bxs-cable-car") }
func BiSolidCake() icons.IsIcon                { return newIcon(solidIcon, "bxs-cake") }
func BiSolidCalculator() icons.IsIcon          { return newIcon(solidIcon, "bxs-calculator") }
func BiSolidCalendarAlt() icons.IsIcon         { return newIcon(solidIcon, "bxs-calendar-alt") }
func BiSolidCalendarCheck() icons.IsIcon       { return newIcon(solidIcon, "bxs-calendar-check") }
func BiSolidCalendarEdit() icons.IsIcon        { return newIcon(solidIcon, "bxs-calendar-edit") }
func BiSolidCalendarEvent() icons.IsIcon       { return newIcon(solidIcon, "bxs-calendar-event") }
func BiSolidCalendarExclamation() icons.IsIcon { return newIcon(solidIcon, "bxs-calendar-exclamation") }
func BiSolidCalendarHeart() icons.IsIcon       { return newIcon(solidIcon, "bxs-calendar-heart") }
func BiSolidCalendarMinus() icons.IsIcon       { return newIcon(solidIcon, "bxs-calendar-minus") }
func BiSolidCalendarPlus() icons.IsIcon        { return newIcon(solidIcon, "bxs-calendar-plus") }
func BiSolidCalendarStar() icons.IsIcon        { return newIcon(solidIcon, "bxs-calendar-star") }
func BiSolidCalendarWeek() icons.IsIcon        { return newIcon(solidIcon, "bxs-calendar-week") }
func BiSolidCalendarX() icons.IsIcon           { return newIcon(solidIcon, "bxs-calendar-x") }
func BiSolidCalendar() icons.IsIcon            { return newIcon(solidIcon, "bxs-calendar") }
func BiSolidCameraHome() icons.IsIcon          { return newIcon(solidIcon, "bxs-camera-home") }
func BiSolidCameraMovie() icons.IsIcon         { return newIcon(solidIcon, "bxs-camera-movie") }
func BiSolidCameraOff() icons.IsIcon           { return newIcon(solidIcon, "bxs-camera-off") }
func BiSolidCameraPlus() icons.IsIcon          { return newIcon(solidIcon, "bxs-camera-plus") }
func BiSolidCamera() icons.IsIcon              { return newIcon(solidIcon, "bxs-camera") }
func BiSolidCapsule() icons.IsIcon             { return newIcon(solidIcon, "bxs-capsule") }
func BiSolidCaptions() icons.IsIcon            { return newIcon(solidIcon, "bxs-captions") }
func BiSolidCarBattery() icons.IsIcon          { return newIcon(solidIcon, "bxs-car-battery") }
func BiSolidCarCrash() icons.IsIcon            { return newIcon(solidIcon, "bxs-car-crash") }
func BiSolidCarGarage() icons.IsIcon           { return newIcon(solidIcon, "bxs-car-garage") }
func BiSolidCarMechanic() icons.IsIcon         { return newIcon(solidIcon, "bxs-car-mechanic") }
func BiSolidCarWash() icons.IsIcon             { return newIcon(solidIcon, "bxs-car-wash") }
func BiSolidCar() icons.IsIcon                 { return newIcon(solidIcon, "bxs-car") }
func BiSolidCard() icons.IsIcon                { return newIcon(solidIcon, "bxs-card") }
func BiSolidCaretDownCircle() icons.IsIcon     { return newIcon(solidIcon, "bxs-caret-down-circle") }
func BiSolidCaretDownSquare() icons.IsIcon     { return newIcon(solidIcon, "bxs-caret-down-square") }
func BiSolidCaretLeftCircle() icons.IsIcon     { return newIcon(solidIcon, "bxs-caret-left-circle") }
func BiSolidCaretLeftSquare() icons.IsIcon     { return newIcon(solidIcon, "bxs-caret-left-square") }
func BiSolidCaretRightCircle() icons.IsIcon    { return newIcon(solidIcon, "bxs-caret-right-circle") }
func BiSolidCaretRightSquare() icons.IsIcon    { return newIcon(solidIcon, "bxs-caret-right-square") }
func BiSolidCaretUpCircle() icons.IsIcon       { return newIcon(solidIcon, "bxs-caret-up-circle") }
func BiSolidCaretUpSquare() icons.IsIcon       { return newIcon(solidIcon, "bxs-caret-up-square") }
func BiSolidCarousel() icons.IsIcon            { return newIcon(solidIcon, "bxs-carousel") }
func BiSolidCartAdd() icons.IsIcon             { return newIcon(solidIcon, "bxs-cart-add") }
func BiSolidCartAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-cart-alt") }
func BiSolidCartDownload() icons.IsIcon        { return newIcon(solidIcon, "bxs-cart-download") }
func BiSolidCart() icons.IsIcon                { return newIcon(solidIcon, "bxs-cart") }
func BiSolidCastle() icons.IsIcon              { return newIcon(solidIcon, "bxs-castle") }
func BiSolidCat() icons.IsIcon                 { return newIcon(solidIcon, "bxs-cat") }
func BiSolidCategoryAlt() icons.IsIcon         { return newIcon(solidIcon, "bxs-category-alt") }
func BiSolidCategory() icons.IsIcon            { return newIcon(solidIcon, "bxs-category") }
func BiSolidCctv() icons.IsIcon                { return newIcon(solidIcon, "bxs-cctv") }
func BiSolidCertification() icons.IsIcon       { return newIcon(solidIcon, "bxs-certification") }
func BiSolidChalkboard() icons.IsIcon          { return newIcon(solidIcon, "bxs-chalkboard") }
func BiSolidChart() icons.IsIcon               { return newIcon(solidIcon, "bxs-chart") }
func BiSolidChat() icons.IsIcon                { return newIcon(solidIcon, "bxs-chat") }
func BiSolidCheckCircle() icons.IsIcon         { return newIcon(solidIcon, "bxs-check-circle") }
func BiSolidCheckShield() icons.IsIcon         { return newIcon(solidIcon, "bxs-check-shield") }
func BiSolidCheckSquare() icons.IsIcon         { return newIcon(solidIcon, "bxs-check-square") }
func BiSolidCheckboxChecked() icons.IsIcon     { return newIcon(solidIcon, "bxs-checkbox-checked") }
func BiSolidCheckboxMinus() icons.IsIcon       { return newIcon(solidIcon, "bxs-checkbox-minus") }
func BiSolidCheckbox() icons.IsIcon            { return newIcon(solidIcon, "bxs-checkbox") }
func BiSolidCheese() icons.IsIcon              { return newIcon(solidIcon, "bxs-cheese") }
func BiSolidChess() icons.IsIcon               { return newIcon(solidIcon, "bxs-chess") }
func BiSolidChevronDownCircle() icons.IsIcon   { return newIcon(solidIcon, "bxs-chevron-down-circle") }
func BiSolidChevronDownSquare() icons.IsIcon   { return newIcon(solidIcon, "bxs-chevron-down-square") }
func BiSolidChevronDown() icons.IsIcon         { return newIcon(solidIcon, "bxs-chevron-down") }
func BiSolidChevronLeftCircle() icons.IsIcon   { return newIcon(solidIcon, "bxs-chevron-left-circle") }
func BiSolidChevronLeftSquare() icons.IsIcon   { return newIcon(solidIcon, "bxs-chevron-left-square") }
func BiSolidChevronLeft() icons.IsIcon         { return newIcon(solidIcon, "bxs-chevron-left") }
func BiSolidChevronRightCircle() icons.IsIcon  { return newIcon(solidIcon, "bxs-chevron-right-circle") }
func BiSolidChevronRightSquare() icons.IsIcon  { return newIcon(solidIcon, "bxs-chevron-right-square") }
func BiSolidChevronRight() icons.IsIcon        { return newIcon(solidIcon, "bxs-chevron-right") }
func BiSolidChevronUpCircle() icons.IsIcon     { return newIcon(solidIcon, "bxs-chevron-up-circle") }
func BiSolidChevronUpSquare() icons.IsIcon     { return newIcon(solidIcon, "bxs-chevron-up-square") }
func BiSolidChevronUp() icons.IsIcon           { return newIcon(solidIcon, "bxs-chevron-up") }
func BiSolidChevronsDown() icons.IsIcon        { return newIcon(solidIcon, "bxs-chevrons-down") }
func BiSolidChevronsLeft() icons.IsIcon        { return newIcon(solidIcon, "bxs-chevrons-left") }
func BiSolidChevronsRight() icons.IsIcon       { return newIcon(solidIcon, "bxs-chevrons-right") }
func BiSolidChevronsUp() icons.IsIcon          { return newIcon(solidIcon, "bxs-chevrons-up") }
func BiSolidChip() icons.IsIcon                { return newIcon(solidIcon, "bxs-chip") }
func BiSolidChurch() icons.IsIcon              { return newIcon(solidIcon, "bxs-church") }
func BiSolidCircleHalf() icons.IsIcon          { return newIcon(solidIcon, "bxs-circle-half") }
func BiSolidCircleQuarter() icons.IsIcon       { return newIcon(solidIcon, "bxs-circle-quarter") }
func BiSolidCircleThreeQuarter() icons.IsIcon  { return newIcon(solidIcon, "bxs-circle-three-quarter") }
func BiSolidCircle() icons.IsIcon              { return newIcon(solidIcon, "bxs-circle") }
func BiSolidCity() icons.IsIcon                { return newIcon(solidIcon, "bxs-city") }
func BiSolidClinic() icons.IsIcon              { return newIcon(solidIcon, "bxs-clinic") }
func BiSolidCloudDownload() icons.IsIcon       { return newIcon(solidIcon, "bxs-cloud-download") }
func BiSolidCloudLightning() icons.IsIcon      { return newIcon(solidIcon, "bxs-cloud-lightning") }
func BiSolidCloudRain() icons.IsIcon           { return newIcon(solidIcon, "bxs-cloud-rain") }
func BiSolidCloudUpload() icons.IsIcon         { return newIcon(solidIcon, "bxs-cloud-upload") }
func BiSolidCloud() icons.IsIcon               { return newIcon(solidIcon, "bxs-cloud") }
func BiSolidCoffeeAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-coffee-alt") }
func BiSolidCoffeeBean() icons.IsIcon          { return newIcon(solidIcon, "bxs-coffee-bean") }
func BiSolidCoffeeTogo() icons.IsIcon          { return newIcon(solidIcon, "bxs-coffee-togo") }
func BiSolidCoffee() icons.IsIcon              { return newIcon(solidIcon, "bxs-coffee") }
func BiSolidCog() icons.IsIcon                 { return newIcon(solidIcon, "bxs-cog") }
func BiSolidCoinStack() icons.IsIcon           { return newIcon(solidIcon, "bxs-coin-stack") }
func BiSolidCoin() icons.IsIcon                { return newIcon(solidIcon, "bxs-coin") }
func BiSolidCollection() icons.IsIcon          { return newIcon(solidIcon, "bxs-collection") }
func BiSolidColorFill() icons.IsIcon           { return newIcon(solidIcon, "bxs-color-fill") }
func BiSolidColor() icons.IsIcon               { return newIcon(solidIcon, "bxs-color") }
func BiSolidCommentAdd() icons.IsIcon          { return newIcon(solidIcon, "bxs-comment-add") }
func BiSolidCommentCheck() icons.IsIcon        { return newIcon(solidIcon, "bxs-comment-check") }
func BiSolidCommentDetail() icons.IsIcon       { return newIcon(solidIcon, "bxs-comment-detail") }
func BiSolidCommentDots() icons.IsIcon         { return newIcon(solidIcon, "bxs-comment-dots") }
func BiSolidCommentEdit() icons.IsIcon         { return newIcon(solidIcon, "bxs-comment-edit") }
func BiSolidCommentError() icons.IsIcon        { return newIcon(solidIcon, "bxs-comment-error") }
func BiSolidCommentMinus() icons.IsIcon        { return newIcon(solidIcon, "bxs-comment-minus") }
func BiSolidCommentX() icons.IsIcon            { return newIcon(solidIcon, "bxs-comment-x") }
func BiSolidComment() icons.IsIcon             { return newIcon(solidIcon, "bxs-comment") }
func BiSolidCompass() icons.IsIcon             { return newIcon(solidIcon, "bxs-compass") }
func BiSolidComponent() icons.IsIcon           { return newIcon(solidIcon, "bxs-component") }
func BiSolidConfused() icons.IsIcon            { return newIcon(solidIcon, "bxs-confused") }
func BiSolidContact() icons.IsIcon             { return newIcon(solidIcon, "bxs-contact") }
func BiSolidConversation() icons.IsIcon        { return newIcon(solidIcon, "bxs-conversation") }
func BiSolidCookie() icons.IsIcon              { return newIcon(solidIcon, "bxs-cookie") }
func BiSolidCool() icons.IsIcon                { return newIcon(solidIcon, "bxs-cool") }
func BiSolidCopyAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-copy-alt") }
func BiSolidCopy() icons.IsIcon                { return newIcon(solidIcon, "bxs-copy") }
func BiSolidCopyright() icons.IsIcon           { return newIcon(solidIcon, "bxs-copyright") }
func BiSolidCoupon() icons.IsIcon              { return newIcon(solidIcon, "bxs-coupon") }
func BiSolidCreditCardAlt() icons.IsIcon       { return newIcon(solidIcon, "bxs-credit-card-alt") }
func BiSolidCreditCardFront() icons.IsIcon     { return newIcon(solidIcon, "bxs-credit-card-front") }
func BiSolidCreditCard() icons.IsIcon          { return newIcon(solidIcon, "bxs-credit-card") }
func BiSolidCricketBall() icons.IsIcon         { return newIcon(solidIcon, "bxs-cricket-ball") }
func BiSolidCrop() icons.IsIcon                { return newIcon(solidIcon, "bxs-crop") }
func BiSolidCrown() icons.IsIcon               { return newIcon(solidIcon, "bxs-crown") }
func BiSolidCubeAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-cube-alt") }
func BiSolidCube() icons.IsIcon                { return newIcon(solidIcon, "bxs-cube") }
func BiSolidCuboid() icons.IsIcon              { return newIcon(solidIcon, "bxs-cuboid") }
func BiSolidCustomize() icons.IsIcon           { return newIcon(solidIcon, "bxs-customize") }
func BiSolidCylinder() icons.IsIcon            { return newIcon(solidIcon, "bxs-cylinder") }
func BiSolidDashboard() icons.IsIcon           { return newIcon(solidIcon, "bxs-dashboard") }
func BiSolidData() icons.IsIcon                { return newIcon(solidIcon, "bxs-data") }
func BiSolidDetail() icons.IsIcon              { return newIcon(solidIcon, "bxs-detail") }
func BiSolidDevices() icons.IsIcon             { return newIcon(solidIcon, "bxs-devices") }
func BiSolidDiamond() icons.IsIcon             { return newIcon(solidIcon, "bxs-diamond") }
func BiSolidDice1() icons.IsIcon               { return newIcon(solidIcon, "bxs-dice-1") }
func BiSolidDice2() icons.IsIcon               { return newIcon(solidIcon, "bxs-dice-2") }
func BiSolidDice3() icons.IsIcon               { return newIcon(solidIcon, "bxs-dice-3") }
func BiSolidDice4() icons.IsIcon               { return newIcon(solidIcon, "bxs-dice-4") }
func BiSolidDice5() icons.IsIcon               { return newIcon(solidIcon, "bxs-dice-5") }
func BiSolidDice6() icons.IsIcon               { return newIcon(solidIcon, "bxs-dice-6") }
func BiSolidDirectionLeft() icons.IsIcon       { return newIcon(solidIcon, "bxs-direction-left") }
func BiSolidDirectionRight() icons.IsIcon      { return newIcon(solidIcon, "bxs-direction-right") }
func BiSolidDirections() icons.IsIcon          { return newIcon(solidIcon, "bxs-directions") }
func BiSolidDisc() icons.IsIcon                { return newIcon(solidIcon, "bxs-disc") }
func BiSolidDiscount() icons.IsIcon            { return newIcon(solidIcon, "bxs-discount") }
func BiSolidDish() icons.IsIcon                { return newIcon(solidIcon, "bxs-dish") }
func BiSolidDislike() icons.IsIcon             { return newIcon(solidIcon, "bxs-dislike") }
func BiSolidDizzy() icons.IsIcon               { return newIcon(solidIcon, "bxs-dizzy") }
func BiSolidDockBottom() icons.IsIcon          { return newIcon(solidIcon, "bxs-dock-bottom") }
func BiSolidDockLeft() icons.IsIcon            { return newIcon(solidIcon, "bxs-dock-left") }
func BiSolidDockRight() icons.IsIcon           { return newIcon(solidIcon, "bxs-dock-right") }
func BiSolidDockTop() icons.IsIcon             { return newIcon(solidIcon, "bxs-dock-top") }
func BiSolidDog() icons.IsIcon                 { return newIcon(solidIcon, "bxs-dog") }
func BiSolidDollarCircle() icons.IsIcon        { return newIcon(solidIcon, "bxs-dollar-circle") }
func BiSolidDonateBlood() icons.IsIcon         { return newIcon(solidIcon, "bxs-donate-blood") }
func BiSolidDonateHeart() icons.IsIcon         { return newIcon(solidIcon, "bxs-donate-heart") }
func BiSolidDoorOpen() icons.IsIcon            { return newIcon(solidIcon, "bxs-door-open") }
func BiSolidDoughnutChart() icons.IsIcon       { return newIcon(solidIcon, "bxs-doughnut-chart") }
func BiSolidDownArrowAlt() icons.IsIcon        { return newIcon(solidIcon, "bxs-down-arrow-alt") }
func BiSolidDownArrowCircle() icons.IsIcon     { return newIcon(solidIcon, "bxs-down-arrow-circle") }
func BiSolidDownArrowSquare() icons.IsIcon     { return newIcon(solidIcon, "bxs-down-arrow-square") }
func BiSolidDownArrow() icons.IsIcon           { return newIcon(solidIcon, "bxs-down-arrow") }
func BiSolidDownload() icons.IsIcon            { return newIcon(solidIcon, "bxs-download") }
func BiSolidDownvote() icons.IsIcon            { return newIcon(solidIcon, "bxs-downvote") }
func BiSolidDrink() icons.IsIcon               { return newIcon(solidIcon, "bxs-drink") }
func BiSolidDropletHalf() icons.IsIcon         { return newIcon(solidIcon, "bxs-droplet-half") }
func BiSolidDroplet() icons.IsIcon             { return newIcon(solidIcon, "bxs-droplet") }
func BiSolidDryer() icons.IsIcon               { return newIcon(solidIcon, "bxs-dryer") }
func BiSolidDuplicate() icons.IsIcon           { return newIcon(solidIcon, "bxs-duplicate") }
func BiSolidEditAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-edit-alt") }
func BiSolidEditLocation() icons.IsIcon        { return newIcon(solidIcon, "bxs-edit-location") }
func BiSolidEdit() icons.IsIcon                { return newIcon(solidIcon, "bxs-edit") }
func BiSolidEject() icons.IsIcon               { return newIcon(solidIcon, "bxs-eject") }
func BiSolidEnvelopeOpen() icons.IsIcon        { return newIcon(solidIcon, "bxs-envelope-open") }
func BiSolidEnvelope() icons.IsIcon            { return newIcon(solidIcon, "bxs-envelope") }
func BiSolidEraser() icons.IsIcon              { return newIcon(solidIcon, "bxs-eraser") }
func BiSolidErrorAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-error-alt") }
func BiSolidErrorCircle() icons.IsIcon         { return newIcon(solidIcon, "bxs-error-circle") }
func BiSolidError() icons.IsIcon               { return newIcon(solidIcon, "bxs-error") }
func BiSolidEvStation() icons.IsIcon           { return newIcon(solidIcon, "bxs-ev-station") }
func BiSolidExit() icons.IsIcon                { return newIcon(solidIcon, "bxs-exit") }
func BiSolidExtension() icons.IsIcon           { return newIcon(solidIcon, "bxs-extension") }
func BiSolidEyedropper() icons.IsIcon          { return newIcon(solidIcon, "bxs-eyedropper") }
func BiSolidFaceMask() icons.IsIcon            { return newIcon(solidIcon, "bxs-face-mask") }
func BiSolidFace() icons.IsIcon                { return newIcon(solidIcon, "bxs-face") }
func BiSolidFactory() icons.IsIcon             { return newIcon(solidIcon, "bxs-factory") }
func BiSolidFastForwardCircle() icons.IsIcon   { return newIcon(solidIcon, "bxs-fast-forward-circle") }
func BiSolidFileArchive() icons.IsIcon         { return newIcon(solidIcon, "bxs-file-archive") }
func BiSolidFileBlank() icons.IsIcon           { return newIcon(solidIcon, "bxs-file-blank") }
func BiSolidFileCss() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-css") }
func BiSolidFileDoc() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-doc") }
func BiSolidFileExport() icons.IsIcon          { return newIcon(solidIcon, "bxs-file-export") }
func BiSolidFileFind() icons.IsIcon            { return newIcon(solidIcon, "bxs-file-find") }
func BiSolidFileGif() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-gif") }
func BiSolidFileHtml() icons.IsIcon            { return newIcon(solidIcon, "bxs-file-html") }
func BiSolidFileImage() icons.IsIcon           { return newIcon(solidIcon, "bxs-file-image") }
func BiSolidFileImport() icons.IsIcon          { return newIcon(solidIcon, "bxs-file-import") }
func BiSolidFileJpg() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-jpg") }
func BiSolidFileJs() icons.IsIcon              { return newIcon(solidIcon, "bxs-file-js") }
func BiSolidFileJson() icons.IsIcon            { return newIcon(solidIcon, "bxs-file-json") }
func BiSolidFileMd() icons.IsIcon              { return newIcon(solidIcon, "bxs-file-md") }
func BiSolidFilePdf() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-pdf") }
func BiSolidFilePlus() icons.IsIcon            { return newIcon(solidIcon, "bxs-file-plus") }
func BiSolidFilePng() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-png") }
func BiSolidFileTxt() icons.IsIcon             { return newIcon(solidIcon, "bxs-file-txt") }
func BiSolidFile() icons.IsIcon                { return newIcon(solidIcon, "bxs-file") }
func BiSolidFilm() icons.IsIcon                { return newIcon(solidIcon, "bxs-film") }
func BiSolidFilterAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-filter-alt") }
func BiSolidFirstAid() icons.IsIcon            { return newIcon(solidIcon, "bxs-first-aid") }
func BiSolidFlagAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-flag-alt") }
func BiSolidFlagCheckered() icons.IsIcon       { return newIcon(solidIcon, "bxs-flag-checkered") }
func BiSolidFlag() icons.IsIcon                { return newIcon(solidIcon, "bxs-flag") }
func BiSolidFlame() icons.IsIcon               { return newIcon(solidIcon, "bxs-flame") }
func BiSolidFlask() icons.IsIcon               { return newIcon(solidIcon, "bxs-flask") }
func BiSolidFlorist() icons.IsIcon             { return newIcon(solidIcon, "bxs-florist") }
func BiSolidFolderMinus() icons.IsIcon         { return newIcon(solidIcon, "bxs-folder-minus") }
func BiSolidFolderOpen() icons.IsIcon          { return newIcon(solidIcon, "bxs-folder-open") }
func BiSolidFolderPlus() icons.IsIcon          { return newIcon(solidIcon, "bxs-folder-plus") }
func BiSolidFolder() icons.IsIcon              { return newIcon(solidIcon, "bxs-folder") }
func BiSolidFoodMenu() icons.IsIcon            { return newIcon(solidIcon, "bxs-food-menu") }
func BiSolidFridge() icons.IsIcon              { return newIcon(solidIcon, "bxs-fridge") }
func BiSolidGame() icons.IsIcon                { return newIcon(solidIcon, "bxs-game") }
func BiSolidGasPump() icons.IsIcon             { return newIcon(solidIcon, "bxs-gas-pump") }
func BiSolidGhost() icons.IsIcon               { return newIcon(solidIcon, "bxs-ghost") }
func BiSolidGift() icons.IsIcon                { return newIcon(solidIcon, "bxs-gift") }
func BiSolidGraduation() icons.IsIcon          { return newIcon(solidIcon, "bxs-graduation") }
func BiSolidGridAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-grid-alt") }
func BiSolidGrid() icons.IsIcon                { return newIcon(solidIcon, "bxs-grid") }
func BiSolidGroup() icons.IsIcon               { return newIcon(solidIcon, "bxs-group") }
func BiSolidGuitarAmp() icons.IsIcon           { return newIcon(solidIcon, "bxs-guitar-amp") }
func BiSolidHandDown() icons.IsIcon            { return newIcon(solidIcon, "bxs-hand-down") }
func BiSolidHandLeft() icons.IsIcon            { return newIcon(solidIcon, "bxs-hand-left") }
func BiSolidHandRight() icons.IsIcon           { return newIcon(solidIcon, "bxs-hand-right") }
func BiSolidHandUp() icons.IsIcon              { return newIcon(solidIcon, "bxs-hand-up") }
func BiSolidHand() icons.IsIcon                { return newIcon(solidIcon, "bxs-hand") }
func BiSolidHappyAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-happy-alt") }
func BiSolidHappyBeaming() icons.IsIcon        { return newIcon(solidIcon, "bxs-happy-beaming") }
func BiSolidHappyHeartEyes() icons.IsIcon      { return newIcon(solidIcon, "bxs-happy-heart-eyes") }
func BiSolidHappy() icons.IsIcon               { return newIcon(solidIcon, "bxs-happy") }
func BiSolidHardHat() icons.IsIcon             { return newIcon(solidIcon, "bxs-hard-hat") }
func BiSolidHdd() icons.IsIcon                 { return newIcon(solidIcon, "bxs-hdd") }
func BiSolidHeartCircle() icons.IsIcon         { return newIcon(solidIcon, "bxs-heart-circle") }
func BiSolidHeartSquare() icons.IsIcon         { return newIcon(solidIcon, "bxs-heart-square") }
func BiSolidHeart() icons.IsIcon               { return newIcon(solidIcon, "bxs-heart") }
func BiSolidHelpCircle() icons.IsIcon          { return newIcon(solidIcon, "bxs-help-circle") }
func BiSolidHide() icons.IsIcon                { return newIcon(solidIcon, "bxs-hide") }
func BiSolidHomeAlt2() icons.IsIcon            { return newIcon(solidIcon, "bxs-home-alt-2") }
func BiSolidHomeCircle() icons.IsIcon          { return newIcon(solidIcon, "bxs-home-circle") }
func BiSolidHomeHeart() icons.IsIcon           { return newIcon(solidIcon, "bxs-home-heart") }
func BiSolidHomeSmile() icons.IsIcon           { return newIcon(solidIcon, "bxs-home-smile") }
func BiSolidHome() icons.IsIcon                { return newIcon(solidIcon, "bxs-home") }
func BiSolidHot() icons.IsIcon                 { return newIcon(solidIcon, "bxs-hot") }
func BiSolidHotel() icons.IsIcon               { return newIcon(solidIcon, "bxs-hotel") }
func BiSolidHourglassBottom() icons.IsIcon     { return newIcon(solidIcon, "bxs-hourglass-bottom") }
func BiSolidHourglassTop() icons.IsIcon        { return newIcon(solidIcon, "bxs-hourglass-top") }
func BiSolidHourglass() icons.IsIcon           { return newIcon(solidIcon, "bxs-hourglass") }
func BiSolidIdCard() icons.IsIcon              { return newIcon(solidIcon, "bxs-id-card") }
func BiSolidImageAdd() icons.IsIcon            { return newIcon(solidIcon, "bxs-image-add") }
func BiSolidImageAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-image-alt") }
func BiSolidImage() icons.IsIcon               { return newIcon(solidIcon, "bxs-image") }
func BiSolidInbox() icons.IsIcon               { return newIcon(solidIcon, "bxs-inbox") }
func BiSolidInfoCircle() icons.IsIcon          { return newIcon(solidIcon, "bxs-info-circle") }
func BiSolidInfoSquare() icons.IsIcon          { return newIcon(solidIcon, "bxs-info-square") }
func BiSolidInjection() icons.IsIcon           { return newIcon(solidIcon, "bxs-injection") }
func BiSolidInstitution() icons.IsIcon         { return newIcon(solidIcon, "bxs-institution") }
func BiSolidInvader() icons.IsIcon             { return newIcon(solidIcon, "bxs-invader") }
func BiSolidJoystickAlt() icons.IsIcon         { return newIcon(solidIcon, "bxs-joystick-alt") }
func BiSolidJoystickButton() icons.IsIcon      { return newIcon(solidIcon, "bxs-joystick-button") }
func BiSolidJoystick() icons.IsIcon            { return newIcon(solidIcon, "bxs-joystick") }
func BiSolidKey() icons.IsIcon                 { return newIcon(solidIcon, "bxs-key") }
func BiSolidKeyboard() icons.IsIcon            { return newIcon(solidIcon, "bxs-keyboard") }
func BiSolidLabel() icons.IsIcon               { return newIcon(solidIcon, "bxs-label") }
func BiSolidLandmark() icons.IsIcon            { return newIcon(solidIcon, "bxs-landmark") }
func BiSolidLandscape() icons.IsIcon           { return newIcon(solidIcon, "bxs-landscape") }
func BiSolidLaugh() icons.IsIcon               { return newIcon(solidIcon, "bxs-laugh") }
func BiSolidLayerMinus() icons.IsIcon          { return newIcon(solidIcon, "bxs-layer-minus") }
func BiSolidLayerPlus() icons.IsIcon           { return newIcon(solidIcon, "bxs-layer-plus") }
func BiSolidLayer() icons.IsIcon               { return newIcon(solidIcon, "bxs-layer") }
func BiSolidLayout() icons.IsIcon              { return newIcon(solidIcon, "bxs-layout") }
func BiSolidLeaf() icons.IsIcon                { return newIcon(solidIcon, "bxs-leaf") }
func BiSolidLeftArrowAlt() icons.IsIcon        { return newIcon(solidIcon, "bxs-left-arrow-alt") }
func BiSolidLeftArrowCircle() icons.IsIcon     { return newIcon(solidIcon, "bxs-left-arrow-circle") }
func BiSolidLeftArrowSquare() icons.IsIcon     { return newIcon(solidIcon, "bxs-left-arrow-square") }
func BiSolidLeftArrow() icons.IsIcon           { return newIcon(solidIcon, "bxs-left-arrow") }
func BiSolidLeftDownArrowCircle() icons.IsIcon {
	return newIcon(solidIcon, "bxs-left-down-arrow-circle")
}
func BiSolidLeftTopArrowCircle() icons.IsIcon { return newIcon(solidIcon, "bxs-left-top-arrow-circle") }
func BiSolidLemon() icons.IsIcon              { return newIcon(solidIcon, "bxs-lemon") }
func BiSolidLike() icons.IsIcon               { return newIcon(solidIcon, "bxs-like") }
func BiSolidLocationPlus() icons.IsIcon       { return newIcon(solidIcon, "bxs-location-plus") }
func BiSolidLockAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-lock-alt") }
func BiSolidLockOpenAlt() icons.IsIcon        { return newIcon(solidIcon, "bxs-lock-open-alt") }
func BiSolidLockOpen() icons.IsIcon           { return newIcon(solidIcon, "bxs-lock-open") }
func BiSolidLock() icons.IsIcon               { return newIcon(solidIcon, "bxs-lock") }
func BiSolidLogInCircle() icons.IsIcon        { return newIcon(solidIcon, "bxs-log-in-circle") }
func BiSolidLogIn() icons.IsIcon              { return newIcon(solidIcon, "bxs-log-in") }
func BiSolidLogOutCircle() icons.IsIcon       { return newIcon(solidIcon, "bxs-log-out-circle") }
func BiSolidLogOut() icons.IsIcon             { return newIcon(solidIcon, "bxs-log-out") }
func BiSolidLowVision() icons.IsIcon          { return newIcon(solidIcon, "bxs-low-vision") }
func BiSolidMagicWand() icons.IsIcon          { return newIcon(solidIcon, "bxs-magic-wand") }
func BiSolidMagnet() icons.IsIcon             { return newIcon(solidIcon, "bxs-magnet") }
func BiSolidMapAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-map-alt") }
func BiSolidMapPin() icons.IsIcon             { return newIcon(solidIcon, "bxs-map-pin") }
func BiSolidMap() icons.IsIcon                { return newIcon(solidIcon, "bxs-map") }
func BiSolidMask() icons.IsIcon               { return newIcon(solidIcon, "bxs-mask") }
func BiSolidMedal() icons.IsIcon              { return newIcon(solidIcon, "bxs-medal") }
func BiSolidMegaphone() icons.IsIcon          { return newIcon(solidIcon, "bxs-megaphone") }
func BiSolidMehAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-meh-alt") }
func BiSolidMehBlank() icons.IsIcon           { return newIcon(solidIcon, "bxs-meh-blank") }
func BiSolidMeh() icons.IsIcon                { return newIcon(solidIcon, "bxs-meh") }
func BiSolidMemoryCard() icons.IsIcon         { return newIcon(solidIcon, "bxs-memory-card") }
func BiSolidMessageAdd() icons.IsIcon         { return newIcon(solidIcon, "bxs-message-add") }
func BiSolidMessageAltAdd() icons.IsIcon      { return newIcon(solidIcon, "bxs-message-alt-add") }
func BiSolidMessageAltCheck() icons.IsIcon    { return newIcon(solidIcon, "bxs-message-alt-check") }
func BiSolidMessageAltDetail() icons.IsIcon   { return newIcon(solidIcon, "bxs-message-alt-detail") }
func BiSolidMessageAltDots() icons.IsIcon     { return newIcon(solidIcon, "bxs-message-alt-dots") }
func BiSolidMessageAltEdit() icons.IsIcon     { return newIcon(solidIcon, "bxs-message-alt-edit") }
func BiSolidMessageAltError() icons.IsIcon    { return newIcon(solidIcon, "bxs-message-alt-error") }
func BiSolidMessageAltMinus() icons.IsIcon    { return newIcon(solidIcon, "bxs-message-alt-minus") }
func BiSolidMessageAltX() icons.IsIcon        { return newIcon(solidIcon, "bxs-message-alt-x") }
func BiSolidMessageAlt() icons.IsIcon         { return newIcon(solidIcon, "bxs-message-alt") }
func BiSolidMessageCheck() icons.IsIcon       { return newIcon(solidIcon, "bxs-message-check") }
func BiSolidMessageDetail() icons.IsIcon      { return newIcon(solidIcon, "bxs-message-detail") }
func BiSolidMessageDots() icons.IsIcon        { return newIcon(solidIcon, "bxs-message-dots") }
func BiSolidMessageEdit() icons.IsIcon        { return newIcon(solidIcon, "bxs-message-edit") }
func BiSolidMessageError() icons.IsIcon       { return newIcon(solidIcon, "bxs-message-error") }
func BiSolidMessageMinus() icons.IsIcon       { return newIcon(solidIcon, "bxs-message-minus") }
func BiSolidMessageRoundedAdd() icons.IsIcon  { return newIcon(solidIcon, "bxs-message-rounded-add") }
func BiSolidMessageRoundedCheck() icons.IsIcon {
	return newIcon(solidIcon, "bxs-message-rounded-check")
}
func BiSolidMessageRoundedDetail() icons.IsIcon {
	return newIcon(solidIcon, "bxs-message-rounded-detail")
}
func BiSolidMessageRoundedDots() icons.IsIcon { return newIcon(solidIcon, "bxs-message-rounded-dots") }
func BiSolidMessageRoundedEdit() icons.IsIcon { return newIcon(solidIcon, "bxs-message-rounded-edit") }
func BiSolidMessageRoundedError() icons.IsIcon {
	return newIcon(solidIcon, "bxs-message-rounded-error")
}
func BiSolidMessageRoundedMinus() icons.IsIcon {
	return newIcon(solidIcon, "bxs-message-rounded-minus")
}
func BiSolidMessageRoundedX() icons.IsIcon    { return newIcon(solidIcon, "bxs-message-rounded-x") }
func BiSolidMessageRounded() icons.IsIcon     { return newIcon(solidIcon, "bxs-message-rounded") }
func BiSolidMessageSquareAdd() icons.IsIcon   { return newIcon(solidIcon, "bxs-message-square-add") }
func BiSolidMessageSquareCheck() icons.IsIcon { return newIcon(solidIcon, "bxs-message-square-check") }
func BiSolidMessageSquareDetail() icons.IsIcon {
	return newIcon(solidIcon, "bxs-message-square-detail")
}
func BiSolidMessageSquareDots() icons.IsIcon  { return newIcon(solidIcon, "bxs-message-square-dots") }
func BiSolidMessageSquareEdit() icons.IsIcon  { return newIcon(solidIcon, "bxs-message-square-edit") }
func BiSolidMessageSquareError() icons.IsIcon { return newIcon(solidIcon, "bxs-message-square-error") }
func BiSolidMessageSquareMinus() icons.IsIcon { return newIcon(solidIcon, "bxs-message-square-minus") }
func BiSolidMessageSquareX() icons.IsIcon     { return newIcon(solidIcon, "bxs-message-square-x") }
func BiSolidMessageSquare() icons.IsIcon      { return newIcon(solidIcon, "bxs-message-square") }
func BiSolidMessageX() icons.IsIcon           { return newIcon(solidIcon, "bxs-message-x") }
func BiSolidMessage() icons.IsIcon            { return newIcon(solidIcon, "bxs-message") }
func BiSolidMeteor() icons.IsIcon             { return newIcon(solidIcon, "bxs-meteor") }
func BiSolidMicrochip() icons.IsIcon          { return newIcon(solidIcon, "bxs-microchip") }
func BiSolidMicrophoneAlt() icons.IsIcon      { return newIcon(solidIcon, "bxs-microphone-alt") }
func BiSolidMicrophoneOff() icons.IsIcon      { return newIcon(solidIcon, "bxs-microphone-off") }
func BiSolidMicrophone() icons.IsIcon         { return newIcon(solidIcon, "bxs-microphone") }
func BiSolidMinusCircle() icons.IsIcon        { return newIcon(solidIcon, "bxs-minus-circle") }
func BiSolidMinusSquare() icons.IsIcon        { return newIcon(solidIcon, "bxs-minus-square") }
func BiSolidMobileVibration() icons.IsIcon    { return newIcon(solidIcon, "bxs-mobile-vibration") }
func BiSolidMobile() icons.IsIcon             { return newIcon(solidIcon, "bxs-mobile") }
func BiSolidMoon() icons.IsIcon               { return newIcon(solidIcon, "bxs-moon") }
func BiSolidMouseAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-mouse-alt") }
func BiSolidMouse() icons.IsIcon              { return newIcon(solidIcon, "bxs-mouse") }
func BiSolidMoviePlay() icons.IsIcon          { return newIcon(solidIcon, "bxs-movie-play") }
func BiSolidMovie() icons.IsIcon              { return newIcon(solidIcon, "bxs-movie") }
func BiSolidMusic() icons.IsIcon              { return newIcon(solidIcon, "bxs-music") }
func BiSolidNavigation() icons.IsIcon         { return newIcon(solidIcon, "bxs-navigation") }
func BiSolidNetworkChart() icons.IsIcon       { return newIcon(solidIcon, "bxs-network-chart") }
func BiSolidNews() icons.IsIcon               { return newIcon(solidIcon, "bxs-news") }
func BiSolidNoEntry() icons.IsIcon            { return newIcon(solidIcon, "bxs-no-entry") }
func BiSolidNote() icons.IsIcon               { return newIcon(solidIcon, "bxs-note") }
func BiSolidNotepad() icons.IsIcon            { return newIcon(solidIcon, "bxs-notepad") }
func BiSolidNotificationOff() icons.IsIcon    { return newIcon(solidIcon, "bxs-notification-off") }
func BiSolidNotification() icons.IsIcon       { return newIcon(solidIcon, "bxs-notification") }
func BiSolidObjectsHorizontalCenter() icons.IsIcon {
	return newIcon(solidIcon, "bxs-objects-horizontal-center")
}
func BiSolidObjectsHorizontalLeft() icons.IsIcon {
	return newIcon(solidIcon, "bxs-objects-horizontal-left")
}
func BiSolidObjectsHorizontalRight() icons.IsIcon {
	return newIcon(solidIcon, "bxs-objects-horizontal-right")
}
func BiSolidObjectsVerticalBottom() icons.IsIcon {
	return newIcon(solidIcon, "bxs-objects-vertical-bottom")
}
func BiSolidObjectsVerticalCenter() icons.IsIcon {
	return newIcon(solidIcon, "bxs-objects-vertical-center")
}
func BiSolidObjectsVerticalTop() icons.IsIcon { return newIcon(solidIcon, "bxs-objects-vertical-top") }
func BiSolidOffer() icons.IsIcon              { return newIcon(solidIcon, "bxs-offer") }
func BiSolidPackage() icons.IsIcon            { return newIcon(solidIcon, "bxs-package") }
func BiSolidPaintRoll() icons.IsIcon          { return newIcon(solidIcon, "bxs-paint-roll") }
func BiSolidPaint() icons.IsIcon              { return newIcon(solidIcon, "bxs-paint") }
func BiSolidPalette() icons.IsIcon            { return newIcon(solidIcon, "bxs-palette") }
func BiSolidPaperPlane() icons.IsIcon         { return newIcon(solidIcon, "bxs-paper-plane") }
func BiSolidParking() icons.IsIcon            { return newIcon(solidIcon, "bxs-parking") }
func BiSolidParty() icons.IsIcon              { return newIcon(solidIcon, "bxs-party") }
func BiSolidPaste() icons.IsIcon              { return newIcon(solidIcon, "bxs-paste") }
func BiSolidPear() icons.IsIcon               { return newIcon(solidIcon, "bxs-pear") }
func BiSolidPen() icons.IsIcon                { return newIcon(solidIcon, "bxs-pen") }
func BiSolidPencil() icons.IsIcon             { return newIcon(solidIcon, "bxs-pencil") }
func BiSolidPhoneCall() icons.IsIcon          { return newIcon(solidIcon, "bxs-phone-call") }
func BiSolidPhoneIncoming() icons.IsIcon      { return newIcon(solidIcon, "bxs-phone-incoming") }
func BiSolidPhoneOff() icons.IsIcon           { return newIcon(solidIcon, "bxs-phone-off") }
func BiSolidPhoneOutgoing() icons.IsIcon      { return newIcon(solidIcon, "bxs-phone-outgoing") }
func BiSolidPhone() icons.IsIcon              { return newIcon(solidIcon, "bxs-phone") }
func BiSolidPhotoAlbum() icons.IsIcon         { return newIcon(solidIcon, "bxs-photo-album") }
func BiSolidPiano() icons.IsIcon              { return newIcon(solidIcon, "bxs-piano") }
func BiSolidPieChartAlt2() icons.IsIcon       { return newIcon(solidIcon, "bxs-pie-chart-alt-2") }
func BiSolidPieChartAlt() icons.IsIcon        { return newIcon(solidIcon, "bxs-pie-chart-alt") }
func BiSolidPieChart() icons.IsIcon           { return newIcon(solidIcon, "bxs-pie-chart") }
func BiSolidPin() icons.IsIcon                { return newIcon(solidIcon, "bxs-pin") }
func BiSolidPizza() icons.IsIcon              { return newIcon(solidIcon, "bxs-pizza") }
func BiSolidPlaneAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-plane-alt") }
func BiSolidPlaneLand() icons.IsIcon          { return newIcon(solidIcon, "bxs-plane-land") }
func BiSolidPlaneTakeOff() icons.IsIcon       { return newIcon(solidIcon, "bxs-plane-take-off") }
func BiSolidPlane() icons.IsIcon              { return newIcon(solidIcon, "bxs-plane") }
func BiSolidPlanet() icons.IsIcon             { return newIcon(solidIcon, "bxs-planet") }
func BiSolidPlaylist() icons.IsIcon           { return newIcon(solidIcon, "bxs-playlist") }
func BiSolidPlug() icons.IsIcon               { return newIcon(solidIcon, "bxs-plug") }
func BiSolidPlusCircle() icons.IsIcon         { return newIcon(solidIcon, "bxs-plus-circle") }
func BiSolidPlusSquare() icons.IsIcon         { return newIcon(solidIcon, "bxs-plus-square") }
func BiSolidPointer() icons.IsIcon            { return newIcon(solidIcon, "bxs-pointer") }
func BiSolidPolygon() icons.IsIcon            { return newIcon(solidIcon, "bxs-polygon") }
func BiSolidPopsicle() icons.IsIcon           { return newIcon(solidIcon, "bxs-popsicle") }
func BiSolidPrinter() icons.IsIcon            { return newIcon(solidIcon, "bxs-printer") }
func BiSolidPurchaseTagAlt() icons.IsIcon     { return newIcon(solidIcon, "bxs-purchase-tag-alt") }
func BiSolidPurchaseTag() icons.IsIcon        { return newIcon(solidIcon, "bxs-purchase-tag") }
func BiSolidPyramid() icons.IsIcon            { return newIcon(solidIcon, "bxs-pyramid") }
func BiSolidQuoteAltLeft() icons.IsIcon       { return newIcon(solidIcon, "bxs-quote-alt-left") }
func BiSolidQuoteAltRight() icons.IsIcon      { return newIcon(solidIcon, "bxs-quote-alt-right") }
func BiSolidQuoteLeft() icons.IsIcon          { return newIcon(solidIcon, "bxs-quote-left") }
func BiSolidQuoteRight() icons.IsIcon         { return newIcon(solidIcon, "bxs-quote-right") }
func BiSolidQuoteSingleLeft() icons.IsIcon    { return newIcon(solidIcon, "bxs-quote-single-left") }
func BiSolidQuoteSingleRight() icons.IsIcon   { return newIcon(solidIcon, "bxs-quote-single-right") }
func BiSolidRadiation() icons.IsIcon          { return newIcon(solidIcon, "bxs-radiation") }
func BiSolidRadio() icons.IsIcon              { return newIcon(solidIcon, "bxs-radio") }
func BiSolidReceipt() icons.IsIcon            { return newIcon(solidIcon, "bxs-receipt") }
func BiSolidRectangle() icons.IsIcon          { return newIcon(solidIcon, "bxs-rectangle") }
func BiSolidRegistered() icons.IsIcon         { return newIcon(solidIcon, "bxs-registered") }
func BiSolidRename() icons.IsIcon             { return newIcon(solidIcon, "bxs-rename") }
func BiSolidReport() icons.IsIcon             { return newIcon(solidIcon, "bxs-report") }
func BiSolidRewindCircle() icons.IsIcon       { return newIcon(solidIcon, "bxs-rewind-circle") }
func BiSolidRightArrowAlt() icons.IsIcon      { return newIcon(solidIcon, "bxs-right-arrow-alt") }
func BiSolidRightArrowCircle() icons.IsIcon   { return newIcon(solidIcon, "bxs-right-arrow-circle") }
func BiSolidRightArrowSquare() icons.IsIcon   { return newIcon(solidIcon, "bxs-right-arrow-square") }
func BiSolidRightArrow() icons.IsIcon         { return newIcon(solidIcon, "bxs-right-arrow") }
func BiSolidRightDownArrowCircle() icons.IsIcon {
	return newIcon(solidIcon, "bxs-right-down-arrow-circle")
}
func BiSolidRightTopArrowCircle() icons.IsIcon {
	return newIcon(solidIcon, "bxs-right-top-arrow-circle")
}
func BiSolidRocket() icons.IsIcon             { return newIcon(solidIcon, "bxs-rocket") }
func BiSolidRuler() icons.IsIcon              { return newIcon(solidIcon, "bxs-ruler") }
func BiSolidSad() icons.IsIcon                { return newIcon(solidIcon, "bxs-sad") }
func BiSolidSave() icons.IsIcon               { return newIcon(solidIcon, "bxs-save") }
func BiSolidSchool() icons.IsIcon             { return newIcon(solidIcon, "bxs-school") }
func BiSolidSearchAlt2() icons.IsIcon         { return newIcon(solidIcon, "bxs-search-alt-2") }
func BiSolidSearch() icons.IsIcon             { return newIcon(solidIcon, "bxs-search") }
func BiSolidSelectMultiple() icons.IsIcon     { return newIcon(solidIcon, "bxs-select-multiple") }
func BiSolidSend() icons.IsIcon               { return newIcon(solidIcon, "bxs-send") }
func BiSolidServer() icons.IsIcon             { return newIcon(solidIcon, "bxs-server") }
func BiSolidShapes() icons.IsIcon             { return newIcon(solidIcon, "bxs-shapes") }
func BiSolidShareAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-share-alt") }
func BiSolidShare() icons.IsIcon              { return newIcon(solidIcon, "bxs-share") }
func BiSolidShieldAlt2() icons.IsIcon         { return newIcon(solidIcon, "bxs-shield-alt-2") }
func BiSolidShieldMinus() icons.IsIcon        { return newIcon(solidIcon, "bxs-shield-minus") }
func BiSolidShieldPlus() icons.IsIcon         { return newIcon(solidIcon, "bxs-shield-plus") }
func BiSolidShieldX() icons.IsIcon            { return newIcon(solidIcon, "bxs-shield-x") }
func BiSolidShield() icons.IsIcon             { return newIcon(solidIcon, "bxs-shield") }
func BiSolidShip() icons.IsIcon               { return newIcon(solidIcon, "bxs-ship") }
func BiSolidShocked() icons.IsIcon            { return newIcon(solidIcon, "bxs-shocked") }
func BiSolidShoppingBagAlt() icons.IsIcon     { return newIcon(solidIcon, "bxs-shopping-bag-alt") }
func BiSolidShoppingBag() icons.IsIcon        { return newIcon(solidIcon, "bxs-shopping-bag") }
func BiSolidShoppingBags() icons.IsIcon       { return newIcon(solidIcon, "bxs-shopping-bags") }
func BiSolidShow() icons.IsIcon               { return newIcon(solidIcon, "bxs-show") }
func BiSolidShower() icons.IsIcon             { return newIcon(solidIcon, "bxs-shower") }
func BiSolidSkipNextCircle() icons.IsIcon     { return newIcon(solidIcon, "bxs-skip-next-circle") }
func BiSolidSkipPreviousCircle() icons.IsIcon { return newIcon(solidIcon, "bxs-skip-previous-circle") }
func BiSolidSkull() icons.IsIcon              { return newIcon(solidIcon, "bxs-skull") }
func BiSolidSleepy() icons.IsIcon             { return newIcon(solidIcon, "bxs-sleepy") }
func BiSolidSlideshow() icons.IsIcon          { return newIcon(solidIcon, "bxs-slideshow") }
func BiSolidSmile() icons.IsIcon              { return newIcon(solidIcon, "bxs-smile") }
func BiSolidSortAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-sort-alt") }
func BiSolidSpa() icons.IsIcon                { return newIcon(solidIcon, "bxs-spa") }
func BiSolidSpeaker() icons.IsIcon            { return newIcon(solidIcon, "bxs-speaker") }
func BiSolidSprayCan() icons.IsIcon           { return newIcon(solidIcon, "bxs-spray-can") }
func BiSolidSpreadsheet() icons.IsIcon        { return newIcon(solidIcon, "bxs-spreadsheet") }
func BiSolidSquareRounded() icons.IsIcon      { return newIcon(solidIcon, "bxs-square-rounded") }
func BiSolidSquare() icons.IsIcon             { return newIcon(solidIcon, "bxs-square") }
func BiSolidStarHalf() icons.IsIcon           { return newIcon(solidIcon, "bxs-star-half") }
func BiSolidStar() icons.IsIcon               { return newIcon(solidIcon, "bxs-star") }
func BiSolidSticker() icons.IsIcon            { return newIcon(solidIcon, "bxs-sticker") }
func BiSolidStopwatch() icons.IsIcon          { return newIcon(solidIcon, "bxs-stopwatch") }
func BiSolidStoreAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-store-alt") }
func BiSolidStore() icons.IsIcon              { return newIcon(solidIcon, "bxs-store") }
func BiSolidSun() icons.IsIcon                { return newIcon(solidIcon, "bxs-sun") }
func BiSolidSushi() icons.IsIcon              { return newIcon(solidIcon, "bxs-sushi") }
func BiSolidTShirt() icons.IsIcon             { return newIcon(solidIcon, "bxs-t-shirt") }
func BiSolidTachometer() icons.IsIcon         { return newIcon(solidIcon, "bxs-tachometer") }
func BiSolidTagAlt() icons.IsIcon             { return newIcon(solidIcon, "bxs-tag-alt") }
func BiSolidTagX() icons.IsIcon               { return newIcon(solidIcon, "bxs-tag-x") }
func BiSolidTag() icons.IsIcon                { return newIcon(solidIcon, "bxs-tag") }
func BiSolidTaxi() icons.IsIcon               { return newIcon(solidIcon, "bxs-taxi") }
func BiSolidTennisBall() icons.IsIcon         { return newIcon(solidIcon, "bxs-tennis-ball") }
func BiSolidTerminal() icons.IsIcon           { return newIcon(solidIcon, "bxs-terminal") }
func BiSolidThermometer() icons.IsIcon        { return newIcon(solidIcon, "bxs-thermometer") }
func BiSolidTimeFive() icons.IsIcon           { return newIcon(solidIcon, "bxs-time-five") }
func BiSolidTime() icons.IsIcon               { return newIcon(solidIcon, "bxs-time") }
func BiSolidTimer() icons.IsIcon              { return newIcon(solidIcon, "bxs-timer") }
func BiSolidTired() icons.IsIcon              { return newIcon(solidIcon, "bxs-tired") }
func BiSolidToTop() icons.IsIcon              { return newIcon(solidIcon, "bxs-to-top") }
func BiSolidToggleLeft() icons.IsIcon         { return newIcon(solidIcon, "bxs-toggle-left") }
func BiSolidToggleRight() icons.IsIcon        { return newIcon(solidIcon, "bxs-toggle-right") }
func BiSolidTone() icons.IsIcon               { return newIcon(solidIcon, "bxs-tone") }
func BiSolidTorch() icons.IsIcon              { return newIcon(solidIcon, "bxs-torch") }
func BiSolidTrafficBarrier() icons.IsIcon     { return newIcon(solidIcon, "bxs-traffic-barrier") }
func BiSolidTrafficCone() icons.IsIcon        { return newIcon(solidIcon, "bxs-traffic-cone") }
func BiSolidTraffic() icons.IsIcon            { return newIcon(solidIcon, "bxs-traffic") }
func BiSolidTrain() icons.IsIcon              { return newIcon(solidIcon, "bxs-train") }
func BiSolidTrashAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-trash-alt") }
func BiSolidTrash() icons.IsIcon              { return newIcon(solidIcon, "bxs-trash") }
func BiSolidTreeAlt() icons.IsIcon            { return newIcon(solidIcon, "bxs-tree-alt") }
func BiSolidTree() icons.IsIcon               { return newIcon(solidIcon, "bxs-tree") }
func BiSolidTrophy() icons.IsIcon             { return newIcon(solidIcon, "bxs-trophy") }
func BiSolidTruck() icons.IsIcon              { return newIcon(solidIcon, "bxs-truck") }
func BiSolidTv() icons.IsIcon                 { return newIcon(solidIcon, "bxs-tv") }
func BiSolidUniversalAccess() icons.IsIcon    { return newIcon(solidIcon, "bxs-universal-access") }
func BiSolidUpArrowAlt() icons.IsIcon         { return newIcon(solidIcon, "bxs-up-arrow-alt") }
func BiSolidUpArrowCircle() icons.IsIcon      { return newIcon(solidIcon, "bxs-up-arrow-circle") }
func BiSolidUpArrowSquare() icons.IsIcon      { return newIcon(solidIcon, "bxs-up-arrow-square") }
func BiSolidUpArrow() icons.IsIcon            { return newIcon(solidIcon, "bxs-up-arrow") }
func BiSolidUpsideDown() icons.IsIcon         { return newIcon(solidIcon, "bxs-upside-down") }
func BiSolidUpvote() icons.IsIcon             { return newIcon(solidIcon, "bxs-upvote") }
func BiSolidUserAccount() icons.IsIcon        { return newIcon(solidIcon, "bxs-user-account") }
func BiSolidUserBadge() icons.IsIcon          { return newIcon(solidIcon, "bxs-user-badge") }
func BiSolidUserCheck() icons.IsIcon          { return newIcon(solidIcon, "bxs-user-check") }
func BiSolidUserCircle() icons.IsIcon         { return newIcon(solidIcon, "bxs-user-circle") }
func BiSolidUserDetail() icons.IsIcon         { return newIcon(solidIcon, "bxs-user-detail") }
func BiSolidUserMinus() icons.IsIcon          { return newIcon(solidIcon, "bxs-user-minus") }
func BiSolidUserPin() icons.IsIcon            { return newIcon(solidIcon, "bxs-user-pin") }
func BiSolidUserPlus() icons.IsIcon           { return newIcon(solidIcon, "bxs-user-plus") }
func BiSolidUserRectangle() icons.IsIcon      { return newIcon(solidIcon, "bxs-user-rectangle") }
func BiSolidUserVoice() icons.IsIcon          { return newIcon(solidIcon, "bxs-user-voice") }
func BiSolidUserX() icons.IsIcon              { return newIcon(solidIcon, "bxs-user-x") }
func BiSolidUser() icons.IsIcon               { return newIcon(solidIcon, "bxs-user") }
func BiSolidVector() icons.IsIcon             { return newIcon(solidIcon, "bxs-vector") }
func BiSolidVial() icons.IsIcon               { return newIcon(solidIcon, "bxs-vial") }
func BiSolidVideoOff() icons.IsIcon           { return newIcon(solidIcon, "bxs-video-off") }
func BiSolidVideoPlus() icons.IsIcon          { return newIcon(solidIcon, "bxs-video-plus") }
func BiSolidVideoRecording() icons.IsIcon     { return newIcon(solidIcon, "bxs-video-recording") }
func BiSolidVideo() icons.IsIcon              { return newIcon(solidIcon, "bxs-video") }
func BiSolidVideos() icons.IsIcon             { return newIcon(solidIcon, "bxs-videos") }
func BiSolidVirusBlock() icons.IsIcon         { return newIcon(solidIcon, "bxs-virus-block") }
func BiSolidVirus() icons.IsIcon              { return newIcon(solidIcon, "bxs-virus") }
func BiSolidVolumeFull() icons.IsIcon         { return newIcon(solidIcon, "bxs-volume-full") }
func BiSolidVolumeLow() icons.IsIcon          { return newIcon(solidIcon, "bxs-volume-low") }
func BiSolidVolumeMute() icons.IsIcon         { return newIcon(solidIcon, "bxs-volume-mute") }
func BiSolidVolume() icons.IsIcon             { return newIcon(solidIcon, "bxs-volume") }
func BiSolidWalletAlt() icons.IsIcon          { return newIcon(solidIcon, "bxs-wallet-alt") }
func BiSolidWallet() icons.IsIcon             { return newIcon(solidIcon, "bxs-wallet") }
func BiSolidWasher() icons.IsIcon             { return newIcon(solidIcon, "bxs-washer") }
func BiSolidWatchAlt() icons.IsIcon           { return newIcon(solidIcon, "bxs-watch-alt") }
func BiSolidWatch() icons.IsIcon              { return newIcon(solidIcon, "bxs-watch") }
func BiSolidWebcam() icons.IsIcon             { return newIcon(solidIcon, "bxs-webcam") }
func BiSolidWidget() icons.IsIcon             { return newIcon(solidIcon, "bxs-widget") }
func BiSolidWindowAlt() icons.IsIcon          { return newIcon(solidIcon, "bxs-window-alt") }
func BiSolidWine() icons.IsIcon               { return newIcon(solidIcon, "bxs-wine") }
func BiSolidWinkSmile() icons.IsIcon          { return newIcon(solidIcon, "bxs-wink-smile") }
func BiSolidWinkTongue() icons.IsIcon         { return newIcon(solidIcon, "bxs-wink-tongue") }
func BiSolidWrench() icons.IsIcon             { return newIcon(solidIcon, "bxs-wrench") }
func BiSolidXCircle() icons.IsIcon            { return newIcon(solidIcon, "bxs-x-circle") }
func BiSolidXSquare() icons.IsIcon            { return newIcon(solidIcon, "bxs-x-square") }
func BiSolidYinYang() icons.IsIcon            { return newIcon(solidIcon, "bxs-yin-yang") }
func BiSolidZap() icons.IsIcon                { return newIcon(solidIcon, "bxs-zap") }
func BiSolidZoomIn() icons.IsIcon             { return newIcon(solidIcon, "bxs-zoom-in") }
func BiSolidZoomOut() icons.IsIcon            { return newIcon(solidIcon, "bxs-zoom-out") }
