package li

import "github.com/raitucarp/gomix/icons"

func Li500Px() icons.IsIcon                { return newIcon("500px") }
func LiAdobe() icons.IsIcon                { return newIcon("adobe") }
func LiAdonis() icons.IsIcon               { return newIcon("adonis") }
func LiAeroplane1() icons.IsIcon           { return newIcon("aeroplane-1") }
func LiAgenda() icons.IsIcon               { return newIcon("agenda") }
func LiAirbnb() icons.IsIcon               { return newIcon("airbnb") }
func LiAirtable() icons.IsIcon             { return newIcon("airtable") }
func LiAlarm1() icons.IsIcon               { return newIcon("alarm-1") }
func LiAlignTextCenter() icons.IsIcon      { return newIcon("align-text-center") }
func LiAlignTextLeft() icons.IsIcon        { return newIcon("align-text-left") }
func LiAlignTextRight() icons.IsIcon       { return newIcon("align-text-right") }
func LiAlpinejs() icons.IsIcon             { return newIcon("alpinejs") }
func LiAmazonOriginal() icons.IsIcon       { return newIcon("amazon-original") }
func LiAmazonPay() icons.IsIcon            { return newIcon("amazon-pay") }
func LiAmazon() icons.IsIcon               { return newIcon("amazon") }
func LiAmbulance1() icons.IsIcon           { return newIcon("ambulance-1") }
func LiAmd() icons.IsIcon                  { return newIcon("amd") }
func LiAmex() icons.IsIcon                 { return newIcon("amex") }
func LiAnchor() icons.IsIcon               { return newIcon("anchor") }
func LiAndroidOld() icons.IsIcon           { return newIcon("android-old") }
func LiAndroid() icons.IsIcon              { return newIcon("android") }
func LiAngellist() icons.IsIcon            { return newIcon("angellist") }
func LiAngleDoubleDown() icons.IsIcon      { return newIcon("angle-double-down") }
func LiAngleDoubleLeft() icons.IsIcon      { return newIcon("angle-double-left") }
func LiAngleDoubleRight() icons.IsIcon     { return newIcon("angle-double-right") }
func LiAngleDoubleUp() icons.IsIcon        { return newIcon("angle-double-up") }
func LiAngular() icons.IsIcon              { return newIcon("angular") }
func LiAppStore() icons.IsIcon             { return newIcon("app-store") }
func LiAppleBrand() icons.IsIcon           { return newIcon("apple-brand") }
func LiAppleMusicAlt() icons.IsIcon        { return newIcon("apple-music-alt") }
func LiAppleMusic() icons.IsIcon           { return newIcon("apple-music") }
func LiApplePay() icons.IsIcon             { return newIcon("apple-pay") }
func LiArcBrowser() icons.IsIcon           { return newIcon("arc-browser") }
func LiArrowAllDirection() icons.IsIcon    { return newIcon("arrow-all-direction") }
func LiArrowAngularTopLeft() icons.IsIcon  { return newIcon("arrow-angular-top-left") }
func LiArrowAngularTopRight() icons.IsIcon { return newIcon("arrow-angular-top-right") }
func LiArrowBothDirectionHorizontal1() icons.IsIcon {
	return newIcon("arrow-both-direction-horizontal-1")
}
func LiArrowBothDirectionVertical1() icons.IsIcon { return newIcon("arrow-both-direction-vertical-1") }
func LiArrowDownward() icons.IsIcon               { return newIcon("arrow-downward") }
func LiArrowLeftCircle() icons.IsIcon             { return newIcon("arrow-left-circle") }
func LiArrowLeft() icons.IsIcon                   { return newIcon("arrow-left") }
func LiArrowRightCircle() icons.IsIcon            { return newIcon("arrow-right-circle") }
func LiArrowRight() icons.IsIcon                  { return newIcon("arrow-right") }
func LiArrowUpward() icons.IsIcon                 { return newIcon("arrow-upward") }
func LiAsana() icons.IsIcon                       { return newIcon("asana") }
func LiAstro() icons.IsIcon                       { return newIcon("astro") }
func LiAtlassian() icons.IsIcon                   { return newIcon("atlassian") }
func LiAudiAlt() icons.IsIcon                     { return newIcon("audi-alt") }
func LiAudi() icons.IsIcon                        { return newIcon("audi") }
func LiAws() icons.IsIcon                         { return newIcon("aws") }
func LiAzure() icons.IsIcon                       { return newIcon("azure") }
func LiBadgeDecagramPercent() icons.IsIcon        { return newIcon("badge-decagram-percent") }
func LiBalloons() icons.IsIcon                    { return newIcon("balloons") }
func LiBan2() icons.IsIcon                        { return newIcon("ban-2") }
func LiBarChart4() icons.IsIcon                   { return newIcon("bar-chart-4") }
func LiBarChartDollar() icons.IsIcon              { return newIcon("bar-chart-dollar") }
func LiBasketShopping3() icons.IsIcon             { return newIcon("basket-shopping-3") }
func LiBeat() icons.IsIcon                        { return newIcon("beat") }
func LiBehance() icons.IsIcon                     { return newIcon("behance") }
func LiBell1() icons.IsIcon                       { return newIcon("bell-1") }
func LiBike() icons.IsIcon                        { return newIcon("bike") }
func LiBing() icons.IsIcon                        { return newIcon("bing") }
func LiBitbucket() icons.IsIcon                   { return newIcon("bitbucket") }
func LiBitcoin() icons.IsIcon                     { return newIcon("bitcoin") }
func LiBittorrent() icons.IsIcon                  { return newIcon("bittorrent") }
func LiBloggerAlt() icons.IsIcon                  { return newIcon("blogger-alt") }
func LiBlogger() icons.IsIcon                     { return newIcon("blogger") }
func LiBluetoothLogo() icons.IsIcon               { return newIcon("bluetooth-logo") }
func LiBluetooth() icons.IsIcon                   { return newIcon("bluetooth") }
func LiBmw() icons.IsIcon                         { return newIcon("bmw") }
func LiBoardWriting3() icons.IsIcon               { return newIcon("board-writing-3") }
func LiBold() icons.IsIcon                        { return newIcon("bold") }
func LiBolt2() icons.IsIcon                       { return newIcon("bolt-2") }
func LiBolt3() icons.IsIcon                       { return newIcon("bolt-3") }
func LiBook1() icons.IsIcon                       { return newIcon("book-1") }
func LiBookmark1() icons.IsIcon                   { return newIcon("bookmark-1") }
func LiBookmarkCircle() icons.IsIcon              { return newIcon("bookmark-circle") }
func LiBooks2() icons.IsIcon                      { return newIcon("books-2") }
func LiBootstrap5Square() icons.IsIcon            { return newIcon("bootstrap-5-square") }
func LiBootstrap5() icons.IsIcon                  { return newIcon("bootstrap-5") }
func LiBoxArchive1() icons.IsIcon                 { return newIcon("box-archive-1") }
func LiBoxClosed() icons.IsIcon                   { return newIcon("box-closed") }
func LiBoxGift1() icons.IsIcon                    { return newIcon("box-gift-1") }
func LiBrave() icons.IsIcon                       { return newIcon("brave") }
func LiBricks() icons.IsIcon                      { return newIcon("bricks") }
func LiBridge3() icons.IsIcon                     { return newIcon("bridge-3") }
func LiBriefcase1() icons.IsIcon                  { return newIcon("briefcase-1") }
func LiBriefcase2() icons.IsIcon                  { return newIcon("briefcase-2") }
func LiBriefcasePlus1() icons.IsIcon              { return newIcon("briefcase-plus-1") }
func LiBrush1Rotated() icons.IsIcon               { return newIcon("brush-1-rotated") }
func LiBrush2() icons.IsIcon                      { return newIcon("brush-2") }
func LiBtc() icons.IsIcon                         { return newIcon("btc") }
func LiBug1() icons.IsIcon                        { return newIcon("bug-1") }
func LiBuildings1() icons.IsIcon                  { return newIcon("buildings-1") }
func LiBulb2() icons.IsIcon                       { return newIcon("bulb-2") }
func LiBulb4() icons.IsIcon                       { return newIcon("bulb-4") }
func LiBurger1() icons.IsIcon                     { return newIcon("burger-1") }
func LiBurgerDrink() icons.IsIcon                 { return newIcon("burger-drink") }
func LiBus1() icons.IsIcon                        { return newIcon("bus-1") }
func LiBusketBall() icons.IsIcon                  { return newIcon("busket-ball") }
func LiCake1() icons.IsIcon                       { return newIcon("cake-1") }
func LiCalculator1() icons.IsIcon                 { return newIcon("calculator-1") }
func LiCalculator2() icons.IsIcon                 { return newIcon("calculator-2") }
func LiCalendarDays() icons.IsIcon                { return newIcon("calendar-days") }
func LiCamera1() icons.IsIcon                     { return newIcon("camera-1") }
func LiCameraMovie1() icons.IsIcon                { return newIcon("camera-movie-1") }
func LiCandyCane2() icons.IsIcon                  { return newIcon("candy-cane-2") }
func LiCandyRound1() icons.IsIcon                 { return newIcon("candy-round-1") }
func LiCanva() icons.IsIcon                       { return newIcon("canva") }
func LiCapsule1() icons.IsIcon                    { return newIcon("capsule-1") }
func LiCar2() icons.IsIcon                        { return newIcon("car-2") }
func LiCar4() icons.IsIcon                        { return newIcon("car-4") }
func LiCar6() icons.IsIcon                        { return newIcon("car-6") }
func LiCaravan1() icons.IsIcon                    { return newIcon("caravan-1") }
func LiCart1() icons.IsIcon                       { return newIcon("cart-1") }
func LiCart2() icons.IsIcon                       { return newIcon("cart-2") }
func LiCashApp() icons.IsIcon                     { return newIcon("cash-app") }
func LiCertificateBadge1() icons.IsIcon           { return newIcon("certificate-badge-1") }
func LiChatBubble2() icons.IsIcon                 { return newIcon("chat-bubble-2") }
func LiCheckCircle1() icons.IsIcon                { return newIcon("check-circle-1") }
func LiCheckSquare2() icons.IsIcon                { return newIcon("check-square-2") }
func LiCheck() icons.IsIcon                       { return newIcon("check") }
func LiChevronDownCircle() icons.IsIcon           { return newIcon("chevron-down-circle") }
func LiChevronDown() icons.IsIcon                 { return newIcon("chevron-down") }
func LiChevronLeftCircle() icons.IsIcon           { return newIcon("chevron-left-circle") }
func LiChevronLeft() icons.IsIcon                 { return newIcon("chevron-left") }
func LiChevronRightCircle() icons.IsIcon          { return newIcon("chevron-right-circle") }
func LiChevronUpCircle() icons.IsIcon             { return newIcon("chevron-up-circle") }
func LiChevronUp() icons.IsIcon                   { return newIcon("chevron-up") }
func LiChrome() icons.IsIcon                      { return newIcon("chrome") }
func LiChromecast() icons.IsIcon                  { return newIcon("chromecast") }
func LiCisco() icons.IsIcon                       { return newIcon("cisco") }
func LiClaude() icons.IsIcon                      { return newIcon("claude") }
func LiClickup() icons.IsIcon                     { return newIcon("clickup") }
func LiClipboard() icons.IsIcon                   { return newIcon("clipboard") }
func LiCloud2() icons.IsIcon                      { return newIcon("cloud-2") }
func LiCloudBolt1() icons.IsIcon                  { return newIcon("cloud-bolt-1") }
func LiCloudBolt2() icons.IsIcon                  { return newIcon("cloud-bolt-2") }
func LiCloudCheckCircle() icons.IsIcon            { return newIcon("cloud-check-circle") }
func LiCloudDownload() icons.IsIcon               { return newIcon("cloud-download") }
func LiCloudIot2() icons.IsIcon                   { return newIcon("cloud-iot-2") }
func LiCloudRain() icons.IsIcon                   { return newIcon("cloud-rain") }
func LiCloudRefreshClockwise() icons.IsIcon       { return newIcon("cloud-refresh-clockwise") }
func LiCloudSun() icons.IsIcon                    { return newIcon("cloud-sun") }
func LiCloudUpload() icons.IsIcon                 { return newIcon("cloud-upload") }
func LiCloudflare() icons.IsIcon                  { return newIcon("cloudflare") }
func LiCode1() icons.IsIcon                       { return newIcon("code-1") }
func LiCodeS() icons.IsIcon                       { return newIcon("code-s") }
func LiCodepen() icons.IsIcon                     { return newIcon("codepen") }
func LiCoffeeCup2() icons.IsIcon                  { return newIcon("coffee-cup-2") }
func LiCoinbase() icons.IsIcon                    { return newIcon("coinbase") }
func LiColourPalette3() icons.IsIcon              { return newIcon("colour-palette-3") }
func LiComment1Share() icons.IsIcon               { return newIcon("comment-1-share") }
func LiComment1Text() icons.IsIcon                { return newIcon("comment-1-text") }
func LiComment1() icons.IsIcon                    { return newIcon("comment-1") }
func LiCompassDrafting2() icons.IsIcon            { return newIcon("compass-drafting-2") }
func LiConnectdevelop() icons.IsIcon              { return newIcon("connectdevelop") }
func LiCopilot() icons.IsIcon                     { return newIcon("copilot") }
func LiCoral() icons.IsIcon                       { return newIcon("coral") }
func LiCpanel() icons.IsIcon                      { return newIcon("cpanel") }
func LiCrane4() icons.IsIcon                      { return newIcon("crane-4") }
func LiCreativeCommons() icons.IsIcon             { return newIcon("creative-commons") }
func LiCreditCardMultiple() icons.IsIcon          { return newIcon("credit-card-multiple") }
func LiCrop2() icons.IsIcon                       { return newIcon("crop-2") }
func LiCrown3() icons.IsIcon                      { return newIcon("crown-3") }
func LiCss3() icons.IsIcon                        { return newIcon("css3") }
func LiDashboardSquare1() icons.IsIcon            { return newIcon("dashboard-square-1") }
func LiDatabase2() icons.IsIcon                   { return newIcon("database-2") }
func LiDeno() icons.IsIcon                        { return newIcon("deno") }
func LiDev() icons.IsIcon                         { return newIcon("dev") }
func LiDialogflow() icons.IsIcon                  { return newIcon("dialogflow") }
func LiDiamonds1() icons.IsIcon                   { return newIcon("diamonds-1") }
func LiDiamonds2() icons.IsIcon                   { return newIcon("diamonds-2") }
func LiDigitalocean() icons.IsIcon                { return newIcon("digitalocean") }
func LiDinersClub() icons.IsIcon                  { return newIcon("diners-club") }
func LiDirectionLtr() icons.IsIcon                { return newIcon("direction-ltr") }
func LiDirectionRtl() icons.IsIcon                { return newIcon("direction-rtl") }
func LiDiscordChat() icons.IsIcon                 { return newIcon("discord-chat") }
func LiDiscord() icons.IsIcon                     { return newIcon("discord") }
func LiDiscover() icons.IsIcon                    { return newIcon("discover") }
func LiDocker() icons.IsIcon                      { return newIcon("docker") }
func LiDollarCircle() icons.IsIcon                { return newIcon("dollar-circle") }
func LiDollar() icons.IsIcon                      { return newIcon("dollar") }
func LiDoubleQuotesEnd1() icons.IsIcon            { return newIcon("double-quotes-end-1") }
func LiDownload1() icons.IsIcon                   { return newIcon("download-1") }
func LiDownloadCircle1() icons.IsIcon             { return newIcon("download-circle-1") }
func LiDribbbleSymbol() icons.IsIcon              { return newIcon("dribbble-symbol") }
func LiDribbble() icons.IsIcon                    { return newIcon("dribbble") }
func LiDrizzle() icons.IsIcon                     { return newIcon("drizzle") }
func LiDropbox() icons.IsIcon                     { return newIcon("dropbox") }
func LiDrupal() icons.IsIcon                      { return newIcon("drupal") }
func LiDumbbell1() icons.IsIcon                   { return newIcon("dumbbell-1") }
func LiEdge() icons.IsIcon                        { return newIcon("edge") }
func LiEmojiExpressionlessFlatEyes() icons.IsIcon { return newIcon("emoji-expressionless-flat-eyes") }
func LiEmojiExpressionless() icons.IsIcon         { return newIcon("emoji-expressionless") }
func LiEmojiGrin() icons.IsIcon                   { return newIcon("emoji-grin") }
func LiEmojiSad() icons.IsIcon                    { return newIcon("emoji-sad") }
func LiEmojiSmileSide() icons.IsIcon              { return newIcon("emoji-smile-side") }
func LiEmojiSmileSunglass() icons.IsIcon          { return newIcon("emoji-smile-sunglass") }
func LiEmojiSmileTongue() icons.IsIcon            { return newIcon("emoji-smile-tongue") }
func LiEmojiSmile() icons.IsIcon                  { return newIcon("emoji-smile") }
func LiEnterDown() icons.IsIcon                   { return newIcon("enter-down") }
func LiEnter() icons.IsIcon                       { return newIcon("enter") }
func LiEnvato() icons.IsIcon                      { return newIcon("envato") }
func LiEnvelope1() icons.IsIcon                   { return newIcon("envelope-1") }
func LiEraser1() icons.IsIcon                     { return newIcon("eraser-1") }
func LiEthereumLogo() icons.IsIcon                { return newIcon("ethereum-logo") }
func LiEuro() icons.IsIcon                        { return newIcon("euro") }
func LiExitUp() icons.IsIcon                      { return newIcon("exit-up") }
func LiExit() icons.IsIcon                        { return newIcon("exit") }
func LiExpandArrow1() icons.IsIcon                { return newIcon("expand-arrow-1") }
func LiExpandSquare4() icons.IsIcon               { return newIcon("expand-square-4") }
func LiExpressjs() icons.IsIcon                   { return newIcon("expressjs") }
func LiEye() icons.IsIcon                         { return newIcon("eye") }
func LiFacebookMessenger() icons.IsIcon           { return newIcon("facebook-messenger") }
func LiFacebookRounded() icons.IsIcon             { return newIcon("facebook-rounded") }
func LiFacebookSquare() icons.IsIcon              { return newIcon("facebook-square") }
func LiFacebook() icons.IsIcon                    { return newIcon("facebook") }
func LiFacetime() icons.IsIcon                    { return newIcon("facetime") }
func LiFigma() icons.IsIcon                       { return newIcon("figma") }
func LiFileFormatZip() icons.IsIcon               { return newIcon("file-format-zip") }
func LiFileMultiple() icons.IsIcon                { return newIcon("file-multiple") }
func LiFilePencil() icons.IsIcon                  { return newIcon("file-pencil") }
func LiFilePlusCircle() icons.IsIcon              { return newIcon("file-plus-circle") }
func LiFileQuestion() icons.IsIcon                { return newIcon("file-question") }
func LiFileXmark() icons.IsIcon                   { return newIcon("file-xmark") }
func LiFirebase() icons.IsIcon                    { return newIcon("firebase") }
func LiFirefox() icons.IsIcon                     { return newIcon("firefox") }
func LiFireworkRocket4() icons.IsIcon             { return newIcon("firework-rocket-4") }
func LiFitbit() icons.IsIcon                      { return newIcon("fitbit") }
func LiFlag1() icons.IsIcon                       { return newIcon("flag-1") }
func LiFlag2() icons.IsIcon                       { return newIcon("flag-2") }
func LiFlickr() icons.IsIcon                      { return newIcon("flickr") }
func LiFloppyDisk1() icons.IsIcon                 { return newIcon("floppy-disk-1") }
func LiFlower2() icons.IsIcon                     { return newIcon("flower-2") }
func LiFlutter() icons.IsIcon                     { return newIcon("flutter") }
func LiFolder1() icons.IsIcon                     { return newIcon("folder-1") }
func LiFord() icons.IsIcon                        { return newIcon("ford") }
func LiFramer() icons.IsIcon                      { return newIcon("framer") }
func LiFunnel1() icons.IsIcon                     { return newIcon("funnel-1") }
func LiGallery() icons.IsIcon                     { return newIcon("gallery") }
func LiGamePadModern1() icons.IsIcon              { return newIcon("game-pad-modern-1") }
func LiGatsby() icons.IsIcon                      { return newIcon("gatsby") }
func LiGauge1() icons.IsIcon                      { return newIcon("gauge-1") }
func LiGear1() icons.IsIcon                       { return newIcon("gear-1") }
func LiGears3() icons.IsIcon                      { return newIcon("gears-3") }
func LiGemini() icons.IsIcon                      { return newIcon("gemini") }
func LiGit() icons.IsIcon                         { return newIcon("git") }
func LiGithub() icons.IsIcon                      { return newIcon("github") }
func LiGlassJuice1() icons.IsIcon                 { return newIcon("glass-juice-1") }
func LiGlobe1() icons.IsIcon                      { return newIcon("globe-1") }
func LiGlobeStand() icons.IsIcon                  { return newIcon("globe-stand") }
func LiGo() icons.IsIcon                          { return newIcon("go") }
func LiGoodreads() icons.IsIcon                   { return newIcon("goodreads") }
func LiGoogleCloud() icons.IsIcon                 { return newIcon("google-cloud") }
func LiGoogleDrive() icons.IsIcon                 { return newIcon("google-drive") }
func LiGoogleMeet() icons.IsIcon                  { return newIcon("google-meet") }
func LiGooglePay() icons.IsIcon                   { return newIcon("google-pay") }
func LiGoogleWallet() icons.IsIcon                { return newIcon("google-wallet") }
func LiGoogle() icons.IsIcon                      { return newIcon("google") }
func LiGraduationCap1() icons.IsIcon              { return newIcon("graduation-cap-1") }
func LiGrammarly() icons.IsIcon                   { return newIcon("grammarly") }
func LiHackerNews() icons.IsIcon                  { return newIcon("hacker-news") }
func LiHammer1() icons.IsIcon                     { return newIcon("hammer-1") }
func LiHammer2() icons.IsIcon                     { return newIcon("hammer-2") }
func LiHandMic() icons.IsIcon                     { return newIcon("hand-mic") }
func LiHandShake() icons.IsIcon                   { return newIcon("hand-shake") }
func LiHandStop() icons.IsIcon                    { return newIcon("hand-stop") }
func LiHandTakingDollar() icons.IsIcon            { return newIcon("hand-taking-dollar") }
func LiHandTakingLeaf1() icons.IsIcon             { return newIcon("hand-taking-leaf-1") }
func LiHandTakingUser() icons.IsIcon              { return newIcon("hand-taking-user") }
func LiHashnode() icons.IsIcon                    { return newIcon("hashnode") }
func LiHatChef3() icons.IsIcon                    { return newIcon("hat-chef-3") }
func LiHeadphone1() icons.IsIcon                  { return newIcon("headphone-1") }
func LiHeart() icons.IsIcon                       { return newIcon("heart") }
func LiHelicopter2() icons.IsIcon                 { return newIcon("helicopter-2") }
func LiHelmetSafety1() icons.IsIcon               { return newIcon("helmet-safety-1") }
func LiHierarchy1() icons.IsIcon                  { return newIcon("hierarchy-1") }
func LiHighlighter1() icons.IsIcon                { return newIcon("highlighter-1") }
func LiHighlighter2() icons.IsIcon                { return newIcon("highlighter-2") }
func LiHome2() icons.IsIcon                       { return newIcon("home-2") }
func LiHospital2() icons.IsIcon                   { return newIcon("hospital-2") }
func LiHourglass() icons.IsIcon                   { return newIcon("hourglass") }
func LiHtml5() icons.IsIcon                       { return newIcon("html5") }
func LiIbm() icons.IsIcon                         { return newIcon("ibm") }
func LiIdCard() icons.IsIcon                      { return newIcon("id-card") }
func LiImdb() icons.IsIcon                        { return newIcon("imdb") }
func LiIndent() icons.IsIcon                      { return newIcon("indent") }
func LiInfo() icons.IsIcon                        { return newIcon("info") }
func LiInjection1() icons.IsIcon                  { return newIcon("injection-1") }
func LiInstagramLogotype() icons.IsIcon           { return newIcon("instagram-logotype") }
func LiInstagram() icons.IsIcon                   { return newIcon("instagram") }
func LiIntel() icons.IsIcon                       { return newIcon("intel") }
func LiIos() icons.IsIcon                         { return newIcon("ios") }
func LiIsland2() icons.IsIcon                     { return newIcon("island-2") }
func LiJaguar() icons.IsIcon                      { return newIcon("jaguar") }
func LiJamstack() icons.IsIcon                    { return newIcon("jamstack") }
func LiJava() icons.IsIcon                        { return newIcon("java") }
func LiJavascript() icons.IsIcon                  { return newIcon("javascript") }
func LiJcb() icons.IsIcon                         { return newIcon("jcb") }
func LiJoomla() icons.IsIcon                      { return newIcon("joomla") }
func LiJsfiddle() icons.IsIcon                    { return newIcon("jsfiddle") }
func LiKey1() icons.IsIcon                        { return newIcon("key-1") }
func LiKeyboard() icons.IsIcon                    { return newIcon("keyboard") }
func LiKnifeFork1() icons.IsIcon                  { return newIcon("knife-fork-1") }
func LiKubernetes() icons.IsIcon                  { return newIcon("kubernetes") }
func LiLabelDollar2() icons.IsIcon                { return newIcon("label-dollar-2") }
func LiLaptop2() icons.IsIcon                     { return newIcon("laptop-2") }
func LiLaptopPhone() icons.IsIcon                 { return newIcon("laptop-phone") }
func LiLaravel() icons.IsIcon                     { return newIcon("laravel") }
func LiLayers1() icons.IsIcon                     { return newIcon("layers-1") }
func LiLayout26() icons.IsIcon                    { return newIcon("layout-26") }
func LiLayout9() icons.IsIcon                     { return newIcon("layout-9") }
func LiLeaf1() icons.IsIcon                       { return newIcon("leaf-1") }
func LiLeaf6() icons.IsIcon                       { return newIcon("leaf-6") }
func LiLemonSqueezy() icons.IsIcon                { return newIcon("lemon-squeezy") }
func LiLifeGuardTube1() icons.IsIcon              { return newIcon("life-guard-tube-1") }
func LiLineDashed() icons.IsIcon                  { return newIcon("line-dashed") }
func LiLineDotted() icons.IsIcon                  { return newIcon("line-dotted") }
func LiLineHeight() icons.IsIcon                  { return newIcon("line-height") }
func LiLine() icons.IsIcon                        { return newIcon("line") }
func LiLineicons() icons.IsIcon                   { return newIcon("lineicons") }
func LiLink2AngularRight() icons.IsIcon           { return newIcon("link-2-angular-right") }
func LiLinkedin() icons.IsIcon                    { return newIcon("linkedin") }
func LiLocationArrowRight() icons.IsIcon          { return newIcon("location-arrow-right") }
func LiLocked1() icons.IsIcon                     { return newIcon("locked-1") }
func LiLocked2() icons.IsIcon                     { return newIcon("locked-2") }
func LiLoom() icons.IsIcon                        { return newIcon("loom") }
func LiMagento() icons.IsIcon                     { return newIcon("magento") }
func LiMagnet() icons.IsIcon                      { return newIcon("magnet") }
func LiMailchimp() icons.IsIcon                   { return newIcon("mailchimp") }
func LiMapMarker1() icons.IsIcon                  { return newIcon("map-marker-1") }
func LiMapMarker5() icons.IsIcon                  { return newIcon("map-marker-5") }
func LiMapPin5() icons.IsIcon                     { return newIcon("map-pin-5") }
func LiMarkdown() icons.IsIcon                    { return newIcon("markdown") }
func LiMastercard() icons.IsIcon                  { return newIcon("mastercard") }
func LiMediumAlt() icons.IsIcon                   { return newIcon("medium-alt") }
func LiMedium() icons.IsIcon                      { return newIcon("medium") }
func LiMegaphone1() icons.IsIcon                  { return newIcon("megaphone-1") }
func LiMenuCheesburger() icons.IsIcon             { return newIcon("menu-cheesburger") }
func LiMenuHamburger1() icons.IsIcon              { return newIcon("menu-hamburger-1") }
func LiMenuMeatballs1() icons.IsIcon              { return newIcon("menu-meatballs-1") }
func LiMenuMeatballs2() icons.IsIcon              { return newIcon("menu-meatballs-2") }
func LiMercedes() icons.IsIcon                    { return newIcon("mercedes") }
func LiMessage2Question() icons.IsIcon            { return newIcon("message-2-question") }
func LiMessage2() icons.IsIcon                    { return newIcon("message-2") }
func LiMessage3Text() icons.IsIcon                { return newIcon("message-3-text") }
func LiMetaAlt() icons.IsIcon                     { return newIcon("meta-alt") }
func LiMeta() icons.IsIcon                        { return newIcon("meta") }
func LiMicrophone1() icons.IsIcon                 { return newIcon("microphone-1") }
func LiMicroscope() icons.IsIcon                  { return newIcon("microscope") }
func LiMicrosoftEdge() icons.IsIcon               { return newIcon("microsoft-edge") }
func LiMicrosoftTeams() icons.IsIcon              { return newIcon("microsoft-teams") }
func LiMicrosoft() icons.IsIcon                   { return newIcon("microsoft") }
func LiMinusCircle() icons.IsIcon                 { return newIcon("minus-circle") }
func LiMinus() icons.IsIcon                       { return newIcon("minus") }
func LiMongodb() icons.IsIcon                     { return newIcon("mongodb") }
func LiMonitorCode() icons.IsIcon                 { return newIcon("monitor-code") }
func LiMonitorMac() icons.IsIcon                  { return newIcon("monitor-mac") }
func LiMonitor() icons.IsIcon                     { return newIcon("monitor") }
func LiMoonHalfRight5() icons.IsIcon              { return newIcon("moon-half-right-5") }
func LiMountains2() icons.IsIcon                  { return newIcon("mountains-2") }
func LiMouse2() icons.IsIcon                      { return newIcon("mouse-2") }
func LiMushroom1() icons.IsIcon                   { return newIcon("mushroom-1") }
func LiMushroom5() icons.IsIcon                   { return newIcon("mushroom-5") }
func LiMusic() icons.IsIcon                       { return newIcon("music") }
func LiMysql() icons.IsIcon                       { return newIcon("mysql") }
func LiNasa() icons.IsIcon                        { return newIcon("nasa") }
func LiNetflix() icons.IsIcon                     { return newIcon("netflix") }
func LiNetlify() icons.IsIcon                     { return newIcon("netlify") }
func LiNextStep2() icons.IsIcon                   { return newIcon("next-step-2") }
func LiNextjs() icons.IsIcon                      { return newIcon("nextjs") }
func LiNike() icons.IsIcon                        { return newIcon("nike") }
func LiNissan() icons.IsIcon                      { return newIcon("nissan") }
func LiNodejsAlt() icons.IsIcon                   { return newIcon("nodejs-alt") }
func LiNodejs() icons.IsIcon                      { return newIcon("nodejs") }
func LiNotebook1() icons.IsIcon                   { return newIcon("notebook-1") }
func LiNotion() icons.IsIcon                      { return newIcon("notion") }
func LiNpm() icons.IsIcon                         { return newIcon("npm") }
func LiNuxt() icons.IsIcon                        { return newIcon("nuxt") }
func LiNvidia() icons.IsIcon                      { return newIcon("nvidia") }
func LiOculus() icons.IsIcon                      { return newIcon("oculus") }
func LiOpenAi() icons.IsIcon                      { return newIcon("open-ai") }
func LiOperaMini() icons.IsIcon                   { return newIcon("opera-mini") }
func LiOracle() icons.IsIcon                      { return newIcon("oracle") }
func LiOutdent() icons.IsIcon                     { return newIcon("outdent") }
func LiPaddle() icons.IsIcon                      { return newIcon("paddle") }
func LiPageBreak1() icons.IsIcon                  { return newIcon("page-break-1") }
func LiPagination() icons.IsIcon                  { return newIcon("pagination") }
func LiPaintBucket() icons.IsIcon                 { return newIcon("paint-bucket") }
func LiPaintRoller1() icons.IsIcon                { return newIcon("paint-roller-1") }
func LiPaperclip1() icons.IsIcon                  { return newIcon("paperclip-1") }
func LiPartyFlags() icons.IsIcon                  { return newIcon("party-flags") }
func LiPartySpray() icons.IsIcon                  { return newIcon("party-spray") }
func LiPatreon() icons.IsIcon                     { return newIcon("patreon") }
func LiPause() icons.IsIcon                       { return newIcon("pause") }
func LiPayoneer() icons.IsIcon                    { return newIcon("payoneer") }
func LiPaypal() icons.IsIcon                      { return newIcon("paypal") }
func LiPenToSquare() icons.IsIcon                 { return newIcon("pen-to-square") }
func LiPencil1() icons.IsIcon                     { return newIcon("pencil-1") }
func LiPepsi() icons.IsIcon                       { return newIcon("pepsi") }
func LiPhone() icons.IsIcon                       { return newIcon("phone") }
func LiPhotos() icons.IsIcon                      { return newIcon("photos") }
func LiPhp() icons.IsIcon                         { return newIcon("php") }
func LiPieChart2() icons.IsIcon                   { return newIcon("pie-chart-2") }
func LiPilcrow() icons.IsIcon                     { return newIcon("pilcrow") }
func LiPimjoLogo() icons.IsIcon                   { return newIcon("pimjo-logo") }
func LiPimjoSymbol() icons.IsIcon                 { return newIcon("pimjo-symbol") }
func LiPinterest() icons.IsIcon                   { return newIcon("pinterest") }
func LiPizza2() icons.IsIcon                      { return newIcon("pizza-2") }
func LiPlaceholderDollar() icons.IsIcon           { return newIcon("placeholder-dollar") }
func LiPlantscale() icons.IsIcon                  { return newIcon("plantscale") }
func LiPlayStore() icons.IsIcon                   { return newIcon("play-store") }
func LiPlay() icons.IsIcon                        { return newIcon("play") }
func LiPlaystation() icons.IsIcon                 { return newIcon("playstation") }
func LiPlug1() icons.IsIcon                       { return newIcon("plug-1") }
func LiPlusCircle() icons.IsIcon                  { return newIcon("plus-circle") }
func LiPlus() icons.IsIcon                        { return newIcon("plus") }
func LiPnpm() icons.IsIcon                        { return newIcon("pnpm") }
func LiPostgresql() icons.IsIcon                  { return newIcon("postgresql") }
func LiPostman() icons.IsIcon                     { return newIcon("postman") }
func LiPound() icons.IsIcon                       { return newIcon("pound") }
func LiPowerButton() icons.IsIcon                 { return newIcon("power-button") }
func LiPreviousStep2() icons.IsIcon               { return newIcon("previous-step-2") }
func LiPrinter() icons.IsIcon                     { return newIcon("printer") }
func LiPrisma() icons.IsIcon                      { return newIcon("prisma") }
func LiProducthunt() icons.IsIcon                 { return newIcon("producthunt") }
func LiProtonMailLogo() icons.IsIcon              { return newIcon("proton-mail-logo") }
func LiProtonMailSymbol() icons.IsIcon            { return newIcon("proton-mail-symbol") }
func LiPython() icons.IsIcon                      { return newIcon("python") }
func LiQuestionMarkCircle() icons.IsIcon          { return newIcon("question-mark-circle") }
func LiQuestionMark() icons.IsIcon                { return newIcon("question-mark") }
func LiQuora() icons.IsIcon                       { return newIcon("quora") }
func LiRadis() icons.IsIcon                       { return newIcon("radis") }
func LiReact() icons.IsIcon                       { return newIcon("react") }
func LiReddit() icons.IsIcon                      { return newIcon("reddit") }
func LiRefreshCircle1Clockwise() icons.IsIcon     { return newIcon("refresh-circle-1-clockwise") }
func LiRefreshDollar1() icons.IsIcon              { return newIcon("refresh-dollar-1") }
func LiRefreshUser1() icons.IsIcon                { return newIcon("refresh-user-1") }
func LiRemixJs() icons.IsIcon                     { return newIcon("remix-js") }
func LiRoad1() icons.IsIcon                       { return newIcon("road-1") }
func LiRocket5() icons.IsIcon                     { return newIcon("rocket-5") }
func LiRoute1() icons.IsIcon                      { return newIcon("route-1") }
func LiRssRight() icons.IsIcon                    { return newIcon("rss-right") }
func LiRuler1() icons.IsIcon                      { return newIcon("ruler-1") }
func LiRulerPen() icons.IsIcon                    { return newIcon("ruler-pen") }
func LiRupee() icons.IsIcon                       { return newIcon("rupee") }
func LiSafari() icons.IsIcon                      { return newIcon("safari") }
func LiSanity() icons.IsIcon                      { return newIcon("sanity") }
func LiSchoolBench1() icons.IsIcon                { return newIcon("school-bench-1") }
func LiSchoolBench2() icons.IsIcon                { return newIcon("school-bench-2") }
func LiScissors1Vertical() icons.IsIcon           { return newIcon("scissors-1-vertical") }
func LiScoter() icons.IsIcon                      { return newIcon("scoter") }
func LiScrollDown2() icons.IsIcon                 { return newIcon("scroll-down-2") }
func LiSearch1() icons.IsIcon                     { return newIcon("search-1") }
func LiSearch2() icons.IsIcon                     { return newIcon("search-2") }
func LiSearchMinus() icons.IsIcon                 { return newIcon("search-minus") }
func LiSearchPlus() icons.IsIcon                  { return newIcon("search-plus") }
func LiSearchText() icons.IsIcon                  { return newIcon("search-text") }
func LiSelectCursor1() icons.IsIcon               { return newIcon("select-cursor-1") }
func LiSeoMonitor() icons.IsIcon                  { return newIcon("seo-monitor") }
func LiServiceBell1() icons.IsIcon                { return newIcon("service-bell-1") }
func LiShare1Circle() icons.IsIcon                { return newIcon("share-1-circle") }
func LiShare1() icons.IsIcon                      { return newIcon("share-1") }
func LiShare2() icons.IsIcon                      { return newIcon("share-2") }
func LiShield2Check() icons.IsIcon                { return newIcon("shield-2-check") }
func LiShield2() icons.IsIcon                     { return newIcon("shield-2") }
func LiShieldDollar() icons.IsIcon                { return newIcon("shield-dollar") }
func LiShiftLeft() icons.IsIcon                   { return newIcon("shift-left") }
func LiShiftRight() icons.IsIcon                  { return newIcon("shift-right") }
func LiShip1() icons.IsIcon                       { return newIcon("ship-1") }
func LiShirt1() icons.IsIcon                      { return newIcon("shirt-1") }
func LiShopify() icons.IsIcon                     { return newIcon("shopify") }
func LiShovel() icons.IsIcon                      { return newIcon("shovel") }
func LiShuffle() icons.IsIcon                     { return newIcon("shuffle") }
func LiSignPostLeft() icons.IsIcon                { return newIcon("sign-post-left") }
func LiSignalApp() icons.IsIcon                   { return newIcon("signal-app") }
func LiSignsPost2() icons.IsIcon                  { return newIcon("signs-post-2") }
func LiSketch() icons.IsIcon                      { return newIcon("sketch") }
func LiSkype() icons.IsIcon                       { return newIcon("skype") }
func LiSlack() icons.IsIcon                       { return newIcon("slack") }
func LiSlice2() icons.IsIcon                      { return newIcon("slice-2") }
func LiSlidersHorizontalSquare2() icons.IsIcon    { return newIcon("sliders-horizontal-square-2") }
func LiSlideshare() icons.IsIcon                  { return newIcon("slideshare") }
func LiSnapchat() icons.IsIcon                    { return newIcon("snapchat") }
func LiSortAlphabetical() icons.IsIcon            { return newIcon("sort-alphabetical") }
func LiSortHighToLow() icons.IsIcon               { return newIcon("sort-high-to-low") }
func LiSoundcloud() icons.IsIcon                  { return newIcon("soundcloud") }
func LiSpacex() icons.IsIcon                      { return newIcon("spacex") }
func LiSpellcheck() icons.IsIcon                  { return newIcon("spellcheck") }
func LiSpinner2Sacle() icons.IsIcon               { return newIcon("spinner-2-sacle") }
func LiSpinner3() icons.IsIcon                    { return newIcon("spinner-3") }
func LiSports() icons.IsIcon                      { return newIcon("sports") }
func LiSpotifyAlt() icons.IsIcon                  { return newIcon("spotify-alt") }
func LiSpotify() icons.IsIcon                     { return newIcon("spotify") }
func LiSquarespace() icons.IsIcon                 { return newIcon("squarespace") }
func LiStackoverflow() icons.IsIcon               { return newIcon("stackoverflow") }
func LiStamp() icons.IsIcon                       { return newIcon("stamp") }
func LiStarFatHalf2() icons.IsIcon                { return newIcon("star-fat-half-2") }
func LiStarFat() icons.IsIcon                     { return newIcon("star-fat") }
func LiStarSharpDisabled() icons.IsIcon           { return newIcon("star-sharp-disabled") }
func LiStatista() icons.IsIcon                    { return newIcon("statista") }
func LiSteam() icons.IsIcon                       { return newIcon("steam") }
func LiStethoscope1() icons.IsIcon                { return newIcon("stethoscope-1") }
func LiStopwatch() icons.IsIcon                   { return newIcon("stopwatch") }
func LiStorageHdd2() icons.IsIcon                 { return newIcon("storage-hdd-2") }
func LiStrikethrough1() icons.IsIcon              { return newIcon("strikethrough-1") }
func LiStripe() icons.IsIcon                      { return newIcon("stripe") }
func LiStumbleupon() icons.IsIcon                 { return newIcon("stumbleupon") }
func LiSun1() icons.IsIcon                        { return newIcon("sun-1") }
func LiSupabase() icons.IsIcon                    { return newIcon("supabase") }
func LiSurfboard2() icons.IsIcon                  { return newIcon("surfboard-2") }
func LiSvelte() icons.IsIcon                      { return newIcon("svelte") }
func LiSwift() icons.IsIcon                       { return newIcon("swift") }
func LiTab() icons.IsIcon                         { return newIcon("tab") }
func LiTailwindcss() icons.IsIcon                 { return newIcon("tailwindcss") }
func LiTargetUser() icons.IsIcon                  { return newIcon("target-user") }
func LiTelegram() icons.IsIcon                    { return newIcon("telegram") }
func LiTelephone1() icons.IsIcon                  { return newIcon("telephone-1") }
func LiTelephone3() icons.IsIcon                  { return newIcon("telephone-3") }
func LiTesla() icons.IsIcon                       { return newIcon("tesla") }
func LiTextFormatRemove() icons.IsIcon            { return newIcon("text-format-remove") }
func LiTextFormat() icons.IsIcon                  { return newIcon("text-format") }
func LiTextParagraph() icons.IsIcon               { return newIcon("text-paragraph") }
func LiThumbsDown3() icons.IsIcon                 { return newIcon("thumbs-down-3") }
func LiThumbsUp3() icons.IsIcon                   { return newIcon("thumbs-up-3") }
func LiTicket1() icons.IsIcon                     { return newIcon("ticket-1") }
func LiTickets3() icons.IsIcon                    { return newIcon("tickets-3") }
func LiTiktokAlt() icons.IsIcon                   { return newIcon("tiktok-alt") }
func LiTiktok() icons.IsIcon                      { return newIcon("tiktok") }
func LiTowerBroadcast1() icons.IsIcon             { return newIcon("tower-broadcast-1") }
func LiToyota() icons.IsIcon                      { return newIcon("toyota") }
func LiTrain1() icons.IsIcon                      { return newIcon("train-1") }
func LiTrain3() icons.IsIcon                      { return newIcon("train-3") }
func LiTrash3() icons.IsIcon                      { return newIcon("trash-3") }
func LiTree2() icons.IsIcon                       { return newIcon("tree-2") }
func LiTrees3() icons.IsIcon                      { return newIcon("trees-3") }
func LiTrello() icons.IsIcon                      { return newIcon("trello") }
func LiTrendDown1() icons.IsIcon                  { return newIcon("trend-down-1") }
func LiTrendUp1() icons.IsIcon                    { return newIcon("trend-up-1") }
func LiTrophy1() icons.IsIcon                     { return newIcon("trophy-1") }
func LiTrowel1() icons.IsIcon                     { return newIcon("trowel-1") }
func LiTruckDelivery1() icons.IsIcon              { return newIcon("truck-delivery-1") }
func LiTumblr() icons.IsIcon                      { return newIcon("tumblr") }
func LiTurborepo() icons.IsIcon                   { return newIcon("turborepo") }
func LiTwitch() icons.IsIcon                      { return newIcon("twitch") }
func LiTwitterOld() icons.IsIcon                  { return newIcon("twitter-old") }
func LiTypescript() icons.IsIcon                  { return newIcon("typescript") }
func LiUberSymbol() icons.IsIcon                  { return newIcon("uber-symbol") }
func LiUber() icons.IsIcon                        { return newIcon("uber") }
func LiUbuntu() icons.IsIcon                      { return newIcon("ubuntu") }
func LiUnderline() icons.IsIcon                   { return newIcon("underline") }
func LiUnlink2AngularEft() icons.IsIcon           { return newIcon("unlink-2-angular-eft") }
func LiUnlocked2() icons.IsIcon                   { return newIcon("unlocked-2") }
func LiUnsplash() icons.IsIcon                    { return newIcon("unsplash") }
func LiUpload1() icons.IsIcon                     { return newIcon("upload-1") }
func LiUploadCircle1() icons.IsIcon               { return newIcon("upload-circle-1") }
func LiUser4() icons.IsIcon                       { return newIcon("user-4") }
func LiUserMultiple4() icons.IsIcon               { return newIcon("user-multiple-4") }
func LiVectorNodes6() icons.IsIcon                { return newIcon("vector-nodes-6") }
func LiVectorNodes7() icons.IsIcon                { return newIcon("vector-nodes-7") }
func LiVercel() icons.IsIcon                      { return newIcon("vercel") }
func LiVimeo() icons.IsIcon                       { return newIcon("vimeo") }
func LiVisa() icons.IsIcon                        { return newIcon("visa") }
func LiVite() icons.IsIcon                        { return newIcon("vite") }
func LiVk() icons.IsIcon                          { return newIcon("vk") }
func LiVmware() icons.IsIcon                      { return newIcon("vmware") }
func LiVolkswagen() icons.IsIcon                  { return newIcon("volkswagen") }
func LiVolume1() icons.IsIcon                     { return newIcon("volume-1") }
func LiVolumeHigh() icons.IsIcon                  { return newIcon("volume-high") }
func LiVolumeLow() icons.IsIcon                   { return newIcon("volume-low") }
func LiVolumeMute() icons.IsIcon                  { return newIcon("volume-mute") }
func LiVolumeOff() icons.IsIcon                   { return newIcon("volume-off") }
func LiVsCode() icons.IsIcon                      { return newIcon("vs-code") }
func LiVuejs() icons.IsIcon                       { return newIcon("vuejs") }
func LiWallet1() icons.IsIcon                     { return newIcon("wallet-1") }
func LiWatchBeat1() icons.IsIcon                  { return newIcon("watch-beat-1") }
func LiWaterDrop1() icons.IsIcon                  { return newIcon("water-drop-1") }
func LiWebflow() icons.IsIcon                     { return newIcon("webflow") }
func LiWebhooks() icons.IsIcon                    { return newIcon("webhooks") }
func LiWechat() icons.IsIcon                      { return newIcon("wechat") }
func LiWeightMachine1() icons.IsIcon              { return newIcon("weight-machine-1") }
func LiWhatsapp() icons.IsIcon                    { return newIcon("whatsapp") }
func LiWheelbarrowEmpty() icons.IsIcon            { return newIcon("wheelbarrow-empty") }
func LiWheelchair1() icons.IsIcon                 { return newIcon("wheelchair-1") }
func LiWindows() icons.IsIcon                     { return newIcon("windows") }
func LiWise() icons.IsIcon                        { return newIcon("wise") }
func LiWordpress() icons.IsIcon                   { return newIcon("wordpress") }
func LiWwwCursor() icons.IsIcon                   { return newIcon("www-cursor") }
func LiWww() icons.IsIcon                         { return newIcon("www") }
func LiX() icons.IsIcon                           { return newIcon("x") }
func LiXampp() icons.IsIcon                       { return newIcon("xampp") }
func LiXbox() icons.IsIcon                        { return newIcon("xbox") }
func LiXmarkCircle() icons.IsIcon                 { return newIcon("xmark-circle") }
func LiXmark() icons.IsIcon                       { return newIcon("xmark") }
func LiXrp() icons.IsIcon                         { return newIcon("xrp") }
func LiYahoo() icons.IsIcon                       { return newIcon("yahoo") }
func LiYarn() icons.IsIcon                        { return newIcon("yarn") }
func LiYcombinator() icons.IsIcon                 { return newIcon("ycombinator") }
func LiYen() icons.IsIcon                         { return newIcon("yen") }
func LiYoutubeKids() icons.IsIcon                 { return newIcon("youtube-kids") }
func LiYoutubeMusic() icons.IsIcon                { return newIcon("youtube-music") }
func LiYoutube() icons.IsIcon                     { return newIcon("youtube") }
func LiZapier() icons.IsIcon                      { return newIcon("zapier") }
func LiZeroSize() icons.IsIcon                    { return newIcon("zero-size") }
func LiZoom() icons.IsIcon                        { return newIcon("zoom") }
