package ci

import "github.com/raitucarp/gomix/icons"

func CiAirportSign1() icons.IsIcon        { return newIcon("Airport_Sign_1") }
func CiAlarmOff() icons.IsIcon            { return newIcon("Alarm_Off") }
func CiAlarmOn() icons.IsIcon             { return newIcon("Alarm_On") }
func CiAlignBottom() icons.IsIcon         { return newIcon("Align_Bottom") }
func CiAlignCenterH() icons.IsIcon        { return newIcon("Align_Center-H") }
func CiAlignCenterV() icons.IsIcon        { return newIcon("Align_Center-V") }
func CiAlignLeft() icons.IsIcon           { return newIcon("Align_Left") }
func CiAlignRight() icons.IsIcon          { return newIcon("Align_Right") }
func CiAlignTop() icons.IsIcon            { return newIcon("Align_Top") }
func CiApple() icons.IsIcon               { return newIcon("Apple") }
func CiAt() icons.IsIcon                  { return newIcon("At") }
func CiAvocado() icons.IsIcon             { return newIcon("Avocado") }
func CiBacon() icons.IsIcon               { return newIcon("Bacon") }
func CiBadgeDollar() icons.IsIcon         { return newIcon("Badge_Dollar") }
func CiBag1() icons.IsIcon                { return newIcon("Bag_1") }
func CiBandage() icons.IsIcon             { return newIcon("Bandage") }
func CiBank() icons.IsIcon                { return newIcon("Bank") }
func CiBarcode() icons.IsIcon             { return newIcon("Barcode") }
func CiBaseball() icons.IsIcon            { return newIcon("Baseball") }
func CiBasketball() icons.IsIcon          { return newIcon("Basketball") }
func CiBatteryCharging() icons.IsIcon     { return newIcon("Battery_Charging") }
func CiBatteryEmpty() icons.IsIcon        { return newIcon("Battery_Empty") }
func CiBatteryFull() icons.IsIcon         { return newIcon("Battery_Full") }
func CiBeaker1() icons.IsIcon             { return newIcon("Beaker_1") }
func CiBeerMugFull() icons.IsIcon         { return newIcon("Beer_Mug_Full") }
func CiBellOff() icons.IsIcon             { return newIcon("Bell_Off") }
func CiBellOn() icons.IsIcon              { return newIcon("Bell_On") }
func CiBezier() icons.IsIcon              { return newIcon("Bezier") }
func CiBitcoin() icons.IsIcon             { return newIcon("Bitcoin") }
func CiBluetooth() icons.IsIcon           { return newIcon("Bluetooth") }
func CiBookmarkCheck() icons.IsIcon       { return newIcon("Bookmark_Check") }
func CiBookmarkMinus() icons.IsIcon       { return newIcon("Bookmark_Minus") }
func CiBookmarkPlus() icons.IsIcon        { return newIcon("Bookmark_Plus") }
func CiBookmarkRemove() icons.IsIcon      { return newIcon("Bookmark_Remove") }
func CiBookmark() icons.IsIcon            { return newIcon("Bookmark") }
func CiBowlNoodles() icons.IsIcon         { return newIcon("Bowl_&_Noodles") }
func CiBoxList() icons.IsIcon             { return newIcon("Box_List") }
func CiBoxes() icons.IsIcon               { return newIcon("Boxes") }
func CiBrightnessDown() icons.IsIcon      { return newIcon("Brightness_Down") }
func CiBrightnessUp() icons.IsIcon        { return newIcon("Brightness_Up") }
func CiBullhorn() icons.IsIcon            { return newIcon("Bullhorn") }
func CiBurger() icons.IsIcon              { return newIcon("Burger") }
func CiCalculator1() icons.IsIcon         { return newIcon("Calculator_1") }
func CiCalculator2() icons.IsIcon         { return newIcon("Calculator_2") }
func CiCalendarDate() icons.IsIcon        { return newIcon("Calendar_Date") }
func CiCalendar() icons.IsIcon            { return newIcon("Calendar") }
func CiCamera() icons.IsIcon              { return newIcon("Camera") }
func CiChat1() icons.IsIcon               { return newIcon("Chat_1") }
func CiChat2() icons.IsIcon               { return newIcon("Chat_2") }
func CiCircleAlert() icons.IsIcon         { return newIcon("Circle_Alert") }
func CiCircleCheck() icons.IsIcon         { return newIcon("Circle_Check") }
func CiCircleChevDown() icons.IsIcon      { return newIcon("Circle_Chev_Down") }
func CiCircleChevLeft() icons.IsIcon      { return newIcon("Circle_Chev_Left") }
func CiCircleChevRight() icons.IsIcon     { return newIcon("Circle_Chev_Right") }
func CiCircleChevUp() icons.IsIcon        { return newIcon("Circle_Chev_Up") }
func CiCircleInfo() icons.IsIcon          { return newIcon("Circle_Info") }
func CiCircleList() icons.IsIcon          { return newIcon("Circle_List") }
func CiCircleMinus() icons.IsIcon         { return newIcon("Circle_Minus") }
func CiCircleMore() icons.IsIcon          { return newIcon("Circle_More") }
func CiCirclePlus() icons.IsIcon          { return newIcon("Circle_Plus") }
func CiCircleQuestion() icons.IsIcon      { return newIcon("Circle_Question") }
func CiCircleRemove() icons.IsIcon        { return newIcon("Circle_Remove") }
func CiClock1() icons.IsIcon              { return newIcon("Clock_1") }
func CiClock2() icons.IsIcon              { return newIcon("Clock_2") }
func CiCloudDrizzle() icons.IsIcon        { return newIcon("Cloud_Drizzle") }
func CiCloudMoon() icons.IsIcon           { return newIcon("Cloud_Moon") }
func CiCloudOff() icons.IsIcon            { return newIcon("Cloud_Off") }
func CiCloudOn() icons.IsIcon             { return newIcon("Cloud_On") }
func CiCloudRainbow() icons.IsIcon        { return newIcon("Cloud_Rainbow") }
func CiCloudSun() icons.IsIcon            { return newIcon("Cloud_Sun") }
func CiCloud() icons.IsIcon               { return newIcon("Cloud") }
func CiCoffeeBean() icons.IsIcon          { return newIcon("Coffee_Bean") }
func CiCoffeeCup() icons.IsIcon           { return newIcon("Coffee_Cup") }
func CiCoinInsert() icons.IsIcon          { return newIcon("Coin_Insert") }
func CiCoins1() icons.IsIcon              { return newIcon("Coins_1") }
func CiCompass1() icons.IsIcon            { return newIcon("Compass_1") }
func CiCreditCard1() icons.IsIcon         { return newIcon("Credit_Card_1") }
func CiCreditCard2() icons.IsIcon         { return newIcon("Credit_Card_2") }
func CiCreditCardOff() icons.IsIcon       { return newIcon("Credit_Card_Off") }
func CiCrop() icons.IsIcon                { return newIcon("Crop") }
func CiDark() icons.IsIcon                { return newIcon("Dark") }
func CiDatabase() icons.IsIcon            { return newIcon("Database") }
func CiDeliveryTruck() icons.IsIcon       { return newIcon("Delivery_Truck") }
func CiDesktopMouse1() icons.IsIcon       { return newIcon("Desktop_Mouse_1") }
func CiDesktopMouse2() icons.IsIcon       { return newIcon("Desktop_Mouse_2") }
func CiDesktop() icons.IsIcon             { return newIcon("Desktop") }
func CiDiscount1() icons.IsIcon           { return newIcon("Discount_1") }
func CiDollar() icons.IsIcon              { return newIcon("Dollar") }
func CiDroplet() icons.IsIcon             { return newIcon("Droplet") }
func CiDumbbell() icons.IsIcon            { return newIcon("Dumbbell") }
func CiEdit() icons.IsIcon                { return newIcon("Edit") }
func CiEraser() icons.IsIcon              { return newIcon("Eraser") }
func CiExport() icons.IsIcon              { return newIcon("Export") }
func CiEyeOff() icons.IsIcon              { return newIcon("Eye_Off") }
func CiEyeOn() icons.IsIcon               { return newIcon("Eye_On") }
func CiFaceFrown() icons.IsIcon           { return newIcon("Face_Frown") }
func CiFaceMeh() icons.IsIcon             { return newIcon("Face_Meh") }
func CiFaceSmile() icons.IsIcon           { return newIcon("Face_Smile") }
func CiFacebook() icons.IsIcon            { return newIcon("Facebook") }
func CiFileOff() icons.IsIcon             { return newIcon("File_Off") }
func CiFileOn() icons.IsIcon              { return newIcon("File_On") }
func CiFilter() icons.IsIcon              { return newIcon("Filter") }
func CiFlag1() icons.IsIcon               { return newIcon("Flag_1") }
func CiFloppyDisk() icons.IsIcon          { return newIcon("Floppy_Disk") }
func CiFolderOff() icons.IsIcon           { return newIcon("Folder_Off") }
func CiFolderOn() icons.IsIcon            { return newIcon("Folder_On") }
func CiFootball() icons.IsIcon            { return newIcon("Football") }
func CiForkKnife() icons.IsIcon           { return newIcon("Fork_&_Knife") }
func CiFries() icons.IsIcon               { return newIcon("Fries") }
func CiGift() icons.IsIcon                { return newIcon("Gift") }
func CiGlass() icons.IsIcon               { return newIcon("Glass") }
func CiGlobe() icons.IsIcon               { return newIcon("Globe") }
func CiGps() icons.IsIcon                 { return newIcon("GPS") }
func CiGrid2H() icons.IsIcon              { return newIcon("Grid__2-H") }
func CiGrid2V() icons.IsIcon              { return newIcon("Grid_2-V") }
func CiGrid31() icons.IsIcon              { return newIcon("Grid_3-1") }
func CiGrid32() icons.IsIcon              { return newIcon("Grid_3-2") }
func CiGrid41() icons.IsIcon              { return newIcon("Grid_4-1") }
func CiGrid42() icons.IsIcon              { return newIcon("Grid_4-2") }
func CiHardDrive() icons.IsIcon           { return newIcon("Hard_Drive") }
func CiHashtag() icons.IsIcon             { return newIcon("Hashtag") }
func CiHeadphones() icons.IsIcon          { return newIcon("Headphones") }
func CiHeart() icons.IsIcon               { return newIcon("Heart") }
func CiHome() icons.IsIcon                { return newIcon("Home") }
func CiHospital1() icons.IsIcon           { return newIcon("Hospital_1") }
func CiHotdog() icons.IsIcon              { return newIcon("Hotdog") }
func CiIceCream() icons.IsIcon            { return newIcon("Ice_Cream") }
func CiImageOff() icons.IsIcon            { return newIcon("Image_Off") }
func CiImageOn() icons.IsIcon             { return newIcon("Image_On") }
func CiImport() icons.IsIcon              { return newIcon("Import") }
func CiInboxIn() icons.IsIcon             { return newIcon("Inbox_In") }
func CiInboxOut() icons.IsIcon            { return newIcon("Inbox_Out") }
func CiIndent() icons.IsIcon              { return newIcon("Indent") }
func CiInstagram() icons.IsIcon           { return newIcon("Instagram") }
func CiKeyboard() icons.IsIcon            { return newIcon("Keyboard") }
func CiLaptop() icons.IsIcon              { return newIcon("Laptop") }
func CiLemon() icons.IsIcon               { return newIcon("Lemon") }
func CiLight() icons.IsIcon               { return newIcon("Light") }
func CiLineHeight() icons.IsIcon          { return newIcon("Line_Height") }
func CiLink() icons.IsIcon                { return newIcon("Link") }
func CiLinkedIn() icons.IsIcon            { return newIcon("LinkedIn") }
func CiLocationArrow1() icons.IsIcon      { return newIcon("Location_Arrow_1") }
func CiLocationOff() icons.IsIcon         { return newIcon("Location_Off") }
func CiLocationOn() icons.IsIcon          { return newIcon("Location_On") }
func CiLock() icons.IsIcon                { return newIcon("Lock") }
func CiLogin() icons.IsIcon               { return newIcon("Login") }
func CiLogout() icons.IsIcon              { return newIcon("Logout") }
func CiLollipop() icons.IsIcon            { return newIcon("Lollipop") }
func CiMail() icons.IsIcon                { return newIcon("Mail") }
func CiMapPin() icons.IsIcon              { return newIcon("Map_Pin") }
func CiMap() icons.IsIcon                 { return newIcon("Map") }
func CiMaximize1() icons.IsIcon           { return newIcon("Maximize_1") }
func CiMaximize2() icons.IsIcon           { return newIcon("Maximize_2") }
func CiMedal() icons.IsIcon               { return newIcon("Medal") }
func CiMedicalCase() icons.IsIcon         { return newIcon("Medical_Case") }
func CiMedicalClipboard() icons.IsIcon    { return newIcon("Medical_Clipboard") }
func CiMedicalCross() icons.IsIcon        { return newIcon("Medical_Cross") }
func CiMedicalMask() icons.IsIcon         { return newIcon("Medical_Mask") }
func CiMemoPad() icons.IsIcon             { return newIcon("Memo_Pad") }
func CiMicrochip() icons.IsIcon           { return newIcon("Microchip") }
func CiMicrophoneOff() icons.IsIcon       { return newIcon("Microphone_Off") }
func CiMicrophoneOn() icons.IsIcon        { return newIcon("Microphone_On") }
func CiMinimize1() icons.IsIcon           { return newIcon("Minimize_1") }
func CiMinimize2() icons.IsIcon           { return newIcon("Minimize_2") }
func CiMobile1() icons.IsIcon             { return newIcon("Mobile_1") }
func CiMobile2() icons.IsIcon             { return newIcon("Mobile_2") }
func CiMobile3() icons.IsIcon             { return newIcon("Mobile_3") }
func CiMobile4() icons.IsIcon             { return newIcon("Mobile_4") }
func CiMoneyBill() icons.IsIcon           { return newIcon("Money_Bill") }
func CiMoneyCheck1() icons.IsIcon         { return newIcon("Money_Check_1") }
func CiMonitor() icons.IsIcon             { return newIcon("Monitor") }
func CiMountain1() icons.IsIcon           { return newIcon("Mountain_1") }
func CiMug1() icons.IsIcon                { return newIcon("Mug_1") }
func CiMusicNote1() icons.IsIcon          { return newIcon("Music_Note_1") }
func CiNoWattingSign() icons.IsIcon       { return newIcon("No_Watting_Sign") }
func CiPalette() icons.IsIcon             { return newIcon("Palette") }
func CiPaperPlane() icons.IsIcon          { return newIcon("Paper_Plane") }
func CiParking1() icons.IsIcon            { return newIcon("Parking_1") }
func CiPassport1() icons.IsIcon           { return newIcon("Passport_1") }
func CiPause1() icons.IsIcon              { return newIcon("Pause_1") }
func CiPen() icons.IsIcon                 { return newIcon("Pen") }
func CiPenpot() icons.IsIcon              { return newIcon("Penpot") }
func CiPercent() icons.IsIcon             { return newIcon("Percent") }
func CiPhone() icons.IsIcon               { return newIcon("Phone") }
func CiPickerEmpty() icons.IsIcon         { return newIcon("Picker_Empty") }
func CiPickerHalf() icons.IsIcon          { return newIcon("Picker_Half") }
func CiPill() icons.IsIcon                { return newIcon("Pill") }
func CiPizza() icons.IsIcon               { return newIcon("Pizza") }
func CiPlane() icons.IsIcon               { return newIcon("Plane") }
func CiPlay1() icons.IsIcon               { return newIcon("Play_1") }
func CiPlug1() icons.IsIcon               { return newIcon("Plug_1") }
func CiPower() icons.IsIcon               { return newIcon("Power") }
func CiPrescriptionBottle1() icons.IsIcon { return newIcon("Prescription_Bottle_1") }
func CiRainbow() icons.IsIcon             { return newIcon("Rainbow") }
func CiReceipt() icons.IsIcon             { return newIcon("Receipt") }
func CiRedo() icons.IsIcon                { return newIcon("Redo") }
func CiRepeat() icons.IsIcon              { return newIcon("Repeat") }
func CiRollingSuitcase() icons.IsIcon     { return newIcon("Rolling_Suitcase") }
func CiRoute() icons.IsIcon               { return newIcon("Route") }
func CiRouter() icons.IsIcon              { return newIcon("Router") }
func CiRuler() icons.IsIcon               { return newIcon("Ruler") }
func CiSatellite1() icons.IsIcon          { return newIcon("Satellite_1") }
func CiSaveDown1() icons.IsIcon           { return newIcon("Save_Down_1") }
func CiSaveDown2() icons.IsIcon           { return newIcon("Save_Down_2") }
func CiSaveUp1() icons.IsIcon             { return newIcon("Save_Up_1") }
func CiSaveUp2() icons.IsIcon             { return newIcon("Save_Up_2") }
func CiSearch() icons.IsIcon              { return newIcon("Search") }
func CiServer() icons.IsIcon              { return newIcon("Server") }
func CiSettings() icons.IsIcon            { return newIcon("Settings") }
func CiShare1() icons.IsIcon              { return newIcon("Share_1") }
func CiShare2() icons.IsIcon              { return newIcon("Share_2") }
func CiShirt() icons.IsIcon               { return newIcon("Shirt") }
func CiShop() icons.IsIcon                { return newIcon("Shop") }
func CiShoppingBasket() icons.IsIcon      { return newIcon("Shopping_Basket") }
func CiShoppingCart() icons.IsIcon        { return newIcon("Shopping_Cart") }
func CiShoppingTag() icons.IsIcon         { return newIcon("Shopping_Tag") }
func CiShuffle() icons.IsIcon             { return newIcon("Shuffle") }
func CiSignpostCombined1() icons.IsIcon   { return newIcon("Signpost_Combined_1") }
func CiSignpostL1() icons.IsIcon          { return newIcon("Signpost_L_1") }
func CiSignpostR1() icons.IsIcon          { return newIcon("Signpost_R_1") }
func CiSliderHorizontal() icons.IsIcon    { return newIcon("Slider_Horizontal") }
func CiSliderVertical() icons.IsIcon      { return newIcon("Slider_Vertical") }
func CiSpeaker() icons.IsIcon             { return newIcon("Speaker") }
func CiSquareAlert() icons.IsIcon         { return newIcon("Square_Alert") }
func CiSquareCheck() icons.IsIcon         { return newIcon("Square_Check") }
func CiSquareChevDown() icons.IsIcon      { return newIcon("Square_Chev_Down") }
func CiSquareChevLeft() icons.IsIcon      { return newIcon("Square_Chev_Left") }
func CiSquareChevRight() icons.IsIcon     { return newIcon("Square_Chev_Right") }
func CiSquareChevUp() icons.IsIcon        { return newIcon("Square_Chev_Up") }
func CiSquareInfo() icons.IsIcon          { return newIcon("Square_Info") }
func CiSquareMinus() icons.IsIcon         { return newIcon("Square_Minus") }
func CiSquareMore() icons.IsIcon          { return newIcon("Square_More") }
func CiSquarePlus() icons.IsIcon          { return newIcon("Square_Plus") }
func CiSquareQuestion() icons.IsIcon      { return newIcon("Square_Question") }
func CiSquareRemove() icons.IsIcon        { return newIcon("Square_Remove") }
func CiStar() icons.IsIcon                { return newIcon("Star") }
func CiStethoscope() icons.IsIcon         { return newIcon("Stethoscope") }
func CiStickyNote() icons.IsIcon          { return newIcon("Sticky_Note") }
func CiStop1() icons.IsIcon               { return newIcon("Stop_1") }
func CiStopSign1() icons.IsIcon           { return newIcon("Stop_Sign_1") }
func CiStopwatch() icons.IsIcon           { return newIcon("Stopwatch") }
func CiStreamOff() icons.IsIcon           { return newIcon("Stream_Off") }
func CiStreamOn() icons.IsIcon            { return newIcon("Stream_On") }
func CiSun() icons.IsIcon                 { return newIcon("Sun") }
func CiTablets1() icons.IsIcon            { return newIcon("Tablets_1") }
func CiTempHigh() icons.IsIcon            { return newIcon("Temp_High") }
func CiTextAlignCenter() icons.IsIcon     { return newIcon("Text_Align_Center") }
func CiTextAlignJustify() icons.IsIcon    { return newIcon("Text_Align_Justify") }
func CiTextAlignLeft() icons.IsIcon       { return newIcon("Text_Align_Left") }
func CiTextAlignRight() icons.IsIcon      { return newIcon("Text_Align_Right") }
func CiText() icons.IsIcon                { return newIcon("Text") }
func CiTimer() icons.IsIcon               { return newIcon("Timer") }
func CiTrashCan() icons.IsIcon            { return newIcon("Trash_Can") }
func CiTrophy() icons.IsIcon              { return newIcon("Trophy") }
func CiTurnL1() icons.IsIcon              { return newIcon("Turn_L_1") }
func CiTurnR1() icons.IsIcon              { return newIcon("Turn_R_1") }
func CiTwitter() icons.IsIcon             { return newIcon("Twitter") }
func CiUmbrella() icons.IsIcon            { return newIcon("Umbrella") }
func CiUndo() icons.IsIcon                { return newIcon("Undo") }
func CiUnlock() icons.IsIcon              { return newIcon("Unlock") }
func CiUsb() icons.IsIcon                 { return newIcon("Usb") }
func CiUser() icons.IsIcon                { return newIcon("User") }
func CiVault() icons.IsIcon               { return newIcon("Vault") }
func CiVial() icons.IsIcon                { return newIcon("Vial") }
func CiVideoOff() icons.IsIcon            { return newIcon("Video_Off") }
func CiVideoOn() icons.IsIcon             { return newIcon("Video_On") }
func CiViewBoard() icons.IsIcon           { return newIcon("View_Board") }
func CiViewColumn() icons.IsIcon          { return newIcon("View_Column") }
func CiViewList() icons.IsIcon            { return newIcon("View_List") }
func CiViewTable() icons.IsIcon           { return newIcon("View_Table") }
func CiViewTimeline() icons.IsIcon        { return newIcon("View_Timeline") }
func CiVirus() icons.IsIcon               { return newIcon("Virus") }
func CiVoicemail() icons.IsIcon           { return newIcon("Voicemail") }
func CiVolumeHight() icons.IsIcon         { return newIcon("Volume_Hight") }
func CiVolumeMute() icons.IsIcon          { return newIcon("Volume_Mute") }
func CiVolume() icons.IsIcon              { return newIcon("Volume") }
func CiWallet() icons.IsIcon              { return newIcon("Wallet") }
func CiWarning() icons.IsIcon             { return newIcon("Warning") }
func CiWavePulse1() icons.IsIcon          { return newIcon("Wave_Pulse_1") }
func CiWheat() icons.IsIcon               { return newIcon("Wheat") }
func CiWiFiOff() icons.IsIcon             { return newIcon("Wi-Fi_Off") }
func CiWiFiOn() icons.IsIcon              { return newIcon("Wi-Fi_On") }
func CiYoutube() icons.IsIcon             { return newIcon("Youtube") }
func CiZoomIn() icons.IsIcon              { return newIcon("Zoom_In") }
func CiZoomOut() icons.IsIcon             { return newIcon("Zoom_Out") }
