package vsc

import "github.com/raitucarp/gomix/icons"

func VscAccount() icons.IsIcon                  { return newIcon("account") }
func VscActivateBreakpoints() icons.IsIcon      { return newIcon("activate-breakpoints") }
func VscAdd() icons.IsIcon                      { return newIcon("add") }
func VscArchive() icons.IsIcon                  { return newIcon("archive") }
func VscArrowBoth() icons.IsIcon                { return newIcon("arrow-both") }
func VscArrowCircleDown() icons.IsIcon          { return newIcon("arrow-circle-down") }
func VscArrowCircleLeft() icons.IsIcon          { return newIcon("arrow-circle-left") }
func VscArrowCircleRight() icons.IsIcon         { return newIcon("arrow-circle-right") }
func VscArrowCircleUp() icons.IsIcon            { return newIcon("arrow-circle-up") }
func VscArrowDown() icons.IsIcon                { return newIcon("arrow-down") }
func VscArrowLeft() icons.IsIcon                { return newIcon("arrow-left") }
func VscArrowRight() icons.IsIcon               { return newIcon("arrow-right") }
func VscArrowSmallDown() icons.IsIcon           { return newIcon("arrow-small-down") }
func VscArrowSmallLeft() icons.IsIcon           { return newIcon("arrow-small-left") }
func VscArrowSmallRight() icons.IsIcon          { return newIcon("arrow-small-right") }
func VscArrowSmallUp() icons.IsIcon             { return newIcon("arrow-small-up") }
func VscArrowSwap() icons.IsIcon                { return newIcon("arrow-swap") }
func VscArrowUp() icons.IsIcon                  { return newIcon("arrow-up") }
func VscAttach() icons.IsIcon                   { return newIcon("attach") }
func VscAzureDevops() icons.IsIcon              { return newIcon("azure-devops") }
func VscAzure() icons.IsIcon                    { return newIcon("azure") }
func VscBeakerStop() icons.IsIcon               { return newIcon("beaker-stop") }
func VscBeaker() icons.IsIcon                   { return newIcon("beaker") }
func VscBellDot() icons.IsIcon                  { return newIcon("bell-dot") }
func VscBellSlashDot() icons.IsIcon             { return newIcon("bell-slash-dot") }
func VscBellSlash() icons.IsIcon                { return newIcon("bell-slash") }
func VscBell() icons.IsIcon                     { return newIcon("bell") }
func VscBlank() icons.IsIcon                    { return newIcon("blank") }
func VscBold() icons.IsIcon                     { return newIcon("bold") }
func VscBook() icons.IsIcon                     { return newIcon("book") }
func VscBookmark() icons.IsIcon                 { return newIcon("bookmark") }
func VscBracketDot() icons.IsIcon               { return newIcon("bracket-dot") }
func VscBracketError() icons.IsIcon             { return newIcon("bracket-error") }
func VscBriefcase() icons.IsIcon                { return newIcon("briefcase") }
func VscBroadcast() icons.IsIcon                { return newIcon("broadcast") }
func VscBrowser() icons.IsIcon                  { return newIcon("browser") }
func VscBug() icons.IsIcon                      { return newIcon("bug") }
func VscCalendar() icons.IsIcon                 { return newIcon("calendar") }
func VscCallIncoming() icons.IsIcon             { return newIcon("call-incoming") }
func VscCallOutgoing() icons.IsIcon             { return newIcon("call-outgoing") }
func VscCaseSensitive() icons.IsIcon            { return newIcon("case-sensitive") }
func VscChatSparkleError() icons.IsIcon         { return newIcon("chat-sparkle-error") }
func VscChatSparkleWarning() icons.IsIcon       { return newIcon("chat-sparkle-warning") }
func VscChatSparkle() icons.IsIcon              { return newIcon("chat-sparkle") }
func VscCheckAll() icons.IsIcon                 { return newIcon("check-all") }
func VscCheck() icons.IsIcon                    { return newIcon("check") }
func VscChecklist() icons.IsIcon                { return newIcon("checklist") }
func VscChevronDown() icons.IsIcon              { return newIcon("chevron-down") }
func VscChevronLeft() icons.IsIcon              { return newIcon("chevron-left") }
func VscChevronRight() icons.IsIcon             { return newIcon("chevron-right") }
func VscChevronUp() icons.IsIcon                { return newIcon("chevron-up") }
func VscChip() icons.IsIcon                     { return newIcon("chip") }
func VscChromeClose() icons.IsIcon              { return newIcon("chrome-close") }
func VscChromeMaximize() icons.IsIcon           { return newIcon("chrome-maximize") }
func VscChromeMinimize() icons.IsIcon           { return newIcon("chrome-minimize") }
func VscChromeRestore() icons.IsIcon            { return newIcon("chrome-restore") }
func VscCircleFilled() icons.IsIcon             { return newIcon("circle-filled") }
func VscCircleLargeFilled() icons.IsIcon        { return newIcon("circle-large-filled") }
func VscCircleLarge() icons.IsIcon              { return newIcon("circle-large") }
func VscCircleSlash() icons.IsIcon              { return newIcon("circle-slash") }
func VscCircleSmallFilled() icons.IsIcon        { return newIcon("circle-small-filled") }
func VscCircleSmall() icons.IsIcon              { return newIcon("circle-small") }
func VscCircle() icons.IsIcon                   { return newIcon("circle") }
func VscCircuitBoard() icons.IsIcon             { return newIcon("circuit-board") }
func VscClearAll() icons.IsIcon                 { return newIcon("clear-all") }
func VscClippy() icons.IsIcon                   { return newIcon("clippy") }
func VscCloseAll() icons.IsIcon                 { return newIcon("close-all") }
func VscClose() icons.IsIcon                    { return newIcon("close") }
func VscCloudDownload() icons.IsIcon            { return newIcon("cloud-download") }
func VscCloudUpload() icons.IsIcon              { return newIcon("cloud-upload") }
func VscCloud() icons.IsIcon                    { return newIcon("cloud") }
func VscCodeOss() icons.IsIcon                  { return newIcon("code-oss") }
func VscCodeReview() icons.IsIcon               { return newIcon("code-review") }
func VscCode() icons.IsIcon                     { return newIcon("code") }
func VscCoffee() icons.IsIcon                   { return newIcon("coffee") }
func VscCollapseAll() icons.IsIcon              { return newIcon("collapse-all") }
func VscCollection() icons.IsIcon               { return newIcon("collection") }
func VscColorMode() icons.IsIcon                { return newIcon("color-mode") }
func VscCombine() icons.IsIcon                  { return newIcon("combine") }
func VscCommentDiscussionSparkle() icons.IsIcon { return newIcon("comment-discussion-sparkle") }
func VscCommentDiscussion() icons.IsIcon        { return newIcon("comment-discussion") }
func VscCommentDraft() icons.IsIcon             { return newIcon("comment-draft") }
func VscCommentUnresolved() icons.IsIcon        { return newIcon("comment-unresolved") }
func VscComment() icons.IsIcon                  { return newIcon("comment") }
func VscCompassActive() icons.IsIcon            { return newIcon("compass-active") }
func VscCompassDot() icons.IsIcon               { return newIcon("compass-dot") }
func VscCompass() icons.IsIcon                  { return newIcon("compass") }
func VscCopilotBlocked() icons.IsIcon           { return newIcon("copilot-blocked") }
func VscCopilotError() icons.IsIcon             { return newIcon("copilot-error") }
func VscCopilotInProgress() icons.IsIcon        { return newIcon("copilot-in-progress") }
func VscCopilotLarge() icons.IsIcon             { return newIcon("copilot-large") }
func VscCopilotNotConnected() icons.IsIcon      { return newIcon("copilot-not-connected") }
func VscCopilotSnooze() icons.IsIcon            { return newIcon("copilot-snooze") }
func VscCopilotSuccess() icons.IsIcon           { return newIcon("copilot-success") }
func VscCopilotUnavailable() icons.IsIcon       { return newIcon("copilot-unavailable") }
func VscCopilotWarningLarge() icons.IsIcon      { return newIcon("copilot-warning-large") }
func VscCopilotWarning() icons.IsIcon           { return newIcon("copilot-warning") }
func VscCopilot() icons.IsIcon                  { return newIcon("copilot") }
func VscCopy() icons.IsIcon                     { return newIcon("copy") }
func VscCoverage() icons.IsIcon                 { return newIcon("coverage") }
func VscCreditCard() icons.IsIcon               { return newIcon("credit-card") }
func VscDash() icons.IsIcon                     { return newIcon("dash") }
func VscDashboard() icons.IsIcon                { return newIcon("dashboard") }
func VscDatabase() icons.IsIcon                 { return newIcon("database") }
func VscDebugAll() icons.IsIcon                 { return newIcon("debug-all") }
func VscDebugAltSmall() icons.IsIcon            { return newIcon("debug-alt-small") }
func VscDebugAlt() icons.IsIcon                 { return newIcon("debug-alt") }
func VscDebugBreakpointConditionalUnverified() icons.IsIcon {
	return newIcon("debug-breakpoint-conditional-unverified")
}
func VscDebugBreakpointConditional() icons.IsIcon { return newIcon("debug-breakpoint-conditional") }
func VscDebugBreakpointDataUnverified() icons.IsIcon {
	return newIcon("debug-breakpoint-data-unverified")
}
func VscDebugBreakpointData() icons.IsIcon { return newIcon("debug-breakpoint-data") }
func VscDebugBreakpointFunctionUnverified() icons.IsIcon {
	return newIcon("debug-breakpoint-function-unverified")
}
func VscDebugBreakpointFunction() icons.IsIcon { return newIcon("debug-breakpoint-function") }
func VscDebugBreakpointLogUnverified() icons.IsIcon {
	return newIcon("debug-breakpoint-log-unverified")
}
func VscDebugBreakpointLog() icons.IsIcon         { return newIcon("debug-breakpoint-log") }
func VscDebugBreakpointUnsupported() icons.IsIcon { return newIcon("debug-breakpoint-unsupported") }
func VscDebugConsole() icons.IsIcon               { return newIcon("debug-console") }
func VscDebugContinueSmall() icons.IsIcon         { return newIcon("debug-continue-small") }
func VscDebugContinue() icons.IsIcon              { return newIcon("debug-continue") }
func VscDebugCoverage() icons.IsIcon              { return newIcon("debug-coverage") }
func VscDebugDisconnect() icons.IsIcon            { return newIcon("debug-disconnect") }
func VscDebugLineByLine() icons.IsIcon            { return newIcon("debug-line-by-line") }
func VscDebugPause() icons.IsIcon                 { return newIcon("debug-pause") }
func VscDebugRerun() icons.IsIcon                 { return newIcon("debug-rerun") }
func VscDebugRestartFrame() icons.IsIcon          { return newIcon("debug-restart-frame") }
func VscDebugRestart() icons.IsIcon               { return newIcon("debug-restart") }
func VscDebugReverseContinue() icons.IsIcon       { return newIcon("debug-reverse-continue") }
func VscDebugStackframeActive() icons.IsIcon      { return newIcon("debug-stackframe-active") }
func VscDebugStackframe() icons.IsIcon            { return newIcon("debug-stackframe") }
func VscDebugStart() icons.IsIcon                 { return newIcon("debug-start") }
func VscDebugStepBack() icons.IsIcon              { return newIcon("debug-step-back") }
func VscDebugStepInto() icons.IsIcon              { return newIcon("debug-step-into") }
func VscDebugStepOut() icons.IsIcon               { return newIcon("debug-step-out") }
func VscDebugStepOver() icons.IsIcon              { return newIcon("debug-step-over") }
func VscDebugStop() icons.IsIcon                  { return newIcon("debug-stop") }
func VscDebug() icons.IsIcon                      { return newIcon("debug") }
func VscDesktopDownload() icons.IsIcon            { return newIcon("desktop-download") }
func VscDeviceCameraVideo() icons.IsIcon          { return newIcon("device-camera-video") }
func VscDeviceCamera() icons.IsIcon               { return newIcon("device-camera") }
func VscDeviceMobile() icons.IsIcon               { return newIcon("device-mobile") }
func VscDiffAdded() icons.IsIcon                  { return newIcon("diff-added") }
func VscDiffIgnored() icons.IsIcon                { return newIcon("diff-ignored") }
func VscDiffModified() icons.IsIcon               { return newIcon("diff-modified") }
func VscDiffMultiple() icons.IsIcon               { return newIcon("diff-multiple") }
func VscDiffRemoved() icons.IsIcon                { return newIcon("diff-removed") }
func VscDiffRenamed() icons.IsIcon                { return newIcon("diff-renamed") }
func VscDiffSingle() icons.IsIcon                 { return newIcon("diff-single") }
func VscDiff() icons.IsIcon                       { return newIcon("diff") }
func VscDiscard() icons.IsIcon                    { return newIcon("discard") }
func VscEditSession() icons.IsIcon                { return newIcon("edit-session") }
func VscEditSparkle() icons.IsIcon                { return newIcon("edit-sparkle") }
func VscEdit() icons.IsIcon                       { return newIcon("edit") }
func VscEditorLayout() icons.IsIcon               { return newIcon("editor-layout") }
func VscEllipsis() icons.IsIcon                   { return newIcon("ellipsis") }
func VscEmptyWindow() icons.IsIcon                { return newIcon("empty-window") }
func VscErrorSmall() icons.IsIcon                 { return newIcon("error-small") }
func VscError() icons.IsIcon                      { return newIcon("error") }
func VscExclude() icons.IsIcon                    { return newIcon("exclude") }
func VscExpandAll() icons.IsIcon                  { return newIcon("expand-all") }
func VscExport() icons.IsIcon                     { return newIcon("export") }
func VscExtensionsLarge() icons.IsIcon            { return newIcon("extensions-large") }
func VscExtensions() icons.IsIcon                 { return newIcon("extensions") }
func VscEyeClosed() icons.IsIcon                  { return newIcon("eye-closed") }
func VscEye() icons.IsIcon                        { return newIcon("eye") }
func VscFeedback() icons.IsIcon                   { return newIcon("feedback") }
func VscFileBinary() icons.IsIcon                 { return newIcon("file-binary") }
func VscFileCode() icons.IsIcon                   { return newIcon("file-code") }
func VscFileMedia() icons.IsIcon                  { return newIcon("file-media") }
func VscFilePdf() icons.IsIcon                    { return newIcon("file-pdf") }
func VscFileSubmodule() icons.IsIcon              { return newIcon("file-submodule") }
func VscFileSymlinkDirectory() icons.IsIcon       { return newIcon("file-symlink-directory") }
func VscFileSymlinkFile() icons.IsIcon            { return newIcon("file-symlink-file") }
func VscFileZip() icons.IsIcon                    { return newIcon("file-zip") }
func VscFile() icons.IsIcon                       { return newIcon("file") }
func VscFiles() icons.IsIcon                      { return newIcon("files") }
func VscFilterFilled() icons.IsIcon               { return newIcon("filter-filled") }
func VscFilter() icons.IsIcon                     { return newIcon("filter") }
func VscFlag() icons.IsIcon                       { return newIcon("flag") }
func VscFlame() icons.IsIcon                      { return newIcon("flame") }
func VscFoldDown() icons.IsIcon                   { return newIcon("fold-down") }
func VscFoldUp() icons.IsIcon                     { return newIcon("fold-up") }
func VscFold() icons.IsIcon                       { return newIcon("fold") }
func VscFolderActive() icons.IsIcon               { return newIcon("folder-active") }
func VscFolderLibrary() icons.IsIcon              { return newIcon("folder-library") }
func VscFolderOpened() icons.IsIcon               { return newIcon("folder-opened") }
func VscFolder() icons.IsIcon                     { return newIcon("folder") }
func VscGame() icons.IsIcon                       { return newIcon("game") }
func VscGear() icons.IsIcon                       { return newIcon("gear") }
func VscGift() icons.IsIcon                       { return newIcon("gift") }
func VscGistSecret() icons.IsIcon                 { return newIcon("gist-secret") }
func VscGist() icons.IsIcon                       { return newIcon("gist") }
func VscGitCommit() icons.IsIcon                  { return newIcon("git-commit") }
func VscGitCompare() icons.IsIcon                 { return newIcon("git-compare") }
func VscGitFetch() icons.IsIcon                   { return newIcon("git-fetch") }
func VscGitMerge() icons.IsIcon                   { return newIcon("git-merge") }
func VscGitPullRequestClosed() icons.IsIcon       { return newIcon("git-pull-request-closed") }
func VscGitPullRequestCreate() icons.IsIcon       { return newIcon("git-pull-request-create") }
func VscGitPullRequestDone() icons.IsIcon         { return newIcon("git-pull-request-done") }
func VscGitPullRequestDraft() icons.IsIcon        { return newIcon("git-pull-request-draft") }
func VscGitPullRequestGoToChanges() icons.IsIcon  { return newIcon("git-pull-request-go-to-changes") }
func VscGitPullRequestNewChanges() icons.IsIcon   { return newIcon("git-pull-request-new-changes") }
func VscGitPullRequest() icons.IsIcon             { return newIcon("git-pull-request") }
func VscGitStashApply() icons.IsIcon              { return newIcon("git-stash-apply") }
func VscGitStashPop() icons.IsIcon                { return newIcon("git-stash-pop") }
func VscGitStash() icons.IsIcon                   { return newIcon("git-stash") }
func VscGithubAction() icons.IsIcon               { return newIcon("github-action") }
func VscGithubAlt() icons.IsIcon                  { return newIcon("github-alt") }
func VscGithubInverted() icons.IsIcon             { return newIcon("github-inverted") }
func VscGithubProject() icons.IsIcon              { return newIcon("github-project") }
func VscGithub() icons.IsIcon                     { return newIcon("github") }
func VscGlobe() icons.IsIcon                      { return newIcon("globe") }
func VscGoToEditingSession() icons.IsIcon         { return newIcon("go-to-editing-session") }
func VscGoToFile() icons.IsIcon                   { return newIcon("go-to-file") }
func VscGoToSearch() icons.IsIcon                 { return newIcon("go-to-search") }
func VscGrabber() icons.IsIcon                    { return newIcon("grabber") }
func VscGraphLeft() icons.IsIcon                  { return newIcon("graph-left") }
func VscGraphLine() icons.IsIcon                  { return newIcon("graph-line") }
func VscGraphScatter() icons.IsIcon               { return newIcon("graph-scatter") }
func VscGraph() icons.IsIcon                      { return newIcon("graph") }
func VscGripper() icons.IsIcon                    { return newIcon("gripper") }
func VscGroupByRefType() icons.IsIcon             { return newIcon("group-by-ref-type") }
func VscHeartFilled() icons.IsIcon                { return newIcon("heart-filled") }
func VscHeart() icons.IsIcon                      { return newIcon("heart") }
func VscHistory() icons.IsIcon                    { return newIcon("history") }
func VscHome() icons.IsIcon                       { return newIcon("home") }
func VscHorizontalRule() icons.IsIcon             { return newIcon("horizontal-rule") }
func VscHubot() icons.IsIcon                      { return newIcon("hubot") }
func VscInbox() icons.IsIcon                      { return newIcon("inbox") }
func VscIndent() icons.IsIcon                     { return newIcon("indent") }
func VscInfo() icons.IsIcon                       { return newIcon("info") }
func VscInsert() icons.IsIcon                     { return newIcon("insert") }
func VscInspect() icons.IsIcon                    { return newIcon("inspect") }
func VscIssueDraft() icons.IsIcon                 { return newIcon("issue-draft") }
func VscIssueReopened() icons.IsIcon              { return newIcon("issue-reopened") }
func VscIssues() icons.IsIcon                     { return newIcon("issues") }
func VscItalic() icons.IsIcon                     { return newIcon("italic") }
func VscJersey() icons.IsIcon                     { return newIcon("jersey") }
func VscJson() icons.IsIcon                       { return newIcon("json") }
func VscKebabVertical() icons.IsIcon              { return newIcon("kebab-vertical") }
func VscKey() icons.IsIcon                        { return newIcon("key") }
func VscKeyboardTabAbove() icons.IsIcon           { return newIcon("keyboard-tab-above") }
func VscKeyboardTabBelow() icons.IsIcon           { return newIcon("keyboard-tab-below") }
func VscKeyboardTab() icons.IsIcon                { return newIcon("keyboard-tab") }
func VscLaw() icons.IsIcon                        { return newIcon("law") }
func VscLayersActive() icons.IsIcon               { return newIcon("layers-active") }
func VscLayersDot() icons.IsIcon                  { return newIcon("layers-dot") }
func VscLayers() icons.IsIcon                     { return newIcon("layers") }
func VscLayoutActivitybarLeft() icons.IsIcon      { return newIcon("layout-activitybar-left") }
func VscLayoutActivitybarRight() icons.IsIcon     { return newIcon("layout-activitybar-right") }
func VscLayoutCentered() icons.IsIcon             { return newIcon("layout-centered") }
func VscLayoutMenubar() icons.IsIcon              { return newIcon("layout-menubar") }
func VscLayoutPanelCenter() icons.IsIcon          { return newIcon("layout-panel-center") }
func VscLayoutPanelDock() icons.IsIcon            { return newIcon("layout-panel-dock") }
func VscLayoutPanelJustify() icons.IsIcon         { return newIcon("layout-panel-justify") }
func VscLayoutPanelLeft() icons.IsIcon            { return newIcon("layout-panel-left") }
func VscLayoutPanelOff() icons.IsIcon             { return newIcon("layout-panel-off") }
func VscLayoutPanelRight() icons.IsIcon           { return newIcon("layout-panel-right") }
func VscLayoutPanel() icons.IsIcon                { return newIcon("layout-panel") }
func VscLayoutSidebarLeftDock() icons.IsIcon      { return newIcon("layout-sidebar-left-dock") }
func VscLayoutSidebarLeftOff() icons.IsIcon       { return newIcon("layout-sidebar-left-off") }
func VscLayoutSidebarLeft() icons.IsIcon          { return newIcon("layout-sidebar-left") }
func VscLayoutSidebarRightDock() icons.IsIcon     { return newIcon("layout-sidebar-right-dock") }
func VscLayoutSidebarRightOff() icons.IsIcon      { return newIcon("layout-sidebar-right-off") }
func VscLayoutSidebarRight() icons.IsIcon         { return newIcon("layout-sidebar-right") }
func VscLayoutStatusbar() icons.IsIcon            { return newIcon("layout-statusbar") }
func VscLayout() icons.IsIcon                     { return newIcon("layout") }
func VscLibrary() icons.IsIcon                    { return newIcon("library") }
func VscLightbulbAutofix() icons.IsIcon           { return newIcon("lightbulb-autofix") }
func VscLightbulbEmpty() icons.IsIcon             { return newIcon("lightbulb-empty") }
func VscLightbulbSparkle() icons.IsIcon           { return newIcon("lightbulb-sparkle") }
func VscLightbulb() icons.IsIcon                  { return newIcon("lightbulb") }
func VscLinkExternal() icons.IsIcon               { return newIcon("link-external") }
func VscLink() icons.IsIcon                       { return newIcon("link") }
func VscListFilter() icons.IsIcon                 { return newIcon("list-filter") }
func VscListFlat() icons.IsIcon                   { return newIcon("list-flat") }
func VscListOrdered() icons.IsIcon                { return newIcon("list-ordered") }
func VscListSelection() icons.IsIcon              { return newIcon("list-selection") }
func VscListTree() icons.IsIcon                   { return newIcon("list-tree") }
func VscListUnordered() icons.IsIcon              { return newIcon("list-unordered") }
func VscLiveShare() icons.IsIcon                  { return newIcon("live-share") }
func VscLoading() icons.IsIcon                    { return newIcon("loading") }
func VscLocation() icons.IsIcon                   { return newIcon("location") }
func VscLockSmall() icons.IsIcon                  { return newIcon("lock-small") }
func VscLock() icons.IsIcon                       { return newIcon("lock") }
func VscMagnet() icons.IsIcon                     { return newIcon("magnet") }
func VscMailRead() icons.IsIcon                   { return newIcon("mail-read") }
func VscMail() icons.IsIcon                       { return newIcon("mail") }
func VscMapFilled() icons.IsIcon                  { return newIcon("map-filled") }
func VscMapVerticalFilled() icons.IsIcon          { return newIcon("map-vertical-filled") }
func VscMapVertical() icons.IsIcon                { return newIcon("map-vertical") }
func VscMap() icons.IsIcon                        { return newIcon("map") }
func VscMarkdown() icons.IsIcon                   { return newIcon("markdown") }
func VscMcp() icons.IsIcon                        { return newIcon("mcp") }
func VscMegaphone() icons.IsIcon                  { return newIcon("megaphone") }
func VscMention() icons.IsIcon                    { return newIcon("mention") }
func VscMenu() icons.IsIcon                       { return newIcon("menu") }
func VscMerge() icons.IsIcon                      { return newIcon("merge") }
func VscMicFilled() icons.IsIcon                  { return newIcon("mic-filled") }
func VscMic() icons.IsIcon                        { return newIcon("mic") }
func VscMilestone() icons.IsIcon                  { return newIcon("milestone") }
func VscMirror() icons.IsIcon                     { return newIcon("mirror") }
func VscMortarBoard() icons.IsIcon                { return newIcon("mortar-board") }
func VscMove() icons.IsIcon                       { return newIcon("move") }
func VscMultipleWindows() icons.IsIcon            { return newIcon("multiple-windows") }
func VscMusic() icons.IsIcon                      { return newIcon("music") }
func VscMute() icons.IsIcon                       { return newIcon("mute") }
func VscNewCollection() icons.IsIcon              { return newIcon("new-collection") }
func VscNewFile() icons.IsIcon                    { return newIcon("new-file") }
func VscNewFolder() icons.IsIcon                  { return newIcon("new-folder") }
func VscNewline() icons.IsIcon                    { return newIcon("newline") }
func VscNoNewline() icons.IsIcon                  { return newIcon("no-newline") }
func VscNote() icons.IsIcon                       { return newIcon("note") }
func VscNotebookTemplate() icons.IsIcon           { return newIcon("notebook-template") }
func VscNotebook() icons.IsIcon                   { return newIcon("notebook") }
func VscOctoface() icons.IsIcon                   { return newIcon("octoface") }
func VscOpenPreview() icons.IsIcon                { return newIcon("open-preview") }
func VscOrganization() icons.IsIcon               { return newIcon("organization") }
func VscOutput() icons.IsIcon                     { return newIcon("output") }
func VscPackage() icons.IsIcon                    { return newIcon("package") }
func VscPaintcan() icons.IsIcon                   { return newIcon("paintcan") }
func VscPassFilled() icons.IsIcon                 { return newIcon("pass-filled") }
func VscPass() icons.IsIcon                       { return newIcon("pass") }
func VscPercentage() icons.IsIcon                 { return newIcon("percentage") }
func VscPersonAdd() icons.IsIcon                  { return newIcon("person-add") }
func VscPerson() icons.IsIcon                     { return newIcon("person") }
func VscPiano() icons.IsIcon                      { return newIcon("piano") }
func VscPieChart() icons.IsIcon                   { return newIcon("pie-chart") }
func VscPin() icons.IsIcon                        { return newIcon("pin") }
func VscPinnedDirty() icons.IsIcon                { return newIcon("pinned-dirty") }
func VscPinned() icons.IsIcon                     { return newIcon("pinned") }
func VscPlayCircle() icons.IsIcon                 { return newIcon("play-circle") }
func VscPlay() icons.IsIcon                       { return newIcon("play") }
func VscPlug() icons.IsIcon                       { return newIcon("plug") }
func VscPreserveCase() icons.IsIcon               { return newIcon("preserve-case") }
func VscPreview() icons.IsIcon                    { return newIcon("preview") }
func VscPrimitiveSquare() icons.IsIcon            { return newIcon("primitive-square") }
func VscProject() icons.IsIcon                    { return newIcon("project") }
func VscPulse() icons.IsIcon                      { return newIcon("pulse") }
func VscPython() icons.IsIcon                     { return newIcon("python") }
func VscQuestion() icons.IsIcon                   { return newIcon("question") }
func VscQuote() icons.IsIcon                      { return newIcon("quote") }
func VscRadioTower() icons.IsIcon                 { return newIcon("radio-tower") }
func VscReactions() icons.IsIcon                  { return newIcon("reactions") }
func VscRecordKeys() icons.IsIcon                 { return newIcon("record-keys") }
func VscRecordSmall() icons.IsIcon                { return newIcon("record-small") }
func VscRecord() icons.IsIcon                     { return newIcon("record") }
func VscRedo() icons.IsIcon                       { return newIcon("redo") }
func VscReferences() icons.IsIcon                 { return newIcon("references") }
func VscRefresh() icons.IsIcon                    { return newIcon("refresh") }
func VscRegex() icons.IsIcon                      { return newIcon("regex") }
func VscRemoteExplorer() icons.IsIcon             { return newIcon("remote-explorer") }
func VscRemote() icons.IsIcon                     { return newIcon("remote") }
func VscRemove() icons.IsIcon                     { return newIcon("remove") }
func VscReplaceAll() icons.IsIcon                 { return newIcon("replace-all") }
func VscReplace() icons.IsIcon                    { return newIcon("replace") }
func VscReply() icons.IsIcon                      { return newIcon("reply") }
func VscRepoClone() icons.IsIcon                  { return newIcon("repo-clone") }
func VscRepoFetch() icons.IsIcon                  { return newIcon("repo-fetch") }
func VscRepoForcePush() icons.IsIcon              { return newIcon("repo-force-push") }
func VscRepoForked() icons.IsIcon                 { return newIcon("repo-forked") }
func VscRepoPinned() icons.IsIcon                 { return newIcon("repo-pinned") }
func VscRepoPull() icons.IsIcon                   { return newIcon("repo-pull") }
func VscRepoPush() icons.IsIcon                   { return newIcon("repo-push") }
func VscRepo() icons.IsIcon                       { return newIcon("repo") }
func VscReport() icons.IsIcon                     { return newIcon("report") }
func VscRequestChanges() icons.IsIcon             { return newIcon("request-changes") }
func VscRobot() icons.IsIcon                      { return newIcon("robot") }
func VscRocket() icons.IsIcon                     { return newIcon("rocket") }
func VscRootFolderOpened() icons.IsIcon           { return newIcon("root-folder-opened") }
func VscRootFolder() icons.IsIcon                 { return newIcon("root-folder") }
func VscRss() icons.IsIcon                        { return newIcon("rss") }
func VscRuby() icons.IsIcon                       { return newIcon("ruby") }
func VscRunAbove() icons.IsIcon                   { return newIcon("run-above") }
func VscRunAllCoverage() icons.IsIcon             { return newIcon("run-all-coverage") }
func VscRunAll() icons.IsIcon                     { return newIcon("run-all") }
func VscRunBelow() icons.IsIcon                   { return newIcon("run-below") }
func VscRunCoverage() icons.IsIcon                { return newIcon("run-coverage") }
func VscRunErrors() icons.IsIcon                  { return newIcon("run-errors") }
func VscSaveAll() icons.IsIcon                    { return newIcon("save-all") }
func VscSaveAs() icons.IsIcon                     { return newIcon("save-as") }
func VscSave() icons.IsIcon                       { return newIcon("save") }
func VscScreenFull() icons.IsIcon                 { return newIcon("screen-full") }
func VscScreenNormal() icons.IsIcon               { return newIcon("screen-normal") }
func VscSearchFuzzy() icons.IsIcon                { return newIcon("search-fuzzy") }
func VscSearchSparkle() icons.IsIcon              { return newIcon("search-sparkle") }
func VscSearchStop() icons.IsIcon                 { return newIcon("search-stop") }
func VscSearch() icons.IsIcon                     { return newIcon("search") }
func VscSendToRemoteAgent() icons.IsIcon          { return newIcon("send-to-remote-agent") }
func VscSend() icons.IsIcon                       { return newIcon("send") }
func VscServerEnvironment() icons.IsIcon          { return newIcon("server-environment") }
func VscServerProcess() icons.IsIcon              { return newIcon("server-process") }
func VscServer() icons.IsIcon                     { return newIcon("server") }
func VscSettingsGear() icons.IsIcon               { return newIcon("settings-gear") }
func VscSettings() icons.IsIcon                   { return newIcon("settings") }
func VscShare() icons.IsIcon                      { return newIcon("share") }
func VscShield() icons.IsIcon                     { return newIcon("shield") }
func VscSignIn() icons.IsIcon                     { return newIcon("sign-in") }
func VscSignOut() icons.IsIcon                    { return newIcon("sign-out") }
func VscSmiley() icons.IsIcon                     { return newIcon("smiley") }
func VscSnake() icons.IsIcon                      { return newIcon("snake") }
func VscSortPrecedence() icons.IsIcon             { return newIcon("sort-precedence") }
func VscSourceControl() icons.IsIcon              { return newIcon("source-control") }
func VscSparkleFilled() icons.IsIcon              { return newIcon("sparkle-filled") }
func VscSparkle() icons.IsIcon                    { return newIcon("sparkle") }
func VscSplitHorizontal() icons.IsIcon            { return newIcon("split-horizontal") }
func VscSplitVertical() icons.IsIcon              { return newIcon("split-vertical") }
func VscSquirrel() icons.IsIcon                   { return newIcon("squirrel") }
func VscStarEmpty() icons.IsIcon                  { return newIcon("star-empty") }
func VscStarFull() icons.IsIcon                   { return newIcon("star-full") }
func VscStarHalf() icons.IsIcon                   { return newIcon("star-half") }
func VscStopCircle() icons.IsIcon                 { return newIcon("stop-circle") }
func VscSurroundWith() icons.IsIcon               { return newIcon("surround-with") }
func VscSymbolArray() icons.IsIcon                { return newIcon("symbol-array") }
func VscSymbolBoolean() icons.IsIcon              { return newIcon("symbol-boolean") }
func VscSymbolClass() icons.IsIcon                { return newIcon("symbol-class") }
func VscSymbolColor() icons.IsIcon                { return newIcon("symbol-color") }
func VscSymbolConstant() icons.IsIcon             { return newIcon("symbol-constant") }
func VscSymbolEnumMember() icons.IsIcon           { return newIcon("symbol-enum-member") }
func VscSymbolEnum() icons.IsIcon                 { return newIcon("symbol-enum") }
func VscSymbolEvent() icons.IsIcon                { return newIcon("symbol-event") }
func VscSymbolField() icons.IsIcon                { return newIcon("symbol-field") }
func VscSymbolFile() icons.IsIcon                 { return newIcon("symbol-file") }
func VscSymbolInterface() icons.IsIcon            { return newIcon("symbol-interface") }
func VscSymbolKey() icons.IsIcon                  { return newIcon("symbol-key") }
func VscSymbolKeyword() icons.IsIcon              { return newIcon("symbol-keyword") }
func VscSymbolMethodArrow() icons.IsIcon          { return newIcon("symbol-method-arrow") }
func VscSymbolMethod() icons.IsIcon               { return newIcon("symbol-method") }
func VscSymbolMisc() icons.IsIcon                 { return newIcon("symbol-misc") }
func VscSymbolNamespace() icons.IsIcon            { return newIcon("symbol-namespace") }
func VscSymbolNumeric() icons.IsIcon              { return newIcon("symbol-numeric") }
func VscSymbolOperator() icons.IsIcon             { return newIcon("symbol-operator") }
func VscSymbolParameter() icons.IsIcon            { return newIcon("symbol-parameter") }
func VscSymbolProperty() icons.IsIcon             { return newIcon("symbol-property") }
func VscSymbolRuler() icons.IsIcon                { return newIcon("symbol-ruler") }
func VscSymbolSnippet() icons.IsIcon              { return newIcon("symbol-snippet") }
func VscSymbolString() icons.IsIcon               { return newIcon("symbol-string") }
func VscSymbolStructure() icons.IsIcon            { return newIcon("symbol-structure") }
func VscSymbolVariable() icons.IsIcon             { return newIcon("symbol-variable") }
func VscSyncIgnored() icons.IsIcon                { return newIcon("sync-ignored") }
func VscSync() icons.IsIcon                       { return newIcon("sync") }
func VscTable() icons.IsIcon                      { return newIcon("table") }
func VscTag() icons.IsIcon                        { return newIcon("tag") }
func VscTarget() icons.IsIcon                     { return newIcon("target") }
func VscTasklist() icons.IsIcon                   { return newIcon("tasklist") }
func VscTelescope() icons.IsIcon                  { return newIcon("telescope") }
func VscTerminalBash() icons.IsIcon               { return newIcon("terminal-bash") }
func VscTerminalCmd() icons.IsIcon                { return newIcon("terminal-cmd") }
func VscTerminalDebian() icons.IsIcon             { return newIcon("terminal-debian") }
func VscTerminalLinux() icons.IsIcon              { return newIcon("terminal-linux") }
func VscTerminalPowershell() icons.IsIcon         { return newIcon("terminal-powershell") }
func VscTerminalTmux() icons.IsIcon               { return newIcon("terminal-tmux") }
func VscTerminalUbuntu() icons.IsIcon             { return newIcon("terminal-ubuntu") }
func VscTerminal() icons.IsIcon                   { return newIcon("terminal") }
func VscTextSize() icons.IsIcon                   { return newIcon("text-size") }
func VscThinking() icons.IsIcon                   { return newIcon("thinking") }
func VscThreeBars() icons.IsIcon                  { return newIcon("three-bars") }
func VscThumbsdownFilled() icons.IsIcon           { return newIcon("thumbsdown-filled") }
func VscThumbsdown() icons.IsIcon                 { return newIcon("thumbsdown") }
func VscThumbsupFilled() icons.IsIcon             { return newIcon("thumbsup-filled") }
func VscThumbsup() icons.IsIcon                   { return newIcon("thumbsup") }
func VscTools() icons.IsIcon                      { return newIcon("tools") }
func VscTrash() icons.IsIcon                      { return newIcon("trash") }
func VscTriangleDown() icons.IsIcon               { return newIcon("triangle-down") }
func VscTriangleLeft() icons.IsIcon               { return newIcon("triangle-left") }
func VscTriangleRight() icons.IsIcon              { return newIcon("triangle-right") }
func VscTriangleUp() icons.IsIcon                 { return newIcon("triangle-up") }
func VscTwitter() icons.IsIcon                    { return newIcon("twitter") }
func VscTypeHierarchySub() icons.IsIcon           { return newIcon("type-hierarchy-sub") }
func VscTypeHierarchySuper() icons.IsIcon         { return newIcon("type-hierarchy-super") }
func VscTypeHierarchy() icons.IsIcon              { return newIcon("type-hierarchy") }
func VscUnfold() icons.IsIcon                     { return newIcon("unfold") }
func VscUngroupByRefType() icons.IsIcon           { return newIcon("ungroup-by-ref-type") }
func VscUnlock() icons.IsIcon                     { return newIcon("unlock") }
func VscUnmute() icons.IsIcon                     { return newIcon("unmute") }
func VscUnverified() icons.IsIcon                 { return newIcon("unverified") }
func VscVariableGroup() icons.IsIcon              { return newIcon("variable-group") }
func VscVerifiedFilled() icons.IsIcon             { return newIcon("verified-filled") }
func VscVerified() icons.IsIcon                   { return newIcon("verified") }
func VscVersions() icons.IsIcon                   { return newIcon("versions") }
func VscVmActive() icons.IsIcon                   { return newIcon("vm-active") }
func VscVmConnect() icons.IsIcon                  { return newIcon("vm-connect") }
func VscVmOutline() icons.IsIcon                  { return newIcon("vm-outline") }
func VscVmRunning() icons.IsIcon                  { return newIcon("vm-running") }
func VscVm() icons.IsIcon                         { return newIcon("vm") }
func VscVr() icons.IsIcon                         { return newIcon("vr") }
func VscVscodeInsiders() icons.IsIcon             { return newIcon("vscode-insiders") }
func VscVscode() icons.IsIcon                     { return newIcon("vscode") }
func VscWand() icons.IsIcon                       { return newIcon("wand") }
func VscWarning() icons.IsIcon                    { return newIcon("warning") }
func VscWatch() icons.IsIcon                      { return newIcon("watch") }
func VscWhitespace() icons.IsIcon                 { return newIcon("whitespace") }
func VscWholeWord() icons.IsIcon                  { return newIcon("whole-word") }
func VscWindow() icons.IsIcon                     { return newIcon("window") }
func VscWordWrap() icons.IsIcon                   { return newIcon("word-wrap") }
func VscWorkspaceTrusted() icons.IsIcon           { return newIcon("workspace-trusted") }
func VscWorkspaceUnknown() icons.IsIcon           { return newIcon("workspace-unknown") }
func VscWorkspaceUntrusted() icons.IsIcon         { return newIcon("workspace-untrusted") }
func VscZoomIn() icons.IsIcon                     { return newIcon("zoom-in") }
func VscZoomOut() icons.IsIcon                    { return newIcon("zoom-out") }
