package zi

import "github.com/raitucarp/gomix/icons"

func ZiAddOutline() icons.IsIcon           { return newIcon("add-outline") }
func ZiAddSolid() icons.IsIcon             { return newIcon("add-solid") }
func ZiAdjust() icons.IsIcon               { return newIcon("adjust") }
func ZiAirplane() icons.IsIcon             { return newIcon("airplane") }
func ZiAlbum() icons.IsIcon                { return newIcon("album") }
func ZiAlignCenter() icons.IsIcon          { return newIcon("align-center") }
func ZiAlignJustified() icons.IsIcon       { return newIcon("align-justified") }
func ZiAlignLeft() icons.IsIcon            { return newIcon("align-left") }
func ZiAlignRight() icons.IsIcon           { return newIcon("align-right") }
func ZiAnchor() icons.IsIcon               { return newIcon("anchor") }
func ZiAnnouncement() icons.IsIcon         { return newIcon("announcement") }
func ZiApparel() icons.IsIcon              { return newIcon("apparel") }
func ZiArrowDown() icons.IsIcon            { return newIcon("arrow-down") }
func ZiArrowLeft() icons.IsIcon            { return newIcon("arrow-left") }
func ZiArrowOutlineDown() icons.IsIcon     { return newIcon("arrow-outline-down") }
func ZiArrowOutlineLeft() icons.IsIcon     { return newIcon("arrow-outline-left") }
func ZiArrowOutlineRight() icons.IsIcon    { return newIcon("arrow-outline-right") }
func ZiArrowOutlineUp() icons.IsIcon       { return newIcon("arrow-outline-up") }
func ZiArrowRight() icons.IsIcon           { return newIcon("arrow-right") }
func ZiArrowThickDown() icons.IsIcon       { return newIcon("arrow-thick-down") }
func ZiArrowThickLeft() icons.IsIcon       { return newIcon("arrow-thick-left") }
func ZiArrowThickRight() icons.IsIcon      { return newIcon("arrow-thick-right") }
func ZiArrowThickUp() icons.IsIcon         { return newIcon("arrow-thick-up") }
func ZiArrowThinDown() icons.IsIcon        { return newIcon("arrow-thin-down") }
func ZiArrowThinLeft() icons.IsIcon        { return newIcon("arrow-thin-left") }
func ZiArrowThinRight() icons.IsIcon       { return newIcon("arrow-thin-right") }
func ZiArrowThinUp() icons.IsIcon          { return newIcon("arrow-thin-up") }
func ZiArrowUp() icons.IsIcon              { return newIcon("arrow-up") }
func ZiArtist() icons.IsIcon               { return newIcon("artist") }
func ZiAtSymbol() icons.IsIcon             { return newIcon("at-symbol") }
func ZiAttachment() icons.IsIcon           { return newIcon("attachment") }
func ZiBackspace() icons.IsIcon            { return newIcon("backspace") }
func ZiBackwardStep() icons.IsIcon         { return newIcon("backward-step") }
func ZiBackward() icons.IsIcon             { return newIcon("backward") }
func ZiBadge() icons.IsIcon                { return newIcon("badge") }
func ZiBatteryFull() icons.IsIcon          { return newIcon("battery-full") }
func ZiBatteryHalf() icons.IsIcon          { return newIcon("battery-half") }
func ZiBatteryLow() icons.IsIcon           { return newIcon("battery-low") }
func ZiBeverage() icons.IsIcon             { return newIcon("beverage") }
func ZiBlock() icons.IsIcon                { return newIcon("block") }
func ZiBluetooth() icons.IsIcon            { return newIcon("bluetooth") }
func ZiBolt() icons.IsIcon                 { return newIcon("bolt") }
func ZiBookReference() icons.IsIcon        { return newIcon("book-reference") }
func ZiBookmarkCopy2() icons.IsIcon        { return newIcon("bookmark copy 2") }
func ZiBookmarkCopy3() icons.IsIcon        { return newIcon("bookmark copy 3") }
func ZiBookmarkOutlineAdd() icons.IsIcon   { return newIcon("bookmark-outline-add") }
func ZiBookmarkOutline() icons.IsIcon      { return newIcon("bookmark-outline") }
func ZiBookmark() icons.IsIcon             { return newIcon("bookmark") }
func ZiBorderAll() icons.IsIcon            { return newIcon("border-all") }
func ZiBorderBottom() icons.IsIcon         { return newIcon("border-bottom") }
func ZiBorderHorizontal() icons.IsIcon     { return newIcon("border-horizontal") }
func ZiBorderInner() icons.IsIcon          { return newIcon("border-inner") }
func ZiBorderLeft() icons.IsIcon           { return newIcon("border-left") }
func ZiBorderNone() icons.IsIcon           { return newIcon("border-none") }
func ZiBorderOuter() icons.IsIcon          { return newIcon("border-outer") }
func ZiBorderRight() icons.IsIcon          { return newIcon("border-right") }
func ZiBorderTop() icons.IsIcon            { return newIcon("border-top") }
func ZiBorderVertical() icons.IsIcon       { return newIcon("border-vertical") }
func ZiBox() icons.IsIcon                  { return newIcon("box") }
func ZiBrightnessDown() icons.IsIcon       { return newIcon("brightness-down") }
func ZiBrightnessUp() icons.IsIcon         { return newIcon("brightness-up") }
func ZiBrowserWindowNew() icons.IsIcon     { return newIcon("browser-window-new") }
func ZiBrowserWindowOpen() icons.IsIcon    { return newIcon("browser-window-open") }
func ZiBrowserWindow() icons.IsIcon        { return newIcon("browser-window") }
func ZiBug() icons.IsIcon                  { return newIcon("bug") }
func ZiBuoy() icons.IsIcon                 { return newIcon("buoy") }
func ZiCalculator() icons.IsIcon           { return newIcon("calculator") }
func ZiCalendar() icons.IsIcon             { return newIcon("calendar") }
func ZiCamera() icons.IsIcon               { return newIcon("camera") }
func ZiChartBar() icons.IsIcon             { return newIcon("chart-bar") }
func ZiChartPie() icons.IsIcon             { return newIcon("chart-pie") }
func ZiChart() icons.IsIcon                { return newIcon("chart") }
func ZiChatBubbleDots() icons.IsIcon       { return newIcon("chat-bubble-dots") }
func ZiCheckmarkOutline() icons.IsIcon     { return newIcon("checkmark-outline") }
func ZiCheckmark() icons.IsIcon            { return newIcon("checkmark") }
func ZiCheveronDown() icons.IsIcon         { return newIcon("cheveron-down") }
func ZiCheveronLeft() icons.IsIcon         { return newIcon("cheveron-left") }
func ZiCheveronOutlineDown() icons.IsIcon  { return newIcon("cheveron-outline-down") }
func ZiCheveronOutlineLeft() icons.IsIcon  { return newIcon("cheveron-outline-left") }
func ZiCheveronOutlineRight() icons.IsIcon { return newIcon("cheveron-outline-right") }
func ZiCheveronOutlineUp() icons.IsIcon    { return newIcon("cheveron-outline-up") }
func ZiCheveronRight() icons.IsIcon        { return newIcon("cheveron-right") }
func ZiCheveronUp() icons.IsIcon           { return newIcon("cheveron-up") }
func ZiClipboard() icons.IsIcon            { return newIcon("clipboard") }
func ZiCloseOutline() icons.IsIcon         { return newIcon("close-outline") }
func ZiCloseSolid() icons.IsIcon           { return newIcon("close-solid") }
func ZiClose() icons.IsIcon                { return newIcon("close") }
func ZiCloudUpload() icons.IsIcon          { return newIcon("cloud-upload") }
func ZiCloud() icons.IsIcon                { return newIcon("cloud") }
func ZiCode() icons.IsIcon                 { return newIcon("code") }
func ZiCoffee() icons.IsIcon               { return newIcon("coffee") }
func ZiCog() icons.IsIcon                  { return newIcon("cog") }
func ZiColorPalette() icons.IsIcon         { return newIcon("color-palette") }
func ZiCompose() icons.IsIcon              { return newIcon("compose") }
func ZiComputerDesktop() icons.IsIcon      { return newIcon("computer-desktop") }
func ZiComputerLaptop() icons.IsIcon       { return newIcon("computer-laptop") }
func ZiConversation() icons.IsIcon         { return newIcon("conversation") }
func ZiCopy() icons.IsIcon                 { return newIcon("copy") }
func ZiCreditCard() icons.IsIcon           { return newIcon("credit-card") }
func ZiCurrencyDollar() icons.IsIcon       { return newIcon("currency-dollar") }
func ZiDashboard() icons.IsIcon            { return newIcon("dashboard") }
func ZiDateAdd() icons.IsIcon              { return newIcon("date-add") }
func ZiDialPad() icons.IsIcon              { return newIcon("dial-pad") }
func ZiDirections() icons.IsIcon           { return newIcon("directions") }
func ZiDocumentAdd() icons.IsIcon          { return newIcon("document-add") }
func ZiDocument() icons.IsIcon             { return newIcon("document") }
func ZiDotsHorizontalDouble() icons.IsIcon { return newIcon("dots-horizontal-double") }
func ZiDotsHorizontalTriple() icons.IsIcon { return newIcon("dots-horizontal-triple") }
func ZiDownload() icons.IsIcon             { return newIcon("download") }
func ZiDuplicate() icons.IsIcon            { return newIcon("duplicate") }
func ZiEditCopy() icons.IsIcon             { return newIcon("edit-copy") }
func ZiEditCrop() icons.IsIcon             { return newIcon("edit-crop") }
func ZiEditCut() icons.IsIcon              { return newIcon("edit-cut") }
func ZiEditPencil() icons.IsIcon           { return newIcon("edit-pencil") }
func ZiEducation() icons.IsIcon            { return newIcon("education") }
func ZiEnvelope() icons.IsIcon             { return newIcon("envelope") }
func ZiExclamationOutline() icons.IsIcon   { return newIcon("exclamation-outline") }
func ZiExclamationSolid() icons.IsIcon     { return newIcon("exclamation-solid") }
func ZiExplore() icons.IsIcon              { return newIcon("explore") }
func ZiFactory() icons.IsIcon              { return newIcon("factory") }
func ZiFastForward() icons.IsIcon          { return newIcon("fast-forward") }
func ZiFastRewind() icons.IsIcon           { return newIcon("fast-rewind") }
func ZiFilm() icons.IsIcon                 { return newIcon("film") }
func ZiFilter() icons.IsIcon               { return newIcon("filter") }
func ZiFlag() icons.IsIcon                 { return newIcon("flag") }
func ZiFlashlight() icons.IsIcon           { return newIcon("flashlight") }
func ZiFolderOutlineAdd() icons.IsIcon     { return newIcon("folder-outline-add") }
func ZiFolderOutline() icons.IsIcon        { return newIcon("folder-outline") }
func ZiFolder() icons.IsIcon               { return newIcon("folder") }
func ZiFormatBold() icons.IsIcon           { return newIcon("format-bold") }
func ZiFormatFontSize() icons.IsIcon       { return newIcon("format-font-size") }
func ZiFormatItalic() icons.IsIcon         { return newIcon("format-italic") }
func ZiFormatTextSize() icons.IsIcon       { return newIcon("format-text-size") }
func ZiFormatUnderline() icons.IsIcon      { return newIcon("format-underline") }
func ZiForwardStep() icons.IsIcon          { return newIcon("forward-step") }
func ZiForward() icons.IsIcon              { return newIcon("forward") }
func ZiGift() icons.IsIcon                 { return newIcon("gift") }
func ZiGlobe() icons.IsIcon                { return newIcon("globe") }
func ZiHandStop() icons.IsIcon             { return newIcon("hand-stop") }
func ZiHardDrive() icons.IsIcon            { return newIcon("hard-drive") }
func ZiHeadphones() icons.IsIcon           { return newIcon("headphones") }
func ZiHeart() icons.IsIcon                { return newIcon("heart") }
func ZiHome() icons.IsIcon                 { return newIcon("home") }
func ZiHot() icons.IsIcon                  { return newIcon("hot") }
func ZiHourGlass() icons.IsIcon            { return newIcon("hour-glass") }
func ZiInboxCheck() icons.IsIcon           { return newIcon("inbox-check") }
func ZiInboxDownload() icons.IsIcon        { return newIcon("inbox-download") }
func ZiInboxFull() icons.IsIcon            { return newIcon("inbox-full") }
func ZiInbox() icons.IsIcon                { return newIcon("inbox") }
func ZiIndentDecrease() icons.IsIcon       { return newIcon("indent-decrease") }
func ZiIndentIncrease() icons.IsIcon       { return newIcon("indent-increase") }
func ZiInformationOutline() icons.IsIcon   { return newIcon("information-outline") }
func ZiInformationSolid() icons.IsIcon     { return newIcon("information-solid") }
func ZiKey() icons.IsIcon                  { return newIcon("key") }
func ZiKeyboard() icons.IsIcon             { return newIcon("keyboard") }
func ZiLayers() icons.IsIcon               { return newIcon("layers") }
func ZiLibrary() icons.IsIcon              { return newIcon("library") }
func ZiLightBulb() icons.IsIcon            { return newIcon("light-bulb") }
func ZiLink() icons.IsIcon                 { return newIcon("link") }
func ZiListAdd() icons.IsIcon              { return newIcon("list-add") }
func ZiListBullet() icons.IsIcon           { return newIcon("list-bullet") }
func ZiList() icons.IsIcon                 { return newIcon("list") }
func ZiLoadBalancer() icons.IsIcon         { return newIcon("load-balancer") }
func ZiLocationCurrent() icons.IsIcon      { return newIcon("location-current") }
func ZiLocationFood() icons.IsIcon         { return newIcon("location-food") }
func ZiLocationGasStation() icons.IsIcon   { return newIcon("location-gas-station") }
func ZiLocationHotel() icons.IsIcon        { return newIcon("location-hotel") }
func ZiLocationMarina() icons.IsIcon       { return newIcon("location-marina") }
func ZiLocationPark() icons.IsIcon         { return newIcon("location-park") }
func ZiLocationRestroom() icons.IsIcon     { return newIcon("location-restroom") }
func ZiLocationShopping() icons.IsIcon     { return newIcon("location-shopping") }
func ZiLocation() icons.IsIcon             { return newIcon("location") }
func ZiLockClosed() icons.IsIcon           { return newIcon("lock-closed") }
func ZiLockOpen() icons.IsIcon             { return newIcon("lock-open") }
func ZiMap() icons.IsIcon                  { return newIcon("map") }
func ZiMenu() icons.IsIcon                 { return newIcon("menu") }
func ZiMic() icons.IsIcon                  { return newIcon("mic") }
func ZiMinusOutline() icons.IsIcon         { return newIcon("minus-outline") }
func ZiMinusSolid() icons.IsIcon           { return newIcon("minus-solid") }
func ZiMobileDevices() icons.IsIcon        { return newIcon("mobile-devices") }
func ZiMoodHappyOutline() icons.IsIcon     { return newIcon("mood-happy-outline") }
func ZiMoodHappySolid() icons.IsIcon       { return newIcon("mood-happy-solid") }
func ZiMoodNeutralOutline() icons.IsIcon   { return newIcon("mood-neutral-outline") }
func ZiMoodNeutralSolid() icons.IsIcon     { return newIcon("mood-neutral-solid") }
func ZiMoodSadOutline() icons.IsIcon       { return newIcon("mood-sad-outline") }
func ZiMoodSadSolid() icons.IsIcon         { return newIcon("mood-sad-solid") }
func ZiMouse() icons.IsIcon                { return newIcon("mouse") }
func ZiMusicAlbum() icons.IsIcon           { return newIcon("music-album") }
func ZiMusicArtist() icons.IsIcon          { return newIcon("music-artist") }
func ZiMusicNotes() icons.IsIcon           { return newIcon("music-notes") }
func ZiMusicPlaylist() icons.IsIcon        { return newIcon("music-playlist") }
func ZiNavigationMore() icons.IsIcon       { return newIcon("navigation-more") }
func ZiNetwork() icons.IsIcon              { return newIcon("network") }
func ZiNewsPaper() icons.IsIcon            { return newIcon("news-paper") }
func ZiNotification() icons.IsIcon         { return newIcon("notification") }
func ZiNotificationsOutline() icons.IsIcon { return newIcon("notifications-outline") }
func ZiNotifications() icons.IsIcon        { return newIcon("notifications") }
func ZiPaste() icons.IsIcon                { return newIcon("paste") }
func ZiPauseOutline() icons.IsIcon         { return newIcon("pause-outline") }
func ZiPauseSolid() icons.IsIcon           { return newIcon("pause-solid") }
func ZiPause() icons.IsIcon                { return newIcon("pause") }
func ZiPenTool() icons.IsIcon              { return newIcon("pen-tool") }
func ZiPhone() icons.IsIcon                { return newIcon("phone") }
func ZiPhoto() icons.IsIcon                { return newIcon("photo") }
func ZiPhpElephant() icons.IsIcon          { return newIcon("php-elephant") }
func ZiPin() icons.IsIcon                  { return newIcon("pin") }
func ZiPlayOutline() icons.IsIcon          { return newIcon("play-outline") }
func ZiPlay() icons.IsIcon                 { return newIcon("play") }
func ZiPlaylist() icons.IsIcon             { return newIcon("playlist") }
func ZiPlugin() icons.IsIcon               { return newIcon("plugin") }
func ZiPortfolio() icons.IsIcon            { return newIcon("portfolio") }
func ZiPrinter() icons.IsIcon              { return newIcon("printer") }
func ZiPylon() icons.IsIcon                { return newIcon("pylon") }
func ZiQuestion() icons.IsIcon             { return newIcon("question") }
func ZiQueue() icons.IsIcon                { return newIcon("queue") }
func ZiRadarCopy2() icons.IsIcon           { return newIcon("radar copy 2") }
func ZiRadar() icons.IsIcon                { return newIcon("radar") }
func ZiRadio() icons.IsIcon                { return newIcon("radio") }
func ZiRefresh() icons.IsIcon              { return newIcon("refresh") }
func ZiReload() icons.IsIcon               { return newIcon("reload") }
func ZiReplyAll() icons.IsIcon             { return newIcon("reply-all") }
func ZiReply() icons.IsIcon                { return newIcon("reply") }
func ZiRepost() icons.IsIcon               { return newIcon("repost") }
func ZiSaveDisk() icons.IsIcon             { return newIcon("save-disk") }
func ZiScreenFull() icons.IsIcon           { return newIcon("screen-full") }
func ZiSearch() icons.IsIcon               { return newIcon("search") }
func ZiSend() icons.IsIcon                 { return newIcon("send") }
func ZiServers() icons.IsIcon              { return newIcon("servers") }
func ZiShare01() icons.IsIcon              { return newIcon("share-01") }
func ZiShareAlt() icons.IsIcon             { return newIcon("share-alt") }
func ZiShare() icons.IsIcon                { return newIcon("share") }
func ZiShield() icons.IsIcon               { return newIcon("shield") }
func ZiShoppingCart() icons.IsIcon         { return newIcon("shopping-cart") }
func ZiShowSidebar() icons.IsIcon          { return newIcon("show-sidebar") }
func ZiShuffle() icons.IsIcon              { return newIcon("shuffle") }
func ZiStandBy() icons.IsIcon              { return newIcon("stand-by") }
func ZiStarFull() icons.IsIcon             { return newIcon("star-full") }
func ZiStation() icons.IsIcon              { return newIcon("station") }
func ZiStepBackward() icons.IsIcon         { return newIcon("step-backward") }
func ZiStepForward() icons.IsIcon          { return newIcon("step-forward") }
func ZiStethoscope() icons.IsIcon          { return newIcon("stethoscope") }
func ZiStoreFront() icons.IsIcon           { return newIcon("store-front") }
func ZiStrokeWidth() icons.IsIcon          { return newIcon("stroke-width") }
func ZiSubdirectoryLeft() icons.IsIcon     { return newIcon("subdirectory-left") }
func ZiSubdirectoryRight() icons.IsIcon    { return newIcon("subdirectory-right") }
func ZiSwap() icons.IsIcon                 { return newIcon("swap") }
func ZiTablet() icons.IsIcon               { return newIcon("tablet") }
func ZiTag() icons.IsIcon                  { return newIcon("tag") }
func ZiTarget() icons.IsIcon               { return newIcon("target") }
func ZiTextBox() icons.IsIcon              { return newIcon("text-box") }
func ZiTextDecoration() icons.IsIcon       { return newIcon("text-decoration") }
func ZiThermometer() icons.IsIcon          { return newIcon("thermometer") }
func ZiThumbsDown() icons.IsIcon           { return newIcon("thumbs-down") }
func ZiThumbsUp() icons.IsIcon             { return newIcon("thumbs-up") }
func ZiTicket() icons.IsIcon               { return newIcon("ticket") }
func ZiTime() icons.IsIcon                 { return newIcon("time") }
func ZiTimer() icons.IsIcon                { return newIcon("timer") }
func ZiToolsCopy() icons.IsIcon            { return newIcon("tools copy") }
func ZiTranslate() icons.IsIcon            { return newIcon("translate") }
func ZiTrash() icons.IsIcon                { return newIcon("trash") }
func ZiTravelBus() icons.IsIcon            { return newIcon("travel-bus") }
func ZiTravelCar() icons.IsIcon            { return newIcon("travel-car") }
func ZiTravelCase() icons.IsIcon           { return newIcon("travel-case") }
func ZiTravelTaxiCab() icons.IsIcon        { return newIcon("travel-taxi-cab") }
func ZiTravelTrain() icons.IsIcon          { return newIcon("travel-train") }
func ZiTravelWalk() icons.IsIcon           { return newIcon("travel-walk") }
func ZiTravel() icons.IsIcon               { return newIcon("travel") }
func ZiTrophy() icons.IsIcon               { return newIcon("trophy") }
func ZiTuning() icons.IsIcon               { return newIcon("tuning") }
func ZiUpload() icons.IsIcon               { return newIcon("upload") }
func ZiUsb() icons.IsIcon                  { return newIcon("usb") }
func ZiUserAdd() icons.IsIcon              { return newIcon("user-add") }
func ZiUserGroup() icons.IsIcon            { return newIcon("user-group") }
func ZiUserSolidCircle() icons.IsIcon      { return newIcon("user-solid-circle") }
func ZiUserSolidSquare() icons.IsIcon      { return newIcon("user-solid-square") }
func ZiUser() icons.IsIcon                 { return newIcon("user") }
func ZiVector() icons.IsIcon               { return newIcon("vector") }
func ZiVideoCamera() icons.IsIcon          { return newIcon("video-camera") }
func ZiViewCarousel() icons.IsIcon         { return newIcon("view-carousel") }
func ZiViewColumn() icons.IsIcon           { return newIcon("view-column") }
func ZiViewHide() icons.IsIcon             { return newIcon("view-hide") }
func ZiViewList() icons.IsIcon             { return newIcon("view-list") }
func ZiViewShow() icons.IsIcon             { return newIcon("view-show") }
func ZiViewTile() icons.IsIcon             { return newIcon("view-tile") }
func ZiVolumeDown() icons.IsIcon           { return newIcon("volume-down") }
func ZiVolumeMute() icons.IsIcon           { return newIcon("volume-mute") }
func ZiVolumeOff() icons.IsIcon            { return newIcon("volume-off") }
func ZiVolumeUp() icons.IsIcon             { return newIcon("volume-up") }
func ZiWallet() icons.IsIcon               { return newIcon("wallet") }
func ZiWatch() icons.IsIcon                { return newIcon("watch") }
func ZiWindowNew() icons.IsIcon            { return newIcon("window-new") }
func ZiWindowOpen() icons.IsIcon           { return newIcon("window-open") }
func ZiWindow() icons.IsIcon               { return newIcon("window") }
func ZiWrench() icons.IsIcon               { return newIcon("wrench") }
func ZiYinYang() icons.IsIcon              { return newIcon("yin-yang") }
func ZiZoomIn() icons.IsIcon               { return newIcon("zoom-in") }
func ZiZoomOut() icons.IsIcon              { return newIcon("zoom-out") }
