package im

import "github.com/raitucarp/gomix/icons"

func Im500Px() icons.IsIcon              { return newIcon("428-500px") }
func ImAccessibility() icons.IsIcon      { return newIcon("179-accessibility") }
func ImAddressBook() icons.IsIcon        { return newIcon("069-address-book") }
func ImAidKit() icons.IsIcon             { return newIcon("153-aid-kit") }
func ImAirplane() icons.IsIcon           { return newIcon("176-airplane") }
func ImAlarm() icons.IsIcon              { return newIcon("081-alarm") }
func ImAmazon() icons.IsIcon             { return newIcon("392-amazon") }
func ImAndroid() icons.IsIcon            { return newIcon("449-android") }
func ImAngry() icons.IsIcon              { return newIcon("238-angry") }
func ImAngry2() icons.IsIcon             { return newIcon("239-angry2") }
func ImAppleinc() icons.IsIcon           { return newIcon("447-appleinc") }
func ImArrowDown() icons.IsIcon          { return newIcon("311-arrow-down") }
func ImArrowDown2() icons.IsIcon         { return newIcon("319-arrow-down2") }
func ImArrowDownLeft() icons.IsIcon      { return newIcon("312-arrow-down-left") }
func ImArrowDownLeft2() icons.IsIcon     { return newIcon("320-arrow-down-left2") }
func ImArrowDownRight() icons.IsIcon     { return newIcon("310-arrow-down-right") }
func ImArrowDownRight2() icons.IsIcon    { return newIcon("318-arrow-down-right2") }
func ImArrowLeft() icons.IsIcon          { return newIcon("313-arrow-left") }
func ImArrowLeft2() icons.IsIcon         { return newIcon("321-arrow-left2") }
func ImArrowRight() icons.IsIcon         { return newIcon("309-arrow-right") }
func ImArrowRight2() icons.IsIcon        { return newIcon("317-arrow-right2") }
func ImArrowUp() icons.IsIcon            { return newIcon("307-arrow-up") }
func ImArrowUp2() icons.IsIcon           { return newIcon("315-arrow-up2") }
func ImArrowUpLeft() icons.IsIcon        { return newIcon("306-arrow-up-left") }
func ImArrowUpLeft2() icons.IsIcon       { return newIcon("314-arrow-up-left2") }
func ImArrowUpRight() icons.IsIcon       { return newIcon("308-arrow-up-right") }
func ImArrowUpRight2() icons.IsIcon      { return newIcon("316-arrow-up-right2") }
func ImAttachment() icons.IsIcon         { return newIcon("206-attachment") }
func ImBackward() icons.IsIcon           { return newIcon("283-backward") }
func ImBackward2() icons.IsIcon          { return newIcon("288-backward2") }
func ImBaffled() icons.IsIcon            { return newIcon("244-baffled") }
func ImBaffled2() icons.IsIcon           { return newIcon("245-baffled2") }
func ImBarcode() icons.IsIcon            { return newIcon("056-barcode") }
func ImBasecamp() icons.IsIcon           { return newIcon("435-basecamp") }
func ImBehance() icons.IsIcon            { return newIcon("425-behance") }
func ImBehance2() icons.IsIcon           { return newIcon("426-behance2") }
func ImBell() icons.IsIcon               { return newIcon("082-bell") }
func ImBin() icons.IsIcon                { return newIcon("173-bin") }
func ImBin2() icons.IsIcon               { return newIcon("174-bin2") }
func ImBinoculars() icons.IsIcon         { return newIcon("134-binoculars") }
func ImBlocked() icons.IsIcon            { return newIcon("271-blocked") }
func ImBlog() icons.IsIcon               { return newIcon("010-blog") }
func ImBlogger() icons.IsIcon            { return newIcon("440-blogger") }
func ImBlogger2() icons.IsIcon           { return newIcon("441-blogger2") }
func ImBold() icons.IsIcon               { return newIcon("355-bold") }
func ImBook() icons.IsIcon               { return newIcon("032-book") }
func ImBookmark() icons.IsIcon           { return newIcon("211-bookmark") }
func ImBookmarks() icons.IsIcon          { return newIcon("212-bookmarks") }
func ImBooks() icons.IsIcon              { return newIcon("033-books") }
func ImBoxAdd() icons.IsIcon             { return newIcon("095-box-add") }
func ImBoxRemove() icons.IsIcon          { return newIcon("096-box-remove") }
func ImBriefcase() icons.IsIcon          { return newIcon("175-briefcase") }
func ImBrightnessContrast() icons.IsIcon { return newIcon("215-brightness-contrast") }
func ImBubble() icons.IsIcon             { return newIcon("108-bubble") }
func ImBubble2() icons.IsIcon            { return newIcon("111-bubble2") }
func ImBubbles() icons.IsIcon            { return newIcon("109-bubbles") }
func ImBubbles2() icons.IsIcon           { return newIcon("110-bubbles2") }
func ImBubbles3() icons.IsIcon           { return newIcon("112-bubbles3") }
func ImBubbles4() icons.IsIcon           { return newIcon("113-bubbles4") }
func ImBug() icons.IsIcon                { return newIcon("154-bug") }
func ImBullhorn() icons.IsIcon           { return newIcon("027-bullhorn") }
func ImCalculator() icons.IsIcon         { return newIcon("065-calculator") }
func ImCalendar() icons.IsIcon           { return newIcon("084-calendar") }
func ImCamera() icons.IsIcon             { return newIcon("016-camera") }
func ImCancelCircle() icons.IsIcon       { return newIcon("270-cancel-circle") }
func ImCart() icons.IsIcon               { return newIcon("059-cart") }
func ImCheckboxChecked() icons.IsIcon    { return newIcon("339-checkbox-checked") }
func ImCheckboxUnchecked() icons.IsIcon  { return newIcon("340-checkbox-unchecked") }
func ImCheckmark() icons.IsIcon          { return newIcon("273-checkmark") }
func ImCheckmark2() icons.IsIcon         { return newIcon("274-checkmark2") }
func ImChrome() icons.IsIcon             { return newIcon("474-chrome") }
func ImCircleDown() icons.IsIcon         { return newIcon("324-circle-down") }
func ImCircleLeft() icons.IsIcon         { return newIcon("325-circle-left") }
func ImCircleRight() icons.IsIcon        { return newIcon("323-circle-right") }
func ImCircleUp() icons.IsIcon           { return newIcon("322-circle-up") }
func ImClearFormatting() icons.IsIcon    { return newIcon("368-clear-formatting") }
func ImClipboard() icons.IsIcon          { return newIcon("185-clipboard") }
func ImClock() icons.IsIcon              { return newIcon("079-clock") }
func ImClock2() icons.IsIcon             { return newIcon("080-clock2") }
func ImCloud() icons.IsIcon              { return newIcon("194-cloud") }
func ImCloudCheck() icons.IsIcon         { return newIcon("197-cloud-check") }
func ImCloudDownload() icons.IsIcon      { return newIcon("195-cloud-download") }
func ImCloudUpload() icons.IsIcon        { return newIcon("196-cloud-upload") }
func ImClubs() icons.IsIcon              { return newIcon("025-clubs") }
func ImCodepen() icons.IsIcon            { return newIcon("489-codepen") }
func ImCog() icons.IsIcon                { return newIcon("149-cog") }
func ImCogs() icons.IsIcon               { return newIcon("150-cogs") }
func ImCoinDollar() icons.IsIcon         { return newIcon("060-coin-dollar") }
func ImCoinEuro() icons.IsIcon           { return newIcon("061-coin-euro") }
func ImCoinPound() icons.IsIcon          { return newIcon("062-coin-pound") }
func ImCoinYen() icons.IsIcon            { return newIcon("063-coin-yen") }
func ImCommand() icons.IsIcon            { return newIcon("335-command") }
func ImCompass() icons.IsIcon            { return newIcon("074-compass") }
func ImCompass2() icons.IsIcon           { return newIcon("075-compass2") }
func ImConfused() icons.IsIcon           { return newIcon("246-confused") }
func ImConfused2() icons.IsIcon          { return newIcon("247-confused2") }
func ImConnection() icons.IsIcon         { return newIcon("028-connection") }
func ImContrast() icons.IsIcon           { return newIcon("214-contrast") }
func ImCool() icons.IsIcon               { return newIcon("236-cool") }
func ImCool2() icons.IsIcon              { return newIcon("237-cool2") }
func ImCopy() icons.IsIcon               { return newIcon("045-copy") }
func ImCreditCard() icons.IsIcon         { return newIcon("064-credit-card") }
func ImCrop() icons.IsIcon               { return newIcon("344-crop") }
func ImCross() icons.IsIcon              { return newIcon("272-cross") }
func ImCrying() icons.IsIcon             { return newIcon("258-crying") }
func ImCrying2() icons.IsIcon            { return newIcon("259-crying2") }
func ImCss3() icons.IsIcon               { return newIcon("487-css3") }
func ImCtrl() icons.IsIcon               { return newIcon("337-ctrl") }
func ImDatabase() icons.IsIcon           { return newIcon("101-database") }
func ImDelicious() icons.IsIcon          { return newIcon("462-delicious") }
func ImDeviantart() icons.IsIcon         { return newIcon("427-deviantart") }
func ImDiamonds() icons.IsIcon           { return newIcon("026-diamonds") }
func ImDice() icons.IsIcon               { return newIcon("022-dice") }
func ImDisplay() icons.IsIcon            { return newIcon("087-display") }
func ImDownload() icons.IsIcon           { return newIcon("097-download") }
func ImDownload2() icons.IsIcon          { return newIcon("198-download2") }
func ImDownload3() icons.IsIcon          { return newIcon("200-download3") }
func ImDrawer() icons.IsIcon             { return newIcon("093-drawer") }
func ImDrawer2() icons.IsIcon            { return newIcon("094-drawer2") }
func ImDribbble() icons.IsIcon           { return newIcon("424-dribbble") }
func ImDrive() icons.IsIcon              { return newIcon("100-drive") }
func ImDropbox() icons.IsIcon            { return newIcon("431-dropbox") }
func ImDroplet() icons.IsIcon            { return newIcon("012-droplet") }
func ImEarth() icons.IsIcon              { return newIcon("203-earth") }
func ImEdge() icons.IsIcon               { return newIcon("477-edge") }
func ImEject() icons.IsIcon              { return newIcon("294-eject") }
func ImEllo() icons.IsIcon               { return newIcon("439-ello") }
func ImEmbed() icons.IsIcon              { return newIcon("384-embed") }
func ImEmbed2() icons.IsIcon             { return newIcon("385-embed2") }
func ImEnlarge() icons.IsIcon            { return newIcon("138-enlarge") }
func ImEnlarge2() icons.IsIcon           { return newIcon("140-enlarge2") }
func ImEnter() icons.IsIcon              { return newIcon("276-enter") }
func ImEnvelop() icons.IsIcon            { return newIcon("070-envelop") }
func ImEqualizer() icons.IsIcon          { return newIcon("147-equalizer") }
func ImEqualizer2() icons.IsIcon         { return newIcon("148-equalizer2") }
func ImEvil() icons.IsIcon               { return newIcon("240-evil") }
func ImEvil2() icons.IsIcon              { return newIcon("241-evil2") }
func ImExit() icons.IsIcon               { return newIcon("277-exit") }
func ImEye() icons.IsIcon                { return newIcon("207-eye") }
func ImEyeBlocked() icons.IsIcon         { return newIcon("210-eye-blocked") }
func ImEyeMinus() icons.IsIcon           { return newIcon("209-eye-minus") }
func ImEyePlus() icons.IsIcon            { return newIcon("208-eye-plus") }
func ImEyedropper() icons.IsIcon         { return newIcon("011-eyedropper") }
func ImFacebook() icons.IsIcon           { return newIcon("401-facebook") }
func ImFacebook2() icons.IsIcon          { return newIcon("402-facebook2") }
func ImFeed() icons.IsIcon               { return newIcon("030-feed") }
func ImFileEmpty() icons.IsIcon          { return newIcon("037-file-empty") }
func ImFileExcel() icons.IsIcon          { return newIcon("483-file-excel") }
func ImFileMusic() icons.IsIcon          { return newIcon("041-file-music") }
func ImFileOpenoffice() icons.IsIcon     { return newIcon("481-file-openoffice") }
func ImFilePdf() icons.IsIcon            { return newIcon("480-file-pdf") }
func ImFilePicture() icons.IsIcon        { return newIcon("040-file-picture") }
func ImFilePlay() icons.IsIcon           { return newIcon("042-file-play") }
func ImFileText() icons.IsIcon           { return newIcon("035-file-text") }
func ImFileText2() icons.IsIcon          { return newIcon("039-file-text2") }
func ImFileVideo() icons.IsIcon          { return newIcon("043-file-video") }
func ImFileWord() icons.IsIcon           { return newIcon("482-file-word") }
func ImFileZip() icons.IsIcon            { return newIcon("044-file-zip") }
func ImFilesEmpty() icons.IsIcon         { return newIcon("038-files-empty") }
func ImFilm() icons.IsIcon               { return newIcon("020-film") }
func ImFilter() icons.IsIcon             { return newIcon("348-filter") }
func ImFinder() icons.IsIcon             { return newIcon("448-finder") }
func ImFire() icons.IsIcon               { return newIcon("170-fire") }
func ImFirefox() icons.IsIcon            { return newIcon("475-firefox") }
func ImFirst() icons.IsIcon              { return newIcon("290-first") }
func ImFlag() icons.IsIcon               { return newIcon("205-flag") }
func ImFlattr() icons.IsIcon             { return newIcon("470-flattr") }
func ImFlickr() icons.IsIcon             { return newIcon("420-flickr") }
func ImFlickr2() icons.IsIcon            { return newIcon("421-flickr2") }
func ImFlickr3() icons.IsIcon            { return newIcon("422-flickr3") }
func ImFlickr4() icons.IsIcon            { return newIcon("423-flickr4") }
func ImFloppyDisk() icons.IsIcon         { return newIcon("099-floppy-disk") }
func ImFolder() icons.IsIcon             { return newIcon("048-folder") }
func ImFolderDownload() icons.IsIcon     { return newIcon("052-folder-download") }
func ImFolderMinus() icons.IsIcon        { return newIcon("051-folder-minus") }
func ImFolderOpen() icons.IsIcon         { return newIcon("049-folder-open") }
func ImFolderPlus() icons.IsIcon         { return newIcon("050-folder-plus") }
func ImFolderUpload() icons.IsIcon       { return newIcon("053-folder-upload") }
func ImFont() icons.IsIcon               { return newIcon("349-font") }
func ImFontSize() icons.IsIcon           { return newIcon("354-font-size") }
func ImForward() icons.IsIcon            { return newIcon("106-forward") }
func ImForward2() icons.IsIcon           { return newIcon("284-forward2") }
func ImForward3() icons.IsIcon           { return newIcon("289-forward3") }
func ImFoursquare() icons.IsIcon         { return newIcon("471-foursquare") }
func ImFrustrated() icons.IsIcon         { return newIcon("256-frustrated") }
func ImFrustrated2() icons.IsIcon        { return newIcon("257-frustrated2") }
func ImGift() icons.IsIcon               { return newIcon("160-gift") }
func ImGit() icons.IsIcon                { return newIcon("488-git") }
func ImGithub() icons.IsIcon             { return newIcon("433-github") }
func ImGlass() icons.IsIcon              { return newIcon("161-glass") }
func ImGlass2() icons.IsIcon             { return newIcon("162-glass2") }
func ImGoogle() icons.IsIcon             { return newIcon("393-google") }
func ImGoogle2() icons.IsIcon            { return newIcon("394-google2") }
func ImGoogle3() icons.IsIcon            { return newIcon("395-google3") }
func ImGoogleDrive() icons.IsIcon        { return newIcon("400-google-drive") }
func ImGooglePlus() icons.IsIcon         { return newIcon("396-google-plus") }
func ImGooglePlus2() icons.IsIcon        { return newIcon("397-google-plus2") }
func ImGooglePlus3() icons.IsIcon        { return newIcon("398-google-plus3") }
func ImGrin() icons.IsIcon               { return newIcon("234-grin") }
func ImGrin2() icons.IsIcon              { return newIcon("235-grin2") }
func ImHackernews() icons.IsIcon         { return newIcon("456-hackernews") }
func ImHammer() icons.IsIcon             { return newIcon("151-hammer") }
func ImHammer2() icons.IsIcon            { return newIcon("169-hammer2") }
func ImHangouts() icons.IsIcon           { return newIcon("399-hangouts") }
func ImHappy() icons.IsIcon              { return newIcon("224-happy") }
func ImHappy2() icons.IsIcon             { return newIcon("225-happy2") }
func ImHeadphones() icons.IsIcon         { return newIcon("017-headphones") }
func ImHeart() icons.IsIcon              { return newIcon("219-heart") }
func ImHeartBroken() icons.IsIcon        { return newIcon("220-heart-broken") }
func ImHipster() icons.IsIcon            { return newIcon("250-hipster") }
func ImHipster2() icons.IsIcon           { return newIcon("251-hipster2") }
func ImHistory() icons.IsIcon            { return newIcon("078-history") }
func ImHome() icons.IsIcon               { return newIcon("001-home") }
func ImHome2() icons.IsIcon              { return newIcon("002-home2") }
func ImHome3() icons.IsIcon              { return newIcon("003-home3") }
func ImHourGlass() icons.IsIcon          { return newIcon("122-hour-glass") }
func ImHtmlFive() icons.IsIcon           { return newIcon("485-html-five") }
func ImHtmlFive2() icons.IsIcon          { return newIcon("486-html-five2") }
func ImIcoMoon() icons.IsIcon            { return newIcon("491-IcoMoon") }
func ImIe() icons.IsIcon                 { return newIcon("476-IE") }
func ImImage() icons.IsIcon              { return newIcon("014-image") }
func ImImages() icons.IsIcon             { return newIcon("015-images") }
func ImIndentDecrease() icons.IsIcon     { return newIcon("381-indent-decrease") }
func ImIndentIncrease() icons.IsIcon     { return newIcon("380-indent-increase") }
func ImInfinite() icons.IsIcon           { return newIcon("304-infinite") }
func ImInfo() icons.IsIcon               { return newIcon("269-info") }
func ImInsertTemplate() icons.IsIcon     { return newIcon("371-insert-template") }
func ImInstagram() icons.IsIcon          { return newIcon("403-instagram") }
func ImItalic() icons.IsIcon             { return newIcon("357-italic") }
func ImJoomla() icons.IsIcon             { return newIcon("438-joomla") }
func ImKey() icons.IsIcon                { return newIcon("142-key") }
func ImKey2() icons.IsIcon               { return newIcon("143-key2") }
func ImKeyboard() icons.IsIcon           { return newIcon("086-keyboard") }
func ImLab() icons.IsIcon                { return newIcon("171-lab") }
func ImLanyrd() icons.IsIcon             { return newIcon("419-lanyrd") }
func ImLaptop() icons.IsIcon             { return newIcon("088-laptop") }
func ImLast() icons.IsIcon               { return newIcon("291-last") }
func ImLastfm() icons.IsIcon             { return newIcon("460-lastfm") }
func ImLastfm2() icons.IsIcon            { return newIcon("461-lastfm2") }
func ImLeaf() icons.IsIcon               { return newIcon("165-leaf") }
func ImLibrary() icons.IsIcon            { return newIcon("034-library") }
func ImLibreoffice() icons.IsIcon        { return newIcon("484-libreoffice") }
func ImLifebuoy() icons.IsIcon           { return newIcon("066-lifebuoy") }
func ImLigature() icons.IsIcon           { return newIcon("350-ligature") }
func ImLigature2() icons.IsIcon          { return newIcon("351-ligature2") }
func ImLink() icons.IsIcon               { return newIcon("204-link") }
func ImLinkedin() icons.IsIcon           { return newIcon("458-linkedin") }
func ImLinkedin2() icons.IsIcon          { return newIcon("459-linkedin2") }
func ImList() icons.IsIcon               { return newIcon("187-list") }
func ImList2() icons.IsIcon              { return newIcon("188-list2") }
func ImListNumbered() icons.IsIcon       { return newIcon("186-list-numbered") }
func ImLocation() icons.IsIcon           { return newIcon("072-location") }
func ImLocation2() icons.IsIcon          { return newIcon("073-location2") }
func ImLock() icons.IsIcon               { return newIcon("144-lock") }
func ImLoop() icons.IsIcon               { return newIcon("302-loop") }
func ImLoop2() icons.IsIcon              { return newIcon("303-loop2") }
func ImLtr() icons.IsIcon                { return newIcon("373-ltr") }
func ImMagicWand() icons.IsIcon          { return newIcon("152-magic-wand") }
func ImMagnet() icons.IsIcon             { return newIcon("172-magnet") }
func ImMail() icons.IsIcon               { return newIcon("388-mail") }
func ImMail2() icons.IsIcon              { return newIcon("389-mail2") }
func ImMail3() icons.IsIcon              { return newIcon("390-mail3") }
func ImMail4() icons.IsIcon              { return newIcon("391-mail4") }
func ImMakeGroup() icons.IsIcon          { return newIcon("345-make-group") }
func ImMan() icons.IsIcon                { return newIcon("221-man") }
func ImManWoman() icons.IsIcon           { return newIcon("223-man-woman") }
func ImMap() icons.IsIcon                { return newIcon("076-map") }
func ImMap2() icons.IsIcon               { return newIcon("077-map2") }
func ImMenu() icons.IsIcon               { return newIcon("190-menu") }
func ImMenu2() icons.IsIcon              { return newIcon("191-menu2") }
func ImMenu3() icons.IsIcon              { return newIcon("192-menu3") }
func ImMenu4() icons.IsIcon              { return newIcon("193-menu4") }
func ImMeter() icons.IsIcon              { return newIcon("167-meter") }
func ImMeter2() icons.IsIcon             { return newIcon("168-meter2") }
func ImMic() icons.IsIcon                { return newIcon("031-mic") }
func ImMinus() icons.IsIcon              { return newIcon("268-minus") }
func ImMobile() icons.IsIcon             { return newIcon("089-mobile") }
func ImMobile2() icons.IsIcon            { return newIcon("090-mobile2") }
func ImMoveDown() icons.IsIcon           { return newIcon("328-move-down") }
func ImMoveUp() icons.IsIcon             { return newIcon("327-move-up") }
func ImMug() icons.IsIcon                { return newIcon("163-mug") }
func ImMusic() icons.IsIcon              { return newIcon("018-music") }
func ImNeutral() icons.IsIcon            { return newIcon("248-neutral") }
func ImNeutral2() icons.IsIcon           { return newIcon("249-neutral2") }
func ImNewTab() icons.IsIcon             { return newIcon("383-new-tab") }
func ImNewspaper() icons.IsIcon          { return newIcon("005-newspaper") }
func ImNext() icons.IsIcon               { return newIcon("282-next") }
func ImNext2() icons.IsIcon              { return newIcon("293-next2") }
func ImNotification() icons.IsIcon       { return newIcon("265-notification") }
func ImNpm() icons.IsIcon                { return newIcon("434-npm") }
func ImOffice() icons.IsIcon             { return newIcon("004-office") }
func ImOmega() icons.IsIcon              { return newIcon("359-omega") }
func ImOnedrive() icons.IsIcon           { return newIcon("432-onedrive") }
func ImOpera() icons.IsIcon              { return newIcon("479-opera") }
func ImOpt() icons.IsIcon                { return newIcon("338-opt") }
func ImPacman() icons.IsIcon             { return newIcon("023-pacman") }
func ImPageBreak() icons.IsIcon          { return newIcon("361-page-break") }
func ImPagebreak() icons.IsIcon          { return newIcon("367-pagebreak") }
func ImPaintFormat() icons.IsIcon        { return newIcon("013-paint-format") }
func ImParagraphCenter() icons.IsIcon    { return newIcon("377-paragraph-center") }
func ImParagraphJustify() icons.IsIcon   { return newIcon("379-paragraph-justify") }
func ImParagraphLeft() icons.IsIcon      { return newIcon("376-paragraph-left") }
func ImParagraphRight() icons.IsIcon     { return newIcon("378-paragraph-right") }
func ImPaste() icons.IsIcon              { return newIcon("046-paste") }
func ImPause() icons.IsIcon              { return newIcon("279-pause") }
func ImPause2() icons.IsIcon             { return newIcon("286-pause2") }
func ImPaypal() icons.IsIcon             { return newIcon("473-paypal") }
func ImPen() icons.IsIcon                { return newIcon("009-pen") }
func ImPencil() icons.IsIcon             { return newIcon("006-pencil") }
func ImPencil2() icons.IsIcon            { return newIcon("007-pencil2") }
func ImPhone() icons.IsIcon              { return newIcon("067-phone") }
func ImPhoneHangUp() icons.IsIcon        { return newIcon("068-phone-hang-up") }
func ImPieChart() icons.IsIcon           { return newIcon("155-pie-chart") }
func ImPilcrow() icons.IsIcon            { return newIcon("372-pilcrow") }
func ImPinterest() icons.IsIcon          { return newIcon("466-pinterest") }
func ImPinterest2() icons.IsIcon         { return newIcon("467-pinterest2") }
func ImPlay() icons.IsIcon               { return newIcon("019-play") }
func ImPlay2() icons.IsIcon              { return newIcon("278-play2") }
func ImPlay3() icons.IsIcon              { return newIcon("285-play3") }
func ImPlus() icons.IsIcon               { return newIcon("267-plus") }
func ImPodcast() icons.IsIcon            { return newIcon("029-podcast") }
func ImPointDown() icons.IsIcon          { return newIcon("262-point-down") }
func ImPointLeft() icons.IsIcon          { return newIcon("263-point-left") }
func ImPointRight() icons.IsIcon         { return newIcon("261-point-right") }
func ImPointUp() icons.IsIcon            { return newIcon("260-point-up") }
func ImPower() icons.IsIcon              { return newIcon("182-power") }
func ImPowerCord() icons.IsIcon          { return newIcon("184-power-cord") }
func ImPrevious() icons.IsIcon           { return newIcon("281-previous") }
func ImPrevious2() icons.IsIcon          { return newIcon("292-previous2") }
func ImPriceTag() icons.IsIcon           { return newIcon("054-price-tag") }
func ImPriceTags() icons.IsIcon          { return newIcon("055-price-tags") }
func ImPrinter() icons.IsIcon            { return newIcon("085-printer") }
func ImProfile() icons.IsIcon            { return newIcon("036-profile") }
func ImPushpin() icons.IsIcon            { return newIcon("071-pushpin") }
func ImQrcode() icons.IsIcon             { return newIcon("057-qrcode") }
func ImQuestion() icons.IsIcon           { return newIcon("266-question") }
func ImQuill() icons.IsIcon              { return newIcon("008-quill") }
func ImQuotesLeft() icons.IsIcon         { return newIcon("120-quotes-left") }
func ImQuotesRight() icons.IsIcon        { return newIcon("121-quotes-right") }
func ImRadioChecked() icons.IsIcon       { return newIcon("341-radio-checked") }
func ImRadioChecked2() icons.IsIcon      { return newIcon("342-radio-checked2") }
func ImRadioUnchecked() icons.IsIcon     { return newIcon("343-radio-unchecked") }
func ImReddit() icons.IsIcon             { return newIcon("455-reddit") }
func ImRedo() icons.IsIcon               { return newIcon("103-redo") }
func ImRedo2() icons.IsIcon              { return newIcon("105-redo2") }
func ImRenren() icons.IsIcon             { return newIcon("410-renren") }
func ImReply() icons.IsIcon              { return newIcon("107-reply") }
func ImRoad() icons.IsIcon               { return newIcon("178-road") }
func ImRocket() icons.IsIcon             { return newIcon("166-rocket") }
func ImRss() icons.IsIcon                { return newIcon("412-rss") }
func ImRss2() icons.IsIcon               { return newIcon("413-rss2") }
func ImRtl() icons.IsIcon                { return newIcon("374-rtl") }
func ImSad() icons.IsIcon                { return newIcon("230-sad") }
func ImSad2() icons.IsIcon               { return newIcon("231-sad2") }
func ImSafari() icons.IsIcon             { return newIcon("478-safari") }
func ImScissors() icons.IsIcon           { return newIcon("347-scissors") }
func ImSearch() icons.IsIcon             { return newIcon("135-search") }
func ImSection() icons.IsIcon            { return newIcon("375-section") }
func ImShare() icons.IsIcon              { return newIcon("382-share") }
func ImShare2() icons.IsIcon             { return newIcon("387-share2") }
func ImShield() icons.IsIcon             { return newIcon("181-shield") }
func ImShift() icons.IsIcon              { return newIcon("336-shift") }
func ImShocked() icons.IsIcon            { return newIcon("242-shocked") }
func ImShocked2() icons.IsIcon           { return newIcon("243-shocked2") }
func ImShrink() icons.IsIcon             { return newIcon("139-shrink") }
func ImShrink2() icons.IsIcon            { return newIcon("141-shrink2") }
func ImShuffle() icons.IsIcon            { return newIcon("305-shuffle") }
func ImSigma() icons.IsIcon              { return newIcon("360-sigma") }
func ImSinaWeibo() icons.IsIcon          { return newIcon("411-sina-weibo") }
func ImSkype() icons.IsIcon              { return newIcon("454-skype") }
func ImSleepy() icons.IsIcon             { return newIcon("254-sleepy") }
func ImSleepy2() icons.IsIcon            { return newIcon("255-sleepy2") }
func ImSmile() icons.IsIcon              { return newIcon("226-smile") }
func ImSmile2() icons.IsIcon             { return newIcon("227-smile2") }
func ImSortAlphaAsc() icons.IsIcon       { return newIcon("329-sort-alpha-asc") }
func ImSortAlphaDesc() icons.IsIcon      { return newIcon("330-sort-alpha-desc") }
func ImSortAmountAsc() icons.IsIcon      { return newIcon("333-sort-amount-asc") }
func ImSortAmountDesc() icons.IsIcon     { return newIcon("334-sort-amount-desc") }
func ImSortNumbericDesc() icons.IsIcon   { return newIcon("332-sort-numberic-desc") }
func ImSortNumericAsc() icons.IsIcon     { return newIcon("331-sort-numeric-asc") }
func ImSoundcloud() icons.IsIcon         { return newIcon("452-soundcloud") }
func ImSoundcloud2() icons.IsIcon        { return newIcon("453-soundcloud2") }
func ImSpades() icons.IsIcon             { return newIcon("024-spades") }
func ImSpellCheck() icons.IsIcon         { return newIcon("275-spell-check") }
func ImSphere() icons.IsIcon             { return newIcon("202-sphere") }
func ImSpinner() icons.IsIcon            { return newIcon("123-spinner") }
func ImSpinner10() icons.IsIcon          { return newIcon("132-spinner10") }
func ImSpinner11() icons.IsIcon          { return newIcon("133-spinner11") }
func ImSpinner2() icons.IsIcon           { return newIcon("124-spinner2") }
func ImSpinner3() icons.IsIcon           { return newIcon("125-spinner3") }
func ImSpinner4() icons.IsIcon           { return newIcon("126-spinner4") }
func ImSpinner5() icons.IsIcon           { return newIcon("127-spinner5") }
func ImSpinner6() icons.IsIcon           { return newIcon("128-spinner6") }
func ImSpinner7() icons.IsIcon           { return newIcon("129-spinner7") }
func ImSpinner8() icons.IsIcon           { return newIcon("130-spinner8") }
func ImSpinner9() icons.IsIcon           { return newIcon("131-spinner9") }
func ImSpoonKnife() icons.IsIcon         { return newIcon("164-spoon-knife") }
func ImSpotify() icons.IsIcon            { return newIcon("405-spotify") }
func ImStack() icons.IsIcon              { return newIcon("047-stack") }
func ImStackoverflow() icons.IsIcon      { return newIcon("465-stackoverflow") }
func ImStarEmpty() icons.IsIcon          { return newIcon("216-star-empty") }
func ImStarFull() icons.IsIcon           { return newIcon("218-star-full") }
func ImStarHalf() icons.IsIcon           { return newIcon("217-star-half") }
func ImStatsBars() icons.IsIcon          { return newIcon("157-stats-bars") }
func ImStatsBars2() icons.IsIcon         { return newIcon("158-stats-bars2") }
func ImStatsDots() icons.IsIcon          { return newIcon("156-stats-dots") }
func ImSteam() icons.IsIcon              { return newIcon("429-steam") }
func ImSteam2() icons.IsIcon             { return newIcon("430-steam2") }
func ImStop() icons.IsIcon               { return newIcon("280-stop") }
func ImStop2() icons.IsIcon              { return newIcon("287-stop2") }
func ImStopwatch() icons.IsIcon          { return newIcon("083-stopwatch") }
func ImStrikethrough() icons.IsIcon      { return newIcon("358-strikethrough") }
func ImStumbleupon() icons.IsIcon        { return newIcon("463-stumbleupon") }
func ImStumbleupon2() icons.IsIcon       { return newIcon("464-stumbleupon2") }
func ImSubscript() icons.IsIcon          { return newIcon("363-subscript") }
func ImSubscript2() icons.IsIcon         { return newIcon("365-subscript2") }
func ImSun() icons.IsIcon                { return newIcon("213-sun") }
func ImSuperscript() icons.IsIcon        { return newIcon("362-superscript") }
func ImSuperscript2() icons.IsIcon       { return newIcon("364-superscript2") }
func ImSvg() icons.IsIcon                { return newIcon("490-svg") }
func ImSwitch() icons.IsIcon             { return newIcon("183-switch") }
func ImTab() icons.IsIcon                { return newIcon("326-tab") }
func ImTable() icons.IsIcon              { return newIcon("369-table") }
func ImTable2() icons.IsIcon             { return newIcon("370-table2") }
func ImTablet() icons.IsIcon             { return newIcon("091-tablet") }
func ImTarget() icons.IsIcon             { return newIcon("180-target") }
func ImTelegram() icons.IsIcon           { return newIcon("406-telegram") }
func ImTerminal() icons.IsIcon           { return newIcon("386-terminal") }
func ImTextColor() icons.IsIcon          { return newIcon("366-text-color") }
func ImTextHeight() icons.IsIcon         { return newIcon("352-text-height") }
func ImTextWidth() icons.IsIcon          { return newIcon("353-text-width") }
func ImTicket() icons.IsIcon             { return newIcon("058-ticket") }
func ImTongue() icons.IsIcon             { return newIcon("228-tongue") }
func ImTongue2() icons.IsIcon            { return newIcon("229-tongue2") }
func ImTree() icons.IsIcon               { return newIcon("189-tree") }
func ImTrello() icons.IsIcon             { return newIcon("436-trello") }
func ImTrophy() icons.IsIcon             { return newIcon("159-trophy") }
func ImTruck() icons.IsIcon              { return newIcon("177-truck") }
func ImTumblr() icons.IsIcon             { return newIcon("442-tumblr") }
func ImTumblr2() icons.IsIcon            { return newIcon("443-tumblr2") }
func ImTux() icons.IsIcon                { return newIcon("446-tux") }
func ImTv() icons.IsIcon                 { return newIcon("092-tv") }
func ImTwitch() icons.IsIcon             { return newIcon("416-twitch") }
func ImTwitter() icons.IsIcon            { return newIcon("407-twitter") }
func ImUnderline() icons.IsIcon          { return newIcon("356-underline") }
func ImUndo() icons.IsIcon               { return newIcon("102-undo") }
func ImUndo2() icons.IsIcon              { return newIcon("104-undo2") }
func ImUngroup() icons.IsIcon            { return newIcon("346-ungroup") }
func ImUnlocked() icons.IsIcon           { return newIcon("145-unlocked") }
func ImUpload() icons.IsIcon             { return newIcon("098-upload") }
func ImUpload2() icons.IsIcon            { return newIcon("199-upload2") }
func ImUpload3() icons.IsIcon            { return newIcon("201-upload3") }
func ImUser() icons.IsIcon               { return newIcon("114-user") }
func ImUserCheck() icons.IsIcon          { return newIcon("118-user-check") }
func ImUserMinus() icons.IsIcon          { return newIcon("117-user-minus") }
func ImUserPlus() icons.IsIcon           { return newIcon("116-user-plus") }
func ImUserTie() icons.IsIcon            { return newIcon("119-user-tie") }
func ImUsers() icons.IsIcon              { return newIcon("115-users") }
func ImVideoCamera() icons.IsIcon        { return newIcon("021-video-camera") }
func ImVimeo() icons.IsIcon              { return newIcon("417-vimeo") }
func ImVimeo2() icons.IsIcon             { return newIcon("418-vimeo2") }
func ImVine() icons.IsIcon               { return newIcon("408-vine") }
func ImVk() icons.IsIcon                 { return newIcon("409-vk") }
func ImVolumeDecrease() icons.IsIcon     { return newIcon("301-volume-decrease") }
func ImVolumeHigh() icons.IsIcon         { return newIcon("295-volume-high") }
func ImVolumeIncrease() icons.IsIcon     { return newIcon("300-volume-increase") }
func ImVolumeLow() icons.IsIcon          { return newIcon("297-volume-low") }
func ImVolumeMedium() icons.IsIcon       { return newIcon("296-volume-medium") }
func ImVolumeMute() icons.IsIcon         { return newIcon("298-volume-mute") }
func ImVolumeMute2() icons.IsIcon        { return newIcon("299-volume-mute2") }
func ImWarning() icons.IsIcon            { return newIcon("264-warning") }
func ImWhatsapp() icons.IsIcon           { return newIcon("404-whatsapp") }
func ImWikipedia() icons.IsIcon          { return newIcon("457-wikipedia") }
func ImWindows() icons.IsIcon            { return newIcon("450-windows") }
func ImWindows8() icons.IsIcon           { return newIcon("451-windows8") }
func ImWink() icons.IsIcon               { return newIcon("232-wink") }
func ImWink2() icons.IsIcon              { return newIcon("233-wink2") }
func ImWoman() icons.IsIcon              { return newIcon("222-woman") }
func ImWondering() icons.IsIcon          { return newIcon("252-wondering") }
func ImWondering2() icons.IsIcon         { return newIcon("253-wondering2") }
func ImWordpress() icons.IsIcon          { return newIcon("437-wordpress") }
func ImWrench() icons.IsIcon             { return newIcon("146-wrench") }
func ImXing() icons.IsIcon               { return newIcon("468-xing") }
func ImXing2() icons.IsIcon              { return newIcon("469-xing2") }
func ImYahoo() icons.IsIcon              { return newIcon("444-yahoo") }
func ImYahoo2() icons.IsIcon             { return newIcon("445-yahoo2") }
func ImYelp() icons.IsIcon               { return newIcon("472-yelp") }
func ImYoutube() icons.IsIcon            { return newIcon("414-youtube") }
func ImYoutube2() icons.IsIcon           { return newIcon("415-youtube2") }
func ImZoomIn() icons.IsIcon             { return newIcon("136-zoom-in") }
func ImZoomOut() icons.IsIcon            { return newIcon("137-zoom-out") }
