package gr

import "github.com/raitucarp/gomix/icons"

func GrAccessibility() icons.IsIcon          { return newIcon("accessibility") }
func GrAchievement() icons.IsIcon            { return newIcon("achievement") }
func GrAction() icons.IsIcon                 { return newIcon("action") }
func GrActions() icons.IsIcon                { return newIcon("actions") }
func GrAd() icons.IsIcon                     { return newIcon("ad") }
func GrAddCircle() icons.IsIcon              { return newIcon("add-circle") }
func GrAdd() icons.IsIcon                    { return newIcon("add") }
func GrAdobeCreativeCloud() icons.IsIcon     { return newIcon("adobe-creative-cloud") }
func GrAed() icons.IsIcon                    { return newIcon("aed") }
func GrAggregate() icons.IsIcon              { return newIcon("aggregate") }
func GrAidOption() icons.IsIcon              { return newIcon("aid-option") }
func GrAid() icons.IsIcon                    { return newIcon("aid") }
func GrAlarm() icons.IsIcon                  { return newIcon("alarm") }
func GrAlert() icons.IsIcon                  { return newIcon("alert") }
func GrAmazon() icons.IsIcon                 { return newIcon("amazon") }
func GrAmex() icons.IsIcon                   { return newIcon("amex") }
func GrAnalytics() icons.IsIcon              { return newIcon("analytics") }
func GrAnchor() icons.IsIcon                 { return newIcon("anchor") }
func GrAndroid() icons.IsIcon                { return newIcon("android") }
func GrAnnounce() icons.IsIcon               { return newIcon("announce") }
func GrAppleAppStore() icons.IsIcon          { return newIcon("apple-app-store") }
func GrAppleMusic() icons.IsIcon             { return newIcon("apple-music") }
func GrApplePodcasts() icons.IsIcon          { return newIcon("apple-podcasts") }
func GrApple() icons.IsIcon                  { return newIcon("apple") }
func GrAppsRounded() icons.IsIcon            { return newIcon("apps-rounded") }
func GrApps() icons.IsIcon                   { return newIcon("apps") }
func GrArchive() icons.IsIcon                { return newIcon("archive") }
func GrArchlinux() icons.IsIcon              { return newIcon("archlinux") }
func GrArticle() icons.IsIcon                { return newIcon("article") }
func GrAruba() icons.IsIcon                  { return newIcon("aruba") }
func GrAscend() icons.IsIcon                 { return newIcon("ascend") }
func GrAscending() icons.IsIcon              { return newIcon("ascending") }
func GrAssistListening() icons.IsIcon        { return newIcon("assist-listening") }
func GrAtm() icons.IsIcon                    { return newIcon("atm") }
func GrAttachment() icons.IsIcon             { return newIcon("attachment") }
func GrAttraction() icons.IsIcon             { return newIcon("attraction") }
func GrBaby() icons.IsIcon                   { return newIcon("baby") }
func GrBackTen() icons.IsIcon                { return newIcon("back-ten") }
func GrBarChart() icons.IsIcon               { return newIcon("bar-chart") }
func GrBar() icons.IsIcon                    { return newIcon("bar") }
func GrBasket() icons.IsIcon                 { return newIcon("basket") }
func GrBeacon() icons.IsIcon                 { return newIcon("beacon") }
func GrBike() icons.IsIcon                   { return newIcon("bike") }
func GrBitcoin() icons.IsIcon                { return newIcon("bitcoin") }
func GrBladesHorizontal() icons.IsIcon       { return newIcon("blades-horizontal") }
func GrBladesVertical() icons.IsIcon         { return newIcon("blades-vertical") }
func GrBlockQuote() icons.IsIcon             { return newIcon("block-quote") }
func GrBlog() icons.IsIcon                   { return newIcon("blog") }
func GrBluetooth() icons.IsIcon              { return newIcon("bluetooth") }
func GrBold() icons.IsIcon                   { return newIcon("bold") }
func GrBook() icons.IsIcon                   { return newIcon("book") }
func GrBookmark() icons.IsIcon               { return newIcon("bookmark") }
func GrBottomCorner() icons.IsIcon           { return newIcon("bottom-corner") }
func GrBraille() icons.IsIcon                { return newIcon("braille") }
func GrBriefcase() icons.IsIcon              { return newIcon("briefcase") }
func GrBrush() icons.IsIcon                  { return newIcon("brush") }
func GrBucket() icons.IsIcon                 { return newIcon("bucket") }
func GrBug() icons.IsIcon                    { return newIcon("bug") }
func GrBundle() icons.IsIcon                 { return newIcon("bundle") }
func GrBus() icons.IsIcon                    { return newIcon("bus") }
func GrBusinessService() icons.IsIcon        { return newIcon("business-service") }
func GrCafeteria() icons.IsIcon              { return newIcon("cafeteria") }
func GrCalculator() icons.IsIcon             { return newIcon("calculator") }
func GrCalendar() icons.IsIcon               { return newIcon("calendar") }
func GrCamera() icons.IsIcon                 { return newIcon("camera") }
func GrCapacity() icons.IsIcon               { return newIcon("capacity") }
func GrCar() icons.IsIcon                    { return newIcon("car") }
func GrCaretDownFill() icons.IsIcon          { return newIcon("caret-down-fill") }
func GrCaretDown() icons.IsIcon              { return newIcon("caret-down") }
func GrCaretLeftFill() icons.IsIcon          { return newIcon("caret-left-fill") }
func GrCaretNext() icons.IsIcon              { return newIcon("caret-next") }
func GrCaretPrevious() icons.IsIcon          { return newIcon("caret-previous") }
func GrCaretRightFill() icons.IsIcon         { return newIcon("caret-right-fill") }
func GrCaretUpFill() icons.IsIcon            { return newIcon("caret-up-fill") }
func GrCaretUp() icons.IsIcon                { return newIcon("caret-up") }
func GrCart() icons.IsIcon                   { return newIcon("cart") }
func GrCatalogOption() icons.IsIcon          { return newIcon("catalog-option") }
func GrCatalog() icons.IsIcon                { return newIcon("catalog") }
func GrCentos() icons.IsIcon                 { return newIcon("centos") }
func GrCertificate() icons.IsIcon            { return newIcon("certificate") }
func GrChannel() icons.IsIcon                { return newIcon("channel") }
func GrChapterAdd() icons.IsIcon             { return newIcon("chapter-add") }
func GrChapterNext() icons.IsIcon            { return newIcon("chapter-next") }
func GrChapterPrevious() icons.IsIcon        { return newIcon("chapter-previous") }
func GrChatOption() icons.IsIcon             { return newIcon("chat-option") }
func GrChat() icons.IsIcon                   { return newIcon("chat") }
func GrCheckboxSelected() icons.IsIcon       { return newIcon("checkbox-selected") }
func GrCheckbox() icons.IsIcon               { return newIcon("checkbox") }
func GrCheckmark() icons.IsIcon              { return newIcon("checkmark") }
func GrChrome() icons.IsIcon                 { return newIcon("chrome") }
func GrCircleAlert() icons.IsIcon            { return newIcon("circle-alert") }
func GrCircleInformation() icons.IsIcon      { return newIcon("circle-information") }
func GrCirclePlay() icons.IsIcon             { return newIcon("circle-play") }
func GrCircleQuestion() icons.IsIcon         { return newIcon("circle-question") }
func GrClearOption() icons.IsIcon            { return newIcon("clear-option") }
func GrClear() icons.IsIcon                  { return newIcon("clear") }
func GrCli() icons.IsIcon                    { return newIcon("cli") }
func GrClipboard() icons.IsIcon              { return newIcon("clipboard") }
func GrClock() icons.IsIcon                  { return newIcon("clock") }
func GrClone() icons.IsIcon                  { return newIcon("clone") }
func GrClose() icons.IsIcon                  { return newIcon("close") }
func GrClosedCaption() icons.IsIcon          { return newIcon("closed-caption") }
func GrCloudComputer() icons.IsIcon          { return newIcon("cloud-computer") }
func GrCloudDownload() icons.IsIcon          { return newIcon("cloud-download") }
func GrCloudSoftware() icons.IsIcon          { return newIcon("cloud-software") }
func GrCloudUpload() icons.IsIcon            { return newIcon("cloud-upload") }
func GrCloud() icons.IsIcon                  { return newIcon("cloud") }
func GrCloudlinux() icons.IsIcon             { return newIcon("cloudlinux") }
func GrCluster() icons.IsIcon                { return newIcon("cluster") }
func GrCoatCheck() icons.IsIcon              { return newIcon("coat-check") }
func GrCodeSandbox() icons.IsIcon            { return newIcon("code-sandbox") }
func GrCode() icons.IsIcon                   { return newIcon("code") }
func GrCodepen() icons.IsIcon                { return newIcon("codepen") }
func GrCoffee() icons.IsIcon                 { return newIcon("coffee") }
func GrColumns() icons.IsIcon                { return newIcon("columns") }
func GrCommand() icons.IsIcon                { return newIcon("command") }
func GrCompare() icons.IsIcon                { return newIcon("compare") }
func GrCompass() icons.IsIcon                { return newIcon("compass") }
func GrCompliance() icons.IsIcon             { return newIcon("compliance") }
func GrConfigure() icons.IsIcon              { return newIcon("configure") }
func GrConnect() icons.IsIcon                { return newIcon("connect") }
func GrConnectivity() icons.IsIcon           { return newIcon("connectivity") }
func GrConsole() icons.IsIcon                { return newIcon("console") }
func GrContactInfo() icons.IsIcon            { return newIcon("contact-info") }
func GrContact() icons.IsIcon                { return newIcon("contact") }
func GrContract() icons.IsIcon               { return newIcon("contract") }
func GrCopy() icons.IsIcon                   { return newIcon("copy") }
func GrCpu() icons.IsIcon                    { return newIcon("cpu") }
func GrCreativeCommons() icons.IsIcon        { return newIcon("creative-commons") }
func GrCreditCard() icons.IsIcon             { return newIcon("credit-card") }
func GrCss3() icons.IsIcon                   { return newIcon("css3") }
func GrCube() icons.IsIcon                   { return newIcon("cube") }
func GrCubes() icons.IsIcon                  { return newIcon("cubes") }
func GrCurrency() icons.IsIcon               { return newIcon("currency") }
func GrCursor() icons.IsIcon                 { return newIcon("cursor") }
func GrCut() icons.IsIcon                    { return newIcon("cut") }
func GrCycle() icons.IsIcon                  { return newIcon("cycle") }
func GrDashboard() icons.IsIcon              { return newIcon("dashboard") }
func GrDatabase() icons.IsIcon               { return newIcon("database") }
func GrDebian() icons.IsIcon                 { return newIcon("debian") }
func GrDeliver() icons.IsIcon                { return newIcon("deliver") }
func GrDeploy() icons.IsIcon                 { return newIcon("deploy") }
func GrDescend() icons.IsIcon                { return newIcon("descend") }
func GrDescending() icons.IsIcon             { return newIcon("descending") }
func GrDesktop() icons.IsIcon                { return newIcon("desktop") }
func GrDetach() icons.IsIcon                 { return newIcon("detach") }
func GrDevice() icons.IsIcon                 { return newIcon("device") }
func GrDiamond() icons.IsIcon                { return newIcon("diamond") }
func GrDirections() icons.IsIcon             { return newIcon("directions") }
func GrDisabledOutline() icons.IsIcon        { return newIcon("disabled-outline") }
func GrDisc() icons.IsIcon                   { return newIcon("disc") }
func GrDislikeFill() icons.IsIcon            { return newIcon("dislike-fill") }
func GrDislike() icons.IsIcon                { return newIcon("dislike") }
func GrDocker() icons.IsIcon                 { return newIcon("docker") }
func GrDocumentCloud() icons.IsIcon          { return newIcon("document-cloud") }
func GrDocumentConfig() icons.IsIcon         { return newIcon("document-config") }
func GrDocumentCsv() icons.IsIcon            { return newIcon("document-csv") }
func GrDocumentDownload() icons.IsIcon       { return newIcon("document-download") }
func GrDocumentExcel() icons.IsIcon          { return newIcon("document-excel") }
func GrDocumentImage() icons.IsIcon          { return newIcon("document-image") }
func GrDocumentLocked() icons.IsIcon         { return newIcon("document-locked") }
func GrDocumentMissing() icons.IsIcon        { return newIcon("document-missing") }
func GrDocumentNotes() icons.IsIcon          { return newIcon("document-notes") }
func GrDocumentOutlook() icons.IsIcon        { return newIcon("document-outlook") }
func GrDocumentPdf() icons.IsIcon            { return newIcon("document-pdf") }
func GrDocumentPerformance() icons.IsIcon    { return newIcon("document-performance") }
func GrDocumentPpt() icons.IsIcon            { return newIcon("document-ppt") }
func GrDocumentRtf() icons.IsIcon            { return newIcon("document-rtf") }
func GrDocumentSound() icons.IsIcon          { return newIcon("document-sound") }
func GrDocumentStore() icons.IsIcon          { return newIcon("document-store") }
func GrDocumentTest() icons.IsIcon           { return newIcon("document-test") }
func GrDocumentText() icons.IsIcon           { return newIcon("document-text") }
func GrDocumentThreat() icons.IsIcon         { return newIcon("document-threat") }
func GrDocumentTime() icons.IsIcon           { return newIcon("document-time") }
func GrDocumentTransfer() icons.IsIcon       { return newIcon("document-transfer") }
func GrDocumentTxt() icons.IsIcon            { return newIcon("document-txt") }
func GrDocumentUpdate() icons.IsIcon         { return newIcon("document-update") }
func GrDocumentUpload() icons.IsIcon         { return newIcon("document-upload") }
func GrDocumentUser() icons.IsIcon           { return newIcon("document-user") }
func GrDocumentVerified() icons.IsIcon       { return newIcon("document-verified") }
func GrDocumentVideo() icons.IsIcon          { return newIcon("document-video") }
func GrDocumentWindows() icons.IsIcon        { return newIcon("document-windows") }
func GrDocumentWord() icons.IsIcon           { return newIcon("document-word") }
func GrDocumentZip() icons.IsIcon            { return newIcon("document-zip") }
func GrDocument() icons.IsIcon               { return newIcon("document") }
func GrDomain() icons.IsIcon                 { return newIcon("domain") }
func GrDos() icons.IsIcon                    { return newIcon("dos") }
func GrDown() icons.IsIcon                   { return newIcon("down") }
func GrDownloadOption() icons.IsIcon         { return newIcon("download-option") }
func GrDownload() icons.IsIcon               { return newIcon("download") }
func GrDrag() icons.IsIcon                   { return newIcon("drag") }
func GrDrawer() icons.IsIcon                 { return newIcon("drawer") }
func GrDribbble() icons.IsIcon               { return newIcon("dribbble") }
func GrDriveCage() icons.IsIcon              { return newIcon("drive-cage") }
func GrDropbox() icons.IsIcon                { return newIcon("dropbox") }
func GrDuplicate() icons.IsIcon              { return newIcon("duplicate") }
func GrDxc() icons.IsIcon                    { return newIcon("dxc") }
func GrEbay() icons.IsIcon                   { return newIcon("ebay") }
func GrEdge() icons.IsIcon                   { return newIcon("edge") }
func GrEdit() icons.IsIcon                   { return newIcon("edit") }
func GrEject() icons.IsIcon                  { return newIcon("eject") }
func GrElevator() icons.IsIcon               { return newIcon("elevator") }
func GrEmergency() icons.IsIcon              { return newIcon("emergency") }
func GrEmoji() icons.IsIcon                  { return newIcon("emoji") }
func GrEmptyCircle() icons.IsIcon            { return newIcon("empty-circle") }
func GrErase() icons.IsIcon                  { return newIcon("erase") }
func GrEscalator() icons.IsIcon              { return newIcon("escalator") }
func GrExpand() icons.IsIcon                 { return newIcon("expand") }
func GrEzmeral() icons.IsIcon                { return newIcon("ezmeral") }
func GrFacebookOption() icons.IsIcon         { return newIcon("facebook-option") }
func GrFacebook() icons.IsIcon               { return newIcon("facebook") }
func GrFanOption() icons.IsIcon              { return newIcon("fan-option") }
func GrFan() icons.IsIcon                    { return newIcon("fan") }
func GrFastForward() icons.IsIcon            { return newIcon("fast-forward") }
func GrFavorite() icons.IsIcon               { return newIcon("favorite") }
func GrFedora() icons.IsIcon                 { return newIcon("fedora") }
func GrFigma() icons.IsIcon                  { return newIcon("figma") }
func GrFilter() icons.IsIcon                 { return newIcon("filter") }
func GrFingerPrint() icons.IsIcon            { return newIcon("finger-print") }
func GrFireball() icons.IsIcon               { return newIcon("fireball") }
func GrFirefox() icons.IsIcon                { return newIcon("firefox") }
func GrFirewall() icons.IsIcon               { return newIcon("firewall") }
func GrFlagFill() icons.IsIcon               { return newIcon("flag-fill") }
func GrFlag() icons.IsIcon                   { return newIcon("flag") }
func GrFlows() icons.IsIcon                  { return newIcon("flows") }
func GrFolderCycle() icons.IsIcon            { return newIcon("folder-cycle") }
func GrFolderOpen() icons.IsIcon             { return newIcon("folder-open") }
func GrFolder() icons.IsIcon                 { return newIcon("folder") }
func GrFormAdd() icons.IsIcon                { return newIcon("form-add") }
func GrFormAttachment() icons.IsIcon         { return newIcon("form-attachment") }
func GrFormCalendar() icons.IsIcon           { return newIcon("form-calendar") }
func GrFormCheckmark() icons.IsIcon          { return newIcon("form-checkmark") }
func GrFormClock() icons.IsIcon              { return newIcon("form-clock") }
func GrFormClose() icons.IsIcon              { return newIcon("form-close") }
func GrFormCut() icons.IsIcon                { return newIcon("form-cut") }
func GrFormDown() icons.IsIcon               { return newIcon("form-down") }
func GrFormEdit() icons.IsIcon               { return newIcon("form-edit") }
func GrFormFilter() icons.IsIcon             { return newIcon("form-filter") }
func GrFormFolder() icons.IsIcon             { return newIcon("form-folder") }
func GrFormLocation() icons.IsIcon           { return newIcon("form-location") }
func GrFormLock() icons.IsIcon               { return newIcon("form-lock") }
func GrFormNextLink() icons.IsIcon           { return newIcon("form-next-link") }
func GrFormNext() icons.IsIcon               { return newIcon("form-next") }
func GrFormPin() icons.IsIcon                { return newIcon("form-pin") }
func GrFormPreviousLink() icons.IsIcon       { return newIcon("form-previous-link") }
func GrFormPrevious() icons.IsIcon           { return newIcon("form-previous") }
func GrFormRefresh() icons.IsIcon            { return newIcon("form-refresh") }
func GrFormSchedule() icons.IsIcon           { return newIcon("form-schedule") }
func GrFormSearch() icons.IsIcon             { return newIcon("form-search") }
func GrFormSubtract() icons.IsIcon           { return newIcon("form-subtract") }
func GrFormTrash() icons.IsIcon              { return newIcon("form-trash") }
func GrFormUp() icons.IsIcon                 { return newIcon("form-up") }
func GrFormUpload() icons.IsIcon             { return newIcon("form-upload") }
func GrFormViewHide() icons.IsIcon           { return newIcon("form-view-hide") }
func GrFormView() icons.IsIcon               { return newIcon("form-view") }
func GrForwardTen() icons.IsIcon             { return newIcon("forward-ten") }
func GrFreebsd() icons.IsIcon                { return newIcon("freebsd") }
func GrGallery() icons.IsIcon                { return newIcon("gallery") }
func GrGamepad() icons.IsIcon                { return newIcon("gamepad") }
func GrGateway() icons.IsIcon                { return newIcon("gateway") }
func GrGatsbyjs() icons.IsIcon               { return newIcon("gatsbyjs") }
func GrGem() icons.IsIcon                    { return newIcon("gem") }
func GrGenai() icons.IsIcon                  { return newIcon("genai") }
func GrGenaifill() icons.IsIcon              { return newIcon("genaifill") }
func GrGift() icons.IsIcon                   { return newIcon("gift") }
func GrGithub() icons.IsIcon                 { return newIcon("github") }
func GrGlobe() icons.IsIcon                  { return newIcon("globe") }
func GrGolang() icons.IsIcon                 { return newIcon("golang") }
func GrGooglePay() icons.IsIcon              { return newIcon("google-pay") }
func GrGooglePlay() icons.IsIcon             { return newIcon("google-play") }
func GrGooglePlus() icons.IsIcon             { return newIcon("google-plus") }
func GrGoogleWallet() icons.IsIcon           { return newIcon("google-wallet") }
func GrGoogle() icons.IsIcon                 { return newIcon("google") }
func GrGraphQl() icons.IsIcon                { return newIcon("graph-ql") }
func GrGremlin() icons.IsIcon                { return newIcon("gremlin") }
func GrGrid() icons.IsIcon                   { return newIcon("grid") }
func GrGrommet() icons.IsIcon                { return newIcon("grommet") }
func GrGroup() icons.IsIcon                  { return newIcon("group") }
func GrGrow() icons.IsIcon                   { return newIcon("grow") }
func GrHadoop() icons.IsIcon                 { return newIcon("hadoop") }
func GrHalt() icons.IsIcon                   { return newIcon("halt") }
func GrHelpBook() icons.IsIcon               { return newIcon("help-book") }
func GrHelpOption() icons.IsIcon             { return newIcon("help-option") }
func GrHelp() icons.IsIcon                   { return newIcon("help") }
func GrHeroku() icons.IsIcon                 { return newIcon("heroku") }
func GrHide() icons.IsIcon                   { return newIcon("hide") }
func GrHistory() icons.IsIcon                { return newIcon("history") }
func GrHomeOption() icons.IsIcon             { return newIcon("home-option") }
func GrHomeRounded() icons.IsIcon            { return newIcon("home-rounded") }
func GrHome() icons.IsIcon                   { return newIcon("home") }
func GrHorton() icons.IsIcon                 { return newIcon("horton") }
func GrHostMaintenance() icons.IsIcon        { return newIcon("host-maintenance") }
func GrHost() icons.IsIcon                   { return newIcon("host") }
func GrHp() icons.IsIcon                     { return newIcon("hp") }
func GrHpeLabs() icons.IsIcon                { return newIcon("hpe-labs") }
func GrHpe() icons.IsIcon                    { return newIcon("hpe") }
func GrHpi() icons.IsIcon                    { return newIcon("hpi") }
func GrHtml5() icons.IsIcon                  { return newIcon("html5") }
func GrIceCream() icons.IsIcon               { return newIcon("ice-cream") }
func GrImage() icons.IsIcon                  { return newIcon("image") }
func GrImpact() icons.IsIcon                 { return newIcon("impact") }
func GrInProgress() icons.IsIcon             { return newIcon("in-progress") }
func GrInbox() icons.IsIcon                  { return newIcon("inbox") }
func GrIndicator() icons.IsIcon              { return newIcon("indicator") }
func GrInfo() icons.IsIcon                   { return newIcon("info") }
func GrInherit() icons.IsIcon                { return newIcon("inherit") }
func GrInsecure() icons.IsIcon               { return newIcon("insecure") }
func GrInspect() icons.IsIcon                { return newIcon("inspect") }
func GrInstagram() icons.IsIcon              { return newIcon("instagram") }
func GrInstallOption() icons.IsIcon          { return newIcon("install-option") }
func GrInstall() icons.IsIcon                { return newIcon("install") }
func GrIntegration() icons.IsIcon            { return newIcon("integration") }
func GrInternetExplorer() icons.IsIcon       { return newIcon("internet-explorer") }
func GrItalic() icons.IsIcon                 { return newIcon("italic") }
func GrIteration() icons.IsIcon              { return newIcon("iteration") }
func GrJava() icons.IsIcon                   { return newIcon("java") }
func GrJs() icons.IsIcon                     { return newIcon("js") }
func GrKey() icons.IsIcon                    { return newIcon("key") }
func GrKeyboard() icons.IsIcon               { return newIcon("keyboard") }
func GrKubernetes() icons.IsIcon             { return newIcon("kubernetes") }
func GrLanguage() icons.IsIcon               { return newIcon("language") }
func GrLastfm() icons.IsIcon                 { return newIcon("lastfm") }
func GrLaunch() icons.IsIcon                 { return newIcon("launch") }
func GrLayer() icons.IsIcon                  { return newIcon("layer") }
func GrLicense() icons.IsIcon                { return newIcon("license") }
func GrLikeFill() icons.IsIcon               { return newIcon("like-fill") }
func GrLike() icons.IsIcon                   { return newIcon("like") }
func GrLineChart() icons.IsIcon              { return newIcon("line-chart") }
func GrLinkBottom() icons.IsIcon             { return newIcon("link-bottom") }
func GrLinkDown() icons.IsIcon               { return newIcon("link-down") }
func GrLinkNext() icons.IsIcon               { return newIcon("link-next") }
func GrLinkPrevious() icons.IsIcon           { return newIcon("link-previous") }
func GrLinkTop() icons.IsIcon                { return newIcon("link-top") }
func GrLinkUp() icons.IsIcon                 { return newIcon("link-up") }
func GrLink() icons.IsIcon                   { return newIcon("link") }
func GrLinkedinOption() icons.IsIcon         { return newIcon("linkedin-option") }
func GrLinkedin() icons.IsIcon               { return newIcon("linkedin") }
func GrList() icons.IsIcon                   { return newIcon("list") }
func GrLocal() icons.IsIcon                  { return newIcon("local") }
func GrLocationPin() icons.IsIcon            { return newIcon("location-pin") }
func GrLocation() icons.IsIcon               { return newIcon("location") }
func GrLock() icons.IsIcon                   { return newIcon("lock") }
func GrLogin() icons.IsIcon                  { return newIcon("login") }
func GrLogout() icons.IsIcon                 { return newIcon("logout") }
func GrLounge() icons.IsIcon                 { return newIcon("lounge") }
func GrMagic() icons.IsIcon                  { return newIcon("magic") }
func GrMailOption() icons.IsIcon             { return newIcon("mail-option") }
func GrMail() icons.IsIcon                   { return newIcon("mail") }
func GrMandriva() icons.IsIcon               { return newIcon("mandriva") }
func GrManual() icons.IsIcon                 { return newIcon("manual") }
func GrMapLocation() icons.IsIcon            { return newIcon("map-location") }
func GrMap() icons.IsIcon                    { return newIcon("map") }
func GrMastercard() icons.IsIcon             { return newIcon("mastercard") }
func GrMedium() icons.IsIcon                 { return newIcon("medium") }
func GrMemory() icons.IsIcon                 { return newIcon("memory") }
func GrMenu() icons.IsIcon                   { return newIcon("menu") }
func GrMeta() icons.IsIcon                   { return newIcon("meta") }
func GrMicrofocus() icons.IsIcon             { return newIcon("microfocus") }
func GrMicrophone() icons.IsIcon             { return newIcon("microphone") }
func GrMoney() icons.IsIcon                  { return newIcon("money") }
func GrMonitor() icons.IsIcon                { return newIcon("monitor") }
func GrMonospace() icons.IsIcon              { return newIcon("monospace") }
func GrMoon() icons.IsIcon                   { return newIcon("moon") }
func GrMoreVertical() icons.IsIcon           { return newIcon("more-vertical") }
func GrMore() icons.IsIcon                   { return newIcon("more") }
func GrMouse() icons.IsIcon                  { return newIcon("mouse") }
func GrMultimedia() icons.IsIcon             { return newIcon("multimedia") }
func GrMultiple() icons.IsIcon               { return newIcon("multiple") }
func GrMusic() icons.IsIcon                  { return newIcon("music") }
func GrMysql() icons.IsIcon                  { return newIcon("mysql") }
func GrNavigate() icons.IsIcon               { return newIcon("navigate") }
func GrNetworkDrive() icons.IsIcon           { return newIcon("network-drive") }
func GrNetwork() icons.IsIcon                { return newIcon("network") }
func GrNewWindow() icons.IsIcon              { return newIcon("new-window") }
func GrNew() icons.IsIcon                    { return newIcon("new") }
func GrNext() icons.IsIcon                   { return newIcon("next") }
func GrNode() icons.IsIcon                   { return newIcon("node") }
func GrNodes() icons.IsIcon                  { return newIcon("nodes") }
func GrNorton() icons.IsIcon                 { return newIcon("norton") }
func GrNote() icons.IsIcon                   { return newIcon("note") }
func GrNotes() icons.IsIcon                  { return newIcon("notes") }
func GrNotification() icons.IsIcon           { return newIcon("notification") }
func GrNpm() icons.IsIcon                    { return newIcon("npm") }
func GrObjectGroup() icons.IsIcon            { return newIcon("object-group") }
func GrObjectUngroup() icons.IsIcon          { return newIcon("object-ungroup") }
func GrOfflineStorage() icons.IsIcon         { return newIcon("offline-storage") }
func GrOnedrive() icons.IsIcon               { return newIcon("onedrive") }
func GrOpera() icons.IsIcon                  { return newIcon("opera") }
func GrOptimize() icons.IsIcon               { return newIcon("optimize") }
func GrOracle() icons.IsIcon                 { return newIcon("oracle") }
func GrOrderedList() icons.IsIcon            { return newIcon("ordered-list") }
func GrOrganization() icons.IsIcon           { return newIcon("organization") }
func GrOverview() icons.IsIcon               { return newIcon("overview") }
func GrPackage() icons.IsIcon                { return newIcon("package") }
func GrPaint() icons.IsIcon                  { return newIcon("paint") }
func GrPan() icons.IsIcon                    { return newIcon("pan") }
func GrPauseFill() icons.IsIcon              { return newIcon("pause-fill") }
func GrPause() icons.IsIcon                  { return newIcon("pause") }
func GrPaypal() icons.IsIcon                 { return newIcon("paypal") }
func GrPerformance() icons.IsIcon            { return newIcon("performance") }
func GrPersonalComputer() icons.IsIcon       { return newIcon("personal-computer") }
func GrPhoneFlip() icons.IsIcon              { return newIcon("phone-flip") }
func GrPhoneHorizontal() icons.IsIcon        { return newIcon("phone-horizontal") }
func GrPhoneVertical() icons.IsIcon          { return newIcon("phone-vertical") }
func GrPhone() icons.IsIcon                  { return newIcon("phone") }
func GrPieChart() icons.IsIcon               { return newIcon("pie-chart") }
func GrPiedPiper() icons.IsIcon              { return newIcon("pied-piper") }
func GrPin() icons.IsIcon                    { return newIcon("pin") }
func GrPinterest() icons.IsIcon              { return newIcon("pinterest") }
func GrPlan() icons.IsIcon                   { return newIcon("plan") }
func GrPlayFill() icons.IsIcon               { return newIcon("play-fill") }
func GrPlay() icons.IsIcon                   { return newIcon("play") }
func GrPlug() icons.IsIcon                   { return newIcon("plug") }
func GrPocket() icons.IsIcon                 { return newIcon("pocket") }
func GrPowerCycle() icons.IsIcon             { return newIcon("power-cycle") }
func GrPowerForceShutdown() icons.IsIcon     { return newIcon("power-force-shutdown") }
func GrPowerReset() icons.IsIcon             { return newIcon("power-reset") }
func GrPowerShutdown() icons.IsIcon          { return newIcon("power-shutdown") }
func GrPower() icons.IsIcon                  { return newIcon("power") }
func GrPrevious() icons.IsIcon               { return newIcon("previous") }
func GrPrint() icons.IsIcon                  { return newIcon("print") }
func GrProductHunt() icons.IsIcon            { return newIcon("product-hunt") }
func GrProjects() icons.IsIcon               { return newIcon("projects") }
func GrQr() icons.IsIcon                     { return newIcon("qr") }
func GrRadialSelected() icons.IsIcon         { return newIcon("radial-selected") }
func GrRadial() icons.IsIcon                 { return newIcon("radial") }
func GrRaspberry() icons.IsIcon              { return newIcon("raspberry") }
func GrReactjs() icons.IsIcon                { return newIcon("reactjs") }
func GrReddit() icons.IsIcon                 { return newIcon("reddit") }
func GrRedhat() icons.IsIcon                 { return newIcon("redhat") }
func GrRedo() icons.IsIcon                   { return newIcon("redo") }
func GrRefresh() icons.IsIcon                { return newIcon("refresh") }
func GrResources() icons.IsIcon              { return newIcon("resources") }
func GrRestaurant() icons.IsIcon             { return newIcon("restaurant") }
func GrRestroomMen() icons.IsIcon            { return newIcon("restroom-men") }
func GrRestroomWomen() icons.IsIcon          { return newIcon("restroom-women") }
func GrRestroom() icons.IsIcon               { return newIcon("restroom") }
func GrResume() icons.IsIcon                 { return newIcon("resume") }
func GrReturn() icons.IsIcon                 { return newIcon("return") }
func GrRevert() icons.IsIcon                 { return newIcon("revert") }
func GrRewind() icons.IsIcon                 { return newIcon("rewind") }
func GrRisk() icons.IsIcon                   { return newIcon("risk") }
func GrRobot() icons.IsIcon                  { return newIcon("robot") }
func GrRotateLeft() icons.IsIcon             { return newIcon("rotate-left") }
func GrRotateRight() icons.IsIcon            { return newIcon("rotate-right") }
func GrRss() icons.IsIcon                    { return newIcon("rss") }
func GrRun() icons.IsIcon                    { return newIcon("run") }
func GrSafariOption() icons.IsIcon           { return newIcon("safari-option") }
func GrSamsungPay() icons.IsIcon             { return newIcon("samsung-pay") }
func GrSans() icons.IsIcon                   { return newIcon("sans") }
func GrSatellite() icons.IsIcon              { return newIcon("satellite") }
func GrSave() icons.IsIcon                   { return newIcon("save") }
func GrScan() icons.IsIcon                   { return newIcon("scan") }
func GrScheduleNew() icons.IsIcon            { return newIcon("schedule-new") }
func GrSchedulePlay() icons.IsIcon           { return newIcon("schedule-play") }
func GrSchedule() icons.IsIcon               { return newIcon("schedule") }
func GrSchedules() icons.IsIcon              { return newIcon("schedules") }
func GrSco() icons.IsIcon                    { return newIcon("sco") }
func GrScorecard() icons.IsIcon              { return newIcon("scorecard") }
func GrScript() icons.IsIcon                 { return newIcon("script") }
func GrSd() icons.IsIcon                     { return newIcon("sd") }
func GrSearchAdvanced() icons.IsIcon         { return newIcon("search-advanced") }
func GrSearch() icons.IsIcon                 { return newIcon("search") }
func GrSecure() icons.IsIcon                 { return newIcon("secure") }
func GrSelect() icons.IsIcon                 { return newIcon("select") }
func GrSelection() icons.IsIcon              { return newIcon("selection") }
func GrSemantics() icons.IsIcon              { return newIcon("semantics") }
func GrSend() icons.IsIcon                   { return newIcon("send") }
func GrServerCluster() icons.IsIcon          { return newIcon("server-cluster") }
func GrServer() icons.IsIcon                 { return newIcon("server") }
func GrServers() icons.IsIcon                { return newIcon("servers") }
func GrServicePlay() icons.IsIcon            { return newIcon("service-play") }
func GrServices() icons.IsIcon               { return newIcon("services") }
func GrSettingsOption() icons.IsIcon         { return newIcon("settings-option") }
func GrShareOption() icons.IsIcon            { return newIcon("share-option") }
func GrShareRounded() icons.IsIcon           { return newIcon("share-rounded") }
func GrShare() icons.IsIcon                  { return newIcon("share") }
func GrShieldSecurity() icons.IsIcon         { return newIcon("shield-security") }
func GrShield() icons.IsIcon                 { return newIcon("shield") }
func GrShift() icons.IsIcon                  { return newIcon("shift") }
func GrShop() icons.IsIcon                   { return newIcon("shop") }
func GrSidebar() icons.IsIcon                { return newIcon("sidebar") }
func GrSign() icons.IsIcon                   { return newIcon("sign") }
func GrSkype() icons.IsIcon                  { return newIcon("skype") }
func GrSlack() icons.IsIcon                  { return newIcon("slack") }
func GrSnapchat() icons.IsIcon               { return newIcon("snapchat") }
func GrSolaris() icons.IsIcon                { return newIcon("solaris") }
func GrSort() icons.IsIcon                   { return newIcon("sort") }
func GrSoundcloud() icons.IsIcon             { return newIcon("soundcloud") }
func GrSpa() icons.IsIcon                    { return newIcon("spa") }
func GrSpectrum() icons.IsIcon               { return newIcon("spectrum") }
func GrSplit() icons.IsIcon                  { return newIcon("split") }
func GrSplits() icons.IsIcon                 { return newIcon("splits") }
func GrSpotify() icons.IsIcon                { return newIcon("spotify") }
func GrSquare() icons.IsIcon                 { return newIcon("square") }
func GrStackOverflow() icons.IsIcon          { return newIcon("stack-overflow") }
func GrStakeholder() icons.IsIcon            { return newIcon("stakeholder") }
func GrStarHalf() icons.IsIcon               { return newIcon("star-half") }
func GrStarOutline() icons.IsIcon            { return newIcon("star-outline") }
func GrStar() icons.IsIcon                   { return newIcon("star") }
func GrStatusCriticalSmall() icons.IsIcon    { return newIcon("status-critical-small") }
func GrStatusCritical() icons.IsIcon         { return newIcon("status-critical") }
func GrStatusDisabledSmall() icons.IsIcon    { return newIcon("status-disabled-small") }
func GrStatusDisabled() icons.IsIcon         { return newIcon("status-disabled") }
func GrStatusGoodSmall() icons.IsIcon        { return newIcon("status-good-small") }
func GrStatusGood() icons.IsIcon             { return newIcon("status-good") }
func GrStatusInfoSmall() icons.IsIcon        { return newIcon("status-info-small") }
func GrStatusInfo() icons.IsIcon             { return newIcon("status-info") }
func GrStatusPlaceholderSmall() icons.IsIcon { return newIcon("status-placeholder-small") }
func GrStatusPlaceholder() icons.IsIcon      { return newIcon("status-placeholder") }
func GrStatusUnknownSmall() icons.IsIcon     { return newIcon("status-unknown-small") }
func GrStatusUnknown() icons.IsIcon          { return newIcon("status-unknown") }
func GrStatusWarningSmall() icons.IsIcon     { return newIcon("status-warning-small") }
func GrStatusWarning() icons.IsIcon          { return newIcon("status-warning") }
func GrStepsOption() icons.IsIcon            { return newIcon("steps-option") }
func GrSteps() icons.IsIcon                  { return newIcon("steps") }
func GrStopFill() icons.IsIcon               { return newIcon("stop-fill") }
func GrStop() icons.IsIcon                   { return newIcon("stop") }
func GrStorage() icons.IsIcon                { return newIcon("storage") }
func GrStreetView() icons.IsIcon             { return newIcon("street-view") }
func GrStrikeThrough() icons.IsIcon          { return newIcon("strike-through") }
func GrStripe() icons.IsIcon                 { return newIcon("stripe") }
func GrSubscript() icons.IsIcon              { return newIcon("subscript") }
func GrSubtractCircle() icons.IsIcon         { return newIcon("subtract-circle") }
func GrSubtract() icons.IsIcon               { return newIcon("subtract") }
func GrSun() icons.IsIcon                    { return newIcon("sun") }
func GrSuperscript() icons.IsIcon            { return newIcon("superscript") }
func GrSupport() icons.IsIcon                { return newIcon("support") }
func GrSuse() icons.IsIcon                   { return newIcon("suse") }
func GrSwift() icons.IsIcon                  { return newIcon("swift") }
func GrSwim() icons.IsIcon                   { return newIcon("swim") }
func GrSwitch() icons.IsIcon                 { return newIcon("switch") }
func GrSync() icons.IsIcon                   { return newIcon("sync") }
func GrSystem() icons.IsIcon                 { return newIcon("system") }
func GrTableAdd() icons.IsIcon               { return newIcon("table-add") }
func GrTable() icons.IsIcon                  { return newIcon("table") }
func GrTag() icons.IsIcon                    { return newIcon("tag") }
func GrTapeOption() icons.IsIcon             { return newIcon("tape-option") }
func GrTape() icons.IsIcon                   { return newIcon("tape") }
func GrTarget() icons.IsIcon                 { return newIcon("target") }
func GrTask() icons.IsIcon                   { return newIcon("task") }
func GrTasks() icons.IsIcon                  { return newIcon("tasks") }
func GrTechnology() icons.IsIcon             { return newIcon("technology") }
func GrTemplate() icons.IsIcon               { return newIcon("template") }
func GrTerminal() icons.IsIcon               { return newIcon("terminal") }
func GrTestDesktop() icons.IsIcon            { return newIcon("test-desktop") }
func GrTest() icons.IsIcon                   { return newIcon("test") }
func GrTextAlignCenter() icons.IsIcon        { return newIcon("text-align-center") }
func GrTextAlignFull() icons.IsIcon          { return newIcon("text-align-full") }
func GrTextAlignLeft() icons.IsIcon          { return newIcon("text-align-left") }
func GrTextAlignRight() icons.IsIcon         { return newIcon("text-align-right") }
func GrTextWrap() icons.IsIcon               { return newIcon("text-wrap") }
func GrThreads() icons.IsIcon                { return newIcon("threads") }
func GrThreats() icons.IsIcon                { return newIcon("threats") }
func GrThreeDEffects() icons.IsIcon          { return newIcon("three-d-effects") }
func GrThreeD() icons.IsIcon                 { return newIcon("three-d") }
func GrTicket() icons.IsIcon                 { return newIcon("ticket") }
func GrTiktok() icons.IsIcon                 { return newIcon("tiktok") }
func GrTime() icons.IsIcon                   { return newIcon("time") }
func GrTip() icons.IsIcon                    { return newIcon("tip") }
func GrToast() icons.IsIcon                  { return newIcon("toast") }
func GrTools() icons.IsIcon                  { return newIcon("tools") }
func GrTooltip() icons.IsIcon                { return newIcon("tooltip") }
func GrTopCorner() icons.IsIcon              { return newIcon("top-corner") }
func GrTrain() icons.IsIcon                  { return newIcon("train") }
func GrTransaction() icons.IsIcon            { return newIcon("transaction") }
func GrTrash() icons.IsIcon                  { return newIcon("trash") }
func GrTreeOption() icons.IsIcon             { return newIcon("tree-option") }
func GrTree() icons.IsIcon                   { return newIcon("tree") }
func GrTrigger() icons.IsIcon                { return newIcon("trigger") }
func GrTrophy() icons.IsIcon                 { return newIcon("trophy") }
func GrTroubleshoot() icons.IsIcon           { return newIcon("troubleshoot") }
func GrTty() icons.IsIcon                    { return newIcon("tty") }
func GrTumblr() icons.IsIcon                 { return newIcon("tumblr") }
func GrTurbolinux() icons.IsIcon             { return newIcon("turbolinux") }
func GrTwitch() icons.IsIcon                 { return newIcon("twitch") }
func GrTwitter() icons.IsIcon                { return newIcon("twitter") }
func GrUbuntu() icons.IsIcon                 { return newIcon("ubuntu") }
func GrUnderline() icons.IsIcon              { return newIcon("underline") }
func GrUndo() icons.IsIcon                   { return newIcon("undo") }
func GrUnlink() icons.IsIcon                 { return newIcon("unlink") }
func GrUnlock() icons.IsIcon                 { return newIcon("unlock") }
func GrUnorderedList() icons.IsIcon          { return newIcon("unordered-list") }
func GrUnsorted() icons.IsIcon               { return newIcon("unsorted") }
func GrUp() icons.IsIcon                     { return newIcon("up") }
func GrUpdate() icons.IsIcon                 { return newIcon("update") }
func GrUpgrade() icons.IsIcon                { return newIcon("upgrade") }
func GrUploadOption() icons.IsIcon           { return newIcon("upload-option") }
func GrUpload() icons.IsIcon                 { return newIcon("upload") }
func GrUsbKey() icons.IsIcon                 { return newIcon("usb-key") }
func GrUserAdd() icons.IsIcon                { return newIcon("user-add") }
func GrUserAdmin() icons.IsIcon              { return newIcon("user-admin") }
func GrUserExpert() icons.IsIcon             { return newIcon("user-expert") }
func GrUserFemale() icons.IsIcon             { return newIcon("user-female") }
func GrUserManager() icons.IsIcon            { return newIcon("user-manager") }
func GrUserNew() icons.IsIcon                { return newIcon("user-new") }
func GrUserPolice() icons.IsIcon             { return newIcon("user-police") }
func GrUserSettings() icons.IsIcon           { return newIcon("user-settings") }
func GrUserWorker() icons.IsIcon             { return newIcon("user-worker") }
func GrUser() icons.IsIcon                   { return newIcon("user") }
func GrValidate() icons.IsIcon               { return newIcon("validate") }
func GrVend() icons.IsIcon                   { return newIcon("vend") }
func GrVenmo() icons.IsIcon                  { return newIcon("venmo") }
func GrVideo() icons.IsIcon                  { return newIcon("video") }
func GrView() icons.IsIcon                   { return newIcon("view") }
func GrVimeo() icons.IsIcon                  { return newIcon("vimeo") }
func GrVirtualMachine() icons.IsIcon         { return newIcon("virtual-machine") }
func GrVirtualStorage() icons.IsIcon         { return newIcon("virtual-storage") }
func GrVisa() icons.IsIcon                   { return newIcon("visa") }
func GrVmMaintenance() icons.IsIcon          { return newIcon("vm-maintenance") }
func GrVmware() icons.IsIcon                 { return newIcon("vmware") }
func GrVolumeControl() icons.IsIcon          { return newIcon("volume-control") }
func GrVolumeLow() icons.IsIcon              { return newIcon("volume-low") }
func GrVolumeMute() icons.IsIcon             { return newIcon("volume-mute") }
func GrVolume() icons.IsIcon                 { return newIcon("volume") }
func GrVulnerability() icons.IsIcon          { return newIcon("vulnerability") }
func GrWaypoint() icons.IsIcon               { return newIcon("waypoint") }
func GrWebcam() icons.IsIcon                 { return newIcon("webcam") }
func GrWechat() icons.IsIcon                 { return newIcon("wechat") }
func GrWhatsapp() icons.IsIcon               { return newIcon("whatsapp") }
func GrWheelchairActive() icons.IsIcon       { return newIcon("wheelchair-active") }
func GrWheelchair() icons.IsIcon             { return newIcon("wheelchair") }
func GrWifiLow() icons.IsIcon                { return newIcon("wifi-low") }
func GrWifiMedium() icons.IsIcon             { return newIcon("wifi-medium") }
func GrWifiNone() icons.IsIcon               { return newIcon("wifi-none") }
func GrWifi() icons.IsIcon                   { return newIcon("wifi") }
func GrWindowsLegacy() icons.IsIcon          { return newIcon("windows-legacy") }
func GrWindows() icons.IsIcon                { return newIcon("windows") }
func GrWordpress() icons.IsIcon              { return newIcon("wordpress") }
func GrWorkshop() icons.IsIcon               { return newIcon("workshop") }
func GrX() icons.IsIcon                      { return newIcon("x") }
func GrXing() icons.IsIcon                   { return newIcon("xing") }
func GrYoga() icons.IsIcon                   { return newIcon("yoga") }
func GrYoutube() icons.IsIcon                { return newIcon("youtube") }
func GrZoomIn() icons.IsIcon                 { return newIcon("zoom-in") }
func GrZoomOut() icons.IsIcon                { return newIcon("zoom-out") }
func GrZoom() icons.IsIcon                   { return newIcon("zoom") }
