package fc

import "github.com/raitucarp/gomix/icons"

func FcAbout() icons.IsIcon                   { return newIcon("about") }
func FcAcceptDatabase() icons.IsIcon          { return newIcon("accept_database") }
func FcAddColumn() icons.IsIcon               { return newIcon("add_column") }
func FcAddDatabase() icons.IsIcon             { return newIcon("add_database") }
func FcAddImage() icons.IsIcon                { return newIcon("add_image") }
func FcAddRow() icons.IsIcon                  { return newIcon("add_row") }
func FcAddressBook() icons.IsIcon             { return newIcon("address_book") }
func FcAdvance() icons.IsIcon                 { return newIcon("advance") }
func FcAdvertising() icons.IsIcon             { return newIcon("advertising") }
func FcAlarmClock() icons.IsIcon              { return newIcon("alarm_clock") }
func FcAlphabeticalSortingAz() icons.IsIcon   { return newIcon("alphabetical_sorting_az") }
func FcAlphabeticalSortingZa() icons.IsIcon   { return newIcon("alphabetical_sorting_za") }
func FcAndroidOs() icons.IsIcon               { return newIcon("android_os") }
func FcAnswers() icons.IsIcon                 { return newIcon("answers") }
func FcApproval() icons.IsIcon                { return newIcon("approval") }
func FcApprove() icons.IsIcon                 { return newIcon("approve") }
func FcAreaChart() icons.IsIcon               { return newIcon("area_chart") }
func FcAssistant() icons.IsIcon               { return newIcon("assistant") }
func FcAudioFile() icons.IsIcon               { return newIcon("audio_file") }
func FcAutomatic() icons.IsIcon               { return newIcon("automatic") }
func FcAutomotive() icons.IsIcon              { return newIcon("automotive") }
func FcBadDecision() icons.IsIcon             { return newIcon("bad_decision") }
func FcBarChart() icons.IsIcon                { return newIcon("bar_chart") }
func FcBbc() icons.IsIcon                     { return newIcon("bbc") }
func FcBearish() icons.IsIcon                 { return newIcon("bearish") }
func FcBinoculars() icons.IsIcon              { return newIcon("binoculars") }
func FcBiohazard() icons.IsIcon               { return newIcon("biohazard") }
func FcBiomass() icons.IsIcon                 { return newIcon("biomass") }
func FcBiotech() icons.IsIcon                 { return newIcon("biotech") }
func FcBookmark() icons.IsIcon                { return newIcon("bookmark") }
func FcBriefcase() icons.IsIcon               { return newIcon("briefcase") }
func FcBrokenLink() icons.IsIcon              { return newIcon("broken_link") }
func FcBullish() icons.IsIcon                 { return newIcon("bullish") }
func FcBusinessContact() icons.IsIcon         { return newIcon("business_contact") }
func FcBusiness() icons.IsIcon                { return newIcon("business") }
func FcBusinessman() icons.IsIcon             { return newIcon("businessman") }
func FcBusinesswoman() icons.IsIcon           { return newIcon("businesswoman") }
func FcButtingIn() icons.IsIcon               { return newIcon("butting_in") }
func FcCableRelease() icons.IsIcon            { return newIcon("cable_release") }
func FcCalculator() icons.IsIcon              { return newIcon("calculator") }
func FcCalendar() icons.IsIcon                { return newIcon("calendar") }
func FcCallTransfer() icons.IsIcon            { return newIcon("call_transfer") }
func FcCallback() icons.IsIcon                { return newIcon("callback") }
func FcCamcorderPro() icons.IsIcon            { return newIcon("camcorder_pro") }
func FcCamcorder() icons.IsIcon               { return newIcon("camcorder") }
func FcCameraAddon() icons.IsIcon             { return newIcon("camera_addon") }
func FcCameraIdentification() icons.IsIcon    { return newIcon("camera_identification") }
func FcCamera() icons.IsIcon                  { return newIcon("camera") }
func FcCancel() icons.IsIcon                  { return newIcon("cancel") }
func FcCandleSticks() icons.IsIcon            { return newIcon("candle_sticks") }
func FcCapacitor() icons.IsIcon               { return newIcon("capacitor") }
func FcCdLogo() icons.IsIcon                  { return newIcon("cd_logo") }
func FcCellPhone() icons.IsIcon               { return newIcon("cell_phone") }
func FcChargeBattery() icons.IsIcon           { return newIcon("charge_battery") }
func FcCheckmark() icons.IsIcon               { return newIcon("checkmark") }
func FcCircuit() icons.IsIcon                 { return newIcon("circuit") }
func FcClapperboard() icons.IsIcon            { return newIcon("clapperboard") }
func FcClearFilters() icons.IsIcon            { return newIcon("clear_filters") }
func FcClock() icons.IsIcon                   { return newIcon("clock") }
func FcCloseUpMode() icons.IsIcon             { return newIcon("close_up_mode") }
func FcCloth() icons.IsIcon                   { return newIcon("cloth") }
func FcCollaboration() icons.IsIcon           { return newIcon("collaboration") }
func FcCollapse() icons.IsIcon                { return newIcon("collapse") }
func FcCollect() icons.IsIcon                 { return newIcon("collect") }
func FcComboChart() icons.IsIcon              { return newIcon("combo_chart") }
func FcCommandLine() icons.IsIcon             { return newIcon("command_line") }
func FcComments() icons.IsIcon                { return newIcon("comments") }
func FcCompactCamera() icons.IsIcon           { return newIcon("compact_camera") }
func FcConferenceCall() icons.IsIcon          { return newIcon("conference_call") }
func FcContacts() icons.IsIcon                { return newIcon("contacts") }
func FcCopyleft() icons.IsIcon                { return newIcon("copyleft") }
func FcCopyright() icons.IsIcon               { return newIcon("copyright") }
func FcCrystalOscillator() icons.IsIcon       { return newIcon("crystal_oscillator") }
func FcCurrencyExchange() icons.IsIcon        { return newIcon("currency_exchange") }
func FcCursor() icons.IsIcon                  { return newIcon("cursor") }
func FcCustomerSupport() icons.IsIcon         { return newIcon("customer_support") }
func FcDam() icons.IsIcon                     { return newIcon("dam") }
func FcDataBackup() icons.IsIcon              { return newIcon("data_backup") }
func FcDataConfiguration() icons.IsIcon       { return newIcon("data_configuration") }
func FcDataEncryption() icons.IsIcon          { return newIcon("data_encryption") }
func FcDataProtection() icons.IsIcon          { return newIcon("data_protection") }
func FcDataRecovery() icons.IsIcon            { return newIcon("data_recovery") }
func FcDataSheet() icons.IsIcon               { return newIcon("data_sheet") }
func FcDatabase() icons.IsIcon                { return newIcon("database") }
func FcDebian() icons.IsIcon                  { return newIcon("debian") }
func FcDebt() icons.IsIcon                    { return newIcon("debt") }
func FcDecision() icons.IsIcon                { return newIcon("decision") }
func FcDeleteColumn() icons.IsIcon            { return newIcon("delete_column") }
func FcDeleteDatabase() icons.IsIcon          { return newIcon("delete_database") }
func FcDeleteRow() icons.IsIcon               { return newIcon("delete_row") }
func FcDepartment() icons.IsIcon              { return newIcon("department") }
func FcDeployment() icons.IsIcon              { return newIcon("deployment") }
func FcDiploma1() icons.IsIcon                { return newIcon("diploma_1") }
func FcDiploma2() icons.IsIcon                { return newIcon("diploma_2") }
func FcDisapprove() icons.IsIcon              { return newIcon("disapprove") }
func FcDisclaimer() icons.IsIcon              { return newIcon("disclaimer") }
func FcDislike() icons.IsIcon                 { return newIcon("dislike") }
func FcDisplay() icons.IsIcon                 { return newIcon("display") }
func FcDoNotInhale() icons.IsIcon             { return newIcon("do_not_inhale") }
func FcDoNotInsert() icons.IsIcon             { return newIcon("do_not_insert") }
func FcDoNotMix() icons.IsIcon                { return newIcon("do_not_mix") }
func FcDocument() icons.IsIcon                { return newIcon("document") }
func FcDonate() icons.IsIcon                  { return newIcon("donate") }
func FcDoughnutChart() icons.IsIcon           { return newIcon("doughnut_chart") }
func FcDownLeft() icons.IsIcon                { return newIcon("down_left") }
func FcDownRight() icons.IsIcon               { return newIcon("down_right") }
func FcDown() icons.IsIcon                    { return newIcon("down") }
func FcDownload() icons.IsIcon                { return newIcon("download") }
func FcDribbble() icons.IsIcon                { return newIcon("dribbble") }
func FcDvdLogo() icons.IsIcon                 { return newIcon("dvd_logo") }
func FcEditImage() icons.IsIcon               { return newIcon("edit_image") }
func FcElectricalSensor() icons.IsIcon        { return newIcon("electrical_sensor") }
func FcElectricalThreshold() icons.IsIcon     { return newIcon("electrical_threshold") }
func FcElectricity() icons.IsIcon             { return newIcon("electricity") }
func FcElectroDevices() icons.IsIcon          { return newIcon("electro_devices") }
func FcElectronics() icons.IsIcon             { return newIcon("electronics") }
func FcEmptyBattery() icons.IsIcon            { return newIcon("empty_battery") }
func FcEmptyFilter() icons.IsIcon             { return newIcon("empty_filter") }
func FcEmptyTrash() icons.IsIcon              { return newIcon("empty_trash") }
func FcEndCall() icons.IsIcon                 { return newIcon("end_call") }
func FcEngineering() icons.IsIcon             { return newIcon("engineering") }
func FcEnteringHeavenAlive() icons.IsIcon     { return newIcon("entering_heaven_alive") }
func FcExpand() icons.IsIcon                  { return newIcon("expand") }
func FcExpired() icons.IsIcon                 { return newIcon("expired") }
func FcExport() icons.IsIcon                  { return newIcon("export") }
func FcExternal() icons.IsIcon                { return newIcon("external") }
func FcFactoryBreakdown() icons.IsIcon        { return newIcon("factory_breakdown") }
func FcFactory() icons.IsIcon                 { return newIcon("factory") }
func FcFaq() icons.IsIcon                     { return newIcon("faq") }
func FcFeedIn() icons.IsIcon                  { return newIcon("feed_in") }
func FcFeedback() icons.IsIcon                { return newIcon("feedback") }
func FcFile() icons.IsIcon                    { return newIcon("file") }
func FcFilingCabinet() icons.IsIcon           { return newIcon("filing_cabinet") }
func FcFilledFilter() icons.IsIcon            { return newIcon("filled_filter") }
func FcFilmReel() icons.IsIcon                { return newIcon("film_reel") }
func FcFilm() icons.IsIcon                    { return newIcon("film") }
func FcFinePrint() icons.IsIcon               { return newIcon("fine_print") }
func FcFlashAuto() icons.IsIcon               { return newIcon("flash_auto") }
func FcFlashOff() icons.IsIcon                { return newIcon("flash_off") }
func FcFlashOn() icons.IsIcon                 { return newIcon("flash_on") }
func FcFlowChart() icons.IsIcon               { return newIcon("flow_chart") }
func FcFolder() icons.IsIcon                  { return newIcon("folder") }
func FcFrame() icons.IsIcon                   { return newIcon("frame") }
func FcFullBattery() icons.IsIcon             { return newIcon("full_battery") }
func FcFullTrash() icons.IsIcon               { return newIcon("full_trash") }
func FcGallery() icons.IsIcon                 { return newIcon("gallery") }
func FcGenealogy() icons.IsIcon               { return newIcon("genealogy") }
func FcGenericSortingAsc() icons.IsIcon       { return newIcon("generic_sorting_asc") }
func FcGenericSortingDesc() icons.IsIcon      { return newIcon("generic_sorting_desc") }
func FcGlobe() icons.IsIcon                   { return newIcon("globe") }
func FcGoodDecision() icons.IsIcon            { return newIcon("good_decision") }
func FcGoogle() icons.IsIcon                  { return newIcon("google") }
func FcGraduationCap() icons.IsIcon           { return newIcon("graduation_cap") }
func FcGrid() icons.IsIcon                    { return newIcon("grid") }
func FcHeadset() icons.IsIcon                 { return newIcon("headset") }
func FcHeatMap() icons.IsIcon                 { return newIcon("heat_map") }
func FcHighBattery() icons.IsIcon             { return newIcon("high_battery") }
func FcHighPriority() icons.IsIcon            { return newIcon("high_priority") }
func FcHome() icons.IsIcon                    { return newIcon("home") }
func FcIcons8Cup() icons.IsIcon               { return newIcon("icons8_cup") }
func FcIdea() icons.IsIcon                    { return newIcon("idea") }
func FcImageFile() icons.IsIcon               { return newIcon("image_file") }
func FcImport() icons.IsIcon                  { return newIcon("import") }
func FcInTransit() icons.IsIcon               { return newIcon("in_transit") }
func FcInfo() icons.IsIcon                    { return newIcon("info") }
func FcInspection() icons.IsIcon              { return newIcon("inspection") }
func FcIntegratedWebcam() icons.IsIcon        { return newIcon("integrated_webcam") }
func FcInternal() icons.IsIcon                { return newIcon("internal") }
func FcInvite() icons.IsIcon                  { return newIcon("invite") }
func FcIpad() icons.IsIcon                    { return newIcon("ipad") }
func FcIphone() icons.IsIcon                  { return newIcon("iphone") }
func FcKey() icons.IsIcon                     { return newIcon("key") }
func FcKindle() icons.IsIcon                  { return newIcon("kindle") }
func FcLandscape() icons.IsIcon               { return newIcon("landscape") }
func FcLeave() icons.IsIcon                   { return newIcon("leave") }
func FcLeftDown() icons.IsIcon                { return newIcon("left_down") }
func FcLeftDown2() icons.IsIcon               { return newIcon("left_down2") }
func FcLeftUp() icons.IsIcon                  { return newIcon("left_up") }
func FcLeftUp2() icons.IsIcon                 { return newIcon("left_up2") }
func FcLeft() icons.IsIcon                    { return newIcon("left") }
func FcLibrary() icons.IsIcon                 { return newIcon("library") }
func FcLightAtTheEndOfTunnel() icons.IsIcon   { return newIcon("light_at_the_end_of_tunnel") }
func FcLikePlaceholder() icons.IsIcon         { return newIcon("like_placeholder") }
func FcLike() icons.IsIcon                    { return newIcon("like") }
func FcLineChart() icons.IsIcon               { return newIcon("line_chart") }
func FcLink() icons.IsIcon                    { return newIcon("link") }
func FcLinux() icons.IsIcon                   { return newIcon("linux") }
func FcList() icons.IsIcon                    { return newIcon("list") }
func FcLockLandscape() icons.IsIcon           { return newIcon("lock_landscape") }
func FcLockPortrait() icons.IsIcon            { return newIcon("lock_portrait") }
func FcLock() icons.IsIcon                    { return newIcon("lock") }
func FcLowBattery() icons.IsIcon              { return newIcon("low_battery") }
func FcLowPriority() icons.IsIcon             { return newIcon("low_priority") }
func FcMakeDecision() icons.IsIcon            { return newIcon("make_decision") }
func FcManager() icons.IsIcon                 { return newIcon("manager") }
func FcMediumPriority() icons.IsIcon          { return newIcon("medium_priority") }
func FcMenu() icons.IsIcon                    { return newIcon("menu") }
func FcMiddleBattery() icons.IsIcon           { return newIcon("middle_battery") }
func FcMindMap() icons.IsIcon                 { return newIcon("mind_map") }
func FcMinus() icons.IsIcon                   { return newIcon("minus") }
func FcMissedCall() icons.IsIcon              { return newIcon("missed_call") }
func FcMms() icons.IsIcon                     { return newIcon("mms") }
func FcMoneyTransfer() icons.IsIcon           { return newIcon("money_transfer") }
func FcMultipleCameras() icons.IsIcon         { return newIcon("multiple_cameras") }
func FcMultipleDevices() icons.IsIcon         { return newIcon("multiple_devices") }
func FcMultipleInputs() icons.IsIcon          { return newIcon("multiple_inputs") }
func FcMultipleSmartphones() icons.IsIcon     { return newIcon("multiple_smartphones") }
func FcMusic() icons.IsIcon                   { return newIcon("music") }
func FcNegativeDynamic() icons.IsIcon         { return newIcon("negative_dynamic") }
func FcNeutralDecision() icons.IsIcon         { return newIcon("neutral_decision") }
func FcNeutralTrading() icons.IsIcon          { return newIcon("neutral_trading") }
func FcNews() icons.IsIcon                    { return newIcon("news") }
func FcNext() icons.IsIcon                    { return newIcon("next") }
func FcNfcSign() icons.IsIcon                 { return newIcon("nfc_sign") }
func FcNightLandscape() icons.IsIcon          { return newIcon("night_landscape") }
func FcNightPortrait() icons.IsIcon           { return newIcon("night_portrait") }
func FcNoIdea() icons.IsIcon                  { return newIcon("no_idea") }
func FcNoVideo() icons.IsIcon                 { return newIcon("no_video") }
func FcNook() icons.IsIcon                    { return newIcon("nook") }
func FcNumericalSorting12() icons.IsIcon      { return newIcon("numerical_sorting_12") }
func FcNumericalSorting21() icons.IsIcon      { return newIcon("numerical_sorting_21") }
func FcOk() icons.IsIcon                      { return newIcon("ok") }
func FcOldTimeCamera() icons.IsIcon           { return newIcon("old_time_camera") }
func FcOnlineSupport() icons.IsIcon           { return newIcon("online_support") }
func FcOpenedFolder() icons.IsIcon            { return newIcon("opened_folder") }
func FcOrgUnit() icons.IsIcon                 { return newIcon("org_unit") }
func FcOrganization() icons.IsIcon            { return newIcon("organization") }
func FcOvertime() icons.IsIcon                { return newIcon("overtime") }
func FcPackage() icons.IsIcon                 { return newIcon("package") }
func FcPaid() icons.IsIcon                    { return newIcon("paid") }
func FcPanorama() icons.IsIcon                { return newIcon("panorama") }
func FcParallelTasks() icons.IsIcon           { return newIcon("parallel_tasks") }
func FcPhoneAndroid() icons.IsIcon            { return newIcon("phone_android") }
func FcPhone() icons.IsIcon                   { return newIcon("phone") }
func FcPhotoReel() icons.IsIcon               { return newIcon("photo_reel") }
func FcPicture() icons.IsIcon                 { return newIcon("picture") }
func FcPieChart() icons.IsIcon                { return newIcon("pie_chart") }
func FcPlanner() icons.IsIcon                 { return newIcon("planner") }
func FcPlus() icons.IsIcon                    { return newIcon("plus") }
func FcPodiumWithAudience() icons.IsIcon      { return newIcon("podium_with_audience") }
func FcPodiumWithSpeaker() icons.IsIcon       { return newIcon("podium_with_speaker") }
func FcPodiumWithoutSpeaker() icons.IsIcon    { return newIcon("podium_without_speaker") }
func FcPortraitMode() icons.IsIcon            { return newIcon("portrait_mode") }
func FcPositiveDynamic() icons.IsIcon         { return newIcon("positive_dynamic") }
func FcPrevious() icons.IsIcon                { return newIcon("previous") }
func FcPrint() icons.IsIcon                   { return newIcon("print") }
func FcPrivacy() icons.IsIcon                 { return newIcon("privacy") }
func FcProcess() icons.IsIcon                 { return newIcon("process") }
func FcPuzzle() icons.IsIcon                  { return newIcon("puzzle") }
func FcQuestions() icons.IsIcon               { return newIcon("questions") }
func FcRadarPlot() icons.IsIcon               { return newIcon("radar_plot") }
func FcRating() icons.IsIcon                  { return newIcon("rating") }
func FcRatings() icons.IsIcon                 { return newIcon("ratings") }
func FcReadingEbook() icons.IsIcon            { return newIcon("reading_ebook") }
func FcReading() icons.IsIcon                 { return newIcon("reading") }
func FcReddit() icons.IsIcon                  { return newIcon("reddit") }
func FcRedo() icons.IsIcon                    { return newIcon("redo") }
func FcRefresh() icons.IsIcon                 { return newIcon("refresh") }
func FcRegisteredTrademark() icons.IsIcon     { return newIcon("registered_trademark") }
func FcRemoveImage() icons.IsIcon             { return newIcon("remove_image") }
func FcReuse() icons.IsIcon                   { return newIcon("reuse") }
func FcRightDown() icons.IsIcon               { return newIcon("right_down") }
func FcRightDown2() icons.IsIcon              { return newIcon("right_down2") }
func FcRightUp() icons.IsIcon                 { return newIcon("right_up") }
func FcRightUp2() icons.IsIcon                { return newIcon("right_up2") }
func FcRight() icons.IsIcon                   { return newIcon("right") }
func FcRotateCamera() icons.IsIcon            { return newIcon("rotate_camera") }
func FcRotateToLandscape() icons.IsIcon       { return newIcon("rotate_to_landscape") }
func FcRotateToPortrait() icons.IsIcon        { return newIcon("rotate_to_portrait") }
func FcRuler() icons.IsIcon                   { return newIcon("ruler") }
func FcRules() icons.IsIcon                   { return newIcon("rules") }
func FcSafe() icons.IsIcon                    { return newIcon("safe") }
func FcSalesPerformance() icons.IsIcon        { return newIcon("sales_performance") }
func FcScatterPlot() icons.IsIcon             { return newIcon("scatter_plot") }
func FcSearch() icons.IsIcon                  { return newIcon("search") }
func FcSelfServiceKiosk() icons.IsIcon        { return newIcon("self_service_kiosk") }
func FcSelfie() icons.IsIcon                  { return newIcon("selfie") }
func FcSerialTasks() icons.IsIcon             { return newIcon("serial_tasks") }
func FcServiceMark() icons.IsIcon             { return newIcon("service_mark") }
func FcServices() icons.IsIcon                { return newIcon("services") }
func FcSettings() icons.IsIcon                { return newIcon("settings") }
func FcShare() icons.IsIcon                   { return newIcon("share") }
func FcShipped() icons.IsIcon                 { return newIcon("shipped") }
func FcShop() icons.IsIcon                    { return newIcon("shop") }
func FcSignature() icons.IsIcon               { return newIcon("signature") }
func FcSimCardChip() icons.IsIcon             { return newIcon("sim_card_chip") }
func FcSimCard() icons.IsIcon                 { return newIcon("sim_card") }
func FcSlrBackSide() icons.IsIcon             { return newIcon("slr_back_side") }
func FcSmartphoneTablet() icons.IsIcon        { return newIcon("smartphone_tablet") }
func FcSms() icons.IsIcon                     { return newIcon("sms") }
func FcSoundRecordingCopyright() icons.IsIcon { return newIcon("sound_recording_copyright") }
func FcSpeaker() icons.IsIcon                 { return newIcon("speaker") }
func FcSportsMode() icons.IsIcon              { return newIcon("sports_mode") }
func FcStackOfPhotos() icons.IsIcon           { return newIcon("stack_of_photos") }
func FcStart() icons.IsIcon                   { return newIcon("start") }
func FcStatistics() icons.IsIcon              { return newIcon("statistics") }
func FcSteam() icons.IsIcon                   { return newIcon("steam") }
func FcStumbleupon() icons.IsIcon             { return newIcon("stumbleupon") }
func FcSupport() icons.IsIcon                 { return newIcon("support") }
func FcSurvey() icons.IsIcon                  { return newIcon("survey") }
func FcSwitchCamera() icons.IsIcon            { return newIcon("switch_camera") }
func FcSynchronize() icons.IsIcon             { return newIcon("synchronize") }
func FcTabletAndroid() icons.IsIcon           { return newIcon("tablet_android") }
func FcTemplate() icons.IsIcon                { return newIcon("template") }
func FcTimeline() icons.IsIcon                { return newIcon("timeline") }
func FcTodoList() icons.IsIcon                { return newIcon("todo_list") }
func FcTouchscreenSmartphone() icons.IsIcon   { return newIcon("touchscreen_smartphone") }
func FcTrademark() icons.IsIcon               { return newIcon("trademark") }
func FcTreeStructure() icons.IsIcon           { return newIcon("tree_structure") }
func FcTwoSmartphones() icons.IsIcon          { return newIcon("two_smartphones") }
func FcUndo() icons.IsIcon                    { return newIcon("undo") }
func FcUnlock() icons.IsIcon                  { return newIcon("unlock") }
func FcUpLeft() icons.IsIcon                  { return newIcon("up_left") }
func FcUpRight() icons.IsIcon                 { return newIcon("up_right") }
func FcUp() icons.IsIcon                      { return newIcon("up") }
func FcUpload() icons.IsIcon                  { return newIcon("upload") }
func FcUsb() icons.IsIcon                     { return newIcon("usb") }
func FcVideoCall() icons.IsIcon               { return newIcon("video_call") }
func FcVideoFile() icons.IsIcon               { return newIcon("video_file") }
func FcVideoProjector() icons.IsIcon          { return newIcon("video_projector") }
func FcViewDetails() icons.IsIcon             { return newIcon("view_details") }
func FcVip() icons.IsIcon                     { return newIcon("vip") }
func FcVlc() icons.IsIcon                     { return newIcon("vlc") }
func FcVoicePresentation() icons.IsIcon       { return newIcon("voice_presentation") }
func FcVoicemail() icons.IsIcon               { return newIcon("voicemail") }
func FcWebcam() icons.IsIcon                  { return newIcon("webcam") }
func FcWiFiLogo() icons.IsIcon                { return newIcon("wi-fi_logo") }
func FcWikipedia() icons.IsIcon               { return newIcon("wikipedia") }
func FcWorkflow() icons.IsIcon                { return newIcon("workflow") }
