package sl

import "github.com/raitucarp/gomix/icons"

func SlActionRedo() icons.IsIcon        { return newIcon("action-redo") }
func SlActionUndo() icons.IsIcon        { return newIcon("action-undo") }
func SlAnchor() icons.IsIcon            { return newIcon("anchor") }
func SlArrowDownCircle() icons.IsIcon   { return newIcon("arrow-down-circle") }
func SlArrowDown() icons.IsIcon         { return newIcon("arrow-down") }
func SlArrowLeftCircle() icons.IsIcon   { return newIcon("arrow-left-circle") }
func SlArrowLeft() icons.IsIcon         { return newIcon("arrow-left") }
func SlArrowRightCircle() icons.IsIcon  { return newIcon("arrow-right-circle") }
func SlArrowRight() icons.IsIcon        { return newIcon("arrow-right") }
func SlArrowUpCircle() icons.IsIcon     { return newIcon("arrow-up-circle") }
func SlArrowUp() icons.IsIcon           { return newIcon("arrow-up") }
func SlBadge() icons.IsIcon             { return newIcon("badge") }
func SlBag() icons.IsIcon               { return newIcon("bag") }
func SlBan() icons.IsIcon               { return newIcon("ban") }
func SlBasketLoaded() icons.IsIcon      { return newIcon("basket-loaded") }
func SlBasket() icons.IsIcon            { return newIcon("basket") }
func SlBell() icons.IsIcon              { return newIcon("bell") }
func SlBookOpen() icons.IsIcon          { return newIcon("book-open") }
func SlBriefcase() icons.IsIcon         { return newIcon("briefcase") }
func SlBubble() icons.IsIcon            { return newIcon("bubble") }
func SlBubbles() icons.IsIcon           { return newIcon("bubbles") }
func SlBulb() icons.IsIcon              { return newIcon("bulb") }
func SlCalculator() icons.IsIcon        { return newIcon("calculator") }
func SlCalender() icons.IsIcon          { return newIcon("calender") }
func SlCallEnd() icons.IsIcon           { return newIcon("call-end") }
func SlCallIn() icons.IsIcon            { return newIcon("call-in") }
func SlCallOut() icons.IsIcon           { return newIcon("call-out") }
func SlCamera() icons.IsIcon            { return newIcon("camera") }
func SlCamrecorder() icons.IsIcon       { return newIcon("camrecorder") }
func SlChart() icons.IsIcon             { return newIcon("chart") }
func SlCheck() icons.IsIcon             { return newIcon("check") }
func SlChemistry() icons.IsIcon         { return newIcon("chemistry") }
func SlClock() icons.IsIcon             { return newIcon("clock") }
func SlClose() icons.IsIcon             { return newIcon("close") }
func SlCloudDownload() icons.IsIcon     { return newIcon("cloud-download") }
func SlCloudUpload() icons.IsIcon       { return newIcon("cloud-upload") }
func SlCompass() icons.IsIcon           { return newIcon("compass") }
func SlControlEnd() icons.IsIcon        { return newIcon("control-end") }
func SlControlForward() icons.IsIcon    { return newIcon("control-forward") }
func SlControlPause() icons.IsIcon      { return newIcon("control-pause") }
func SlControlPlay() icons.IsIcon       { return newIcon("control-play") }
func SlControlRewind() icons.IsIcon     { return newIcon("control-rewind") }
func SlControlStart() icons.IsIcon      { return newIcon("control-start") }
func SlCreditCard() icons.IsIcon        { return newIcon("credit-card") }
func SlCrop() icons.IsIcon              { return newIcon("crop") }
func SlCup() icons.IsIcon               { return newIcon("cup") }
func SlCursorMove() icons.IsIcon        { return newIcon("cursor-move") }
func SlCursor() icons.IsIcon            { return newIcon("cursor") }
func SlDiamond() icons.IsIcon           { return newIcon("diamond") }
func SlDirection() icons.IsIcon         { return newIcon("direction") }
func SlDirections() icons.IsIcon        { return newIcon("directions") }
func SlDisc() icons.IsIcon              { return newIcon("disc") }
func SlDislike() icons.IsIcon           { return newIcon("dislike") }
func SlDoc() icons.IsIcon               { return newIcon("doc") }
func SlDocs() icons.IsIcon              { return newIcon("docs") }
func SlDrawer() icons.IsIcon            { return newIcon("drawer") }
func SlDrop() icons.IsIcon              { return newIcon("drop") }
func SlEarphonesAlt() icons.IsIcon      { return newIcon("earphones-alt") }
func SlEarphones() icons.IsIcon         { return newIcon("earphones") }
func SlEmotsmile() icons.IsIcon         { return newIcon("emotsmile") }
func SlEnergy() icons.IsIcon            { return newIcon("energy") }
func SlEnvelopeOpen() icons.IsIcon      { return newIcon("envelope-open") }
func SlEnvolopeLetter() icons.IsIcon    { return newIcon("envolope-letter") }
func SlEnvolope() icons.IsIcon          { return newIcon("envolope") }
func SlEqualizer() icons.IsIcon         { return newIcon("equalizer") }
func SlEvent() icons.IsIcon             { return newIcon("event") }
func SlExclamation() icons.IsIcon       { return newIcon("exclamation") }
func SlEye() icons.IsIcon               { return newIcon("eye") }
func SlEyeglass() icons.IsIcon          { return newIcon("eyeglass") }
func SlFeed() icons.IsIcon              { return newIcon("feed") }
func SlFilm() icons.IsIcon              { return newIcon("film") }
func SlFire() icons.IsIcon              { return newIcon("fire") }
func SlFlag() icons.IsIcon              { return newIcon("flag") }
func SlFolderAlt() icons.IsIcon         { return newIcon("folder-alt") }
func SlFolder() icons.IsIcon            { return newIcon("folder") }
func SlFrame() icons.IsIcon             { return newIcon("frame") }
func SlGameController() icons.IsIcon    { return newIcon("game-controller") }
func SlGhost() icons.IsIcon             { return newIcon("ghost") }
func SlGlobeAlt() icons.IsIcon          { return newIcon("globe-alt") }
func SlGlobe() icons.IsIcon             { return newIcon("globe") }
func SlGraduation() icons.IsIcon        { return newIcon("graduation") }
func SlGraph() icons.IsIcon             { return newIcon("graph") }
func SlGrid() icons.IsIcon              { return newIcon("grid") }
func SlHandbag() icons.IsIcon           { return newIcon("handbag") }
func SlHeart() icons.IsIcon             { return newIcon("heart") }
func SlHome() icons.IsIcon              { return newIcon("home") }
func SlHourglass() icons.IsIcon         { return newIcon("hourglass") }
func SlInfo() icons.IsIcon              { return newIcon("info") }
func SlKey() icons.IsIcon               { return newIcon("key") }
func SlLayers() icons.IsIcon            { return newIcon("layers") }
func SlLike() icons.IsIcon              { return newIcon("like") }
func SlLink() icons.IsIcon              { return newIcon("link") }
func SlList() icons.IsIcon              { return newIcon("list") }
func SlLocationPin() icons.IsIcon       { return newIcon("location-pin") }
func SlLockOpen() icons.IsIcon          { return newIcon("lock-open") }
func SlLock() icons.IsIcon              { return newIcon("lock") }
func SlLogin() icons.IsIcon             { return newIcon("login") }
func SlLogout() icons.IsIcon            { return newIcon("logout") }
func SlLoop() icons.IsIcon              { return newIcon("loop") }
func SlMagicWand() icons.IsIcon         { return newIcon("magic-wand") }
func SlMagnet() icons.IsIcon            { return newIcon("magnet") }
func SlMagnifierAdd() icons.IsIcon      { return newIcon("magnifier-add") }
func SlMagnifierRemove() icons.IsIcon   { return newIcon("magnifier-remove") }
func SlMagnifier() icons.IsIcon         { return newIcon("magnifier") }
func SlMap() icons.IsIcon               { return newIcon("map") }
func SlMenu() icons.IsIcon              { return newIcon("menu") }
func SlMicrophone() icons.IsIcon        { return newIcon("microphone") }
func SlMinus() icons.IsIcon             { return newIcon("minus") }
func SlMouse() icons.IsIcon             { return newIcon("mouse") }
func SlMusicToneAlt() icons.IsIcon      { return newIcon("music-tone-alt") }
func SlMusicTone() icons.IsIcon         { return newIcon("music-tone") }
func SlMustache() icons.IsIcon          { return newIcon("mustache") }
func SlNote() icons.IsIcon              { return newIcon("note") }
func SlNotebook() icons.IsIcon          { return newIcon("notebook") }
func SlOptionsVertical() icons.IsIcon   { return newIcon("options-vertical") }
func SlOptions() icons.IsIcon           { return newIcon("options") }
func SlOrganization() icons.IsIcon      { return newIcon("organization") }
func SlPaperClip() icons.IsIcon         { return newIcon("paper-clip") }
func SlPaperPlane() icons.IsIcon        { return newIcon("paper-plane") }
func SlPaypal() icons.IsIcon            { return newIcon("paypal") }
func SlPencil() icons.IsIcon            { return newIcon("pencil") }
func SlPeople() icons.IsIcon            { return newIcon("people") }
func SlPhone() icons.IsIcon             { return newIcon("phone") }
func SlPicture() icons.IsIcon           { return newIcon("picture") }
func SlPieChart() icons.IsIcon          { return newIcon("pie-chart") }
func SlPin() icons.IsIcon               { return newIcon("pin") }
func SlPlane() icons.IsIcon             { return newIcon("plane") }
func SlPlaylist() icons.IsIcon          { return newIcon("playlist") }
func SlPlus() icons.IsIcon              { return newIcon("plus") }
func SlPower() icons.IsIcon             { return newIcon("power") }
func SlPresent() icons.IsIcon           { return newIcon("present") }
func SlPrinter() icons.IsIcon           { return newIcon("printer") }
func SlPuzzle() icons.IsIcon            { return newIcon("puzzle") }
func SlQuestion() icons.IsIcon          { return newIcon("question") }
func SlRefresh() icons.IsIcon           { return newIcon("refresh") }
func SlReload() icons.IsIcon            { return newIcon("reload") }
func SlRocket() icons.IsIcon            { return newIcon("rocket") }
func SlScreenDesktop() icons.IsIcon     { return newIcon("screen-desktop") }
func SlScreenSmartphone() icons.IsIcon  { return newIcon("screen-smartphone") }
func SlScreenTablet() icons.IsIcon      { return newIcon("screen-tablet") }
func SlSettings() icons.IsIcon          { return newIcon("settings") }
func SlShareAlt() icons.IsIcon          { return newIcon("share-alt") }
func SlShare() icons.IsIcon             { return newIcon("share") }
func SlShield() icons.IsIcon            { return newIcon("shield") }
func SlShuffle() icons.IsIcon           { return newIcon("shuffle") }
func SlSizeActual() icons.IsIcon        { return newIcon("size-actual") }
func SlSizeFullscreen() icons.IsIcon    { return newIcon("size-fullscreen") }
func SlSocialBehance() icons.IsIcon     { return newIcon("social-behance") }
func SlSocialDribbble() icons.IsIcon    { return newIcon("social-dribbble") }
func SlSocialDropbox() icons.IsIcon     { return newIcon("social-dropbox") }
func SlSocialFacebook() icons.IsIcon    { return newIcon("social-facebook") }
func SlSocialFoursqare() icons.IsIcon   { return newIcon("social-foursqare") }
func SlSocialGithub() icons.IsIcon      { return newIcon("social-github") }
func SlSocialGoogle() icons.IsIcon      { return newIcon("social-google") }
func SlSocialInstagram() icons.IsIcon   { return newIcon("social-instagram") }
func SlSocialLinkedin() icons.IsIcon    { return newIcon("social-linkedin") }
func SlSocialPintarest() icons.IsIcon   { return newIcon("social-pintarest") }
func SlSocialReddit() icons.IsIcon      { return newIcon("social-reddit") }
func SlSocialSkype() icons.IsIcon       { return newIcon("social-skype") }
func SlSocialSoundcloud() icons.IsIcon  { return newIcon("social-soundcloud") }
func SlSocialSpotify() icons.IsIcon     { return newIcon("social-spotify") }
func SlSocialSteam() icons.IsIcon       { return newIcon("social-steam") }
func SlSocialStumbleupon() icons.IsIcon { return newIcon("social-stumbleupon") }
func SlSocialTumblr() icons.IsIcon      { return newIcon("social-tumblr") }
func SlSocialTwitter() icons.IsIcon     { return newIcon("social-twitter") }
func SlSocialVkontakte() icons.IsIcon   { return newIcon("social-vkontakte") }
func SlSocialYoutube() icons.IsIcon     { return newIcon("social-youtube") }
func SlSpeech() icons.IsIcon            { return newIcon("speech") }
func SlSpeedometer() icons.IsIcon       { return newIcon("speedometer") }
func SlStar() icons.IsIcon              { return newIcon("star") }
func SlSupport() icons.IsIcon           { return newIcon("support") }
func SlSymbleFemale() icons.IsIcon      { return newIcon("symble-female") }
func SlSymbolMale() icons.IsIcon        { return newIcon("symbol-male") }
func SlTag() icons.IsIcon               { return newIcon("tag") }
func SlTarget() icons.IsIcon            { return newIcon("target") }
func SlTrash() icons.IsIcon             { return newIcon("trash") }
func SlTrophy() icons.IsIcon            { return newIcon("trophy") }
func SlUmbrella() icons.IsIcon          { return newIcon("umbrella") }
func SlUserFemale() icons.IsIcon        { return newIcon("user-female") }
func SlUserFollow() icons.IsIcon        { return newIcon("user-follow") }
func SlUserFollowing() icons.IsIcon     { return newIcon("user-following") }
func SlUserUnfollow() icons.IsIcon      { return newIcon("user-unfollow") }
func SlUser() icons.IsIcon              { return newIcon("user") }
func SlVector() icons.IsIcon            { return newIcon("vector") }
func SlVolume1() icons.IsIcon           { return newIcon("volume-1") }
func SlVolume2() icons.IsIcon           { return newIcon("volume-2") }
func SlVolumeOff() icons.IsIcon         { return newIcon("volume-off") }
func SlWallet() icons.IsIcon            { return newIcon("wallet") }
func SlWrench() icons.IsIcon            { return newIcon("wrench") }
