package ti

import "github.com/raitucarp/gomix/icons"

func TiAdjustBrightness() icons.IsIcon          { return newIcon("adjust-brightness") }
func TiAdjustContrast() icons.IsIcon            { return newIcon("adjust-contrast") }
func TiAnchorOutline() icons.IsIcon             { return newIcon("anchor-outline") }
func TiAnchor() icons.IsIcon                    { return newIcon("anchor") }
func TiArchive() icons.IsIcon                   { return newIcon("archive") }
func TiArrowBackOutline() icons.IsIcon          { return newIcon("arrow-back-outline") }
func TiArrowBack() icons.IsIcon                 { return newIcon("arrow-back") }
func TiArrowDownOutline() icons.IsIcon          { return newIcon("arrow-down-outline") }
func TiArrowDownThick() icons.IsIcon            { return newIcon("arrow-down-thick") }
func TiArrowDown() icons.IsIcon                 { return newIcon("arrow-down") }
func TiArrowForwardOutline() icons.IsIcon       { return newIcon("arrow-forward-outline") }
func TiArrowForward() icons.IsIcon              { return newIcon("arrow-forward") }
func TiArrowLeftOutline() icons.IsIcon          { return newIcon("arrow-left-outline") }
func TiArrowLeftThick() icons.IsIcon            { return newIcon("arrow-left-thick") }
func TiArrowLeft() icons.IsIcon                 { return newIcon("arrow-left") }
func TiArrowLoopOutline() icons.IsIcon          { return newIcon("arrow-loop-outline") }
func TiArrowLoop() icons.IsIcon                 { return newIcon("arrow-loop") }
func TiArrowMaximiseOutline() icons.IsIcon      { return newIcon("arrow-maximise-outline") }
func TiArrowMaximise() icons.IsIcon             { return newIcon("arrow-maximise") }
func TiArrowMinimiseOutline() icons.IsIcon      { return newIcon("arrow-minimise-outline") }
func TiArrowMinimise() icons.IsIcon             { return newIcon("arrow-minimise") }
func TiArrowMoveOutline() icons.IsIcon          { return newIcon("arrow-move-outline") }
func TiArrowMove() icons.IsIcon                 { return newIcon("arrow-move") }
func TiArrowRepeatOutline() icons.IsIcon        { return newIcon("arrow-repeat-outline") }
func TiArrowRepeat() icons.IsIcon               { return newIcon("arrow-repeat") }
func TiArrowRightOutline() icons.IsIcon         { return newIcon("arrow-right-outline") }
func TiArrowRightThick() icons.IsIcon           { return newIcon("arrow-right-thick") }
func TiArrowRight() icons.IsIcon                { return newIcon("arrow-right") }
func TiArrowShuffle() icons.IsIcon              { return newIcon("arrow-shuffle") }
func TiArrowSortedDown() icons.IsIcon           { return newIcon("arrow-sorted-down") }
func TiArrowSortedUp() icons.IsIcon             { return newIcon("arrow-sorted-up") }
func TiArrowSyncOutline() icons.IsIcon          { return newIcon("arrow-sync-outline") }
func TiArrowSync() icons.IsIcon                 { return newIcon("arrow-sync") }
func TiArrowUnsorted() icons.IsIcon             { return newIcon("arrow-unsorted") }
func TiArrowUpOutline() icons.IsIcon            { return newIcon("arrow-up-outline") }
func TiArrowUpThick() icons.IsIcon              { return newIcon("arrow-up-thick") }
func TiArrowUp() icons.IsIcon                   { return newIcon("arrow-up") }
func TiAt() icons.IsIcon                        { return newIcon("at") }
func TiAttachmentOutline() icons.IsIcon         { return newIcon("attachment-outline") }
func TiAttachment() icons.IsIcon                { return newIcon("attachment") }
func TiBackspaceOutline() icons.IsIcon          { return newIcon("backspace-outline") }
func TiBackspace() icons.IsIcon                 { return newIcon("backspace") }
func TiBatteryCharge() icons.IsIcon             { return newIcon("battery-charge") }
func TiBatteryFull() icons.IsIcon               { return newIcon("battery-full") }
func TiBatteryHigh() icons.IsIcon               { return newIcon("battery-high") }
func TiBatteryLow() icons.IsIcon                { return newIcon("battery-low") }
func TiBatteryMid() icons.IsIcon                { return newIcon("battery-mid") }
func TiBeaker() icons.IsIcon                    { return newIcon("beaker") }
func TiBeer() icons.IsIcon                      { return newIcon("beer") }
func TiBell() icons.IsIcon                      { return newIcon("bell") }
func TiBook() icons.IsIcon                      { return newIcon("book") }
func TiBookmark() icons.IsIcon                  { return newIcon("bookmark") }
func TiBriefcase() icons.IsIcon                 { return newIcon("briefcase") }
func TiBrush() icons.IsIcon                     { return newIcon("brush") }
func TiBusinessCard() icons.IsIcon              { return newIcon("business-card") }
func TiCalculator() icons.IsIcon                { return newIcon("calculator") }
func TiCalendarOutline() icons.IsIcon           { return newIcon("calendar-outline") }
func TiCalendar() icons.IsIcon                  { return newIcon("calendar") }
func TiCameraOutline() icons.IsIcon             { return newIcon("camera-outline") }
func TiCamera() icons.IsIcon                    { return newIcon("camera") }
func TiCancelOutline() icons.IsIcon             { return newIcon("cancel-outline") }
func TiCancel() icons.IsIcon                    { return newIcon("cancel") }
func TiChartAreaOutline() icons.IsIcon          { return newIcon("chart-area-outline") }
func TiChartArea() icons.IsIcon                 { return newIcon("chart-area") }
func TiChartBarOutline() icons.IsIcon           { return newIcon("chart-bar-outline") }
func TiChartBar() icons.IsIcon                  { return newIcon("chart-bar") }
func TiChartLineOutline() icons.IsIcon          { return newIcon("chart-line-outline") }
func TiChartLine() icons.IsIcon                 { return newIcon("chart-line") }
func TiChartPieOutline() icons.IsIcon           { return newIcon("chart-pie-outline") }
func TiChartPie() icons.IsIcon                  { return newIcon("chart-pie") }
func TiChevronLeftOutline() icons.IsIcon        { return newIcon("chevron-left-outline") }
func TiChevronLeft() icons.IsIcon               { return newIcon("chevron-left") }
func TiChevronRightOutline() icons.IsIcon       { return newIcon("chevron-right-outline") }
func TiChevronRight() icons.IsIcon              { return newIcon("chevron-right") }
func TiClipboard() icons.IsIcon                 { return newIcon("clipboard") }
func TiCloudStorageOutline() icons.IsIcon       { return newIcon("cloud-storage-outline") }
func TiCloudStorage() icons.IsIcon              { return newIcon("cloud-storage") }
func TiCodeOutline() icons.IsIcon               { return newIcon("code-outline") }
func TiCode() icons.IsIcon                      { return newIcon("code") }
func TiCoffee() icons.IsIcon                    { return newIcon("coffee") }
func TiCogOutline() icons.IsIcon                { return newIcon("cog-outline") }
func TiCog() icons.IsIcon                       { return newIcon("cog") }
func TiCompass() icons.IsIcon                   { return newIcon("compass") }
func TiContacts() icons.IsIcon                  { return newIcon("contacts") }
func TiCreditCard() icons.IsIcon                { return newIcon("credit-card") }
func TiCss3() icons.IsIcon                      { return newIcon("css3") }
func TiDatabase() icons.IsIcon                  { return newIcon("database") }
func TiDeleteOutline() icons.IsIcon             { return newIcon("delete-outline") }
func TiDelete() icons.IsIcon                    { return newIcon("delete") }
func TiDeviceDesktop() icons.IsIcon             { return newIcon("device-desktop") }
func TiDeviceLaptop() icons.IsIcon              { return newIcon("device-laptop") }
func TiDevicePhone() icons.IsIcon               { return newIcon("device-phone") }
func TiDeviceTablet() icons.IsIcon              { return newIcon("device-tablet") }
func TiDirections() icons.IsIcon                { return newIcon("directions") }
func TiDivideOutline() icons.IsIcon             { return newIcon("divide-outline") }
func TiDivide() icons.IsIcon                    { return newIcon("divide") }
func TiDocumentAdd() icons.IsIcon               { return newIcon("document-add") }
func TiDocumentDelete() icons.IsIcon            { return newIcon("document-delete") }
func TiDocumentText() icons.IsIcon              { return newIcon("document-text") }
func TiDocument() icons.IsIcon                  { return newIcon("document") }
func TiDownloadOutline() icons.IsIcon           { return newIcon("download-outline") }
func TiDownload() icons.IsIcon                  { return newIcon("download") }
func TiDropbox() icons.IsIcon                   { return newIcon("dropbox") }
func TiEdit() icons.IsIcon                      { return newIcon("edit") }
func TiEjectOutline() icons.IsIcon              { return newIcon("eject-outline") }
func TiEject() icons.IsIcon                     { return newIcon("eject") }
func TiEqualsOutline() icons.IsIcon             { return newIcon("equals-outline") }
func TiEquals() icons.IsIcon                    { return newIcon("equals") }
func TiExportOutline() icons.IsIcon             { return newIcon("export-outline") }
func TiExport() icons.IsIcon                    { return newIcon("export") }
func TiEyeOutline() icons.IsIcon                { return newIcon("eye-outline") }
func TiEye() icons.IsIcon                       { return newIcon("eye") }
func TiFeather() icons.IsIcon                   { return newIcon("feather") }
func TiFilm() icons.IsIcon                      { return newIcon("film") }
func TiFilter() icons.IsIcon                    { return newIcon("filter") }
func TiFlagOutline() icons.IsIcon               { return newIcon("flag-outline") }
func TiFlag() icons.IsIcon                      { return newIcon("flag") }
func TiFlashOutline() icons.IsIcon              { return newIcon("flash-outline") }
func TiFlash() icons.IsIcon                     { return newIcon("flash") }
func TiFlowChildren() icons.IsIcon              { return newIcon("flow-children") }
func TiFlowMerge() icons.IsIcon                 { return newIcon("flow-merge") }
func TiFlowParallel() icons.IsIcon              { return newIcon("flow-parallel") }
func TiFlowSwitch() icons.IsIcon                { return newIcon("flow-switch") }
func TiFolderAdd() icons.IsIcon                 { return newIcon("folder-add") }
func TiFolderDelete() icons.IsIcon              { return newIcon("folder-delete") }
func TiFolderOpen() icons.IsIcon                { return newIcon("folder-open") }
func TiFolder() icons.IsIcon                    { return newIcon("folder") }
func TiGift() icons.IsIcon                      { return newIcon("gift") }
func TiGlobeOutline() icons.IsIcon              { return newIcon("globe-outline") }
func TiGlobe() icons.IsIcon                     { return newIcon("globe") }
func TiGroupOutline() icons.IsIcon              { return newIcon("group-outline") }
func TiGroup() icons.IsIcon                     { return newIcon("group") }
func TiHeadphones() icons.IsIcon                { return newIcon("headphones") }
func TiHeartFullOutline() icons.IsIcon          { return newIcon("heart-full-outline") }
func TiHeartHalfOutline() icons.IsIcon          { return newIcon("heart-half-outline") }
func TiHeartOutline() icons.IsIcon              { return newIcon("heart-outline") }
func TiHeart() icons.IsIcon                     { return newIcon("heart") }
func TiHomeOutline() icons.IsIcon               { return newIcon("home-outline") }
func TiHome() icons.IsIcon                      { return newIcon("home") }
func TiHtml5() icons.IsIcon                     { return newIcon("html5") }
func TiImageOutline() icons.IsIcon              { return newIcon("image-outline") }
func TiImage() icons.IsIcon                     { return newIcon("image") }
func TiInfinityOutline() icons.IsIcon           { return newIcon("infinity-outline") }
func TiInfinity() icons.IsIcon                  { return newIcon("infinity") }
func TiInfoLargeOutline() icons.IsIcon          { return newIcon("info-large-outline") }
func TiInfoLarge() icons.IsIcon                 { return newIcon("info-large") }
func TiInfoOutline() icons.IsIcon               { return newIcon("info-outline") }
func TiInfo() icons.IsIcon                      { return newIcon("info") }
func TiInputCheckedOutline() icons.IsIcon       { return newIcon("input-checked-outline") }
func TiInputChecked() icons.IsIcon              { return newIcon("input-checked") }
func TiKeyOutline() icons.IsIcon                { return newIcon("key-outline") }
func TiKey() icons.IsIcon                       { return newIcon("key") }
func TiKeyboard() icons.IsIcon                  { return newIcon("keyboard") }
func TiLeaf() icons.IsIcon                      { return newIcon("leaf") }
func TiLightbulb() icons.IsIcon                 { return newIcon("lightbulb") }
func TiLinkOutline() icons.IsIcon               { return newIcon("link-outline") }
func TiLink() icons.IsIcon                      { return newIcon("link") }
func TiLocationArrowOutline() icons.IsIcon      { return newIcon("location-arrow-outline") }
func TiLocationArrow() icons.IsIcon             { return newIcon("location-arrow") }
func TiLocationOutline() icons.IsIcon           { return newIcon("location-outline") }
func TiLocation() icons.IsIcon                  { return newIcon("location") }
func TiLockClosedOutline() icons.IsIcon         { return newIcon("lock-closed-outline") }
func TiLockClosed() icons.IsIcon                { return newIcon("lock-closed") }
func TiLockOpenOutline() icons.IsIcon           { return newIcon("lock-open-outline") }
func TiLockOpen() icons.IsIcon                  { return newIcon("lock-open") }
func TiMail() icons.IsIcon                      { return newIcon("mail") }
func TiMap() icons.IsIcon                       { return newIcon("map") }
func TiMediaEjectOutline() icons.IsIcon         { return newIcon("media-eject-outline") }
func TiMediaEject() icons.IsIcon                { return newIcon("media-eject") }
func TiMediaFastForwardOutline() icons.IsIcon   { return newIcon("media-fast-forward-outline") }
func TiMediaFastForward() icons.IsIcon          { return newIcon("media-fast-forward") }
func TiMediaPauseOutline() icons.IsIcon         { return newIcon("media-pause-outline") }
func TiMediaPause() icons.IsIcon                { return newIcon("media-pause") }
func TiMediaPlayOutline() icons.IsIcon          { return newIcon("media-play-outline") }
func TiMediaPlayReverseOutline() icons.IsIcon   { return newIcon("media-play-reverse-outline") }
func TiMediaPlayReverse() icons.IsIcon          { return newIcon("media-play-reverse") }
func TiMediaPlay() icons.IsIcon                 { return newIcon("media-play") }
func TiMediaRecordOutline() icons.IsIcon        { return newIcon("media-record-outline") }
func TiMediaRecord() icons.IsIcon               { return newIcon("media-record") }
func TiMediaRewindOutline() icons.IsIcon        { return newIcon("media-rewind-outline") }
func TiMediaRewind() icons.IsIcon               { return newIcon("media-rewind") }
func TiMediaStopOutline() icons.IsIcon          { return newIcon("media-stop-outline") }
func TiMediaStop() icons.IsIcon                 { return newIcon("media-stop") }
func TiMessageTyping() icons.IsIcon             { return newIcon("message-typing") }
func TiMessage() icons.IsIcon                   { return newIcon("message") }
func TiMessages() icons.IsIcon                  { return newIcon("messages") }
func TiMicrophoneOutline() icons.IsIcon         { return newIcon("microphone-outline") }
func TiMicrophone() icons.IsIcon                { return newIcon("microphone") }
func TiMinusOutline() icons.IsIcon              { return newIcon("minus-outline") }
func TiMinus() icons.IsIcon                     { return newIcon("minus") }
func TiMortarBoard() icons.IsIcon               { return newIcon("mortar-board") }
func TiNews() icons.IsIcon                      { return newIcon("news") }
func TiNotesOutline() icons.IsIcon              { return newIcon("notes-outline") }
func TiNotes() icons.IsIcon                     { return newIcon("notes") }
func TiPen() icons.IsIcon                       { return newIcon("pen") }
func TiPencil() icons.IsIcon                    { return newIcon("pencil") }
func TiPhoneOutline() icons.IsIcon              { return newIcon("phone-outline") }
func TiPhone() icons.IsIcon                     { return newIcon("phone") }
func TiPiOutline() icons.IsIcon                 { return newIcon("pi-outline") }
func TiPi() icons.IsIcon                        { return newIcon("pi") }
func TiPinOutline() icons.IsIcon                { return newIcon("pin-outline") }
func TiPin() icons.IsIcon                       { return newIcon("pin") }
func TiPipette() icons.IsIcon                   { return newIcon("pipette") }
func TiPlaneOutline() icons.IsIcon              { return newIcon("plane-outline") }
func TiPlane() icons.IsIcon                     { return newIcon("plane") }
func TiPlug() icons.IsIcon                      { return newIcon("plug") }
func TiPlusOutline() icons.IsIcon               { return newIcon("plus-outline") }
func TiPlus() icons.IsIcon                      { return newIcon("plus") }
func TiPointOfInterestOutline() icons.IsIcon    { return newIcon("point-of-interest-outline") }
func TiPointOfInterest() icons.IsIcon           { return newIcon("point-of-interest") }
func TiPowerOutline() icons.IsIcon              { return newIcon("power-outline") }
func TiPower() icons.IsIcon                     { return newIcon("power") }
func TiPrinter() icons.IsIcon                   { return newIcon("printer") }
func TiPuzzleOutline() icons.IsIcon             { return newIcon("puzzle-outline") }
func TiPuzzle() icons.IsIcon                    { return newIcon("puzzle") }
func TiRadarOutline() icons.IsIcon              { return newIcon("radar-outline") }
func TiRadar() icons.IsIcon                     { return newIcon("radar") }
func TiRefreshOutline() icons.IsIcon            { return newIcon("refresh-outline") }
func TiRefresh() icons.IsIcon                   { return newIcon("refresh") }
func TiRssOutline() icons.IsIcon                { return newIcon("rss-outline") }
func TiRss() icons.IsIcon                       { return newIcon("rss") }
func TiScissorsOutline() icons.IsIcon           { return newIcon("scissors-outline") }
func TiScissors() icons.IsIcon                  { return newIcon("scissors") }
func TiShoppingBag() icons.IsIcon               { return newIcon("shopping-bag") }
func TiShoppingCart() icons.IsIcon              { return newIcon("shopping-cart") }
func TiSocialAtCircular() icons.IsIcon          { return newIcon("social-at-circular") }
func TiSocialDribbbleCircular() icons.IsIcon    { return newIcon("social-dribbble-circular") }
func TiSocialDribbble() icons.IsIcon            { return newIcon("social-dribbble") }
func TiSocialFacebookCircular() icons.IsIcon    { return newIcon("social-facebook-circular") }
func TiSocialFacebook() icons.IsIcon            { return newIcon("social-facebook") }
func TiSocialFlickrCircular() icons.IsIcon      { return newIcon("social-flickr-circular") }
func TiSocialFlickr() icons.IsIcon              { return newIcon("social-flickr") }
func TiSocialGithubCircular() icons.IsIcon      { return newIcon("social-github-circular") }
func TiSocialGithub() icons.IsIcon              { return newIcon("social-github") }
func TiSocialGooglePlusCircular() icons.IsIcon  { return newIcon("social-google-plus-circular") }
func TiSocialGooglePlus() icons.IsIcon          { return newIcon("social-google-plus") }
func TiSocialInstagramCircular() icons.IsIcon   { return newIcon("social-instagram-circular") }
func TiSocialInstagram() icons.IsIcon           { return newIcon("social-instagram") }
func TiSocialLastFmCircular() icons.IsIcon      { return newIcon("social-last-fm-circular") }
func TiSocialLastFm() icons.IsIcon              { return newIcon("social-last-fm") }
func TiSocialLinkedinCircular() icons.IsIcon    { return newIcon("social-linkedin-circular") }
func TiSocialLinkedin() icons.IsIcon            { return newIcon("social-linkedin") }
func TiSocialPinterestCircular() icons.IsIcon   { return newIcon("social-pinterest-circular") }
func TiSocialPinterest() icons.IsIcon           { return newIcon("social-pinterest") }
func TiSocialSkypeOutline() icons.IsIcon        { return newIcon("social-skype-outline") }
func TiSocialSkype() icons.IsIcon               { return newIcon("social-skype") }
func TiSocialTumblerCircular() icons.IsIcon     { return newIcon("social-tumbler-circular") }
func TiSocialTumbler() icons.IsIcon             { return newIcon("social-tumbler") }
func TiSocialTwitterCircular() icons.IsIcon     { return newIcon("social-twitter-circular") }
func TiSocialTwitter() icons.IsIcon             { return newIcon("social-twitter") }
func TiSocialVimeoCircular() icons.IsIcon       { return newIcon("social-vimeo-circular") }
func TiSocialVimeo() icons.IsIcon               { return newIcon("social-vimeo") }
func TiSocialYoutubeCircular() icons.IsIcon     { return newIcon("social-youtube-circular") }
func TiSocialYoutube() icons.IsIcon             { return newIcon("social-youtube") }
func TiSortAlphabeticallyOutline() icons.IsIcon { return newIcon("sort-alphabetically-outline") }
func TiSortAlphabetically() icons.IsIcon        { return newIcon("sort-alphabetically") }
func TiSortNumericallyOutline() icons.IsIcon    { return newIcon("sort-numerically-outline") }
func TiSortNumerically() icons.IsIcon           { return newIcon("sort-numerically") }
func TiSpannerOutline() icons.IsIcon            { return newIcon("spanner-outline") }
func TiSpanner() icons.IsIcon                   { return newIcon("spanner") }
func TiSpiral() icons.IsIcon                    { return newIcon("spiral") }
func TiStarFullOutline() icons.IsIcon           { return newIcon("star-full-outline") }
func TiStarHalfOutline() icons.IsIcon           { return newIcon("star-half-outline") }
func TiStarHalf() icons.IsIcon                  { return newIcon("star-half") }
func TiStarOutline() icons.IsIcon               { return newIcon("star-outline") }
func TiStar() icons.IsIcon                      { return newIcon("star") }
func TiStarburstOutline() icons.IsIcon          { return newIcon("starburst-outline") }
func TiStarburst() icons.IsIcon                 { return newIcon("starburst") }
func TiStopwatch() icons.IsIcon                 { return newIcon("stopwatch") }
func TiSupport() icons.IsIcon                   { return newIcon("support") }
func TiTabsOutline() icons.IsIcon               { return newIcon("tabs-outline") }
func TiTag() icons.IsIcon                       { return newIcon("tag") }
func TiTags() icons.IsIcon                      { return newIcon("tags") }
func TiThLargeOutline() icons.IsIcon            { return newIcon("th-large-outline") }
func TiThLarge() icons.IsIcon                   { return newIcon("th-large") }
func TiThListOutline() icons.IsIcon             { return newIcon("th-list-outline") }
func TiThList() icons.IsIcon                    { return newIcon("th-list") }
func TiThMenuOutline() icons.IsIcon             { return newIcon("th-menu-outline") }
func TiThMenu() icons.IsIcon                    { return newIcon("th-menu") }
func TiThSmallOutline() icons.IsIcon            { return newIcon("th-small-outline") }
func TiThSmall() icons.IsIcon                   { return newIcon("th-small") }
func TiThermometer() icons.IsIcon               { return newIcon("thermometer") }
func TiThumbsDown() icons.IsIcon                { return newIcon("thumbs-down") }
func TiThumbsOk() icons.IsIcon                  { return newIcon("thumbs-ok") }
func TiThumbsUp() icons.IsIcon                  { return newIcon("thumbs-up") }
func TiTickOutline() icons.IsIcon               { return newIcon("tick-outline") }
func TiTick() icons.IsIcon                      { return newIcon("tick") }
func TiTicket() icons.IsIcon                    { return newIcon("ticket") }
func TiTime() icons.IsIcon                      { return newIcon("time") }
func TiTimesOutline() icons.IsIcon              { return newIcon("times-outline") }
func TiTimes() icons.IsIcon                     { return newIcon("times") }
func TiTrash() icons.IsIcon                     { return newIcon("trash") }
func TiTree() icons.IsIcon                      { return newIcon("tree") }
func TiUploadOutline() icons.IsIcon             { return newIcon("upload-outline") }
func TiUpload() icons.IsIcon                    { return newIcon("upload") }
func TiUserAddOutline() icons.IsIcon            { return newIcon("user-add-outline") }
func TiUserAdd() icons.IsIcon                   { return newIcon("user-add") }
func TiUserDeleteOutline() icons.IsIcon         { return newIcon("user-delete-outline") }
func TiUserDelete() icons.IsIcon                { return newIcon("user-delete") }
func TiUserOutline() icons.IsIcon               { return newIcon("user-outline") }
func TiUser() icons.IsIcon                      { return newIcon("user") }
func TiVendorAndroid() icons.IsIcon             { return newIcon("vendor-android") }
func TiVendorApple() icons.IsIcon               { return newIcon("vendor-apple") }
func TiVendorMicrosoft() icons.IsIcon           { return newIcon("vendor-microsoft") }
func TiVideoOutline() icons.IsIcon              { return newIcon("video-outline") }
func TiVideo() icons.IsIcon                     { return newIcon("video") }
func TiVolumeDown() icons.IsIcon                { return newIcon("volume-down") }
func TiVolumeMute() icons.IsIcon                { return newIcon("volume-mute") }
func TiVolumeUp() icons.IsIcon                  { return newIcon("volume-up") }
func TiVolume() icons.IsIcon                    { return newIcon("volume") }
func TiWarningOutline() icons.IsIcon            { return newIcon("warning-outline") }
func TiWarning() icons.IsIcon                   { return newIcon("warning") }
func TiWatch() icons.IsIcon                     { return newIcon("watch") }
func TiWavesOutline() icons.IsIcon              { return newIcon("waves-outline") }
func TiWaves() icons.IsIcon                     { return newIcon("waves") }
func TiWeatherCloudy() icons.IsIcon             { return newIcon("weather-cloudy") }
func TiWeatherDownpour() icons.IsIcon           { return newIcon("weather-downpour") }
func TiWeatherNight() icons.IsIcon              { return newIcon("weather-night") }
func TiWeatherPartlySunny() icons.IsIcon        { return newIcon("weather-partly-sunny") }
func TiWeatherShower() icons.IsIcon             { return newIcon("weather-shower") }
func TiWeatherSnow() icons.IsIcon               { return newIcon("weather-snow") }
func TiWeatherStormy() icons.IsIcon             { return newIcon("weather-stormy") }
func TiWeatherSunny() icons.IsIcon              { return newIcon("weather-sunny") }
func TiWeatherWindyCloudy() icons.IsIcon        { return newIcon("weather-windy-cloudy") }
func TiWeatherWindy() icons.IsIcon              { return newIcon("weather-windy") }
func TiWiFiOutline() icons.IsIcon               { return newIcon("wi-fi-outline") }
func TiWiFi() icons.IsIcon                      { return newIcon("wi-fi") }
func TiWine() icons.IsIcon                      { return newIcon("wine") }
func TiWorldOutline() icons.IsIcon              { return newIcon("world-outline") }
func TiWorld() icons.IsIcon                     { return newIcon("world") }
func TiZoomInOutline() icons.IsIcon             { return newIcon("zoom-in-outline") }
func TiZoomIn() icons.IsIcon                    { return newIcon("zoom-in") }
func TiZoomOutOutline() icons.IsIcon            { return newIcon("zoom-out-outline") }
func TiZoomOut() icons.IsIcon                   { return newIcon("zoom-out") }
func TiZoomOutline() icons.IsIcon               { return newIcon("zoom-outline") }
func TiZoom() icons.IsIcon                      { return newIcon("zoom") }
