package tfi

import "github.com/raitucarp/gomix/icons"

func TfiAgenda() icons.IsIcon                   { return newIcon("agenda") }
func TfiAlarmClock() icons.IsIcon               { return newIcon("alarm-clock") }
func TfiAlert() icons.IsIcon                    { return newIcon("alert") }
func TfiAlignCenter() icons.IsIcon              { return newIcon("align-center") }
func TfiAlignJustify() icons.IsIcon             { return newIcon("align-justify") }
func TfiAlignLeft() icons.IsIcon                { return newIcon("align-left") }
func TfiAlignRight() icons.IsIcon               { return newIcon("align-right") }
func TfiAnchor() icons.IsIcon                   { return newIcon("anchor") }
func TfiAndroid() icons.IsIcon                  { return newIcon("android") }
func TfiAngleDoubleDown() icons.IsIcon          { return newIcon("angle-double-down") }
func TfiAngleDoubleLeft() icons.IsIcon          { return newIcon("angle-double-left") }
func TfiAngleDoubleRight() icons.IsIcon         { return newIcon("angle-double-right") }
func TfiAngleDoubleUp() icons.IsIcon            { return newIcon("angle-double-up") }
func TfiAngleDown() icons.IsIcon                { return newIcon("angle-down") }
func TfiAngleLeft() icons.IsIcon                { return newIcon("angle-left") }
func TfiAngleRight() icons.IsIcon               { return newIcon("angle-right") }
func TfiAngleUp() icons.IsIcon                  { return newIcon("angle-up") }
func TfiAnnouncement() icons.IsIcon             { return newIcon("announcement") }
func TfiApple() icons.IsIcon                    { return newIcon("apple") }
func TfiArchive() icons.IsIcon                  { return newIcon("archive") }
func TfiArrowCircleDown() icons.IsIcon          { return newIcon("arrow-circle-down") }
func TfiArrowCircleLeft() icons.IsIcon          { return newIcon("arrow-circle-left") }
func TfiArrowCircleRight() icons.IsIcon         { return newIcon("arrow-circle-right") }
func TfiArrowCircleUp() icons.IsIcon            { return newIcon("arrow-circle-up") }
func TfiArrowDown() icons.IsIcon                { return newIcon("arrow-down") }
func TfiArrowLeft() icons.IsIcon                { return newIcon("arrow-left") }
func TfiArrowRight() icons.IsIcon               { return newIcon("arrow-right") }
func TfiArrowTopLeft() icons.IsIcon             { return newIcon("arrow-top-left") }
func TfiArrowTopRight() icons.IsIcon            { return newIcon("arrow-top-right") }
func TfiArrowUp() icons.IsIcon                  { return newIcon("arrow-up") }
func TfiArrow() icons.IsIcon                    { return newIcon("arrow") }
func TfiArrowsCorner() icons.IsIcon             { return newIcon("arrows-corner") }
func TfiArrowsHorizontal() icons.IsIcon         { return newIcon("arrows-horizontal") }
func TfiArrowsVertical() icons.IsIcon           { return newIcon("arrows-vertical") }
func TfiBackLeft() icons.IsIcon                 { return newIcon("back-left") }
func TfiBackRight() icons.IsIcon                { return newIcon("back-right") }
func TfiBag() icons.IsIcon                      { return newIcon("bag") }
func TfiBarChartAlt() icons.IsIcon              { return newIcon("bar-chart-alt") }
func TfiBarChart() icons.IsIcon                 { return newIcon("bar-chart") }
func TfiBasketball() icons.IsIcon               { return newIcon("basketball") }
func TfiBell() icons.IsIcon                     { return newIcon("bell") }
func TfiBlackboard() icons.IsIcon               { return newIcon("blackboard") }
func TfiBoltAlt() icons.IsIcon                  { return newIcon("bolt-alt") }
func TfiBolt() icons.IsIcon                     { return newIcon("bolt") }
func TfiBook() icons.IsIcon                     { return newIcon("book") }
func TfiBookmarkAlt() icons.IsIcon              { return newIcon("bookmark-alt") }
func TfiBookmark() icons.IsIcon                 { return newIcon("bookmark") }
func TfiBriefcase() icons.IsIcon                { return newIcon("briefcase") }
func TfiBrushAlt() icons.IsIcon                 { return newIcon("brush-alt") }
func TfiBrush() icons.IsIcon                    { return newIcon("brush") }
func TfiCalendar() icons.IsIcon                 { return newIcon("calendar") }
func TfiCamera() icons.IsIcon                   { return newIcon("camera") }
func TfiCar() icons.IsIcon                      { return newIcon("car") }
func TfiCheckBox() icons.IsIcon                 { return newIcon("check-box") }
func TfiCheck() icons.IsIcon                    { return newIcon("check") }
func TfiClip() icons.IsIcon                     { return newIcon("clip") }
func TfiClipboard() icons.IsIcon                { return newIcon("clipboard") }
func TfiClose() icons.IsIcon                    { return newIcon("close") }
func TfiCloudDown() icons.IsIcon                { return newIcon("cloud-down") }
func TfiCloudUp() icons.IsIcon                  { return newIcon("cloud-up") }
func TfiCloud() icons.IsIcon                    { return newIcon("cloud") }
func TfiCommentAlt() icons.IsIcon               { return newIcon("comment-alt") }
func TfiComment() icons.IsIcon                  { return newIcon("comment") }
func TfiCommentsSmiley() icons.IsIcon           { return newIcon("comments-smiley") }
func TfiComments() icons.IsIcon                 { return newIcon("comments") }
func TfiControlBackward() icons.IsIcon          { return newIcon("control-backward") }
func TfiControlEject() icons.IsIcon             { return newIcon("control-eject") }
func TfiControlForward() icons.IsIcon           { return newIcon("control-forward") }
func TfiControlPause() icons.IsIcon             { return newIcon("control-pause") }
func TfiControlPlay() icons.IsIcon              { return newIcon("control-play") }
func TfiControlRecord() icons.IsIcon            { return newIcon("control-record") }
func TfiControlShuffle() icons.IsIcon           { return newIcon("control-shuffle") }
func TfiControlSkipBackward() icons.IsIcon      { return newIcon("control-skip-backward") }
func TfiControlSkipForward() icons.IsIcon       { return newIcon("control-skip-forward") }
func TfiControlStop() icons.IsIcon              { return newIcon("control-stop") }
func TfiCreditCard() icons.IsIcon               { return newIcon("credit-card") }
func TfiCrown() icons.IsIcon                    { return newIcon("crown") }
func TfiCss3() icons.IsIcon                     { return newIcon("css3") }
func TfiCup() icons.IsIcon                      { return newIcon("cup") }
func TfiCut() icons.IsIcon                      { return newIcon("cut") }
func TfiDashboard() icons.IsIcon                { return newIcon("dashboard") }
func TfiDesktop() icons.IsIcon                  { return newIcon("desktop") }
func TfiDirectionAlt() icons.IsIcon             { return newIcon("direction-alt") }
func TfiDirection() icons.IsIcon                { return newIcon("direction") }
func TfiDownload() icons.IsIcon                 { return newIcon("download") }
func TfiDribbble() icons.IsIcon                 { return newIcon("dribbble") }
func TfiDropboxAlt() icons.IsIcon               { return newIcon("dropbox-alt") }
func TfiDropbox() icons.IsIcon                  { return newIcon("dropbox") }
func TfiDrupal() icons.IsIcon                   { return newIcon("drupal") }
func TfiEmail() icons.IsIcon                    { return newIcon("email") }
func TfiEnvelope() icons.IsIcon                 { return newIcon("envelope") }
func TfiEraser() icons.IsIcon                   { return newIcon("eraser") }
func TfiExchangeVertical() icons.IsIcon         { return newIcon("exchange-vertical") }
func TfiExport() icons.IsIcon                   { return newIcon("export") }
func TfiEye() icons.IsIcon                      { return newIcon("eye") }
func TfiFaceSad() icons.IsIcon                  { return newIcon("face-sad") }
func TfiFaceSmile() icons.IsIcon                { return newIcon("face-smile") }
func TfiFacebook() icons.IsIcon                 { return newIcon("facebook") }
func TfiFile() icons.IsIcon                     { return newIcon("file") }
func TfiFiles() icons.IsIcon                    { return newIcon("files") }
func TfiFilter() icons.IsIcon                   { return newIcon("filter") }
func TfiFlagAlt2() icons.IsIcon                 { return newIcon("flag-alt-2") }
func TfiFlagAlt() icons.IsIcon                  { return newIcon("flag-alt") }
func TfiFlag() icons.IsIcon                     { return newIcon("flag") }
func TfiFlickrAlt() icons.IsIcon                { return newIcon("flickr-alt") }
func TfiFlickr() icons.IsIcon                   { return newIcon("flickr") }
func TfiFolder() icons.IsIcon                   { return newIcon("folder") }
func TfiFullscreen() icons.IsIcon               { return newIcon("fullscreen") }
func TfiGallery() icons.IsIcon                  { return newIcon("gallery") }
func TfiGame() icons.IsIcon                     { return newIcon("game") }
func TfiGift() icons.IsIcon                     { return newIcon("gift") }
func TfiGithub() icons.IsIcon                   { return newIcon("github") }
func TfiGoogle() icons.IsIcon                   { return newIcon("google") }
func TfiHandDrag() icons.IsIcon                 { return newIcon("hand-drag") }
func TfiHandOpen() icons.IsIcon                 { return newIcon("hand-open") }
func TfiHandPointDown() icons.IsIcon            { return newIcon("hand-point-down") }
func TfiHandPointLeft() icons.IsIcon            { return newIcon("hand-point-left") }
func TfiHandPointRight() icons.IsIcon           { return newIcon("hand-point-right") }
func TfiHandPointUp() icons.IsIcon              { return newIcon("hand-point-up") }
func TfiHandStop() icons.IsIcon                 { return newIcon("hand-stop") }
func TfiHarddrive() icons.IsIcon                { return newIcon("harddrive") }
func TfiHarddrives() icons.IsIcon               { return newIcon("harddrives") }
func TfiHeadphoneAlt() icons.IsIcon             { return newIcon("headphone-alt") }
func TfiHeadphone() icons.IsIcon                { return newIcon("headphone") }
func TfiHeartBroken() icons.IsIcon              { return newIcon("heart-broken") }
func TfiHeart() icons.IsIcon                    { return newIcon("heart") }
func TfiHelpAlt() icons.IsIcon                  { return newIcon("help-alt") }
func TfiHelp() icons.IsIcon                     { return newIcon("help") }
func TfiHome() icons.IsIcon                     { return newIcon("home") }
func TfiHtml5() icons.IsIcon                    { return newIcon("html5") }
func TfiHummer() icons.IsIcon                   { return newIcon("hummer") }
func TfiIdBadge() icons.IsIcon                  { return newIcon("id-badge") }
func TfiImage() icons.IsIcon                    { return newIcon("image") }
func TfiImport() icons.IsIcon                   { return newIcon("import") }
func TfiInfinite() icons.IsIcon                 { return newIcon("infinite") }
func TfiInfoAlt() icons.IsIcon                  { return newIcon("info-alt") }
func TfiInfo() icons.IsIcon                     { return newIcon("info") }
func TfiInkPen() icons.IsIcon                   { return newIcon("ink-pen") }
func TfiInstagram() icons.IsIcon                { return newIcon("instagram") }
func TfiItalic() icons.IsIcon                   { return newIcon("Italic") }
func TfiJoomla() icons.IsIcon                   { return newIcon("joomla") }
func TfiJsfiddle() icons.IsIcon                 { return newIcon("jsfiddle") }
func TfiKey() icons.IsIcon                      { return newIcon("key") }
func TfiLayersAlt() icons.IsIcon                { return newIcon("layers-alt") }
func TfiLayers() icons.IsIcon                   { return newIcon("layers") }
func TfiLayoutAccordionList() icons.IsIcon      { return newIcon("layout-accordion-list") }
func TfiLayoutAccordionMerged() icons.IsIcon    { return newIcon("layout-accordion-merged") }
func TfiLayoutAccordionSeparated() icons.IsIcon { return newIcon("layout-accordion-separated") }
func TfiLayoutColumn2Alt() icons.IsIcon         { return newIcon("layout-column2-alt") }
func TfiLayoutColumn2() icons.IsIcon            { return newIcon("layout-column2") }
func TfiLayoutColumn3Alt() icons.IsIcon         { return newIcon("layout-column3-alt") }
func TfiLayoutColumn3() icons.IsIcon            { return newIcon("layout-column3") }
func TfiLayoutColumn4Alt() icons.IsIcon         { return newIcon("layout-column4-alt") }
func TfiLayoutColumn4() icons.IsIcon            { return newIcon("layout-column4") }
func TfiLayoutCtaBtnLeft() icons.IsIcon         { return newIcon("layout-cta-btn-left") }
func TfiLayoutCtaBtnRight() icons.IsIcon        { return newIcon("layout-cta-btn-right") }
func TfiLayoutCtaCenter() icons.IsIcon          { return newIcon("layout-cta-center") }
func TfiLayoutCtaLeft() icons.IsIcon            { return newIcon("layout-cta-left") }
func TfiLayoutCtaRight() icons.IsIcon           { return newIcon("layout-cta-right") }
func TfiLayoutGrid2Alt() icons.IsIcon           { return newIcon("layout-grid2-alt") }
func TfiLayoutGrid2Thumb() icons.IsIcon         { return newIcon("layout-grid2-thumb") }
func TfiLayoutGrid2() icons.IsIcon              { return newIcon("layout-grid2") }
func TfiLayoutGrid3Alt() icons.IsIcon           { return newIcon("layout-grid3-alt") }
func TfiLayoutGrid3() icons.IsIcon              { return newIcon("layout-grid3") }
func TfiLayoutGrid4Alt() icons.IsIcon           { return newIcon("layout-grid4-alt") }
func TfiLayoutGrid4() icons.IsIcon              { return newIcon("layout-grid4") }
func TfiLayoutLineSolid() icons.IsIcon          { return newIcon("layout-line-solid") }
func TfiLayoutListLargeImage() icons.IsIcon     { return newIcon("layout-list-large-image") }
func TfiLayoutListPost() icons.IsIcon           { return newIcon("layout-list-post") }
func TfiLayoutListThumbAlt() icons.IsIcon       { return newIcon("layout-list-thumb-alt") }
func TfiLayoutListThumb() icons.IsIcon          { return newIcon("layout-list-thumb") }
func TfiLayoutMediaCenterAlt() icons.IsIcon     { return newIcon("layout-media-center-alt") }
func TfiLayoutMediaCenter() icons.IsIcon        { return newIcon("layout-media-center") }
func TfiLayoutMediaLeftAlt() icons.IsIcon       { return newIcon("layout-media-left-alt") }
func TfiLayoutMediaLeft() icons.IsIcon          { return newIcon("layout-media-left") }
func TfiLayoutMediaOverlayAlt2() icons.IsIcon   { return newIcon("layout-media-overlay-alt-2") }
func TfiLayoutMediaOverlayAlt() icons.IsIcon    { return newIcon("layout-media-overlay-alt") }
func TfiLayoutMediaOverlay() icons.IsIcon       { return newIcon("layout-media-overlay") }
func TfiLayoutMediaRightAlt() icons.IsIcon      { return newIcon("layout-media-right-alt") }
func TfiLayoutMediaRight() icons.IsIcon         { return newIcon("layout-media-right") }
func TfiLayoutMenuFull() icons.IsIcon           { return newIcon("layout-menu-full") }
func TfiLayoutMenuSeparated() icons.IsIcon      { return newIcon("layout-menu-separated") }
func TfiLayoutMenuV() icons.IsIcon              { return newIcon("layout-menu-v") }
func TfiLayoutMenu() icons.IsIcon               { return newIcon("layout-menu") }
func TfiLayoutPlaceholder() icons.IsIcon        { return newIcon("layout-placeholder") }
func TfiLayoutSidebar2() icons.IsIcon           { return newIcon("layout-sidebar-2") }
func TfiLayoutSidebarLeft() icons.IsIcon        { return newIcon("layout-sidebar-left") }
func TfiLayoutSidebarNone() icons.IsIcon        { return newIcon("layout-sidebar-none") }
func TfiLayoutSidebarRight() icons.IsIcon       { return newIcon("layout-sidebar-right") }
func TfiLayoutSliderAlt() icons.IsIcon          { return newIcon("layout-slider-alt") }
func TfiLayoutSlider() icons.IsIcon             { return newIcon("layout-slider") }
func TfiLayoutTabMin() icons.IsIcon             { return newIcon("layout-tab-min") }
func TfiLayoutTabV() icons.IsIcon               { return newIcon("layout-tab-v") }
func TfiLayoutTabWindow() icons.IsIcon          { return newIcon("layout-tab-window") }
func TfiLayoutTab() icons.IsIcon                { return newIcon("layout-tab") }
func TfiLayoutWidthDefaultAlt() icons.IsIcon    { return newIcon("layout-width-default-alt") }
func TfiLayoutWidthDefault() icons.IsIcon       { return newIcon("layout-width-default") }
func TfiLayoutWidthFull() icons.IsIcon          { return newIcon("layout-width-full") }
func TfiLayout() icons.IsIcon                   { return newIcon("layout") }
func TfiLightBulb() icons.IsIcon                { return newIcon("light-bulb") }
func TfiLineDashed() icons.IsIcon               { return newIcon("line-dashed") }
func TfiLineDotted() icons.IsIcon               { return newIcon("line-dotted") }
func TfiLineDouble() icons.IsIcon               { return newIcon("line-double") }
func TfiLink() icons.IsIcon                     { return newIcon("link") }
func TfiLinkedin() icons.IsIcon                 { return newIcon("linkedin") }
func TfiLinux() icons.IsIcon                    { return newIcon("linux") }
func TfiListOl() icons.IsIcon                   { return newIcon("list-ol") }
func TfiList() icons.IsIcon                     { return newIcon("list") }
func TfiLocationArrow() icons.IsIcon            { return newIcon("location-arrow") }
func TfiLocationPin() icons.IsIcon              { return newIcon("location-pin") }
func TfiLock() icons.IsIcon                     { return newIcon("lock") }
func TfiLoop() icons.IsIcon                     { return newIcon("loop") }
func TfiMagnet() icons.IsIcon                   { return newIcon("magnet") }
func TfiMapAlt() icons.IsIcon                   { return newIcon("map-alt") }
func TfiMap() icons.IsIcon                      { return newIcon("map") }
func TfiMarkerAlt() icons.IsIcon                { return newIcon("marker-alt") }
func TfiMarker() icons.IsIcon                   { return newIcon("marker") }
func TfiMedallAlt() icons.IsIcon                { return newIcon("medall-alt") }
func TfiMedall() icons.IsIcon                   { return newIcon("medall") }
func TfiMenuAlt() icons.IsIcon                  { return newIcon("menu-alt") }
func TfiMenu() icons.IsIcon                     { return newIcon("menu") }
func TfiMicrophoneAlt() icons.IsIcon            { return newIcon("microphone-alt") }
func TfiMicrophone() icons.IsIcon               { return newIcon("microphone") }
func TfiMicrosoftAlt() icons.IsIcon             { return newIcon("microsoft-alt") }
func TfiMicrosoft() icons.IsIcon                { return newIcon("microsoft") }
func TfiMinus() icons.IsIcon                    { return newIcon("minus") }
func TfiMobile() icons.IsIcon                   { return newIcon("mobile") }
func TfiMoney() icons.IsIcon                    { return newIcon("money") }
func TfiMoreAlt() icons.IsIcon                  { return newIcon("more-alt") }
func TfiMore() icons.IsIcon                     { return newIcon("more") }
func TfiMouseAlt() icons.IsIcon                 { return newIcon("mouse-alt") }
func TfiMouse() icons.IsIcon                    { return newIcon("mouse") }
func TfiMusicAlt() icons.IsIcon                 { return newIcon("music-alt") }
func TfiMusic() icons.IsIcon                    { return newIcon("music") }
func TfiNa() icons.IsIcon                       { return newIcon("na") }
func TfiNewWindow() icons.IsIcon                { return newIcon("new-window") }
func TfiNotepad() icons.IsIcon                  { return newIcon("notepad") }
func TfiPackage() icons.IsIcon                  { return newIcon("package") }
func TfiPaintBucket() icons.IsIcon              { return newIcon("paint-bucket") }
func TfiPaintRoller() icons.IsIcon              { return newIcon("paint-roller") }
func TfiPalette() icons.IsIcon                  { return newIcon("palette") }
func TfiPanel() icons.IsIcon                    { return newIcon("panel") }
func TfiParagraph() icons.IsIcon                { return newIcon("paragraph") }
func TfiPencilAlt() icons.IsIcon                { return newIcon("pencil-alt") }
func TfiPencilAlt2() icons.IsIcon               { return newIcon("pencil-alt2") }
func TfiPencil() icons.IsIcon                   { return newIcon("pencil") }
func TfiPieChart() icons.IsIcon                 { return newIcon("pie-chart") }
func TfiPinAlt() icons.IsIcon                   { return newIcon("pin-alt") }
func TfiPin() icons.IsIcon                      { return newIcon("pin") }
func TfiPin2() icons.IsIcon                     { return newIcon("pin2") }
func TfiPinterestAlt() icons.IsIcon             { return newIcon("pinterest-alt") }
func TfiPinterest() icons.IsIcon                { return newIcon("pinterest") }
func TfiPlug() icons.IsIcon                     { return newIcon("plug") }
func TfiPlus() icons.IsIcon                     { return newIcon("plus") }
func TfiPowerOff() icons.IsIcon                 { return newIcon("power-off") }
func TfiPrinter() icons.IsIcon                  { return newIcon("printer") }
func TfiPulse() icons.IsIcon                    { return newIcon("pulse") }
func TfiQuoteLeft() icons.IsIcon                { return newIcon("quote-left") }
func TfiQuoteRight() icons.IsIcon               { return newIcon("quote-right") }
func TfiReceipt() icons.IsIcon                  { return newIcon("receipt") }
func TfiReddit() icons.IsIcon                   { return newIcon("reddit") }
func TfiReload() icons.IsIcon                   { return newIcon("reload") }
func TfiRocket() icons.IsIcon                   { return newIcon("rocket") }
func TfiRssAlt() icons.IsIcon                   { return newIcon("rss-alt") }
func TfiRss() icons.IsIcon                      { return newIcon("rss") }
func TfiRulerAlt2() icons.IsIcon                { return newIcon("ruler-alt-2") }
func TfiRulerAlt() icons.IsIcon                 { return newIcon("ruler-alt") }
func TfiRulerPencil() icons.IsIcon              { return newIcon("ruler-pencil") }
func TfiRuler() icons.IsIcon                    { return newIcon("ruler") }
func TfiSaveAlt() icons.IsIcon                  { return newIcon("save-alt") }
func TfiSave() icons.IsIcon                     { return newIcon("save") }
func TfiSearch() icons.IsIcon                   { return newIcon("search") }
func TfiServer() icons.IsIcon                   { return newIcon("server") }
func TfiSettings() icons.IsIcon                 { return newIcon("settings") }
func TfiShareAlt() icons.IsIcon                 { return newIcon("share-alt") }
func TfiShare() icons.IsIcon                    { return newIcon("share") }
func TfiSharethisAlt() icons.IsIcon             { return newIcon("sharethis-alt") }
func TfiSharethis() icons.IsIcon                { return newIcon("sharethis") }
func TfiShield() icons.IsIcon                   { return newIcon("shield") }
func TfiShiftLeftAlt() icons.IsIcon             { return newIcon("shift-left-alt") }
func TfiShiftLeft() icons.IsIcon                { return newIcon("shift-left") }
func TfiShiftRightAlt() icons.IsIcon            { return newIcon("shift-right-alt") }
func TfiShiftRight() icons.IsIcon               { return newIcon("shift-right") }
func TfiShine() icons.IsIcon                    { return newIcon("shine") }
func TfiShoppingCartFull() icons.IsIcon         { return newIcon("shopping-cart-full") }
func TfiShoppingCart() icons.IsIcon             { return newIcon("shopping-cart") }
func TfiShortcode() icons.IsIcon                { return newIcon("shortcode") }
func TfiSignal() icons.IsIcon                   { return newIcon("signal") }
func TfiSkype() icons.IsIcon                    { return newIcon("skype") }
func TfiSlice() icons.IsIcon                    { return newIcon("slice") }
func TfiSmallcap() icons.IsIcon                 { return newIcon("smallcap") }
func TfiSoundcloud() icons.IsIcon               { return newIcon("soundcloud") }
func TfiSplitH() icons.IsIcon                   { return newIcon("split-h") }
func TfiSplitVAlt() icons.IsIcon                { return newIcon("split-v-alt") }
func TfiSplitV() icons.IsIcon                   { return newIcon("split-v") }
func TfiSpray() icons.IsIcon                    { return newIcon("spray") }
func TfiStackOverflow() icons.IsIcon            { return newIcon("stack-overflow") }
func TfiStamp() icons.IsIcon                    { return newIcon("stamp") }
func TfiStar() icons.IsIcon                     { return newIcon("star") }
func TfiStatsDown() icons.IsIcon                { return newIcon("stats-down") }
func TfiStatsUp() icons.IsIcon                  { return newIcon("stats-up") }
func TfiSupport() icons.IsIcon                  { return newIcon("support") }
func TfiTablet() icons.IsIcon                   { return newIcon("tablet") }
func TfiTag() icons.IsIcon                      { return newIcon("tag") }
func TfiTarget() icons.IsIcon                   { return newIcon("target") }
func TfiText() icons.IsIcon                     { return newIcon("text") }
func TfiThemifyFaviconAlt() icons.IsIcon        { return newIcon("themify-favicon-alt") }
func TfiThemifyFavicon() icons.IsIcon           { return newIcon("themify-favicon") }
func TfiThemifyLogo() icons.IsIcon              { return newIcon("themify-logo") }
func TfiThought() icons.IsIcon                  { return newIcon("thought") }
func TfiThumbDown() icons.IsIcon                { return newIcon("thumb-down") }
func TfiThumbUp() icons.IsIcon                  { return newIcon("thumb-up") }
func TfiTicket() icons.IsIcon                   { return newIcon("ticket") }
func TfiTime() icons.IsIcon                     { return newIcon("time") }
func TfiTimer() icons.IsIcon                    { return newIcon("timer") }
func TfiTrash() icons.IsIcon                    { return newIcon("trash") }
func TfiTrello() icons.IsIcon                   { return newIcon("trello") }
func TfiTruck() icons.IsIcon                    { return newIcon("truck") }
func TfiTumblrAlt() icons.IsIcon                { return newIcon("tumblr-alt") }
func TfiTumblr() icons.IsIcon                   { return newIcon("tumblr") }
func TfiTwitterAlt() icons.IsIcon               { return newIcon("twitter-alt") }
func TfiTwitter() icons.IsIcon                  { return newIcon("twitter") }
func TfiUnderline() icons.IsIcon                { return newIcon("underline") }
func TfiUnlink() icons.IsIcon                   { return newIcon("unlink") }
func TfiUnlock() icons.IsIcon                   { return newIcon("unlock") }
func TfiUpload() icons.IsIcon                   { return newIcon("upload") }
func TfiUppercase() icons.IsIcon                { return newIcon("uppercase") }
func TfiUser() icons.IsIcon                     { return newIcon("user") }
func TfiVector() icons.IsIcon                   { return newIcon("vector") }
func TfiVideoCamera() icons.IsIcon              { return newIcon("video-camera") }
func TfiVideoClapper() icons.IsIcon             { return newIcon("video-clapper") }
func TfiViewGrid() icons.IsIcon                 { return newIcon("view-grid") }
func TfiViewListAlt() icons.IsIcon              { return newIcon("view-list-alt") }
func TfiViewList() icons.IsIcon                 { return newIcon("view-list") }
func TfiVimeoAlt() icons.IsIcon                 { return newIcon("vimeo-alt") }
func TfiVimeo() icons.IsIcon                    { return newIcon("vimeo") }
func TfiVolume() icons.IsIcon                   { return newIcon("volume") }
func TfiWallet() icons.IsIcon                   { return newIcon("wallet") }
func TfiWand() icons.IsIcon                     { return newIcon("wand") }
func TfiWheelchair() icons.IsIcon               { return newIcon("wheelchair") }
func TfiWidgetAlt() icons.IsIcon                { return newIcon("widget-alt") }
func TfiWidget() icons.IsIcon                   { return newIcon("widget") }
func TfiWidgetized() icons.IsIcon               { return newIcon("widgetized") }
func TfiWindow() icons.IsIcon                   { return newIcon("window") }
func TfiWordpress() icons.IsIcon                { return newIcon("wordpress") }
func TfiWorld() icons.IsIcon                    { return newIcon("world") }
func TfiWrite() icons.IsIcon                    { return newIcon("write") }
func TfiYahoo() icons.IsIcon                    { return newIcon("yahoo") }
func TfiYoutube() icons.IsIcon                  { return newIcon("youtube") }
func TfiZip() icons.IsIcon                      { return newIcon("zip") }
func TfiZoomIn() icons.IsIcon                   { return newIcon("zoom-in") }
func TfiZoomOut() icons.IsIcon                  { return newIcon("zoom-out") }
