package ai

import "github.com/raitucarp/gomix/icons"

func AiFillAccountBook() icons.IsIcon       { return newIcon(filledIcon, "account-book") }
func AiFillAlert() icons.IsIcon             { return newIcon(filledIcon, "alert") }
func AiFillAlipayCircle() icons.IsIcon      { return newIcon(filledIcon, "alipay-circle") }
func AiFillAlipaySquare() icons.IsIcon      { return newIcon(filledIcon, "alipay-square") }
func AiFillAliwangwang() icons.IsIcon       { return newIcon(filledIcon, "aliwangwang") }
func AiFillAmazonCircle() icons.IsIcon      { return newIcon(filledIcon, "amazon-circle") }
func AiFillAmazonSquare() icons.IsIcon      { return newIcon(filledIcon, "amazon-square") }
func AiFillAndroid() icons.IsIcon           { return newIcon(filledIcon, "android") }
func AiFillApi() icons.IsIcon               { return newIcon(filledIcon, "api") }
func AiFillApple() icons.IsIcon             { return newIcon(filledIcon, "apple") }
func AiFillAppstore() icons.IsIcon          { return newIcon(filledIcon, "appstore") }
func AiFillAudio() icons.IsIcon             { return newIcon(filledIcon, "audio") }
func AiFillBackward() icons.IsIcon          { return newIcon(filledIcon, "backward") }
func AiFillBank() icons.IsIcon              { return newIcon(filledIcon, "bank") }
func AiFillBehanceCircle() icons.IsIcon     { return newIcon(filledIcon, "behance-circle") }
func AiFillBehanceSquare() icons.IsIcon     { return newIcon(filledIcon, "behance-square") }
func AiFillBell() icons.IsIcon              { return newIcon(filledIcon, "bell") }
func AiFillBilibili() icons.IsIcon          { return newIcon(filledIcon, "bilibili") }
func AiFillBook() icons.IsIcon              { return newIcon(filledIcon, "book") }
func AiFillBoxPlot() icons.IsIcon           { return newIcon(filledIcon, "box-plot") }
func AiFillBug() icons.IsIcon               { return newIcon(filledIcon, "bug") }
func AiFillBuild() icons.IsIcon             { return newIcon(filledIcon, "build") }
func AiFillBulb() icons.IsIcon              { return newIcon(filledIcon, "bulb") }
func AiFillCalculator() icons.IsIcon        { return newIcon(filledIcon, "calculator") }
func AiFillCalendar() icons.IsIcon          { return newIcon(filledIcon, "calendar") }
func AiFillCamera() icons.IsIcon            { return newIcon(filledIcon, "camera") }
func AiFillCar() icons.IsIcon               { return newIcon(filledIcon, "car") }
func AiFillCaretDown() icons.IsIcon         { return newIcon(filledIcon, "caret-down") }
func AiFillCaretLeft() icons.IsIcon         { return newIcon(filledIcon, "caret-left") }
func AiFillCaretRight() icons.IsIcon        { return newIcon(filledIcon, "caret-right") }
func AiFillCaretUp() icons.IsIcon           { return newIcon(filledIcon, "caret-up") }
func AiFillCarryOut() icons.IsIcon          { return newIcon(filledIcon, "carry-out") }
func AiFillCheckCircle() icons.IsIcon       { return newIcon(filledIcon, "check-circle") }
func AiFillCheckSquare() icons.IsIcon       { return newIcon(filledIcon, "check-square") }
func AiFillChrome() icons.IsIcon            { return newIcon(filledIcon, "chrome") }
func AiFillCiCircle() icons.IsIcon          { return newIcon(filledIcon, "ci-circle") }
func AiFillClockCircle() icons.IsIcon       { return newIcon(filledIcon, "clock-circle") }
func AiFillCloseCircle() icons.IsIcon       { return newIcon(filledIcon, "close-circle") }
func AiFillCloseSquare() icons.IsIcon       { return newIcon(filledIcon, "close-square") }
func AiFillCloud() icons.IsIcon             { return newIcon(filledIcon, "cloud") }
func AiFillCodeSandboxCircle() icons.IsIcon { return newIcon(filledIcon, "code-sandbox-circle") }
func AiFillCodeSandboxSquare() icons.IsIcon { return newIcon(filledIcon, "code-sandbox-square") }
func AiFillCode() icons.IsIcon              { return newIcon(filledIcon, "code") }
func AiFillCodepenCircle() icons.IsIcon     { return newIcon(filledIcon, "codepen-circle") }
func AiFillCodepenSquare() icons.IsIcon     { return newIcon(filledIcon, "codepen-square") }
func AiFillCompass() icons.IsIcon           { return newIcon(filledIcon, "compass") }
func AiFillContacts() icons.IsIcon          { return newIcon(filledIcon, "contacts") }
func AiFillContainer() icons.IsIcon         { return newIcon(filledIcon, "container") }
func AiFillControl() icons.IsIcon           { return newIcon(filledIcon, "control") }
func AiFillCopy() icons.IsIcon              { return newIcon(filledIcon, "copy") }
func AiFillCopyrightCircle() icons.IsIcon   { return newIcon(filledIcon, "copyright-circle") }
func AiFillCreditCard() icons.IsIcon        { return newIcon(filledIcon, "credit-card") }
func AiFillCrown() icons.IsIcon             { return newIcon(filledIcon, "crown") }
func AiFillCustomerService() icons.IsIcon   { return newIcon(filledIcon, "customer-service") }
func AiFillDashboard() icons.IsIcon         { return newIcon(filledIcon, "dashboard") }
func AiFillDatabase() icons.IsIcon          { return newIcon(filledIcon, "database") }
func AiFillDelete() icons.IsIcon            { return newIcon(filledIcon, "delete") }
func AiFillDiff() icons.IsIcon              { return newIcon(filledIcon, "diff") }
func AiFillDingtalkCircle() icons.IsIcon    { return newIcon(filledIcon, "dingtalk-circle") }
func AiFillDingtalkSquare() icons.IsIcon    { return newIcon(filledIcon, "dingtalk-square") }
func AiFillDiscord() icons.IsIcon           { return newIcon(filledIcon, "discord") }
func AiFillDislike() icons.IsIcon           { return newIcon(filledIcon, "dislike") }
func AiFillDollarCircle() icons.IsIcon      { return newIcon(filledIcon, "dollar-circle") }
func AiFillDownCircle() icons.IsIcon        { return newIcon(filledIcon, "down-circle") }
func AiFillDownSquare() icons.IsIcon        { return newIcon(filledIcon, "down-square") }
func AiFillDribbbleCircle() icons.IsIcon    { return newIcon(filledIcon, "dribbble-circle") }
func AiFillDribbbleSquare() icons.IsIcon    { return newIcon(filledIcon, "dribbble-square") }
func AiFillDropboxCircle() icons.IsIcon     { return newIcon(filledIcon, "dropbox-circle") }
func AiFillDropboxSquare() icons.IsIcon     { return newIcon(filledIcon, "dropbox-square") }
func AiFillEdit() icons.IsIcon              { return newIcon(filledIcon, "edit") }
func AiFillEnvironment() icons.IsIcon       { return newIcon(filledIcon, "environment") }
func AiFillEuroCircle() icons.IsIcon        { return newIcon(filledIcon, "euro-circle") }
func AiFillExclamationCircle() icons.IsIcon { return newIcon(filledIcon, "exclamation-circle") }
func AiFillExperiment() icons.IsIcon        { return newIcon(filledIcon, "experiment") }
func AiFillEyeInvisible() icons.IsIcon      { return newIcon(filledIcon, "eye-invisible") }
func AiFillEye() icons.IsIcon               { return newIcon(filledIcon, "eye") }
func AiFillFacebook() icons.IsIcon          { return newIcon(filledIcon, "facebook") }
func AiFillFastBackward() icons.IsIcon      { return newIcon(filledIcon, "fast-backward") }
func AiFillFastForward() icons.IsIcon       { return newIcon(filledIcon, "fast-forward") }
func AiFillFileAdd() icons.IsIcon           { return newIcon(filledIcon, "file-add") }
func AiFillFileExcel() icons.IsIcon         { return newIcon(filledIcon, "file-excel") }
func AiFillFileExclamation() icons.IsIcon   { return newIcon(filledIcon, "file-exclamation") }
func AiFillFileImage() icons.IsIcon         { return newIcon(filledIcon, "file-image") }
func AiFillFileMarkdown() icons.IsIcon      { return newIcon(filledIcon, "file-markdown") }
func AiFillFilePdf() icons.IsIcon           { return newIcon(filledIcon, "file-pdf") }
func AiFillFilePpt() icons.IsIcon           { return newIcon(filledIcon, "file-ppt") }
func AiFillFileText() icons.IsIcon          { return newIcon(filledIcon, "file-text") }
func AiFillFileUnknown() icons.IsIcon       { return newIcon(filledIcon, "file-unknown") }
func AiFillFileWord() icons.IsIcon          { return newIcon(filledIcon, "file-word") }
func AiFillFileZip() icons.IsIcon           { return newIcon(filledIcon, "file-zip") }
func AiFillFile() icons.IsIcon              { return newIcon(filledIcon, "file") }
func AiFillFilter() icons.IsIcon            { return newIcon(filledIcon, "filter") }
func AiFillFire() icons.IsIcon              { return newIcon(filledIcon, "fire") }
func AiFillFlag() icons.IsIcon              { return newIcon(filledIcon, "flag") }
func AiFillFolderAdd() icons.IsIcon         { return newIcon(filledIcon, "folder-add") }
func AiFillFolderOpen() icons.IsIcon        { return newIcon(filledIcon, "folder-open") }
func AiFillFolder() icons.IsIcon            { return newIcon(filledIcon, "folder") }
func AiFillFormatPainter() icons.IsIcon     { return newIcon(filledIcon, "format-painter") }
func AiFillForward() icons.IsIcon           { return newIcon(filledIcon, "forward") }
func AiFillFrown() icons.IsIcon             { return newIcon(filledIcon, "frown") }
func AiFillFund() icons.IsIcon              { return newIcon(filledIcon, "fund") }
func AiFillFunnelPlot() icons.IsIcon        { return newIcon(filledIcon, "funnel-plot") }
func AiFillGift() icons.IsIcon              { return newIcon(filledIcon, "gift") }
func AiFillGithub() icons.IsIcon            { return newIcon(filledIcon, "github") }
func AiFillGitlab() icons.IsIcon            { return newIcon(filledIcon, "gitlab") }
func AiFillGold() icons.IsIcon              { return newIcon(filledIcon, "gold") }
func AiFillGolden() icons.IsIcon            { return newIcon(filledIcon, "golden") }
func AiFillGoogleCircle() icons.IsIcon      { return newIcon(filledIcon, "google-circle") }
func AiFillGooglePlusCircle() icons.IsIcon  { return newIcon(filledIcon, "google-plus-circle") }
func AiFillGooglePlusSquare() icons.IsIcon  { return newIcon(filledIcon, "google-plus-square") }
func AiFillGoogleSquare() icons.IsIcon      { return newIcon(filledIcon, "google-square") }
func AiFillHdd() icons.IsIcon               { return newIcon(filledIcon, "hdd") }
func AiFillHeart() icons.IsIcon             { return newIcon(filledIcon, "heart") }
func AiFillHighlight() icons.IsIcon         { return newIcon(filledIcon, "highlight") }
func AiFillHome() icons.IsIcon              { return newIcon(filledIcon, "home") }
func AiFillHourglass() icons.IsIcon         { return newIcon(filledIcon, "hourglass") }
func AiFillHtml5() icons.IsIcon             { return newIcon(filledIcon, "html5") }
func AiFillIdcard() icons.IsIcon            { return newIcon(filledIcon, "idcard") }
func AiFillIeCircle() icons.IsIcon          { return newIcon(filledIcon, "ie-circle") }
func AiFillIeSquare() icons.IsIcon          { return newIcon(filledIcon, "ie-square") }
func AiFillInfoCircle() icons.IsIcon        { return newIcon(filledIcon, "info-circle") }
func AiFillInstagram() icons.IsIcon         { return newIcon(filledIcon, "instagram") }
func AiFillInsurance() icons.IsIcon         { return newIcon(filledIcon, "insurance") }
func AiFillInteraction() icons.IsIcon       { return newIcon(filledIcon, "interaction") }
func AiFillLayout() icons.IsIcon            { return newIcon(filledIcon, "layout") }
func AiFillLeftCircle() icons.IsIcon        { return newIcon(filledIcon, "left-circle") }
func AiFillLeftSquare() icons.IsIcon        { return newIcon(filledIcon, "left-square") }
func AiFillLike() icons.IsIcon              { return newIcon(filledIcon, "like") }
func AiFillLinkedin() icons.IsIcon          { return newIcon(filledIcon, "linkedin") }
func AiFillLock() icons.IsIcon              { return newIcon(filledIcon, "lock") }
func AiFillMacCommand() icons.IsIcon        { return newIcon(filledIcon, "mac-command") }
func AiFillMail() icons.IsIcon              { return newIcon(filledIcon, "mail") }
func AiFillMedicineBox() icons.IsIcon       { return newIcon(filledIcon, "medicine-box") }
func AiFillMediumCircle() icons.IsIcon      { return newIcon(filledIcon, "medium-circle") }
func AiFillMediumSquare() icons.IsIcon      { return newIcon(filledIcon, "medium-square") }
func AiFillMeh() icons.IsIcon               { return newIcon(filledIcon, "meh") }
func AiFillMerge() icons.IsIcon             { return newIcon(filledIcon, "merge") }
func AiFillMessage() icons.IsIcon           { return newIcon(filledIcon, "message") }
func AiFillMinusCircle() icons.IsIcon       { return newIcon(filledIcon, "minus-circle") }
func AiFillMinusSquare() icons.IsIcon       { return newIcon(filledIcon, "minus-square") }
func AiFillMobile() icons.IsIcon            { return newIcon(filledIcon, "mobile") }
func AiFillMoneyCollect() icons.IsIcon      { return newIcon(filledIcon, "money-collect") }
func AiFillMoon() icons.IsIcon              { return newIcon(filledIcon, "moon") }
func AiFillMuted() icons.IsIcon             { return newIcon(filledIcon, "muted") }
func AiFillNotification() icons.IsIcon      { return newIcon(filledIcon, "notification") }
func AiFillOpenAI() icons.IsIcon            { return newIcon(filledIcon, "open-a-i") }
func AiFillPauseCircle() icons.IsIcon       { return newIcon(filledIcon, "pause-circle") }
func AiFillPayCircle() icons.IsIcon         { return newIcon(filledIcon, "pay-circle") }
func AiFillPhone() icons.IsIcon             { return newIcon(filledIcon, "phone") }
func AiFillPicture() icons.IsIcon           { return newIcon(filledIcon, "picture") }
func AiFillPieChart() icons.IsIcon          { return newIcon(filledIcon, "pie-chart") }
func AiFillPinterest() icons.IsIcon         { return newIcon(filledIcon, "pinterest") }
func AiFillPlayCircle() icons.IsIcon        { return newIcon(filledIcon, "play-circle") }
func AiFillPlaySquare() icons.IsIcon        { return newIcon(filledIcon, "play-square") }
func AiFillPlusCircle() icons.IsIcon        { return newIcon(filledIcon, "plus-circle") }
func AiFillPlusSquare() icons.IsIcon        { return newIcon(filledIcon, "plus-square") }
func AiFillPoundCircle() icons.IsIcon       { return newIcon(filledIcon, "pound-circle") }
func AiFillPrinter() icons.IsIcon           { return newIcon(filledIcon, "printer") }
func AiFillProduct() icons.IsIcon           { return newIcon(filledIcon, "product") }
func AiFillProfile() icons.IsIcon           { return newIcon(filledIcon, "profile") }
func AiFillProject() icons.IsIcon           { return newIcon(filledIcon, "project") }
func AiFillPropertySafety() icons.IsIcon    { return newIcon(filledIcon, "property-safety") }
func AiFillPushpin() icons.IsIcon           { return newIcon(filledIcon, "pushpin") }
func AiFillQqCircle() icons.IsIcon          { return newIcon(filledIcon, "qq-circle") }
func AiFillQqSquare() icons.IsIcon          { return newIcon(filledIcon, "qq-square") }
func AiFillQuestionCircle() icons.IsIcon    { return newIcon(filledIcon, "question-circle") }
func AiFillRead() icons.IsIcon              { return newIcon(filledIcon, "read") }
func AiFillReconciliation() icons.IsIcon    { return newIcon(filledIcon, "reconciliation") }
func AiFillRedEnvelope() icons.IsIcon       { return newIcon(filledIcon, "red-envelope") }
func AiFillRedditCircle() icons.IsIcon      { return newIcon(filledIcon, "reddit-circle") }
func AiFillRedditSquare() icons.IsIcon      { return newIcon(filledIcon, "reddit-square") }
func AiFillRest() icons.IsIcon              { return newIcon(filledIcon, "rest") }
func AiFillRightCircle() icons.IsIcon       { return newIcon(filledIcon, "right-circle") }
func AiFillRightSquare() icons.IsIcon       { return newIcon(filledIcon, "right-square") }
func AiFillRobot() icons.IsIcon             { return newIcon(filledIcon, "robot") }
func AiFillRocket() icons.IsIcon            { return newIcon(filledIcon, "rocket") }
func AiFillSafetyCertificate() icons.IsIcon { return newIcon(filledIcon, "safety-certificate") }
func AiFillSave() icons.IsIcon              { return newIcon(filledIcon, "save") }
func AiFillSchedule() icons.IsIcon          { return newIcon(filledIcon, "schedule") }
func AiFillSecurityScan() icons.IsIcon      { return newIcon(filledIcon, "security-scan") }
func AiFillSetting() icons.IsIcon           { return newIcon(filledIcon, "setting") }
func AiFillShop() icons.IsIcon              { return newIcon(filledIcon, "shop") }
func AiFillShopping() icons.IsIcon          { return newIcon(filledIcon, "shopping") }
func AiFillSignal() icons.IsIcon            { return newIcon(filledIcon, "signal") }
func AiFillSignature() icons.IsIcon         { return newIcon(filledIcon, "signature") }
func AiFillSketchCircle() icons.IsIcon      { return newIcon(filledIcon, "sketch-circle") }
func AiFillSketchSquare() icons.IsIcon      { return newIcon(filledIcon, "sketch-square") }
func AiFillSkin() icons.IsIcon              { return newIcon(filledIcon, "skin") }
func AiFillSkype() icons.IsIcon             { return newIcon(filledIcon, "skype") }
func AiFillSlackCircle() icons.IsIcon       { return newIcon(filledIcon, "slack-circle") }
func AiFillSlackSquare() icons.IsIcon       { return newIcon(filledIcon, "slack-square") }
func AiFillSliders() icons.IsIcon           { return newIcon(filledIcon, "sliders") }
func AiFillSmile() icons.IsIcon             { return newIcon(filledIcon, "smile") }
func AiFillSnippets() icons.IsIcon          { return newIcon(filledIcon, "snippets") }
func AiFillSound() icons.IsIcon             { return newIcon(filledIcon, "sound") }
func AiFillSpotify() icons.IsIcon           { return newIcon(filledIcon, "spotify") }
func AiFillStar() icons.IsIcon              { return newIcon(filledIcon, "star") }
func AiFillStepBackward() icons.IsIcon      { return newIcon(filledIcon, "step-backward") }
func AiFillStepForward() icons.IsIcon       { return newIcon(filledIcon, "step-forward") }
func AiFillStop() icons.IsIcon              { return newIcon(filledIcon, "stop") }
func AiFillSun() icons.IsIcon               { return newIcon(filledIcon, "sun") }
func AiFillSwitcher() icons.IsIcon          { return newIcon(filledIcon, "switcher") }
func AiFillTablet() icons.IsIcon            { return newIcon(filledIcon, "tablet") }
func AiFillTag() icons.IsIcon               { return newIcon(filledIcon, "tag") }
func AiFillTags() icons.IsIcon              { return newIcon(filledIcon, "tags") }
func AiFillTaobaoCircle() icons.IsIcon      { return newIcon(filledIcon, "taobao-circle") }
func AiFillTaobaoSquare() icons.IsIcon      { return newIcon(filledIcon, "taobao-square") }
func AiFillThunderbolt() icons.IsIcon       { return newIcon(filledIcon, "thunderbolt") }
func AiFillTikTok() icons.IsIcon            { return newIcon(filledIcon, "tik-tok") }
func AiFillTool() icons.IsIcon              { return newIcon(filledIcon, "tool") }
func AiFillTrademarkCircle() icons.IsIcon   { return newIcon(filledIcon, "trademark-circle") }
func AiFillTrophy() icons.IsIcon            { return newIcon(filledIcon, "trophy") }
func AiFillTruck() icons.IsIcon             { return newIcon(filledIcon, "truck") }
func AiFillTwitch() icons.IsIcon            { return newIcon(filledIcon, "twitch") }
func AiFillTwitterCircle() icons.IsIcon     { return newIcon(filledIcon, "twitter-circle") }
func AiFillTwitterSquare() icons.IsIcon     { return newIcon(filledIcon, "twitter-square") }
func AiFillUnlock() icons.IsIcon            { return newIcon(filledIcon, "unlock") }
func AiFillUpCircle() icons.IsIcon          { return newIcon(filledIcon, "up-circle") }
func AiFillUpSquare() icons.IsIcon          { return newIcon(filledIcon, "up-square") }
func AiFillUsb() icons.IsIcon               { return newIcon(filledIcon, "usb") }
func AiFillVideoCamera() icons.IsIcon       { return newIcon(filledIcon, "video-camera") }
func AiFillWallet() icons.IsIcon            { return newIcon(filledIcon, "wallet") }
func AiFillWarning() icons.IsIcon           { return newIcon(filledIcon, "warning") }
func AiFillWechatWork() icons.IsIcon        { return newIcon(filledIcon, "wechat-work") }
func AiFillWechat() icons.IsIcon            { return newIcon(filledIcon, "wechat") }
func AiFillWeiboCircle() icons.IsIcon       { return newIcon(filledIcon, "weibo-circle") }
func AiFillWeiboSquare() icons.IsIcon       { return newIcon(filledIcon, "weibo-square") }
func AiFillWindows() icons.IsIcon           { return newIcon(filledIcon, "windows") }
func AiFillX() icons.IsIcon                 { return newIcon(filledIcon, "x") }
func AiFillYahoo() icons.IsIcon             { return newIcon(filledIcon, "yahoo") }
func AiFillYoutube() icons.IsIcon           { return newIcon(filledIcon, "youtube") }
func AiFillYuque() icons.IsIcon             { return newIcon(filledIcon, "yuque") }
func AiFillZhihuCircle() icons.IsIcon       { return newIcon(filledIcon, "zhihu-circle") }
func AiFillZhihuSquare() icons.IsIcon       { return newIcon(filledIcon, "zhihu-square") }