package ai

import "github.com/raitucarp/gomix/icons"

func AiOutlineAccountBook() icons.IsIcon        { return newIcon(outlinedIcon, "account-book") }
func AiOutlineAim() icons.IsIcon                { return newIcon(outlinedIcon, "aim") }
func AiOutlineAlert() icons.IsIcon              { return newIcon(outlinedIcon, "alert") }
func AiOutlineAlibaba() icons.IsIcon            { return newIcon(outlinedIcon, "alibaba") }
func AiOutlineAlignCenter() icons.IsIcon        { return newIcon(outlinedIcon, "align-center") }
func AiOutlineAlignLeft() icons.IsIcon          { return newIcon(outlinedIcon, "align-left") }
func AiOutlineAlignRight() icons.IsIcon         { return newIcon(outlinedIcon, "align-right") }
func AiOutlineAlipayCircle() icons.IsIcon       { return newIcon(outlinedIcon, "alipay-circle") }
func AiOutlineAlipay() icons.IsIcon             { return newIcon(outlinedIcon, "alipay") }
func AiOutlineAliwangwang() icons.IsIcon        { return newIcon(outlinedIcon, "aliwangwang") }
func AiOutlineAliyun() icons.IsIcon             { return newIcon(outlinedIcon, "aliyun") }
func AiOutlineAmazon() icons.IsIcon             { return newIcon(outlinedIcon, "amazon") }
func AiOutlineAndroid() icons.IsIcon            { return newIcon(outlinedIcon, "android") }
func AiOutlineAntCloud() icons.IsIcon           { return newIcon(outlinedIcon, "ant-cloud") }
func AiOutlineAntDesign() icons.IsIcon          { return newIcon(outlinedIcon, "ant-design") }
func AiOutlineApartment() icons.IsIcon          { return newIcon(outlinedIcon, "apartment") }
func AiOutlineApi() icons.IsIcon                { return newIcon(outlinedIcon, "api") }
func AiOutlineApple() icons.IsIcon              { return newIcon(outlinedIcon, "apple") }
func AiOutlineAppstoreAdd() icons.IsIcon        { return newIcon(outlinedIcon, "appstore-add") }
func AiOutlineAppstore() icons.IsIcon           { return newIcon(outlinedIcon, "appstore") }
func AiOutlineAreaChart() icons.IsIcon          { return newIcon(outlinedIcon, "area-chart") }
func AiOutlineArrowDown() icons.IsIcon          { return newIcon(outlinedIcon, "arrow-down") }
func AiOutlineArrowLeft() icons.IsIcon          { return newIcon(outlinedIcon, "arrow-left") }
func AiOutlineArrowRight() icons.IsIcon         { return newIcon(outlinedIcon, "arrow-right") }
func AiOutlineArrowUp() icons.IsIcon            { return newIcon(outlinedIcon, "arrow-up") }
func AiOutlineArrowsAlt() icons.IsIcon          { return newIcon(outlinedIcon, "arrows-alt") }
func AiOutlineAudioMuted() icons.IsIcon         { return newIcon(outlinedIcon, "audio-muted") }
func AiOutlineAudio() icons.IsIcon              { return newIcon(outlinedIcon, "audio") }
func AiOutlineAudit() icons.IsIcon              { return newIcon(outlinedIcon, "audit") }
func AiOutlineBackward() icons.IsIcon           { return newIcon(outlinedIcon, "backward") }
func AiOutlineBaidu() icons.IsIcon              { return newIcon(outlinedIcon, "baidu") }
func AiOutlineBank() icons.IsIcon               { return newIcon(outlinedIcon, "bank") }
func AiOutlineBarChart() icons.IsIcon           { return newIcon(outlinedIcon, "bar-chart") }
func AiOutlineBarcode() icons.IsIcon            { return newIcon(outlinedIcon, "barcode") }
func AiOutlineBars() icons.IsIcon               { return newIcon(outlinedIcon, "bars") }
func AiOutlineBehanceSquare() icons.IsIcon      { return newIcon(outlinedIcon, "behance-square") }
func AiOutlineBehance() icons.IsIcon            { return newIcon(outlinedIcon, "behance") }
func AiOutlineBell() icons.IsIcon               { return newIcon(outlinedIcon, "bell") }
func AiOutlineBgColors() icons.IsIcon           { return newIcon(outlinedIcon, "bg-colors") }
func AiOutlineBilibili() icons.IsIcon           { return newIcon(outlinedIcon, "bilibili") }
func AiOutlineBlock() icons.IsIcon              { return newIcon(outlinedIcon, "block") }
func AiOutlineBold() icons.IsIcon               { return newIcon(outlinedIcon, "bold") }
func AiOutlineBook() icons.IsIcon               { return newIcon(outlinedIcon, "book") }
func AiOutlineBorderBottom() icons.IsIcon       { return newIcon(outlinedIcon, "border-bottom") }
func AiOutlineBorderHorizontal() icons.IsIcon   { return newIcon(outlinedIcon, "border-horizontal") }
func AiOutlineBorderInner() icons.IsIcon        { return newIcon(outlinedIcon, "border-inner") }
func AiOutlineBorderLeft() icons.IsIcon         { return newIcon(outlinedIcon, "border-left") }
func AiOutlineBorderOuter() icons.IsIcon        { return newIcon(outlinedIcon, "border-outer") }
func AiOutlineBorderRight() icons.IsIcon        { return newIcon(outlinedIcon, "border-right") }
func AiOutlineBorderTop() icons.IsIcon          { return newIcon(outlinedIcon, "border-top") }
func AiOutlineBorderVerticle() icons.IsIcon     { return newIcon(outlinedIcon, "border-verticle") }
func AiOutlineBorder() icons.IsIcon             { return newIcon(outlinedIcon, "border") }
func AiOutlineBorderlessTable() icons.IsIcon    { return newIcon(outlinedIcon, "borderless-table") }
func AiOutlineBoxPlot() icons.IsIcon            { return newIcon(outlinedIcon, "box-plot") }
func AiOutlineBranches() icons.IsIcon           { return newIcon(outlinedIcon, "branches") }
func AiOutlineBug() icons.IsIcon                { return newIcon(outlinedIcon, "bug") }
func AiOutlineBuild() icons.IsIcon              { return newIcon(outlinedIcon, "build") }
func AiOutlineBulb() icons.IsIcon               { return newIcon(outlinedIcon, "bulb") }
func AiOutlineCalculator() icons.IsIcon         { return newIcon(outlinedIcon, "calculator") }
func AiOutlineCalendar() icons.IsIcon           { return newIcon(outlinedIcon, "calendar") }
func AiOutlineCamera() icons.IsIcon             { return newIcon(outlinedIcon, "camera") }
func AiOutlineCar() icons.IsIcon                { return newIcon(outlinedIcon, "car") }
func AiOutlineCaretDown() icons.IsIcon          { return newIcon(outlinedIcon, "caret-down") }
func AiOutlineCaretLeft() icons.IsIcon          { return newIcon(outlinedIcon, "caret-left") }
func AiOutlineCaretRight() icons.IsIcon         { return newIcon(outlinedIcon, "caret-right") }
func AiOutlineCaretUp() icons.IsIcon            { return newIcon(outlinedIcon, "caret-up") }
func AiOutlineCarryOut() icons.IsIcon           { return newIcon(outlinedIcon, "carry-out") }
func AiOutlineCheckCircle() icons.IsIcon        { return newIcon(outlinedIcon, "check-circle") }
func AiOutlineCheckSquare() icons.IsIcon        { return newIcon(outlinedIcon, "check-square") }
func AiOutlineCheck() icons.IsIcon              { return newIcon(outlinedIcon, "check") }
func AiOutlineChrome() icons.IsIcon             { return newIcon(outlinedIcon, "chrome") }
func AiOutlineCiCircle() icons.IsIcon           { return newIcon(outlinedIcon, "ci-circle") }
func AiOutlineCi() icons.IsIcon                 { return newIcon(outlinedIcon, "ci") }
func AiOutlineClear() icons.IsIcon              { return newIcon(outlinedIcon, "clear") }
func AiOutlineClockCircle() icons.IsIcon        { return newIcon(outlinedIcon, "clock-circle") }
func AiOutlineCloseCircle() icons.IsIcon        { return newIcon(outlinedIcon, "close-circle") }
func AiOutlineCloseSquare() icons.IsIcon        { return newIcon(outlinedIcon, "close-square") }
func AiOutlineClose() icons.IsIcon              { return newIcon(outlinedIcon, "close") }
func AiOutlineCloudDownload() icons.IsIcon      { return newIcon(outlinedIcon, "cloud-download") }
func AiOutlineCloudServer() icons.IsIcon        { return newIcon(outlinedIcon, "cloud-server") }
func AiOutlineCloudSync() icons.IsIcon          { return newIcon(outlinedIcon, "cloud-sync") }
func AiOutlineCloudUpload() icons.IsIcon        { return newIcon(outlinedIcon, "cloud-upload") }
func AiOutlineCloud() icons.IsIcon              { return newIcon(outlinedIcon, "cloud") }
func AiOutlineCluster() icons.IsIcon            { return newIcon(outlinedIcon, "cluster") }
func AiOutlineCodeSandbox() icons.IsIcon        { return newIcon(outlinedIcon, "code-sandbox") }
func AiOutlineCode() icons.IsIcon               { return newIcon(outlinedIcon, "code") }
func AiOutlineCodepenCircle() icons.IsIcon      { return newIcon(outlinedIcon, "codepen-circle") }
func AiOutlineCodepen() icons.IsIcon            { return newIcon(outlinedIcon, "codepen") }
func AiOutlineCoffee() icons.IsIcon             { return newIcon(outlinedIcon, "coffee") }
func AiOutlineColumnHeight() icons.IsIcon       { return newIcon(outlinedIcon, "column-height") }
func AiOutlineColumnWidth() icons.IsIcon        { return newIcon(outlinedIcon, "column-width") }
func AiOutlineComment() icons.IsIcon            { return newIcon(outlinedIcon, "comment") }
func AiOutlineCompass() icons.IsIcon            { return newIcon(outlinedIcon, "compass") }
func AiOutlineCompress() icons.IsIcon           { return newIcon(outlinedIcon, "compress") }
func AiOutlineConsoleSql() icons.IsIcon         { return newIcon(outlinedIcon, "console-sql") }
func AiOutlineContacts() icons.IsIcon           { return newIcon(outlinedIcon, "contacts") }
func AiOutlineContainer() icons.IsIcon          { return newIcon(outlinedIcon, "container") }
func AiOutlineControl() icons.IsIcon            { return newIcon(outlinedIcon, "control") }
func AiOutlineCopy() icons.IsIcon               { return newIcon(outlinedIcon, "copy") }
func AiOutlineCopyrightCircle() icons.IsIcon    { return newIcon(outlinedIcon, "copyright-circle") }
func AiOutlineCopyright() icons.IsIcon          { return newIcon(outlinedIcon, "copyright") }
func AiOutlineCreditCard() icons.IsIcon         { return newIcon(outlinedIcon, "credit-card") }
func AiOutlineCrown() icons.IsIcon              { return newIcon(outlinedIcon, "crown") }
func AiOutlineCustomerService() icons.IsIcon    { return newIcon(outlinedIcon, "customer-service") }
func AiOutlineDash() icons.IsIcon               { return newIcon(outlinedIcon, "dash") }
func AiOutlineDashboard() icons.IsIcon          { return newIcon(outlinedIcon, "dashboard") }
func AiOutlineDatabase() icons.IsIcon           { return newIcon(outlinedIcon, "database") }
func AiOutlineDeleteColumn() icons.IsIcon       { return newIcon(outlinedIcon, "delete-column") }
func AiOutlineDeleteRow() icons.IsIcon          { return newIcon(outlinedIcon, "delete-row") }
func AiOutlineDelete() icons.IsIcon             { return newIcon(outlinedIcon, "delete") }
func AiOutlineDeliveredProcedure() icons.IsIcon { return newIcon(outlinedIcon, "delivered-procedure") }
func AiOutlineDeploymentUnit() icons.IsIcon     { return newIcon(outlinedIcon, "deployment-unit") }
func AiOutlineDesktop() icons.IsIcon            { return newIcon(outlinedIcon, "desktop") }
func AiOutlineDiff() icons.IsIcon               { return newIcon(outlinedIcon, "diff") }
func AiOutlineDingding() icons.IsIcon           { return newIcon(outlinedIcon, "dingding") }
func AiOutlineDingtalk() icons.IsIcon           { return newIcon(outlinedIcon, "dingtalk") }
func AiOutlineDisconnect() icons.IsIcon         { return newIcon(outlinedIcon, "disconnect") }
func AiOutlineDiscord() icons.IsIcon            { return newIcon(outlinedIcon, "discord") }
func AiOutlineDislike() icons.IsIcon            { return newIcon(outlinedIcon, "dislike") }
func AiOutlineDocker() icons.IsIcon             { return newIcon(outlinedIcon, "docker") }
func AiOutlineDollarCircle() icons.IsIcon       { return newIcon(outlinedIcon, "dollar-circle") }
func AiOutlineDollar() icons.IsIcon             { return newIcon(outlinedIcon, "dollar") }
func AiOutlineDotChart() icons.IsIcon           { return newIcon(outlinedIcon, "dot-chart") }
func AiOutlineDotNet() icons.IsIcon             { return newIcon(outlinedIcon, "dot-net") }
func AiOutlineDoubleLeft() icons.IsIcon         { return newIcon(outlinedIcon, "double-left") }
func AiOutlineDoubleRight() icons.IsIcon        { return newIcon(outlinedIcon, "double-right") }
func AiOutlineDownCircle() icons.IsIcon         { return newIcon(outlinedIcon, "down-circle") }
func AiOutlineDownSquare() icons.IsIcon         { return newIcon(outlinedIcon, "down-square") }
func AiOutlineDown() icons.IsIcon               { return newIcon(outlinedIcon, "down") }
func AiOutlineDownload() icons.IsIcon           { return newIcon(outlinedIcon, "download") }
func AiOutlineDrag() icons.IsIcon               { return newIcon(outlinedIcon, "drag") }
func AiOutlineDribbbleSquare() icons.IsIcon     { return newIcon(outlinedIcon, "dribbble-square") }
func AiOutlineDribbble() icons.IsIcon           { return newIcon(outlinedIcon, "dribbble") }
func AiOutlineDropbox() icons.IsIcon            { return newIcon(outlinedIcon, "dropbox") }
func AiOutlineEdit() icons.IsIcon               { return newIcon(outlinedIcon, "edit") }
func AiOutlineEllipsis() icons.IsIcon           { return newIcon(outlinedIcon, "ellipsis") }
func AiOutlineEnter() icons.IsIcon              { return newIcon(outlinedIcon, "enter") }
func AiOutlineEnvironment() icons.IsIcon        { return newIcon(outlinedIcon, "environment") }
func AiOutlineEuroCircle() icons.IsIcon         { return newIcon(outlinedIcon, "euro-circle") }
func AiOutlineEuro() icons.IsIcon               { return newIcon(outlinedIcon, "euro") }
func AiOutlineException() icons.IsIcon          { return newIcon(outlinedIcon, "exception") }
func AiOutlineExclamationCircle() icons.IsIcon  { return newIcon(outlinedIcon, "exclamation-circle") }
func AiOutlineExclamation() icons.IsIcon        { return newIcon(outlinedIcon, "exclamation") }
func AiOutlineExpandAlt() icons.IsIcon          { return newIcon(outlinedIcon, "expand-alt") }
func AiOutlineExpand() icons.IsIcon             { return newIcon(outlinedIcon, "expand") }
func AiOutlineExperiment() icons.IsIcon         { return newIcon(outlinedIcon, "experiment") }
func AiOutlineExport() icons.IsIcon             { return newIcon(outlinedIcon, "export") }
func AiOutlineEyeInvisible() icons.IsIcon       { return newIcon(outlinedIcon, "eye-invisible") }
func AiOutlineEye() icons.IsIcon                { return newIcon(outlinedIcon, "eye") }
func AiOutlineFacebook() icons.IsIcon           { return newIcon(outlinedIcon, "facebook") }
func AiOutlineFall() icons.IsIcon               { return newIcon(outlinedIcon, "fall") }
func AiOutlineFastBackward() icons.IsIcon       { return newIcon(outlinedIcon, "fast-backward") }
func AiOutlineFastForward() icons.IsIcon        { return newIcon(outlinedIcon, "fast-forward") }
func AiOutlineFieldBinary() icons.IsIcon        { return newIcon(outlinedIcon, "field-binary") }
func AiOutlineFieldNumber() icons.IsIcon        { return newIcon(outlinedIcon, "field-number") }
func AiOutlineFieldString() icons.IsIcon        { return newIcon(outlinedIcon, "field-string") }
func AiOutlineFieldTime() icons.IsIcon          { return newIcon(outlinedIcon, "field-time") }
func AiOutlineFileAdd() icons.IsIcon            { return newIcon(outlinedIcon, "file-add") }
func AiOutlineFileDone() icons.IsIcon           { return newIcon(outlinedIcon, "file-done") }
func AiOutlineFileExcel() icons.IsIcon          { return newIcon(outlinedIcon, "file-excel") }
func AiOutlineFileExclamation() icons.IsIcon    { return newIcon(outlinedIcon, "file-exclamation") }
func AiOutlineFileGif() icons.IsIcon            { return newIcon(outlinedIcon, "file-gif") }
func AiOutlineFileImage() icons.IsIcon          { return newIcon(outlinedIcon, "file-image") }
func AiOutlineFileJpg() icons.IsIcon            { return newIcon(outlinedIcon, "file-jpg") }
func AiOutlineFileMarkdown() icons.IsIcon       { return newIcon(outlinedIcon, "file-markdown") }
func AiOutlineFilePdf() icons.IsIcon            { return newIcon(outlinedIcon, "file-pdf") }
func AiOutlineFilePpt() icons.IsIcon            { return newIcon(outlinedIcon, "file-ppt") }
func AiOutlineFileProtect() icons.IsIcon        { return newIcon(outlinedIcon, "file-protect") }
func AiOutlineFileSearch() icons.IsIcon         { return newIcon(outlinedIcon, "file-search") }
func AiOutlineFileSync() icons.IsIcon           { return newIcon(outlinedIcon, "file-sync") }
func AiOutlineFileText() icons.IsIcon           { return newIcon(outlinedIcon, "file-text") }
func AiOutlineFileUnknown() icons.IsIcon        { return newIcon(outlinedIcon, "file-unknown") }
func AiOutlineFileWord() icons.IsIcon           { return newIcon(outlinedIcon, "file-word") }
func AiOutlineFileZip() icons.IsIcon            { return newIcon(outlinedIcon, "file-zip") }
func AiOutlineFile() icons.IsIcon               { return newIcon(outlinedIcon, "file") }
func AiOutlineFilter() icons.IsIcon             { return newIcon(outlinedIcon, "filter") }
func AiOutlineFire() icons.IsIcon               { return newIcon(outlinedIcon, "fire") }
func AiOutlineFlag() icons.IsIcon               { return newIcon(outlinedIcon, "flag") }
func AiOutlineFolderAdd() icons.IsIcon          { return newIcon(outlinedIcon, "folder-add") }
func AiOutlineFolderOpen() icons.IsIcon         { return newIcon(outlinedIcon, "folder-open") }
func AiOutlineFolderView() icons.IsIcon         { return newIcon(outlinedIcon, "folder-view") }
func AiOutlineFolder() icons.IsIcon             { return newIcon(outlinedIcon, "folder") }
func AiOutlineFontColors() icons.IsIcon         { return newIcon(outlinedIcon, "font-colors") }
func AiOutlineFontSize() icons.IsIcon           { return newIcon(outlinedIcon, "font-size") }
func AiOutlineFork() icons.IsIcon               { return newIcon(outlinedIcon, "fork") }
func AiOutlineForm() icons.IsIcon               { return newIcon(outlinedIcon, "form") }
func AiOutlineFormatPainter() icons.IsIcon      { return newIcon(outlinedIcon, "format-painter") }
func AiOutlineForward() icons.IsIcon            { return newIcon(outlinedIcon, "forward") }
func AiOutlineFrown() icons.IsIcon              { return newIcon(outlinedIcon, "frown") }
func AiOutlineFullscreenExit() icons.IsIcon     { return newIcon(outlinedIcon, "fullscreen-exit") }
func AiOutlineFullscreen() icons.IsIcon         { return newIcon(outlinedIcon, "fullscreen") }
func AiOutlineFunction() icons.IsIcon           { return newIcon(outlinedIcon, "function") }
func AiOutlineFundProjectionScreen() icons.IsIcon {
	return newIcon(outlinedIcon, "fund-projection-screen")
}
func AiOutlineFundView() icons.IsIcon          { return newIcon(outlinedIcon, "fund-view") }
func AiOutlineFund() icons.IsIcon              { return newIcon(outlinedIcon, "fund") }
func AiOutlineFunnelPlot() icons.IsIcon        { return newIcon(outlinedIcon, "funnel-plot") }
func AiOutlineGateway() icons.IsIcon           { return newIcon(outlinedIcon, "gateway") }
func AiOutlineGif() icons.IsIcon               { return newIcon(outlinedIcon, "gif") }
func AiOutlineGift() icons.IsIcon              { return newIcon(outlinedIcon, "gift") }
func AiOutlineGithub() icons.IsIcon            { return newIcon(outlinedIcon, "github") }
func AiOutlineGitlab() icons.IsIcon            { return newIcon(outlinedIcon, "gitlab") }
func AiOutlineGlobal() icons.IsIcon            { return newIcon(outlinedIcon, "global") }
func AiOutlineGold() icons.IsIcon              { return newIcon(outlinedIcon, "gold") }
func AiOutlineGooglePlus() icons.IsIcon        { return newIcon(outlinedIcon, "google-plus") }
func AiOutlineGoogle() icons.IsIcon            { return newIcon(outlinedIcon, "google") }
func AiOutlineGroup() icons.IsIcon             { return newIcon(outlinedIcon, "group") }
func AiOutlineHarmonyOS() icons.IsIcon         { return newIcon(outlinedIcon, "harmony-o-s") }
func AiOutlineHdd() icons.IsIcon               { return newIcon(outlinedIcon, "hdd") }
func AiOutlineHeart() icons.IsIcon             { return newIcon(outlinedIcon, "heart") }
func AiOutlineHeatMap() icons.IsIcon           { return newIcon(outlinedIcon, "heat-map") }
func AiOutlineHighlight() icons.IsIcon         { return newIcon(outlinedIcon, "highlight") }
func AiOutlineHistory() icons.IsIcon           { return newIcon(outlinedIcon, "history") }
func AiOutlineHolder() icons.IsIcon            { return newIcon(outlinedIcon, "holder") }
func AiOutlineHome() icons.IsIcon              { return newIcon(outlinedIcon, "home") }
func AiOutlineHourglass() icons.IsIcon         { return newIcon(outlinedIcon, "hourglass") }
func AiOutlineHtml5() icons.IsIcon             { return newIcon(outlinedIcon, "html5") }
func AiOutlineIdcard() icons.IsIcon            { return newIcon(outlinedIcon, "idcard") }
func AiOutlineIe() icons.IsIcon                { return newIcon(outlinedIcon, "ie") }
func AiOutlineImport() icons.IsIcon            { return newIcon(outlinedIcon, "import") }
func AiOutlineInbox() icons.IsIcon             { return newIcon(outlinedIcon, "inbox") }
func AiOutlineInfoCircle() icons.IsIcon        { return newIcon(outlinedIcon, "info-circle") }
func AiOutlineInfo() icons.IsIcon              { return newIcon(outlinedIcon, "info") }
func AiOutlineInsertRowAbove() icons.IsIcon    { return newIcon(outlinedIcon, "insert-row-above") }
func AiOutlineInsertRowBelow() icons.IsIcon    { return newIcon(outlinedIcon, "insert-row-below") }
func AiOutlineInsertRowLeft() icons.IsIcon     { return newIcon(outlinedIcon, "insert-row-left") }
func AiOutlineInsertRowRight() icons.IsIcon    { return newIcon(outlinedIcon, "insert-row-right") }
func AiOutlineInstagram() icons.IsIcon         { return newIcon(outlinedIcon, "instagram") }
func AiOutlineInsurance() icons.IsIcon         { return newIcon(outlinedIcon, "insurance") }
func AiOutlineInteraction() icons.IsIcon       { return newIcon(outlinedIcon, "interaction") }
func AiOutlineIssuesClose() icons.IsIcon       { return newIcon(outlinedIcon, "issues-close") }
func AiOutlineItalic() icons.IsIcon            { return newIcon(outlinedIcon, "italic") }
func AiOutlineJavaScript() icons.IsIcon        { return newIcon(outlinedIcon, "java-script") }
func AiOutlineJava() icons.IsIcon              { return newIcon(outlinedIcon, "java") }
func AiOutlineKey() icons.IsIcon               { return newIcon(outlinedIcon, "key") }
func AiOutlineKubernetes() icons.IsIcon        { return newIcon(outlinedIcon, "kubernetes") }
func AiOutlineLaptop() icons.IsIcon            { return newIcon(outlinedIcon, "laptop") }
func AiOutlineLayout() icons.IsIcon            { return newIcon(outlinedIcon, "layout") }
func AiOutlineLeftCircle() icons.IsIcon        { return newIcon(outlinedIcon, "left-circle") }
func AiOutlineLeftSquare() icons.IsIcon        { return newIcon(outlinedIcon, "left-square") }
func AiOutlineLeft() icons.IsIcon              { return newIcon(outlinedIcon, "left") }
func AiOutlineLike() icons.IsIcon              { return newIcon(outlinedIcon, "like") }
func AiOutlineLineChart() icons.IsIcon         { return newIcon(outlinedIcon, "line-chart") }
func AiOutlineLineHeight() icons.IsIcon        { return newIcon(outlinedIcon, "line-height") }
func AiOutlineLine() icons.IsIcon              { return newIcon(outlinedIcon, "line") }
func AiOutlineLink() icons.IsIcon              { return newIcon(outlinedIcon, "link") }
func AiOutlineLinkedin() icons.IsIcon          { return newIcon(outlinedIcon, "linkedin") }
func AiOutlineLinux() icons.IsIcon             { return newIcon(outlinedIcon, "linux") }
func AiOutlineLoading3Quarters() icons.IsIcon  { return newIcon(outlinedIcon, "loading-3-quarters") }
func AiOutlineLoading() icons.IsIcon           { return newIcon(outlinedIcon, "loading") }
func AiOutlineLock() icons.IsIcon              { return newIcon(outlinedIcon, "lock") }
func AiOutlineLogin() icons.IsIcon             { return newIcon(outlinedIcon, "login") }
func AiOutlineLogout() icons.IsIcon            { return newIcon(outlinedIcon, "logout") }
func AiOutlineMacCommand() icons.IsIcon        { return newIcon(outlinedIcon, "mac-command") }
func AiOutlineMail() icons.IsIcon              { return newIcon(outlinedIcon, "mail") }
func AiOutlineMan() icons.IsIcon               { return newIcon(outlinedIcon, "man") }
func AiOutlineMedicineBox() icons.IsIcon       { return newIcon(outlinedIcon, "medicine-box") }
func AiOutlineMediumWorkmark() icons.IsIcon    { return newIcon(outlinedIcon, "medium-workmark") }
func AiOutlineMedium() icons.IsIcon            { return newIcon(outlinedIcon, "medium") }
func AiOutlineMeh() icons.IsIcon               { return newIcon(outlinedIcon, "meh") }
func AiOutlineMenuFold() icons.IsIcon          { return newIcon(outlinedIcon, "menu-fold") }
func AiOutlineMenuUnfold() icons.IsIcon        { return newIcon(outlinedIcon, "menu-unfold") }
func AiOutlineMenu() icons.IsIcon              { return newIcon(outlinedIcon, "menu") }
func AiOutlineMergeCells() icons.IsIcon        { return newIcon(outlinedIcon, "merge-cells") }
func AiOutlineMerge() icons.IsIcon             { return newIcon(outlinedIcon, "merge") }
func AiOutlineMessage() icons.IsIcon           { return newIcon(outlinedIcon, "message") }
func AiOutlineMinusCircle() icons.IsIcon       { return newIcon(outlinedIcon, "minus-circle") }
func AiOutlineMinusSquare() icons.IsIcon       { return newIcon(outlinedIcon, "minus-square") }
func AiOutlineMinus() icons.IsIcon             { return newIcon(outlinedIcon, "minus") }
func AiOutlineMobile() icons.IsIcon            { return newIcon(outlinedIcon, "mobile") }
func AiOutlineMoneyCollect() icons.IsIcon      { return newIcon(outlinedIcon, "money-collect") }
func AiOutlineMonitor() icons.IsIcon           { return newIcon(outlinedIcon, "monitor") }
func AiOutlineMoon() icons.IsIcon              { return newIcon(outlinedIcon, "moon") }
func AiOutlineMore() icons.IsIcon              { return newIcon(outlinedIcon, "more") }
func AiOutlineMuted() icons.IsIcon             { return newIcon(outlinedIcon, "muted") }
func AiOutlineNodeCollapse() icons.IsIcon      { return newIcon(outlinedIcon, "node-collapse") }
func AiOutlineNodeExpand() icons.IsIcon        { return newIcon(outlinedIcon, "node-expand") }
func AiOutlineNodeIndex() icons.IsIcon         { return newIcon(outlinedIcon, "node-index") }
func AiOutlineNotification() icons.IsIcon      { return newIcon(outlinedIcon, "notification") }
func AiOutlineNumber() icons.IsIcon            { return newIcon(outlinedIcon, "number") }
func AiOutlineOneToOne() icons.IsIcon          { return newIcon(outlinedIcon, "one-to-one") }
func AiOutlineOpenAI() icons.IsIcon            { return newIcon(outlinedIcon, "open-a-i") }
func AiOutlineOrderedList() icons.IsIcon       { return newIcon(outlinedIcon, "ordered-list") }
func AiOutlinePaperClip() icons.IsIcon         { return newIcon(outlinedIcon, "paper-clip") }
func AiOutlinePartition() icons.IsIcon         { return newIcon(outlinedIcon, "partition") }
func AiOutlinePauseCircle() icons.IsIcon       { return newIcon(outlinedIcon, "pause-circle") }
func AiOutlinePause() icons.IsIcon             { return newIcon(outlinedIcon, "pause") }
func AiOutlinePayCircle() icons.IsIcon         { return newIcon(outlinedIcon, "pay-circle") }
func AiOutlinePercentage() icons.IsIcon        { return newIcon(outlinedIcon, "percentage") }
func AiOutlinePhone() icons.IsIcon             { return newIcon(outlinedIcon, "phone") }
func AiOutlinePicCenter() icons.IsIcon         { return newIcon(outlinedIcon, "pic-center") }
func AiOutlinePicLeft() icons.IsIcon           { return newIcon(outlinedIcon, "pic-left") }
func AiOutlinePicRight() icons.IsIcon          { return newIcon(outlinedIcon, "pic-right") }
func AiOutlinePicture() icons.IsIcon           { return newIcon(outlinedIcon, "picture") }
func AiOutlinePieChart() icons.IsIcon          { return newIcon(outlinedIcon, "pie-chart") }
func AiOutlinePinterest() icons.IsIcon         { return newIcon(outlinedIcon, "pinterest") }
func AiOutlinePlayCircle() icons.IsIcon        { return newIcon(outlinedIcon, "play-circle") }
func AiOutlinePlaySquare() icons.IsIcon        { return newIcon(outlinedIcon, "play-square") }
func AiOutlinePlusCircle() icons.IsIcon        { return newIcon(outlinedIcon, "plus-circle") }
func AiOutlinePlusSquare() icons.IsIcon        { return newIcon(outlinedIcon, "plus-square") }
func AiOutlinePlus() icons.IsIcon              { return newIcon(outlinedIcon, "plus") }
func AiOutlinePoundCircle() icons.IsIcon       { return newIcon(outlinedIcon, "pound-circle") }
func AiOutlinePound() icons.IsIcon             { return newIcon(outlinedIcon, "pound") }
func AiOutlinePoweroff() icons.IsIcon          { return newIcon(outlinedIcon, "poweroff") }
func AiOutlinePrinter() icons.IsIcon           { return newIcon(outlinedIcon, "printer") }
func AiOutlineProduct() icons.IsIcon           { return newIcon(outlinedIcon, "product") }
func AiOutlineProfile() icons.IsIcon           { return newIcon(outlinedIcon, "profile") }
func AiOutlineProject() icons.IsIcon           { return newIcon(outlinedIcon, "project") }
func AiOutlinePropertySafety() icons.IsIcon    { return newIcon(outlinedIcon, "property-safety") }
func AiOutlinePullRequest() icons.IsIcon       { return newIcon(outlinedIcon, "pull-request") }
func AiOutlinePushpin() icons.IsIcon           { return newIcon(outlinedIcon, "pushpin") }
func AiOutlinePython() icons.IsIcon            { return newIcon(outlinedIcon, "python") }
func AiOutlineQq() icons.IsIcon                { return newIcon(outlinedIcon, "qq") }
func AiOutlineQrcode() icons.IsIcon            { return newIcon(outlinedIcon, "qrcode") }
func AiOutlineQuestionCircle() icons.IsIcon    { return newIcon(outlinedIcon, "question-circle") }
func AiOutlineQuestion() icons.IsIcon          { return newIcon(outlinedIcon, "question") }
func AiOutlineRadarChart() icons.IsIcon        { return newIcon(outlinedIcon, "radar-chart") }
func AiOutlineRadiusBottomleft() icons.IsIcon  { return newIcon(outlinedIcon, "radius-bottomleft") }
func AiOutlineRadiusBottomright() icons.IsIcon { return newIcon(outlinedIcon, "radius-bottomright") }
func AiOutlineRadiusSetting() icons.IsIcon     { return newIcon(outlinedIcon, "radius-setting") }
func AiOutlineRadiusUpleft() icons.IsIcon      { return newIcon(outlinedIcon, "radius-upleft") }
func AiOutlineRadiusUpright() icons.IsIcon     { return newIcon(outlinedIcon, "radius-upright") }
func AiOutlineRead() icons.IsIcon              { return newIcon(outlinedIcon, "read") }
func AiOutlineReconciliation() icons.IsIcon    { return newIcon(outlinedIcon, "reconciliation") }
func AiOutlineRedEnvelope() icons.IsIcon       { return newIcon(outlinedIcon, "red-envelope") }
func AiOutlineReddit() icons.IsIcon            { return newIcon(outlinedIcon, "reddit") }
func AiOutlineRedo() icons.IsIcon              { return newIcon(outlinedIcon, "redo") }
func AiOutlineReload() icons.IsIcon            { return newIcon(outlinedIcon, "reload") }
func AiOutlineRest() icons.IsIcon              { return newIcon(outlinedIcon, "rest") }
func AiOutlineRetweet() icons.IsIcon           { return newIcon(outlinedIcon, "retweet") }
func AiOutlineRightCircle() icons.IsIcon       { return newIcon(outlinedIcon, "right-circle") }
func AiOutlineRightSquare() icons.IsIcon       { return newIcon(outlinedIcon, "right-square") }
func AiOutlineRight() icons.IsIcon             { return newIcon(outlinedIcon, "right") }
func AiOutlineRise() icons.IsIcon              { return newIcon(outlinedIcon, "rise") }
func AiOutlineRobot() icons.IsIcon             { return newIcon(outlinedIcon, "robot") }
func AiOutlineRocket() icons.IsIcon            { return newIcon(outlinedIcon, "rocket") }
func AiOutlineRollback() icons.IsIcon          { return newIcon(outlinedIcon, "rollback") }
func AiOutlineRotateLeft() icons.IsIcon        { return newIcon(outlinedIcon, "rotate-left") }
func AiOutlineRotateRight() icons.IsIcon       { return newIcon(outlinedIcon, "rotate-right") }
func AiOutlineRuby() icons.IsIcon              { return newIcon(outlinedIcon, "ruby") }
func AiOutlineSafetyCertificate() icons.IsIcon { return newIcon(outlinedIcon, "safety-certificate") }
func AiOutlineSafety() icons.IsIcon            { return newIcon(outlinedIcon, "safety") }
func AiOutlineSave() icons.IsIcon              { return newIcon(outlinedIcon, "save") }
func AiOutlineScan() icons.IsIcon              { return newIcon(outlinedIcon, "scan") }
func AiOutlineSchedule() icons.IsIcon          { return newIcon(outlinedIcon, "schedule") }
func AiOutlineScissor() icons.IsIcon           { return newIcon(outlinedIcon, "scissor") }
func AiOutlineSearch() icons.IsIcon            { return newIcon(outlinedIcon, "search") }
func AiOutlineSecurityScan() icons.IsIcon      { return newIcon(outlinedIcon, "security-scan") }
func AiOutlineSelect() icons.IsIcon            { return newIcon(outlinedIcon, "select") }
func AiOutlineSend() icons.IsIcon              { return newIcon(outlinedIcon, "send") }
func AiOutlineSetting() icons.IsIcon           { return newIcon(outlinedIcon, "setting") }
func AiOutlineShake() icons.IsIcon             { return newIcon(outlinedIcon, "shake") }
func AiOutlineShareAlt() icons.IsIcon          { return newIcon(outlinedIcon, "share-alt") }
func AiOutlineShop() icons.IsIcon              { return newIcon(outlinedIcon, "shop") }
func AiOutlineShoppingCart() icons.IsIcon      { return newIcon(outlinedIcon, "shopping-cart") }
func AiOutlineShopping() icons.IsIcon          { return newIcon(outlinedIcon, "shopping") }
func AiOutlineShrink() icons.IsIcon            { return newIcon(outlinedIcon, "shrink") }
func AiOutlineSignature() icons.IsIcon         { return newIcon(outlinedIcon, "signature") }
func AiOutlineSisternode() icons.IsIcon        { return newIcon(outlinedIcon, "sisternode") }
func AiOutlineSketch() icons.IsIcon            { return newIcon(outlinedIcon, "sketch") }
func AiOutlineSkin() icons.IsIcon              { return newIcon(outlinedIcon, "skin") }
func AiOutlineSkype() icons.IsIcon             { return newIcon(outlinedIcon, "skype") }
func AiOutlineSlackSquare() icons.IsIcon       { return newIcon(outlinedIcon, "slack-square") }
func AiOutlineSlack() icons.IsIcon             { return newIcon(outlinedIcon, "slack") }
func AiOutlineSliders() icons.IsIcon           { return newIcon(outlinedIcon, "sliders") }
func AiOutlineSmallDash() icons.IsIcon         { return newIcon(outlinedIcon, "small-dash") }
func AiOutlineSmile() icons.IsIcon             { return newIcon(outlinedIcon, "smile") }
func AiOutlineSnippets() icons.IsIcon          { return newIcon(outlinedIcon, "snippets") }
func AiOutlineSolution() icons.IsIcon          { return newIcon(outlinedIcon, "solution") }
func AiOutlineSortAscending() icons.IsIcon     { return newIcon(outlinedIcon, "sort-ascending") }
func AiOutlineSortDescending() icons.IsIcon    { return newIcon(outlinedIcon, "sort-descending") }
func AiOutlineSound() icons.IsIcon             { return newIcon(outlinedIcon, "sound") }
func AiOutlineSplitCells() icons.IsIcon        { return newIcon(outlinedIcon, "split-cells") }
func AiOutlineSpotify() icons.IsIcon           { return newIcon(outlinedIcon, "spotify") }
func AiOutlineStar() icons.IsIcon              { return newIcon(outlinedIcon, "star") }
func AiOutlineStepBackward() icons.IsIcon      { return newIcon(outlinedIcon, "step-backward") }
func AiOutlineStepForward() icons.IsIcon       { return newIcon(outlinedIcon, "step-forward") }
func AiOutlineStock() icons.IsIcon             { return newIcon(outlinedIcon, "stock") }
func AiOutlineStop() icons.IsIcon              { return newIcon(outlinedIcon, "stop") }
func AiOutlineStrikethrough() icons.IsIcon     { return newIcon(outlinedIcon, "strikethrough") }
func AiOutlineSubnode() icons.IsIcon           { return newIcon(outlinedIcon, "subnode") }
func AiOutlineSun() icons.IsIcon               { return newIcon(outlinedIcon, "sun") }
func AiOutlineSwapLeft() icons.IsIcon          { return newIcon(outlinedIcon, "swap-left") }
func AiOutlineSwapRight() icons.IsIcon         { return newIcon(outlinedIcon, "swap-right") }
func AiOutlineSwap() icons.IsIcon              { return newIcon(outlinedIcon, "swap") }
func AiOutlineSwitcher() icons.IsIcon          { return newIcon(outlinedIcon, "switcher") }
func AiOutlineSync() icons.IsIcon              { return newIcon(outlinedIcon, "sync") }
func AiOutlineTable() icons.IsIcon             { return newIcon(outlinedIcon, "table") }
func AiOutlineTablet() icons.IsIcon            { return newIcon(outlinedIcon, "tablet") }
func AiOutlineTag() icons.IsIcon               { return newIcon(outlinedIcon, "tag") }
func AiOutlineTags() icons.IsIcon              { return newIcon(outlinedIcon, "tags") }
func AiOutlineTaobaoCircle() icons.IsIcon      { return newIcon(outlinedIcon, "taobao-circle") }
func AiOutlineTaobao() icons.IsIcon            { return newIcon(outlinedIcon, "taobao") }
func AiOutlineTeam() icons.IsIcon              { return newIcon(outlinedIcon, "team") }
func AiOutlineThunderbolt() icons.IsIcon       { return newIcon(outlinedIcon, "thunderbolt") }
func AiOutlineTikTok() icons.IsIcon            { return newIcon(outlinedIcon, "tik-tok") }
func AiOutlineToTop() icons.IsIcon             { return newIcon(outlinedIcon, "to-top") }
func AiOutlineTool() icons.IsIcon              { return newIcon(outlinedIcon, "tool") }
func AiOutlineTrademarkCircle() icons.IsIcon   { return newIcon(outlinedIcon, "trademark-circle") }
func AiOutlineTrademark() icons.IsIcon         { return newIcon(outlinedIcon, "trademark") }
func AiOutlineTransaction() icons.IsIcon       { return newIcon(outlinedIcon, "transaction") }
func AiOutlineTranslation() icons.IsIcon       { return newIcon(outlinedIcon, "translation") }
func AiOutlineTrophy() icons.IsIcon            { return newIcon(outlinedIcon, "trophy") }
func AiOutlineTruck() icons.IsIcon             { return newIcon(outlinedIcon, "truck") }
func AiOutlineTwitch() icons.IsIcon            { return newIcon(outlinedIcon, "twitch") }
func AiOutlineTwitter() icons.IsIcon           { return newIcon(outlinedIcon, "twitter") }
func AiOutlineUnderline() icons.IsIcon         { return newIcon(outlinedIcon, "underline") }
func AiOutlineUndo() icons.IsIcon              { return newIcon(outlinedIcon, "undo") }
func AiOutlineUngroup() icons.IsIcon           { return newIcon(outlinedIcon, "ungroup") }
func AiOutlineUnlock() icons.IsIcon            { return newIcon(outlinedIcon, "unlock") }
func AiOutlineUnorderedList() icons.IsIcon     { return newIcon(outlinedIcon, "unordered-list") }
func AiOutlineUpCircle() icons.IsIcon          { return newIcon(outlinedIcon, "up-circle") }
func AiOutlineUpSquare() icons.IsIcon          { return newIcon(outlinedIcon, "up-square") }
func AiOutlineUp() icons.IsIcon                { return newIcon(outlinedIcon, "up") }
func AiOutlineUpload() icons.IsIcon            { return newIcon(outlinedIcon, "upload") }
func AiOutlineUsb() icons.IsIcon               { return newIcon(outlinedIcon, "usb") }
func AiOutlineUserAdd() icons.IsIcon           { return newIcon(outlinedIcon, "user-add") }
func AiOutlineUserDelete() icons.IsIcon        { return newIcon(outlinedIcon, "user-delete") }
func AiOutlineUserSwitch() icons.IsIcon        { return newIcon(outlinedIcon, "user-switch") }
func AiOutlineUser() icons.IsIcon              { return newIcon(outlinedIcon, "user") }
func AiOutlineUsergroupAdd() icons.IsIcon      { return newIcon(outlinedIcon, "usergroup-add") }
func AiOutlineUsergroupDelete() icons.IsIcon   { return newIcon(outlinedIcon, "usergroup-delete") }
func AiOutlineVerified() icons.IsIcon          { return newIcon(outlinedIcon, "verified") }
func AiOutlineVerticalAlignBottom() icons.IsIcon {
	return newIcon(outlinedIcon, "vertical-align-bottom")
}
func AiOutlineVerticalAlignMiddle() icons.IsIcon {
	return newIcon(outlinedIcon, "vertical-align-middle")
}
func AiOutlineVerticalAlignTop() icons.IsIcon { return newIcon(outlinedIcon, "vertical-align-top") }
func AiOutlineVerticalLeft() icons.IsIcon     { return newIcon(outlinedIcon, "vertical-left") }
func AiOutlineVerticalRight() icons.IsIcon    { return newIcon(outlinedIcon, "vertical-right") }
func AiOutlineVideoCameraAdd() icons.IsIcon   { return newIcon(outlinedIcon, "video-camera-add") }
func AiOutlineVideoCamera() icons.IsIcon      { return newIcon(outlinedIcon, "video-camera") }
func AiOutlineWallet() icons.IsIcon           { return newIcon(outlinedIcon, "wallet") }
func AiOutlineWarning() icons.IsIcon          { return newIcon(outlinedIcon, "warning") }
func AiOutlineWechatWork() icons.IsIcon       { return newIcon(outlinedIcon, "wechat-work") }
func AiOutlineWechat() icons.IsIcon           { return newIcon(outlinedIcon, "wechat") }
func AiOutlineWeiboCircle() icons.IsIcon      { return newIcon(outlinedIcon, "weibo-circle") }
func AiOutlineWeiboSquare() icons.IsIcon      { return newIcon(outlinedIcon, "weibo-square") }
func AiOutlineWeibo() icons.IsIcon            { return newIcon(outlinedIcon, "weibo") }
func AiOutlineWhatsApp() icons.IsIcon         { return newIcon(outlinedIcon, "whats-app") }
func AiOutlineWifi() icons.IsIcon             { return newIcon(outlinedIcon, "wifi") }
func AiOutlineWindows() icons.IsIcon          { return newIcon(outlinedIcon, "windows") }
func AiOutlineWoman() icons.IsIcon            { return newIcon(outlinedIcon, "woman") }
func AiOutlineX() icons.IsIcon                { return newIcon(outlinedIcon, "x") }
func AiOutlineYahoo() icons.IsIcon            { return newIcon(outlinedIcon, "yahoo") }
func AiOutlineYoutube() icons.IsIcon          { return newIcon(outlinedIcon, "youtube") }
func AiOutlineYuque() icons.IsIcon            { return newIcon(outlinedIcon, "yuque") }
func AiOutlineZhihu() icons.IsIcon            { return newIcon(outlinedIcon, "zhihu") }
func AiOutlineZoomIn() icons.IsIcon           { return newIcon(outlinedIcon, "zoom-in") }
func AiOutlineZoomOut() icons.IsIcon          { return newIcon(outlinedIcon, "zoom-out") }
