package ai

import "github.com/raitucarp/gomix/icons"

func AiTwotoneAccountBook() icons.IsIcon       { return newIcon(twoToneIcon, "account-book") }
func AiTwotoneAlert() icons.IsIcon             { return newIcon(twoToneIcon, "alert") }
func AiTwotoneApi() icons.IsIcon               { return newIcon(twoToneIcon, "api") }
func AiTwotoneAppstore() icons.IsIcon          { return newIcon(twoToneIcon, "appstore") }
func AiTwotoneAudio() icons.IsIcon             { return newIcon(twoToneIcon, "audio") }
func AiTwotoneBank() icons.IsIcon              { return newIcon(twoToneIcon, "bank") }
func AiTwotoneBell() icons.IsIcon              { return newIcon(twoToneIcon, "bell") }
func AiTwotoneBook() icons.IsIcon              { return newIcon(twoToneIcon, "book") }
func AiTwotoneBoxPlot() icons.IsIcon           { return newIcon(twoToneIcon, "box-plot") }
func AiTwotoneBug() icons.IsIcon               { return newIcon(twoToneIcon, "bug") }
func AiTwotoneBuild() icons.IsIcon             { return newIcon(twoToneIcon, "build") }
func AiTwotoneBulb() icons.IsIcon              { return newIcon(twoToneIcon, "bulb") }
func AiTwotoneCalculator() icons.IsIcon        { return newIcon(twoToneIcon, "calculator") }
func AiTwotoneCalendar() icons.IsIcon          { return newIcon(twoToneIcon, "calendar") }
func AiTwotoneCamera() icons.IsIcon            { return newIcon(twoToneIcon, "camera") }
func AiTwotoneCar() icons.IsIcon               { return newIcon(twoToneIcon, "car") }
func AiTwotoneCarryOut() icons.IsIcon          { return newIcon(twoToneIcon, "carry-out") }
func AiTwotoneCheckCircle() icons.IsIcon       { return newIcon(twoToneIcon, "check-circle") }
func AiTwotoneCheckSquare() icons.IsIcon       { return newIcon(twoToneIcon, "check-square") }
func AiTwotoneCiCircle() icons.IsIcon          { return newIcon(twoToneIcon, "ci-circle") }
func AiTwotoneCi() icons.IsIcon                { return newIcon(twoToneIcon, "ci") }
func AiTwotoneClockCircle() icons.IsIcon       { return newIcon(twoToneIcon, "clock-circle") }
func AiTwotoneCloseCircle() icons.IsIcon       { return newIcon(twoToneIcon, "close-circle") }
func AiTwotoneCloseSquare() icons.IsIcon       { return newIcon(twoToneIcon, "close-square") }
func AiTwotoneCloud() icons.IsIcon             { return newIcon(twoToneIcon, "cloud") }
func AiTwotoneCode() icons.IsIcon              { return newIcon(twoToneIcon, "code") }
func AiTwotoneCompass() icons.IsIcon           { return newIcon(twoToneIcon, "compass") }
func AiTwotoneContacts() icons.IsIcon          { return newIcon(twoToneIcon, "contacts") }
func AiTwotoneContainer() icons.IsIcon         { return newIcon(twoToneIcon, "container") }
func AiTwotoneControl() icons.IsIcon           { return newIcon(twoToneIcon, "control") }
func AiTwotoneCopy() icons.IsIcon              { return newIcon(twoToneIcon, "copy") }
func AiTwotoneCopyrightCircle() icons.IsIcon   { return newIcon(twoToneIcon, "copyright-circle") }
func AiTwotoneCopyright() icons.IsIcon         { return newIcon(twoToneIcon, "copyright") }
func AiTwotoneCreditCard() icons.IsIcon        { return newIcon(twoToneIcon, "credit-card") }
func AiTwotoneCrown() icons.IsIcon             { return newIcon(twoToneIcon, "crown") }
func AiTwotoneCustomerService() icons.IsIcon   { return newIcon(twoToneIcon, "customer-service") }
func AiTwotoneDashboard() icons.IsIcon         { return newIcon(twoToneIcon, "dashboard") }
func AiTwotoneDatabase() icons.IsIcon          { return newIcon(twoToneIcon, "database") }
func AiTwotoneDelete() icons.IsIcon            { return newIcon(twoToneIcon, "delete") }
func AiTwotoneDiff() icons.IsIcon              { return newIcon(twoToneIcon, "diff") }
func AiTwotoneDislike() icons.IsIcon           { return newIcon(twoToneIcon, "dislike") }
func AiTwotoneDollarCircle() icons.IsIcon      { return newIcon(twoToneIcon, "dollar-circle") }
func AiTwotoneDollar() icons.IsIcon            { return newIcon(twoToneIcon, "dollar") }
func AiTwotoneDownCircle() icons.IsIcon        { return newIcon(twoToneIcon, "down-circle") }
func AiTwotoneDownSquare() icons.IsIcon        { return newIcon(twoToneIcon, "down-square") }
func AiTwotoneEdit() icons.IsIcon              { return newIcon(twoToneIcon, "edit") }
func AiTwotoneEnvironment() icons.IsIcon       { return newIcon(twoToneIcon, "environment") }
func AiTwotoneEuroCircle() icons.IsIcon        { return newIcon(twoToneIcon, "euro-circle") }
func AiTwotoneEuro() icons.IsIcon              { return newIcon(twoToneIcon, "euro") }
func AiTwotoneExclamationCircle() icons.IsIcon { return newIcon(twoToneIcon, "exclamation-circle") }
func AiTwotoneExperiment() icons.IsIcon        { return newIcon(twoToneIcon, "experiment") }
func AiTwotoneEyeInvisible() icons.IsIcon      { return newIcon(twoToneIcon, "eye-invisible") }
func AiTwotoneEye() icons.IsIcon               { return newIcon(twoToneIcon, "eye") }
func AiTwotoneFileAdd() icons.IsIcon           { return newIcon(twoToneIcon, "file-add") }
func AiTwotoneFileExcel() icons.IsIcon         { return newIcon(twoToneIcon, "file-excel") }
func AiTwotoneFileExclamation() icons.IsIcon   { return newIcon(twoToneIcon, "file-exclamation") }
func AiTwotoneFileImage() icons.IsIcon         { return newIcon(twoToneIcon, "file-image") }
func AiTwotoneFileMarkdown() icons.IsIcon      { return newIcon(twoToneIcon, "file-markdown") }
func AiTwotoneFilePdf() icons.IsIcon           { return newIcon(twoToneIcon, "file-pdf") }
func AiTwotoneFilePpt() icons.IsIcon           { return newIcon(twoToneIcon, "file-ppt") }
func AiTwotoneFileText() icons.IsIcon          { return newIcon(twoToneIcon, "file-text") }
func AiTwotoneFileUnknown() icons.IsIcon       { return newIcon(twoToneIcon, "file-unknown") }
func AiTwotoneFileWord() icons.IsIcon          { return newIcon(twoToneIcon, "file-word") }
func AiTwotoneFileZip() icons.IsIcon           { return newIcon(twoToneIcon, "file-zip") }
func AiTwotoneFile() icons.IsIcon              { return newIcon(twoToneIcon, "file") }
func AiTwotoneFilter() icons.IsIcon            { return newIcon(twoToneIcon, "filter") }
func AiTwotoneFire() icons.IsIcon              { return newIcon(twoToneIcon, "fire") }
func AiTwotoneFlag() icons.IsIcon              { return newIcon(twoToneIcon, "flag") }
func AiTwotoneFolderAdd() icons.IsIcon         { return newIcon(twoToneIcon, "folder-add") }
func AiTwotoneFolderOpen() icons.IsIcon        { return newIcon(twoToneIcon, "folder-open") }
func AiTwotoneFolder() icons.IsIcon            { return newIcon(twoToneIcon, "folder") }
func AiTwotoneFrown() icons.IsIcon             { return newIcon(twoToneIcon, "frown") }
func AiTwotoneFund() icons.IsIcon              { return newIcon(twoToneIcon, "fund") }
func AiTwotoneFunnelPlot() icons.IsIcon        { return newIcon(twoToneIcon, "funnel-plot") }
func AiTwotoneGift() icons.IsIcon              { return newIcon(twoToneIcon, "gift") }
func AiTwotoneGold() icons.IsIcon              { return newIcon(twoToneIcon, "gold") }
func AiTwotoneHdd() icons.IsIcon               { return newIcon(twoToneIcon, "hdd") }
func AiTwotoneHeart() icons.IsIcon             { return newIcon(twoToneIcon, "heart") }
func AiTwotoneHighlight() icons.IsIcon         { return newIcon(twoToneIcon, "highlight") }
func AiTwotoneHome() icons.IsIcon              { return newIcon(twoToneIcon, "home") }
func AiTwotoneHourglass() icons.IsIcon         { return newIcon(twoToneIcon, "hourglass") }
func AiTwotoneHtml5() icons.IsIcon             { return newIcon(twoToneIcon, "html5") }
func AiTwotoneIdcard() icons.IsIcon            { return newIcon(twoToneIcon, "idcard") }
func AiTwotoneInfoCircle() icons.IsIcon        { return newIcon(twoToneIcon, "info-circle") }
func AiTwotoneInsurance() icons.IsIcon         { return newIcon(twoToneIcon, "insurance") }
func AiTwotoneInteraction() icons.IsIcon       { return newIcon(twoToneIcon, "interaction") }
func AiTwotoneLayout() icons.IsIcon            { return newIcon(twoToneIcon, "layout") }
func AiTwotoneLeftCircle() icons.IsIcon        { return newIcon(twoToneIcon, "left-circle") }
func AiTwotoneLeftSquare() icons.IsIcon        { return newIcon(twoToneIcon, "left-square") }
func AiTwotoneLike() icons.IsIcon              { return newIcon(twoToneIcon, "like") }
func AiTwotoneLock() icons.IsIcon              { return newIcon(twoToneIcon, "lock") }
func AiTwotoneMail() icons.IsIcon              { return newIcon(twoToneIcon, "mail") }
func AiTwotoneMedicineBox() icons.IsIcon       { return newIcon(twoToneIcon, "medicine-box") }
func AiTwotoneMeh() icons.IsIcon               { return newIcon(twoToneIcon, "meh") }
func AiTwotoneMessage() icons.IsIcon           { return newIcon(twoToneIcon, "message") }
func AiTwotoneMinusCircle() icons.IsIcon       { return newIcon(twoToneIcon, "minus-circle") }
func AiTwotoneMinusSquare() icons.IsIcon       { return newIcon(twoToneIcon, "minus-square") }
func AiTwotoneMobile() icons.IsIcon            { return newIcon(twoToneIcon, "mobile") }
func AiTwotoneMoneyCollect() icons.IsIcon      { return newIcon(twoToneIcon, "money-collect") }
func AiTwotoneNotification() icons.IsIcon      { return newIcon(twoToneIcon, "notification") }
func AiTwotonePauseCircle() icons.IsIcon       { return newIcon(twoToneIcon, "pause-circle") }
func AiTwotonePhone() icons.IsIcon             { return newIcon(twoToneIcon, "phone") }
func AiTwotonePicture() icons.IsIcon           { return newIcon(twoToneIcon, "picture") }
func AiTwotonePieChart() icons.IsIcon          { return newIcon(twoToneIcon, "pie-chart") }
func AiTwotonePlayCircle() icons.IsIcon        { return newIcon(twoToneIcon, "play-circle") }
func AiTwotonePlaySquare() icons.IsIcon        { return newIcon(twoToneIcon, "play-square") }
func AiTwotonePlusCircle() icons.IsIcon        { return newIcon(twoToneIcon, "plus-circle") }
func AiTwotonePlusSquare() icons.IsIcon        { return newIcon(twoToneIcon, "plus-square") }
func AiTwotonePoundCircle() icons.IsIcon       { return newIcon(twoToneIcon, "pound-circle") }
func AiTwotonePrinter() icons.IsIcon           { return newIcon(twoToneIcon, "printer") }
func AiTwotoneProfile() icons.IsIcon           { return newIcon(twoToneIcon, "profile") }
func AiTwotoneProject() icons.IsIcon           { return newIcon(twoToneIcon, "project") }
func AiTwotonePropertySafety() icons.IsIcon    { return newIcon(twoToneIcon, "property-safety") }
func AiTwotonePushpin() icons.IsIcon           { return newIcon(twoToneIcon, "pushpin") }
func AiTwotoneQuestionCircle() icons.IsIcon    { return newIcon(twoToneIcon, "question-circle") }
func AiTwotoneReconciliation() icons.IsIcon    { return newIcon(twoToneIcon, "reconciliation") }
func AiTwotoneRedEnvelope() icons.IsIcon       { return newIcon(twoToneIcon, "red-envelope") }
func AiTwotoneRest() icons.IsIcon              { return newIcon(twoToneIcon, "rest") }
func AiTwotoneRightCircle() icons.IsIcon       { return newIcon(twoToneIcon, "right-circle") }
func AiTwotoneRightSquare() icons.IsIcon       { return newIcon(twoToneIcon, "right-square") }
func AiTwotoneRocket() icons.IsIcon            { return newIcon(twoToneIcon, "rocket") }
func AiTwotoneSafetyCertificate() icons.IsIcon { return newIcon(twoToneIcon, "safety-certificate") }
func AiTwotoneSave() icons.IsIcon              { return newIcon(twoToneIcon, "save") }
func AiTwotoneSchedule() icons.IsIcon          { return newIcon(twoToneIcon, "schedule") }
func AiTwotoneSecurityScan() icons.IsIcon      { return newIcon(twoToneIcon, "security-scan") }
func AiTwotoneSetting() icons.IsIcon           { return newIcon(twoToneIcon, "setting") }
func AiTwotoneShop() icons.IsIcon              { return newIcon(twoToneIcon, "shop") }
func AiTwotoneShopping() icons.IsIcon          { return newIcon(twoToneIcon, "shopping") }
func AiTwotoneSkin() icons.IsIcon              { return newIcon(twoToneIcon, "skin") }
func AiTwotoneSliders() icons.IsIcon           { return newIcon(twoToneIcon, "sliders") }
func AiTwotoneSmile() icons.IsIcon             { return newIcon(twoToneIcon, "smile") }
func AiTwotoneSnippets() icons.IsIcon          { return newIcon(twoToneIcon, "snippets") }
func AiTwotoneSound() icons.IsIcon             { return newIcon(twoToneIcon, "sound") }
func AiTwotoneStar() icons.IsIcon              { return newIcon(twoToneIcon, "star") }
func AiTwotoneStop() icons.IsIcon              { return newIcon(twoToneIcon, "stop") }
func AiTwotoneSwitcher() icons.IsIcon          { return newIcon(twoToneIcon, "switcher") }
func AiTwotoneTablet() icons.IsIcon            { return newIcon(twoToneIcon, "tablet") }
func AiTwotoneTag() icons.IsIcon               { return newIcon(twoToneIcon, "tag") }
func AiTwotoneTags() icons.IsIcon              { return newIcon(twoToneIcon, "tags") }
func AiTwotoneThunderbolt() icons.IsIcon       { return newIcon(twoToneIcon, "thunderbolt") }
func AiTwotoneTool() icons.IsIcon              { return newIcon(twoToneIcon, "tool") }
func AiTwotoneTrademarkCircle() icons.IsIcon   { return newIcon(twoToneIcon, "trademark-circle") }
func AiTwotoneTrophy() icons.IsIcon            { return newIcon(twoToneIcon, "trophy") }
func AiTwotoneUnlock() icons.IsIcon            { return newIcon(twoToneIcon, "unlock") }
func AiTwotoneUpCircle() icons.IsIcon          { return newIcon(twoToneIcon, "up-circle") }
func AiTwotoneUpSquare() icons.IsIcon          { return newIcon(twoToneIcon, "up-square") }
func AiTwotoneUsb() icons.IsIcon               { return newIcon(twoToneIcon, "usb") }
func AiTwotoneVideoCamera() icons.IsIcon       { return newIcon(twoToneIcon, "video-camera") }
func AiTwotoneWallet() icons.IsIcon            { return newIcon(twoToneIcon, "wallet") }
func AiTwotoneWarning() icons.IsIcon           { return newIcon(twoToneIcon, "warning") }
