package size

type Size string

const (
	Size_000 Size = "--size-000"
	Size_00  Size = "--size-00"
	Size_1   Size = "--size-1"
	Size_2   Size = "--size-2"
	Size_3   Size = "--size-3"
	Size_4   Size = "--size-4"
	Size_5   Size = "--size-5"
	Size_6   Size = "--size-6"
	Size_7   Size = "--size-7"
	Size_8   Size = "--size-8"
	Size_9   Size = "--size-9"
	Size_10  Size = "--size-10"
	Size_11  Size = "--size-11"
	Size_12  Size = "--size-12"
	Size_13  Size = "--size-13"
	Size_14  Size = "--size-14"
	Size_15  Size = "--size-15"

	Size_Px_000 Size = "--size-px-000"
	Size_Px_00  Size = "--size-px-00"
	Size_Px_1   Size = "--size-px-1"
	Size_Px_2   Size = "--size-px-2"
	Size_Px_3   Size = "--size-px-3"
	Size_Px_4   Size = "--size-px-4"
	Size_Px_5   Size = "--size-px-5"
	Size_Px_6   Size = "--size-px-6"
	Size_Px_7   Size = "--size-px-7"
	Size_Px_8   Size = "--size-px-8"
	Size_Px_9   Size = "--size-px-9"
	Size_Px_10  Size = "--size-px-10"
	Size_Px_11  Size = "--size-px-11"
	Size_Px_12  Size = "--size-px-12"
	Size_Px_13  Size = "--size-px-13"
	Size_Px_14  Size = "--size-px-14"
	Size_Px_15  Size = "--size-px-15"

	Size_Fluid_1  Size = "--size-fluid-1"
	Size_Fluid_2  Size = "--size-fluid-2"
	Size_Fluid_3  Size = "--size-fluid-3"
	Size_Fluid_4  Size = "--size-fluid-4"
	Size_Fluid_5  Size = "--size-fluid-5"
	Size_Fluid_6  Size = "--size-fluid-6"
	Size_Fluid_7  Size = "--size-fluid-7"
	Size_Fluid_8  Size = "--size-fluid-8"
	Size_Fluid_9  Size = "--size-fluid-9"
	Size_Fluid_10 Size = "--size-fluid-10"

	Size_Content_1 Size = "--size-content-1"
	Size_Content_2 Size = "--size-content-2"
	Size_Content_3 Size = "--size-content-3"

	Size_Header_1 Size = "--size-header-1"
	Size_Header_2 Size = "--size-header-2"
	Size_Header_3 Size = "--size-header-3"

	Size_Relative_000 Size = "--size-relative-000"
	Size_Relative_00  Size = "--size-relative-00"
	Size_Relative_1   Size = "--size-relative-1"
	Size_Relative_2   Size = "--size-relative-2"
	Size_Relative_3   Size = "--size-relative-3"
	Size_Relative_4   Size = "--size-relative-4"
	Size_Relative_5   Size = "--size-relative-5"
	Size_Relative_6   Size = "--size-relative-6"
	Size_Relative_7   Size = "--size-relative-7"
	Size_Relative_8   Size = "--size-relative-8"
	Size_Relative_9   Size = "--size-relative-9"
	Size_Relative_10  Size = "--size-relative-10"
	Size_Relative_11  Size = "--size-relative-11"
	Size_Relative_12  Size = "--size-relative-12"
	Size_Relative_13  Size = "--size-relative-13"
	Size_Relative_14  Size = "--size-relative-14"
	Size_Relative_15  Size = "--size-relative-15"
)
